#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
BUNDLE_REPORT = ROOT / 'artifacts' / 'reports' / 'rust_standing_bootstrap_comeback_bundle.json'
BUNDLE_PATCH = ROOT / 'artifacts' / 'patches' / 'rust_standing_bootstrap_comeback_bundle.patch'
OUT_JSON = ROOT / 'artifacts' / 'reports' / 'rust_standing_bootstrap_comeback_bundle_rehearsal.json'
OUT_MD = ROOT / 'docs' / 'RUST_STANDING_BOOTSTRAP_COMEBACK_BUNDLE_REHEARSAL.md'


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _run_apply(cwd: Path, patch_path: Path, check_only: bool) -> tuple[bool, str]:
    cmd = ['git', 'apply']
    if check_only:
        cmd.append('--check')
    cmd.append(str(patch_path))
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    summary = '\n'.join(part for part in [proc.stdout.strip(), proc.stderr.strip()] if part).strip()
    return proc.returncode == 0, summary


def _snapshot_hashes(root: Path, relpaths: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for rel in relpaths:
        path = root / rel
        out[rel] = _sha256_bytes(path.read_bytes()) if path.exists() else 'MISSING'
    return out


def collect() -> dict[str, Any]:
    bundle_report = json.loads(BUNDLE_REPORT.read_text(encoding='utf-8'))
    patch_text = BUNDLE_PATCH.read_text(encoding='utf-8')
    target_files = [str(rel) for rel in bundle_report['target_files']]
    expected_hashes = {str(rel): str(digest) for rel, digest in bundle_report['final_hashes'].items()}

    with tempfile.TemporaryDirectory(prefix='gr_bootstrap_bundle_rehearsal_') as tmp:
        scratch = Path(tmp)
        patch_dst = scratch / BUNDLE_PATCH.relative_to(ROOT)
        patch_dst.parent.mkdir(parents=True, exist_ok=True)
        patch_dst.write_text(patch_text, encoding='utf-8')
        for rel in target_files:
            src = ROOT / rel
            if src.exists():
                dst = scratch / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                dst.write_bytes(src.read_bytes())
        check_ok, check_summary = _run_apply(scratch, patch_dst, True)
        apply_ok = False
        apply_summary = ''
        final_hashes: dict[str, str] = {rel: 'MISSING' for rel in target_files}
        if check_ok:
            apply_ok, apply_summary = _run_apply(scratch, patch_dst, False)
            final_hashes = _snapshot_hashes(scratch, target_files)

    return {
        'tool': 'build_rust_standing_bootstrap_comeback_bundle_rehearsal',
        'source_bundle_report': str(BUNDLE_REPORT.relative_to(ROOT)),
        'source_bundle_patch': str(BUNDLE_PATCH.relative_to(ROOT)),
        'target_files': target_files,
        'summary': {
            'check_ok': check_ok,
            'apply_ok': apply_ok,
            'final_hashes_match_report': final_hashes == expected_hashes,
            'bundle_patch_sha256': _sha256_bytes(patch_text.encode('utf-8')),
        },
        'notes': {
            'check_summary': check_summary,
            'apply_summary': apply_summary,
        },
    }


def render_markdown(report: dict[str, Any]) -> str:
    s = report['summary']
    lines = [
        '# Rust Standing Bootstrap Comeback Bundle Rehearsal',
        '',
        'Generated by `scripts/report/build_rust_standing_bootstrap_comeback_bundle_rehearsal.py`. This scratch-applies the clean-head comeback bundle patch and checks that the landed file hashes match the generated bundle report.',
        '',
        '## Snapshot',
        '',
        f"- source bundle patch: `{report['source_bundle_patch']}`",
        f"- check_ok: `{str(s['check_ok']).lower()}`",
        f"- apply_ok: `{str(s['apply_ok']).lower()}`",
        f"- final_hashes_match_report: `{str(s['final_hashes_match_report']).lower()}`",
        f"- bundle_patch_sha256: `{s['bundle_patch_sha256']}`",
        '',
    ]
    return '\n'.join(lines)


def _check(expected_report: dict[str, Any], expected_markdown: str) -> int:
    if not OUT_JSON.exists() or not OUT_MD.exists():
        print('rust-standing-bootstrap-comeback-bundle-rehearsal: missing report/doc', file=sys.stderr)
        return 1
    if json.loads(OUT_JSON.read_text(encoding='utf-8')) != expected_report:
        print('rust-standing-bootstrap-comeback-bundle-rehearsal: report drift detected', file=sys.stderr)
        return 1
    if OUT_MD.read_text(encoding='utf-8').rstrip('\n') != expected_markdown.rstrip('\n'):
        print('rust-standing-bootstrap-comeback-bundle-rehearsal: markdown drift detected', file=sys.stderr)
        return 1
    print('rust-standing-bootstrap-comeback-bundle-rehearsal: ok clean-head bundle check/apply/hash-match all true')
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    report = collect()
    markdown = render_markdown(report)
    if args.write:
        OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
        OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True) + '\n', encoding='utf-8')
        OUT_MD.write_text(markdown + '\n', encoding='utf-8')
        print(f'wrote {OUT_JSON.relative_to(ROOT)}')
        print(f'wrote {OUT_MD.relative_to(ROOT)}')
        return 0
    return _check(report, markdown)


if __name__ == '__main__':
    raise SystemExit(main())
