#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
CHECKPOINTS_REPORT = ROOT / 'artifacts' / 'reports' / 'rust_standing_bootstrap_checkpoints.json'
CHECKPOINTS_DOC = ROOT / 'docs' / 'RUST_STANDING_BOOTSTRAP_CHECKPOINTS.md'
TOOL_PATH = ROOT / 'scripts' / 'tools' / 'verify_rust_standing_bootstrap_checkpoint.py'
OUT_JSON = ROOT / 'artifacts' / 'reports' / 'rust_standing_bootstrap_checkpoint_verifier.json'
OUT_MD = ROOT / 'docs' / 'RUST_STANDING_BOOTSTRAP_CHECKPOINT_VERIFIER.md'


def _run_tool(*args: str) -> dict[str, Any]:
    proc = subprocess.run(
        ['python3', str(TOOL_PATH), '--report', str(CHECKPOINTS_REPORT), '--json', *args],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise SystemExit(
            'rust-standing-bootstrap-checkpoint-verifier: tool invocation failed\n' + proc.stdout + proc.stderr
        )
    return json.loads(proc.stdout)


def collect() -> tuple[dict[str, Any], str]:
    if not CHECKPOINTS_REPORT.exists() or not CHECKPOINTS_DOC.exists() or not TOOL_PATH.exists():
        raise SystemExit('rust-standing-bootstrap-checkpoint-verifier: missing prerequisites')
    checkpoints = json.loads(CHECKPOINTS_REPORT.read_text(encoding='utf-8'))
    live = _run_tool('--target-root', str(ROOT), '--expect-state-id', 'clean_head')
    state_rows = []
    checkpoint_rows = []
    for state in checkpoints['state_checkpoints']:
        state_rows.append(
            {
                'state_id': state['state_id'],
                'label': state['label'],
                'observed_combined_hash': state['observed_combined_hash'],
                'direct_verify_command': (
                    'python3 scripts/tools/verify_rust_standing_bootstrap_checkpoint.py '
                    f"--target-root . --expect-state-id {state['state_id']} --expect-combined-hash {state['observed_combined_hash']} --json"
                ),
                'checkpoint_count': len(state['checkpoints']),
            }
        )
        for cp in state['checkpoints']:
            checkpoint_rows.append(
                {
                    'from_state_id': state['state_id'],
                    'step_index': cp['step_index'],
                    'apply_command': cp['apply_command'],
                    'expected_state_id': cp['expected_state_id'],
                    'expected_combined_hash': cp['expected_combined_hash'],
                    'route_verify_command': (
                        'python3 scripts/tools/verify_rust_standing_bootstrap_checkpoint.py '
                        f"--target-root . --from-state-id {state['state_id']} --step-index {cp['step_index']} --json"
                    ),
                }
            )
    report = {
        'tool': 'build_rust_standing_bootstrap_checkpoint_verifier',
        'source_report': str(CHECKPOINTS_REPORT.relative_to(ROOT)),
        'source_doc': str(CHECKPOINTS_DOC.relative_to(ROOT)),
        'verifier_tool': str(TOOL_PATH.relative_to(ROOT)),
        'summary': {
            'recognized_state_count': len(state_rows),
            'state_with_checkpoints_count': len([row for row in state_rows if row['checkpoint_count']]),
            'total_checkpoint_count': len(checkpoint_rows),
            'live_root_verified': live['verified'],
            'live_root_matched_state_id': live['matched_state_id'],
            'live_root_observed_combined_hash': live['observed_combined_hash'],
            'tool_direct_invocation': 'python3 scripts/tools/verify_rust_standing_bootstrap_checkpoint.py --target-root . --expect-state-id clean_head --json',
            'tool_route_invocation_example': 'python3 scripts/tools/verify_rust_standing_bootstrap_checkpoint.py --target-root . --from-state-id repair_only --step-index 1 --json',
        },
        'state_rows': state_rows,
        'checkpoint_rows': checkpoint_rows,
        'headline_findings': [
            'The archive now has one exact verifier for both checkpoint modes: direct exact-state verification and route-step verification derived from the checkpoints card.',
            'The live clean-head archive root already verifies directly as clean_head, so the verifier is usable before the first Rust-capable machine lands any patch.',
            'Every recorded checkpoint now has a replayable one-command proof surface instead of only a documented expected hash.',
        ],
    }
    return report, render_markdown(report)


def render_markdown(report: dict[str, Any]) -> str:
    s = report['summary']
    lines = [
        '# Rust Standing Bootstrap Checkpoint Verifier',
        '',
        'Generated by `scripts/report/build_rust_standing_bootstrap_checkpoint_verifier.py`. This turns the checkpoints card into an exact verifier tool: it can either prove a checkout matches a named recognized bootstrap state directly, or prove that a just-applied checkpoint landed the exact expected post-step state and combined hash.',
        '',
        '## Snapshot',
        '',
        f"- recognized_state_count: `{s['recognized_state_count']}`",
        f"- state_with_checkpoints_count: `{s['state_with_checkpoints_count']}`",
        f"- total_checkpoint_count: `{s['total_checkpoint_count']}`",
        f"- live_root_verified: `{str(s['live_root_verified']).lower()}`",
        f"- live_root_matched_state_id: `{s['live_root_matched_state_id']}`",
        f"- live_root_observed_combined_hash: `{s['live_root_observed_combined_hash']}`",
        f"- direct invocation: `{s['tool_direct_invocation']}`",
        f"- route-step invocation example: `{s['tool_route_invocation_example']}`",
        '',
        '## What this buys the inheritor',
        '',
        '- The checkpoints card no longer requires manual hash comparison after each patch. The verifier can fail fast with a nonzero exit code when the checkout is not the expected exact state.',
        '- Direct mode supports “tell me I am exactly at `repair_guard` (or `final_full`)”. Route-step mode supports “I started from `repair_only`, just applied step 1, prove I am now at the exact checkpoint the card promised.”',
        '- The tool stays state-aware: it reports best partial matches and differing files when verification fails, so a bad landing does not collapse into a silent mismatch.',
        '',
        '## Direct exact-state verification commands',
        '',
        '| state | checkpoints | direct verify command |',
        '|---|---:|---|',
    ]
    for row in report['state_rows']:
        lines.append(f"| `{row['state_id']}` | {row['checkpoint_count']} | `{row['direct_verify_command']}` |")
    lines.extend([
        '',
        '## Route-step verification commands',
        '',
        '| from state | step | expected state | verify command |',
        '|---|---:|---|---|',
    ])
    for row in report['checkpoint_rows']:
        lines.append(
            f"| `{row['from_state_id']}` | {row['step_index']} | `{row['expected_state_id']}` | `{row['route_verify_command']}` |"
        )
    lines.extend([
        '',
        '## Safe operational reading',
        '',
        '1. Before applying anything, use the state selector or checkpoints tool to identify the exact starting state.',
        '2. After each bootstrap apply step, run the matching route-step verifier command from this card. Treat any nonzero exit as a real checkpoint miss until explained.',
        '3. Once the verifier reports exact `final_full`, stop applying bootstrap patches and switch to `emit_rust_standing_bootstrap_verification_ladder.py` for the cheapest Rust witness sequence.',
    ])
    return '\n'.join(lines)


def _check(expected_report: dict[str, Any], expected_markdown: str) -> int:
    if not OUT_JSON.exists() or not OUT_MD.exists():
        print('rust-standing-bootstrap-checkpoint-verifier: missing report/doc', file=sys.stderr)
        return 1
    if json.loads(OUT_JSON.read_text(encoding='utf-8')) != expected_report:
        print('rust-standing-bootstrap-checkpoint-verifier: report drift detected', file=sys.stderr)
        return 1
    if OUT_MD.read_text(encoding='utf-8').rstrip('\n') != expected_markdown.rstrip('\n'):
        print('rust-standing-bootstrap-checkpoint-verifier: markdown drift detected', file=sys.stderr)
        return 1
    print('rust-standing-bootstrap-checkpoint-verifier: ok direct and route-step verification surfaces remain reproducible')
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    report, markdown = collect()
    if args.write:
        OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
        OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True) + '\n', encoding='utf-8')
        OUT_MD.write_text(markdown + '\n', encoding='utf-8')
        print(f'wrote {OUT_JSON.relative_to(ROOT)}')
        print(f'wrote {OUT_MD.relative_to(ROOT)}')
        return 0
    return _check(report, markdown)


if __name__ == '__main__':
    raise SystemExit(main())
