#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

from build_rust_external_test_queue import build_queue
from build_rust_lift_bundle_plan import build_report as build_bundle_plan

ROOT = Path(__file__).resolve().parents[2]
OUT_JSON = ROOT / 'artifacts' / 'reports' / 'rust_external_test_patch_shards.json'
OUT_MD = ROOT / 'docs' / 'RUST_EXTERNAL_TEST_PATCH_SHARDS.md'
OUT_DIR = ROOT / 'artifacts' / 'patches' / 'rust_external_test_shards'

BAND_WEIGHT = {
    'lift_first': 0,
    'externalize_now': 1,
    'broaden_after_lift': 2,
}
LANE_MIX_WEIGHT = {
    'probe_run_only': 0,
    'dual_lane': 1,
    'metamorphic_suite_only': 2,
}


def to_snake(text: str) -> str:
    cleaned = re.sub(r'[^a-zA-Z0-9]+', '_', text)
    cleaned = re.sub(r'_+', '_', cleaned).strip('_')
    if not cleaned:
        return 'shard'
    lowered = cleaned.lower()
    if lowered[0].isdigit():
        lowered = f'shard_{lowered}'
    return lowered


def _ensure_trailing_newline(text: str) -> str:
    return text if text.endswith('\n') else text + '\n'


def _added_lines_count(patch_text: str) -> int:
    count = 0
    for line in patch_text.splitlines():
        if line.startswith('+++') or line.startswith('@@'):
            continue
        if line.startswith('+'):
            count += 1
    return count


def section_markers(seed_path: str) -> tuple[str, str]:
    slug = to_snake(Path(seed_path).stem)
    begin = f'// --- BEGIN blocked-rust external test shard: {slug} (generated) ---'
    end = f'// --- END blocked-rust external test shard: {slug} (generated) ---'
    return begin, end


def bundle_order_key(bundle: dict[str, object]) -> tuple[object, ...]:
    rows = bundle['rows']
    min_band = min(BAND_WEIGHT[str(row['lift_band'])] for row in rows)
    lane_mix = LANE_MIX_WEIGHT[str(bundle['lane_mix'])]
    first_variant = min(str(row['variant']) for row in rows)
    return (min_band, lane_mix, str(bundle['seed_path']), first_variant)


def build_report() -> tuple[dict[str, object], dict[str, str]]:
    bundle_plan = build_bundle_plan()
    queue = build_queue()
    hints_by_test = {str(row['proposed_test_name']): str(row['future_cargo_hint']) for row in queue['entries']}

    ordered_bundles = sorted(bundle_plan['entries'], key=bundle_order_key)
    file_state: dict[str, str] = {}
    for target_file in sorted({str(block['target_file']) for bundle in ordered_bundles for block in bundle['lane_snippets']}):
        file_state[target_file] = _ensure_trailing_newline((ROOT / target_file).read_text(encoding='utf-8'))

    entries: list[dict[str, object]] = []
    patch_files: dict[str, str] = {}
    band_mix_counts = {'lift_first': 0, 'externalize_now': 0, 'broaden_after_lift': 0}
    total_added_lines = 0
    total_patch_bytes = 0

    for index, bundle in enumerate(ordered_bundles, start=1):
        seed_path = str(bundle['seed_path'])
        slug = to_snake(Path(seed_path).stem)
        patch_name = f'{index:02d}_{slug}.patch'
        patch_rel = f'artifacts/patches/rust_external_test_shards/{patch_name}'
        begin_marker, end_marker = section_markers(seed_path)
        patch_parts: list[str] = []
        affected_targets: list[str] = []
        helper_names: list[str] = []
        test_names: list[str] = []
        lane_names: list[str] = []
        bundle_bands = sorted({str(row['lift_band']) for row in bundle['rows']}, key=lambda band: BAND_WEIGHT[band])
        for band in bundle_bands:
            band_mix_counts[band] += 1

        for lane_block in sorted(bundle['lane_snippets'], key=lambda row: (str(row['target_file']), str(row['lane']))):
            target_file = str(lane_block['target_file'])
            original = file_state[target_file]
            helper_names.append(str(bundle['shared_helper_name']))
            lane_names.append(str(lane_block['lane']))
            test_names.extend(str(name) for name in lane_block['test_names'])
            affected_targets.append(target_file)

            append_lines = [
                '',
                begin_marker,
                f'// Generated by scripts/report/build_rust_external_test_patch_shards.py as shard {index:02d}.',
                f'// Seed fixture: {seed_path}',
                '',
            ]
            append_lines.extend(str(bundle['helper_snippet']).splitlines())
            append_lines.append('')
            for snippet in lane_block['snippets']:
                append_lines.extend(str(snippet).splitlines())
                append_lines.append('')
            append_lines.append(end_marker)
            append_lines.append('')
            patched = original + '\n'.join(append_lines)
            file_state[target_file] = patched

            diff_lines = list(
                difflib.unified_diff(
                    original.splitlines(keepends=True),
                    patched.splitlines(keepends=True),
                    fromfile=f'a/{target_file}',
                    tofile=f'b/{target_file}',
                    lineterm='',
                )
            )
            patch_parts.append(''.join(line if line.endswith('\n') else line + '\n' for line in diff_lines))

        patch_text = ''.join(patch_parts)
        patch_files[patch_rel] = patch_text
        added_lines = _added_lines_count(patch_text)
        patch_bytes = len(patch_text.encode('utf-8'))
        total_added_lines += added_lines
        total_patch_bytes += patch_bytes
        unique_test_names = sorted(set(test_names))
        unique_helper_names = sorted(set(helper_names))
        unique_lanes = sorted(set(lane_names))
        unique_targets = sorted(set(affected_targets))
        cargo_hints = [hints_by_test[name] for name in unique_test_names if name in hints_by_test]
        entries.append({
            'series_index': index,
            'patch_path': patch_rel,
            'seed_path': seed_path,
            'bundle_strategy': str(bundle['bundle_strategy']),
            'lane_mix': str(bundle['lane_mix']),
            'lift_bands': bundle_bands,
            'rows': bundle['rows'],
            'target_files': unique_targets,
            'lanes': unique_lanes,
            'helper_names': unique_helper_names,
            'test_names': unique_test_names,
            'future_cargo_hints': cargo_hints,
            'added_lines': added_lines,
            'patch_hunks': patch_text.count('@@'),
            'patch_bytes': patch_bytes,
            'patch_preview': patch_text.splitlines()[:24],
            'apply_hint': f'git apply {patch_rel}',
            'section_begin': begin_marker,
            'section_end': end_marker,
        })

    series_paths = [entry['patch_path'] for entry in entries]
    apply_steps = [f'git apply {path}' for path in series_paths]
    return ({
        'metadata': {
            'inventory_version': '2026-03-23.rust_external_test_patch_shards.v1',
            'crate': 'gr_engine',
            'source_reports': [
                'artifacts/reports/rust_external_test_queue.json',
                'artifacts/reports/rust_lift_bundle_plan.json',
                'artifacts/reports/rust_external_test_patchset.json',
            ],
            'patch_directory': OUT_DIR.relative_to(ROOT).as_posix(),
        },
        'summary': {
            'shard_count': len(entries),
            'target_file_count': len({target for entry in entries for target in entry['target_files']}),
            'total_test_count': sum(len(entry['test_names']) for entry in entries),
            'total_helper_count': sum(len(entry['helper_names']) for entry in entries),
            'total_added_lines': total_added_lines,
            'total_patch_bytes': total_patch_bytes,
            'lane_mix_counts': {
                'probe_run_only': sum(1 for entry in entries if entry['lane_mix'] == 'probe_run_only'),
                'dual_lane': sum(1 for entry in entries if entry['lane_mix'] == 'dual_lane'),
                'metamorphic_suite_only': sum(1 for entry in entries if entry['lane_mix'] == 'metamorphic_suite_only'),
            },
            'lift_band_bundle_counts': band_mix_counts,
            'cumulative_apply_hint': ' && '.join(apply_steps),
        },
        'series': {
            'patch_paths': series_paths,
            'apply_steps': apply_steps,
            'bundle_order_basis': 'min lift band, lane-mix complexity, seed path',
        },
        'entries': entries,
    }, patch_files)


def render_markdown(report: dict[str, object]) -> str:
    summary = report['summary']
    series = report['series']
    lines = [
        '# Rust External Test Patch Shards',
        '',
        'Generated by `scripts/report/build_rust_external_test_patch_shards.py`. This turns the unified blocked-Rust comeback diff into an ordered cumulative patch series so the next Rust-capable inheritor can land the external-test lift in smaller replayable chunks.',
        '',
        '## Snapshot',
        '',
        '- crate: `gr_engine`',
        f"- shard_count: {summary['shard_count']}",
        f"- target_file_count: {summary['target_file_count']}",
        f"- total_test_count: {summary['total_test_count']}",
        f"- total_helper_count: {summary['total_helper_count']}",
        f"- total_added_lines: {summary['total_added_lines']}",
        f"- total_patch_bytes: {summary['total_patch_bytes']}",
        f"- probe_run_only shards: {summary['lane_mix_counts']['probe_run_only']}",
        f"- dual_lane shards: {summary['lane_mix_counts']['dual_lane']}",
        f"- metamorphic_suite_only shards: {summary['lane_mix_counts']['metamorphic_suite_only']}",
        f"- lift_first bundle shards: {summary['lift_band_bundle_counts']['lift_first']}",
        f"- externalize_now bundle shards: {summary['lift_band_bundle_counts']['externalize_now']}",
        f"- broaden_after_lift bundle shards: {summary['lift_band_bundle_counts']['broaden_after_lift']}",
        '',
        '## Apply order',
        '',
        'Apply these shards in order on a Rust-capable machine. Each patch is cumulative against the state produced by the previous shard, not a standalone alternative patch.',
        '',
    ]
    for step in series['apply_steps']:
        lines.append(f'- `{step}`')
    lines.extend([
        '',
        f"Combined apply hint: `{summary['cumulative_apply_hint']}`",
        '',
        '## Shards',
        '',
        '| # | patch | lane mix | lift bands | tests | target files |',
        '|---:|---|---|---|---:|---|',
    ])
    for entry in report['entries']:
        lines.append(
            f"| {entry['series_index']} | `{entry['patch_path']}` | `{entry['lane_mix']}` | `{', '.join(entry['lift_bands'])}` | {len(entry['test_names'])} | `{', '.join(entry['target_files'])}` |"
        )
    lines.extend(['', '## Detailed shards', ''])
    for entry in report['entries']:
        row_labels = ', '.join(f"`{row['family']}/{row['variant']}`" for row in entry['rows'])
        lines.extend([
            f"### Shard {entry['series_index']:02d} — `{entry['seed_path']}`",
            '',
            f"- patch_path: `{entry['patch_path']}`",
            f"- lane_mix: `{entry['lane_mix']}`",
            f"- bundle_strategy: `{entry['bundle_strategy']}`",
            f"- lift_bands: `{', '.join(entry['lift_bands'])}`",
            f"- target_files: `{', '.join(entry['target_files'])}`",
            f"- helper_names: {', '.join(f'`{name}`' for name in entry['helper_names'])}",
            f"- test_names: {', '.join(f'`{name}`' for name in entry['test_names'])}",
            f"- row coverage: {row_labels}",
            f"- added_lines: {entry['added_lines']}",
            f"- patch_hunks: {entry['patch_hunks']}",
            f"- patch_bytes: {entry['patch_bytes']}",
            f"- apply_hint: `{entry['apply_hint']}`",
            '',
            'Future cargo hints:',
            '',
        ])
        for hint in entry['future_cargo_hints']:
            lines.append(f'- `{hint}`')
        lines.extend([
            '',
            'Patch preview:',
            '',
            '```diff',
            '\n'.join(entry['patch_preview']),
            '```',
            '',
        ])
    return '\n'.join(lines).rstrip() + '\n'


def _report_without_previews(report: dict[str, object]) -> dict[str, object]:
    cooked = json.loads(json.dumps(report))
    return cooked


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description='Build an ordered cumulative patch-shard series for the blocked-Rust external-test comeback.')
    parser.add_argument('--write', action='store_true', help='write outputs instead of diff-checking them')
    args = parser.parse_args(argv)

    report, patch_files = build_report()
    js = json.dumps(_report_without_previews(report), indent=2, sort_keys=True) + '\n'
    md = render_markdown(report)

    expected_files = {OUT_JSON.relative_to(ROOT).as_posix(): js, OUT_MD.relative_to(ROOT).as_posix(): md, **patch_files}

    if args.write:
        OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
        OUT_MD.parent.mkdir(parents=True, exist_ok=True)
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        for old in OUT_DIR.glob('*.patch'):
            old.unlink()
        OUT_JSON.write_text(js, encoding='utf-8')
        OUT_MD.write_text(md, encoding='utf-8')
        for rel_path, content in patch_files.items():
            full = ROOT / rel_path
            full.parent.mkdir(parents=True, exist_ok=True)
            full.write_text(content, encoding='utf-8')
        print(f'rust-external-test-patch-shards: wrote {OUT_JSON.relative_to(ROOT)}')
        print(f'rust-external-test-patch-shards: wrote {OUT_MD.relative_to(ROOT)}')
        for rel_path in sorted(patch_files):
            print(f'rust-external-test-patch-shards: wrote {rel_path}')
        return 0

    missing = []
    for rel_path in expected_files:
        if not (ROOT / rel_path).exists():
            missing.append(rel_path)
    if missing:
        for rel_path in missing:
            print(f'rust-external-test-patch-shards: missing {rel_path}', file=sys.stderr)
        return 1

    extra_patch_files = [
        p.relative_to(ROOT).as_posix()
        for p in sorted(OUT_DIR.glob('*.patch'))
        if p.relative_to(ROOT).as_posix() not in patch_files
    ]
    if extra_patch_files:
        for rel_path in extra_patch_files:
            print(f'rust-external-test-patch-shards: unexpected shard file {rel_path}', file=sys.stderr)
        return 1

    drift = False
    for rel_path, expected in expected_files.items():
        current = (ROOT / rel_path).read_text(encoding='utf-8')
        if current != expected:
            print(f'rust-external-test-patch-shards: drift detected in {rel_path}; run with --write', file=sys.stderr)
            drift = True
    if drift:
        return 1

    print(f"rust-external-test-patch-shards: ok ({report['summary']['shard_count']} shards)")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
