#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import sys
from collections import defaultdict
from pathlib import Path

from build_rust_external_test_queue import build_queue
from build_rust_lift_bundle_plan import build_report as build_bundle_plan
from build_rust_external_test_patch_shards import bundle_order_key, section_markers

ROOT = Path(__file__).resolve().parents[2]
OUT_JSON = ROOT / 'artifacts' / 'reports' / 'rust_external_test_patchset.json'
OUT_MD = ROOT / 'docs' / 'RUST_EXTERNAL_TEST_PATCHSET.md'
OUT_PATCH = ROOT / 'artifacts' / 'patches' / 'rust_external_test_patchset.patch'


def _ensure_trailing_newline(text: str) -> str:
    return text if text.endswith('\n') else text + '\n'


def _added_lines_count(patch_text: str) -> int:
    count = 0
    for line in patch_text.splitlines():
        if line.startswith('+++') or line.startswith('@@'):
            continue
        if line.startswith('+'):
            count += 1
    return count


def build_report() -> dict[str, object]:
    bundle_plan = build_bundle_plan()
    queue = build_queue()
    hints_by_test = {str(row['proposed_test_name']): str(row['future_cargo_hint']) for row in queue['entries']}

    ordered_bundles = sorted(bundle_plan['entries'], key=bundle_order_key)
    target_files = sorted({str(block['target_file']) for bundle in ordered_bundles for block in bundle['lane_snippets']})
    original_state = {target_file: _ensure_trailing_newline((ROOT / target_file).read_text(encoding='utf-8')) for target_file in target_files}
    file_state = dict(original_state)

    grouped: dict[str, dict[str, object]] = defaultdict(lambda: {
        'lanes': set(),
        'helper_names': [],
        'test_names': [],
        'future_cargo_hints': [],
        'seed_paths': [],
        'bundle_rows': [],
    })

    for bundle_index, bundle in enumerate(ordered_bundles, start=1):
        seed_path = str(bundle['seed_path'])
        begin_marker, end_marker = section_markers(seed_path)
        row_variants = [str(row['variant']) for row in bundle['rows']]

        for lane_block in sorted(bundle['lane_snippets'], key=lambda row: (str(row['target_file']), str(row['lane']))):
            target_file = str(lane_block['target_file'])
            original = file_state[target_file]
            append_lines = [
                '',
                begin_marker,
                f'// Generated by scripts/report/build_rust_external_test_patch_shards.py as shard {bundle_index:02d}.',
                f'// Seed fixture: {seed_path}',
                '',
            ]
            append_lines.extend(str(bundle['helper_snippet']).splitlines())
            append_lines.append('')
            for snippet in lane_block['snippets']:
                append_lines.extend(str(snippet).splitlines())
                append_lines.append('')
            append_lines.append(end_marker)
            append_lines.append('')
            file_state[target_file] = original + '\n'.join(append_lines)

            info = grouped[target_file]
            info['lanes'].add(str(lane_block['lane']))
            info['helper_names'].append(str(bundle['shared_helper_name']))
            info['test_names'].extend(str(name) for name in lane_block['test_names'])
            info['future_cargo_hints'].extend(
                hint for hint in (hints_by_test.get(str(name)) for name in lane_block['test_names']) if hint
            )
            if seed_path not in info['seed_paths']:
                info['seed_paths'].append(seed_path)
            info['bundle_rows'].append({
                'seed_path': seed_path,
                'variants': row_variants,
                'bundle_strategy': str(bundle['bundle_strategy']),
                'lane': str(lane_block['lane']),
                'section_begin': begin_marker,
                'section_end': end_marker,
            })

    entries: list[dict[str, object]] = []
    combined_patch_parts: list[str] = []
    total_helpers = 0
    total_tests = 0
    total_added_lines = 0

    for target_file in target_files:
        original = original_state[target_file]
        patched = file_state[target_file]
        diff_lines = list(
            difflib.unified_diff(
                original.splitlines(keepends=True),
                patched.splitlines(keepends=True),
                fromfile=f'a/{target_file}',
                tofile=f'b/{target_file}',
                lineterm='',
            )
        )
        patch_text = ''.join(line if line.endswith('\n') else line + '\n' for line in diff_lines)
        combined_patch_parts.append(patch_text)
        added_lines = _added_lines_count(patch_text)
        info = grouped[target_file]
        helper_names = list(dict.fromkeys(info['helper_names']))
        test_names = list(dict.fromkeys(info['test_names']))
        future_hints = list(dict.fromkeys(info['future_cargo_hints']))
        lanes = sorted(info['lanes'])
        total_helpers += len(helper_names)
        total_tests += len(test_names)
        total_added_lines += added_lines

        entries.append({
            'target_file': target_file,
            'lanes': lanes,
            'lane_mix': 'dual_lane' if len(lanes) > 1 else (lanes[0] if lanes else 'none'),
            'helper_count': len(helper_names),
            'helper_names': helper_names,
            'test_count': len(test_names),
            'test_names': test_names,
            'future_cargo_hints': future_hints,
            'seed_paths': info['seed_paths'],
            'bundle_rows': info['bundle_rows'],
            'added_lines': added_lines,
            'patch_hunks': patch_text.count('@@'),
            'patch_preview': patch_text.splitlines()[:24],
            'patch_path': OUT_PATCH.relative_to(ROOT).as_posix(),
        })

    combined_patch = ''.join(combined_patch_parts)
    return {
        'metadata': {
            'inventory_version': '2026-03-23.rust_external_test_patchset.v2',
            'crate': 'gr_engine',
            'source_reports': [
                'artifacts/reports/rust_external_test_queue.json',
                'artifacts/reports/rust_lift_bundle_plan.json',
                'artifacts/reports/rust_external_test_patch_shards.json',
            ],
            'patch_path': OUT_PATCH.relative_to(ROOT).as_posix(),
            'alignment_note': 'monolithic patchset preserves the same landing order and block markers as the cumulative shard series',
        },
        'summary': {
            'target_file_count': len(entries),
            'helper_count': total_helpers,
            'test_count': total_tests,
            'added_lines': total_added_lines,
            'patch_hunks': combined_patch.count('@@'),
            'patch_bytes': len(combined_patch.encode('utf-8')),
            'probe_run_targets': sum(1 for entry in entries if entry['target_file'].endswith('probe_run.rs')),
            'metamorphic_targets': sum(1 for entry in entries if entry['target_file'].endswith('metamorphic_suite.rs')),
        },
        'entries': entries,
        'patch': {
            'artifact_path': OUT_PATCH.relative_to(ROOT).as_posix(),
            'apply_hint': f'git apply {OUT_PATCH.relative_to(ROOT).as_posix()}',
            'fallback_hint': f'patch -p1 < {OUT_PATCH.relative_to(ROOT).as_posix()}',
            'text': combined_patch,
        },
    }


def render_markdown(report: dict[str, object]) -> str:
    s = report['summary']
    patch = report['patch']
    lines = [
        '# Rust External Test Patchset',
        '',
        'Generated by `scripts/report/build_rust_external_test_patchset.py`. This is the single-file replayable handoff for the blocked-Rust comeback. It now preserves the same landing order and per-seed block markers as the cumulative shard series, so both apply paths can land on the same final test files.',
        '',
        '## Snapshot',
        '',
        '- crate: `gr_engine`',
        f"- target_file_count: {s['target_file_count']}",
        f"- helper_count: {s['helper_count']}",
        f"- test_count: {s['test_count']}",
        f"- added_lines: {s['added_lines']}",
        f"- patch_hunks: {s['patch_hunks']}",
        f"- patch_bytes: {s['patch_bytes']}",
        f"- patch artifact: `{patch['artifact_path']}`",
        f"- apply_hint: `{patch['apply_hint']}`",
        f"- fallback_hint: `{patch['fallback_hint']}`",
        '',
        '## Target files',
        '',
        '| target file | lanes | helpers | tests | added lines |',
        '|---|---|---:|---:|---:|',
    ]
    for entry in report['entries']:
        lines.append(
            f"| `{entry['target_file']}` | `{', '.join(entry['lanes'])}` | {entry['helper_count']} | {entry['test_count']} | {entry['added_lines']} |"
        )
    lines.extend(['', '## Patch targets', ''])
    for entry in report['entries']:
        lines.extend([
            f"### `{entry['target_file']}`",
            '',
            f"- lanes: `{', '.join(entry['lanes'])}`",
            f"- helper_names: {', '.join(f'`{name}`' for name in entry['helper_names'])}",
            f"- test_names: {', '.join(f'`{name}`' for name in entry['test_names'])}",
            f"- seed_paths: {', '.join(f'`{path}`' for path in entry['seed_paths'])}",
            f"- added_lines: {entry['added_lines']}",
            f"- patch_hunks: {entry['patch_hunks']}",
            '',
            'Future cargo hints:',
            '',
        ])
        for hint in entry['future_cargo_hints']:
            lines.append(f'- `{hint}`')
        lines.extend([
            '',
            'Patch preview:',
            '',
            '```diff',
            '\n'.join(entry['patch_preview']),
            '```',
            '',
        ])
    return '\n'.join(lines).rstrip() + '\n'


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description='Build a replayable unified patch for the Rust external-test lift queue.')
    parser.add_argument('--write', action='store_true', help='write outputs instead of diff-checking them')
    args = parser.parse_args(argv)

    report = build_report()
    js = json.dumps({k: v for k, v in report.items() if k != 'patch'} | {'patch': {'artifact_path': report['patch']['artifact_path'], 'apply_hint': report['patch']['apply_hint'], 'fallback_hint': report['patch']['fallback_hint']}}, indent=2, sort_keys=True) + '\n'
    md = render_markdown(report)
    patch_text = report['patch']['text']

    if args.write:
        OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
        OUT_MD.parent.mkdir(parents=True, exist_ok=True)
        OUT_PATCH.parent.mkdir(parents=True, exist_ok=True)
        OUT_JSON.write_text(js, encoding='utf-8')
        OUT_MD.write_text(md, encoding='utf-8')
        OUT_PATCH.write_text(patch_text, encoding='utf-8')
        print(f'rust-external-test-patchset: wrote {OUT_JSON.relative_to(ROOT)}')
        print(f'rust-external-test-patchset: wrote {OUT_MD.relative_to(ROOT)}')
        print(f'rust-external-test-patchset: wrote {OUT_PATCH.relative_to(ROOT)}')
        return 0

    missing = []
    for path in [OUT_JSON, OUT_MD, OUT_PATCH]:
        if not path.exists():
            missing.append(path.relative_to(ROOT).as_posix())
    if missing:
        for item in missing:
            print(f'rust-external-test-patchset: missing {item}', file=sys.stderr)
        return 1

    stale = False
    if OUT_JSON.read_text(encoding='utf-8') != js:
        print('rust-external-test-patchset: outputs are stale; run with --write', file=sys.stderr)
        stale = True
    if OUT_MD.read_text(encoding='utf-8') != md:
        print('rust-external-test-patchset: outputs are stale; run with --write', file=sys.stderr)
        stale = True
    if OUT_PATCH.read_text(encoding='utf-8') != patch_text:
        print('rust-external-test-patchset: outputs are stale; run with --write', file=sys.stderr)
        stale = True
    if stale:
        return 1

    print(
        'rust-external-test-patchset: ok '
        f"(targets={report['summary']['target_file_count']} tests={report['summary']['test_count']} bytes={report['summary']['patch_bytes']})"
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
