#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
PATCH_REPORT = ROOT / 'artifacts' / 'reports' / 'rust_standing_bootstrap_guard.json'
PATCH_PATH = ROOT / 'artifacts' / 'patches' / 'rust_standing_bootstrap_guard.patch'
OUT_JSON = ROOT / 'artifacts' / 'reports' / 'rust_standing_bootstrap_guard_rehearsal.json'
OUT_MD = ROOT / 'docs' / 'RUST_STANDING_BOOTSTRAP_GUARD_REHEARSAL.md'

def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def _run_apply(cwd: Path, patch_path: Path, check_only: bool) -> tuple[bool, str]:
    cmd = ['git', 'apply']
    if check_only:
        cmd.append('--check')
    cmd.append(str(patch_path))
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return proc.returncode == 0, '\n'.join(part for part in [proc.stdout.strip(), proc.stderr.strip()] if part).strip()

def collect() -> dict[str, Any]:
    patch_report = json.loads(PATCH_REPORT.read_text(encoding='utf-8'))
    patch_text = PATCH_PATH.read_text(encoding='utf-8')
    target_rel = str(patch_report['target_file'])
    expected_sha = str(patch_report['summary']['target_sha256'])
    expected_bytes = int(patch_report['summary']['target_bytes'])
    with tempfile.TemporaryDirectory(prefix='gr_bootstrap_guard_') as tmp:
        scratch = Path(tmp)
        patch_dst = scratch / PATCH_PATH.relative_to(ROOT)
        patch_dst.parent.mkdir(parents=True, exist_ok=True)
        patch_dst.write_text(patch_text, encoding='utf-8')
        check_ok, check_summary = _run_apply(scratch, patch_dst, True)
        apply_ok = False
        apply_summary = ''
        target_sha = ''
        target_bytes = 0
        if check_ok:
            apply_ok, apply_summary = _run_apply(scratch, patch_dst, False)
            target_path = scratch / target_rel
            if target_path.exists():
                payload = target_path.read_bytes()
                target_sha = _sha256_bytes(payload)
                target_bytes = len(payload)
    return {
        'tool': 'build_rust_standing_bootstrap_guard_rehearsal',
        'source_patch_report': str(PATCH_REPORT.relative_to(ROOT)),
        'source_patch': str(PATCH_PATH.relative_to(ROOT)),
        'target_file': target_rel,
        'summary': {
            'check_ok': check_ok,
            'apply_ok': apply_ok,
            'target_sha_matches_report': target_sha == expected_sha,
            'target_bytes_match_report': target_bytes == expected_bytes,
            'patch_sha256': _sha256_bytes(patch_text.encode('utf-8')),
        },
    }

def render_markdown(report: dict[str, Any]) -> str:
    s = report['summary']
    return '\n'.join([
        '# Rust Standing Bootstrap Guard Rehearsal',
        '',
        'Generated by `scripts/report/build_rust_standing_bootstrap_guard_rehearsal.py`. This scratch-applies the standalone standing-bootstrap guard patch and checks that the landed test file bytes match the generated report.',
        '',
        '## Snapshot',
        '',
        f"- source patch: `{report['source_patch']}`",
        f"- target file: `{report['target_file']}`",
        f"- check_ok: `{str(s['check_ok']).lower()}`",
        f"- apply_ok: `{str(s['apply_ok']).lower()}`",
        f"- target_sha_matches_report: `{str(s['target_sha_matches_report']).lower()}`",
        f"- target_bytes_match_report: `{str(s['target_bytes_match_report']).lower()}`",
        f"- patch_sha256: `{s['patch_sha256']}`",
        '',
    ])

def _check(expected_report: dict[str, Any], expected_markdown: str) -> int:
    if json.loads(OUT_JSON.read_text(encoding='utf-8')) != expected_report:
        print('rust-standing-bootstrap-guard-rehearsal: report drift detected', file=sys.stderr)
        return 1
    if OUT_MD.read_text(encoding='utf-8').rstrip('\n') != expected_markdown.rstrip('\n'):
        print('rust-standing-bootstrap-guard-rehearsal: markdown drift detected', file=sys.stderr)
        return 1
    print('rust-standing-bootstrap-guard-rehearsal: ok check/apply/hash-match all true')
    return 0

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    report = collect()
    markdown = render_markdown(report)
    if args.write:
        OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
        OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True) + '\n', encoding='utf-8')
        OUT_MD.write_text(markdown + '\n', encoding='utf-8')
        print(f'wrote {OUT_JSON.relative_to(ROOT)}')
        print(f'wrote {OUT_MD.relative_to(ROOT)}')
        return 0
    return _check(report, markdown)

if __name__ == '__main__':
    raise SystemExit(main())
