#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
PLAN_TOOL = ROOT / 'scripts' / 'tools' / 'plan_userspace_rustup_comeback.py'
OUT_JSON = ROOT / 'artifacts' / 'reports' / 'cloudtainer_userspace_rustup_plan.json'
OUT_MD = ROOT / 'docs' / 'CLOUDTAINER_USERSPACE_RUSTUP_PLAN.md'


def _load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f'unable to load module {name} from {path}')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def build_report() -> dict[str, Any]:
    module = _load_module('plan_userspace_rustup_comeback', PLAN_TOOL)
    plan = module.build_plan()
    summary = {
        'current_state_code': (plan.get('recovery_context') or {}).get('current_state_code'),
        'bridge_mode': (plan.get('recovery_context') or {}).get('bridge_mode'),
        'channel': plan['toolchain']['channel'],
        'profile': plan['toolchain']['profile'],
        'components': list(plan['toolchain'].get('components') or []),
        'targets': list(plan['toolchain'].get('targets') or []),
        'cargo_lock_present': bool(plan['cargo_lock_present']),
        'transient_roots': [
            plan['paths']['cargo_home'],
            plan['paths']['rustup_home'],
            plan['paths']['target_dir'],
        ],
        'phase_ids': [phase['phase_id'] for phase in plan['phases']],
    }
    return {
        'tool': 'build_cloudtainer_userspace_rustup_plan',
        'summary': summary,
        'plan': plan,
    }


def render_markdown(report: dict[str, Any]) -> str:
    plan = report['plan']
    summary = report['summary']
    lines = [
        '# Cloudtainer userspace rustup plan',
        '',
        'Generated by `scripts/report/build_cloudtainer_userspace_rustup_plan.py`. This turns the standing userspace-rustup detour into one replayable command surface for the *next* HTTPS-capable machine while keeping the transient toolchain roots explicit and easy to prune before the next archive cut.',
        '',
        '## Summary',
        '',
        f"- current cloudtainer state: `{summary['current_state_code'] or 'unknown'}`",
        f"- current bridge mode: `{summary['bridge_mode'] or 'unknown'}`",
        f"- repo toolchain channel: `{summary['channel']}`",
        f"- requested profile: `{summary['profile']}`",
        f"- additive components: `{', '.join(summary['components']) if summary['components'] else 'none'}`",
        f"- additive targets: `{', '.join(summary['targets']) if summary['targets'] else 'none'}`",
        f"- `Cargo.lock` present: `{str(summary['cargo_lock_present']).lower()}`",
        f"- transient roots: `{', '.join(summary['transient_roots'])}`",
        f"- phase ids: `{', '.join(summary['phase_ids'])}`",
        '',
        '## Why keep this surface',
        '',
        '- It converts the prose detour into a deterministic command sequence that can be emitted again without reopening multiple docs.',
        '- It keeps all heavy userspace Rust state under three explicit scratch roots so the next inheritor knows exactly what to delete before packaging.',
        '- It stages dependency fetch before the first real Rust witness, which is the best use of a brief egress window on a later machine.',
        '',
        '## Phases',
        '',
    ]
    for phase in plan['phases']:
        lines.append(f"### `{phase['phase_id']}` — {phase['label']}")
        lines.append('')
        commands = phase.get('commands') or []
        if commands:
            lines.append('```bash')
            lines.extend(commands)
            lines.append('```')
        else:
            lines.append('_No commands emitted for this phase in the current repo state._')
        lines.append('')
    lines.extend([
        '## Emission shortcuts',
        '',
        '```bash',
        'make show-cloudtainer-userspace-rustup-plan',
        'python3 scripts/tools/plan_userspace_rustup_comeback.py --emit json',
        'python3 scripts/tools/plan_userspace_rustup_comeback.py --emit markdown',
        '```',
        '',
    ])
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description='Build the generated cloudtainer userspace rustup plan card.')
    parser.add_argument('--write', action='store_true', help='write the report to docs/ and artifacts/reports/')
    args = parser.parse_args()

    report = build_report()
    markdown = render_markdown(report)
    if args.write:
        OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True) + '\n', encoding='utf-8')
        OUT_MD.write_text(markdown, encoding='utf-8')
    else:
        print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
