from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import yaml
from typer.testing import CliRunner

import vhk.cli as cli_mod
from vhk.cli import app
from vhk.system.global_shortcuts_portal import BoundShortcut, ShortcutSignal


runner = CliRunner()


def _make_project(tmp_path: Path) -> Path:
    project_dir = tmp_path / "proj"
    (project_dir / "macros").mkdir(parents=True)

    (project_dir / "macros" / "launch.yaml").write_text(
        yaml.safe_dump(
            {
                "name": "launch",
                "steps": [
                    {"type": "TypeText", "text": "hello"},
                    {"type": "Return", "value": "ok"},
                ],
            },
            sort_keys=False,
        )
    )

    (project_dir / "project.yaml").write_text(
        yaml.safe_dump(
            {
                "name": "proj",
                "settings": {"desktop_backend": "wayland"},
                "bindings": [
                    {
                        "keys": "Mod4+Shift+P",
                        "name": "launch_hotkey",
                        "macro": "launch",
                        "description": "Launch macro",
                        "vars": {"mode": "fast"},
                        "when": {"class": "Firefox"},
                    },
                    {
                        "keys": "Ctrl+ä",
                        "macro": "launch",
                        "description": "Unportable chord",
                    },
                ],
            },
            sort_keys=False,
        )
    )
    return project_dir



def test_gen_portal_shortcuts_spec_writes_reviewable_catalog(tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    out_path = tmp_path / "vhk.portal-shortcuts.yml"

    res = runner.invoke(
        app,
        [
            "gen-portal-shortcuts-spec",
            str(project_dir),
            "--bus-event",
            "vhk.trigger",
            "--out",
            str(out_path),
        ],
    )
    assert res.exit_code == 0, res.output

    text = out_path.read_text()
    assert text.startswith("# VHK portal shortcut catalog for project: proj\n")
    assert "# Generated by: vhk gen-portal-shortcuts-spec" in text

    payload = yaml.safe_load(text)
    assert payload["portal_interface"] == "org.freedesktop.portal.GlobalShortcuts"
    assert payload["bus_event"] == "vhk.trigger"
    assert payload["project"]["desktop_backend"] == "wayland"
    assert payload["bind_command"].startswith("vhk portal-hotkeys ")

    shortcuts = payload["shortcuts"]
    assert len(shortcuts) == 1
    assert shortcuts[0]["shortcut_id"] == "launch_hotkey"
    assert shortcuts[0]["preferred_trigger"] == "LOGO+SHIFT+p"
    assert shortcuts[0]["dispatch_payload"]["macro"] == "launch"
    assert shortcuts[0]["dispatch_payload"]["require_window"]["class"] == "Firefox"

    skipped = payload["skipped_bindings"]
    assert len(skipped) == 1
    assert skipped[0]["description"] == "Unportable chord"
    assert "could not convert hotkey" in skipped[0]["reason"]


def test_gen_portal_shortcuts_spec_embeds_catalog_commands_when_path_is_known(tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    out_path = tmp_path / "artifacts" / "vhk.portal-shortcuts.yml"

    res = runner.invoke(
        app,
        [
            "gen-portal-shortcuts-spec",
            str(project_dir),
            "--bus-event",
            "vhk.trigger",
            "--out",
            str(out_path),
        ],
    )
    assert res.exit_code == 0, res.output

    payload = yaml.safe_load(out_path.read_text())
    assert payload["catalog_path_hint"] == str(out_path)
    assert f"--catalog {str(out_path)}" in payload["bind_from_catalog_command"]
    assert f"--catalog {str(out_path)}" in payload["bindless_listen_from_catalog_command"]
    assert payload["assignment_report_path_hint"] == str(out_path.with_suffix(".assigned.yml"))
    assert payload["assignment_diff_path_hint"] == str(out_path.with_suffix(".assigned.diff.yml"))
    assert payload["assignment_state_root_hint"] == "${XDG_STATE_HOME:-$HOME/.local/state}/vhk/portal-shortcuts/proj"
    assert payload["latest_assignment_report_path_hint"] == "${XDG_STATE_HOME:-$HOME/.local/state}/vhk/portal-shortcuts/proj/latest/vhk.portal-shortcuts.assigned.yml"
    assert payload["latest_assignment_diff_path_hint"] == "${XDG_STATE_HOME:-$HOME/.local/state}/vhk/portal-shortcuts/proj/latest/vhk.portal-shortcuts.assigned.diff.yml"
    assert f"--assignment-report {str(out_path.with_suffix('.assigned.yml'))}" in payload["bind_and_capture_assignment_command"]
    assert "--assignment-history --max-events 1" in payload["bind_and_capture_assignment_history_command"]
    assert f"--catalog {str(out_path)}" in payload["bind_and_capture_assignment_history_command"]
    assert f"diff-portal-assignment-report <previous-report> {str(out_path.with_suffix('.assigned.yml'))}" in payload["compare_assignment_report_command_template"]
    assert f"--out {str(out_path.with_suffix('.assigned.diff.yml'))}" in payload["compare_assignment_report_command_template"]
    assert payload["list_assignment_history_command"] == f"vhk portal-assignment-history {project_dir} --json"
    assert payload["list_assignment_history_drift_command"] == f"vhk portal-assignment-history {project_dir} --json --drift-only"
    assert payload["list_assignment_history_since_command_template"] == f"vhk portal-assignment-history {project_dir} --json --since <YYYYMMDDTHHMMSSZ>"
    assert payload["export_assignment_history_markdown_path_hint"] == str(out_path.with_suffix(".history.md"))
    assert payload["export_assignment_history_markdown_command"] == f"vhk export-portal-assignment-history {project_dir} --out {str(out_path.with_suffix('.history.md'))}"
    assert payload["export_assignment_history_drift_markdown_command"] == f"vhk export-portal-assignment-history {project_dir} --drift-only --out {str(out_path.with_suffix('.history.md'))}"
    assert payload["export_assignment_history_since_command_template"] == f"vhk export-portal-assignment-history {project_dir} --since <YYYYMMDDTHHMMSSZ> --out {str(out_path.with_suffix('.history.md'))}"
    assert payload["export_assignment_history_html_path_hint"] == str(out_path.with_suffix('.history.html'))
    assert payload["export_assignment_history_html_command"] == f"vhk export-portal-assignment-history {project_dir} --format html --out {str(out_path.with_suffix('.history.html'))}"
    assert payload["export_assignment_history_drift_html_command"] == f"vhk export-portal-assignment-history {project_dir} --format html --drift-only --out {str(out_path.with_suffix('.history.html'))}"
    assert payload["export_assignment_history_since_html_command_template"] == f"vhk export-portal-assignment-history {project_dir} --format html --since <YYYYMMDDTHHMMSSZ> --out {str(out_path.with_suffix('.history.html'))}"
    assert payload["prune_assignment_history_command_template"] == f"vhk prune-portal-assignment-history {project_dir} --keep <count> --dry-run"
    assert payload["prune_assignment_history_older_than_command_template"] == f"vhk prune-portal-assignment-history {project_dir} --keep <count> --older-than-days <days> --dry-run"
    assert payload["assignment_presets_path_hint"] == str(out_path.with_suffix('.history-presets.yml'))
    assert payload["assignment_local_presets_path_hint"] == "${XDG_CONFIG_HOME:-$HOME/.config}/vhk/portal-shortcuts/proj/history-presets.local.yml"
    assert payload["generate_assignment_presets_command"] == f"vhk gen-portal-assignment-presets {project_dir} --out {str(out_path.with_suffix('.history-presets.yml'))}"
    assert payload["generate_assignment_presets_with_local_template_command"] == f"vhk gen-portal-assignment-presets {project_dir} --out {str(out_path.with_suffix('.history-presets.yml'))} --local-out '${{XDG_CONFIG_HOME:-$HOME/.config}}/vhk/portal-shortcuts/proj/history-presets.local.yml'"
    assert payload["inspect_assignment_history_recent_drift_preset_command"] == f"vhk inspect-portal-assignment-preset {project_dir} --preset-file {str(out_path.with_suffix('.history-presets.yml'))} --preset recent-drift --section history --json"
    assert payload["list_assignment_history_recent_drift_preset_command"] == f"vhk portal-assignment-history {project_dir} --preset-file {str(out_path.with_suffix('.history-presets.yml'))} --preset recent-drift --json"
    assert payload["export_assignment_history_latest_handoff_preset_command"] == f"vhk export-portal-assignment-history {project_dir} --preset-file {str(out_path.with_suffix('.history-presets.yml'))} --preset latest-handoff --out {str(out_path.with_suffix('.history.html'))}"
    assert payload["prune_assignment_history_retention_preset_command"] == f"vhk prune-portal-assignment-history {project_dir} --preset-file {str(out_path.with_suffix('.history-presets.yml'))} --preset retention-30d --dry-run"
    assert payload["inspect_assignment_history_recent_drift_layered_preset_command"] == f"vhk inspect-portal-assignment-preset {project_dir} --preset-file {str(out_path.with_suffix('.history-presets.yml'))} --preset-file '${{XDG_CONFIG_HOME:-$HOME/.config}}/vhk/portal-shortcuts/proj/history-presets.local.yml' --preset recent-drift --section history --json"
    assert payload["list_assignment_history_recent_drift_layered_preset_command"] == f"vhk portal-assignment-history {project_dir} --preset-file {str(out_path.with_suffix('.history-presets.yml'))} --preset-file '${{XDG_CONFIG_HOME:-$HOME/.config}}/vhk/portal-shortcuts/proj/history-presets.local.yml' --preset recent-drift --json"



def test_gen_portal_assignment_presets_writes_reusable_filters(tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    out_path = tmp_path / "portal.history-presets.yml"
    local_out = tmp_path / "portal.history-presets.local.yml"

    res = runner.invoke(app, ["gen-portal-assignment-presets", str(project_dir), "--out", str(out_path), "--local-out", str(local_out)])
    assert res.exit_code == 0, res.output

    text = out_path.read_text()
    assert text.startswith("# VHK portal assignment review presets for project: proj\n")
    payload = yaml.safe_load(text)
    assert payload["state_root_hint"] == "${XDG_STATE_HOME:-$HOME/.local/state}/vhk/portal-shortcuts/proj"
    assert payload["local_presets_path_hint"] == str(local_out)
    assert payload["history_presets"]["recent-drift"]["filters"]["drift_only"] is True
    assert payload["export_presets"]["latest-handoff"]["filters"]["format"] == "html"
    assert payload["export_presets"]["latest-handoff"]["filters"]["include_paths"] is False
    assert payload["prune_presets"]["retention-30d"]["filters"]["older_than_days"] == 30
    assert payload["inspect_recent_drift_command"] == f"vhk inspect-portal-assignment-preset {project_dir} --preset-file {out_path} --preset recent-drift --section history --json"
    assert payload["list_recent_drift_command"] == f"vhk portal-assignment-history {project_dir} --preset-file {out_path} --preset recent-drift --json"
    assert payload["inspect_recent_drift_layered_command"] == f"vhk inspect-portal-assignment-preset {project_dir} --preset-file {out_path} --preset-file {local_out} --preset recent-drift --section history --json"
    assert payload["list_recent_drift_layered_command"] == f"vhk portal-assignment-history {project_dir} --preset-file {out_path} --preset-file {local_out} --preset recent-drift --json"

    local_payload = yaml.safe_load(local_out.read_text())
    assert local_payload["layering"]["role"] == "operator-local-overrides"
    assert local_payload["history_presets"]["recent-drift"]["filters"]["limit"] == 8
    assert local_payload["export_presets"]["latest-handoff"]["filters"]["include_paths"] is True



def test_portal_hotkeys_can_consume_generated_catalog(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    catalog_path = tmp_path / "vhk.portal-shortcuts.yml"

    gen_res = runner.invoke(
        app,
        [
            "gen-portal-shortcuts-spec",
            str(project_dir),
            "--bus-event",
            "vhk.trigger",
            "--out",
            str(catalog_path),
        ],
    )
    assert gen_res.exit_code == 0, gen_res.output

    bound_specs: list[object] = []
    emitted: list[tuple[str, str, dict]] = []

    monkeypatch.setattr(cli_mod, "portal_create_session", lambda: "/org/freedesktop/portal/desktop/session/1_2/vhk")
    monkeypatch.setattr(cli_mod, "portal_bind_shortcuts", lambda sess, specs, parent_window="": bound_specs.extend(specs))
    monkeypatch.setattr(
        cli_mod,
        "iter_portal_shortcut_signals",
        lambda session_handle: iter([
            ShortcutSignal(
                kind="Activated",
                session_handle=session_handle,
                shortcut_id="launch_hotkey",
                timestamp=12345,
                options={},
            )
        ]),
    )
    monkeypatch.setattr(cli_mod, "emit_bus_event", lambda sock, event, payload: emitted.append((sock, event, dict(payload))))
    monkeypatch.setattr(cli_mod, "get_bus_socket_path", lambda root_dir, configured=None: "/tmp/vhk.sock")

    res = runner.invoke(
        app,
        [
            "portal-hotkeys",
            str(project_dir),
            "--catalog",
            str(catalog_path),
            "--bind",
            "--max-events",
            "1",
        ],
    )
    assert res.exit_code == 0, res.output
    assert "Shortcut source:" in res.output
    assert "catalog" in res.output

    assert len(bound_specs) == 1
    assert bound_specs[0].shortcut_id == "launch_hotkey"
    assert bound_specs[0].preferred_trigger == "LOGO+SHIFT+p"

    assert len(emitted) == 1
    sock, event_name, payload = emitted[0]
    assert sock == "/tmp/vhk.sock"
    assert event_name == "vhk.trigger"
    assert payload["portal_kind"] == "Activated"
    assert payload["portal_session"] == "/org/freedesktop/portal/desktop/session/1_2/vhk"
    assert payload["portal_timestamp"] == 12345
    assert payload["shortcut_id"] == "launch_hotkey"
    assert payload["macro"] == "launch"
    assert payload["vars"] == {"mode": "fast"}
    assert payload["binding"] == "launch_hotkey"
    assert payload["keys"] == "Mod4+Shift+P"
    assert payload["require_window"]["class"] == "Firefox"


def test_portal_hotkeys_rejects_invalid_catalog(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    catalog_path = tmp_path / "broken.portal-shortcuts.yml"
    catalog_path.write_text(
        yaml.safe_dump(
            {
                "bus_event": "vhk.trigger",
                "shortcuts": [
                    {"shortcut_id": "dup", "description": "one", "preferred_trigger": "LOGO+a", "dispatch_payload": {"macro": "launch"}},
                    {"shortcut_id": "dup", "description": "two", "preferred_trigger": "LOGO+b", "dispatch_payload": {"macro": "launch"}},
                ],
            },
            sort_keys=False,
        )
    )

    monkeypatch.setattr(cli_mod, "portal_create_session", lambda: "/org/freedesktop/portal/desktop/session/1_2/vhk")
    res = runner.invoke(app, ["portal-hotkeys", str(project_dir), "--catalog", str(catalog_path), "--max-events", "1"])
    assert res.exit_code != 0
    assert "duplicate shortcut_id" in res.output


def test_portal_hotkeys_can_write_assignment_report(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    catalog_path = tmp_path / "vhk.portal-shortcuts.yml"
    report_path = tmp_path / "vhk.portal-shortcuts.assigned.yml"

    gen_res = runner.invoke(
        app,
        [
            "gen-portal-shortcuts-spec",
            str(project_dir),
            "--bus-event",
            "vhk.trigger",
            "--out",
            str(catalog_path),
        ],
    )
    assert gen_res.exit_code == 0, gen_res.output

    monkeypatch.setattr(cli_mod, "portal_create_session", lambda: "/org/freedesktop/portal/desktop/session/1_2/vhk")
    monkeypatch.setattr(
        cli_mod,
        "portal_bind_shortcuts",
        lambda sess, specs, parent_window="": [
            BoundShortcut(shortcut_id="launch_hotkey", description="Launch macro", trigger_description="Super+Shift+P")
        ],
    )
    monkeypatch.setattr(cli_mod, "iter_portal_shortcut_signals", lambda session_handle: iter(()))
    monkeypatch.setattr(cli_mod, "emit_bus_event", lambda sock, event, payload: None)
    monkeypatch.setattr(cli_mod, "get_bus_socket_path", lambda root_dir, configured=None: "/tmp/vhk.sock")

    res = runner.invoke(
        app,
        [
            "portal-hotkeys",
            str(project_dir),
            "--catalog",
            str(catalog_path),
            "--bind",
            "--assignment-report",
            str(report_path),
        ],
    )
    assert res.exit_code == 0, res.output
    assert "Wrote portal assignment report:" in res.output

    payload = yaml.safe_load(report_path.read_text())
    assert payload["session_handle"] == "/org/freedesktop/portal/desktop/session/1_2/vhk"
    assert payload["summary"]["requested_count"] == 1
    assert payload["summary"]["assigned_count"] == 1
    assert payload["summary"]["matched_assigned_count"] == 1
    assert payload["comparison"][0]["shortcut_id"] == "launch_hotkey"
    assert payload["comparison"][0]["requested_preferred_trigger"] == "LOGO+SHIFT+p"
    assert payload["comparison"][0]["assigned_trigger_description"] == "Super+Shift+P"
    assert payload["comparison"][0]["status"] == "assigned"


def test_portal_hotkeys_assignment_report_can_use_list_shortcuts_without_bind(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    catalog_path = tmp_path / "vhk.portal-shortcuts.yml"
    report_path = tmp_path / "vhk.portal-shortcuts.assigned.yml"

    gen_res = runner.invoke(
        app,
        [
            "gen-portal-shortcuts-spec",
            str(project_dir),
            "--bus-event",
            "vhk.trigger",
            "--out",
            str(catalog_path),
        ],
    )
    assert gen_res.exit_code == 0, gen_res.output

    monkeypatch.setattr(cli_mod, "portal_create_session", lambda: "/org/freedesktop/portal/desktop/session/1_2/vhk")
    monkeypatch.setattr(cli_mod, "portal_list_shortcuts", lambda sess: [
        BoundShortcut(shortcut_id="launch_hotkey", description="Launch macro", trigger_description="Super+Shift+P")
    ])
    monkeypatch.setattr(cli_mod, "iter_portal_shortcut_signals", lambda session_handle: iter(()))
    monkeypatch.setattr(cli_mod, "emit_bus_event", lambda sock, event, payload: None)
    monkeypatch.setattr(cli_mod, "get_bus_socket_path", lambda root_dir, configured=None: "/tmp/vhk.sock")

    res = runner.invoke(
        app,
        [
            "portal-hotkeys",
            str(project_dir),
            "--catalog",
            str(catalog_path),
            "--no-bind",
            "--assignment-report",
            str(report_path),
        ],
    )
    assert res.exit_code == 0, res.output

    payload = yaml.safe_load(report_path.read_text())
    assert payload["summary"]["matched_assigned_count"] == 1
    assert payload["comparison"][0]["assigned_trigger_description"] == "Super+Shift+P"



def test_diff_portal_assignment_report_detects_trigger_drift(tmp_path: Path) -> None:
    baseline_path = tmp_path / "baseline.assigned.yml"
    current_path = tmp_path / "current.assigned.yml"
    out_path = tmp_path / "current.assigned.diff.yml"

    baseline_path.write_text(
        yaml.safe_dump(
            {
                "project": {"root_dir": "/tmp/proj"},
                "session_handle": "/org/freedesktop/portal/desktop/session/1_2/vhk-old",
                "bus_event": "vhk.trigger",
                "requested_shortcuts": [
                    {
                        "shortcut_id": "launch_hotkey",
                        "description": "Launch macro",
                        "preferred_trigger": "LOGO+SHIFT+p",
                    }
                ],
                "assigned_shortcuts": [
                    {
                        "shortcut_id": "launch_hotkey",
                        "description": "Launch macro",
                        "trigger_description": "Super+Shift+P",
                    }
                ],
                "comparison": [
                    {
                        "shortcut_id": "launch_hotkey",
                        "description": "Launch macro",
                        "requested_preferred_trigger": "LOGO+SHIFT+p",
                        "assigned_trigger_description": "Super+Shift+P",
                        "status": "assigned",
                    }
                ],
            },
            sort_keys=False,
        )
    )
    current_path.write_text(
        yaml.safe_dump(
            {
                "project": {"root_dir": "/tmp/proj"},
                "session_handle": "/org/freedesktop/portal/desktop/session/1_2/vhk-new",
                "bus_event": "vhk.trigger",
                "requested_shortcuts": [
                    {
                        "shortcut_id": "launch_hotkey",
                        "description": "Launch macro",
                        "preferred_trigger": "LOGO+SHIFT+p",
                    },
                    {
                        "shortcut_id": "search_hotkey",
                        "description": "Search macro",
                        "preferred_trigger": "LOGO+f",
                    },
                ],
                "assigned_shortcuts": [
                    {
                        "shortcut_id": "launch_hotkey",
                        "description": "Launch macro",
                        "trigger_description": "Super+Shift+L",
                    },
                    {
                        "shortcut_id": "search_hotkey",
                        "description": "Search macro",
                        "trigger_description": "Super+F",
                    },
                ],
                "comparison": [
                    {
                        "shortcut_id": "launch_hotkey",
                        "description": "Launch macro",
                        "requested_preferred_trigger": "LOGO+SHIFT+p",
                        "assigned_trigger_description": "Super+Shift+L",
                        "status": "assigned",
                    },
                    {
                        "shortcut_id": "search_hotkey",
                        "description": "Search macro",
                        "requested_preferred_trigger": "LOGO+f",
                        "assigned_trigger_description": "Super+F",
                        "status": "assigned",
                    },
                ],
            },
            sort_keys=False,
        )
    )

    res = runner.invoke(
        app,
        [
            "diff-portal-assignment-report",
            str(baseline_path),
            str(current_path),
            "--out",
            str(out_path),
        ],
    )
    assert res.exit_code == 0, res.output
    assert "Wrote portal assignment diff:" in res.output

    payload = yaml.safe_load(out_path.read_text())
    assert payload["baseline"]["path"] == str(baseline_path.resolve())
    assert payload["current"]["path"] == str(current_path.resolve())
    assert payload["summary"]["drift_present"] is True
    assert payload["summary"]["assigned_trigger_changed"] == ["launch_hotkey"]
    assert payload["summary"]["added_shortcuts"] == ["search_hotkey"]

    launch = next(item for item in payload["comparison"] if item["shortcut_id"] == "launch_hotkey")
    assert launch["change_kinds"] == ["assigned-trigger-changed"]
    assert launch["baseline_assigned_trigger_description"] == "Super+Shift+P"
    assert launch["current_assigned_trigger_description"] == "Super+Shift+L"

    search = next(item for item in payload["comparison"] if item["shortcut_id"] == "search_hotkey")
    assert search["change_kinds"] == ["added-shortcut"]
    assert search["current_status"] == "assigned"



def test_diff_portal_assignment_report_check_mode_fails_on_drift(tmp_path: Path) -> None:
    baseline_path = tmp_path / "baseline.assigned.yml"
    current_path = tmp_path / "current.assigned.yml"

    baseline_path.write_text(
        yaml.safe_dump(
            {
                "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
                "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
                "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
            },
            sort_keys=False,
        )
    )
    current_path.write_text(
        yaml.safe_dump(
            {
                "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
                "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+L"}],
                "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+L", "status": "assigned"}],
            },
            sort_keys=False,
        )
    )

    res = runner.invoke(
        app,
        [
            "diff-portal-assignment-report",
            str(baseline_path),
            str(current_path),
            "--check",
        ],
    )
    assert res.exit_code == 1
    payload = yaml.safe_load(res.output)
    assert payload["summary"]["drift_present"] is True
    assert payload["summary"]["assigned_trigger_changed"] == ["launch_hotkey"]


def test_portal_hotkeys_assignment_history_persists_under_xdg_state(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    catalog_path = tmp_path / "vhk.portal-shortcuts.yml"
    state_home = tmp_path / "state"

    gen_res = runner.invoke(
        app,
        [
            "gen-portal-shortcuts-spec",
            str(project_dir),
            "--bus-event",
            "vhk.trigger",
            "--out",
            str(catalog_path),
        ],
    )
    assert gen_res.exit_code == 0, gen_res.output

    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))
    monkeypatch.setattr(cli_mod, "portal_create_session", lambda: "/org/freedesktop/portal/desktop/session/1_2/vhk")
    monkeypatch.setattr(cli_mod, "iter_portal_shortcut_signals", lambda session_handle: iter(()))
    monkeypatch.setattr(cli_mod, "emit_bus_event", lambda sock, event, payload: None)
    monkeypatch.setattr(cli_mod, "get_bus_socket_path", lambda root_dir, configured=None: "/tmp/vhk.sock")

    timestamps = iter(["20260308T220900Z", "20260308T221000Z"])
    monkeypatch.setattr(cli_mod, "_portal_assignment_history_timestamp", lambda: next(timestamps))

    monkeypatch.setattr(
        cli_mod,
        "portal_bind_shortcuts",
        lambda sess, specs, parent_window="": [
            BoundShortcut(shortcut_id="launch_hotkey", description="Launch macro", trigger_description="Super+Shift+P")
        ],
    )
    res1 = runner.invoke(
        app,
        [
            "portal-hotkeys",
            str(project_dir),
            "--catalog",
            str(catalog_path),
            "--bind",
            "--assignment-history",
        ],
    )
    assert res1.exit_code == 0, res1.output
    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    latest_report = state_root / "latest" / "vhk.portal-shortcuts.assigned.yml"
    first_history = state_root / "history" / "20260308T220900Z.assigned.yml"
    assert latest_report.exists()
    assert first_history.exists()
    assert not (state_root / "latest" / "vhk.portal-shortcuts.assigned.diff.yml").exists()

    monkeypatch.setattr(
        cli_mod,
        "portal_bind_shortcuts",
        lambda sess, specs, parent_window="": [
            BoundShortcut(shortcut_id="launch_hotkey", description="Launch macro", trigger_description="Super+Shift+L")
        ],
    )
    res2 = runner.invoke(
        app,
        [
            "portal-hotkeys",
            str(project_dir),
            "--catalog",
            str(catalog_path),
            "--bind",
            "--assignment-history",
        ],
    )
    assert res2.exit_code == 0, res2.output
    second_history = state_root / "history" / "20260308T221000Z.assigned.yml"
    latest_diff = state_root / "latest" / "vhk.portal-shortcuts.assigned.diff.yml"
    history_diff = state_root / "history" / "20260308T221000Z.assigned.diff.yml"
    assert second_history.exists()
    assert latest_diff.exists()
    assert history_diff.exists()

    diff_payload = yaml.safe_load(latest_diff.read_text())
    assert diff_payload["summary"]["drift_present"] is True
    assert diff_payload["summary"]["assigned_trigger_changed"] == ["launch_hotkey"]

    latest_payload = yaml.safe_load(latest_report.read_text())
    assert latest_payload["comparison"][0]["assigned_trigger_description"] == "Super+Shift+L"


def test_portal_assignment_history_lists_snapshots_from_xdg_state(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))

    report_one = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/one",
        "catalog_source": "catalog-one.yml",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }
    report_two = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/two",
        "catalog_source": "catalog-two.yml",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+L"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+L", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }
    diff_two = {
        "summary": {
            "drift_present": True,
            "changed_shortcuts": ["launch_hotkey"],
            "assigned_trigger_changed": ["launch_hotkey"],
        }
    }

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    latest_dir = state_root / "latest"
    history_dir = state_root / "history"
    latest_dir.mkdir(parents=True)
    history_dir.mkdir(parents=True)
    (history_dir / "20260308T220900Z.assigned.yml").write_text(yaml.safe_dump(report_one, sort_keys=False))
    (history_dir / "20260308T221000Z.assigned.yml").write_text(yaml.safe_dump(report_two, sort_keys=False))
    (history_dir / "20260308T221000Z.assigned.diff.yml").write_text(yaml.safe_dump(diff_two, sort_keys=False))
    (latest_dir / "vhk.portal-shortcuts.assigned.yml").write_text(yaml.safe_dump(report_two, sort_keys=False))
    (latest_dir / "vhk.portal-shortcuts.assigned.diff.yml").write_text(yaml.safe_dump(diff_two, sort_keys=False))

    res = runner.invoke(app, ["portal-assignment-history", str(project_dir), "--json"])
    assert res.exit_code == 0, res.output
    payload = yaml.safe_load(res.output)
    assert payload["state_root"] == str(state_root)
    assert payload["summary"]["history_count"] == 2
    assert payload["summary"]["drift_history_timestamps"] == ["20260308T221000Z"]
    assert payload["latest"]["drift_present"] is True
    assert payload["history"][0]["timestamp"] == "20260308T221000Z"
    assert payload["history"][0]["changed_shortcuts"] == ["launch_hotkey"]
    assert payload["history"][1]["timestamp"] == "20260308T220900Z"
    assert payload["history"][1]["drift_present"] is None

    res_drift = runner.invoke(app, ["portal-assignment-history", str(project_dir), "--json", "--drift-only"])
    assert res_drift.exit_code == 0, res_drift.output
    payload_drift = yaml.safe_load(res_drift.output)
    assert [item["timestamp"] for item in payload_drift["history"]] == ["20260308T221000Z"]


def test_portal_assignment_history_supports_time_and_shortcut_filters(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))

    report_payload = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/test",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    history_dir = state_root / "history"
    history_dir.mkdir(parents=True)
    for stamp, changed in [
        ("20260308T220900Z", []),
        ("20260308T221000Z", ["launch_hotkey"]),
        ("20260308T221100Z", ["other_hotkey"]),
    ]:
        (history_dir / f"{stamp}.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))
        if changed:
            (history_dir / f"{stamp}.assigned.diff.yml").write_text(
                yaml.safe_dump({"summary": {"drift_present": True, "changed_shortcuts": changed}}, sort_keys=False)
            )

    res = runner.invoke(
        app,
        [
            "portal-assignment-history",
            str(project_dir),
            "--json",
            "--since",
            "20260308T221000Z",
            "--until",
            "2026-03-08T22:11:00Z",
            "--changed-shortcut",
            "launch_hotkey",
        ],
    )
    assert res.exit_code == 0, res.output
    payload = yaml.safe_load(res.output)
    assert payload["summary"]["filters"]["since"] == "20260308T221000Z"
    assert payload["summary"]["filters"]["until"] == "20260308T221100Z"
    assert payload["summary"]["filters"]["changed_shortcuts"] == ["launch_hotkey"]
    assert [item["timestamp"] for item in payload["history"]] == ["20260308T221000Z"]



def test_prune_portal_assignment_history_removes_older_snapshots(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))

    report_payload = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/test",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }
    diff_payload = {"summary": {"drift_present": True, "changed_shortcuts": ["launch_hotkey"]}}

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    history_dir = state_root / "history"
    history_dir.mkdir(parents=True)
    for stamp in ["20260308T220900Z", "20260308T221000Z", "20260308T221100Z"]:
        (history_dir / f"{stamp}.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))
        (history_dir / f"{stamp}.assigned.diff.yml").write_text(yaml.safe_dump(diff_payload, sort_keys=False))

    dry = runner.invoke(app, ["prune-portal-assignment-history", str(project_dir), "--keep", "1", "--dry-run", "--json"])
    assert dry.exit_code == 0, dry.output
    dry_payload = yaml.safe_load(dry.output)
    assert dry_payload["summary"]["removed_count"] == 2
    assert dry_payload["removed"][0]["timestamp"] == "20260308T221000Z"
    assert dry_payload["removed"][0]["diff_existed"] is True
    assert (history_dir / "20260308T220900Z.assigned.yml").exists()

    res = runner.invoke(app, ["prune-portal-assignment-history", str(project_dir), "--keep", "1", "--json"])
    assert res.exit_code == 0, res.output
    payload = yaml.safe_load(res.output)
    assert payload["summary"]["removed_count"] == 2
    assert (history_dir / "20260308T221100Z.assigned.yml").exists()
    assert not (history_dir / "20260308T221000Z.assigned.yml").exists()
    assert not (history_dir / "20260308T220900Z.assigned.diff.yml").exists()


def test_prune_portal_assignment_history_supports_older_than_days(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))
    monkeypatch.setattr(cli_mod, "_portal_assignment_history_now", lambda: datetime(2026, 3, 8, 22, 30, tzinfo=timezone.utc))

    report_payload = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/test",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    history_dir = state_root / "history"
    history_dir.mkdir(parents=True)
    for stamp in ["20260308T221100Z", "20260307T223000Z", "20260306T221500Z"]:
        (history_dir / f"{stamp}.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))

    res = runner.invoke(
        app,
        [
            "prune-portal-assignment-history",
            str(project_dir),
            "--keep",
            "1",
            "--older-than-days",
            "1",
            "--json",
        ],
    )
    assert res.exit_code == 0, res.output
    payload = yaml.safe_load(res.output)
    assert payload["summary"]["older_than_days"] == 1
    assert payload["summary"]["cutoff_timestamp"] == "20260307T223000Z"
    assert payload["summary"]["protected_count"] == 1
    assert payload["summary"]["removed_count"] == 1
    assert payload["removed"][0]["timestamp"] == "20260306T221500Z"
    assert (history_dir / "20260308T221100Z.assigned.yml").exists()
    assert (history_dir / "20260307T223000Z.assigned.yml").exists()
    assert not (history_dir / "20260306T221500Z.assigned.yml").exists()


def test_export_portal_assignment_history_writes_markdown_summary(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))
    monkeypatch.setattr(cli_mod, "_portal_assignment_history_now", lambda: datetime(2026, 3, 8, 23, 5, tzinfo=timezone.utc))

    report_payload = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/test",
        "catalog_source": "catalog.yml",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }
    diff_payload = {"summary": {"drift_present": True, "changed_shortcuts": ["launch_hotkey"]}}

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    latest_dir = state_root / "latest"
    history_dir = state_root / "history"
    latest_dir.mkdir(parents=True)
    history_dir.mkdir(parents=True)
    (history_dir / "20260308T221000Z.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))
    (history_dir / "20260308T221000Z.assigned.diff.yml").write_text(yaml.safe_dump(diff_payload, sort_keys=False))
    (latest_dir / "vhk.portal-shortcuts.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))
    (latest_dir / "vhk.portal-shortcuts.assigned.diff.yml").write_text(yaml.safe_dump(diff_payload, sort_keys=False))

    out_path = tmp_path / "portal-history.md"
    res = runner.invoke(app, ["export-portal-assignment-history", str(project_dir), "--out", str(out_path)])
    assert res.exit_code == 0, res.output

    text = out_path.read_text()
    assert text.startswith("# VHK portal assignment history for proj\n")
    assert "- Generated: `20260308T230500Z`" in text
    assert "## Latest assignment" in text
    assert "| `20260308T221000Z` | 1 | 1 | 1 | yes | launch_hotkey |" in text
    assert "### `20260308T221000Z`" in text
    assert f"- State root: `{state_root}`" in text


def test_export_portal_assignment_history_supports_filters_and_no_paths(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))

    report_payload = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/test",
        "catalog_source": "catalog.yml",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    history_dir = state_root / "history"
    history_dir.mkdir(parents=True)
    for stamp, changed in [("20260308T221000Z", ["launch_hotkey"]), ("20260308T221100Z", ["other_hotkey"])]:
        (history_dir / f"{stamp}.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))
        (history_dir / f"{stamp}.assigned.diff.yml").write_text(yaml.safe_dump({"summary": {"drift_present": True, "changed_shortcuts": changed}}, sort_keys=False))

    res = runner.invoke(
        app,
        [
            "export-portal-assignment-history",
            str(project_dir),
            "--drift-only",
            "--changed-shortcut",
            "launch_hotkey",
            "--no-include-paths",
        ],
    )
    assert res.exit_code == 0, res.output
    text = res.output
    assert "| `20260308T221000Z` | 1 | 1 | 1 | yes | launch_hotkey |" in text
    assert "20260308T221100Z" not in text
    assert "Report path:" not in text
    assert "Diff path:" not in text


def test_export_portal_assignment_history_can_write_html_summary(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))
    monkeypatch.setattr(cli_mod, "_portal_assignment_history_now", lambda: datetime(2026, 3, 8, 23, 10, tzinfo=timezone.utc))

    report_payload = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/test",
        "catalog_source": "catalog.yml",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }
    diff_payload = {"summary": {"drift_present": True, "changed_shortcuts": ["launch_hotkey"]}}

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    latest_dir = state_root / "latest"
    history_dir = state_root / "history"
    latest_dir.mkdir(parents=True)
    history_dir.mkdir(parents=True)
    (history_dir / "20260308T221000Z.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))
    (history_dir / "20260308T221000Z.assigned.diff.yml").write_text(yaml.safe_dump(diff_payload, sort_keys=False))
    (latest_dir / "vhk.portal-shortcuts.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))
    (latest_dir / "vhk.portal-shortcuts.assigned.diff.yml").write_text(yaml.safe_dump(diff_payload, sort_keys=False))

    out_path = tmp_path / "portal-history.html"
    res = runner.invoke(app, ["export-portal-assignment-history", str(project_dir), "--out", str(out_path), "--format", "auto"])
    assert res.exit_code == 0, res.output

    text = out_path.read_text()
    assert text.startswith("<!DOCTYPE html>\n")
    assert "<title>proj portal assignment history</title>" in text
    assert "<h2>History snapshots</h2>" in text
    assert "<code>20260308T221000Z</code>" in text
    assert "launch_hotkey" in text
    assert str(state_root) in text


def test_export_portal_assignment_history_rejects_unknown_format(tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    res = runner.invoke(app, ["export-portal-assignment-history", str(project_dir), "--format", "pdf"])
    assert res.exit_code != 0
    assert "format must be one of" in res.output


def test_portal_assignment_history_can_use_generated_preset_file(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))

    report_payload = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/test",
        "catalog_source": "catalog.yml",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    history_dir = state_root / "history"
    history_dir.mkdir(parents=True)
    for stamp, changed in [("20260308T221000Z", ["launch_hotkey"]), ("20260308T221100Z", ["other_hotkey"]), ("20260308T221200Z", ["launch_hotkey"])]:
        (history_dir / f"{stamp}.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))
        (history_dir / f"{stamp}.assigned.diff.yml").write_text(yaml.safe_dump({"summary": {"drift_present": True, "changed_shortcuts": changed}}, sort_keys=False))

    presets_path = tmp_path / "portal.history-presets.yml"
    gen_res = runner.invoke(app, ["gen-portal-assignment-presets", str(project_dir), "--out", str(presets_path)])
    assert gen_res.exit_code == 0, gen_res.output

    res = runner.invoke(
        app,
        [
            "portal-assignment-history",
            str(project_dir),
            "--preset-file",
            str(presets_path),
            "--preset",
            "recent-drift",
            "--json",
        ],
    )
    assert res.exit_code == 0, res.output
    payload = yaml.safe_load(res.output)
    assert payload["summary"]["history_count"] == 3
    assert payload["summary"]["filters"]["preset"] == "recent-drift"
    assert payload["summary"]["filters"]["preset_file"] == str(presets_path)


def test_portal_assignment_history_layered_preset_files_allow_local_override(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))

    report_payload = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/test",
        "catalog_source": "catalog.yml",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    history_dir = state_root / "history"
    history_dir.mkdir(parents=True)
    for stamp in ["20260308T221000Z", "20260308T221100Z", "20260308T221200Z"]:
        (history_dir / f"{stamp}.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))
        (history_dir / f"{stamp}.assigned.diff.yml").write_text(yaml.safe_dump({"summary": {"drift_present": True, "changed_shortcuts": ["launch_hotkey"]}}, sort_keys=False))

    shared_path = tmp_path / "portal.history-presets.yml"
    local_path = tmp_path / "portal.history-presets.local.yml"
    gen_res = runner.invoke(app, ["gen-portal-assignment-presets", str(project_dir), "--out", str(shared_path), "--local-out", str(local_path)])
    assert gen_res.exit_code == 0, gen_res.output

    local_payload = yaml.safe_load(local_path.read_text())
    local_payload["history_presets"]["recent-drift"]["filters"]["limit"] = 2
    local_path.write_text(yaml.safe_dump(local_payload, sort_keys=False))

    res = runner.invoke(
        app,
        [
            "portal-assignment-history",
            str(project_dir),
            "--preset-file",
            str(shared_path),
            "--preset-file",
            str(local_path),
            "--preset",
            "recent-drift",
            "--json",
        ],
    )
    assert res.exit_code == 0, res.output
    payload = yaml.safe_load(res.output)
    assert payload["summary"]["history_count"] == 2
    assert payload["summary"]["filters"]["preset"] == "recent-drift"
    assert payload["summary"]["filters"]["preset_files"] == [str(shared_path), str(local_path)]
    assert payload["summary"]["filters"]["preset_source_path"] == str(local_path)
    resolution = payload["summary"]["filters"]["preset_resolution"]
    assert resolution["section_key"] == "history_presets"
    assert resolution["source_path"] == str(local_path)
    assert resolution["source_rank"] == 2
    assert resolution["paths"] == [str(shared_path), str(local_path)]


def test_inspect_portal_assignment_preset_reports_layered_provenance(tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    shared_path = tmp_path / "portal.history-presets.yml"
    local_path = tmp_path / "portal.history-presets.local.yml"

    gen_res = runner.invoke(app, ["gen-portal-assignment-presets", str(project_dir), "--out", str(shared_path), "--local-out", str(local_path)])
    assert gen_res.exit_code == 0, gen_res.output

    local_payload = yaml.safe_load(local_path.read_text())
    local_payload["history_presets"]["recent-drift"]["filters"]["limit"] = 4
    local_path.write_text(yaml.safe_dump(local_payload, sort_keys=False))

    res = runner.invoke(
        app,
        [
            "inspect-portal-assignment-preset",
            str(project_dir),
            "--preset-file",
            str(shared_path),
            "--preset-file",
            str(local_path),
            "--preset",
            "recent-drift",
            "--section",
            "history",
            "--json",
        ],
    )
    assert res.exit_code == 0, res.output
    payload = yaml.safe_load(res.output)
    resolution = payload["preset_resolution"]
    assert resolution["name"] == "recent-drift"
    assert resolution["section_key"] == "history_presets"
    assert resolution["source_path"] == str(local_path)
    assert resolution["source_rank"] == 2
    assert resolution["filters"]["limit"] == 4
    assert resolution["paths"] == [str(shared_path), str(local_path)]
    assert "Later --preset-file entries override" in resolution["merge_rule"]


def test_export_portal_assignment_history_can_use_generated_export_preset(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))

    report_payload = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/test",
        "catalog_source": "catalog.yml",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }
    diff_payload = {"summary": {"drift_present": True, "changed_shortcuts": ["launch_hotkey"]}}

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    history_dir = state_root / "history"
    history_dir.mkdir(parents=True)
    (history_dir / "20260308T221000Z.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))
    (history_dir / "20260308T221000Z.assigned.diff.yml").write_text(yaml.safe_dump(diff_payload, sort_keys=False))

    presets_path = tmp_path / "portal.history-presets.yml"
    gen_res = runner.invoke(app, ["gen-portal-assignment-presets", str(project_dir), "--out", str(presets_path)])
    assert gen_res.exit_code == 0, gen_res.output

    out_path = tmp_path / "handoff.html"
    res = runner.invoke(
        app,
        [
            "export-portal-assignment-history",
            str(project_dir),
            "--preset-file",
            str(presets_path),
            "--preset",
            "latest-handoff",
            "--out",
            str(out_path),
        ],
    )
    assert res.exit_code == 0, res.output
    text = out_path.read_text()
    assert text.startswith("<!DOCTYPE html>\n")
    assert "Preset resolution" in text
    assert str(presets_path) in text
    assert "Report path:" not in text
    assert "Diff path:" not in text


def test_prune_portal_assignment_history_can_use_generated_prune_preset(monkeypatch, tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    state_home = tmp_path / "state"
    monkeypatch.setenv("XDG_STATE_HOME", str(state_home))
    monkeypatch.setattr(cli_mod, "_portal_assignment_history_now", lambda: datetime(2026, 3, 8, 22, 30, tzinfo=timezone.utc))

    report_payload = {
        "project": {"root_dir": str(project_dir)},
        "session_handle": "/org/freedesktop/portal/desktop/session/1_2/test",
        "bus_event": "vhk.trigger",
        "requested_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "preferred_trigger": "LOGO+SHIFT+p"}],
        "assigned_shortcuts": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "trigger_description": "Super+Shift+P"}],
        "comparison": [{"shortcut_id": "launch_hotkey", "description": "Launch macro", "requested_preferred_trigger": "LOGO+SHIFT+p", "assigned_trigger_description": "Super+Shift+P", "status": "assigned"}],
        "summary": {"requested_count": 1, "assigned_count": 1, "matched_assigned_count": 1, "missing_requested": [], "extra_assigned": []},
    }

    state_root = state_home / "vhk" / "portal-shortcuts" / "proj"
    history_dir = state_root / "history"
    history_dir.mkdir(parents=True)
    for stamp in ["20260308T221100Z", "20260307T223000Z", "20260306T221500Z"]:
        (history_dir / f"{stamp}.assigned.yml").write_text(yaml.safe_dump(report_payload, sort_keys=False))

    presets_path = tmp_path / "portal.history-presets.yml"
    gen_res = runner.invoke(app, ["gen-portal-assignment-presets", str(project_dir), "--out", str(presets_path)])
    assert gen_res.exit_code == 0, gen_res.output

    res = runner.invoke(
        app,
        [
            "prune-portal-assignment-history",
            str(project_dir),
            "--preset-file",
            str(presets_path),
            "--preset",
            "retention-30d",
            "--dry-run",
            "--json",
        ],
    )
    assert res.exit_code == 0, res.output
    payload = yaml.safe_load(res.output)
    assert payload["summary"]["keep"] == 10
    assert payload["summary"]["older_than_days"] == 30
    assert payload["summary"]["removed_count"] == 0


def test_portal_assignment_history_rejects_mixing_preset_and_manual_filters(tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    presets_path = tmp_path / "portal.history-presets.yml"
    gen_res = runner.invoke(app, ["gen-portal-assignment-presets", str(project_dir), "--out", str(presets_path)])
    assert gen_res.exit_code == 0, gen_res.output

    res = runner.invoke(
        app,
        [
            "portal-assignment-history",
            str(project_dir),
            "--preset-file",
            str(presets_path),
            "--preset",
            "recent-drift",
            "--limit",
            "5",
        ],
    )
    assert res.exit_code != 0
    assert "cannot combine --preset" in res.output
