#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path

from archive_meta import GENERATED, ROOT, current_revision, generated_at_utc

SKIP_NAMES = {"GENERATED_SURFACE_AUDIT.json", "GENERATED_SURFACE_AUDIT.md", "MANIFEST.json"}
TEST_MATRIX_RE = re.compile(r"^[A-Z0-9_]+_TESTS\.(json|md)$")
BUDGETS = {
    "large_markdown_bytes": 500_000,
    "large_json_bytes": 800_000,
    "very_large_file_bytes": 1_500_000,
    "reader_route_file_count_warning": 60,
    "total_generated_bytes_warning": 7_000_000,
}


def h1(path: Path) -> str | None:
    if path.suffix.lower() != ".md":
        return None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def surface_role(path: Path) -> str:
    if TEST_MATRIX_RE.fullmatch(path.name):
        return "leaf_test_matrix_render"
    if path.suffix.lower() == ".md":
        return "reader_route"
    if path.name in {"ARCHIVE_INDEX.json", "NOTE_STATUS.json", "CONTROL_SURFACES.json", "ASSURANCE_ARTIFACTS.json", "LIFECYCLE_GATES.json", "THREAD_SUMMARY.json", "CANON_MAP.json", "RELEASES.json"}:
        return "machine_route"
    return "machine_support"


def counts_toward_reader_route_budget(role: str) -> bool:
    # The old audit treated every generated leaf matrix JSON/Markdown pair as
    # equal reader cost. That made the test matrix library look like package
    # sprawl even after the actual oversized surfaces were compacted. The budget
    # now tracks first-reader route pressure separately from leaf matrix renders.
    return role in {"reader_route", "machine_route", "machine_support"}


def file_row(path: Path) -> dict:
    size = path.stat().st_size
    warnings: list[str] = []
    role = surface_role(path)
    if path.suffix.lower() == ".md" and size > BUDGETS["large_markdown_bytes"]:
        warnings.append("large_markdown_surface")
    if path.suffix.lower() == ".json" and size > BUDGETS["large_json_bytes"]:
        warnings.append("large_json_surface")
    if size > BUDGETS["very_large_file_bytes"]:
        warnings.append("very_large_generated_file")
    if path.name == "THREADS.md" and size > BUDGETS["large_markdown_bytes"]:
        warnings.append("thread_index_bloat_candidate")
    return {
        "file": str(path.relative_to(ROOT)),
        "name": path.name,
        "suffix": path.suffix.lower(),
        "surface_role": role,
        "counts_toward_reader_route_budget": counts_toward_reader_route_budget(role),
        "bytes": size,
        "h1": h1(path),
        "warnings": warnings,
    }


def render_markdown(data: dict) -> str:
    lines = [
        "# Generated surface audit",
        "",
        f"Generated for `{data['revision']}` from the `generated/` directory.",
        "",
        "This audit flags reader-cost and package-weight risks. It separates first-reader route pressure from leaf test-matrix renders so matrix coverage is not mistaken for front-door sprawl.",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "| --- | ---: |",
        f"| Generated files scanned | {data['generated_file_count']} |",
        f"| Reader-route budget files | {data['reader_route_file_count']} |",
        f"| Leaf test-matrix render files | {data['leaf_test_matrix_file_count']} |",
        f"| Total generated bytes | {data['total_bytes']} |",
        f"| Files with warnings | {data['warning_file_count']} |",
        f"| Package warnings | {len(data.get('package_warnings', []))} |",
        "",
        "## Package warnings",
        "",
    ]
    if data.get("package_warnings"):
        for warning in data["package_warnings"]:
            lines.append(f"- `{warning}`")
    else:
        lines.append("- None.")
    lines.extend([
        "",
        "## Role counts",
        "",
        "| Role | Files | Bytes |",
        "| --- | ---: | ---: |",
    ])
    for role, count in data.get("surface_role_counts", {}).items():
        lines.append(f"| `{role}` | {count} | {data.get('surface_role_bytes', {}).get(role, 0)} |")
    lines.extend([
        "",
        "## Largest generated files",
        "",
        "| File | Bytes | Role | Warnings |",
        "| --- | ---: | --- | --- |",
    ])
    for row in data.get("largest_files", []):
        warnings = ", ".join(f"`{w}`" for w in row.get("warnings", [])) or "—"
        lines.append(f"| `{row['file']}` | {row['bytes']} | `{row.get('surface_role', '')}` | {warnings} |")
    lines.extend(["", "## Warning files", ""])
    warning_rows = [row for row in data.get("files", []) if row.get("warnings")]
    if not warning_rows:
        lines.append("- None.")
    for row in warning_rows:
        lines.append(f"- `{row['file']}` — {', '.join(row['warnings'])} ({row['bytes']} bytes)")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    GENERATED.mkdir(exist_ok=True)
    for name in SKIP_NAMES:
        path = GENERATED / name
        if path.exists():
            path.unlink()
    rows = [file_row(path) for path in sorted(GENERATED.rglob("*")) if path.is_file() and path.name not in SKIP_NAMES]
    suffix_counts: Counter[str] = Counter(row["suffix"] or "[none]" for row in rows)
    role_counts: Counter[str] = Counter(row["surface_role"] for row in rows)
    role_bytes: Counter[str] = Counter()
    for row in rows:
        role_bytes[row["surface_role"]] += row["bytes"]
    warning_counts: Counter[str] = Counter(warning for row in rows for warning in row.get("warnings", []))
    total_bytes = sum(row["bytes"] for row in rows)
    reader_route_file_count = sum(1 for row in rows if row.get("counts_toward_reader_route_budget"))
    leaf_test_matrix_file_count = sum(1 for row in rows if row.get("surface_role") == "leaf_test_matrix_render")
    package_warnings: list[str] = []
    if reader_route_file_count > BUDGETS["reader_route_file_count_warning"]:
        package_warnings.append("reader_route_file_count_budget_exceeded")
    if total_bytes > BUDGETS["total_generated_bytes_warning"]:
        package_warnings.append("total_generated_bytes_budget_exceeded")
    data = {
        "revision": current_revision(),
        "generated_at_utc": generated_at_utc(),
        "surface_audit_role": "reader-cost and generated-surface budget audit",
        "audit_refactor_note": "Leaf *_TESTS.json/md matrices are evidence-library renders; they are counted separately from first-reader route pressure.",
        "budgets": BUDGETS,
        "generated_file_count": len(rows),
        "reader_route_file_count": reader_route_file_count,
        "leaf_test_matrix_file_count": leaf_test_matrix_file_count,
        "total_bytes": total_bytes,
        "package_warnings": package_warnings,
        "suffix_counts": dict(sorted(suffix_counts.items())),
        "surface_role_counts": dict(sorted(role_counts.items())),
        "surface_role_bytes": dict(sorted(role_bytes.items())),
        "warning_counts": dict(sorted(warning_counts.items())),
        "warning_file_count": sum(1 for row in rows if row.get("warnings")),
        "largest_files": sorted(rows, key=lambda item: item["bytes"], reverse=True)[:20],
        "files": rows,
    }
    (GENERATED / "GENERATED_SURFACE_AUDIT.json").write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (GENERATED / "GENERATED_SURFACE_AUDIT.md").write_text(render_markdown(data), encoding="utf-8")
    print("OK: wrote generated/GENERATED_SURFACE_AUDIT.json and generated/GENERATED_SURFACE_AUDIT.md")


if __name__ == "__main__":
    main()
