#!/usr/bin/env python3
"""Require a default rebuild to leave every generated byte unchanged."""
from __future__ import annotations

import hashlib
import subprocess
import sys
from pathlib import Path

sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "generated"
BUILD_ALL = ROOT / "tools" / "build_all.py"


def hashes() -> dict[str, str]:
    if not GENERATED.exists():
        raise RuntimeError("generated/ does not exist; run the build first")
    return {
        str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(GENERATED.rglob("*"))
        if path.is_file()
    }


def main() -> None:
    before = hashes()
    completed = subprocess.run(
        [sys.executable, str(BUILD_ALL)],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        print("FAIL: reproducibility rebuild failed")
        if completed.stdout:
            print(completed.stdout, end="")
        if completed.stderr:
            print(completed.stderr, file=sys.stderr, end="")
        raise SystemExit(completed.returncode)

    after = hashes()
    added = sorted(set(after) - set(before))
    removed = sorted(set(before) - set(after))
    changed = sorted(path for path in set(before) & set(after) if before[path] != after[path])
    if added or removed or changed:
        print("FAIL: default build is not reproducible")
        if added:
            print(f"  added: {added[:20]}")
        if removed:
            print(f"  removed: {removed[:20]}")
        if changed:
            print(f"  changed: {changed[:20]}")
        raise SystemExit(1)

    print(f"OK: reproducible build passed ({len(after)} generated files byte-identical)")


if __name__ == "__main__":
    main()
