#!/usr/bin/env python3
from __future__ import annotations

COMMON_TEST_MATRICES = [
    {
        "metadata_filename": "credential_access_tests.json",
        "schema_const": "radical-governance-credential-access-tests-v1",
        "output_stem": "CREDENTIAL_ACCESS_TESTS",
        "title": "Credential-access tests matrix",
        "source_field": "credential_access_test_source",
        "front_door_key": "credential_access_tests",
        "use_rule": "Run credential-access tests whenever a public login, account, identity-proofing route, federation layer, passkey, wallet, delegated mandate, biometric check, or shared identity provider becomes a practical gate to a public service, entitlement, payment, notice, status proof, authorisation, filing, deadline, or representative action. Separate person, credential, account, session, mandate, entitlement, fallback, and service-owner duties before scoring access or denial.",
    },
    {
        "metadata_filename": "representative_access_tests.json",
        "schema_const": "radical-governance-representative-access-tests-v1",
        "output_stem": "REPRESENTATIVE_ACCESS_TESTS",
        "title": "Representative-access tests matrix",
        "source_field": "representative_access_test_source",
        "front_door_key": "representative_access_tests",
        "use_rule": "Run representative-access tests whenever a payee, appointee, guardian, attorney-in-fact, tax representative, professional authorisation, appeal representative, helper, caregiver, organisation, delegated account user, or informal proxy can receive notices, control money, submit claims, access records, bind filings, preserve deadlines, or speak for a person. Separate person, credential, authority, scope, capacity, wishes, revocation, fiduciary duty, payment control, and public-service outcome before accepting proxy action or denial.",
    },
    {
        "metadata_filename": "disaster_assistance_tests.json",
        "schema_const": "radical-governance-disaster-assistance-tests-v1",
        "output_stem": "DISASTER_ASSISTANCE_TESTS",
        "title": "Disaster-assistance tests matrix",
        "source_field": "disaster_assistance_test_source",
        "front_door_key": "disaster_assistance_tests",
        "use_rule": "Run disaster-assistance tests whenever a declared incident, emergency relief route, individual-assistance programme, household proof problem, insurance / duplication review, fraud screen, appeal, inter-program referral, recovery payment, or long-term recovery handoff can affect whether a survivor actually receives safe shelter, essential needs, repair support, or remaining-need help. Separate declaration, household eligibility, proof state, denial reason, appeal clock, handoff receipt, payment receipt, fraud-control harm, and recovery outcome before scoring aid as delivered or a case as closed.",
    },
    {
        "metadata_filename": "unemployment_insurance_tests.json",
        "schema_const": "radical-governance-unemployment-insurance-tests-v1",
        "output_stem": "UNEMPLOYMENT_INSURANCE_TESTS",
        "title": "Unemployment-insurance integrity and access tests matrix",
        "source_field": "unemployment_insurance_test_source",
        "front_door_key": "unemployment_insurance_tests",
        "use_rule": "Run unemployment-insurance tests whenever UI claims, pandemic or emergency benefit programs, identity proofing, payment holds, fraud controls, overpayment notices, waivers, appeals, recovery actions, state IT modernization, or public integrity dashboards can determine whether a valid claimant is paid or a fraudulent claim is stopped. Separate claim issue state, identity route, payment reason, fraud signal, overpayment category, waiver, appeal, recovery, and state performance before scoring blocked payment as integrity or paid benefit as success.",
    },
    {
        "metadata_filename": "watchlist_border_tests.json",
        "schema_const": "radical-governance-watchlist-border-tests-v1",
        "output_stem": "WATCHLIST_BORDER_TESTS",
        "title": "Watchlist / border / law-enforcement automation tests",
        "source_field": "watchlist_border_tests_source",
        "front_door_key": "watchlist_border_tests",
        "use_rule": "Use these tests when watchlists, border screening, biometric candidates, NCIC / nonfederal alerts, mobile field capture, DHS TRIP redress, or AI / facial-recognition inventories shape liberty, travel, immigration, police, or public-safety consequences. A match opens an inquiry lane; it does not itself prove identity, threat, authority, or remedy completion.",
    },
    {
        "metadata_filename": "public_ai_register_tests.json",
        "schema_const": "radical-governance-public-ai-register-tests-v1",
        "output_stem": "PUBLIC_AI_REGISTER_TESTS",
        "title": "Public AI register maintenance tests matrix",
        "source_field": "public_ai_register_test_source",
        "front_door_key": "public_ai_register_tests",
        "use_rule": "Run public-AI-register tests whenever an AI inventory, algorithmic transparency record, high-risk AI database entry, agency AI page, public/internal inventory split, COTS AI rollup, high-impact count, missing row, paused tool, or withdrawn row is cited as evidence. Separate source-of-truth hierarchy, public/internal/exempt reconciliation, lifecycle state, risk classification, authority, procurement, model/data/vendor drift, monitoring, incident, redress, machine-readable row identity, and retirement receipts before treating a listing as governance or an absence as non-use.",
    },
    {
        "metadata_filename": "subnational_ai_tests.json",
        "schema_const": "radical-governance-subnational-ai-tests-v1",
        "output_stem": "SUBNATIONAL_AI_TESTS",
        "title": "Subnational AI and local digital-government tests matrix",
        "source_field": "subnational_ai_test_source",
        "front_door_key": "subnational_ai_tests",
        "use_rule": "Run subnational-AI tests whenever a state statute, municipal algorithmic-tool report, local AI pilot, high-risk ADS inventory, school or court AI policy, public-records route, procurement file, police/vendor tool, permitting workflow, benefits workflow, or no-use statement is cited as proof of public-service accountability. Separate jurisdiction, authority, workflow consequence, records, procurement, affected-person route, school/court boundaries, enforcement escalation, pilot lifecycle, and public metrics before treating a local pilot, policy, inventory, or no-use statement as governance.",
    },
    {
        "metadata_filename": "global_south_source_tests.json",
        "schema_const": "radical-governance-global-south-source-tests-v1",
        "output_stem": "GLOBAL_SOUTH_SOURCE_TESTS",
        "title": "Non-English / Global South official-source tests matrix",
        "source_field": "global_south_source_test_source",
        "front_door_key": "global_south_source_tests",
        "use_rule": "Run non-English / Global South source tests whenever an official source, translated source, machine-translated service page, national digital ID, document-wallet route, social-benefit registry, public-service AI plan, pending AI bill, donor / benchmark summary, or country comparator is used as proof of law, service access, identity, benefit payment, notice, correction, appeal, or implementation. Separate source language, translation status, publication state, claim class, currentness, identity / benefit consequence, local implementation, and remedy before citing a summary as authority.",
    },
    {
        "metadata_filename": "climate_utility_tests.json",
        "schema_const": "radical-governance-climate-utility-tests-v1",
        "output_stem": "CLIMATE_UTILITY_TESTS",
        "title": "Climate / utility shutoff and medical-baseline continuity tests matrix",
        "source_field": "climate_utility_test_source",
        "front_door_key": "climate_utility_tests",
        "use_rule": "Run climate / utility tests whenever utility final notices, nonpayment shutoffs, reconnections, LIHEAP or state energy assistance, medical-baseline or serious-illness certificates, electricity-dependent equipment, refrigerated medication, heat / cold / smoke / storm risk, PSPS / de-energization, outage maps, cooling or warming centers, backup power, transport, or emergency-management outreach can determine whether a household actually retains life-safety utility continuity. Separate account, medical, assistance, hazard, notice, backup, reconnection, and aftercare states before treating an account code, certificate, map, award, or notice as safety.",
    },
    {
        "metadata_filename": "software_cyber_continuity_tests.json",
        "schema_const": "radical-governance-software-cyber-continuity-tests-v1",
        "output_stem": "SOFTWARE_CYBER_CONTINUITY_TESTS",
        "title": "Software / cyber incident public-service continuity tests matrix",
        "source_field": "software_cyber_continuity_test_source",
        "front_door_key": "software_cyber_continuity_tests",
        "use_rule": "Use when a cyber incident, ransomware event, software supply-chain assurance claim, SBOM, secure-software attestation, hardware/software inventory, privileged supplier access, cloud/runtime dependency, KEV/vulnerability exposure, breach notification, degraded mode, public-service outage, payment/clinical/access disruption, recovery statement, or supplier concentration risk can affect service continuity.",
    },
    {
        "metadata_filename": "housing_continuity_tests.json",
        "schema_const": "radical-governance-housing-continuity-tests-v1",
        "output_stem": "HOUSING_CONTINUITY_TESTS",
        "title": "Housing stability / eviction / rental-assistance continuity tests matrix",
        "source_field": "housing_continuity_test_source",
        "front_door_key": "housing_continuity_tests",
        "use_rule": "Run housing-continuity tests whenever rental assistance, eviction notices, court filings, possession clocks, right-to-counsel routes, tenant-screening reports, shelter referrals, relocation, voucher / subsidy cliffs, landlord ledgers, or informal displacement can determine whether a household is actually stably housed. Separate household, unit, arrears, assistance, court, possession, representation, screening, shelter, and tail-risk states before treating a portal, docket, report, or referral as housing stability.",
    },
    {
        "metadata_filename": "health_benefit_tests.json",
        "schema_const": "radical-governance-health-benefit-tests-v1",
        "output_stem": "HEALTH_BENEFIT_TESTS",
        "title": "Health-benefit and prescription-drug transition tests matrix",
        "source_field": "health_benefit_test_source",
        "front_door_key": "health_benefit_tests",
        "use_rule": "Run health-benefit tests whenever Medicaid, CHIP, Marketplace, Medicare, Part D, managed-care, pharmacy-benefit, formulary, prior-authorization, transition-fill, exception, appeal, Extra Help / LIS, payment-plan, premium, document-verification, or pharmacy point-of-sale state can interrupt treatment. Separate eligibility, enrollment, payer, plan, formulary, utilization-management, cost, notice, representative, treatment, and repair states before treating coverage or medication as continuous.",
    },
    {
        "metadata_filename": "election_continuity_tests.json",
        "schema_const": "radical-governance-election-continuity-tests-v1",
        "output_stem": "ELECTION_CONTINUITY_TESTS",
        "title": "Election administration / vote-continuity tests matrix",
        "source_field": "election_continuity_test_source",
        "front_door_key": "election_continuity_tests",
        "use_rule": "Run election-continuity tests whenever voter registration, list maintenance, ballot style, mail or absentee voting, UOCAVA, drop boxes, polling places, e-pollbooks, voting systems, accessibility, provisional or challenged ballots, signature/ID cure, tabulation, audits, canvass, certification, recounts, contests, election websites, USPS Election Mail, or cyber/physical election-security services can determine whether an eligible voter cast a countable ballot and whether the result surface is administratively trustworthy. Separate eligibility, registration, ballot, channel, accessibility, custody, cure, count, audit, certification, contest, and remedy states before treating a status row, result feed, audit label, or certified total as election proof.",
    },

    {
        "metadata_filename": "child_welfare_tests.json",
        "schema_const": "radical-governance-child-welfare-tests-v1",
        "output_stem": "CHILD_WELFARE_TESTS",
        "title": "Child welfare / foster care continuity tests matrix",
        "source_field": "child_welfare_test_source",
        "front_door_key": "child_welfare_tests",
        "use_rule": "Run child-welfare tests whenever a maltreatment report, investigation, safety plan, removal, prevention service, placement change, missing-from-care episode, psychotropic medication, congregate/out-of-state placement, permanency decision, or transition deadline can affect a child or family. Separate safety, family support, legal authority, placement suitability, health, education, missing-from-care response, youth voice, permanency, and oversight denominators before accepting protection claims.",
    },
{
    "metadata_filename": "custody_reentry_tests.json",
    "schema_const": "radical-governance-custody-reentry-tests-v1",
    "output_stem": "CUSTODY_REENTRY_TESTS",
    "title": "Custody / corrections / release / reentry continuity tests matrix",
    "source_field": "custody_reentry_test_source",
    "front_door_key": "custody_reentry_tests",
    "use_rule": "Run custody/reentry tests whenever booking, detention, jail/prison custody, transfer, classification, medical/MOUD need, death or serious injury, release calculation, First Step Act or sentence credits, Medicaid reentry, ID documents, RRC/home confinement, housing, supervision, electronic monitoring, or reentry referrals can affect liberty, safety, health, accountability, or community return. Separate legal authority, intake risk, conditions, health, incident reporting, communication/counsel, release execution, benefits/IDs, housing/treatment, supervision, and source posture before treating a custody row, count, release date, or referral as proof.",
},
    {
        "metadata_filename": "long_term_care_tests.json",
        "schema_const": "radical-governance-long-term-care-tests-v1",
        "output_stem": "LONG_TERM_CARE_TESTS",
        "title": "Long-term services/supports and care-continuity tests matrix",
        "source_field": "long_term_care_test_source",
        "front_door_key": "long_term_care_tests",
        "use_rule": "Run long-term-care tests whenever nursing-home provider data, Care Compare ratings, SFF status, staffing rules or repeals, facility-initiated discharge, HCBS enrollment or quality measures, APS/NAMRS data, ombudsman routes, guardianship/fiduciary authority, assisted-living/residential settings, home care, emergency evacuation, closure, medication, restraints, resident rights, or family/caregiver continuity can affect older adults or people with disabilities. Separate setting, authority, care delivery, staffing, rights, APS, ombudsman, transfer/discharge, HCBS, guardianship, emergency, and source-currentness before treating a facility row, HCBS slot, intake, guardian order, or rating as care.",
    },

    {
        "metadata_filename": "special_education_tests.json",
        "schema_const": "radical-governance-special-education-tests-v1",
        "output_stem": "SPECIAL_EDUCATION_TESTS",
        "title": "Special education / IEP / Section 504 continuity tests matrix",
        "source_field": "special_education_test_source",
        "front_door_key": "special_education_tests",
        "use_rule": "Run special-education tests whenever an IEP, Section 504 plan, eligibility label, evaluation, related-service grid, LRE percentage, assistive technology, transport, discipline removal, restraint, seclusion, law-enforcement referral, Part C/Part B transition, graduation/age-out, dispute-resolution route, or federal/state aggregate source is cited as proof that a student received FAPE or equal access. Separate legal lane, evaluation, plan, delivered service, accessibility, discipline, transition, remedy, and source-currentness before treating a row, plan, determination, or dataset as education continuity.",
    },

    {
        "metadata_filename": "water_sanitation_tests.json",
        "schema_const": "radical-governance-water-sanitation-tests-v1",
        "output_stem": "WATER_SANITATION_TESTS",
        "title": "Water and sanitation continuity tests matrix",
        "source_field": "water_sanitation_test_source",
        "front_door_key": "water_sanitation_tests",
        "use_rule": "Run water/sanitation tests whenever drinking-water system rows, SDWIS/ECHO data, Consumer Confidence Reports, lead service line inventories, PFAS rules, boil/do-not-drink/do-not-use advisories, AWIA risk/resilience plans, wastewater/septic/stormwater records, water shutoffs, affordability burdens, cyber/OT incidents, emergency supply, or critical-facility water dependencies can determine whether people actually have safe water and sanitation. Separate user, premise, source, treatment, contaminant, notice, wastewater, emergency, cyber, affordability, and remedy states before treating a compliance row, report, inventory, permit, or certification as safe water.",
    },

    {
        "metadata_filename": "food_nutrition_tests.json",
        "schema_const": "radical-governance-food-nutrition-tests-v1",
        "output_stem": "FOOD_NUTRITION_TESTS",
        "title": "Food and nutrition assistance continuity tests matrix",
        "source_field": "food_nutrition_test_source",
        "front_door_key": "food_nutrition_tests",
        "use_rule": "Run food/nutrition continuity tests whenever SNAP, WIC, school meals, CACFP, SFSP, Summer EBT/SUN Bucks, D-SNAP, replacement benefits, EBT/eWIC cards, stolen benefits, retailer access, formula/food packages, disaster feeding, or food-security statistics are cited as proof that people received timely, usable food. Separate participant identity, eligibility clocks, issuance, card security, retailer access, WIC service, child meals, summer/disaster routes, integrity/remedy, outcome, and source-currentness before treating benefit rows, data tables, meal counts, plans, waivers, dashboards, or retailer rows as food security.",
    },

    {
        "metadata_filename": "emergency_response_tests.json",
        "schema_const": "radical-governance-emergency-response-tests-v1",
        "output_stem": "EMERGENCY_RESPONSE_TESTS",
        "title": "Emergency response / 911 / EMS / 988 / public alerting continuity tests matrix",
        "source_field": "emergency_response_test_source",
        "front_door_key": "emergency_response_tests",
        "use_rule": "Run emergency-response continuity tests whenever 911, text-to-911, RTT, VoIP/wireless routing, PSAP answer, NG911 profile, FCC reliability/location/outage evidence, CAD dispatch, radio/MDT delivery, EMS/NEMSIS data, 988 contact metrics, mobile crisis, IPAWS, WEA/EAS, outage, cyber, power, language/accessibility, or after-action records are cited as proof that help reached people. Separate caller/person, channel, routing, location, dispatch, responder, care, crisis, alert, degraded-mode, equity, remedy, and source-currentness before treating a call, dispatch, contact, alert, or dataset as rescue.",
    },


    {
        "metadata_filename": "transportation_mobility_tests.json",
        "schema_const": "radical-governance-transportation-mobility-tests-v1",
        "output_stem": "TRANSPORTATION_MOBILITY_TESTS",
        "title": "Transportation / transit / paratransit mobility-continuity tests matrix",
        "source_field": "transportation_mobility_test_source",
        "front_door_key": "transportation_mobility_tests",
        "use_rule": "Run transportation/mobility tests whenever fixed-route transit, paratransit, GTFS, National Transit Map, NTD rows, fare systems, reduced-fare credentials, ADA, Title VI, PTASP, TAM, rural/tribal transit, service changes, disruptions, station/stop accessibility, shuttles, safety incidents, or complaints are cited as proof that people can travel. Separate rider, trip purpose, origin/destination, stop/station path, schedule/realtime, vehicle/operator, fare, paratransit, equity, safety, assets, rural/tribal access, remedy, and source-currentness before treating a scheduled trip, map, boarding, eligibility, plan, target, or complaint form as mobility.",
    },

    {
        "metadata_filename": "broadband_connectivity_tests.json",
        "schema_const": "radical-governance-broadband-connectivity-tests-v1",
        "output_stem": "BROADBAND_CONNECTIVITY_TESTS",
        "title": "Broadband / telecommunications / digital-access continuity tests matrix",
        "source_field": "broadband_connectivity_test_source",
        "front_door_key": "broadband_connectivity_tests",
        "use_rule": "Run broadband/connectivity tests whenever a coverage map, Broadband Serviceable Location, provider availability claim, speed tier, broadband label, Lifeline/National Verifier row, ACP history, BEAD milestone, public Wi-Fi fallback, outage filing, portal dependency, or digital-access complaint is cited as proof that a person can use public services online. Separate household, address, serviceability, affordability, subsidy, device, performance, outage, portal task, fallback, remedy, and source-currentness before treating a polygon, row, label, dashboard, or filing as access.",
    },

    {
        "metadata_filename": "veterans_continuity_tests.json",
        "schema_const": "radical-governance-veterans-continuity-tests-v1",
        "output_stem": "VETERANS_CONTINUITY_TESTS",
        "title": "Veterans benefits / care / support continuity tests matrix",
        "source_field": "veterans_continuity_test_source",
        "front_door_key": "veterans_continuity_tests",
        "use_rule": "Run veterans-continuity tests whenever VA claims, ratings, PACT Act evidence, health-care eligibility, community care, appeals, EHRM, crisis lines, homelessness programs, GI Bill, caregiver support, survivor/dependent benefits, or VA digital-status surfaces are cited as proof that a veteran, survivor, dependent, caregiver, or family received support. Separate person, claim, exam, rating, appeal, care, authorization, records, housing, crisis, education, caregiver, payment, remedy, and source-currentness before treating a claim row, rating, dashboard, eligibility, authorization, docket, voucher, certification, or caregiver row as support.",
    },

    {
        "metadata_filename": "immigration_status_tests.json",
        "schema_const": "radical-governance-immigration-status-tests-v1",
        "output_stem": "IMMIGRATION_STATUS_TESTS",
        "title": "Immigration / asylum / status continuity tests matrix",
        "source_field": "immigration_status_test_source",
        "front_door_key": "immigration_status_tests",
        "use_rule": "Run immigration-status tests whenever USCIS receipts, case-status pages, processing times, I-589 asylum filings, I-765 work-authorization applications, asylum EAD-clock evidence, USCIS/EOIR address changes, immigration-court dockets, Respondent Access/ECAS/eROP records, SAVE responses, CaseCheck, detention/release, or downstream benefit/license/work/school decisions are cited as proof that a person has status, work authorization, notice, hearing safety, access, or remedy. Separate person, case, notice, filing, asylum/protection, work, court, SAVE/downstream, digital access, custody, representative, and repair states before treating a receipt, docket, clock, address form, portal, or verification response as status.",
    },


    {
        "metadata_filename": "tax_refund_tests.json",
        "schema_const": "radical-governance-tax-refund-tests-v1",
        "output_stem": "TAX_REFUND_TESTS",
        "title": "Tax filing / refund / credit continuity tests matrix",
        "source_field": "tax_refund_test_source",
        "front_door_key": "tax_refund_tests",
        "use_rule": "Run tax-refund continuity tests whenever federal or state tax return rows, IRS filing-season data, Where's My Refund, refund transcripts, EITC, CTC, ACTC, refundable credits, ITIN applications/renewals, IP PINs, identity-theft victim assistance, direct deposit, paper checks, Treasury offsets, Free File, VITA/TCE, Taxpayer Assistance Centers, TAS cases, notices, audits, math-error corrections, or appeal deadlines are cited as proof that a household received tax relief. Separate taxpayer, return, credit, identity/ITIN, refund/payment, offset, notice/appeal, assisted access, and hardship outcome before treating a return, tracker, schedule, PIN, or offset row as relief.",
    },

    {
        "metadata_filename": "consumer_finance_tests.json",
        "schema_const": "radical-governance-consumer-finance-tests-v1",
        "output_stem": "CONSUMER_FINANCE_TESTS",
        "title": "Consumer finance / credit / debt / account continuity tests matrix",
        "source_field": "consumer_finance_test_source",
        "front_door_key": "consumer_finance_tests",
        "use_rule": "Run consumer-finance continuity tests whenever a banked or unbanked status, checking/savings/prepaid/card account, direct deposit, ACH/debit/EFT transaction, overdraft/fee, credit report, score, consumer report, debt validation notice, collector contact, garnishment, complaint ID, CFPB/OCC/FTC/state routing, or company response is cited as proof of financial access or remedy. Separate person, account, transaction, credit file, furnisher, debt owner, collector, complaint, regulator, correction, money receipt, and downstream public-service outcome before accepting the row as access.",
    },
    {
        "metadata_filename": "service_home_tests.json",
        "schema_const": "radical-governance-service-home-tests-v1",
        "output_stem": "SERVICE_HOME_TESTS",
        "title": "Service-home governance tests matrix",
        "source_field": "service_home_test_source",
        "front_door_key": "service_home_tests",
        "use_rule": "Run service-home tests whenever a metropolitan, regional, joint-powers, shared-service, functional-authority, concession, operator-chain, or cross-boundary service arrangement is cited as proof that a territory has an honest service home. Separate service map, authority, operator, regulator, commissioner, contractor, front door, complaint handoff, continuity, source boundary, and route-absorption parity before treating the arrangement as service government.",
    },

]

COMMON_TEST_MATRIX_BY_OUTPUT = {spec["output_stem"]: spec for spec in COMMON_TEST_MATRICES}
