#!/usr/bin/env bash
set -euo pipefail

if [[ ${1:-} == --help ]]; then
    cat <<'HELP'
Usage: tools/run-ratox-impairment-lab.sh

Runs the Ratox latency/carrier experiment through two disposable endpoint
network namespaces. Only namespace egress qdiscs are shaped; no qdisc is ever
attached to a physical or host interface. The default matrix crosses native
UDP and forced TCP-relay transport with these profiles:

  baseline     no delay or loss, netem limit 1000
  delay40      40 ms +/- 10 ms normally distributed delay
  adversity    delay40 plus 2% loss, 0.5% duplication, and 5% reordering
  constrained  delay40 plus 1% loss, a 4 Mbit/s ceiling, and queue limit 64

Environment:
  IOTOX_BINARY                    source-linked standalone executable
  IOTOX_IMPAIRMENT_PROFILES       comma list (default all profiles above)
  IOTOX_IMPAIRMENT_MODES          comma list containing udp and/or tcp
  IOTOX_IMPAIRMENT_SAMPLES        single probes per carrier/state (default 24)
  IOTOX_IMPAIRMENT_BURST_COUNT    probes per custom carrier/state (default 64)
  IOTOX_IMPAIRMENT_BURST_SPACING_MS                       (default 2)
  IOTOX_IMPAIRMENT_BURST_PACKET_BYTES                     (default 10)
  IOTOX_IMPAIRMENT_DEADLINE_MS    per-probe response deadline (default 2500)
  IOTOX_IMPAIRMENT_BYTES          bulk payload bytes (default 8388608)
  IOTOX_IMPAIRMENT_CONSTRAINED_BYTES                      (default 4194304)
  IOTOX_IMPAIRMENT_TIMEOUT_SECONDS                       (default 420)
  IOTOX_IMPAIRMENT_REPORT_DIR     private output directory

Requires noninteractive sudo, iproute2 netem, iptables, and setpriv. Cleanup
removes only names generated by this invocation and its exact NAT rule.
HELP
    exit 0
fi

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
binary=${IOTOX_BINARY:-"$root/dist/standalone/iotox"}
profiles_spec=${IOTOX_IMPAIRMENT_PROFILES:-baseline,delay40,adversity,constrained}
modes_spec=${IOTOX_IMPAIRMENT_MODES:-udp,tcp}
samples=${IOTOX_IMPAIRMENT_SAMPLES:-24}
burst_count=${IOTOX_IMPAIRMENT_BURST_COUNT:-64}
burst_spacing_ms=${IOTOX_IMPAIRMENT_BURST_SPACING_MS:-2}
burst_packet_bytes=${IOTOX_IMPAIRMENT_BURST_PACKET_BYTES:-10}
deadline_ms=${IOTOX_IMPAIRMENT_DEADLINE_MS:-2500}
normal_bytes=${IOTOX_IMPAIRMENT_BYTES:-8388608}
constrained_bytes=${IOTOX_IMPAIRMENT_CONSTRAINED_BYTES:-4194304}
timeout_seconds=${IOTOX_IMPAIRMENT_TIMEOUT_SECONDS:-420}
report_dir=${IOTOX_IMPAIRMENT_REPORT_DIR:-"$root/build/ratox-impairment-lab"}

for command in sudo ip tc iptables setpriv sha256sum flock; do
    command -v "$command" >/dev/null 2>&1 || {
        printf 'required command not found: %s\n' "$command" >&2
        exit 2
    }
done
sudo -n true || {
    printf '%s\n' 'noninteractive sudo is required' >&2
    exit 2
}
[[ -x "$binary" ]] || {
    printf 'source-linked binary not found: %s\n' "$binary" >&2
    exit 2
}
for value_name in samples burst_count burst_spacing_ms burst_packet_bytes deadline_ms normal_bytes \
                  constrained_bytes timeout_seconds; do
    value=${!value_name}
    [[ "$value" =~ ^[0-9]+$ ]] || {
        printf '%s must be an unsigned integer\n' "$value_name" >&2
        exit 2
    }
done
(( samples >= 1 && samples <= 10000 )) || exit 2
(( burst_count >= 1 && burst_count <= 128 )) || exit 2
(( burst_spacing_ms <= 1000 && deadline_ms >= 1 && deadline_ms <= 10000 )) || exit 2
(( burst_packet_bytes >= 10 && burst_packet_bytes <= 1200 )) || exit 2
(( normal_bytes >= 4096 && normal_bytes % 4 == 0 )) || exit 2
(( constrained_bytes >= 4096 && constrained_bytes % 4 == 0 )) || exit 2
(( timeout_seconds >= 1 )) || exit 2

IFS=, read -r -a profiles <<<"$profiles_spec"
declare -A known_profile=(
    [baseline]=1 [delay40]=1 [adversity]=1 [constrained]=1
)
for profile in "${profiles[@]}"; do
    [[ ${known_profile[$profile]:-0} == 1 ]] || {
        printf 'unknown impairment profile: %s\n' "$profile" >&2
        exit 2
    }
done
IFS=, read -r -a modes <<<"$modes_spec"
for mode in "${modes[@]}"; do
    [[ "$mode" == udp || "$mode" == tcp ]] || {
        printf 'unknown transport mode: %s\n' "$mode" >&2
        exit 2
    }
done

install -d -m 0700 "$report_dir"
exec 9>"$report_dir/.lock"
chmod 0600 "$report_dir/.lock"
flock -n 9 || {
    printf 'another impairment lab owns %s\n' "$report_dir" >&2
    exit 2
}

tag=$(printf '%05x' "$(( (BASHPID ^ $(date +%s)) & 1048575 ))")
ns_a="itxa$tag"
ns_b="itxb$tag"
bridge="itxbr$tag"
veth_a="itxva$tag"
veth_b="itxvb$tag"
third_octet=$((200 + (16#$tag % 40)))
subnet="10.254.$third_octet.0/24"
gateway="10.254.$third_octet.1"
address_a="10.254.$third_octet.2"
address_b="10.254.$third_octet.3"
uplink=$(ip -4 -o route show default | awk 'NR == 1 {print $5}')
[[ -n "$uplink" ]] || {
    printf '%s\n' 'no IPv4 default-route uplink found' >&2
    exit 2
}
for name in "$ns_a" "$ns_b"; do
    ! sudo -n ip netns list | awk '{print $1}' | grep -Fxq "$name" || {
        printf 'generated namespace collision: %s\n' "$name" >&2
        exit 2
    }
done
for name in "$bridge" "$veth_a" "$veth_b"; do
    ! ip link show dev "$name" >/dev/null 2>&1 || {
        printf 'generated interface collision: %s\n' "$name" >&2
        exit 2
    }
done
! ip -4 route show | grep -Fq "$subnet" || {
    printf 'generated subnet collides with a host route: %s\n' "$subnet" >&2
    exit 2
}

nat_added=0
network_created=0
manifest_stage=
cleanup() {
    local status=$?
    trap - EXIT INT TERM
    if (( nat_added == 1 )); then
        sudo -n iptables -t nat -D POSTROUTING -s "$subnet" -o "$uplink" \
            -j MASQUERADE >/dev/null 2>&1 || true
    fi
    if (( network_created == 1 )); then
        sudo -n ip netns pids "$ns_a" 2>/dev/null | xargs -r sudo -n kill >/dev/null 2>&1 || true
        sudo -n ip netns pids "$ns_b" 2>/dev/null | xargs -r sudo -n kill >/dev/null 2>&1 || true
        sudo -n ip netns del "$ns_a" >/dev/null 2>&1 || true
        sudo -n ip netns del "$ns_b" >/dev/null 2>&1 || true
        sudo -n ip link del "$veth_a" >/dev/null 2>&1 || true
        sudo -n ip link del "$veth_b" >/dev/null 2>&1 || true
        sudo -n ip link del "$bridge" >/dev/null 2>&1 || true
    fi
    [[ -z "$manifest_stage" ]] || rm -f -- "$manifest_stage"
    exit "$status"
}
trap cleanup EXIT INT TERM

sudo -n ip link add "$bridge" type bridge
network_created=1
sudo -n ip addr add "$gateway/24" dev "$bridge"
sudo -n ip link set "$bridge" up
sudo -n ip netns add "$ns_a"
sudo -n ip netns add "$ns_b"
sudo -n ip link add "$veth_a" type veth peer name eth0 netns "$ns_a"
sudo -n ip link add "$veth_b" type veth peer name eth0 netns "$ns_b"
sudo -n ip link set "$veth_a" master "$bridge"
sudo -n ip link set "$veth_b" master "$bridge"
sudo -n ip link set "$veth_a" up
sudo -n ip link set "$veth_b" up
for spec in "$ns_a:$address_a" "$ns_b:$address_b"; do
    namespace=${spec%%:*}
    address=${spec#*:}
    sudo -n ip -n "$namespace" link set lo up
    sudo -n ip -n "$namespace" link set eth0 up
    sudo -n ip -n "$namespace" addr add "$address/24" dev eth0
    sudo -n ip -n "$namespace" route add default via "$gateway"
done
sudo -n iptables -t nat -A POSTROUTING -s "$subnet" -o "$uplink" -j MASQUERADE
nat_added=1

run_id=$(date -u +%Y%m%dT%H%M%SZ)-$tag
manifest="$report_dir/matrix-$run_id.tsv"
manifest_stage="$manifest.stage"
: >"$manifest_stage"
chmod 0600 "$manifest_stage"
record() { printf '%s\n' "$1" >>"$manifest_stage"; }
record $'schema\tiotox-ratox-impairment-matrix-v1'
record $'run-id\t'"$run_id"
record $'binary-sha256\t'"$(sha256sum "$binary" | cut -d' ' -f1)"
record $'profiles\t'"$profiles_spec"
record $'modes\t'"$modes_spec"
record $'samples-per-carrier-state\t'"$samples"
record $'burst-count-per-custom-carrier-state\t'"$burst_count"
record $'burst-spacing-ms\t'"$burst_spacing_ms"
record $'burst-packet-bytes\t'"$burst_packet_bytes"
record $'deadline-ms\t'"$deadline_ms"
record $'topology\ttwo-private-network-namespaces-one-private-bridge'
record $'shaping-boundary\teach-endpoint-namespace-egress-eth0-only'
record $'host-physical-qdisc-touched\tno'

apply_profile() {
    local namespace=$1 profile=$2 seed=$3
    sudo -n ip netns exec "$namespace" tc qdisc del dev eth0 root \
        >/dev/null 2>&1 || true
    case "$profile" in
        baseline)
            sudo -n ip netns exec "$namespace" tc qdisc add dev eth0 root \
                netem limit 1000 seed "$seed"
            ;;
        delay40)
            sudo -n ip netns exec "$namespace" tc qdisc add dev eth0 root \
                netem limit 1000 delay 40ms 10ms distribution normal seed "$seed"
            ;;
        adversity)
            sudo -n ip netns exec "$namespace" tc qdisc add dev eth0 root \
                netem limit 256 delay 40ms 10ms distribution normal \
                loss random 2% duplicate 0.5% reorder 5% 50% seed "$seed"
            ;;
        constrained)
            sudo -n ip netns exec "$namespace" tc qdisc add dev eth0 root \
                netem limit 64 delay 40ms 10ms distribution normal \
                loss random 1% rate 4mbit seed "$seed"
            ;;
    esac
}

run_index=0
for mode in "${modes[@]}"; do
    for profile in "${profiles[@]}"; do
        run_index=$((run_index + 1))
        seed_a=$((151515 + run_index * 2))
        seed_b=$((seed_a + 1))
        apply_profile "$ns_a" "$profile" "$seed_a"
        apply_profile "$ns_b" "$profile" "$seed_b"
        report="$report_dir/$run_id-$mode-$profile.tsv"
        qdisc_before_a=$(sudo -n ip netns exec "$ns_a" tc -s qdisc show dev eth0 | tr '\n' ';')
        qdisc_before_b=$(sudo -n ip netns exec "$ns_b" tc -s qdisc show dev eth0 | tr '\n' ';')
        printf 'running mode=%s profile=%s report=%s\n' "$mode" "$profile" "$report"
        payload_bytes=$normal_bytes
        [[ "$profile" != constrained ]] || payload_bytes=$constrained_bytes
        tcp_only=0
        [[ "$mode" != tcp ]] || tcp_only=1
        IOTOX_BINARY="$binary" \
        IOTOX_FOUR_ROUTE_A_NETNS="$ns_a" \
        IOTOX_FOUR_ROUTE_B_NETNS="$ns_b" \
        IOTOX_FOUR_ROUTE_TCP_ONLY="$tcp_only" \
        IOTOX_FOUR_ROUTE_KEYS=reuse \
        IOTOX_FOUR_ROUTE_LATENCY_ONLY=1 \
        IOTOX_FOUR_ROUTE_LATENCY_SAMPLES="$samples" \
        IOTOX_FOUR_ROUTE_LATENCY_SEED="$seed_a" \
        IOTOX_FOUR_ROUTE_LATENCY_PROFILE="$profile" \
        IOTOX_FOUR_ROUTE_BURST_COUNT="$burst_count" \
        IOTOX_FOUR_ROUTE_BURST_SPACING_MS="$burst_spacing_ms" \
        IOTOX_FOUR_ROUTE_BURST_PACKET_BYTES="$burst_packet_bytes" \
        IOTOX_FOUR_ROUTE_PROBE_DEADLINE_MS="$deadline_ms" \
        IOTOX_FOUR_ROUTE_BYTES="$payload_bytes" \
        IOTOX_FOUR_ROUTE_TRIALS=1 \
        IOTOX_FOUR_ROUTE_TIMEOUT_SECONDS="$timeout_seconds" \
        IOTOX_FOUR_ROUTE_REPORT="$report" \
            "$root/tools/run-four-route-lab.sh" --reuse-keys
        qdisc_after_a=$(sudo -n ip netns exec "$ns_a" tc -s qdisc show dev eth0 | tr '\n' ';')
        qdisc_after_b=$(sudo -n ip netns exec "$ns_b" tc -s qdisc show dev eth0 | tr '\n' ';')
        report_sha=$(sha256sum "$report" | cut -d' ' -f1)
        record $'run\t'"$mode"$'\t'"$profile"$'\tseed-a\t'"$seed_a"$'\tseed-b\t'"$seed_b"$'\tpayload-bytes\t'"$payload_bytes"$'\treport\t'"$(basename "$report")"$'\tsha256\t'"$report_sha"
        record $'qdisc-before-a\t'"$mode"$'\t'"$profile"$'\t'"$qdisc_before_a"
        record $'qdisc-before-b\t'"$mode"$'\t'"$profile"$'\t'"$qdisc_before_b"
        record $'qdisc-after-a\t'"$mode"$'\t'"$profile"$'\t'"$qdisc_after_a"
        record $'qdisc-after-b\t'"$mode"$'\t'"$profile"$'\t'"$qdisc_after_b"
    done
done
record $'matrix\tpass'
mv -- "$manifest_stage" "$manifest"
manifest_stage=
printf 'manifest=%s\n' "$manifest"
