#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path


REQUIRED = [
    "docs/EXPERIMENT_CATALOG.md",
    "docs/TRANCHES_SUMMARY.md",
    "docs/COMMAND_INVENTORY.md",
    "docs/VALIDATOR_INVENTORY.md",
    "docs/POLICY_INVENTORY.md",
    "docs/SCHEMA_INVENTORY.md",
    "docs/COOPERATION_BENCHMARK_CARD_REVIEW_QUEUE.md",
    "docs/COOPERATION_BENCHMARK_CARD_MACRO_REVIEW_QUEUE.md",
    "docs/COOPERATION_BENCHMARK_CARD_CITATION_SURFACE.md",
    "docs/COOPERATION_BENCHMARK_CARD_SCOPE_SURFACE.md",
    "docs/ARTIFACT_BUCKETS.md",
    "docs/CLAIM_MATRIX.md",
    "docs/CLAIM_REGISTER.md",
    "docs/RISK_REGISTER.md",
    "docs/RUST_TEST_CONTRACTS.md",
    "docs/RUST_TEST_SCENARIO_COVERAGE.md",
    "docs/RUST_GAP_WITNESS_QUEUE.md",
    "docs/RUST_GAP_PROBE_SEED_INDEX.md",
    "docs/RUST_EXTERNAL_TEST_QUEUE.md",
    "docs/RUST_SEED_LOADER_READINESS.md",
    "docs/RUST_LIFT_BUNDLE_PLAN.md",
    "docs/RUST_EXTERNAL_TEST_PATCHSET.md",
    "docs/RUST_EXTERNAL_TEST_PATCH_SHARDS.md",
    "docs/RUST_EXTERNAL_TEST_PATCH_REHEARSAL.md",
    "docs/RUST_STANDING_BOOTSTRAP_GUARD.md",
    "docs/RUST_STANDING_BOOTSTRAP_GUARD_REHEARSAL.md",
    "docs/RUST_STANDING_BOOTSTRAP_REPAIR_PATCH.md",
    "docs/RUST_STANDING_BOOTSTRAP_REPAIR_REHEARSAL.md",
    "docs/RUST_STANDING_BOOTSTRAP_INTEGRATION_REHEARSAL.md",
    "docs/RUST_STANDING_BOOTSTRAP_COMEBACK_BUNDLE.md",
    "docs/RUST_STANDING_BOOTSTRAP_COMEBACK_BUNDLE_REHEARSAL.md",
    "docs/RUST_STANDING_BOOTSTRAP_POST_PATCHSET_BUNDLE.md",
    "docs/RUST_STANDING_BOOTSTRAP_POST_PATCHSET_BUNDLE_REHEARSAL.md",
    "docs/RUST_STANDING_BOOTSTRAP_STATE_SELECTOR.md",
    "docs/RUST_STANDING_BOOTSTRAP_STATE_SELECTOR_REHEARSAL.md",
    "docs/RUST_STANDING_BOOTSTRAP_ROUTE_EQUIVALENCE.md",
    "docs/RUST_STANDING_BOOTSTRAP_EXECUTION_CARD.md",
    "docs/RUST_STANDING_BOOTSTRAP_EXECUTION_REHEARSAL.md",
    "docs/RUST_STANDING_BOOTSTRAP_VERIFICATION_LADDER.md",
    "docs/RUST_STANDING_BOOTSTRAP_VERIFICATION_LADDER_REHEARSAL.md",
    "docs/RUST_STANDING_BOOTSTRAP_CHECKPOINTS.md",
    "docs/RUST_STANDING_BOOTSTRAP_CHECKPOINTS_REHEARSAL.md",
    "docs/RUST_STANDING_BOOTSTRAP_CHECKPOINT_VERIFIER.md",
    "docs/RUST_STANDING_BOOTSTRAP_CHECKPOINT_VERIFIER_REHEARSAL.md",
    "docs/RUST_PATCH_PREFIX_FRONTIER.md",
    "docs/RUST_COMEBACK_CARD.md",
    "docs/RUST_COMEBACK_EXECUTION_CARD.md",
    "docs/CLOUDTAINER_SHADOW_PASS_FRONTIER.md",
    "docs/CLOUDTAINER_SHADOW_PASS_HISTORY.md",
    "docs/CLOUDTAINER_SHADOW_PASS_VOLATILITY.md",
    "docs/CLOUDTAINER_SHADOW_PASS_BUDGET_CARD.md",
    "docs/CLOUDTAINER_RUST_RECOVERY_CARD.md",
    "docs/CLOUDTAINER_RUST_PROBE_ORACLES.md",
    "docs/CLOUDTAINER_USERSPACE_RUSTUP_PLAN.md",
    "docs/CLOUDTAINER_USERSPACE_FETCH_SURFACE.md",
    "docs/CLOUDTAINER_USERSPACE_COMPILE_SURFACE.md",
    "docs/CLOUDTAINER_USERSPACE_OFFLINE_PROOF_LADDER.md",
    "docs/CLOUDTAINER_USERSPACE_FAILURE_RESUME_CARD.md",
    "docs/CLOUDTAINER_STANDING_BOOTSTRAP_DELTA.md",
    "docs/ARCHIVE_SIZE_GUARDRAIL_CARD.md",
    "docs/ARCHIVE_BYTE_TRIAGE_CARD.md",
    "docs/ARCHIVE_PACKAGE_CUT_CARD.md",
    "docs/ARCHIVE_REENTRY_CARD.md",
    "docs/ARCHIVE_HANDOFF_PACK.md",
    "docs/ARCHIVE_REVISION_CUT_CARD.md",
    "docs/ARCHIVE_ZIP_LINEAGE_CARD.md",
    "docs/ARCHIVE_ZIP_CHRONOLOGY_CARD.md",
    "docs/ARCHIVE_ZIP_AUTHORITY_CARD.md",
    "docs/ARCHIVE_ZIP_DIGEST_CARD.md",
    "docs/ARCHIVE_ZIP_SIZE_TRUTH_CARD.md",
    "docs/REMATCH_WORLD_BENCHMARK_WORLD_EMISSION_CARD.md",
    "docs/REMATCH_WORLD_BENCHMARK_NATIVE_FILL_MAP.md",
    "docs/REMATCH_WORLD_BENCHMARK_LANDING_LADDER.md",
    "docs/REMATCH_WORLD_BENCHMARK_EXAMPLE_DELTA_LEDGER.md",
    "docs/REMATCH_WORLD_BENCHMARK_CLOSEOUT_LIFECYCLE_LEDGER.md",
    "docs/REMATCH_WORLD_BENCHMARK_CITATION_WITNESS_MATRIX.md",
    "docs/REMATCH_WORLD_BENCHMARK_OPEN_TOUCHPOINT_RESOLUTION_MAP.md",
    "docs/REMATCH_WORLD_BENCHMARK_CLAIM_FRONTIER.md",
    "docs/REMATCH_WORLD_BENCHMARK_STAGE_YIELD_LEDGER.md",
    "docs/REMATCH_WORLD_BENCHMARK_PROOF_BUDGET_LEDGER.md",
]


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    missing = [p for p in REQUIRED if not (root / p).exists()]
    if missing:
        for p in missing:
            print(f"generated-docs: missing {p}", file=sys.stderr)
        return 1

    print(f"generated-docs: ok ({len(REQUIRED)} docs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
