import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
receipt = json.loads((ROOT / 'REVISION_RECEIPT.json').read_text(encoding='utf-8'))
assumptions = json.loads((ROOT / 'ASSUMPTION_LEDGER.json').read_text(encoding='utf-8'))['items']
followthrough = json.loads((ROOT / 'FOLLOWTHROUGH_QUEUE.json').read_text(encoding='utf-8'))['items']

payload = {
    'project': 'AI-EDU',
    'revision': receipt['revision'],
    'startup_path': [
        'START_HERE.md',
        'AGENTS.md',
        'docs/10-core/minimal-ai-literacy-spine.md',
        'docs/10-core/reference-model.md',
        'docs/30-operations/subject-embedded-exemplar-kernel.md',
        'docs/30-operations/course-level-ai-use-grammar.md',
        'docs/20-governance/accommodation-aware-disclosure-and-accessibility.md',
        'docs/20-governance/presumptive-access-support-categories-and-override-triggers.md',
        'docs/20-governance/subject-and-age-override-table-profile.md',
        'docs/20-governance/reusable-starter-override-rows.md',
        'docs/20-governance/general-purpose-vs-purpose-built-deployment-ladder.md',
        'docs/20-governance/student-facing-function-deployment-defaults-and-handoff-triggers.md',
        'docs/20-governance/recovery-packets-and-aggregate-dependence-signals.md',
        'docs/20-governance/sector-and-context-profile-splits-for-recovery-defaults.md',
        'docs/20-governance/hardening-branching-and-retreat-rules-for-recovery-profiles.md',
        'docs/20-governance/portable-review-window-substitute-path-and-publication-defaults-for-recovery-branches.md',
        'docs/20-governance/mini-codes-for-partially-portable-recovery-treatment-branches.md',
        'docs/20-governance/authority-family-defaults-for-recovery-treatment-mini-codes.md',
        'docs/20-governance/portable-owner-facing-handback-packet-fields-for-recovery-authority-families.md',
        'docs/20-governance/publication-of-local-departures-from-owner-facing-recovery-packet-defaults.md',
        'docs/20-governance/portable-defaults-for-predeclared-packet-maintenance-envelopes.md',
        'docs/20-governance/portable-quantitative-bands-for-promoted-packet-maintenance-envelopes.md',
        'docs/20-governance/portable-checkpoint-and-breach-defaults-for-promoted-packet-maintenance-envelopes.md',
        'docs/20-governance/portable-republication-and-recurrence-defaults-for-promoted-packet-maintenance-envelopes.md',
        'docs/20-governance/portable-cumulative-cycle-ceilings-and-fatigue-defaults-for-promoted-packet-maintenance-envelopes.md',
        'docs/20-governance/portable-re-promotion-and-cooldown-exit-defaults-for-promoted-packet-maintenance-envelopes.md',
        'docs/20-governance/portable-first-post-repromotion-watch-and-immediate-re-cooling-defaults-for-promoted-packet-maintenance-envelopes.md',
        'docs/20-governance/portable-probation-expiry-and-ordinary-status-restoration-defaults-for-re-promoted-packet-maintenance-envelopes.md',
        'docs/20-governance/portable-recent-repair-sensitivity-and-accelerated-re-cooling-defaults-for-restored-ordinary-packet-maintenance-envelopes.md',
        'docs/20-governance/portable-recent-repair-expiry-and-fully-settled-ordinary-status-defaults-for-post-restoration-packet-maintenance-envelopes.md',
        'docs/20-governance/late-relapse-and-ordinary-reset-defaults-for-fully-settled-packet-maintenance-envelopes.md',
        'docs/20-governance/sector-and-age-profile-splits-for-student-facing-defaults.md',
        'docs/20-governance/teacher-facing-function-delegation-defaults-and-sign-off-triggers.md',
        'docs/20-governance/sector-and-age-profile-splits-for-teacher-facing-defaults.md',
        'docs/20-governance/institution-facing-decision-support-defaults-and-contestability-triggers.md',
        'docs/20-governance/sector-and-office-profile-splits-for-institution-facing-defaults.md',
        'docs/20-governance/persistent-memory-personalization-and-learner-model-boundaries.md',
        'docs/20-governance/sector-and-function-profile-splits-for-memory-defaults.md',
        'docs/20-governance/minimum-observability-and-retention-without-surveillance.md',
        'docs/20-governance/sector-and-function-profile-splits-for-observability-defaults.md',
        'docs/20-governance/failure-escalation-safe-degradation-and-manual-fallback.md',
        'docs/20-governance/sector-and-function-profile-splits-for-failure-defaults.md',
        'docs/20-governance/model-and-workflow-change-classification-and-fresh-review-triggers.md',
        'docs/20-governance/sector-and-function-profile-splits-for-change-defaults.md',
        'docs/30-operations/lifelong-public-ai-learning-stack.md',
        'docs/30-operations/minimum-public-entitlement-and-handoff-standard.md',
        'docs/30-operations/portable-public-learning-packet-and-recognition-profile.md',
        'docs/30-operations/sector-defaults-for-public-ai-learning-recognition.md',
        'docs/30-operations/standing-equivalency-lists-and-review-governance.md',
        'docs/30-operations/standing-list-publication-profile-and-recency-windows.md',
        'docs/30-operations/standing-recognition-exception-profile-and-local-overrides.md',
        'docs/30-operations/appeal-feedback-and-standing-list-maintenance.md',
        'docs/30-operations/public-maintenance-history-and-trust-signals.md',
        'docs/30-operations/partner-consumption-and-grandfathering-rules.md',
        'docs/30-operations/in-flight-teach-out-and-substitute-equivalent-rules.md',
        'docs/30-operations/documented-reliance-and-burden-thresholds.md',
        'docs/30-operations/no-fault-transition-cost-absorption-and-fee-waiver-rules.md',
        'docs/20-governance/evidence-and-procurement.md',
        'docs/20-governance/pilot-to-scale-evidence-and-rollout-gates.md',
        'docs/20-governance/sector-and-function-profile-splits-for-rollout-gates.md',
        'docs/40-assessment/authentic-assessment-and-proof-of-learning.md',
        'docs/40-assessment/proof-of-learning-bundles.md',
        'docs/40-assessment/bundle-intensity-bands-and-sampling-ceilings.md',
        'docs/40-assessment/subject-family-proof-intensity-defaults.md',
        'docs/40-assessment/sector-and-age-profile-splits-for-proof-intensity-defaults.md'
    ],
    'current_summary': receipt['summary'],
    'live_assumptions': assumptions,
    'live_followthrough': followthrough,
    'open_questions': [
        'OQ-0001', 'OQ-0002', 'OQ-0003', 'OQ-0004', 'OQ-0005', 'OQ-0007', 'OQ-0008', 'OQ-0009', 'OQ-0010', 'OQ-0011', 'OQ-0023', 'OQ-0031', 'OQ-0032', 'OQ-0033', 'OQ-0034', 'OQ-0035', 'OQ-0037', 'OQ-0039', 'OQ-0040'
    ],
}
(ROOT / 'context-pack.json').write_text(json.dumps(payload, indent=2) + '\n', encoding='utf-8')
print('gen_context_pack: OK')
