"""rev0075 outbox settlement joining summary-outbox and settlement branchlets.

The rev0074 outbox/fence line and the alternate settlement/public-ledger line
both look locally plausible.  This join refuses to let either branch authorize a
summary-send canary alone: outbox, fence, settlement, ledger, redaction-GC, and
contradiction memory must bind at the same boundary.
"""
from __future__ import annotations
from dataclasses import dataclass
from enum import Enum
from typing import Any
from .bencode import bencode
from .ids import DOMAIN, sha256
from .moderationquarantine import ZERO_DIGEST
from .sideeffectjournal import SideEffectAction
OUTBOX_SETTLEMENT_DOMAIN=DOMAIN+b":outbox-settlement-join-v1:"
class OutboxSettlementClass(str, Enum):
    SUMMARY_OUTBOX="summary_outbox"; PUBLISH_FENCE="publish_fence"; SUMMARY_SETTLEMENT="summary_settlement"; PUBLIC_LEDGER="public_ledger"; REDACTION_GC="redaction_gc"; CONTRADICTION_MEMORY="contradiction_memory"
class OutboxSettlementDecisionKind(str, Enum):
    ACCEPT_OUTBOX_SETTLED="accept_outbox_settled"; HOLD_SUMMARY_OUTBOX_PENDING="hold_summary_outbox_pending"; HOLD_PUBLISH_FENCE_PENDING="hold_publish_fence_pending"; HOLD_SUMMARY_SETTLEMENT_PENDING="hold_summary_settlement_pending"; HOLD_PUBLIC_LEDGER_PENDING="hold_public_ledger_pending"; HOLD_REDACTION_GC_PENDING="hold_redaction_gc_pending"; HOLD_MISSING_REQUIRED_CLASS="hold_missing_required_class"; HOLD_LOW_FAMILY_DIVERSITY="hold_low_family_diversity"; HOLD_LOW_PATH_DIVERSITY="hold_low_path_diversity"; QUARANTINE_BOUNDARY_DRIFT="quarantine_boundary_drift"; QUARANTINE_DIGEST_DRIFT="quarantine_digest_drift"; QUARANTINE_REPLAY="quarantine_replay"; QUARANTINE_SEQUENCE_ROLLBACK="quarantine_sequence_rollback"; QUARANTINE_SEQUENCE_FORK="quarantine_sequence_fork"; QUARANTINE_PREVIOUS_MISMATCH="quarantine_previous_mismatch"; QUARANTINE_CONTRADICTION_DROPPED="quarantine_contradiction_dropped"; QUARANTINE_HARD_NEGATIVE_PRESSURE="quarantine_hard_negative_pressure"
@dataclass(frozen=True)
class OutboxSettlementMarker:
    settlement_class:OutboxSettlementClass; sequence:int; previous_digest:bytes; action:SideEffectAction; profile_id:str; service_name:str; scope_digest:bytes; request_digest:bytes; payload_digest:bytes; idempotency_key:bytes; retry_idempotency_key:bytes; summary_outbox_digest:bytes; publish_fence_digest:bytes; summary_settlement_digest:bytes; public_ledger_digest:bytes; redaction_gc_digest:bytes; accepted_outbox_entry_digest:bytes; accepted_fence_marker_digest:bytes; accepted_settlement_marker_digest:bytes; accepted_public_ledger_entry_digest:bytes; accepted_redaction_gc_proposal_digest:bytes; redacted_summary_digest:bytes; contradiction_carried:bool; family_id:str; path_family_id:str; hard_negative_count:int=0
    @property
    def marker_digest(self)->bytes:
        return sha256(OUTBOX_SETTLEMENT_DOMAIN+b":marker:"+bencode({b"class":self.settlement_class.value,b"seq":self.sequence,b"prev":self.previous_digest,b"action":self.action.value,b"profile":self.profile_id,b"service":self.service_name,b"scope":self.scope_digest,b"request":self.request_digest,b"payload":self.payload_digest,b"idem":self.idempotency_key,b"retry":self.retry_idempotency_key,b"outbox":self.summary_outbox_digest,b"fence":self.publish_fence_digest,b"settlement":self.summary_settlement_digest,b"ledger":self.public_ledger_digest,b"gc":self.redaction_gc_digest,b"outbox_entry":self.accepted_outbox_entry_digest,b"fence_marker":self.accepted_fence_marker_digest,b"settlement_marker":self.accepted_settlement_marker_digest,b"ledger_entry":self.accepted_public_ledger_entry_digest,b"gc_proposal":self.accepted_redaction_gc_proposal_digest,b"redacted":self.redacted_summary_digest,b"contradiction":1 if self.contradiction_carried else 0,b"family":self.family_id,b"path":self.path_family_id,b"hard":self.hard_negative_count}))
@dataclass(frozen=True)
class OutboxSettlementReport:
    decision_kind:OutboxSettlementDecisionKind; accept:bool; watch:bool; outbox_settled:bool; contradiction_preserved:bool; reason:str; action:SideEffectAction; profile_id:str; service_name:str; scope_digest:bytes; request_digest:bytes; payload_digest:bytes; idempotency_key:bytes; retry_idempotency_key:bytes; summary_outbox_digest:bytes; publish_fence_digest:bytes; summary_settlement_digest:bytes; public_ledger_digest:bytes; redaction_gc_digest:bytes; accepted_marker_digest:bytes; redacted_summary_digest:bytes; class_values:tuple[str,...]; marker_digests:tuple[bytes,...]; family_count:int; path_family_count:int; hard_negative_count:int; report_digest:bytes
    @property
    def quarantined(self)->bool: return self.decision_kind.value.startswith('quarantine_')
    @property
    def redacted(self)->bool: return isinstance(self.redacted_summary_digest, bytes) and len(self.redacted_summary_digest)==32 and self.redacted_summary_digest != ZERO_DIGEST
def _digest(r:Any|None)->bytes:
    if r is None: return ZERO_DIGEST
    for a in ('report_digest','accepted_marker_digest','accepted_entry_digest','accepted_proposal_digest','accepted_receipt_digest'):
        v=getattr(r,a,None)
        if isinstance(v,bytes) and len(v)==32: return v
    raise ValueError('component lacks digest')
def _boundary(r:Any)->tuple[Any,...]: return (SideEffectAction(getattr(r,'action')),getattr(r,'profile_id'),getattr(r,'service_name'),getattr(r,'scope_digest'),getattr(r,'request_digest'),getattr(r,'payload_digest'),getattr(r,'idempotency_key'))
def _mb(m:OutboxSettlementMarker)->tuple[Any,...]: return (m.action,m.profile_id,m.service_name,m.scope_digest,m.request_digest,m.payload_digest,m.idempotency_key)
def make_outbox_settlement_marker(*, settlement_class:OutboxSettlementClass, sequence:int, summary_outbox_report:Any, publish_fence_report:Any, summary_settlement_report:Any, public_ledger_report:Any, redaction_gc_report:Any, previous_digest:bytes=ZERO_DIGEST, contradiction_carried:bool|None=None, family_id:str='outbox-settlement-family-a', path_family_id:str='outbox-settlement-path-a', hard_negative_count:int=0)->OutboxSettlementMarker:
    contradiction=bool(getattr(summary_outbox_report,'contradiction_carried',False) and getattr(publish_fence_report,'contradiction_preserved',False) and getattr(summary_settlement_report,'contradiction_preserved',False) and getattr(public_ledger_report,'contradiction_preserved',False) and getattr(redaction_gc_report,'contradiction_retained',False)) if contradiction_carried is None else bool(contradiction_carried)
    redacted_summary=getattr(summary_outbox_report,'redacted_summary_digest',ZERO_DIGEST)
    if redacted_summary==ZERO_DIGEST:
        redacted_summary=sha256(OUTBOX_SETTLEMENT_DOMAIN+b':redacted-summary:'+_digest(summary_outbox_report)+_digest(summary_settlement_report)+_digest(public_ledger_report)+_digest(redaction_gc_report))
    return OutboxSettlementMarker(OutboxSettlementClass(settlement_class),int(sequence),previous_digest,SideEffectAction(getattr(summary_outbox_report,'action')),getattr(summary_outbox_report,'profile_id'),getattr(summary_outbox_report,'service_name'),getattr(summary_outbox_report,'scope_digest'),getattr(summary_outbox_report,'request_digest'),getattr(summary_outbox_report,'payload_digest'),getattr(summary_outbox_report,'idempotency_key'),getattr(summary_outbox_report,'retry_idempotency_key',ZERO_DIGEST),_digest(summary_outbox_report),_digest(publish_fence_report),_digest(summary_settlement_report),_digest(public_ledger_report),_digest(redaction_gc_report),getattr(summary_outbox_report,'accepted_entry_digest',ZERO_DIGEST),getattr(publish_fence_report,'accepted_marker_digest',ZERO_DIGEST),getattr(summary_settlement_report,'accepted_marker_digest',ZERO_DIGEST),getattr(public_ledger_report,'accepted_entry_digest',ZERO_DIGEST),getattr(redaction_gc_report,'accepted_proposal_digest',ZERO_DIGEST),redacted_summary,contradiction,family_id,path_family_id,hard_negative_count)
def _report(kind,accept,watch,settled,contradiction,reason,*,summary_outbox_report,publish_fence_report,summary_settlement_report,public_ledger_report,redaction_gc_report,markers,accepted_marker_digest=ZERO_DIGEST):
    fam={m.family_id for m in markers}; paths={m.path_family_id for m in markers}; classes=tuple(sorted({m.settlement_class.value for m in markers})); md=tuple(m.marker_digest for m in markers); hard=sum(int(getattr(x,'hard_negative_count',0) or 0) for x in (summary_outbox_report,publish_fence_report,summary_settlement_report,public_ledger_report,redaction_gc_report))+sum(m.hard_negative_count for m in markers)
    dg=sha256(OUTBOX_SETTLEMENT_DOMAIN+b':report:'+bencode({b'kind':kind.value,b'accept':1 if accept else 0,b'settled':1 if settled else 0,b'contradiction':1 if contradiction else 0,b'outbox':_digest(summary_outbox_report),b'fence':_digest(publish_fence_report),b'settlement':_digest(summary_settlement_report),b'ledger':_digest(public_ledger_report),b'gc':_digest(redaction_gc_report),b'accepted':accepted_marker_digest,b'classes':list(classes),b'markers':list(md),b'families':len(fam),b'paths':len(paths),b'hard':hard,b'reason':reason}))
    redacted_report=getattr(summary_outbox_report,'redacted_summary_digest',ZERO_DIGEST)
    if redacted_report==ZERO_DIGEST and markers:
        redacted_report=markers[0].redacted_summary_digest
    return OutboxSettlementReport(kind,accept,watch,settled,contradiction,reason,SideEffectAction(getattr(summary_outbox_report,'action')),getattr(summary_outbox_report,'profile_id'),getattr(summary_outbox_report,'service_name'),getattr(summary_outbox_report,'scope_digest'),getattr(summary_outbox_report,'request_digest'),getattr(summary_outbox_report,'payload_digest'),getattr(summary_outbox_report,'idempotency_key'),getattr(summary_outbox_report,'retry_idempotency_key',ZERO_DIGEST),_digest(summary_outbox_report),_digest(publish_fence_report),_digest(summary_settlement_report),_digest(public_ledger_report),_digest(redaction_gc_report),accepted_marker_digest,redacted_report,classes,md,len(fam),len(paths),hard,dg)
def assess_outbox_settlement(*, summary_outbox_report:Any, publish_fence_report:Any, summary_settlement_report:Any, public_ledger_report:Any, redaction_gc_report:Any, markers:tuple[OutboxSettlementMarker,...], previous_digest:bytes=ZERO_DIGEST, required_classes:tuple[OutboxSettlementClass,...]=(OutboxSettlementClass.SUMMARY_OUTBOX,OutboxSettlementClass.PUBLISH_FENCE,OutboxSettlementClass.SUMMARY_SETTLEMENT,OutboxSettlementClass.PUBLIC_LEDGER,OutboxSettlementClass.REDACTION_GC,OutboxSettlementClass.CONTRADICTION_MEMORY), min_family_count:int=2, min_path_family_count:int=2)->OutboxSettlementReport:
    markers=tuple(markers)
    if not getattr(summary_outbox_report,'outbox_staged',False): return _report(OutboxSettlementDecisionKind.HOLD_SUMMARY_OUTBOX_PENDING,False,True,False,False,'outbox pending',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    if not getattr(publish_fence_report,'summary_publish_fenced',False): return _report(OutboxSettlementDecisionKind.HOLD_PUBLISH_FENCE_PENDING,False,True,False,False,'fence pending',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    if not getattr(summary_settlement_report,'summary_settled',False): return _report(OutboxSettlementDecisionKind.HOLD_SUMMARY_SETTLEMENT_PENDING,False,True,False,False,'settlement pending',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    if not getattr(public_ledger_report,'public_summary_ledgered',False): return _report(OutboxSettlementDecisionKind.HOLD_PUBLIC_LEDGER_PENDING,False,True,False,False,'ledger pending',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    if not getattr(redaction_gc_report,'redaction_gc_guarded',False): return _report(OutboxSettlementDecisionKind.HOLD_REDACTION_GC_PENDING,False,True,False,False,'gc pending',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    b=_boundary(summary_outbox_report)
    if _boundary(publish_fence_report)!=b or _boundary(summary_settlement_report)!=b or _boundary(public_ledger_report)!=b or _boundary(redaction_gc_report)!=b or any(_mb(m)!=b for m in markers): return _report(OutboxSettlementDecisionKind.QUARANTINE_BOUNDARY_DRIFT,False,True,False,False,'boundary drift',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    if getattr(publish_fence_report,'summary_outbox_digest',_digest(summary_outbox_report))!=_digest(summary_outbox_report) or getattr(public_ledger_report,'summary_settlement_digest',_digest(summary_settlement_report))!=_digest(summary_settlement_report): return _report(OutboxSettlementDecisionKind.QUARANTINE_DIGEST_DRIFT,False,True,False,False,'component digest drift',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    if any(m.summary_outbox_digest!=_digest(summary_outbox_report) or m.publish_fence_digest!=_digest(publish_fence_report) or m.summary_settlement_digest!=_digest(summary_settlement_report) or m.public_ledger_digest!=_digest(public_ledger_report) or m.redaction_gc_digest!=_digest(redaction_gc_report) for m in markers): return _report(OutboxSettlementDecisionKind.QUARANTINE_DIGEST_DRIFT,False,True,False,False,'marker digest drift',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    if any(not m.contradiction_carried for m in markers) or not (getattr(summary_outbox_report,'contradiction_carried',False) and getattr(publish_fence_report,'contradiction_preserved',False) and getattr(summary_settlement_report,'contradiction_preserved',False) and getattr(public_ledger_report,'contradiction_preserved',False) and getattr(redaction_gc_report,'contradiction_retained',False)): return _report(OutboxSettlementDecisionKind.QUARANTINE_CONTRADICTION_DROPPED,False,True,False,False,'contradiction dropped',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    if sum(int(getattr(x,'hard_negative_count',0) or 0) for x in (summary_outbox_report,publish_fence_report,summary_settlement_report,public_ledger_report,redaction_gc_report))+sum(m.hard_negative_count for m in markers): return _report(OutboxSettlementDecisionKind.QUARANTINE_HARD_NEGATIVE_PRESSURE,False,True,False,True,'hard negative',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    if not set(required_classes).issubset({m.settlement_class for m in markers}): return _report(OutboxSettlementDecisionKind.HOLD_MISSING_REQUIRED_CLASS,False,True,False,True,'missing class',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    prev=previous_digest; seen={}; dseen=set()
    for m in sorted(markers,key=lambda x:x.sequence):
        d=m.marker_digest
        if d in dseen: return _report(OutboxSettlementDecisionKind.QUARANTINE_REPLAY,False,True,False,True,'replay',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
        dseen.add(d)
        if m.sequence<=0: return _report(OutboxSettlementDecisionKind.QUARANTINE_SEQUENCE_ROLLBACK,False,True,False,True,'rollback',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
        if m.sequence in seen and seen[m.sequence]!=d: return _report(OutboxSettlementDecisionKind.QUARANTINE_SEQUENCE_FORK,False,True,False,True,'fork',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
        if m.previous_digest!=prev: return _report(OutboxSettlementDecisionKind.QUARANTINE_PREVIOUS_MISMATCH,False,True,False,True,'prev mismatch',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
        seen[m.sequence]=d; prev=d
    if len({m.family_id for m in markers})<min_family_count: return _report(OutboxSettlementDecisionKind.HOLD_LOW_FAMILY_DIVERSITY,False,True,False,True,'low family',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    if len({m.path_family_id for m in markers})<min_path_family_count: return _report(OutboxSettlementDecisionKind.HOLD_LOW_PATH_DIVERSITY,False,True,False,True,'low path',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers)
    return _report(OutboxSettlementDecisionKind.ACCEPT_OUTBOX_SETTLED,True,False,True,True,'outbox settlement joined',summary_outbox_report=summary_outbox_report,publish_fence_report=publish_fence_report,summary_settlement_report=summary_settlement_report,public_ledger_report=public_ledger_report,redaction_gc_report=redaction_gc_report,markers=markers,accepted_marker_digest=markers[-1].marker_digest if markers else ZERO_DIGEST)
