from __future__ import annotations

from random import Random

from src.muc5.action_budget import action_diversity_key, select_budgeted_action_indices
from src.muc5.action_schema import Action
from src.muc5.cards import CARD_COUNTERSPELL, CARD_FORCE, CARD_ISLAND, CARD_JACE, CARD_OVERLORD
from src.muc5.decision import DecisionFrame
from src.muc5.public_agents import make_public_agent
from src.muc5.ranker_policy import counterfactual_ranker_model_path, load_counterfactual_ranker_agent
from src.muc5.strategy_sets import budgeted_counterfactual_action_ranker_bundles


def _fake_frame() -> DecisionFrame:
    actions = (
        Action("PASS"),
        Action("PLAY_ISLAND"),
        Action("CAST", {"card": CARD_COUNTERSPELL, "target_card": CARD_JACE}),
        Action("CAST", {"card": CARD_FORCE, "payment": "pitch", "pitch_card": CARD_OVERLORD, "target_card": CARD_JACE}),
        Action("CAST", {"card": CARD_FORCE, "payment": "pitch", "pitch_card": CARD_COUNTERSPELL, "target_card": CARD_OVERLORD}),
        Action("CAST", {"card": CARD_JACE}),
        Action("CAST", {"card": CARD_OVERLORD, "mode": "impending"}),
        Action("ACTIVATE_JACE", {"mode": "zero"}),
        Action("CHOOSE_FOR_EFFECT", {"effect": "cleanup_discard", "card": CARD_ISLAND}),
        Action("CHOOSE_FOR_EFFECT", {"effect": "cleanup_discard", "card": CARD_OVERLORD}),
    )
    return DecisionFrame(player=0, state_revision=1, observation={"frame": "MAIN", "player": 0}, legal_actions=actions)


def test_budgeted_selector_keeps_chosen_and_respects_budget() -> None:
    frame = _fake_frame()
    sel = select_budgeted_action_indices(frame, chosen_index=5, budget=6, rng=Random(35))
    assert 5 in sel.indices
    assert len(sel.indices) <= 6
    assert sel.full_action_count == frame.action_count
    assert sel.is_subset
    assert sel.reasons[5] == "behavior_chosen"
    assert any(frame.legal_actions[i].kind == "PASS" for i in sel.indices)
    assert any(frame.legal_actions[i].kind == "PLAY_ISLAND" for i in sel.indices)


def test_action_diversity_key_distinguishes_force_pitch_cards() -> None:
    a = Action("CAST", {"card": CARD_FORCE, "payment": "pitch", "pitch_card": CARD_OVERLORD})
    b = Action("CAST", {"card": CARD_FORCE, "payment": "pitch", "pitch_card": CARD_COUNTERSPELL})
    assert action_diversity_key(a) != action_diversity_key(b)


def test_rev0035_ranker_artifact_loads_after_generation() -> None:
    # The artifact is generated by scripts/run_rev0035_budgeted_action_counterfactual.py
    # before the full audit/test pass.  This test keeps the public-agent factory
    # wired to the JSON model rather than silently falling back to an older ranker.
    path = counterfactual_ranker_model_path("rev0035")
    if path.exists():
        agent = load_counterfactual_ranker_agent("rev0035", name="counterfactual_linear_ranker_rev0035")
        assert agent.name == "counterfactual_linear_ranker_rev0035"
        assert make_public_agent("counterfactual_ranker_blend_counter_rev0035").name.endswith("rev0035")


def test_rev0035_strategy_panel_shape() -> None:
    bundles = budgeted_counterfactual_action_ranker_bundles("data/seed_decks.json")
    assert len(bundles) == 8
    assert any(b.agent_name == "counterfactual_linear_ranker_rev0035" for b in bundles)
    assert any(str(b.mulligan_policy).startswith("mulligan_") for b in bundles)
