from __future__ import annotations

import json
from pathlib import Path
from random import Random

from src.muc5.action_racing import _allocation_priority
from src.muc5.decision import build_decision_frame
from src.muc5.engine import start_game
from src.muc5.mulligan_ranker import make_mulligan_agent
from src.muc5.public_agents import make_public_agent
from src.muc5.strategy_sets import adaptive_counterfactual_action_ranker_bundles

ROOT = Path(__file__).resolve().parents[1]


def test_adaptive_allocation_priority_prefers_current_leader_and_runner_up() -> None:
    scores = {0: [0.0, 0.0], 1: [1.0], 2: [0.5]}
    top, second, margin, uncertainty, confidence = _allocation_priority(scores, rng=Random(1))
    assert top == 1
    assert second in {2, 0}
    assert margin >= 0.5
    assert uncertainty > 0
    assert 0 <= confidence <= 1


def test_rev0036_counterfactual_aliases_load_and_choose_legal_action() -> None:
    bundles = adaptive_counterfactual_action_ranker_bundles(ROOT / "data" / "seed_decks.json")
    # The model file is generated by scripts/run_rev0036_adaptive_action_counterfactual.py.
    assert (ROOT / "data" / "rev0036_counterfactual_action_ranker_model.json").exists()
    agent = make_public_agent("counterfactual_ranker_blend_threat_rev0036")
    state = start_game(
        bundles[0].deck,
        bundles[1].deck,
        seed=363636,
        starting_player=0,
        starting_life=20,
        mulligan_agents=(make_mulligan_agent(bundles[0].mulligan_policy), make_mulligan_agent(bundles[1].mulligan_policy)),
        record_log=False,
    )
    frame = build_decision_frame(state)
    idx = agent.choose_action_index(frame, Random(7))
    assert 0 <= idx < frame.action_count


def test_rev0036_summary_gates_and_cpp_parity() -> None:
    summary = json.loads((ROOT / "data" / "rev0036_adaptive_action_counterfactual_summary.json").read_text())
    cf = summary["counterfactual_summary"]
    assert cf["branch_terminal_games"] > 0
    assert cf["branch_truncations"] == 0
    assert cf["cpp_mismatches"] == 0
    assert cf["cpp_skipped_transitions"] == 0
    assert cf["adaptive_extra_rollouts"] > 0
    assert summary["promotion_gate"]["passed"] is True
    assert summary["statistical_gate"]["passed"] is True
    assert summary["replay_passed"] == summary["replay_samples"]
    assert summary["cpp_shadow_summary"]["mismatches"] == 0
