from __future__ import annotations

from src.muc5.action_counterfactual import build_action_counterfactual_specs
from src.muc5.action_disagreement import collect_disagreement_screened_counterfactuals
from src.muc5.strategy_sets import outcome_ranker_probe_bundles, disagreement_counterfactual_action_ranker_bundles
from src.muc5.public_agents import make_public_agent


def test_disagreement_screen_collects_only_disagreement_frames():
    strategies = outcome_ranker_probe_bundles("data/seed_decks.json")[:2]
    specs = build_action_counterfactual_specs(
        strategies,
        life_totals=(20,),
        base_seed=938000,
        max_decisions=260,
        limit_games=2,
    )
    candidates, branches, screen_rows, transitions, summary = collect_disagreement_screened_counterfactuals(
        specs,
        revision="rev0038_test",
        screen_agent_names=("counter_happy", "threat_rush", "patient"),
        min_unique_screen_votes=2,
        max_situations=2,
        max_actions_per_frame=4,
        sample_high_action_frames=True,
        branch_action_budget=5,
        branch_rollouts_per_action=1,
        branch_max_decisions=180,
        budget_rng_seed=938,
    )
    assert summary.sampled_situations >= 1
    assert summary.cpp_mismatches == 0
    assert summary.cpp_skipped_transitions == 0
    assert len(candidates) >= summary.sampled_situations * 2
    assert len(branches) >= len(candidates)
    assert len(transitions) >= len(branches)
    by_situation = {}
    for row in candidates:
        by_situation.setdefault(row["situation_id"], []).append(row)
    for rows in by_situation.values():
        assert int(rows[0]["screen_unique_votes"]) >= 2
    assert len(screen_rows) >= summary.sampled_situations * 2


def test_rev0038_strategy_bundles_and_generic_agent_aliases_load():
    bundles = disagreement_counterfactual_action_ranker_bundles("data/seed_decks.json")
    assert any(b.agent_name == "counterfactual_linear_ranker_rev0038" for b in bundles)
    # The model file is generated by the rev0038 script, so do not load it here.
    # This still verifies the older factory names used by screeners remain valid.
    for name in ["counter_happy", "threat_rush", "patient", "code_jace_lock_rev0013"]:
        agent = make_public_agent(name)
        assert agent.name
