import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REV = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
SNAP_REL = f"examples/live-receipt-floor-computed-snapshot-{REV}.json"

try:
    from jsonschema import Draft202012Validator
except Exception:
    Draft202012Validator = None


def load(rel):
    return json.loads((ROOT / rel).read_text(encoding="utf-8"))

if Draft202012Validator is not None:
    schema = load("schemas/live-receipt-floor-computed-snapshot.schema.json")
    data = load(SNAP_REL)
    Draft202012Validator.check_schema(schema)
    errors = sorted(Draft202012Validator(schema).iter_errors(data), key=lambda e: list(e.path))
    if errors:
        raise SystemExit(f"{SNAP_REL} fails live-receipt-floor-computed-snapshot.schema.json: {errors[0].message}")

# The checked-in snapshot must be exactly regenerated by the engine.
subprocess.run([sys.executable, str(ROOT / "tools/compute_live_receipt_floor.py"), "--check"], check=True)

snap = load(SNAP_REL)
floor = snap.get("computed_floor", {})
if floor.get("independent_receipts_present") != 0 or floor.get("live_floor_delta") != 0:
    raise SystemExit("computed floor must remain zero in rev0203")
if floor.get("eligible_live_imports") or floor.get("live_classes_satisfied"):
    raise SystemExit("rev0203 snapshot must not list eligible live imports or satisfied classes")
if "independence_discount_register" not in floor or "candidate_live_imports_before_independence_discount" not in floor:
    raise SystemExit("computed snapshot must expose candidate set and independence discount register")
if "independence_discount_applied" not in snap.get("mismatch_checks", {}):
    raise SystemExit("computed snapshot mismatch checks must expose independence_discount_applied")
if floor.get("live_quorum_satisfied") is not False or floor.get("cross_critical_quorum_satisfied") is not False:
    raise SystemExit("computed floor must not satisfy quorum")
for cls in ["first-touch-clock", "continuity-compute-floor", "result-return"]:
    if cls not in floor.get("missing_live_classes", []):
        raise SystemExit(f"computed snapshot missing required live class from gaps: {cls}")
checks = snap.get("mismatch_checks", {})
if checks.get("live_packet_floor_matches") is not True:
    raise SystemExit("live packet floor must match computed snapshot")
if checks.get("manual_ledger_override_detected") is not False:
    raise SystemExit("manual ledger override unexpectedly detected")
if checks.get("failed_gate_public_summary_present_for_exclusions") is not True:
    raise SystemExit("snapshot exclusions must have failed-gate publication path")
if checks.get("frontdoor_revision_matches") is not True:
    raise SystemExit("front doors do not match active revision")

exclusions = snap.get("exclusion_register", [])
refs = {item.get("source_ref") for item in exclusions}
for ref in ["ARIG-2026-result-return-fixture-import-gate", "ARIG-2026-result-return-institutional-dryrun-gate", "RICR-2026-dryrun-premature-import-rollback"]:
    if ref not in refs:
        raise SystemExit(f"computed snapshot missing exclusion: {ref}")

doc = (ROOT / "docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md").read_text(encoding="utf-8")
for phrase in ["Computed floor is source of truth", "Admission checklist is not admission", "Artifact quarantine comes before response creation", "Failed-gate publication follows every non-import", "One valid class remains class-local"]:
    if phrase not in doc:
        raise SystemExit(f"computed-floor doc missing phrase: {phrase}")

suite = load("examples/fixture-suite-profile-red-team-v1.json")
report = load("examples/fixture-run-report-negative-suite.json")
suite_ids = {f.get("fixture_id") for f in suite.get("fixtures", [])}
report_by_id = {f.get("fixture_id"): f for f in report.get("fixtures_run", [])}
for fid in ["NF-PLAYBOOK-2026-0032", "NF-PLAYBOOK-2026-0033", "NF-PLAYBOOK-2026-0034"]:
    if fid not in suite_ids:
        raise SystemExit(f"rev0203 fixture missing from suite: {fid}")
    if report_by_id.get(fid, {}).get("result") != "blocking-failure":
        raise SystemExit(f"rev0203 fixture must be blocking-failure: {fid}")

registry = load(f"examples/schema-fixture-domain-registry-{REV}.json")
if "LIVE-RECEIPT-FLOOR-COMPUTED-SNAPSHOT" not in {f.get("family_id") for f in registry.get("families", [])}:
    raise SystemExit("registry missing LIVE-RECEIPT-FLOOR-COMPUTED-SNAPSHOT")
rights = load(f"examples/rights-domain-coverage-map-{REV}.json")
if "computed-live-floor-engine" not in {d.get("domain_id") for d in rights.get("domains", [])}:
    raise SystemExit("rights map missing computed-live-floor-engine")
queue = load("FOLLOWTHROUGH-QUEUE.json")
by_id = {e.get("id"): e for e in queue.get("entries", [])}
if by_id.get("FT-0203-COMPUTED-FLOOR-ENGINE", {}).get("state") != "closed":
    raise SystemExit("computed floor engine queue item must be closed")
if by_id.get("FT-0203-LIVE-ARTIFACT-ADMISSION-CHECKLIST", {}).get("state") != "closed":
    raise SystemExit("artifact admission checklist queue item must be closed")
actual_import = by_id.get("FT-0203-ACTUAL-LIVE-ARTIFACT-IMPORT", {})
actual_state = actual_import.get("state")
if actual_state not in {"open", "advanced_not_closed", "deferred"}:
    raise SystemExit("actual live artifact import must remain explicitly not closed")
if actual_state == "deferred" and "deferred-by-rev0250-from-advanced_not_closed" not in actual_import.get("source_state", ""):
    raise SystemExit("deferred actual live artifact import must retain its rev0250 nonclosure provenance")

print("audit_computed_live_floor_engine: OK")
