from __future__ import annotations

import json
from pathlib import Path

import yaml
from typer.testing import CliRunner

from vhk.cli import app


runner = CliRunner()


def _make_project(tmp_path: Path) -> Path:
    project_dir = tmp_path / "proj"
    (project_dir / "macros").mkdir(parents=True)

    (project_dir / "macros" / "launch.yaml").write_text(
        yaml.safe_dump(
            {
                "name": "launch",
                "steps": [
                    {"type": "TypeText", "text": "hello"},
                    {"type": "Return", "value": "ok"},
                ],
            },
            sort_keys=False,
        )
    )

    (project_dir / "project.yaml").write_text(
        yaml.safe_dump(
            {
                "name": "proj",
                "settings": {"desktop_backend": "wayland"},
                "bindings": [
                    {"keys": "Mod4+Shift+P", "macro": "launch", "description": "Launch macro"},
                ],
            },
            sort_keys=False,
        )
    )
    return project_dir



def test_gen_trigger_pack_writes_configs_and_docs(tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)

    res = runner.invoke(app, ["gen-trigger-pack", str(project_dir), "--no-session-check", "--quiet"])
    assert res.exit_code == 0, res.output

    root = project_dir / "build" / "trigger_pack"
    docs_dir = root / "docs"
    configs_dir = root / "configs"
    scripts_dir = root / "scripts"

    guide = (docs_dir / "VHK_TRIGGER_SURFACES.md").read_text()
    matrix = (docs_dir / "VHK_TRIGGER_MATRIX.md").read_text()
    manifest = json.loads((docs_dir / "VHK_TRIGGER_PACK.json").read_text())
    script = (scripts_dir / "vhk_refresh_trigger_pack.sh").read_text()

    keyd = (configs_dir / "remappers" / "vhk.keyd.conf").read_text()
    kanata = (configs_dir / "remappers" / "vhk.kanata.kbd").read_text()
    kmonad = (configs_dir / "remappers" / "vhk.kmonad.kbd").read_text()
    xremap = (configs_dir / "remappers" / "vhk.xremap.yml").read_text()
    sxhkd = (configs_dir / "x11" / "vhk.sxhkdrc").read_text()
    i3 = (configs_dir / "wm" / "vhk.i3.conf").read_text()
    sway = (configs_dir / "wm" / "vhk.sway.conf").read_text()
    portal = (configs_dir / "portal" / "vhk.portal-shortcuts.yml").read_text()
    hypr = (configs_dir / "wm" / "vhk.hyprland.conf").read_text()

    assert "# VHK trigger surfaces for proj" in guide
    assert "## Generated trigger configs" in guide
    assert "Trigger surfaces without static files" in guide

    assert "# VHK trigger matrix for proj" in matrix
    assert "no static artifact in this pack" in matrix

    assert manifest["project"]["name"] == "proj"
    assert len(manifest["generated_surfaces"]) >= 9
    assert any(item["id"] == "keyd-remap" for item in manifest["generated_surfaces"])
    assert any(item["id"] == "xremap-remap" for item in manifest["generated_surfaces"])
    assert any(item["id"] == "portal-global-shortcuts" for item in manifest["generated_surfaces"])
    assert all(item["id"] != "portal-global-shortcuts" for item in manifest["non_file_surfaces"])

    assert script.startswith("#!/usr/bin/env sh\n")
    assert 'OUT_DIR="${OUT_DIR:-./build/trigger_pack}"' in script
    assert 'vhk gen-trigger-pack . --out-dir "$OUT_DIR" --force --quiet' in script

    assert keyd.startswith("# VHK trigger-pack surface: keyd remap layer\n")
    assert "Generated by: vhk gen-keyd-config" in keyd
    assert kanata.startswith("# VHK trigger-pack surface: Kanata remap layer\n")
    assert kmonad.startswith(";; VHK trigger-pack surface: KMonad remap layer\n")
    assert xremap.startswith("# VHK trigger-pack surface: xremap app-aware remap layer\n")
    assert "Generated by: vhk gen-xremap-config" in xremap
    assert portal.startswith("# VHK trigger-pack surface: GlobalShortcuts portal catalog\n")
    assert "Generated by: vhk gen-portal-shortcuts-spec" in portal
    assert sxhkd.startswith("# VHK trigger-pack surface: sxhkd hotkey daemon\n")
    assert i3.startswith("# VHK trigger-pack surface: i3 WM dispatch\n")
    assert sway.startswith("# VHK trigger-pack surface: sway WM dispatch\n")
    assert hypr.startswith("# VHK trigger-pack surface: Hyprland WM dispatch\n")



def test_gen_trigger_pack_can_write_to_custom_root(tmp_path: Path) -> None:
    project_dir = _make_project(tmp_path)
    out_dir = tmp_path / "exports" / "triggers"

    res = runner.invoke(
        app,
        [
            "gen-trigger-pack",
            str(project_dir),
            "--out-dir",
            str(out_dir),
            "--no-session-check",
            "--no-guide",
            "--no-script",
            "--force",
            "--quiet",
        ],
    )
    assert res.exit_code == 0, res.output

    assert not (out_dir / "docs" / "VHK_TRIGGER_SURFACES.md").exists()
    assert (out_dir / "docs" / "VHK_TRIGGER_MATRIX.md").exists()
    assert (out_dir / "docs" / "VHK_TRIGGER_PACK.json").exists()
    assert not (out_dir / "scripts" / "vhk_refresh_trigger_pack.sh").exists()
    assert (out_dir / "configs" / "remappers" / "vhk.keyd.conf").exists()
    assert (out_dir / "configs" / "remappers" / "vhk.xremap.yml").exists()
    assert (out_dir / "configs" / "wm" / "vhk.i3.conf").exists()
