#!/usr/bin/env python3
import json, pathlib, re, sys
root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else '.').resolve()
scorecard = json.loads((root / 'scorecard-template.json').read_text(encoding='utf-8'))
criteria = sorted(scorecard.get('criteria', []), key=lambda c: int(c['id'][1:]))
max_score = 2 * len(criteria)
min_score = -2 * len(criteria)
lines = []
lines.append('# Proposal scorecard')
lines.append('')
lines.append('This table is generated from `scorecard-template.json`; edit the JSON, then render this markdown. The checker treats JSON as canonical.')
lines.append('')
lines.append('## One-line thesis')
lines.append('')
lines.append('A morally serious tax proposal should pass recurring tests for floor protection, subject/base clarity, incidence, timing, measurement, standing, review, channel access, current-law integrity, and classification seams before prose expansion.')
lines.append('')
lines.append('## Score scale')
lines.append('')
lines.append('- **+2** — strongly satisfies the criterion')
lines.append('- **+1** — mostly satisfies it')
lines.append('- **0** — mixed or unclear')
lines.append('- **-1** — significant defect')
lines.append('- **-2** — strong failure')
lines.append(f'- **Maximum score:** +{max_score}; **minimum score:** {min_score}.')
lines.append('')
lines.append('Protected-floor vetoes, non-compensable harm gates, standing/remedy failures, and source-currentness failures can block approval even when the arithmetic score is positive.')
lines.append('')
lines.append('## Criteria')
lines.append('')
lines.append('| ID | Criterion | Question |')
lines.append('|---|---|---|')
for c in criteria:
    name = c.get('name','').replace('_',' ')
    q = c.get('question','').replace('\n',' ')
    lines.append(f'| {c["id"]} | {name} | {q} |')
lines.append('')
print('\n'.join(lines))
