#!/usr/bin/env python3
"""Run all lightweight archive hygiene checks.

This is a convenience wrapper so CI or humans can run a single command.

Usage:
  python3 tools/hygiene.py

Exit codes:
  0: all checks passed
  1: at least one check failed
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CHECKS = [
    [sys.executable, str(ROOT / "tools" / "check_consistency.py")],
    [sys.executable, str(ROOT / "tools" / "lint_spec_schemas.py")],
    [sys.executable, str(ROOT / "tools" / "check_schema_kind_matches_filename.py")],
    [sys.executable, str(ROOT / "tools" / "validate_spec_examples.py")],
    [sys.executable, str(ROOT / "tools" / "check_discovery.py")],
    [sys.executable, str(ROOT / "tools" / "check_meta_doc_discoverability.py")],
    [sys.executable, str(ROOT / "tools" / "check_changelog_format.py")],
    [sys.executable, str(ROOT / "tools" / "check_changelog_artifact_mentions.py")],
    [sys.executable, str(ROOT / "tools" / "check_release_last_updated.py")],
    [sys.executable, str(ROOT / "tools" / "check_must_read_set.py")],
    [sys.executable, str(ROOT / "tools" / "check_doc_metadata.py")],
    [sys.executable, str(ROOT / "tools" / "check_doc_patterns.py")],
    [sys.executable, str(ROOT / "tools" / "check_diff_surface_registry.py")],
    [sys.executable, str(ROOT / "tools" / "check_diff_surface_registry_wiring.py")],
    [sys.executable, str(ROOT / "tools" / "check_diff_review_docs.py")],
    [sys.executable, str(ROOT / "tools" / "check_diff_wiring_risk_flags.py")],
    [sys.executable, str(ROOT / "tools" / "check_juicy_lesson_references.py")],
    [sys.executable, str(ROOT / "tools" / "check_risk_flag_registry.py")],
    [sys.executable, str(ROOT / "tools" / "check_risk_flag_typical_sources.py")],
    [sys.executable, str(ROOT / "tools" / "check_product_profiles.py")],
    [sys.executable, str(ROOT / "tools" / "check_profile_default_vocabulary.py")],
    [sys.executable, str(ROOT / "tools" / "check_remote_assistance_recording_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_operator_access_recording_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_recording_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_recording_activation_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_repair_outcome_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_method_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_bootstrap_join_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_bootstrap_sequence_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_bootstrap_actuation_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_destructive_reprovision_evidence_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_firmware_evidence_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_trust_bundle_apply_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_trust_bundle_apply_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_event_seal_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_event_journal_digest_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_restore_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_restore_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_support_session_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_operator_session_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_bundle_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_export_receipt_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_anchor_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_live_locator_boundary.py")],
[sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_payload_anchor_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_case_object_exactness_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_case_object_validator_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_case_object_remote_protection_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_case_object_remote_protection_exactness_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_case_object_remote_locator_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_adapter_case_object_reverification_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_uefi_var_set_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_fw_update_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_fw_inventory_diff_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_boot_bless_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_storage_scrub_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_time_sync_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_time_degraded_response_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_crypto_compat_agent_projection_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_lease_snapshot_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_secret_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_pki_issue_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_reference_variance_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_reference_exception_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_reference_renewal_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_reference_selection_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_identity_provenance_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_action_verification_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_degraded_admission_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_rejected_override_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_verdict_projection_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_resumption_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_resumption_join_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_resumption_subject_binding_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_breakglass_resumption_temporal_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_learn_net_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_access_posture_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_lifetime_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_locator_posture_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_secret_handoff_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_secret_handoff_authn_mode_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_secret_lifetime_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_secret_consumption_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_support_session_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_authority_join_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_lease_id_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_maintenance_trigger_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_support_trigger_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_access_model_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_human_share_access_model_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_organization_exposure_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_surface_continuity_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_diagnostic_artifact_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_notes_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_visible_indicator_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_revocation_affordance_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_return_path_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_management_return_binding_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_post_end_management_return_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_terminal_end_condition_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_current_stack_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_post_end_access_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_binding_hints_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_binding_hint_exactness_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_webhook_validation_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_validation_hint_webhook_only_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_endpoint_hint_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_url_hint_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_https_url_hint_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_path_prefix_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_path_prefix_uri_safe_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_local_service_hint_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_hostname_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_remote_locator_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_remote_locator_value_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_remote_locator_uri_hint_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_destination_hint_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_publish_session_tailnet_access_model_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_session_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_summary_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_selector_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_artifact_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_import_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_normalization_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_approval_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_transport_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_acceptance_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_destination_binding_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_recipient_digest_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_remote_object_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_remote_validator_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_remote_protection_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_remote_locator_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_reverification_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_packet_capture_export_digest_stability_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_store_gc_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_base_set_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_tree_mount_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_hw_support_matrix_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_hw_support_promotion_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_hw_support_qualification_receipt_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_hw_support_qualification_profile_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_hw_support_qualification_freshness_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_hw_support_qualification_status_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_hw_support_conditions_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_hw_support_qualification_target_scope_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_graphics_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_session_surface_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_subject_exactness.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_grant_digest_join.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_single_delivery_exhaustion.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_effective_until.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_renewal_lineage.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_successor_scope.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_successor_payload_lineage.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_successor_payload_digest.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_successor_foreground.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_successor_delivery_mode.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_successor_rate_limit.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_successor_expires_at.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_constraints_closed_world.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_baseline_frozen.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_distinct_family_split.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_first_richer_rfc_target.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_finite_collection_autostop.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_snapshot_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_manifest_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_readonly_first.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_member_kind_floor.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_manifest_field_floor.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_manifest_order.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_manifest_digest.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_review_path_normalization.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_top_level_names.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_ancestor_closure.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_selected_roots.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_fresh_root.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_result_root_receipt.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_result_root_locator_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_result_root_display_snapshot_continuity.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_result_root_handle_opacity.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_placement_hint_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_profile_scope.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_artifact_family_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_example_joins.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_first_impl_aliasing.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_review_ui_path_compression.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_mime_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_collection_filesystem_metadata_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_datatransfer_finite_collection_current_stack_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_uri_open_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_file_open_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_document_edit_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_document_viewing_posture.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_sanitized_derivative_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_sanitized_ocr_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_sanitized_ocr_index_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_ocr_text_egress_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_working_copy_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_working_copy_save_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_reintegration_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_candidate_snapshot_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_candidate_supersession_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_candidate_same_origin_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_candidate_stale_target_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_candidate_stale_denial_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_candidate_retry_recovery_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_intent_role_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_role_binding_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_role_binding_diff_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_role_binding_event_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_workstation_role_binding_consent_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_precondition_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_import_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_authority_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_profile_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_apply_window_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_instance_identity_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_denial_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_denial_precedence_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_consumption_pointer_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_consumption_digest_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_consumption_binding_digest_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_consumption_diff_digest_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_consumption_previous_binding_digest_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_consumption_action_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_consumption_recovery_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_role_binding_policy_recovery_interpretation_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_support_bundle_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_support_bundle_import_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_safe_open_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_boot_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_reset_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_content_origin_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_strata_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_exec_integrity_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_keyless_identity_contract.py")],

    [sys.executable, str(ROOT / "tools" / "check_release_transparency_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_witness_policy_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_supplychain_verification_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_vulnerability_verification_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_attestation_admission_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_lease_authority_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_authority_budget_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_frontend_compile_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_package_recipe_surface_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_package_recipe_step_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_cross_platform_identity_boundary.py")],
    [sys.executable, str(ROOT / "tools" / "check_derive_unit_contract.py")],
    [sys.executable, str(ROOT / "tools" / "check_fuzz_contract.py")],

    [sys.executable, str(ROOT / "tools" / "check_curated_references.py")],
    [sys.executable, str(ROOT / "tools" / "check_release_curated_references.py")],
    [sys.executable, str(ROOT / "tools" / "check_generated_docs.py")],
    [sys.executable, str(ROOT / "tools" / "check_risk_register.py")],
    [sys.executable, str(ROOT / "tools" / "check_open_questions_decisions.py")],
    [sys.executable, str(ROOT / "tools" / "check_microvm_example_plan_digests.py")],
    [sys.executable, str(ROOT / "tools" / "check_microvm_receipt_reason_requirements.py")],
    [sys.executable, str(ROOT / "tools" / "check_microvm_reason_code_registry.py")],



    [sys.executable, str(ROOT / "tools" / "check_spec_example_coverage.py")],
    [sys.executable, str(ROOT / "tools" / "check_version.py")],
]



def run(cmd: list[str]) -> int:
    print(f"==> {' '.join(cmd)}")
    p = subprocess.run(cmd, cwd=ROOT)
    return int(p.returncode)


def main() -> int:
    rc = 0
    for cmd in CHECKS:
        r = run(cmd)
        if r != 0:
            rc = 1
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
