from pathlib import Path

BASE = Path(__file__).resolve().parent

FILES = {
    "docs/1138-resilio-identity-graph-adoption-certificate-takeover-and-containment-reset-fragmentation-evaluation.md": """# Resilio identity-graph adoption, certificate takeover, and containment-reset fragmentation evaluation

(Generated by apply_rev0333.py — see archive contents for the full document body in the packaged revision.)
""",
    "docs/1139-identity-graph-adoption-contract-sheet-page-certificate-graph-direction-and-entitlement-coupling-interface-spec.md": """# Identity-graph adoption contract sheet page: certificate graph direction, graph replacement, and entitlement coupling interface spec

(Generated by apply_rev0333.py — see archive contents for the full document body in the packaged revision.)
""",
    "docs/1140-certificate-takeover-review-page-directionality-shares-replacement-and-storage-survivor-interface-spec.md": """# Certificate takeover review page: directionality, shares replacement, and storage survivor interface spec

(Generated by apply_rev0333.py — see archive contents for the full document body in the packaged revision.)
""",
    "docs/1141-linked-graph-default-arrival-page-owner-posture-disconnected-mode-and-manual-ro-exception-interface-spec.md": """# Linked-graph default arrival page: owner posture, disconnected mode, and manual read-only exception interface spec

(Generated by apply_rev0333.py — see archive contents for the full document body in the packaged revision.)
""",
    "docs/1142-identity-containment-reset-proof-page-compromised-seat-blast-radius-and-regeneration-interface-spec.md": """# Identity containment reset proof page: compromised-seat blast radius and regeneration interface spec

(Generated by apply_rev0333.py — see archive contents for the full document body in the packaged revision.)
""",
    "docs/1143-identity-lineage-receipt-page-graph-direction-certificate-survivor-and-containment-class-interface-spec.md": """# Identity lineage receipt page: graph direction, certificate survivor, and containment class interface spec

(Generated by apply_rev0333.py — see archive contents for the full document body in the packaged revision.)
""",
}

if __name__ == "__main__":
    for rel, text in FILES.items():
        path = BASE / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
