#!/usr/bin/env python3
"""scripts/gen_evidence_object_catalog.py

Generate a small, human-readable catalog of EvidenceEnvelope kinds:
- kind registry (track/stability/payload schema)
- required attachments (anti-suppression)
- example packets that exercise each kind

This is a compression tool: it reduces duplicated lists across docs and helps cold-start verifiers.
Determinism requirement: given identical inputs, output must be byte-for-byte identical.
"""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

KIND_REG = ROOT / "artifacts" / "registries" / "envelope-kinds.csv"
ATT_REG = ROOT / "artifacts" / "registries" / "envelope-attachment-requirements.csv"
EXAMPLES_DIR = ROOT / "artifacts" / "examples"
OUT = ROOT / "docs" / "EVIDENCE_OBJECT_CATALOG.md"


def sha256_hex(p: Path) -> str:
    h = hashlib.sha256()
    h.update(p.read_bytes())
    return h.hexdigest()


def load_kind_registry() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    with KIND_REG.open(newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append(r)
    rows.sort(key=lambda r: r["kind"])
    return rows


def load_attachment_registry() -> dict[str, list[dict[str, str]]]:
    by_kind: dict[str, list[dict[str, str]]] = {}
    with ATT_REG.open(newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            by_kind.setdefault(r["kind"], []).append(r)
    for k, lst in by_kind.items():
        lst.sort(key=lambda r: (r["required"], r["rel"], r["attachment_schema"]))
    return by_kind


def find_example_packets() -> dict[str, list[str]]:
    """Return kind -> list of packet manifest paths (relative to repo root)."""
    out: dict[str, list[str]] = {}
    if not EXAMPLES_DIR.exists():
        return out
    for p in sorted(EXAMPLES_DIR.iterdir(), key=lambda x: x.name):
        if not p.is_dir():
            continue
        manifest = p / "manifest.json"
        if not manifest.exists():
            continue
        try:
            m = json.loads(manifest.read_text(encoding="utf-8"))
        except Exception:
            continue
        artifacts = m.get("artifacts", [])
        for a in artifacts:
            k = a.get("kind")
            # EvidenceEnvelope kinds are registered; payload pseudo-kinds often end with .payload
            if isinstance(k, str) and k.startswith("hfv.") and not k.endswith(".payload"):
                out.setdefault(k, []).append(str(manifest.relative_to(ROOT)).replace("\\", "/"))
    for k, lst in out.items():
        # stable, de-duplicated ordering
        out[k] = sorted(set(lst))
    return out


def main() -> int:
    kinds = load_kind_registry()
    atts = load_attachment_registry()
    examples = find_example_packets()

    lines: list[str] = []
    lines.append("# Evidence object catalog\n")
    lines.append("This file is generated by `scripts/gen_evidence_object_catalog.py`.\n")
    lines.append("It summarizes the verifier-facing EvidenceEnvelope kinds, required anti-suppression attachments, and example packets.\n")

    lines.append("## EvidenceEnvelope kinds\n")
    lines.append("| kind | track | stability | payload schema | schema sha256 | required attachments | example packet(s) |\n")
    lines.append("|---|---:|---:|---|---|---|---|\n")

    for r in kinds:
        kind = r["kind"]
        track = r.get("track", "")
        stability = r.get("stability", "")
        schema_path = r.get("payload_schema", "")
        schema_file = ROOT / schema_path if schema_path else None
        schema_link = f"[`{schema_path}`](../{schema_path})" if schema_path else ""
        schema_hash = sha256_hex(schema_file) if (schema_file and schema_file.exists()) else ""

        req = []
        for a in atts.get(kind, []):
            if a.get("required", "").strip().lower() in ("yes", "true", "1"):
                req.append(a.get("rel", "").strip())
        req = sorted(set([x for x in req if x]))
        req_s = ", ".join([f"`{x}`" for x in req]) if req else ""

        ex_paths = examples.get(kind, [])
        if ex_paths:
            ex_links = ", ".join([f"[`{p}`](../{p})" for p in ex_paths])
        else:
            ex_links = ""

        lines.append(f"| `{kind}` | `{track}` | `{stability}` | {schema_link} | `{schema_hash}` | {req_s} | {ex_links} |\n")

    content = "".join(lines)
    OUT.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
