from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from vhk.project.loader import load_project
from vhk.project.strategy import summarize_project_strategy


def _write_if_allowed(path: Path, content: bytes | str, *, force: bool) -> None:
    if path.exists() and not force:
        raise ValueError(f"Refusing to overwrite existing file: {path}. Use --force.")
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content)


def _trim_items(items: list[dict[str, Any]] | None, limit: int = 6) -> list[dict[str, Any]]:
    return [dict(item) for item in list(items or [])[:limit] if isinstance(item, dict)]


def _first_text(item: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = item.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def build_design_pack_plan(
    project_dir: Path,
    *,
    capability_usage: dict[str, list[dict[str, object]]] | None = None,
    capability_matrix: dict[str, object] | None = None,
    capability_issues: list[dict[str, object]] | None = None,
) -> dict[str, Any]:
    project = load_project(project_dir)
    return summarize_project_strategy(
        project,
        capability_usage=capability_usage,
        capability_matrix=capability_matrix,
        capability_issues=capability_issues,
    )


def render_design_brief(plan: dict[str, Any]) -> str:
    project = dict(plan.get("project") or {})
    overview = dict(plan.get("overview") or {})
    stack_profiles = _trim_items(plan.get("stack_profiles") or plan.get("deployment_profiles"), limit=5)
    runtime_seams = _trim_items(plan.get("runtime_seams"), limit=6)
    ecosystem_lessons = _trim_items(plan.get("ecosystem_lessons"), limit=7)
    implementation_waves = _trim_items(plan.get("implementation_waves"), limit=4)
    next_steps = _trim_items(plan.get("next_steps"), limit=6)
    setup_recipes = _trim_items(plan.get("setup_recipes"), limit=4)

    lines: list[str] = []
    lines.append(f"# VHK design brief for {project.get('name') or 'project'}")
    lines.append("")
    lines.append("Generated by `vhk gen-design-pack`. This is the product/runtime architecture handoff version of `vhk plan-project`.")
    lines.append("")

    lines.append("## Project snapshot")
    lines.append("")
    lines.append(f"- Root: `{project.get('root_dir') or '.'}`")
    lines.append(f"- Desktop backend: `{project.get('desktop_backend') or 'unknown'}`")
    lines.append(f"- Macros: {overview.get('macros', 0)}")
    lines.append(f"- Bindings: {overview.get('bindings', 0)}")
    lines.append(f"- Hotstrings: {overview.get('hotstrings', 0)}")
    lines.append(f"- Bus watchers: {overview.get('bus_watchers', 0)}")
    lines.append(f"- Clipboard watchers: {overview.get('clipboard_watchers', 0)}")
    lines.append(f"- Window watchers: {overview.get('window_watchers', 0)}")
    tags = list(plan.get("project_tags") or [])
    if tags:
        lines.append(f"- Tags: {', '.join(str(tag) for tag in tags)}")
    lines.append("")

    architecture = dict(plan.get("architecture_map") or {})
    stance = _first_text(architecture, "stance", "summary", "why")
    if stance:
        lines.append("## Architecture stance")
        lines.append("")
        lines.append(stance)
        lines.append("")

    if stack_profiles:
        lines.append("## Recommended stack profiles")
        lines.append("")
        for item in stack_profiles:
            title = item.get("title") or item.get("id") or "profile"
            lines.append(f"### {title}")
            summary = _first_text(item, "summary", "ownership_split", "why_linux_native", "description")
            if summary:
                lines.append(summary)
            product_shape = str(item.get("product_shape") or "").strip()
            if product_shape:
                lines.append("")
                lines.append(f"Product shape: `{product_shape}`")
            thin_layers = list(item.get("thin_layers") or [])
            if thin_layers:
                lines.append("")
                lines.append("Thin layers:")
                for entry in thin_layers[:4]:
                    lines.append(f"- {entry}")
            stateful_layers = list(item.get("stateful_layers") or [])
            if stateful_layers:
                lines.append("")
                lines.append("Stateful layers:")
                for entry in stateful_layers[:4]:
                    lines.append(f"- {entry}")
            commands = list(item.get("commands") or [])
            if commands:
                lines.append("")
                lines.append("Start here:")
                for cmd in commands[:3]:
                    lines.append(f"- `{cmd}`")
            lines.append("")

    if runtime_seams:
        lines.append("## Runtime seams")
        lines.append("")
        for item in runtime_seams:
            title = item.get("title") or item.get("id") or "seam"
            lines.append(f"### {title}")
            responsibility = _first_text(item, "responsibility", "summary", "why")
            why_split = _first_text(item, "why_split", "notes")
            if responsibility:
                lines.append(responsibility)
            if why_split:
                lines.append("")
                lines.append(f"Why this seam exists: {why_split}")
            contracts = list(item.get("contracts") or [])
            if contracts:
                lines.append("")
                lines.append("Contract:")
                for contract in contracts[:4]:
                    lines.append(f"- {contract}")
            artifacts = list(item.get("artifacts") or [])
            if artifacts:
                lines.append("")
                lines.append("Artifacts / surfaces:")
                for artifact in artifacts[:4]:
                    lines.append(f"- {artifact}")
            lines.append("")

    if ecosystem_lessons:
        lines.append("## Ecosystem lessons carried into the design")
        lines.append("")
        for item in ecosystem_lessons:
            title = item.get("title") or item.get("id") or "lesson"
            summary = _first_text(item, "summary", "why", "description")
            implication = _first_text(item, "product_implication", "implication", "notes")
            tools = list(item.get("source_tools") or [])
            tool_text = f" (from {', '.join(str(x) for x in tools[:3])})" if tools else ""
            lines.append(f"### {title}{tool_text}")
            if summary:
                lines.append(summary)
            if implication:
                lines.append("")
                lines.append(f"What VHK should do: {implication}")
            commands = list(item.get("commands") or [])
            if commands:
                lines.append("")
                lines.append("Review / apply with:")
                for cmd in commands[:3]:
                    lines.append(f"- `{cmd}`")
            lines.append("")

    if implementation_waves:
        lines.append("## Implementation waves")
        lines.append("")
        for item in implementation_waves:
            title = item.get("title") or item.get("id") or "wave"
            order = item.get("order")
            lines.append(f"### Wave {order}: {title}" if order is not None else f"### {title}")
            objective = _first_text(item, "objective", "summary", "why_now")
            if objective:
                lines.append(objective)
            deliverables = list(item.get("deliverables") or [])
            if deliverables:
                lines.append("")
                lines.append("Deliverables:")
                for entry in deliverables[:4]:
                    lines.append(f"- {entry}")
            lines.append("")

    if setup_recipes or next_steps:
        lines.append("## Immediate next moves")
        lines.append("")
        for item in setup_recipes:
            title = item.get("title") or item.get("id") or "recipe"
            summary = _first_text(item, "summary", "when_to_use", "why")
            lines.append(f"- **{title}** — {summary or 'review install/verify flow'}")
        for item in next_steps[:4]:
            title = item.get("title") or item.get("id") or "step"
            details = _first_text(item, "details", "summary", "why")
            lines.append(f"- **{title}** — {details or 'planner-backed next step'}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"



def render_runtime_contract(plan: dict[str, Any]) -> str:
    project = dict(plan.get("project") or {})
    runtime_seams = _trim_items(plan.get("runtime_seams"), limit=8)
    stack_profiles = _trim_items(plan.get("stack_profiles") or plan.get("deployment_profiles"), limit=4)
    toolchain_choices = _trim_items(plan.get("toolchain_choices"), limit=6)
    verification_gates = _trim_items(plan.get("verification_gates"), limit=5)
    session_capabilities = dict(plan.get("session_capabilities") or {})
    session_issues = list(plan.get("session_issues") or [])

    lines: list[str] = []
    lines.append(f"# VHK runtime contract for {project.get('name') or 'project'}")
    lines.append("")
    lines.append("Generated by `vhk gen-design-pack`. This file spells out which layers stay inside VHK and which should remain thin exported/helper surfaces.")
    lines.append("")

    if stack_profiles:
        lines.append("## Leading stack profiles")
        lines.append("")
        for item in stack_profiles:
            title = item.get("title") or item.get("id") or "profile"
            lines.append(f"- **{title}** — {_first_text(item, 'ownership_split', 'summary', 'why_linux_native') or 'review planner output'}")
        lines.append("")

    if runtime_seams:
        lines.append("## Layer ownership")
        lines.append("")
        for item in runtime_seams:
            title = item.get("title") or item.get("id") or "seam"
            owner = str(item.get("owner") or "VHK").strip()
            layer_kind = str(item.get("layer_kind") or "layer").strip()
            lines.append(f"### {title}")
            lines.append(f"- Kind: `{layer_kind}`")
            lines.append(f"- Owner: {owner}")
            responsibility = _first_text(item, "responsibility", "summary", "why")
            if responsibility:
                lines.append(f"- Responsibility: {responsibility}")
            why_split = _first_text(item, "why_split", "notes")
            if why_split:
                lines.append(f"- Why split: {why_split}")
            contracts = list(item.get("contracts") or [])
            if contracts:
                lines.append("- Contract checks:")
                for contract in contracts[:4]:
                    lines.append(f"  - {contract}")
            commands = list(item.get("commands") or [])
            if commands:
                lines.append("- Review commands:")
                for cmd in commands[:3]:
                    lines.append(f"  - `{cmd}`")
            notes = list(item.get("notes") or [])
            if notes:
                lines.append("- Notes:")
                for note in notes[:4]:
                    lines.append(f"  - {note}")
            lines.append("")

    if toolchain_choices:
        lines.append("## Toolchain boundary choices")
        lines.append("")
        for item in toolchain_choices:
            title = item.get("title") or item.get("id") or "toolchain"
            recommended = str(item.get("recommended_toolchain") or "").strip() or "n/a"
            fallbacks = list(item.get("fallback_toolchains") or [])
            lines.append(f"- **{title}** — recommended: `{recommended}`; fallbacks: {', '.join(str(x) for x in fallbacks[:4]) or 'n/a'}")
        lines.append("")

    if verification_gates:
        lines.append("## Release discipline")
        lines.append("")
        for item in verification_gates:
            title = item.get("title") or item.get("id") or "gate"
            summary = _first_text(item, "summary", "why", "description")
            lines.append(f"- **{title}** — {summary or 'planner-backed release gate'}")
        lines.append("")

    if session_capabilities:
        lines.append("## Current session snapshot")
        lines.append("")
        for capability in [
            "screen_capture",
            "text_injection",
            "pointer_injection",
            "global_hotkeys",
            "window_introspection",
            "input_capture",
        ]:
            item = session_capabilities.get(capability)
            if not isinstance(item, dict):
                continue
            status = str(item.get("status") or "unknown")
            recommended = str(item.get("recommended") or "n/a")
            lines.append(f"- **{capability}** — `{status}`; recommended: `{recommended}`")
        if session_issues:
            lines.append("")
            lines.append("Session warnings:")
            for item in session_issues[:6]:
                message = _first_text(item, "message", "summary", "why")
                suggestion = _first_text(item, "suggestion", "response", "notes")
                if suggestion:
                    lines.append(f"- {message} — {suggestion}")
                else:
                    lines.append(f"- {message}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"



def write_design_pack(
    project_dir: Path,
    *,
    out_dir: Path | None = None,
    force: bool = False,
    brief: bool = True,
    contract: bool = True,
    plan_json: bool = True,
    capability_usage: dict[str, list[dict[str, object]]] | None = None,
    capability_matrix: dict[str, object] | None = None,
    capability_issues: list[dict[str, object]] | None = None,
) -> dict[str, Path]:
    project_dir = project_dir.expanduser().resolve()
    out_dir = out_dir.expanduser().resolve() if out_dir is not None else (project_dir / "docs")
    plan = build_design_pack_plan(
        project_dir,
        capability_usage=capability_usage,
        capability_matrix=capability_matrix,
        capability_issues=capability_issues,
    )

    written: dict[str, Path] = {}
    if brief:
        path = out_dir / "VHK_DESIGN_BRIEF.md"
        _write_if_allowed(path, render_design_brief(plan), force=force)
        written["brief"] = path
    if contract:
        path = out_dir / "VHK_RUNTIME_CONTRACT.md"
        _write_if_allowed(path, render_runtime_contract(plan), force=force)
        written["contract"] = path
    if plan_json:
        path = out_dir / "VHK_DESIGN_PLAN.json"
        _write_if_allowed(path, json.dumps(plan, indent=2, sort_keys=False) + "\n", force=force)
        written["plan_json"] = path
    return written
