from __future__ import annotations

from pathlib import Path
from typing import Any


FLAGSHIP_STACK_INSTALL_HANDOFF_KIND = "vhk.i3_x11.flagship_stack_install_handoff"


def build_i3_x11_flagship_stack_install_handoff(
    *,
    project_dir: Path,
    stack_install_pack: dict[str, Any],
) -> dict[str, Any]:
    install_story = dict((stack_install_pack or {}).get("install_story") or {})
    install_summary = dict((stack_install_pack or {}).get("install_summary") or {})
    unit_base = str(install_story.get("unit_base") or "vhk-busd-project").strip() or "vhk-busd-project"
    command_name = str(install_story.get("command_name") or unit_base).strip() or unit_base
    payload_rel = str(install_story.get("payload_rel") or f"vhk/{command_name}/session-service")
    handoff_summary = {
        "unit_base": unit_base,
        "payload_rel": payload_rel,
        "helper_json": "install_lane_ticket_json.sh",
        "helper_text": "install_lane_ticket.sh",
        "status_ids": [
            "install_not_deployed",
            "repair_required",
            "start_recommended",
            "active",
        ],
        "recommended_surface_order": [
            "install_lane_ticket_json.sh",
            "verify_user_session_json.sh",
            "repair_user_session.sh",
            "install_user_session.sh",
        ],
    }
    return {
        "pack_kind": FLAGSHIP_STACK_INSTALL_HANDOFF_KIND,
        "project_root": str(project_dir.expanduser().resolve()),
        "install_story": install_story,
        "install_summary": install_summary,
        "handoff_summary": handoff_summary,
    }


def render_i3_x11_flagship_stack_install_lane_ticket_json(pack: dict[str, Any]) -> str:
    del pack
    lines = [
        "#!/usr/bin/env sh",
        "set -eu",
        "",
        'SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"',
        'VERIFY_JSON="$SCRIPT_DIR/../verify_user_session_json.sh"',
        'if [ ! -x "$VERIFY_JSON" ]; then',
        "  python3 - <<'PY'",
        "import json",
        "payload = {",
        '    "schema_version": 1,',
        '    "stack_kind": "vhk.i3_x11.flagship_install_lane_ticket",',
        '    "status_id": "install_verifier_missing",',
        '    "route_id": "inspect_install_helpers",',
        '    "deployed": False,',
        '    "install_complete": False,',
        '    "runtime_startable_now": False,',
        '    "runtime_active_now": False,',
        '    "summary": "Installed-lane verifier is missing from the generated stack.",',
        '    "reason": "verify_user_session_json.sh is missing or not executable.",',
        '    "recommended": {"id": "inspect_install_helpers", "command": "./verify_user_session.sh", "reason": "Verify helper is missing from the generated stack."},',
        '    "source_helper": {"name": "verify_user_session_json", "command": "./verify_user_session_json.sh", "available": False},',
        "}",
        "print(json.dumps(payload, indent=2, sort_keys=False))",
        "PY",
        "  exit 0",
        "fi",
        'TMP_JSON="$(mktemp "${TMPDIR:-/tmp}/vhk-install-lane-ticket.XXXXXX.json")"',
        "trap 'rm -f \"$TMP_JSON\"' EXIT HUP INT TERM",
        'sh "$VERIFY_JSON" > "$TMP_JSON"',
        "python3 - \"$TMP_JSON\" <<'PY'",
        "import json, pathlib, sys",
        "payload = json.loads(pathlib.Path(sys.argv[1]).read_text())",
        "artifacts = dict(payload.get('artifacts') or {})",
        "paths = dict(payload.get('paths') or {})",
        "warnings = list(payload.get('warnings') or [])",
        "payload_dir = str(paths.get('payload_dir') or '').strip()",
        "start_helper_command = f'{payload_dir}/start_user_session.sh' if payload_dir else None",
        "artifact_flags = [",
        "    artifacts.get('payload_present') is True,",
        "    artifacts.get('service_present') is True,",
        "    artifacts.get('i3_include_present') is True,",
        "    artifacts.get('sync_helper_present') is True,",
        "    artifacts.get('start_helper_present') is True,",
        "    artifacts.get('readiness_helper_present') is True,",
        "    artifacts.get('targets_helper_present') is True,",
        "    artifacts.get('handoff_helper_present') is True,",
        "    artifacts.get('socket_present') is True,",
        "    artifacts.get('autostart_present') is True,",
        "    ]",
        "deployed = any(artifact_flags)",
        "install_complete = bool(payload.get('install_complete'))",
        "runtime_startable_now = bool(payload.get('runtime_startable_now'))",
        "runtime_active_now = bool(payload.get('runtime_active_now'))",
        "source_helper = {'name': 'verify_user_session_json', 'command': './verify_user_session_json.sh', 'available': True}",
        "text_helper = {'name': 'verify_user_session', 'command': './verify_user_session.sh', 'available': True}",
        "if not deployed:",
        "    status_id = 'install_not_deployed'",
        "    route_id = 'install_generated_stack'",
        "    summary = 'Installed warm lane is not deployed yet.'",
        "    reason = 'No installed XDG-local user-unit, payload, or i3 include artifacts were found for the flagship stack.'",
        "    recommended = {'id': 'install_generated_stack', 'command': './install_user_session.sh', 'reason': 'Install the generated stack into XDG-local user paths before prioritizing installed-lane repair or startup.', 'followup': ['./smoke_install.sh', './verify_user_session_json.sh']}",
        "elif runtime_active_now:",
        "    status_id = 'active'",
        "    route_id = 'observe_installed_lane'",
        "    summary = 'Installed warm lane is active on the current session.'",
        "    reason = str(payload.get('summary') or 'The installed lane is already active and should be observed rather than restarted blindly.')",
        "    recommended = {'id': 'observe_installed_lane', 'command': './verify_user_session_json.sh', 'reason': 'Installed artifacts and the current session already look active; inspect before changing startup ownership.', 'followup': ['./verify_user_session.sh', './bin/status_runtime_json.sh']}",
        "elif install_complete and runtime_startable_now:",
        "    status_id = 'start_recommended'",
        "    route_id = 'start_installed_lane'",
        "    summary = 'Installed warm lane is present and session-fit but not active yet.'",
        "    reason = 'Installed artifacts are complete and the live X11/i3 session looks startable, so the next move is to start the installed lane instead of reinstalling it.'",
        "    recommended = {'id': 'start_installed_lane', 'command': start_helper_command or './repair_user_session.sh', 'reason': 'Start the installed lane from its payload helper when possible, then re-verify the installed-lane verdict.', 'followup': ['./verify_user_session_json.sh', './bin/status_runtime_json.sh']}",
        "else:",
        "    status_id = 'repair_required'",
        "    route_id = 'repair_installed_lane'",
        "    summary = 'Installed warm lane exists but needs repair before it should be trusted.'",
        "    reason = '; '.join(warnings) or str(payload.get('summary') or 'Installed artifacts are present but the lane is incomplete, session-unfit, or drifted.')",
        "    recommended = {'id': 'repair_installed_lane', 'command': './repair_user_session.sh', 'reason': 'Installed artifacts already exist, so repair should stay on the bounded reinstall + session-start bridge.', 'followup': ['./verify_user_session_json.sh', './bin/status_runtime_json.sh']}",
        "ticket = {",
        '    "schema_version": 1,',
        '    "stack_kind": "vhk.i3_x11.flagship_install_lane_ticket",',
        "    'status_id': status_id,",
        "    'route_id': route_id,",
        "    'deployed': deployed,",
        "    'install_complete': install_complete,",
        "    'runtime_startable_now': runtime_startable_now,",
        "    'runtime_active_now': runtime_active_now,",
        "    'summary': summary,",
        "    'reason': reason,",
        "    'warnings': warnings,",
        "    'recommended': recommended,",
        "    'verdict': payload,",
        "    'source_helper': source_helper,",
        "    'text_helper': text_helper,",
        "    'signals': {",
        "        'session_readiness_ok': ((payload.get('session') or {}).get('readiness_ok')),",
        "        'session_targets_ok': ((payload.get('session') or {}).get('targets_ok')),",
        "        'startup_handoff_ok': ((payload.get('session') or {}).get('startup_handoff_ok')),",
        "        'unit_active_state': ((payload.get('systemd_user') or {}).get('active_state')),",
        "        'unit_enabled_state': ((payload.get('systemd_user') or {}).get('enabled_state')),",
        "        'warning_count': len(warnings),",
        "    },",
        "}",
        "print(json.dumps(ticket, indent=2, sort_keys=False))",
        "PY",
        "",
    ]
    return "\n".join(lines)


def render_i3_x11_flagship_stack_install_lane_ticket(pack: dict[str, Any]) -> str:
    del pack
    lines = [
        "#!/usr/bin/env sh",
        "set -eu",
        "",
        'SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"',
        'TICKET_JSON="$SCRIPT_DIR/install_lane_ticket_json.sh"',
        'if [ ! -x "$TICKET_JSON" ]; then',
        '  echo "install_lane_ticket_json.sh is missing or not executable" >&2',
        '  exit 1',
        'fi',
        'TMP_JSON="$(mktemp "${TMPDIR:-/tmp}/vhk-install-lane-ticket-view.XXXXXX.json")"',
        "trap 'rm -f \"$TMP_JSON\"' EXIT HUP INT TERM",
        'sh "$TICKET_JSON" > "$TMP_JSON"',
        "python3 - \"$TMP_JSON\" <<'PY'",
        "import json, pathlib, sys",
        "payload = json.loads(pathlib.Path(sys.argv[1]).read_text())",
        "print(payload.get('summary') or 'installed-lane status unavailable')",
        "print('status_id:', payload.get('status_id'))",
        "print('deployed:', payload.get('deployed'))",
        "print('install_complete:', payload.get('install_complete'))",
        "print('runtime_startable_now:', payload.get('runtime_startable_now'))",
        "print('runtime_active_now:', payload.get('runtime_active_now'))",
        "reason = payload.get('reason')",
        "if reason:",
        "    print('reason:', reason)",
        "recommended = dict(payload.get('recommended') or {})",
        "if recommended.get('command'):",
        "    print('next command:', recommended.get('command'))",
        "warnings = list(payload.get('warnings') or [])",
        "if warnings:",
        "    print('warnings:', ', '.join(warnings))",
        "PY",
        "",
    ]
    return "\n".join(lines)
