from __future__ import annotations

import base64
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import json
import yaml

from vhk.project.loader import load_project
from vhk.project.schema import write_default_schemas
from vhk.project.strategy import summarize_project_strategy


ProjectTemplate = Literal["minimal", "demo", "vision"]


_PNG_1X1_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wwAAgMBAp1RXr8AAAAASUVORK5CYII="
)


@dataclass
class InitResult:
    project_dir: Path
    created_files: list[Path]
    created_dirs: list[Path]
    starter_plan_path: Path | None = None
    starter_guide_path: Path | None = None


def _ensure_empty_dir(path: Path, *, force: bool) -> None:
    if path.exists():
        if not path.is_dir():
            raise ValueError(f"Project path exists and is not a directory: {path}")
        # Allow empty directories.
        if any(path.iterdir()) and not force:
            raise ValueError(
                f"Project directory is not empty: {path}. Use --force to overwrite files in-place."
            )
    else:
        path.mkdir(parents=True, exist_ok=True)


def _write_if_allowed(path: Path, content: bytes | str, *, force: bool) -> None:
    if path.exists() and not force:
        raise ValueError(f"Refusing to overwrite existing file: {path}. Use --force.")
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content)


def _yaml_with_modeline(modeline: str | None, payload: dict) -> str:
    """Serialize YAML with an optional yaml-language-server modeline."""

    body = yaml.safe_dump(payload, sort_keys=False)
    if not modeline:
        return body
    # Modeline must be on the first line.
    return f"# yaml-language-server: $schema={modeline}\n" + body


def _trim_items(items: list[dict[str, Any]] | None, limit: int = 5) -> list[dict[str, Any]]:
    return [dict(item) for item in list(items or [])[:limit] if isinstance(item, dict)]


def _first_text(item: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = item.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def _render_artifact_summary(item: Any) -> str:
    if isinstance(item, str):
        return item
    if isinstance(item, dict):
        title = str(item.get("title") or item.get("id") or "artifact")
        path_hint = str(item.get("path_hint") or item.get("install_hint") or "").strip()
        if path_hint:
            return f"{title} (`{path_hint}`)"
        return title
    return str(item)


def _render_starter_guide(plan: dict[str, Any]) -> str:
    project = dict(plan.get("project") or {})
    overview = dict(plan.get("overview") or {})
    product_lanes = _trim_items(plan.get("product_lanes"), limit=3)
    integration_targets = _trim_items(plan.get("integration_targets"), limit=4)
    deployable_surfaces = _trim_items(plan.get("deployable_surfaces"), limit=5)
    setup_recipes = _trim_items(plan.get("setup_recipes"), limit=5)
    toolchain_choices = _trim_items(plan.get("toolchain_choices"), limit=4)
    reference_patterns = _trim_items(plan.get("reference_patterns"), limit=4)
    verification_gates = _trim_items(plan.get("verification_gates"), limit=3)

    lines: list[str] = []
    lines.append(f"# VHK starter guide for {project.get('name') or 'project'}")
    lines.append("")
    lines.append("Generated by `vhk init` from the same planner heuristics used by `vhk plan-project`.")
    lines.append("This is intentionally capability-agnostic: refresh it later with `vhk doctor`, `vhk validate`, and `vhk plan-project` on the target session before shipping.")
    lines.append("")
    lines.append("## Project snapshot")
    lines.append("")
    lines.append(f"- Macros: {overview.get('macros', 0)}")
    lines.append(f"- Bindings: {overview.get('bindings', 0)}")
    lines.append(f"- Hotstrings: {overview.get('hotstrings', 0)}")
    lines.append(f"- Clipboard watchers: {overview.get('clipboard_watchers', 0)}")
    lines.append(f"- File watchers: {overview.get('file_watchers', 0)}")
    lines.append(f"- Window watchers: {overview.get('window_watchers', 0)}")
    lines.append(f"- Presets: {overview.get('presets', 0)}")
    lines.append("")

    if product_lanes:
        lines.append("## Likely product lanes")
        lines.append("")
        for item in product_lanes:
            title = item.get('title') or item.get('id') or 'lane'
            lines.append(f"### {title}")
            summary = _first_text(item, 'summary', 'why', 'description', 'notes')
            if summary:
                lines.append(str(summary))
            strengths = list(item.get('strengths') or [])
            if strengths:
                lines.append("")
                lines.append("Strengths:")
                for s in strengths[:4]:
                    lines.append(f"- {s}")
            lines.append("")

    if integration_targets:
        lines.append("## Integration targets to keep in mind")
        lines.append("")
        for item in integration_targets:
            title = item.get('title') or item.get('id') or 'target'
            summary = _first_text(item, 'summary', 'why', 'description', 'notes')
            if summary:
                lines.append(f"- **{title}** — {summary}")
            else:
                lines.append(f"- **{title}**")
        lines.append("")

    if deployable_surfaces:
        lines.append("## Deployable surfaces")
        lines.append("")
        for item in deployable_surfaces:
            title = item.get('title') or item.get('id') or 'surface'
            lines.append(f"### {title}")
            summary = _first_text(item, 'summary', 'why', 'description', 'notes')
            if summary:
                lines.append(str(summary))
            artifacts = list(item.get('artifacts') or [])
            if artifacts:
                lines.append("")
                lines.append("Representative artifacts:")
                for art in artifacts[:4]:
                    lines.append(f"- {_render_artifact_summary(art)}")
            lines.append("")

    if setup_recipes:
        lines.append("## Setup recipes")
        lines.append("")
        for item in setup_recipes:
            title = item.get('title') or item.get('id') or 'recipe'
            lines.append(f"### {title}")
            summary = _first_text(item, 'summary', 'why', 'description', 'notes')
            if summary:
                lines.append(str(summary))
            steps = list(item.get('steps') or [])
            if steps:
                lines.append("")
                lines.append("Suggested handoff:")
                for step in steps[:5]:
                    lines.append(f"- {step}")
            lines.append("")

    if toolchain_choices:
        lines.append("## Toolchain choices worth reviewing")
        lines.append("")
        for item in toolchain_choices:
            title = item.get('title') or item.get('id') or 'choice'
            summary = _first_text(item, 'summary', 'why', 'description', 'notes')
            if summary:
                lines.append(f"- **{title}** — {summary}")
            else:
                lines.append(f"- **{title}**")
        lines.append("")

    if reference_patterns:
        lines.append("## Reference patterns to study")
        lines.append("")
        for item in reference_patterns:
            title = item.get('title') or item.get('id') or 'pattern'
            summary = _first_text(item, 'summary', 'why', 'description', 'notes')
            if summary:
                lines.append(f"- **{title}** — {summary}")
            else:
                lines.append(f"- **{title}**")
        lines.append("")

    lines.append("## Suggested commands")
    lines.append("")
    lines.append("```bash")
    lines.append("vhk doctor --json")
    lines.append("vhk validate . --json")
    lines.append("vhk plan-project . --json")
    lines.append("```")
    lines.append("")

    if verification_gates:
        lines.append("## Early verification gates")
        lines.append("")
        for item in verification_gates:
            title = item.get('title') or item.get('id') or 'gate'
            lines.append(f"### {title}")
            summary = _first_text(item, 'summary', 'why', 'description', 'notes')
            if summary:
                lines.append(str(summary))
            checks = list(item.get('checks') or [])
            if checks:
                lines.append("")
                lines.append("Checks:")
                for check in checks[:5]:
                    lines.append(f"- {check}")
            lines.append("")

    return "\n".join(line.rstrip() for line in lines).rstrip() + "\n"


def build_starter_plan(project_dir: Path) -> dict[str, Any]:
    """Load a freshly initialized project and emit a capability-agnostic starter plan."""

    project = load_project(project_dir)
    return summarize_project_strategy(project)


def write_starter_artifacts(project_dir: Path, *, force: bool) -> tuple[Path, Path]:
    """Write starter planning artifacts for a new project."""

    docs_dir = project_dir / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    plan = build_starter_plan(project_dir)
    plan_path = docs_dir / "VHK_STARTER_PLAN.json"
    guide_path = docs_dir / "VHK_STARTER_GUIDE.md"
    _write_if_allowed(plan_path, json.dumps(plan, ensure_ascii=False, indent=2) + "\n", force=force)
    _write_if_allowed(guide_path, _render_starter_guide(plan), force=force)
    return plan_path, guide_path


def _macro_template(name: str, template: ProjectTemplate) -> dict:
    if template == "minimal":
        return {
            "name": name,
            "steps": [
                {"type": "Log", "message": "Hello from VHK."},
                {"type": "Return", "value_expr": "'OK'", "out_var": "return_value"},
            ],
        }

    if template == "demo":
        return {
            "name": name,
            "steps": [
                {"type": "Notify", "title": "VHK", "message": "Demo macro started"},
                {"type": "Delay", "ms": 250},
                {"type": "TypeText", "text": "Hello, world!", "backend": "native", "delay_ms_per_char": 12},
                {"type": "Key", "keys": "enter"},
                {"type": "Return", "value_expr": "'OK'", "out_var": "return_value"},
            ],
        }

    # vision
    return {
        "name": name,
        "steps": [
            {
                "type": "WaitForImage",
                "enabled": False,
                "comment": "TODO: capture a needle and enable this wait (avoid fixed sleeps)",
                "needle_path": "assets/TODO.png",
                "timeout_ms": 5000,
            },
            {
                "type": "ClickNeedle",
                "enabled": False,
                "comment": "TODO: replace with your own captured needle",
                "needle_path": "assets/TODO.png",
            },
            {"type": "Return", "value_expr": "'OK'", "out_var": "return_value"},
        ],
    }


def init_project(
    project_dir: Path,
    *,
    name: str | None = None,
    template: ProjectTemplate = "minimal",
    with_schemas: bool = True,
    with_vscode_settings: bool = True,
    force: bool = False,
    with_starter_guide: bool = True,
    with_starter_plan_json: bool = True,
) -> InitResult:
    """Create a new VHK project skeleton."""

    project_dir = project_dir.expanduser().resolve()
    _ensure_empty_dir(project_dir, force=force)

    created_files: list[Path] = []
    created_dirs: list[Path] = []

    # Standard folders.
    for rel in [
        Path("macros"),
        Path("assets"),
        Path("assets/needles"),
        Path("assets/baselines"),
        Path("logs"),
    ]:
        p = project_dir / rel
        if not p.exists():
            p.mkdir(parents=True, exist_ok=True)
            created_dirs.append(p)

    # A tiny placeholder PNG that scaffolding/vision templates can reference.
    todo_png = project_dir / "assets" / "TODO.png"
    _write_if_allowed(todo_png, base64.b64decode(_PNG_1X1_B64), force=force)
    created_files.append(todo_png)

    todo_json = project_dir / "assets" / "TODO.json"
    _write_if_allowed(
        todo_json,
        json.dumps(
            {
                "tags": ["todo"],
                "area": [
                    {
                        "type": "match",
                        "xpos": 0,
                        "ypos": 0,
                        "width": 1,
                        "height": 1,
                    }
                ],
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        force=force,
    )
    created_files.append(todo_json)

    if with_schemas:
        created = write_default_schemas(project_dir, force=force, with_vscode_settings=with_vscode_settings)
        created_files.extend(created)

    # Starter macro.
    macro_name = "main"
    macro_path = project_dir / "macros" / f"{macro_name}.yaml"
    macro_payload = _macro_template(macro_name, template)
    macro_modeline = "../schemas/vhk_macro.schema.json" if with_schemas else None
    _write_if_allowed(macro_path, _yaml_with_modeline(macro_modeline, macro_payload), force=force)
    created_files.append(macro_path)

    project_name = name or project_dir.name
    project_yaml = project_dir / "project.yaml"
    project_payload = {
        "name": project_name,
        "macros": {macro_name: f"macros/{macro_name}.yaml"},
        "regions": {},
        "bindings": [],
        "hotstrings": [],
        "clipboard_watchers": [],
        "file_watchers": [],
        "window_watchers": [],
    }
    proj_modeline = "schemas/vhk_project.schema.json" if with_schemas else None
    _write_if_allowed(project_yaml, _yaml_with_modeline(proj_modeline, project_payload), force=force)
    created_files.append(project_yaml)

    gitignore = project_dir / ".gitignore"
    _write_if_allowed(
        gitignore,
        """# VHK project artifacts\nlogs/\n__pycache__/\n*.pyc\n.DS_Store\n""",
        force=force,
    )
    created_files.append(gitignore)

    starter_plan_path: Path | None = None
    starter_guide_path: Path | None = None
    if with_starter_guide or with_starter_plan_json:
        plan_path, guide_path = write_starter_artifacts(project_dir, force=force)
        if with_starter_plan_json:
            starter_plan_path = plan_path
            created_files.append(plan_path)
        else:
            plan_path.unlink(missing_ok=True)
        if with_starter_guide:
            starter_guide_path = guide_path
            created_files.append(guide_path)
        else:
            guide_path.unlink(missing_ok=True)

    return InitResult(
        project_dir=project_dir,
        created_files=created_files,
        created_dirs=created_dirs,
        starter_plan_path=starter_plan_path,
        starter_guide_path=starter_guide_path,
    )


def add_macro(
    project_dir: Path,
    *,
    macro_name: str,
    template: ProjectTemplate = "minimal",
    register: bool = True,
    force: bool = False,
) -> Path:
    """Create a new macro file under macros/ and optionally register in project.yaml."""

    project_dir = project_dir.expanduser().resolve()
    manifest = project_dir / "project.yaml"
    if not manifest.exists():
        raise FileNotFoundError(f"Missing project.yaml in {project_dir}")

    # Write macro file.
    macros_dir = project_dir / "macros"
    macros_dir.mkdir(parents=True, exist_ok=True)
    macro_path = macros_dir / f"{macro_name}.yaml"
    payload = _macro_template(macro_name, template)
    schema_path = project_dir / "schemas" / "vhk_macro.schema.json"
    modeline = "../schemas/vhk_macro.schema.json" if schema_path.exists() else None
    _write_if_allowed(macro_path, _yaml_with_modeline(modeline, payload), force=force)

    if register:
        doc = yaml.safe_load(manifest.read_text()) or {}
        if not isinstance(doc, dict):
            raise ValueError("project.yaml must be a mapping")
        macros = doc.get("macros") or {}
        if not isinstance(macros, dict):
            raise ValueError("project.yaml 'macros' must be a mapping when present")
        macros[str(macro_name)] = f"macros/{macro_name}.yaml"
        doc["macros"] = macros
        # Force overwrite: we are intentionally updating the manifest.
        _write_if_allowed(manifest, yaml.safe_dump(doc, sort_keys=False), force=True)

    return macro_path
