#!/usr/bin/env bash
# Generated by public_trace_capture_start_preflight_report.py.
# Source this only after the strict capture-start preflight succeeds.
export PUBLIC_TRACE_CAPTURE_START_STATUS=blocked_here
export PUBLIC_TRACE_CAPTURE_START_DECISION=do_not_start_capture
export MODEL_ID=TinyLlama/TinyLlama-1.1B-Chat-v1.0
export MODEL_REVISION=fe8a4ea1ffedaf415f4da2f062534de366a451e6
export PROMPT_MANIFEST=artifacts/prompts/REV0142_PUBLIC_TRACE_PROMPTS.txt
export CAPTURE_SNAPSHOT_SELECTION_CONTRACT=digest_verified_local_snapshot_path_v1
# No LOCAL_SNAPSHOT_DIR exported because capture is blocked or no digest-verified snapshot was selected.
