from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import re
from typing import Any

from vhk.core.models import Project
from vhk.project.dragonfly_pack import DragonflyEntry, _context_slug_from_payload, _slugify, build_dragonfly_entries


@dataclass(frozen=True)
class TalonPackManifest:
    project: str
    base_name: str
    python_path: Path
    talon_path: Path
    context_paths: tuple[Path, ...]
    readme_path: Path
    commands_path: Path
    commands: tuple[DragonflyEntry, ...]
    skipped: tuple[DragonflyEntry, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "project": self.project,
            "base_name": self.base_name,
            "python_path": str(self.python_path),
            "talon_path": str(self.talon_path),
            "context_paths": [str(path) for path in self.context_paths],
            "readme_path": str(self.readme_path),
            "commands_path": str(self.commands_path),
            "command_count": len(self.commands),
            "skipped_count": len(self.skipped),
            "commands": [item.to_dict() for item in self.commands],
            "skipped": [item.to_dict() for item in self.skipped],
        }



def default_talon_dir(project: Project) -> Path:
    return Path(project.root_dir) / "integrations" / "talon"



def default_talon_base_name(project: Project) -> str:
    return f"vhk_{_slugify(project.name)}"



def _python_header(*, project_name: str) -> str:
    return f'''"""Auto-generated Talon action module for {project_name}.

Generated by `vhk gen-talon-pack`.

This module intentionally shells back into VHK (`vhk run ...`) instead of
re-encoding the automation graph inside Talon. That keeps voice triggering as
an adapter layer rather than a second execution engine.
"""'''



def render_talon_python_module(
    project: Project,
    *,
    commands: list[DragonflyEntry],
    base_name: str | None = None,
) -> str:
    base = base_name or default_talon_base_name(project)
    command_map = {entry.command_id: list(entry.argv) for entry in commands}
    lines = [
        _python_header(project_name=project.name),
        "",
        "from __future__ import annotations",
        "",
        "import subprocess",
        "",
        "from talon import Module, app",
        "",
        "mod = Module()",
        f"BASE_NAME = {base!r}",
        f"PROJECT_NAME = {project.name!r}",
        f"COMMANDS = {json.dumps(command_map, ensure_ascii=False, indent=2)}",
        "",
        "",
        "@mod.action_class",
        "class Actions:",
        "    def vhk_run_generated_voice(command_id: str) -> None:",
        '        """Run a generated VHK voice command by its stable command id."""',
        "        command = COMMANDS.get(command_id)",
        "        if not command:",
        '            app.notify(title="VHK Talon pack", body=f"Unknown voice command: {command_id}")',
        "            return",
        "        subprocess.Popen(command)",
        "",
    ]
    return "\n".join(lines)



def _talon_context_lines(entry: DragonflyEntry) -> list[str]:
    lines = ["os: linux"]
    context = entry.voice_context or {}
    app_name = context.get("app")
    title = context.get("title")
    if app_name:
        lines.append(f"app: {app_name}")
    if title:
        escaped = re.escape(str(title))
        lines.append(f"title: /{escaped}/")
    lines.append("-")
    return lines



def render_talon_commands_file(
    project: Project,
    *,
    commands: list[DragonflyEntry],
    base_name: str | None = None,
    context_label: str | None = None,
) -> str:
    base = base_name or default_talon_base_name(project)
    lines = [
        f"# Auto-generated Talon commands for {project.name}.",
        "# Generated by `vhk gen-talon-pack`.",
        "# This file stays intentionally literal: spoken phrases call back into",
        "# a generated Python action which launches `vhk run ...`.",
        f"# Companion Python file: {base}.py",
        "",
    ]
    if context_label:
        lines.append(f"# Context: {context_label}")
    if commands and commands[0].voice_context:
        lines.extend(_talon_context_lines(commands[0]))
    else:
        lines.extend(["os: linux", "-"])
    if commands:
        for entry in commands:
            label = entry.label
            for phrase in entry.spoken_forms:
                lines.extend(
                    [
                        f"# {label}",
                        f"{phrase}:",
                        f"    user.vhk_run_generated_voice({json.dumps(entry.command_id, ensure_ascii=False)})",
                        "",
                    ]
                )
    else:
        lines.extend(
            [
                "# No command entries were generated.",
                "# Review the sibling commands.json / README.md for skipped/contextual items.",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"



def render_talon_readme(
    project: Project,
    *,
    manifest: TalonPackManifest,
) -> str:
    rel_python = manifest.python_path.name
    rel_talon = manifest.talon_path.name
    rel_commands = manifest.commands_path.name
    lines = [
        f"# Talon pack for {project.name}",
        "",
        "This pack is generated by `vhk gen-talon-pack`.",
        "",
        "What this is:",
        "- a Talon `.talon` command file with literal spoken phrases",
        "- optional extra `.talon` files when `voice_when` creates app/title-specific voice contexts",
        "- a small Python action module that launches `vhk run ...`",
        "- a JSON command ledger you can diff in Git",
        "",
        "What this is not:",
        "- a speech recognizer",
        "- a second automation runtime for VHK",
        "",
        "Files:",
        f"- `{rel_talon}` — Talon spoken-command file for global voice commands",
        f"- `{rel_python}` — Talon Python action module",
        f"- `{rel_commands}` — reviewable command/phrase manifest",
    ]
    for extra_path in manifest.context_paths:
        lines.append(f"- `{extra_path.name}` — Talon context-specific voice commands")
    lines.extend(
        [
            "",
            "Suggested workflow:",
            "1. Install/configure Talon for your environment.",
            "2. Copy these files into one folder under `~/.talon/user/`.",
            "3. Reload Talon scripts and try one of the spoken forms from the JSON ledger.",
            "",
            "Conservative defaults:",
            "- preset entries with interactive prompt overlays are skipped unless you regenerate with `--include-prompt-entries`",
            "- spoken forms are normalized to lowercase literal phrases",
            "- `voice_when` is only exported when it can be mapped honestly to Talon app/title context headers",
            "- VHK remains the only automation runner; Talon only launches it",
            "",
        ]
    )
    if manifest.skipped:
        lines.append("Skipped entries:")
        for item in manifest.skipped:
            label = item.label
            reason = item.skip_reason or "skipped"
            lines.append(f"- `{label}` — {reason}")
        lines.append("")
    lines.append("Commands:")
    for item in manifest.commands:
        target = item.macro if item.preset is None else f"{item.macro} --preset {item.preset}"
        context_suffix = f" (context: {item.voice_context_label})" if item.voice_context_label else ""
        lines.append(f"- `{', '.join(item.spoken_forms)}` → `vhk run ... {target}`{context_suffix}")
    lines.append("")
    return "\n".join(lines)



def _group_commands(commands: list[DragonflyEntry]) -> tuple[list[DragonflyEntry], list[tuple[str, list[DragonflyEntry]]]]:
    global_commands: list[DragonflyEntry] = []
    groups: dict[str, list[DragonflyEntry]] = {}
    labels: dict[str, str] = {}
    for entry in commands:
        if not entry.voice_context:
            global_commands.append(entry)
            continue
        key = json.dumps(entry.voice_context, sort_keys=True, ensure_ascii=False)
        groups.setdefault(key, []).append(entry)
        labels[key] = entry.voice_context_label or _context_slug_from_payload(entry.voice_context)
    ordered_contexts = sorted(groups.items(), key=lambda item: labels[item[0]])
    return global_commands, [(labels[key], items) for key, items in ordered_contexts]



def write_talon_pack(
    project: Project,
    *,
    out_dir: Path,
    command: str = "vhk",
    base_name: str | None = None,
    include_hidden: bool = False,
    include_presets: bool = True,
    include_prompt_entries: bool = False,
) -> TalonPackManifest:
    commands, skipped = build_dragonfly_entries(
        project,
        command=command,
        include_hidden=include_hidden,
        include_presets=include_presets,
        include_prompt_entries=include_prompt_entries,
        backend="talon",
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    resolved_base_name = base_name or default_talon_base_name(project)
    python_path = out_dir / f"{resolved_base_name}.py"
    talon_path = out_dir / f"{resolved_base_name}.talon"
    commands_path = out_dir / "commands.json"
    readme_path = out_dir / "README.md"

    global_commands, context_groups = _group_commands(commands)
    context_paths: list[Path] = []
    for label, items in context_groups:
        slug = _context_slug_from_payload(items[0].voice_context)
        path = out_dir / f"{resolved_base_name}__{slug}.talon"
        path.write_text(
            render_talon_commands_file(project, commands=items, base_name=resolved_base_name, context_label=label),
            encoding="utf-8",
        )
        context_paths.append(path)

    manifest = TalonPackManifest(
        project=project.name,
        base_name=resolved_base_name,
        python_path=python_path,
        talon_path=talon_path,
        context_paths=tuple(context_paths),
        readme_path=readme_path,
        commands_path=commands_path,
        commands=tuple(commands),
        skipped=tuple(skipped),
    )
    python_path.write_text(
        render_talon_python_module(project, commands=commands, base_name=resolved_base_name),
        encoding="utf-8",
    )
    talon_path.write_text(
        render_talon_commands_file(project, commands=global_commands, base_name=resolved_base_name),
        encoding="utf-8",
    )
    commands_path.write_text(json.dumps(manifest.to_dict(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    readme_path.write_text(render_talon_readme(project, manifest=manifest), encoding="utf-8")
    return manifest
