# Locality-sized core method contract specs.
# Aggregated by tools/core_method_contract_specs.py; consumed by the core method batch checker.

CORE_METHOD_CONTRACT_SPECS_PART_2 = [{'source_checker': 'check_public_hidden_state_contract.py',
  'doc_path': 'docs/10-method/public-hidden-state-and-reentry-abi.md',
  'doc_needles': ['# Public hidden state and re-entry ABI',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## State packet vs evidence packet vs check packet',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'state packet',
                  'evidence packet',
                  'check packet'],
  'surface_needles': {}},
 {'source_checker': 'check_rate_distortion_contract.py',
  'doc_path': 'docs/10-method/continuation-rate-distortion-and-prior-intrusion.md',
  'doc_needles': ['# Continuation rate–distortion and prior intrusion',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Rate budget vs distortion target vs mismatch budget',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'distortion target',
                  'mismatch budget',
                  'prior intrusion'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': ['If you claim a compression or '
                                                              'innovation improvement, name the '
                                                              'distortion target']}},
 {'source_checker': 'check_future_equivalence_contract.py',
  'doc_path': 'docs/10-method/future-equivalence-classes-and-causal-state-compression.md',
  'doc_needles': ['# Future-equivalence classes and causal-state compression',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Future-equivalence class vs test-sufficient packet vs local probe',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'future-equivalence classes',
                  'future family',
                  'lost distinction'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': ['future-equivalence class',
                                                              'lost distinction',
                                                              'compression was too aggressive']}},
 {'source_checker': 'check_intervention_equivalence_contract.py',
  'doc_path': 'docs/10-method/intervention-equivalence-and-causal-control-packets.md',
  'doc_needles': ['# Intervention-equivalence and causal-control packets',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Passive-future equivalence vs intervention-equivalence vs local probe',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'intervention family',
                  'branch divergence',
                  'causal-control packets'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': ['intervention-equivalence question',
                                                              'branch divergence',
                                                              'observationally safe']}},
 {'source_checker': 'check_memory_vs_reentry_contract.py',
  'doc_path': 'docs/10-method/memory-stores-vs-regime-reentry-packets.md',
  'doc_needles': ['# Memory stores vs regime-reentry packets',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Memory store vs regime-reentry packet vs check/admission packet',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'memory store',
                  'regime-reentry packet',
                  'check/admission packet'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': ['memory store',
                                                              'regime-reentry packet',
                                                              'check/admission object']}},
 {'source_checker': 'check_predictive_state_contract.py',
  'doc_path': 'docs/10-method/predictive-state-representations-and-test-sufficient-packets.md',
  'doc_needles': ['# Predictive state representations and test-sufficient packets',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Test-sufficient packet vs memory store vs predictive model vs local probe',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'test-sufficient packet',
                  'future tests',
                  'challenge probes'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': ['future tests',
                                                              'predictive sufficiency',
                                                              'challenge probes']}},
 {'source_checker': 'check_witness_set_contract.py',
  'doc_path': 'docs/10-method/witness-sets-boundary-panels-and-basin-support-vectors.md',
  'doc_needles': ['# Witness sets, boundary panels, and basin support vectors',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Witness set vs recap example vs challenge probe',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'witness set',
                  'boundary panel',
                  'drift signature'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': [{'any': ['witness set',
                                                                       'boundary panel']}]}},
 {'source_checker': 'check_identification_packet_contract.py',
  'doc_path': 'docs/10-method/dual-control-revisions-and-identification-packets.md',
  'doc_needles': ['# Dual-control revisions and identification packets',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Innovation packet vs identification packet vs sentinel panel vs hold packet',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'identification packet',
                  'observation sought',
                  'recover-resync'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': ['identification packet']}},
 {'source_checker': 'check_sentinel_panel_contract.py',
  'doc_path': 'docs/10-method/sentinel-panels-border-inputs-and-reopen-canaries.md',
  'doc_needles': ['# Sentinel panels, border inputs, and reopen canaries',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Sentinel panel vs witness panel vs challenge probe',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'sentinel panel',
                  'property monitored',
                  'expected deviation signature',
                  'recover-resync'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': [{'any': ['sentinel panel',
                                                                       'reopen canary']}]}},
 {'source_checker': 'check_hold_packet_contract.py',
  'doc_path': 'docs/10-method/hold-packets-abstention-and-epistemic-brakes.md',
  'doc_needles': ['# Hold packets, abstention, and epistemic brakes',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Hold packet vs quarantine vs demotion',
                  '## Brake postures',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'hold packet',
                  'unlock condition',
                  'recover-resync'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': [{'any': ['hold packet',
                                                                       'epistemic brake']}],
                      'docs/20-constitution/move-registry.md': ['MV-0013']}}]
