# Locality-sized core method contract specs.
# Aggregated by tools/core_method_contract_specs.py; consumed by the core method batch checker.

CORE_METHOD_CONTRACT_SPECS_PART_1 = [{'source_checker': 'check_regime_probe_contract.py',
  'doc_path': 'docs/10-method/stable-continuation-regimes-and-regime-probes.md',
  'doc_needles': ['# Stable continuation regimes and regime probes',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Counterpressure / disagreement',
                  '## Regime probes',
                  '## Transformer-facing implication',
                  'stable continuation regime',
                  'regime probe'],
  'surface_needles': {'docs/20-constitution/claim-registry.md': ['CL-0022'],
                      'docs/20-constitution/invariant-registry.md': ['INV-0020'],
                      'docs/20-constitution/open-question-registry.md': ['OQ-0022'],
                      'docs/50-promptcraft/prompt-pairs.md': ['discriminating probe or '
                                                              'countermodel']}},
 {'source_checker': 'check_timescale_lane_contract.py',
  'doc_path': 'docs/10-method/timescale-stratification-and-consolidation-lanes.md',
  'doc_needles': ['# Timescale stratification and consolidation lanes',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Fast lane vs medium lane vs slow lane',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'timescale',
                  'transfer rule',
                  'expire'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': [{'any': ['timescale stratification',
                                                                       'consolidation-lane']}]}},
 {'source_checker': 'check_phase_boundary_contract.py',
  'doc_path': 'docs/10-method/phase-boundaries-rollover-packets-and-event-cut-discipline.md',
  'doc_needles': ['# Phase boundaries, rollover packets, and event-cut discipline',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Phase boundary vs timescale lane vs innovation packet vs hold packet',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'phase boundary',
                  'rollover packet',
                  'persists',
                  'reset'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': [{'any': ['phase boundary',
                                                                       'rollover packet']}]}},
 {'source_checker': 'check_gauge_discipline_contract.py',
  'doc_path': 'docs/10-method/gauge-discipline-canonical-charts-and-invariant-claims.md',
  'doc_needles': ['# Gauge discipline, canonical charts, and invariant claims',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Invariant claim vs canonical chart vs metaphor',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'invariant claim',
                  'chart switch',
                  'coordinate-loaded',
                  'canonical chart'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': [{'any': ['chart switch',
                                                                       'chart-specific',
                                                                       'invariant claim']}]}},
 {'source_checker': 'check_loop_closure_contract.py',
  'doc_path': 'docs/10-method/loop-closure-commutator-probes-and-path-dependence.md',
  'doc_needles': ['# Loop closure, commutator probes, and path dependence',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Closure target vs commuting path vs expected non-commutation',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'loop-closure',
                  'commutator',
                  'closure target',
                  'closure error',
                  'path-dependent'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': [{'any': ['loop-closure',
                                                                       'commutator',
                                                                       'closure error']}]}},
 {'source_checker': 'check_continuation_margin_contract.py',
  'doc_path': 'docs/10-method/continuation-margins-guard-bands-and-perturbation-budgets.md',
  'doc_needles': ['# Continuation margins, guard bands, and perturbation budgets',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Continuation margin vs witness panel vs sentinel panel vs loop-closure probe',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'protected property',
                  'perturbation family',
                  'failure signature',
                  'guard band'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': [{'any': ['perturbation family',
                                                                       'guard band',
                                                                       'protected property']}]}},
 {'source_checker': 'check_control_authority_contract.py',
  'doc_path': 'docs/10-method/control-authority-effort-leakage-and-resistance.md',
  'doc_needles': ['# Control authority, steering effort, leakage, and endogenous resistance',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Control authority vs witness panel vs identification packet vs continuation '
                  'margin',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'actuator surface',
                  'target property',
                  'effort',
                  'leakage',
                  'endogenous resistance'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': [{'any': ['actuator surface',
                                                                       'target property',
                                                                       'endogenous-resistance']}]}},
 {'source_checker': 'check_balanced_archive_contract.py',
  'doc_path': 'docs/10-method/balanced-archive-reduction-dual-salience-and-minimal-realization.md',
  'doc_needles': ['# Balanced archive reduction, dual salience, and minimal realization',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Balanced reduction vs identification packet vs control-authority packet vs '
                  'timescale lane',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'observation role',
                  'control role',
                  'truncation consequence',
                  'dual salience'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': [{'any': ['observation role',
                                                                       'control role',
                                                                       'truncation '
                                                                       'consequence']}]}},
 {'source_checker': 'check_revision_gain_contract.py',
  'doc_path': 'docs/10-method/update-gain-surprise-gating-and-challenge-probes.md',
  'doc_needles': ['# Update gain, surprise gating, and challenge probes',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Trigger vs update gain vs challenge probe',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'update gain',
                  'challenge probe',
                  'recover-resync'],
  'surface_needles': {'docs/50-promptcraft/prompt-pairs.md': ['name the trigger, the update '
                                                              'gain']}},
 {'source_checker': 'check_belief_state_contract.py',
  'doc_path': 'docs/10-method/public-belief-state-under-partial-observability.md',
  'doc_needles': ['# Public belief state under partial observability',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'partial observability',
                  'public belief state'],
  'surface_needles': {}}]
