# Locality-sized segment of exact GPU witness contract specs.
# Aggregated by tools/gpu_witness_contract_specs.py; consumed by the batch checker.

GPU_WITNESS_CONTRACT_SPECS_PART_4 = [{'source_checker': 'check_gpu_replay_cross_observer_promotion_gate_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_promotion_gate_witness_contract',
             'doc_path': 'docs/10-method/gpu-replay-cross-observer-promotion-gate-witnesses-no-promotion-local-hardening-repeated-overflow-custody-boundary-authority-handoff-and-mixed-promotion.md',
             'doc_needles': ['# GPU replay cross-observer promotion-gate witnesses, no promotion, local hardening, '
                             'repeated bridge overflow, custody boundary, authority handoff, and mixed promotion',
                             'This is the compact successor surface for `OQ-0169`.',
                             '## Practice / observation',
                             '## External pressure from bridge keys, trace context, metric exemplars, placement '
                             'surfaces, and repeated missing-bridge cases',
                             '## Working synthesis',
                             '## No-promotion vs local-hardening vs repeated-missing-bridge vs custody-boundary vs '
                             'authority-handoff vs mixed promotion',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_promotion_gate_state`',
                             'no-promotion-gate',
                             'local-bridge-hardening-gate',
                             'repeated-missing-bridge-overflow',
                             'custody-boundary-overflow',
                             'authority-handoff-overflow',
                             'mixed-promotion-gate'],
             'runbook_ref': 'gpu-replay-cross-observer-promotion-gate-witnesses-no-promotion-local-hardening-repeated-overflow-custody-boundary-authority-handoff-and-mixed-promotion.md',
             'prompt_id': 'PP-0126',
             'prompt_needles': ['Use '
                                '`docs/10-method/gpu-replay-cross-observer-promotion-gate-witnesses-no-promotion-local-hardening-repeated-overflow-custody-boundary-authority-handoff-and-mixed-promotion.md`',
                                'no-promotion-gate, local-bridge-hardening-gate, repeated-missing-bridge-overflow, '
                                'custody-boundary-overflow, authority-handoff-overflow, or mixed-promotion-gate'],
             'claim_id': 'CL-0166',
             'oq_id': 'OQ-0169',
             'resolution_id': 'RS-0176',
             'trajectory_oq_id': 'OQ-0170',
             'qws_id': 'QWS-0251',
             'qws_label': 'cross-observer custody scope ledger / promotion board / telemetry custody treaty',
             'changelog_needles': ['gpu-replay-cross-observer-promotion-gate-witnesses-no-promotion-local-hardening-repeated-overflow-custody-boundary-authority-handoff-and-mixed-promotion.md',
                                   'check_gpu_replay_cross_observer_promotion_gate_witness_contract.py',
                                   'check_reentry_command_visibility_contract.py',
                                   'gpu_replay_cross_observer_promotion_gate_state'],
             'family': 'gpu_replay_cross_observer_promotion_gate_state',
             'allowed': ['no-promotion-gate',
                         'local-bridge-hardening-gate',
                         'repeated-missing-bridge-overflow',
                         'custody-boundary-overflow',
                         'authority-handoff-overflow',
                         'mixed-promotion-gate'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-replay-cross-observer-promotion-gate-witnesses-no-promotion-local-hardening-repeated-overflow-custody-boundary-authority-handoff-and-mixed-promotion.md'],
             'excluded': ['one-missing-bridge-means-treaty',
                          'richest-observer-gets-notary',
                          'dashboard-spike-promotes-escrow',
                          'trace-id-promotes-treaty',
                          'promotion-gate-ish']}},
 {'source_checker': 'check_gpu_replay_envelope_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_envelope_witness_contract',
             'doc_path': 'docs/10-method/gpu-replay-envelope-witnesses-captured-graph-stable-pool-and-locality-partition.md',
             'doc_needles': ['# GPU replay-envelope witnesses, captured graph, stable pool, and locality partition',
                             'This is the compact successor surface for `OQ-0164`.',
                             '## Practice / observation',
                             '## External pressure from CUDA graph update, graph node types, stream-ordered memory '
                             'pools, graph memory resources, and MPS locality partitioning',
                             '## Working synthesis',
                             '## Captured graph envelope vs stream-pool envelope vs locality-partition envelope vs '
                             'mixed GPU replay envelope',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_envelope_state`',
                             'captured-graph-envelope',
                             'stream-pool-envelope',
                             'locality-partition-envelope',
                             'mixed-gpu-replay-envelope'],
             'runbook_ref': 'gpu-replay-envelope-witnesses-captured-graph-stable-pool-and-locality-partition.md',
             'prompt_id': 'PP-0121',
             'prompt_needles': ['Use '
                                '`docs/10-method/gpu-replay-envelope-witnesses-captured-graph-stable-pool-and-locality-partition.md`',
                                'captured-graph-envelope, stream-pool-envelope, locality-partition-envelope, or '
                                'mixed-gpu-replay-envelope'],
             'claim_id': 'CL-0161',
             'oq_id': 'OQ-0164',
             'resolution_id': 'RS-0170',
             'trajectory_oq_id': 'OQ-0165',
             'qws_id': 'QWS-0246',
             'qws_label': 'graph escrow / replay-envelope notary / locality futures',
             'changelog_needles': ['gpu-replay-envelope-witnesses-captured-graph-stable-pool-and-locality-partition.md',
                                   'check_gpu_replay_envelope_witness_contract.py'],
             'family': 'gpu_replay_envelope_state',
             'allowed': ['captured-graph-envelope',
                         'stream-pool-envelope',
                         'locality-partition-envelope',
                         'mixed-gpu-replay-envelope'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-replay-envelope-witnesses-captured-graph-stable-pool-and-locality-partition.md'],
             'excluded': ['cuda-replay-means-same-envelope',
                          'graph-is-always-faster',
                          'same-output-same-envelope',
                          'gpu-replay-ish']}},
 {'source_checker': 'check_gpu_replay_observer_conflict_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_observer_conflict_witness_contract',
             'doc_path': 'docs/10-method/gpu-replay-observer-conflict-witnesses-scope-correlation-intrusion-authority-and-mixed-conflict.md',
             'doc_needles': ['# GPU replay observer-conflict witnesses, scope boundaries, correlation keys, intrusion '
                             'shifts, authority gaps, and mixed conflict',
                             'This is the compact successor surface for `OQ-0167`.',
                             '## Practice / observation',
                             '## External pressure from CUPTI graph correlation, Nsight graph/node trace scope, DCGM '
                             'exporter cluster metrics, and OpenTelemetry GPU metrics',
                             '## Working synthesis',
                             '## Scope-boundary vs correlation-key vs intrusion-shift vs authority-gap vs mixed '
                             'observer conflict',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_observer_conflict_state`',
                             'scope-boundary-conflict',
                             'correlation-key-conflict',
                             'intrusion-shift-conflict',
                             'authority-gap-conflict',
                             'mixed-observer-conflict'],
             'runbook_ref': 'gpu-replay-observer-conflict-witnesses-scope-correlation-intrusion-authority-and-mixed-conflict.md',
             'prompt_id': 'PP-0124',
             'prompt_needles': ['Use '
                                '`docs/10-method/gpu-replay-observer-conflict-witnesses-scope-correlation-intrusion-authority-and-mixed-conflict.md`',
                                'scope-boundary-conflict, correlation-key-conflict, intrusion-shift-conflict, '
                                'authority-gap-conflict, or mixed-observer-conflict'],
             'claim_id': 'CL-0164',
             'oq_id': 'OQ-0167',
             'resolution_id': 'RS-0173',
             'trajectory_oq_id': 'OQ-0168',
             'qws_id': 'QWS-0249',
             'qws_label': 'cross-observer span escrow / GPU telemetry treaty / correlation futures',
             'changelog_needles': ['gpu-replay-observer-conflict-witnesses-scope-correlation-intrusion-authority-and-mixed-conflict.md',
                                   'check_gpu_replay_observer_conflict_witness_contract.py',
                                   '_assert_unique_toolchain',
                                   'PYTHON ?= python -S'],
             'family': 'gpu_replay_observer_conflict_state',
             'allowed': ['scope-boundary-conflict',
                         'correlation-key-conflict',
                         'intrusion-shift-conflict',
                         'authority-gap-conflict',
                         'mixed-observer-conflict'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-replay-observer-conflict-witnesses-scope-correlation-intrusion-authority-and-mixed-conflict.md'],
             'excluded': ['one-observer-wins',
                          'profiler-overrules-runtime',
                          'metrics-overrule-lineage',
                          'correlation-id-is-truth',
                          'observer-conflict-ish']}},
 {'source_checker': 'check_gpu_replay_receipt_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_receipt_witness_contract',
             'doc_path': 'docs/10-method/gpu-replay-receipt-witnesses-capture-lineage-update-delta-resource-lifetime-and-locality-lease.md',
             'doc_needles': ['# GPU replay-receipt witnesses, capture lineage, update delta, resource lifetime, and '
                             'locality lease',
                             'This is the compact successor surface for `OQ-0165`.',
                             '## Practice / observation',
                             '## External pressure from CUDA graph updates, graph memory/user-object lifetime, '
                             'CUPTI/Nsight traces, and green-context locality',
                             '## Working synthesis',
                             '## Capture-lineage vs update-delta vs resource-lifetime vs locality-lease vs mixed GPU '
                             'replay receipt',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_receipt_state`',
                             'capture-lineage-receipt',
                             'update-delta-receipt',
                             'resource-lifetime-receipt',
                             'locality-lease-receipt',
                             'mixed-gpu-replay-receipt'],
             'runbook_ref': 'gpu-replay-receipt-witnesses-capture-lineage-update-delta-resource-lifetime-and-locality-lease.md',
             'prompt_id': 'PP-0122',
             'prompt_needles': ['Use '
                                '`docs/10-method/gpu-replay-receipt-witnesses-capture-lineage-update-delta-resource-lifetime-and-locality-lease.md`',
                                'capture-lineage-receipt, update-delta-receipt, resource-lifetime-receipt, '
                                'locality-lease-receipt, or mixed-gpu-replay-receipt'],
             'claim_id': 'CL-0162',
             'oq_id': 'OQ-0165',
             'resolution_id': 'RS-0171',
             'trajectory_oq_id': 'OQ-0166',
             'qws_id': 'QWS-0247',
             'qws_label': 'GPU replay flight recorder / trace escrow / locality lease market',
             'changelog_needles': ['gpu-replay-receipt-witnesses-capture-lineage-update-delta-resource-lifetime-and-locality-lease.md',
                                   'check_gpu_replay_receipt_witness_contract.py',
                                   'CONTRACT_PATTERN_GROUPS'],
             'family': 'gpu_replay_receipt_state',
             'allowed': ['capture-lineage-receipt',
                         'update-delta-receipt',
                         'resource-lifetime-receipt',
                         'locality-lease-receipt',
                         'mixed-gpu-replay-receipt'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-replay-receipt-witnesses-capture-lineage-update-delta-resource-lifetime-and-locality-lease.md'],
             'excluded': ['same-envelope-because-fast',
                          'trace-means-truth',
                          'notary-by-default',
                          'locality-ish',
                          'receipt-ish']}},
 {'source_checker': 'check_gpu_replay_trace_grade_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_trace_grade_witness_contract',
             'doc_path': 'docs/10-method/gpu-replay-trace-grade-witnesses-runtime-self-attestation-profiler-trace-external-observer-and-missing-receipt.md',
             'doc_needles': ['# GPU replay trace-grade witnesses, self-attestation, profiler trace, external observer, '
                             'and missing receipt',
                             'This is the compact successor surface for `OQ-0166`.',
                             '## Practice / observation',
                             '## External pressure from CUDA graph updates, CUPTI graph correlation, Nsight trace '
                             'scope, DCGM monitoring, and OpenTelemetry GPU metrics',
                             '## Working synthesis',
                             '## Runtime self-attested vs profiler-trace-backed vs external-observer-backed vs missing '
                             'trace receipt vs mixed GPU replay trace grade',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_trace_grade_state`',
                             'runtime-self-attested',
                             'profiler-trace-backed',
                             'external-observer-backed',
                             'missing-trace-receipt',
                             'mixed-gpu-replay-trace-grade'],
             'runbook_ref': 'gpu-replay-trace-grade-witnesses-runtime-self-attestation-profiler-trace-external-observer-and-missing-receipt.md',
             'prompt_id': 'PP-0123',
             'prompt_needles': ['Use '
                                '`docs/10-method/gpu-replay-trace-grade-witnesses-runtime-self-attestation-profiler-trace-external-observer-and-missing-receipt.md`',
                                'runtime-self-attested, profiler-trace-backed, external-observer-backed, '
                                'missing-trace-receipt, or mixed-gpu-replay-trace-grade'],
             'claim_id': 'CL-0163',
             'oq_id': 'OQ-0166',
             'resolution_id': 'RS-0172',
             'trajectory_oq_id': 'OQ-0167',
             'qws_id': 'QWS-0248',
             'qws_label': 'multi-observer trace tribunal / telemetry mirror ledger / replay evidence custody mesh',
             'changelog_needles': ['gpu-replay-trace-grade-witnesses-runtime-self-attestation-profiler-trace-external-observer-and-missing-receipt.md',
                                   'check_gpu_replay_trace_grade_witness_contract.py',
                                   '_stable_unique'],
             'family': 'gpu_replay_trace_grade_state',
             'allowed': ['runtime-self-attested',
                         'profiler-trace-backed',
                         'external-observer-backed',
                         'missing-trace-receipt',
                         'mixed-gpu-replay-trace-grade'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-replay-trace-grade-witnesses-runtime-self-attestation-profiler-trace-external-observer-and-missing-receipt.md'],
             'excluded': ['telemetry-means-truth',
                          'profiler-screenshot-is-proof',
                          'observer-metric-is-lineage',
                          'missing-trace-is-failure',
                          'trace-grade-ish']}},
 {'source_checker': 'check_gpu_wvf_0094_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_drift_arbitration_retirement_governance_threshold_witness_contract',
             'doc_path': 'docs/10-method/gpu-rpra-drift-retirement-threshold-witnesses.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry '
                             'reopened-residue post-closeout portability-drift conflict-arbitration retirement '
                             'governance-threshold witnesses, no standing governance, repeated failure, history loss, '
                             'overbinding, authority split, sunset breach, and mixed escalation',
                             'This is the compact successor surface for `OQ-0189`.',
                             '## Practice / observation',
                             '## External pressure from audit retention, transparency history, cleanup ownership, '
                             'admission scope, rule sunsets, and sampling windows',
                             '## Working synthesis',
                             '## No standing governance vs repeated failure vs history loss vs history overbinding vs '
                             'authority split vs sunset breach vs mixed escalation',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_threshold_state`',
                             'no-standing-reopen-drift-retirement-governance',
                             'repeated-closeout-failure-reopen-drift-governance',
                             'history-loss-reopen-drift-retirement-governance',
                             'history-overbinding-reopen-drift-retirement-governance',
                             'authority-split-reopen-drift-retirement-governance',
                             'sunset-breach-reopen-drift-retirement-governance',
                             'mixed-reopen-drift-retirement-governance-escalation'],
             'runbook_ref': 'gpu-rpra-drift-retirement-threshold-witnesses.md',
             'prompt_id': 'PP-0147',
             'prompt_needles': ['Use `docs/10-method/gpu-rpra-drift-retirement-threshold-witnesses.md`',
                                'no-standing-reopen-drift-retirement-governance, '
                                'repeated-closeout-failure-reopen-drift-governance, '
                                'history-loss-reopen-drift-retirement-governance, '
                                'history-overbinding-reopen-drift-retirement-governance, '
                                'authority-split-reopen-drift-retirement-governance, '
                                'sunset-breach-reopen-drift-retirement-governance, or '
                                'mixed-reopen-drift-retirement-governance-escalation'],
             'claim_id': 'CL-0187',
             'oq_id': 'OQ-0189',
             'resolution_id': 'RS-0197',
             'trajectory_oq_id': 'OQ-0190',
             'qws_id': 'QWS-0272',
             'qws_label': 'standing residue-drift retirement governance scope / revival-history custody board / '
                          'drift-retirement operator court',
             'changelog_needles': ['gpu-rpra-drift-retirement-threshold-witnesses.md',
                                   'check_gpu_wvf_0094_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_threshold_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_threshold_state',
             'allowed': ['no-standing-reopen-drift-retirement-governance',
                         'repeated-closeout-failure-reopen-drift-governance',
                         'history-loss-reopen-drift-retirement-governance',
                         'history-overbinding-reopen-drift-retirement-governance',
                         'authority-split-reopen-drift-retirement-governance',
                         'sunset-breach-reopen-drift-retirement-governance',
                         'mixed-reopen-drift-retirement-governance-escalation'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-rpra-drift-retirement-threshold-witnesses.md'],
             'excluded': ['drift-retirement-court-by-default',
                          'revival-history-vault-by-use',
                          'arbitration-closeout-board-by-citation',
                          'standing-governance-after-one-failure',
                          'retirement-governance-ish']}},
 {'source_checker': 'check_gpu_wvf_0095_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_drift_arbitration_retirement_governance_scope_witness_contract',
             'doc_path': 'docs/10-method/gpu-rpra-drift-retirement-scope-witnesses.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry '
                             'reopened-residue post-closeout portability-drift conflict-arbitration retirement '
                             'governance-scope witnesses, packet-local, carrier-bound, authority-limited, '
                             'nonbinding-history, retirement-window, and mixed scope',
                             'This is the compact successor surface for `OQ-0190`.',
                             '## Practice / observation',
                             '## External pressure from audit scope, owner boundaries, admission bindings, rule '
                             'windows, sampling carriers, and transparency history',
                             '## Working synthesis',
                             '## Packet-local vs carrier-bound vs authority-limited vs nonbinding-history vs '
                             'retirement-window vs mixed governance scope',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_scope_state`',
                             'packet-local-reopen-drift-governance-scope',
                             'carrier-bound-reopen-drift-governance-scope',
                             'authority-limited-reopen-drift-governance-scope',
                             'nonbinding-history-reopen-drift-governance-scope',
                             'retirement-window-reopen-drift-governance-scope',
                             'mixed-reopen-drift-governance-scope'],
             'runbook_ref': 'gpu-rpra-drift-retirement-scope-witnesses.md',
             'prompt_id': 'PP-0148',
             'prompt_needles': ['Use `docs/10-method/gpu-rpra-drift-retirement-scope-witnesses.md`',
                                'packet-local-reopen-drift-governance-scope, '
                                'carrier-bound-reopen-drift-governance-scope, '
                                'authority-limited-reopen-drift-governance-scope, '
                                'nonbinding-history-reopen-drift-governance-scope, '
                                'retirement-window-reopen-drift-governance-scope, or '
                                'mixed-reopen-drift-governance-scope'],
             'claim_id': 'CL-0188',
             'oq_id': 'OQ-0190',
             'resolution_id': 'RS-0198',
             'trajectory_oq_id': 'OQ-0191',
             'qws_id': 'QWS-0273',
             'qws_label': 'global residue-drift retirement governance / revival-history custody board / '
                          'drift-retirement operator court',
             'changelog_needles': ['gpu-rpra-drift-retirement-scope-witnesses.md',
                                   'check_gpu_wvf_0095_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_scope_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_scope_state',
             'allowed': ['packet-local-reopen-drift-governance-scope',
                         'carrier-bound-reopen-drift-governance-scope',
                         'authority-limited-reopen-drift-governance-scope',
                         'nonbinding-history-reopen-drift-governance-scope',
                         'retirement-window-reopen-drift-governance-scope',
                         'mixed-reopen-drift-governance-scope'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-rpra-drift-retirement-scope-witnesses.md'],
             'excluded': ['global-drift-retirement-court',
                          'revival-history-custody-by-scope',
                          'operator-authority-by-overflow',
                          'nonbinding-history-means-governance',
                          'drift-governance-scope-ish']}},
 {'source_checker': 'check_gpu_wvf_0106_contract.py',
  'kwargs': {'kind': 'gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_witness_contract',
             'doc_path': 'docs/10-method/wvf-0106.md',
             'doc_needles': ['# GPU replay reopened-residue drift governance-retirement portability-drift '
                             'conflict-arbitration retirement governance-retirement portability-drift '
                             'conflict-arbitration witnesses, no arbitration, local join, current carrier precedence, '
                             'revocation precedence, exit-proof precedence, successor-route precedence, and mixed '
                             'arbitration',
                             'This is the compact successor surface for `OQ-0201`.',
                             '## Practice / observation',
                             '## External pressure from admission rebinding, audit retention, tombstones, trace '
                             'carriers, transparency revocation, finalizer release, and policy windows',
                             '## Working synthesis',
                             '## No arbitration vs local join vs current carrier vs revocation vs exit proof vs '
                             'successor route vs mixed arbitration',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_state`',
                             'no-arbitration-needed-post-arbitration-governance-retirement-drift-conflict',
                             'local-join-post-arbitration-governance-retirement-drift-conflict',
                             'current-carrier-precedence-post-arbitration-governance-retirement-drift',
                             'revocation-precedence-post-arbitration-governance-retirement-drift',
                             'exit-proof-precedence-post-arbitration-governance-retirement-drift',
                             'successor-route-precedence-post-arbitration-governance-retirement-drift',
                             'mixed-post-arbitration-governance-retirement-drift-arbitration'],
             'runbook_ref': 'wvf-0106.md',
             'prompt_id': 'PP-0159',
             'prompt_needles': ['Use `docs/10-method/wvf-0106.md`',
                                'no-arbitration-needed-post-arbitration-governance-retirement-drift-conflict, '
                                'local-join-post-arbitration-governance-retirement-drift-conflict, '
                                'current-carrier-precedence-post-arbitration-governance-retirement-drift, '
                                'revocation-precedence-post-arbitration-governance-retirement-drift, '
                                'exit-proof-precedence-post-arbitration-governance-retirement-drift, '
                                'successor-route-precedence-post-arbitration-governance-retirement-drift, or '
                                'mixed-post-arbitration-governance-retirement-drift-arbitration'],
             'claim_id': 'CL-0199',
             'oq_id': 'OQ-0201',
             'resolution_id': 'RS-0209',
             'trajectory_oq_id': 'OQ-0202',
             'qws_id': 'QWS-0284',
             'qws_label': 'post-arbitration-governance-retirement arbitration-retirement court / exit-proof priority '
                          'ledger / freshness closeout board',
             'changelog_needles': ['wvf-0106.md',
                                   'check_gpu_wvf_0106_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_state',
             'allowed': ['no-arbitration-needed-post-arbitration-governance-retirement-drift-conflict',
                         'local-join-post-arbitration-governance-retirement-drift-conflict',
                         'current-carrier-precedence-post-arbitration-governance-retirement-drift',
                         'revocation-precedence-post-arbitration-governance-retirement-drift',
                         'exit-proof-precedence-post-arbitration-governance-retirement-drift',
                         'successor-route-precedence-post-arbitration-governance-retirement-drift',
                         'mixed-post-arbitration-governance-retirement-drift-arbitration'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0106.md'],
             'excluded': ['post-arbitration-governance-retirement-drift-arbitration-court',
                          'exit-proof-priority-ladder-by-default',
                          'carrier-freshness-tribunal',
                          'revoked-post-arbitration-governance-retirement-lesson-reanimated',
                          'post-arbitration-governance-retirement-drift-arbitration-ish']}},
 {'source_checker': 'check_gpu_wvf_0107_contract.py',
  'kwargs': {'kind': 'gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_witness_contract',
             'doc_path': 'docs/10-method/pa-governance-retirement-portability-drift-conflict-arbitration-retirement-witnesses-settled-handoff-expiry-authority-sunset-quarantine-mixed.md',
             'doc_needles': ['# GPU replay reopened-residue drift governance-retirement portability-drift '
                             'conflict-arbitration retirement governance-retirement portability-drift '
                             'conflict-arbitration-retirement witnesses, settled arbitration, joined handoff, carrier '
                             'expiry, authority return, priority sunset, residue quarantine, and mixed retirement',
                             'This is the compact successor surface for `OQ-0202`.',
                             '## Practice / observation',
                             '## External pressure from cleanup completion, audit retention, carrier expiry, authority '
                             'return, rule sunsets, sampling windows, and transparency history',
                             '## Working synthesis',
                             '## Settled arbitration vs joined handoff vs carrier expiry vs authority return vs '
                             'priority sunset vs residue quarantine vs mixed retirement',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_state`',
                             'settled-post-arbitration-governance-retirement-drift-arbitration-retirement',
                             'joined-route-handoff-post-arbitration-governance-retirement-drift-retirement',
                             'carrier-expiry-post-arbitration-governance-retirement-drift-arbitration-retirement',
                             'authority-return-post-arbitration-governance-retirement-drift-arbitration-retirement',
                             'priority-sunset-post-arbitration-governance-retirement-drift-arbitration-retirement',
                             'residue-quarantine-post-arbitration-governance-retirement-drift-arbitration-retirement',
                             'mixed-post-arbitration-governance-retirement-drift-arbitration-retirement'],
             'runbook_ref': 'pa-governance-retirement-portability-drift-conflict-arbitration-retirement-witnesses-settled-handoff-expiry-authority-sunset-quarantine-mixed.md',
             'prompt_id': 'PP-0160',
             'prompt_needles': ['Use '
                                '`docs/10-method/pa-governance-retirement-portability-drift-conflict-arbitration-retirement-witnesses-settled-handoff-expiry-authority-sunset-quarantine-mixed.md`',
                                'settled-post-arbitration-governance-retirement-drift-arbitration-retirement, '
                                'joined-route-handoff-post-arbitration-governance-retirement-drift-retirement, '
                                'carrier-expiry-post-arbitration-governance-retirement-drift-arbitration-retirement, '
                                'authority-return-post-arbitration-governance-retirement-drift-arbitration-retirement, '
                                'priority-sunset-post-arbitration-governance-retirement-drift-arbitration-retirement, '
                                'residue-quarantine-post-arbitration-governance-retirement-drift-arbitration-retirement, '
                                'or mixed-post-arbitration-governance-retirement-drift-arbitration-retirement'],
             'claim_id': 'CL-0200',
             'oq_id': 'OQ-0202',
             'resolution_id': 'RS-0210',
             'trajectory_oq_id': 'OQ-0203',
             'qws_id': 'QWS-0285',
             'qws_label': 'post-arbitration-governance-retirement arbitration-retirement governance threshold / '
                          'exit-proof closeout history vault / successor-route closeout board',
             'changelog_needles': ['pa-governance-retirement-portability-drift-conflict-arbitration-retirement-witnesses-settled-handoff-expiry-authority-sunset-quarantine-mixed.md',
                                   'check_gpu_wvf_0107_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_state',
             'allowed': ['settled-post-arbitration-governance-retirement-drift-arbitration-retirement',
                         'joined-route-handoff-post-arbitration-governance-retirement-drift-retirement',
                         'carrier-expiry-post-arbitration-governance-retirement-drift-arbitration-retirement',
                         'authority-return-post-arbitration-governance-retirement-drift-arbitration-retirement',
                         'priority-sunset-post-arbitration-governance-retirement-drift-arbitration-retirement',
                         'residue-quarantine-post-arbitration-governance-retirement-drift-arbitration-retirement',
                         'mixed-post-arbitration-governance-retirement-drift-arbitration-retirement'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/pa-governance-retirement-portability-drift-conflict-arbitration-retirement-witnesses-settled-handoff-expiry-authority-sunset-quarantine-mixed.md'],
             'excluded': ['post-arbitration-governance-retirement-arbitration-retirement-court',
                          'exit-proof-priority-ledger-by-default',
                          'freshness-closeout-board',
                          'winner-persists-after-post-arbitration-governance-retirement',
                          'post-arbitration-governance-retirement-arbitration-retirement-ish']}},
 {'source_checker': 'check_gpu_wvf_0117_contract.py',
  'kwargs': {'kind': 'gpu_pa_governance_retirement_threshold_scope_retirement_history_portability_currentness_closeout_history_portability_expiry_history_portability_closeout_witness_contract',
             'doc_path': 'docs/10-method/wvf-0117.md',
             'doc_needles': ['# GPU replay reopened-residue post-arbitration-governance-retirement threshold-scope '
                             'retirement-history portability-currentness closeout-history portability-expiry-history '
                             'portability closeout witnesses, closed, tombstone-pruned, warning-sunset, '
                             'successor-handoff, quarantine-expired, redacted-freeze, and mixed',
                             'This is the compact successor surface for `OQ-0212`.',
                             '## Governed exact-token family',
                             '## Token semantics',
                             '## Closeout rule',
                             '## Template-placeholder closure guard',
                             '## Self-sufficiency tail alignment guard',
                             '## Fail-closed rule',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_governance_scope_retirement_history_portability_currentness_closeout_history_portability_expiry_history_portability_closeout_state`',
                             '`closed-transported-closeout-expiry-record-travel`',
                             '`tombstone-pruned-transported-closeout-expiry-record-travel`',
                             '`warning-sunset-transported-closeout-expiry-record-travel`',
                             '`successor-handoff-transported-closeout-expiry-record-travel`',
                             '`quarantine-expired-transported-closeout-expiry-record-travel`',
                             '`redacted-freeze-transported-closeout-expiry-record-travel`',
                             '`mixed-transported-closeout-expiry-record-travel-closeout`',
                             '`tombstone-registry-board`',
                             '`expiry-record-closeout-court`',
                             '`carrier-resurrection-archive`',
                             '`permanent-expiry-tombstone-ledger`',
                             '`closed-tombstone-authority-by-default`',
                             'A transported closeout expiry-record travel record closes by ending its active travel '
                             'role'],
             'runbook_ref': 'wvf-0117.md',
             'prompt_id': 'PP-0170',
             'prompt_needles': ['Use `docs/10-method/wvf-0117.md`',
                                'closed-transported-closeout-expiry-record-travel, '
                                'tombstone-pruned-transported-closeout-expiry-record-travel, '
                                'warning-sunset-transported-closeout-expiry-record-travel, '
                                'successor-handoff-transported-closeout-expiry-record-travel, '
                                'quarantine-expired-transported-closeout-expiry-record-travel, '
                                'redacted-freeze-transported-closeout-expiry-record-travel, or '
                                'mixed-transported-closeout-expiry-record-travel-closeout',
                                'Do not let transported closeout expiry-record travel closeout become a tombstone '
                                'registry board, expiry-record closeout court, carrier-resurrection archive, permanent '
                                'expiry tombstone ledger, or closed tombstone authority by default.'],
             'claim_id': 'CL-0210',
             'oq_id': 'OQ-0212',
             'resolution_id': 'RS-0220',
             'trajectory_oq_id': 'OQ-0213',
             'qws_id': 'QWS-0295',
             'qws_label': 'tombstone registry board / expiry-record closeout court / carrier-resurrection archive',
             'changelog_needles': ['wvf-0117.md',
                                   'check_gpu_wvf_0117_contract.py',
                                   'check_template_placeholder_closure.py',
                                   'check_self_sufficiency_tail_alignment.py'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_governance_scope_retirement_history_portability_currentness_closeout_history_portability_expiry_history_portability_closeout_state',
             'allowed': ['closed-transported-closeout-expiry-record-travel',
                         'tombstone-pruned-transported-closeout-expiry-record-travel',
                         'warning-sunset-transported-closeout-expiry-record-travel',
                         'successor-handoff-transported-closeout-expiry-record-travel',
                         'quarantine-expired-transported-closeout-expiry-record-travel',
                         'redacted-freeze-transported-closeout-expiry-record-travel',
                         'mixed-transported-closeout-expiry-record-travel-closeout'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0117.md'],
             'excluded': ['tombstone-registry-board',
                          'expiry-record-closeout-court',
                          'carrier-resurrection-archive',
                          'permanent-expiry-tombstone-ledger',
                          'closed-tombstone-authority-by-default']}},
 {'source_checker': 'check_gpu_wvf_0118_contract.py',
  'kwargs': {'kind': 'gpu_pa_governance_retirement_threshold_scope_retirement_history_portability_currentness_closeout_history_portability_expiry_history_portability_closeout_history_portability_witness_contract',
             'doc_path': 'docs/10-method/pa-closeout-history-portability-travel-witnesses.md',
             'doc_needles': ['# GPU replay reopened-residue post-arbitration-governance-retirement threshold-scope '
                             'retirement-history portability-currentness closeout-history portability-expiry-history '
                             'portability closeout-history portability witnesses, nonportable, audit-reference, '
                             'warning-only, successor-context, redacted-summary, quarantine-reference, and mixed',
                             'This is the compact successor surface for `OQ-0213`.',
                             '## Governed exact-token family',
                             '## Token semantics',
                             '## Portability rule',
                             '## Current witness receipt-slot guard',
                             '## Fail-closed rule',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_governance_scope_retirement_history_portability_currentness_closeout_history_portability_expiry_history_portability_closeout_history_portability_state`',
                             '`nonportable-transported-closeout-expiry-record-closeout-history`',
                             '`audit-reference-transported-closeout-expiry-record-closeout-history`',
                             '`warning-only-transported-closeout-expiry-record-closeout-history`',
                             '`successor-context-transported-closeout-expiry-record-closeout-history`',
                             '`redacted-summary-transported-closeout-expiry-record-closeout-history`',
                             '`quarantine-reference-transported-closeout-expiry-record-closeout-history`',
                             '`mixed-transported-closeout-expiry-record-closeout-history-portability`',
                             '`closed-tombstone-reopen-board`',
                             '`tombstone-history-registry`',
                             '`carrier-resurrection-by-closeout-history`',
                             '`portable-closeout-history-authority-by-default`',
                             '`expiry-record-closeout-precedent-court`',
                             'A transported closeout expiry-record closeout-history record travels only as nonbinding '
                             'history'],
             'runbook_ref': 'pa-closeout-history-portability-travel-witnesses.md',
             'prompt_id': 'PP-0171',
             'prompt_needles': ['Use `docs/10-method/pa-closeout-history-portability-travel-witnesses.md`',
                                'nonportable-transported-closeout-expiry-record-closeout-history, '
                                'audit-reference-transported-closeout-expiry-record-closeout-history, '
                                'warning-only-transported-closeout-expiry-record-closeout-history, '
                                'successor-context-transported-closeout-expiry-record-closeout-history, '
                                'redacted-summary-transported-closeout-expiry-record-closeout-history, '
                                'quarantine-reference-transported-closeout-expiry-record-closeout-history, or '
                                'mixed-transported-closeout-expiry-record-closeout-history-portability',
                                'Do not let transported closeout expiry-record closeout-history portability become a '
                                'closed-tombstone reopen board, tombstone-history registry, carrier resurrection by '
                                'closeout history, portable closeout-history authority by default, or expiry-record '
                                'closeout precedent court.'],
             'claim_id': 'CL-0211',
             'oq_id': 'OQ-0213',
             'resolution_id': 'RS-0221',
             'trajectory_oq_id': 'OQ-0214',
             'qws_id': 'QWS-0296',
             'qws_label': 'closed-tombstone reopen board / tombstone-history registry / carrier resurrection by '
                          'closeout history',
             'changelog_needles': ['pa-closeout-history-portability-travel-witnesses.md',
                                   'check_gpu_wvf_0118_contract.py',
                                   'check_current_witness_receipt_slot.py'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_governance_scope_retirement_history_portability_currentness_closeout_history_portability_expiry_history_portability_closeout_history_portability_state',
             'allowed': ['nonportable-transported-closeout-expiry-record-closeout-history',
                         'audit-reference-transported-closeout-expiry-record-closeout-history',
                         'warning-only-transported-closeout-expiry-record-closeout-history',
                         'successor-context-transported-closeout-expiry-record-closeout-history',
                         'redacted-summary-transported-closeout-expiry-record-closeout-history',
                         'quarantine-reference-transported-closeout-expiry-record-closeout-history',
                         'mixed-transported-closeout-expiry-record-closeout-history-portability'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/pa-closeout-history-portability-travel-witnesses.md'],
             'excluded': ['closed-tombstone-reopen-board',
                          'tombstone-history-registry',
                          'carrier-resurrection-by-closeout-history',
                          'portable-closeout-history-authority-by-default',
                          'expiry-record-closeout-precedent-court']}},
 {'source_checker': 'check_gpu_wvf_0119_contract.py',
  'kwargs': {'kind': 'gpu_pa_governance_retirement_threshold_scope_retirement_history_portability_currentness_closeout_history_portability_expiry_history_portability_closeout_history_portability_expiry_witness_contract',
             'doc_path': 'docs/10-method/pa-closeout-history-portability-expiry-state-witnesses.md',
             'doc_needles': ['# GPU replay reopened-residue post-arbitration-governance-retirement threshold-scope '
                             'retirement-history portability-currentness closeout-history portability-expiry-history '
                             'portability closeout-history portability-expiry witnesses, unexpired, horizon-expired, '
                             'use-exhausted, successor-superseded, source-revoked, quarantine-expired, and mixed',
                             'This is the compact successor surface for `OQ-0214`.',
                             '## Governed exact-token family',
                             '## Token semantics',
                             '## Expiry rule',
                             '## Archive-index table-shape guard',
                             '## Fail-closed rule',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_governance_scope_retirement_history_portability_currentness_closeout_history_portability_expiry_history_portability_closeout_history_portability_expiry_state`',
                             '`unexpired-transported-closeout-expiry-record-closeout-history-portability`',
                             '`horizon-expired-transported-closeout-expiry-record-closeout-history-portability`',
                             '`use-exhausted-transported-closeout-expiry-record-closeout-history-portability`',
                             '`successor-superseded-transported-closeout-expiry-record-closeout-history-portability`',
                             '`source-revoked-transported-closeout-expiry-record-closeout-history-portability`',
                             '`quarantine-expired-transported-closeout-expiry-record-closeout-history-portability`',
                             '`mixed-transported-closeout-expiry-record-closeout-history-portability-expiry`',
                             '`tombstone-history-review-layer`',
                             '`portable-closeout-history-expiry-court`',
                             '`closed-tombstone-revalidation-board`',
                             '`carrier-renewal-by-expiry-review`',
                             '`nonexpiring-closeout-history-registry`',
                             'Expiry preserves source inspectability while ending ordinary carry'],
             'runbook_ref': 'pa-closeout-history-portability-expiry-state-witnesses.md',
             'prompt_id': 'PP-0172',
             'prompt_needles': ['Use `docs/10-method/pa-closeout-history-portability-expiry-state-witnesses.md`',
                                'unexpired-transported-closeout-expiry-record-closeout-history-portability, '
                                'horizon-expired-transported-closeout-expiry-record-closeout-history-portability, '
                                'use-exhausted-transported-closeout-expiry-record-closeout-history-portability, '
                                'successor-superseded-transported-closeout-expiry-record-closeout-history-portability, '
                                'source-revoked-transported-closeout-expiry-record-closeout-history-portability, '
                                'quarantine-expired-transported-closeout-expiry-record-closeout-history-portability, '
                                'or mixed-transported-closeout-expiry-record-closeout-history-portability-expiry',
                                'Do not let transported closeout expiry-record closeout-history portability expiry '
                                'become a tombstone-history review layer, portable closeout-history expiry court, '
                                'closed-tombstone revalidation board, carrier-renewal by expiry review, or nonexpiring '
                                'closeout-history registry.'],
             'claim_id': 'CL-0212',
             'oq_id': 'OQ-0214',
             'resolution_id': 'RS-0222',
             'trajectory_oq_id': 'OQ-0215',
             'qws_id': 'QWS-0297',
             'qws_label': 'tombstone-history review layer / portable closeout-history expiry court / carrier-renewal '
                          'by expiry review',
             'changelog_needles': ['pa-closeout-history-portability-expiry-state-witnesses.md',
                                   'check_gpu_wvf_0119_contract.py',
                                   'check_archive_index_table_shape.py'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_governance_scope_retirement_history_portability_currentness_closeout_history_portability_expiry_history_portability_closeout_history_portability_expiry_state',
             'allowed': ['unexpired-transported-closeout-expiry-record-closeout-history-portability',
                         'horizon-expired-transported-closeout-expiry-record-closeout-history-portability',
                         'use-exhausted-transported-closeout-expiry-record-closeout-history-portability',
                         'successor-superseded-transported-closeout-expiry-record-closeout-history-portability',
                         'source-revoked-transported-closeout-expiry-record-closeout-history-portability',
                         'quarantine-expired-transported-closeout-expiry-record-closeout-history-portability',
                         'mixed-transported-closeout-expiry-record-closeout-history-portability-expiry'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/pa-closeout-history-portability-expiry-state-witnesses.md'],
             'excluded': ['tombstone-history-review-layer',
                          'portable-closeout-history-expiry-court',
                          'closed-tombstone-revalidation-board',
                          'carrier-renewal-by-expiry-review',
                          'nonexpiring-closeout-history-registry']}}]
