# Locality-sized segment of exact GPU witness contract specs.
# Aggregated by tools/gpu_witness_contract_specs.py; consumed by the batch checker.

GPU_WITNESS_CONTRACT_SPECS_PART_3 = [{'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_closeout_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_closeout_witness_contract',
             'doc_path': 'docs/10-method/wvf-0089.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry '
                             'reopened-residue closeout witnesses, settled reopen, audit handoff, carrier expiry, '
                             'tombstone freeze, authority return, and mixed closeout',
                             'This is the compact successor surface for `OQ-0184`.',
                             '## Practice / observation',
                             '## External pressure from TTL cleanup, audit handoff, finalizer release, tombstone '
                             'freeze, rule staleness, sampling carriers, and transparency history',
                             '## Working synthesis',
                             '## Settled reopen vs audit handoff vs carrier expiry vs tombstone freeze vs authority '
                             'return vs mixed reopened-residue closeout',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_closeout_state`',
                             'settled-reopen-closeout',
                             'audit-handoff-reopen-closeout',
                             'carrier-expiry-reopen-closeout',
                             'tombstone-freeze-reopen-closeout',
                             'authority-return-reopen-closeout',
                             'mixed-reopened-residue-closeout'],
             'runbook_ref': 'wvf-0089.md',
             'prompt_id': 'PP-0142',
             'prompt_needles': ['Use `docs/10-method/wvf-0089.md`',
                                'settled-reopen-closeout, audit-handoff-reopen-closeout, '
                                'carrier-expiry-reopen-closeout, tombstone-freeze-reopen-closeout, '
                                'authority-return-reopen-closeout, or mixed-reopened-residue-closeout'],
             'claim_id': 'CL-0182',
             'oq_id': 'OQ-0184',
             'resolution_id': 'RS-0192',
             'trajectory_oq_id': 'OQ-0185',
             'qws_id': 'QWS-0267',
             'qws_label': 'reopened-residue closeout court / permanent revival ledger / deletion-closeout board',
             'changelog_needles': ['wvf-0089.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_closeout_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_closeout_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_closeout_state',
             'allowed': ['settled-reopen-closeout',
                         'audit-handoff-reopen-closeout',
                         'carrier-expiry-reopen-closeout',
                         'tombstone-freeze-reopen-closeout',
                         'authority-return-reopen-closeout',
                         'mixed-reopened-residue-closeout'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0089.md'],
             'excluded': ['permanent-reopen-by-closeout',
                          'revival-ledger-by-shrinkback',
                          'audit-handoff-means-authority',
                          'tombstone-freeze-means-deletion-court',
                          'reopened-residue-closeout-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_drift_arbitration_retirement_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_drift_arbitration_retirement_witness_contract',
             'doc_path': 'docs/10-method/wvf-0093.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry '
                             'reopened-residue post-closeout portability-drift conflict-arbitration retirement '
                             'witnesses, settled tiebreak, joined handoff, carrier expiry, authority return, priority '
                             'sunset, residue quarantine, and mixed retirement',
                             'This is the compact successor surface for `OQ-0188`.',
                             '## Practice / observation',
                             '## External pressure from cleanup completion, audit retention, carrier expiry, authority '
                             'return, rule sunsets, sampling windows, and transparency history',
                             '## Working synthesis',
                             '## Settled drift tiebreak vs joined handoff vs carrier expiry vs authority return vs '
                             'priority sunset vs residue quarantine vs mixed retirement',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_state`',
                             'settled-reopen-drift-tiebreak-retirement',
                             'joined-lesson-handoff-reopen-drift-retirement',
                             'carrier-expiry-reopen-drift-retirement',
                             'authority-return-reopen-drift-retirement',
                             'priority-sunset-reopen-drift-retirement',
                             'residue-quarantine-reopen-drift-retirement',
                             'mixed-reopen-drift-arbitration-retirement'],
             'runbook_ref': 'wvf-0093.md',
             'prompt_id': 'PP-0146',
             'prompt_needles': ['Use `docs/10-method/wvf-0093.md`',
                                'settled-reopen-drift-tiebreak-retirement, '
                                'joined-lesson-handoff-reopen-drift-retirement, '
                                'carrier-expiry-reopen-drift-retirement, authority-return-reopen-drift-retirement, '
                                'priority-sunset-reopen-drift-retirement, residue-quarantine-reopen-drift-retirement, '
                                'or mixed-reopen-drift-arbitration-retirement'],
             'claim_id': 'CL-0186',
             'oq_id': 'OQ-0188',
             'resolution_id': 'RS-0196',
             'trajectory_oq_id': 'OQ-0189',
             'qws_id': 'QWS-0271',
             'qws_label': 'drift-retirement court / revival-history vault / arbitration-closeout board',
             'changelog_needles': ['wvf-0093.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_drift_arbitration_retirement_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_state',
             'allowed': ['settled-reopen-drift-tiebreak-retirement',
                         'joined-lesson-handoff-reopen-drift-retirement',
                         'carrier-expiry-reopen-drift-retirement',
                         'authority-return-reopen-drift-retirement',
                         'priority-sunset-reopen-drift-retirement',
                         'residue-quarantine-reopen-drift-retirement',
                         'mixed-reopen-drift-arbitration-retirement'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0093.md'],
             'excluded': ['drift-retirement-court-by-default',
                          'revival-history-vault',
                          'arbitration-closeout-board',
                          'winner-persists-after-closeout',
                          'drift-arbitration-retirement-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_drift_arbitration_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_drift_arbitration_witness_contract',
             'doc_path': 'docs/10-method/wvf-0092.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry '
                             'reopened-residue post-closeout portability-drift conflict-arbitration witnesses, no '
                             'arbitration, local join, current evidence precedence, carrier precedence, revocation '
                             'precedence, sunset precedence, and mixed arbitration',
                             'This is the compact successor surface for `OQ-0187`.',
                             '## Practice / observation',
                             '## External pressure from admission bindings, audit-retention currentness, tombstones, '
                             'rule windows, sampling policy changes, cleanup release, and transparency history',
                             '## Working synthesis',
                             '## No arbitration vs local join vs current evidence precedence vs carrier precedence vs '
                             'revocation precedence vs sunset precedence vs mixed arbitration',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_state`',
                             'no-arbitration-needed-reopen-drift-conflict',
                             'local-join-reopen-drift-conflict',
                             'current-evidence-precedence-reopen-drift',
                             'carrier-precedence-reopen-drift',
                             'revocation-precedence-reopen-drift',
                             'sunset-precedence-reopen-drift',
                             'mixed-reopen-drift-arbitration'],
             'runbook_ref': 'wvf-0092.md',
             'prompt_id': 'PP-0145',
             'prompt_needles': ['Use `docs/10-method/wvf-0092.md`',
                                'no-arbitration-needed-reopen-drift-conflict, local-join-reopen-drift-conflict, '
                                'current-evidence-precedence-reopen-drift, carrier-precedence-reopen-drift, '
                                'revocation-precedence-reopen-drift, sunset-precedence-reopen-drift, or '
                                'mixed-reopen-drift-arbitration'],
             'claim_id': 'CL-0185',
             'oq_id': 'OQ-0187',
             'resolution_id': 'RS-0195',
             'trajectory_oq_id': 'OQ-0188',
             'qws_id': 'QWS-0270',
             'qws_label': 'drift-arbitration court / revival-priority ladder / revocation-supremacy tribunal',
             'changelog_needles': ['wvf-0092.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_drift_arbitration_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_state',
             'allowed': ['no-arbitration-needed-reopen-drift-conflict',
                         'local-join-reopen-drift-conflict',
                         'current-evidence-precedence-reopen-drift',
                         'carrier-precedence-reopen-drift',
                         'revocation-precedence-reopen-drift',
                         'sunset-precedence-reopen-drift',
                         'mixed-reopen-drift-arbitration'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0092.md'],
             'excluded': ['drift-arbitration-court-by-default',
                          'revival-priority-ladder',
                          'revocation-supremacy-tribunal',
                          'oldest-portable-lesson-wins',
                          'drift-arbitration-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_witness_contract',
             'doc_path': 'docs/10-method/gpu-rpra-post-closeout-portability-drift-witnesses.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry '
                             'reopened-residue post-closeout portability-drift witnesses, current portability, stale '
                             'template, conflicting carrier, revoked lesson, expired sunset, and mixed drift',
                             'This is the compact successor surface for `OQ-0186`.',
                             '## Practice / observation',
                             '## External pressure from TTL expiry, audit retention, tombstones, admission rebinding, '
                             'rule staleness, sampling policy change, and transparency history',
                             '## Working synthesis',
                             '## Current portability vs stale template vs conflicting carrier vs revoked lesson vs '
                             'expired sunset vs mixed drift',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_state`',
                             'current-reopen-closeout-portability',
                             'stale-reopen-closeout-template',
                             'conflicting-reopen-closeout-carrier',
                             'revoked-reopen-closeout-lesson',
                             'expired-reopen-closeout-sunset',
                             'mixed-reopen-closeout-drift'],
             'runbook_ref': 'gpu-rpra-post-closeout-portability-drift-witnesses.md',
             'prompt_id': 'PP-0144',
             'prompt_needles': ['Use `docs/10-method/gpu-rpra-post-closeout-portability-drift-witnesses.md`',
                                'current-reopen-closeout-portability, stale-reopen-closeout-template, '
                                'conflicting-reopen-closeout-carrier, revoked-reopen-closeout-lesson, '
                                'expired-reopen-closeout-sunset, or mixed-reopen-closeout-drift'],
             'claim_id': 'CL-0184',
             'oq_id': 'OQ-0186',
             'resolution_id': 'RS-0194',
             'trajectory_oq_id': 'OQ-0187',
             'qws_id': 'QWS-0269',
             'qws_label': 'revival-precedent court / residue-drift registry / revocation tribunal',
             'changelog_needles': ['gpu-rpra-post-closeout-portability-drift-witnesses.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_state',
             'allowed': ['current-reopen-closeout-portability',
                         'stale-reopen-closeout-template',
                         'conflicting-reopen-closeout-carrier',
                         'revoked-reopen-closeout-lesson',
                         'expired-reopen-closeout-sunset',
                         'mixed-reopen-closeout-drift'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-rpra-post-closeout-portability-drift-witnesses.md'],
             'excluded': ['revival-precedent-court-by-drift',
                          'stale-portability-still-binds',
                          'carrier-conflict-needs-court',
                          'revocation-erases-audit-history',
                          'post-portability-drift-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_witness_contract',
             'doc_path': 'docs/10-method/wvf-0090.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry '
                             'reopened-residue post-closeout portability witnesses, nonportable history, audit '
                             'reference, tombstone reference, carrier template, counterexample, and mixed portability',
                             'This is the compact successor surface for `OQ-0185`.',
                             '## Practice / observation',
                             '## External pressure from TTL completion, audit retention, tombstone carry, carrier '
                             'templates, sampling context, admission scope, and transparency history',
                             '## Working synthesis',
                             '## Nonportable history vs audit reference vs tombstone reference vs carrier template vs '
                             'counterexample vs mixed reopen-closeout portability',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_state`',
                             'nonportable-reopen-closeout-history',
                             'audit-reference-reopen-closeout',
                             'tombstone-reference-reopen-closeout',
                             'carrier-template-reopen-closeout',
                             'counterexample-only-reopen-closeout',
                             'mixed-reopen-closeout-portability'],
             'runbook_ref': 'wvf-0090.md',
             'prompt_id': 'PP-0143',
             'prompt_needles': ['Use `docs/10-method/wvf-0090.md`',
                                'nonportable-reopen-closeout-history, audit-reference-reopen-closeout, '
                                'tombstone-reference-reopen-closeout, carrier-template-reopen-closeout, '
                                'counterexample-only-reopen-closeout, or mixed-reopen-closeout-portability'],
             'claim_id': 'CL-0183',
             'oq_id': 'OQ-0185',
             'resolution_id': 'RS-0193',
             'trajectory_oq_id': 'OQ-0186',
             'qws_id': 'QWS-0268',
             'qws_label': 'post-closeout portability court / permanent revival ledger / deletion-precedent board',
             'changelog_needles': ['wvf-0090.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_state',
             'allowed': ['nonportable-reopen-closeout-history',
                         'audit-reference-reopen-closeout',
                         'tombstone-reference-reopen-closeout',
                         'carrier-template-reopen-closeout',
                         'counterexample-only-reopen-closeout',
                         'mixed-reopen-closeout-portability'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0090.md'],
             'excluded': ['revival-ledger-by-portability',
                          'deletion-court-by-tombstone',
                          'audit-reference-means-precedence',
                          'template-means-authority',
                          'post-closeout-portability-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_scope_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_scope_witness_contract',
             'doc_path': 'docs/10-method/wvf-0088.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry '
                             'reopened-residue scope witnesses, packet-local, audit-bound, fresh-carrier, '
                             'tombstone-bound, authority-limited, and mixed scope',
                             'This is the compact successor surface for `OQ-0183`.',
                             '## Practice / observation',
                             '## External pressure from audit retention, tombstones, finalizers, admission scope, rule '
                             'staleness, sampling carriers, and transparency history',
                             '## Working synthesis',
                             '## Packet-local vs audit-bound vs fresh-carrier vs tombstone-bound vs authority-limited '
                             'vs mixed reopened-residue scope',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_scope_state`',
                             'packet-local-reopened-residue',
                             'audit-bound-reopened-residue',
                             'fresh-carrier-reopened-residue',
                             'tombstone-bound-reopened-residue',
                             'authority-limited-reopened-residue',
                             'mixed-reopened-residue-scope'],
             'runbook_ref': 'wvf-0088.md',
             'prompt_id': 'PP-0141',
             'prompt_needles': ['Use `docs/10-method/wvf-0088.md`',
                                'packet-local-reopened-residue, audit-bound-reopened-residue, '
                                'fresh-carrier-reopened-residue, tombstone-bound-reopened-residue, '
                                'authority-limited-reopened-residue, or mixed-reopened-residue-scope'],
             'claim_id': 'CL-0181',
             'oq_id': 'OQ-0183',
             'resolution_id': 'RS-0191',
             'trajectory_oq_id': 'OQ-0184',
             'qws_id': 'QWS-0266',
             'qws_label': 'reopened-residue scope court / global operator authority / revival-scope board',
             'changelog_needles': ['wvf-0088.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_scope_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_scope_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_scope_state',
             'allowed': ['packet-local-reopened-residue',
                         'audit-bound-reopened-residue',
                         'fresh-carrier-reopened-residue',
                         'tombstone-bound-reopened-residue',
                         'authority-limited-reopened-residue',
                         'mixed-reopened-residue-scope'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0088.md'],
             'excluded': ['global-operator-by-reopen',
                          'revival-court-by-fresh-packet',
                          'audit-scope-means-precedence',
                          'tombstone-means-erasure',
                          'reopened-residue-scope-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_residue_reopen_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_residue_reopen_witness_contract',
             'doc_path': 'docs/10-method/wvf-0087.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry '
                             'residue/reopen witnesses, no reopen, inspectable history, audit-only reopen, '
                             'fresh-packet required, tombstone-only residue, and mixed residue',
                             'This is the compact successor surface for `OQ-0182`.',
                             '## Practice / observation',
                             '## External pressure from audit retention, tombstones, finalizers, TTL cleanup, rule '
                             'staleness, sampling carriers, and transparency history',
                             '## Working synthesis',
                             '## No reopen vs inspectable history vs audit-only reopen vs fresh-packet required vs '
                             'tombstone-only residue vs mixed residue',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_residue_reopen_state`',
                             'no-reopen-tiebreak-registry-residue',
                             'inspectable-history-tiebreak-registry-residue',
                             'audit-only-reopen-tiebreak-registry-residue',
                             'fresh-packet-required-tiebreak-registry-residue',
                             'tombstone-only-tiebreak-registry-residue',
                             'mixed-tiebreak-registry-residue-reopen'],
             'runbook_ref': 'wvf-0087.md',
             'prompt_id': 'PP-0140',
             'prompt_needles': ['Use `docs/10-method/wvf-0087.md`',
                                'no-reopen-tiebreak-registry-residue, inspectable-history-tiebreak-registry-residue, '
                                'audit-only-reopen-tiebreak-registry-residue, '
                                'fresh-packet-required-tiebreak-registry-residue, '
                                'tombstone-only-tiebreak-registry-residue, or mixed-tiebreak-registry-residue-reopen'],
             'claim_id': 'CL-0180',
             'oq_id': 'OQ-0182',
             'resolution_id': 'RS-0190',
             'trajectory_oq_id': 'OQ-0183',
             'qws_id': 'QWS-0265',
             'qws_label': 'post-retirement reopen board / binding revival court / silent-deletion auditor',
             'changelog_needles': ['wvf-0087.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_residue_reopen_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_residue_reopen_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_residue_reopen_state',
             'allowed': ['no-reopen-tiebreak-registry-residue',
                         'inspectable-history-tiebreak-registry-residue',
                         'audit-only-reopen-tiebreak-registry-residue',
                         'fresh-packet-required-tiebreak-registry-residue',
                         'tombstone-only-tiebreak-registry-residue',
                         'mixed-tiebreak-registry-residue-reopen'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0087.md'],
             'excluded': ['reopen-board-by-residue',
                          'binding-revival-by-history',
                          'silent-deletion-by-retirement',
                          'audit-log-means-authority',
                          'residue-reopen-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_retirement_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_retirement_witness_contract',
             'doc_path': 'docs/10-method/wvf-0086.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry-retirement '
                             'witnesses, settled closeout, carrier expiry, authority return, history freeze, window '
                             'expiry, residue quarantine, and mixed retirement',
                             'This is the compact successor surface for `OQ-0181`.',
                             '## Practice / observation',
                             '## External pressure from TTL cleanup, finalizers, audit retention, admission bindings, '
                             'rule windows, sampling carriers, and transparency history',
                             '## Working synthesis',
                             '## Settled closeout vs carrier expiry vs authority return vs history freeze vs window '
                             'expiry vs residue quarantine vs mixed retirement',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_retirement_state`',
                             'settled-closeout-tiebreak-registry-retirement',
                             'carrier-expiry-tiebreak-registry-retirement',
                             'authority-return-tiebreak-registry-retirement',
                             'nonbinding-history-freeze-tiebreak-registry-retirement',
                             'retirement-window-expiry-tiebreak-registry-retirement',
                             'residue-quarantine-tiebreak-registry-retirement',
                             'mixed-tiebreak-registry-retirement'],
             'runbook_ref': 'wvf-0086.md',
             'prompt_id': 'PP-0139',
             'prompt_needles': ['Use `docs/10-method/wvf-0086.md`',
                                'settled-closeout-tiebreak-registry-retirement, '
                                'carrier-expiry-tiebreak-registry-retirement, '
                                'authority-return-tiebreak-registry-retirement, '
                                'nonbinding-history-freeze-tiebreak-registry-retirement, '
                                'retirement-window-expiry-tiebreak-registry-retirement, '
                                'residue-quarantine-tiebreak-registry-retirement, or '
                                'mixed-tiebreak-registry-retirement'],
             'claim_id': 'CL-0179',
             'oq_id': 'OQ-0181',
             'resolution_id': 'RS-0189',
             'trajectory_oq_id': 'OQ-0182',
             'qws_id': 'QWS-0264',
             'qws_label': 'registry-retirement board / global operator court / immortal closeout ledger',
             'changelog_needles': ['wvf-0086.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_retirement_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_retirement_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_retirement_state',
             'allowed': ['settled-closeout-tiebreak-registry-retirement',
                         'carrier-expiry-tiebreak-registry-retirement',
                         'authority-return-tiebreak-registry-retirement',
                         'nonbinding-history-freeze-tiebreak-registry-retirement',
                         'retirement-window-expiry-tiebreak-registry-retirement',
                         'residue-quarantine-tiebreak-registry-retirement',
                         'mixed-tiebreak-registry-retirement'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0086.md'],
             'excluded': ['operator-court-by-retirement',
                          'immortal-registry-by-closeout',
                          'global-precedence-after-sunset',
                          'history-freeze-means-binding',
                          'registry-retirement-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_scope_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_scope_witness_contract',
             'doc_path': 'docs/10-method/wvf-0085.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break registry-scope '
                             'witnesses, packet-local, carrier-bound, authority-limited, nonbinding-history, '
                             'retirement-window, and mixed scope',
                             'This is the compact successor surface for `OQ-0180`.',
                             '## Practice / observation',
                             '## External pressure from audit scope, owner boundaries, admission bindings, rule '
                             'windows, sampling carriers, and transparency history',
                             '## Working synthesis',
                             '## Packet-local vs carrier-bound vs authority-limited vs nonbinding-history vs '
                             'retirement-window vs mixed registry scope',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_scope_state`',
                             'packet-local-tiebreak-registry-scope',
                             'carrier-bound-tiebreak-registry-scope',
                             'authority-limited-tiebreak-registry-scope',
                             'nonbinding-history-tiebreak-registry-scope',
                             'retirement-window-tiebreak-registry-scope',
                             'mixed-tiebreak-registry-scope'],
             'runbook_ref': 'wvf-0085.md',
             'prompt_id': 'PP-0138',
             'prompt_needles': ['Use `docs/10-method/wvf-0085.md`',
                                'packet-local-tiebreak-registry-scope, carrier-bound-tiebreak-registry-scope, '
                                'authority-limited-tiebreak-registry-scope, '
                                'nonbinding-history-tiebreak-registry-scope, '
                                'retirement-window-tiebreak-registry-scope, or mixed-tiebreak-registry-scope'],
             'claim_id': 'CL-0178',
             'oq_id': 'OQ-0180',
             'resolution_id': 'RS-0188',
             'trajectory_oq_id': 'OQ-0181',
             'qws_id': 'QWS-0263',
             'qws_label': 'global tie-break priority registry / registry-operator court / immortal precedent ledger',
             'changelog_needles': ['wvf-0085.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_scope_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_scope_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_scope_state',
             'allowed': ['packet-local-tiebreak-registry-scope',
                         'carrier-bound-tiebreak-registry-scope',
                         'authority-limited-tiebreak-registry-scope',
                         'nonbinding-history-tiebreak-registry-scope',
                         'retirement-window-tiebreak-registry-scope',
                         'mixed-tiebreak-registry-scope'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0085.md'],
             'excluded': ['global-precedence-registry',
                          'registry-operator-by-default',
                          'closeout-court-by-scope',
                          'history-means-priority',
                          'registry-scope-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_retirement_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_retirement_witness_contract',
             'doc_path': 'docs/10-method/wvf-0078.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal-retirement witnesses, dispute-settled '
                             'closeout, survivor handoff, authority return, policy sunset, precedent quarantine, and '
                             'mixed retirement',
                             'This is the compact successor surface for `OQ-0174`.',
                             '## Practice / observation',
                             '## External pressure from TTL cleanup, garbage collection, audit lifecycles, sampling '
                             'decisions, and transparency logs',
                             '## Working synthesis',
                             '## Dispute-settled closeout vs survivor handoff vs authority return vs policy sunset vs '
                             'precedent quarantine vs mixed retirement',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_retirement_state`',
                             'dispute-settled-appeal-retirement',
                             'survivor-handoff-appeal-retirement',
                             'authority-return-appeal-retirement',
                             'policy-sunset-appeal-retirement',
                             'precedent-quarantine-appeal-retirement',
                             'mixed-appeal-retirement'],
             'runbook_ref': 'wvf-0078.md',
             'prompt_id': 'PP-0131',
             'prompt_needles': ['Use `docs/10-method/wvf-0078.md`',
                                'dispute-settled-appeal-retirement, survivor-handoff-appeal-retirement, '
                                'authority-return-appeal-retirement, policy-sunset-appeal-retirement, '
                                'precedent-quarantine-appeal-retirement, or mixed-appeal-retirement'],
             'claim_id': 'CL-0171',
             'oq_id': 'OQ-0174',
             'resolution_id': 'RS-0181',
             'trajectory_oq_id': 'OQ-0175',
             'qws_id': 'QWS-0256',
             'qws_label': 'post-appeal precedent-portability board / appeal-history vault / cleanup-policy senate',
             'changelog_needles': ['wvf-0078.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_retirement_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_retirement_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_retirement_state',
             'allowed': ['dispute-settled-appeal-retirement',
                         'survivor-handoff-appeal-retirement',
                         'authority-return-appeal-retirement',
                         'policy-sunset-appeal-retirement',
                         'precedent-quarantine-appeal-retirement',
                         'mixed-appeal-retirement'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0078.md'],
             'excluded': ['appeal-never-ends',
                          'precedent-vault-by-default',
                          'survivor-carrier-means-custody',
                          'audit-log-keeps-court-open',
                          'appeal-retirement-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_scope_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_scope_witness_contract',
             'doc_path': 'docs/10-method/gpu-replay-cross-observer-custody-exit-appeal-scope-witnesses-packet-local-survivor-carrier-authority-boundary-policy-window-retirement-window-and-mixed-scope.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal-scope witnesses, packet-local appeal, '
                             'survivor-carrier appeal, authority-boundary appeal, policy-window appeal, '
                             'retirement-window appeal, and mixed scope',
                             'This is the compact successor surface for `OQ-0173`.',
                             '## Practice / observation',
                             '## External pressure from admission request matching, audit policies, tail sampling, and '
                             'transparency logs',
                             '## Working synthesis',
                             '## Packet-local appeal vs survivor-carrier appeal vs authority-boundary appeal vs '
                             'policy-window appeal vs retirement-window appeal vs mixed scope',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_scope_state`',
                             'packet-local-appeal-scope',
                             'survivor-carrier-appeal-scope',
                             'authority-boundary-appeal-scope',
                             'policy-window-appeal-scope',
                             'retirement-window-appeal-scope',
                             'mixed-appeal-scope'],
             'runbook_ref': 'gpu-replay-cross-observer-custody-exit-appeal-scope-witnesses-packet-local-survivor-carrier-authority-boundary-policy-window-retirement-window-and-mixed-scope.md',
             'prompt_id': 'PP-0130',
             'prompt_needles': ['Use '
                                '`docs/10-method/gpu-replay-cross-observer-custody-exit-appeal-scope-witnesses-packet-local-survivor-carrier-authority-boundary-policy-window-retirement-window-and-mixed-scope.md`',
                                'packet-local-appeal-scope, survivor-carrier-appeal-scope, '
                                'authority-boundary-appeal-scope, policy-window-appeal-scope, '
                                'retirement-window-appeal-scope, or mixed-appeal-scope'],
             'claim_id': 'CL-0170',
             'oq_id': 'OQ-0173',
             'resolution_id': 'RS-0180',
             'trajectory_oq_id': 'OQ-0174',
             'qws_id': 'QWS-0255',
             'qws_label': 'appeal-retention board / permanent precedent vault / custody-exit policy court',
             'changelog_needles': ['gpu-replay-cross-observer-custody-exit-appeal-scope-witnesses-packet-local-survivor-carrier-authority-boundary-policy-window-retirement-window-and-mixed-scope.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_scope_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_scope_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_scope_state',
             'allowed': ['packet-local-appeal-scope',
                         'survivor-carrier-appeal-scope',
                         'authority-boundary-appeal-scope',
                         'policy-window-appeal-scope',
                         'retirement-window-appeal-scope',
                         'mixed-appeal-scope'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-replay-cross-observer-custody-exit-appeal-scope-witnesses-packet-local-survivor-carrier-authority-boundary-policy-window-retirement-window-and-mixed-scope.md'],
             'excluded': ['appeal-court-by-default',
                          'vault-everything',
                          'webhook-sees-all',
                          'audit-policy-is-truth',
                          'appeal-scope-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_threshold_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_threshold_witness_contract',
             'doc_path': 'docs/10-method/wvf-0076.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal-threshold witnesses, no appeal, receipt '
                             'repair, repeated retention dispute, authority contest, deletion-proof overflow, and '
                             'mixed threshold',
                             'This is the compact successor surface for `OQ-0172`.',
                             '## Practice / observation',
                             '## External pressure from tombstones, finalizers, audit policy, and audit annotations',
                             '## Working synthesis',
                             '## No appeal vs receipt repair vs repeated retention dispute vs authority contest vs '
                             'deletion-proof overflow vs mixed threshold',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_threshold_state`',
                             'no-appeal-needed',
                             'receipt-repair-threshold',
                             'repeated-retention-dispute',
                             'authority-contest-overflow',
                             'deletion-proof-overflow',
                             'mixed-appeal-threshold'],
             'runbook_ref': 'wvf-0076.md',
             'prompt_id': 'PP-0129',
             'prompt_needles': ['Use `docs/10-method/wvf-0076.md`',
                                'no-appeal-needed, receipt-repair-threshold, repeated-retention-dispute, '
                                'authority-contest-overflow, deletion-proof-overflow, or mixed-appeal-threshold'],
             'claim_id': 'CL-0169',
             'oq_id': 'OQ-0172',
             'resolution_id': 'RS-0179',
             'trajectory_oq_id': 'OQ-0173',
             'qws_id': 'QWS-0254',
             'qws_label': 'appeal-scope court / immutable evidence vault / deletion-dispute tribunal',
             'changelog_needles': ['wvf-0076.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_threshold_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_threshold_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_threshold_state',
             'allowed': ['no-appeal-needed',
                         'receipt-repair-threshold',
                         'repeated-retention-dispute',
                         'authority-contest-overflow',
                         'deletion-proof-overflow',
                         'mixed-appeal-threshold'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0076.md'],
             'excluded': ['appeal-board-by-default',
                          'tombstone-means-proof-of-deletion',
                          'finalizer-is-court',
                          'audit-log-is-truth',
                          'appeal-threshold-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_retirement_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_retirement_witness_contract',
             'doc_path': 'docs/10-method/gpu-replay-cross-observer-custody-retirement-witnesses-claim-settled-carrier-expiry-authority-return-scope-shrink-and-mixed-retirement.md',
             'doc_needles': ['# GPU replay cross-observer custody-retirement witnesses, claim-settled retirement, '
                             'carrier-expiry retirement, authority-return retirement, scope-shrink retirement, and '
                             'mixed retirement',
                             'This is the compact successor surface for `OQ-0171`.',
                             '## Practice / observation',
                             '## External pressure from buffer flushes, metric retention, workload cleanup, owner '
                             'deletion, and finalizers',
                             '## Working synthesis',
                             '## Claim-settled vs carrier-expiry vs authority-return vs scope-shrink vs mixed '
                             'retirement',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_retirement_state`',
                             'claim-settled-retirement',
                             'carrier-expiry-retirement',
                             'authority-return-retirement',
                             'scope-shrink-retirement',
                             'mixed-custody-retirement'],
             'runbook_ref': 'gpu-replay-cross-observer-custody-retirement-witnesses-claim-settled-carrier-expiry-authority-return-scope-shrink-and-mixed-retirement.md',
             'prompt_id': 'PP-0128',
             'prompt_needles': ['Use '
                                '`docs/10-method/gpu-replay-cross-observer-custody-retirement-witnesses-claim-settled-carrier-expiry-authority-return-scope-shrink-and-mixed-retirement.md`',
                                'claim-settled-retirement, carrier-expiry-retirement, authority-return-retirement, '
                                'scope-shrink-retirement, or mixed-custody-retirement'],
             'claim_id': 'CL-0168',
             'oq_id': 'OQ-0171',
             'resolution_id': 'RS-0178',
             'trajectory_oq_id': 'OQ-0172',
             'qws_id': 'QWS-0253',
             'qws_label': 'retention-audit appeal board / custody-exit notary / deletion-proof court',
             'changelog_needles': ['gpu-replay-cross-observer-custody-retirement-witnesses-claim-settled-carrier-expiry-authority-return-scope-shrink-and-mixed-retirement.md',
                                   'check_gpu_replay_cross_observer_custody_retirement_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_retirement_state'],
             'family': 'gpu_replay_cross_observer_custody_retirement_state',
             'allowed': ['claim-settled-retirement',
                         'carrier-expiry-retirement',
                         'authority-return-retirement',
                         'scope-shrink-retirement',
                         'mixed-custody-retirement'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-replay-cross-observer-custody-retirement-witnesses-claim-settled-carrier-expiry-authority-return-scope-shrink-and-mixed-retirement.md'],
             'excluded': ['permanent-retention-by-default',
                          'delete-evidence-after-victory',
                          'appeal-window-forever',
                          'carrier-ttl-means-truth',
                          'custody-retirement-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_scope_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_scope_witness_contract',
             'doc_path': 'docs/10-method/gpu-replay-cross-observer-custody-scope-witnesses-packet-local-bridge-record-evidence-carrier-authority-handoff-retirement-window-and-mixed-custody.md',
             'doc_needles': ['# GPU replay cross-observer custody-scope witnesses, packet-local custody, bridge-record '
                             'custody, evidence-carrier custody, authority-handoff custody, retirement window, and '
                             'mixed custody',
                             'This is the compact successor surface for `OQ-0170`.',
                             '## Practice / observation',
                             '## External pressure from correlation records, trace links, metric exemplars, object '
                             'identities, placement authority, and retention windows',
                             '## Working synthesis',
                             '## Packet-local vs bridge-record vs evidence-carrier vs authority-handoff vs '
                             'retirement-window vs mixed custody',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_scope_state`',
                             'packet-local-custody',
                             'bridge-record-custody',
                             'evidence-carrier-custody',
                             'authority-handoff-custody',
                             'retirement-window-custody',
                             'mixed-custody-scope'],
             'runbook_ref': 'gpu-replay-cross-observer-custody-scope-witnesses-packet-local-bridge-record-evidence-carrier-authority-handoff-retirement-window-and-mixed-custody.md',
             'prompt_id': 'PP-0127',
             'prompt_needles': ['Use '
                                '`docs/10-method/gpu-replay-cross-observer-custody-scope-witnesses-packet-local-bridge-record-evidence-carrier-authority-handoff-retirement-window-and-mixed-custody.md`',
                                'packet-local-custody, bridge-record-custody, evidence-carrier-custody, '
                                'authority-handoff-custody, retirement-window-custody, or mixed-custody-scope'],
             'claim_id': 'CL-0167',
             'oq_id': 'OQ-0170',
             'resolution_id': 'RS-0177',
             'trajectory_oq_id': 'OQ-0171',
             'qws_id': 'QWS-0252',
             'qws_label': 'custody-retention notary / authority escrow / telemetry retirement court',
             'changelog_needles': ['gpu-replay-cross-observer-custody-scope-witnesses-packet-local-bridge-record-evidence-carrier-authority-handoff-retirement-window-and-mixed-custody.md',
                                   'check_gpu_replay_cross_observer_custody_scope_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_scope_state'],
             'family': 'gpu_replay_cross_observer_custody_scope_state',
             'allowed': ['packet-local-custody',
                         'bridge-record-custody',
                         'evidence-carrier-custody',
                         'authority-handoff-custody',
                         'retirement-window-custody',
                         'mixed-custody-scope'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-replay-cross-observer-custody-scope-witnesses-packet-local-bridge-record-evidence-carrier-authority-handoff-retirement-window-and-mixed-custody.md'],
             'excluded': ['notary-custody-by-default',
                          'trace-id-owns-custody',
                          'exemplar-escrow-for-every-metric',
                          'scheduler-is-replay-court',
                          'custody-scope-ish']}}]
