# Locality-sized segment of exact GPU witness contract specs.
# Aggregated by tools/gpu_witness_contract_specs.py; consumed by the batch checker.

GPU_WITNESS_CONTRACT_SPECS_PART_2 = [{'source_checker': 'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_witness_contract.py',
  'kwargs': {'kind': 'gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_witness_contract',
             'doc_path': 'docs/10-method/wvf-0103.md',
             'doc_needles': ['# GPU replay reopened-residue drift governance-retirement portability-drift '
                             'conflict-arbitration retirement governance-retirement witnesses, discharge, scope '
                             'sunset, authority return, history freeze, residue quarantine, handoff, and mixed '
                             'closeout',
                             'This is the compact successor surface for `OQ-0198`.',
                             '## Practice / observation',
                             '## External pressure from cleanup completion, finalizer removal, owner return, audit '
                             'freeze, stale-signal tombstones, trace horizon expiry, and transparency checkpoints',
                             '## Working synthesis',
                             '## Discharged vs scope-sunset vs authority-return vs conflict-history-freeze vs '
                             'residue-quarantine vs successor-handoff vs mixed governance retirement',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_state`',
                             'discharged-post-arbitration-governance-retirement',
                             'scope-sunset-post-arbitration-governance-retirement',
                             'authority-return-post-arbitration-governance-retirement',
                             'conflict-history-freeze-post-arbitration-governance-retirement',
                             'residue-quarantine-post-arbitration-governance-retirement',
                             'successor-handoff-post-arbitration-governance-retirement',
                             'mixed-post-arbitration-governance-retirement'],
             'runbook_ref': 'wvf-0103.md',
             'prompt_id': 'PP-0156',
             'prompt_needles': ['Use `docs/10-method/wvf-0103.md`',
                                'discharged-post-arbitration-governance-retirement, '
                                'scope-sunset-post-arbitration-governance-retirement, '
                                'authority-return-post-arbitration-governance-retirement, '
                                'conflict-history-freeze-post-arbitration-governance-retirement, '
                                'residue-quarantine-post-arbitration-governance-retirement, '
                                'successor-handoff-post-arbitration-governance-retirement, or '
                                'mixed-post-arbitration-governance-retirement'],
             'claim_id': 'CL-0196',
             'oq_id': 'OQ-0198',
             'resolution_id': 'RS-0206',
             'trajectory_oq_id': 'OQ-0199',
             'qws_id': 'QWS-0281',
             'qws_label': 'post-arbitration-governance-retirement portability court / retired governance carrier '
                          'exchange / conflict-history exit-proof registry',
             'changelog_needles': ['wvf-0103.md',
                                   'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_retirement_state',
             'allowed': ['discharged-post-arbitration-governance-retirement',
                         'scope-sunset-post-arbitration-governance-retirement',
                         'authority-return-post-arbitration-governance-retirement',
                         'conflict-history-freeze-post-arbitration-governance-retirement',
                         'residue-quarantine-post-arbitration-governance-retirement',
                         'successor-handoff-post-arbitration-governance-retirement',
                         'mixed-post-arbitration-governance-retirement'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0103.md'],
             'excluded': ['permanent-post-arbitration-governance-by-scope',
                          'immortal-conflict-history-ledger',
                          'authority-return-court-after-closeout',
                          'scoped-governance-remains-live',
                          'post-arbitration-governance-retirement-ish']}},
 {'source_checker': 'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_scope_witness_contract.py',
  'kwargs': {'kind': 'gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_scope_witness_contract',
             'doc_path': 'docs/10-method/wvf-0102.md',
             'doc_needles': ['# GPU replay reopened-residue drift governance-retirement portability-drift '
                             'conflict-arbitration retirement governance-scope witnesses, packet-local, '
                             'history-custody-bound, authority-lane-limited, successor-route-bound, retirement-window, '
                             'and mixed scope',
                             'This is the compact successor surface for `OQ-0197`.',
                             '## Practice / observation',
                             '## External pressure from audit retention, policy binding, owner scope, stale-signal '
                             'windows, trace-carrier limits, and transparency checkpoints',
                             '## Working synthesis',
                             '## Packet-local vs history-custody-bound vs authority-lane-limited vs '
                             'successor-route-bound vs retirement-window vs mixed scope',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_scope_state`',
                             'packet-local-post-arbitration-governance-scope',
                             'history-custody-bound-post-arbitration-governance-scope',
                             'authority-lane-limited-post-arbitration-governance-scope',
                             'successor-route-bound-post-arbitration-governance-scope',
                             'retirement-window-post-arbitration-governance-scope',
                             'mixed-post-arbitration-governance-scope'],
             'runbook_ref': 'wvf-0102.md',
             'prompt_id': 'PP-0155',
             'prompt_needles': ['Use `docs/10-method/wvf-0102.md`',
                                'packet-local-post-arbitration-governance-scope, '
                                'history-custody-bound-post-arbitration-governance-scope, '
                                'authority-lane-limited-post-arbitration-governance-scope, '
                                'successor-route-bound-post-arbitration-governance-scope, '
                                'retirement-window-post-arbitration-governance-scope, or '
                                'mixed-post-arbitration-governance-scope'],
             'claim_id': 'CL-0195',
             'oq_id': 'OQ-0197',
             'resolution_id': 'RS-0205',
             'trajectory_oq_id': 'OQ-0198',
             'qws_id': 'QWS-0280',
             'qws_label': 'permanent post-arbitration governance board / conflict-history custody court / '
                          'successor-route authority registry',
             'changelog_needles': ['wvf-0102.md',
                                   'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_scope_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_scope_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_scope_state',
             'allowed': ['packet-local-post-arbitration-governance-scope',
                         'history-custody-bound-post-arbitration-governance-scope',
                         'authority-lane-limited-post-arbitration-governance-scope',
                         'successor-route-bound-post-arbitration-governance-scope',
                         'retirement-window-post-arbitration-governance-scope',
                         'mixed-post-arbitration-governance-scope'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0102.md'],
             'excluded': ['global-post-arbitration-governance-court',
                          'conflict-history-vault-by-scope',
                          'successor-route-board-by-default',
                          'authority-lane-senate',
                          'post-arbitration-governance-scope-ish']}},
 {'source_checker': 'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_witness_contract.py',
  'kwargs': {'kind': 'gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_witness_contract',
             'doc_path': 'docs/10-method/wvf-0101.md',
             'doc_needles': ['# GPU replay reopened-residue drift governance-retirement portability-drift '
                             'conflict-arbitration retirement governance-threshold witnesses, no standing governance, '
                             'repeated retirement failure, history loss, overbinding, authority split, successor-route '
                             'loop, and mixed escalation',
                             'This is the compact successor surface for `OQ-0196`.',
                             '## Practice / observation',
                             '## External pressure from incident escalation, audit retention, policy binding, owner '
                             'return, stale-signal expiry, and transparency checkpoints',
                             '## Working synthesis',
                             '## No standing governance vs repeated failure vs history loss vs overbinding vs '
                             'authority split vs successor loop vs mixed threshold',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_state`',
                             'no-standing-post-arbitration-governance',
                             'repeated-retirement-failure-post-arbitration-governance',
                             'conflict-history-loss-post-arbitration-governance',
                             'conflict-history-overbinding-post-arbitration-governance',
                             'authority-split-post-arbitration-governance',
                             'successor-route-loop-post-arbitration-governance',
                             'mixed-post-arbitration-governance-threshold'],
             'runbook_ref': 'wvf-0101.md',
             'prompt_id': 'PP-0154',
             'prompt_needles': ['Use `docs/10-method/wvf-0101.md`',
                                'no-standing-post-arbitration-governance, '
                                'repeated-retirement-failure-post-arbitration-governance, '
                                'conflict-history-loss-post-arbitration-governance, '
                                'conflict-history-overbinding-post-arbitration-governance, '
                                'authority-split-post-arbitration-governance, '
                                'successor-route-loop-post-arbitration-governance, or '
                                'mixed-post-arbitration-governance-threshold'],
             'claim_id': 'CL-0194',
             'oq_id': 'OQ-0196',
             'resolution_id': 'RS-0204',
             'trajectory_oq_id': 'OQ-0197',
             'qws_id': 'QWS-0279',
             'qws_label': 'post-arbitration governance scope court / conflict-history vault / successor-route board',
             'changelog_needles': ['wvf-0101.md',
                                   'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_governance_threshold_state',
             'allowed': ['no-standing-post-arbitration-governance',
                         'repeated-retirement-failure-post-arbitration-governance',
                         'conflict-history-loss-post-arbitration-governance',
                         'conflict-history-overbinding-post-arbitration-governance',
                         'authority-split-post-arbitration-governance',
                         'successor-route-loop-post-arbitration-governance',
                         'mixed-post-arbitration-governance-threshold'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0101.md'],
             'excluded': ['post-arbitration-governance-by-default',
                          'exit-proof-conflict-history-vault',
                          'successor-route-closeout-board',
                          'retired-arbitration-common-law',
                          'post-arbitration-governance-ish']}},
 {'source_checker': 'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_witness_contract.py',
  'kwargs': {'kind': 'gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_witness_contract',
             'doc_path': 'docs/10-method/wvf-0100.md',
             'doc_needles': ['# GPU replay reopened-residue drift governance-retirement portability-drift '
                             'conflict-arbitration retirement witnesses, settled arbitration, joined handoff, carrier '
                             'expiry, authority return, priority sunset, residue quarantine, and mixed retirement',
                             'This is the compact successor surface for `OQ-0195`.',
                             '## Practice / observation',
                             '## External pressure from cleanup completion, audit retention, carrier expiry, authority '
                             'return, rule sunsets, sampling windows, and transparency history',
                             '## Working synthesis',
                             '## Settled arbitration vs joined handoff vs carrier expiry vs authority return vs '
                             'priority sunset vs residue quarantine vs mixed retirement',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_state`',
                             'settled-retired-governance-drift-arbitration-retirement',
                             'joined-route-handoff-retired-governance-drift-retirement',
                             'carrier-expiry-retired-governance-drift-arbitration-retirement',
                             'authority-return-retired-governance-drift-arbitration-retirement',
                             'priority-sunset-retired-governance-drift-arbitration-retirement',
                             'residue-quarantine-retired-governance-drift-arbitration-retirement',
                             'mixed-retired-governance-drift-arbitration-retirement'],
             'runbook_ref': 'wvf-0100.md',
             'prompt_id': 'PP-0153',
             'prompt_needles': ['Use `docs/10-method/wvf-0100.md`',
                                'settled-retired-governance-drift-arbitration-retirement, '
                                'joined-route-handoff-retired-governance-drift-retirement, '
                                'carrier-expiry-retired-governance-drift-arbitration-retirement, '
                                'authority-return-retired-governance-drift-arbitration-retirement, '
                                'priority-sunset-retired-governance-drift-arbitration-retirement, '
                                'residue-quarantine-retired-governance-drift-arbitration-retirement, or '
                                'mixed-retired-governance-drift-arbitration-retirement'],
             'claim_id': 'CL-0193',
             'oq_id': 'OQ-0195',
             'resolution_id': 'RS-0203',
             'trajectory_oq_id': 'OQ-0196',
             'qws_id': 'QWS-0278',
             'qws_label': 'post-arbitration-retirement governance threshold / exit-proof conflict-history vault / '
                          'successor-route closeout board',
             'changelog_needles': ['wvf-0100.md',
                                   'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_retirement_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_retirement_state',
             'allowed': ['settled-retired-governance-drift-arbitration-retirement',
                         'joined-route-handoff-retired-governance-drift-retirement',
                         'carrier-expiry-retired-governance-drift-arbitration-retirement',
                         'authority-return-retired-governance-drift-arbitration-retirement',
                         'priority-sunset-retired-governance-drift-arbitration-retirement',
                         'residue-quarantine-retired-governance-drift-arbitration-retirement',
                         'mixed-retired-governance-drift-arbitration-retirement'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0100.md'],
             'excluded': ['retired-governance-arbitration-retirement-court',
                          'exit-proof-conflict-ledger-by-default',
                          'successor-route-priority-board',
                          'winner-persists-after-retirement',
                          'retired-governance-arbitration-retirement-ish']}},
 {'source_checker': 'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_witness_contract.py',
  'kwargs': {'kind': 'gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_witness_contract',
             'doc_path': 'docs/10-method/wvf-0099.md',
             'doc_needles': ['# GPU replay reopened-residue drift governance-retirement portability-drift '
                             'conflict-arbitration witnesses, no arbitration, local join, current carrier precedence, '
                             'revocation precedence, exit-proof precedence, successor-route precedence, and mixed '
                             'arbitration',
                             'This is the compact successor surface for `OQ-0194`.',
                             '## Practice / observation',
                             '## External pressure from admission rebinding, audit retention, tombstones, trace '
                             'carriers, transparency revocation, finalizer release, and policy windows',
                             '## Working synthesis',
                             '## No arbitration vs local join vs current carrier vs revocation vs exit proof vs '
                             'successor route vs mixed arbitration',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_state`',
                             'no-arbitration-needed-retired-governance-drift-conflict',
                             'local-join-retired-governance-drift-conflict',
                             'current-carrier-precedence-retired-governance-drift',
                             'revocation-precedence-retired-governance-drift',
                             'exit-proof-precedence-retired-governance-drift',
                             'successor-route-precedence-retired-governance-drift',
                             'mixed-retired-governance-drift-arbitration'],
             'runbook_ref': 'wvf-0099.md',
             'prompt_id': 'PP-0152',
             'prompt_needles': ['Use `docs/10-method/wvf-0099.md`',
                                'no-arbitration-needed-retired-governance-drift-conflict, '
                                'local-join-retired-governance-drift-conflict, '
                                'current-carrier-precedence-retired-governance-drift, '
                                'revocation-precedence-retired-governance-drift, '
                                'exit-proof-precedence-retired-governance-drift, '
                                'successor-route-precedence-retired-governance-drift, or '
                                'mixed-retired-governance-drift-arbitration'],
             'claim_id': 'CL-0192',
             'oq_id': 'OQ-0194',
             'resolution_id': 'RS-0202',
             'trajectory_oq_id': 'OQ-0195',
             'qws_id': 'QWS-0277',
             'qws_label': 'retired-governance arbitration-retirement court / exit-proof conflict ledger / '
                          'successor-route priority board',
             'changelog_needles': ['wvf-0099.md',
                                   'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_conflict_arbitration_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_conflict_arbitration_state',
             'allowed': ['no-arbitration-needed-retired-governance-drift-conflict',
                         'local-join-retired-governance-drift-conflict',
                         'current-carrier-precedence-retired-governance-drift',
                         'revocation-precedence-retired-governance-drift',
                         'exit-proof-precedence-retired-governance-drift',
                         'successor-route-precedence-retired-governance-drift',
                         'mixed-retired-governance-drift-arbitration'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0099.md'],
             'excluded': ['retired-governance-drift-arbitration-court',
                          'exit-proof-priority-ladder-by-default',
                          'carrier-freshness-tribunal',
                          'revoked-retired-governance-lesson-reanimated',
                          'retired-governance-drift-arbitration-ish']}},
 {'source_checker': 'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_witness_contract.py',
  'kwargs': {'kind': 'gpu_reopened_residue_drift_governance_retirement_portability_drift_witness_contract',
             'doc_path': 'docs/10-method/wvf-0098.md',
             'doc_needles': ['# GPU replay reopened-residue drift governance-retirement portability-drift witnesses, '
                             'current carry, stale template, carrier conflict, revoked lesson, expired exit proof, '
                             'successor-required, and mixed drift',
                             'This is the compact successor surface for `OQ-0193`.',
                             '## Practice / observation',
                             '## External pressure from audit-retention currentness, finalizer release, tombstone '
                             'staleness, trace-carrier rebinding, transparency-log revocation, and policy revalidation '
                             'windows',
                             '## Working synthesis',
                             '## Current carry vs stale template vs carrier conflict vs revoked lesson vs expired exit '
                             'proof vs successor-required vs mixed drift',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_state`',
                             'current-retired-governance-portability',
                             'stale-retired-governance-template',
                             'carrier-conflicted-retired-governance',
                             'revoked-retired-governance-lesson',
                             'expired-retired-governance-exit-proof',
                             'successor-required-retired-governance-drift',
                             'mixed-retired-governance-drift'],
             'runbook_ref': 'wvf-0098.md',
             'prompt_id': 'PP-0151',
             'prompt_needles': ['Use `docs/10-method/wvf-0098.md`',
                                'current-retired-governance-portability, stale-retired-governance-template, '
                                'carrier-conflicted-retired-governance, revoked-retired-governance-lesson, '
                                'expired-retired-governance-exit-proof, successor-required-retired-governance-drift, '
                                'or mixed-retired-governance-drift'],
             'claim_id': 'CL-0191',
             'oq_id': 'OQ-0193',
             'resolution_id': 'RS-0201',
             'trajectory_oq_id': 'OQ-0194',
             'qws_id': 'QWS-0276',
             'qws_label': 'retired-governance drift-arbitration court / exit-proof priority ladder / carrier-freshness '
                          'tribunal',
             'changelog_needles': ['wvf-0098.md',
                                   'check_gpu_reopened_residue_drift_governance_retirement_portability_drift_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_drift_state',
             'allowed': ['current-retired-governance-portability',
                         'stale-retired-governance-template',
                         'carrier-conflicted-retired-governance',
                         'revoked-retired-governance-lesson',
                         'expired-retired-governance-exit-proof',
                         'successor-required-retired-governance-drift',
                         'mixed-retired-governance-drift'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0098.md'],
             'excluded': ['retired-governance-portability-drift-court',
                          'carrier-revalidation-board-by-default',
                          'exit-proof-freshness-registry',
                          'revoked-retirement-history-erased',
                          'retired-governance-drift-ish']}},
 {'source_checker': 'check_gpu_reopened_residue_drift_governance_retirement_portability_witness_contract.py',
  'kwargs': {'kind': 'gpu_reopened_residue_drift_governance_retirement_portability_witness_contract',
             'doc_path': 'docs/10-method/wvf-0097.md',
             'doc_needles': ['# GPU replay reopened-residue drift governance-retirement portability witnesses, '
                             'nonportable, audit reference, carrier template, exit-proof reference, counterexample, '
                             'successor-required, and mixed carry',
                             'This is the compact successor surface for `OQ-0192`.',
                             '## Practice / observation',
                             '## External pressure from audit retention, finalizer release, tombstone portability, '
                             'trace carrier reuse, transparency inclusion proof, and policy revalidation windows',
                             '## Working synthesis',
                             '## Nonportable vs audit-reference vs carrier-template vs exit-proof-reference vs '
                             'counterexample-only vs successor-packet-required vs mixed portability',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_state`',
                             'nonportable-retired-governance-history',
                             'audit-reference-retired-governance',
                             'carrier-template-retired-governance',
                             'exit-proof-reference-retired-governance',
                             'counterexample-only-retired-governance',
                             'successor-packet-required-retired-governance',
                             'mixed-retired-governance-portability'],
             'runbook_ref': 'wvf-0097.md',
             'prompt_id': 'PP-0150',
             'prompt_needles': ['Use `docs/10-method/wvf-0097.md`',
                                'nonportable-retired-governance-history, audit-reference-retired-governance, '
                                'carrier-template-retired-governance, exit-proof-reference-retired-governance, '
                                'counterexample-only-retired-governance, successor-packet-required-retired-governance, '
                                'or mixed-retired-governance-portability'],
             'claim_id': 'CL-0190',
             'oq_id': 'OQ-0192',
             'resolution_id': 'RS-0200',
             'trajectory_oq_id': 'OQ-0193',
             'qws_id': 'QWS-0275',
             'qws_label': 'retired-governance portability-drift court / carrier-revalidation board / exit-proof '
                          'freshness registry',
             'changelog_needles': ['wvf-0097.md',
                                   'check_gpu_reopened_residue_drift_governance_retirement_portability_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_portability_state',
             'allowed': ['nonportable-retired-governance-history',
                         'audit-reference-retired-governance',
                         'carrier-template-retired-governance',
                         'exit-proof-reference-retired-governance',
                         'counterexample-only-retired-governance',
                         'successor-packet-required-retired-governance',
                         'mixed-retired-governance-portability'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0097.md'],
             'excluded': ['retired-governance-portability-court',
                          'retired-governance-carrier-exchange',
                          'exit-proof-registry-by-default',
                          'retired-authority-travels-live',
                          'retired-governance-portability-ish']}},
 {'source_checker': 'check_gpu_reopened_residue_drift_governance_retirement_witness_contract.py',
  'kwargs': {'kind': 'gpu_reopened_residue_drift_governance_retirement_witness_contract',
             'doc_path': 'docs/10-method/reopened-residue-drift-governance-retirement-witnesses-discharge-sunset-return-freeze-quarantine-handoff-and-mixed.md',
             'doc_needles': ['# GPU replay reopened-residue drift governance-retirement witnesses, discharge, sunset, '
                             'return, freeze, quarantine, handoff, and mixed closeout',
                             'This is the compact successor surface for `OQ-0191`.',
                             '## Practice / observation',
                             '## External pressure from finalizer removal, tombstone expiry, audit retention, rule '
                             'silence, sampling horizon, and transparency checkpoint closures',
                             '## Working synthesis',
                             '## Discharged vs scope-sunset vs authority-return vs history-freeze vs '
                             'residue-quarantine vs successor-handoff vs mixed governance retirement',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_state`',
                             'discharged-reopen-drift-governance-retirement',
                             'scope-sunset-reopen-drift-governance-retirement',
                             'authority-return-reopen-drift-governance-retirement',
                             'history-freeze-reopen-drift-governance-retirement',
                             'residue-quarantine-reopen-drift-governance-retirement',
                             'successor-handoff-reopen-drift-governance-retirement',
                             'mixed-reopen-drift-governance-retirement'],
             'runbook_ref': 'reopened-residue-drift-governance-retirement-witnesses-discharge-sunset-return-freeze-quarantine-handoff-and-mixed.md',
             'prompt_id': 'PP-0149',
             'prompt_needles': ['Use '
                                '`docs/10-method/reopened-residue-drift-governance-retirement-witnesses-discharge-sunset-return-freeze-quarantine-handoff-and-mixed.md`',
                                'discharged-reopen-drift-governance-retirement, '
                                'scope-sunset-reopen-drift-governance-retirement, '
                                'authority-return-reopen-drift-governance-retirement, '
                                'history-freeze-reopen-drift-governance-retirement, '
                                'residue-quarantine-reopen-drift-governance-retirement, '
                                'successor-handoff-reopen-drift-governance-retirement, or '
                                'mixed-reopen-drift-governance-retirement'],
             'claim_id': 'CL-0189',
             'oq_id': 'OQ-0191',
             'resolution_id': 'RS-0199',
             'trajectory_oq_id': 'OQ-0192',
             'qws_id': 'QWS-0274',
             'qws_label': 'post-governance-retirement portability court / retired-governance carrier exchange / '
                          'exit-proof registry',
             'changelog_needles': ['reopened-residue-drift-governance-retirement-witnesses-discharge-sunset-return-freeze-quarantine-handoff-and-mixed.md',
                                   'check_gpu_reopened_residue_drift_governance_retirement_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_registry_reopened_residue_post_closeout_portability_drift_conflict_arbitration_retirement_governance_retirement_state',
             'allowed': ['discharged-reopen-drift-governance-retirement',
                         'scope-sunset-reopen-drift-governance-retirement',
                         'authority-return-reopen-drift-governance-retirement',
                         'history-freeze-reopen-drift-governance-retirement',
                         'residue-quarantine-reopen-drift-governance-retirement',
                         'successor-handoff-reopen-drift-governance-retirement',
                         'mixed-reopen-drift-governance-retirement'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/reopened-residue-drift-governance-retirement-witnesses-discharge-sunset-return-freeze-quarantine-handoff-and-mixed.md'],
             'excluded': ['permanent-governance-by-scope',
                          'immortal-revival-history-ledger',
                          'operator-court-after-closeout',
                          'retired-governance-remains-live',
                          'governance-retirement-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_bridge_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_bridge_witness_contract',
             'doc_path': 'docs/10-method/gpu-replay-cross-observer-bridge-witnesses-trace-context-external-correlation-metric-exemplars-placement-scope-and-missing-bridge.md',
             'doc_needles': ['# GPU replay cross-observer bridge witnesses, trace context, external correlation, '
                             'metric exemplars, placement scope, missing bridge, and mixed bridge',
                             'This is the compact successor surface for `OQ-0168`.',
                             '## Practice / observation',
                             '## External pressure from CUPTI external correlation, Nsight NVTX projection, W3C trace '
                             'context, OpenTelemetry metric exemplars, DCGM Kubernetes telemetry, and device placement',
                             '## Working synthesis',
                             '## External-correlation vs trace-context vs metric-exemplar vs placement-scope vs '
                             'missing vs mixed bridge',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_bridge_state`',
                             'external-correlation-bridge',
                             'trace-context-bridge',
                             'metric-exemplar-bridge',
                             'placement-scope-bridge',
                             'missing-cross-observer-bridge',
                             'mixed-cross-observer-bridge'],
             'runbook_ref': 'gpu-replay-cross-observer-bridge-witnesses-trace-context-external-correlation-metric-exemplars-placement-scope-and-missing-bridge.md',
             'prompt_id': 'PP-0125',
             'prompt_needles': ['Use '
                                '`docs/10-method/gpu-replay-cross-observer-bridge-witnesses-trace-context-external-correlation-metric-exemplars-placement-scope-and-missing-bridge.md`',
                                'external-correlation-bridge, trace-context-bridge, metric-exemplar-bridge, '
                                'placement-scope-bridge, missing-cross-observer-bridge, or '
                                'mixed-cross-observer-bridge'],
             'claim_id': 'CL-0165',
             'oq_id': 'OQ-0168',
             'resolution_id': 'RS-0175',
             'trajectory_oq_id': 'OQ-0169',
             'qws_id': 'QWS-0250',
             'qws_label': 'cross-observer bridge notary / exemplar escrow / placement treaty',
             'changelog_needles': ['gpu-replay-cross-observer-bridge-witnesses-trace-context-external-correlation-metric-exemplars-placement-scope-and-missing-bridge.md',
                                   'check_gpu_replay_cross_observer_bridge_witness_contract.py',
                                   'check_reentry_generation_closure_contract.py',
                                   'gpu_replay_cross_observer_bridge_state'],
             'family': 'gpu_replay_cross_observer_bridge_state',
             'allowed': ['external-correlation-bridge',
                         'trace-context-bridge',
                         'metric-exemplar-bridge',
                         'placement-scope-bridge',
                         'missing-cross-observer-bridge',
                         'mixed-cross-observer-bridge'],
             'surfaces': ['WITNESS-VOCABULARY.json',
                          'REVISION-RECEIPT.json',
                          'docs/10-method/gpu-replay-cross-observer-bridge-witnesses-trace-context-external-correlation-metric-exemplars-placement-scope-and-missing-bridge.md'],
             'excluded': ['trace-id-is-truth',
                          'metric-exemplar-is-lineage',
                          'placement-label-proves-replay',
                          'bridge-means-treaty',
                          'cross-observer-bridge-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_retirement_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_retirement_witness_contract',
             'doc_path': 'docs/10-method/wvf-0083.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent-conflict arbitration '
                             'retirement witnesses, settled tiebreak, joined handoff, carrier expiry, authority '
                             'return, priority sunset, residue quarantine, and mixed retirement',
                             'This is the compact successor surface for `OQ-0178`.',
                             '## Practice / observation',
                             '## External pressure from TTL cleanup, finalizers, alert resolution, sampling decisions, '
                             'admission scope, and transparency logs',
                             '## Working synthesis',
                             '## Settled tiebreak vs joined handoff vs carrier expiry vs authority return vs priority '
                             'sunset vs residue quarantine vs mixed retirement',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_retirement_state`',
                             'settled-tiebreak-arbitration-retirement',
                             'joined-lesson-handoff-arbitration-retirement',
                             'carrier-expiry-arbitration-retirement',
                             'authority-return-arbitration-retirement',
                             'priority-sunset-arbitration-retirement',
                             'residue-quarantine-arbitration-retirement',
                             'mixed-arbitration-retirement'],
             'runbook_ref': 'wvf-0083.md',
             'prompt_id': 'PP-0136',
             'prompt_needles': ['Use `docs/10-method/wvf-0083.md`',
                                'settled-tiebreak-arbitration-retirement, '
                                'joined-lesson-handoff-arbitration-retirement, carrier-expiry-arbitration-retirement, '
                                'authority-return-arbitration-retirement, priority-sunset-arbitration-retirement, '
                                'residue-quarantine-arbitration-retirement, or mixed-arbitration-retirement'],
             'claim_id': 'CL-0176',
             'oq_id': 'OQ-0178',
             'resolution_id': 'RS-0186',
             'trajectory_oq_id': 'OQ-0179',
             'qws_id': 'QWS-0261',
             'qws_label': 'permanent tie-break registry / precedent-priority ledger / arbitration-closeout court',
             'changelog_needles': ['wvf-0083.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_retirement_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_retirement_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_retirement_state',
             'allowed': ['settled-tiebreak-arbitration-retirement',
                         'joined-lesson-handoff-arbitration-retirement',
                         'carrier-expiry-arbitration-retirement',
                         'authority-return-arbitration-retirement',
                         'priority-sunset-arbitration-retirement',
                         'residue-quarantine-arbitration-retirement',
                         'mixed-arbitration-retirement'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0083.md'],
             'excluded': ['permanent-tiebreak-registry',
                          'priority-ladder-by-retirement',
                          'arbitration-closeout-court',
                          'winning-lesson-always-persists',
                          'arbitration-retirement-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_witness_contract',
             'doc_path': 'docs/10-method/wvf-0082.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent-conflict arbitration '
                             'witnesses, no arbitration, local join, carrier precedence, authority precedence, sunset '
                             'precedence, revocation precedence, and mixed arbitration',
                             'This is the compact successor surface for `OQ-0177`.',
                             '## Practice / observation',
                             '## External pressure from admission bindings, webhook reinvocation and failure policy, '
                             'recording-rule ordering, sampling policies, and transparency logs',
                             '## Working synthesis',
                             '## No arbitration vs local join vs carrier precedence vs authority precedence vs sunset '
                             'precedence vs revocation precedence vs mixed arbitration',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_state`',
                             'no-arbitration-needed-precedent-conflict',
                             'local-join-precedent-conflict',
                             'carrier-precedence-precedent-conflict',
                             'authority-precedence-precedent-conflict',
                             'sunset-precedence-precedent-conflict',
                             'revocation-precedence-precedent-conflict',
                             'mixed-precedent-conflict-arbitration'],
             'runbook_ref': 'wvf-0082.md',
             'prompt_id': 'PP-0135',
             'prompt_needles': ['Use `docs/10-method/wvf-0082.md`',
                                'no-arbitration-needed-precedent-conflict, local-join-precedent-conflict, '
                                'carrier-precedence-precedent-conflict, authority-precedence-precedent-conflict, '
                                'sunset-precedence-precedent-conflict, revocation-precedence-precedent-conflict, or '
                                'mixed-precedent-conflict-arbitration'],
             'claim_id': 'CL-0175',
             'oq_id': 'OQ-0177',
             'resolution_id': 'RS-0185',
             'trajectory_oq_id': 'OQ-0178',
             'qws_id': 'QWS-0260',
             'qws_label': 'binding precedent appellate court / global priority ladder / inter-case arbitration '
                          'tribunal',
             'changelog_needles': ['wvf-0082.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_conflict_arbitration_state',
             'allowed': ['no-arbitration-needed-precedent-conflict',
                         'local-join-precedent-conflict',
                         'carrier-precedence-precedent-conflict',
                         'authority-precedence-precedent-conflict',
                         'sunset-precedence-precedent-conflict',
                         'revocation-precedence-precedent-conflict',
                         'mixed-precedent-conflict-arbitration'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0082.md'],
             'excluded': ['precedent-court-by-default',
                          'binding-priority-ladder',
                          'arbitration-tribunal-by-conflict',
                          'oldest-lesson-always-wins',
                          'precedent-conflict-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_drift_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_drift_witness_contract',
             'doc_path': 'docs/10-method/wvf-0081.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent-drift witnesses, current '
                             'portability, stale template, conflicting carrier, revoked lesson, sunset expiry, and '
                             'mixed drift',
                             'This is the compact successor surface for `OQ-0176`.',
                             '## Practice / observation',
                             '## External pressure from admission policy bindings, webhook mutation windows, '
                             'recording-rule evaluation, staleness markers, sampling criteria, and transparency logs',
                             '## Working synthesis',
                             '## Current portability vs stale template vs conflicting carrier vs revoked lesson vs '
                             'sunset expiry vs mixed drift',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_drift_state`',
                             'current-portability-precedent',
                             'stale-template-precedent',
                             'conflicting-carrier-precedent',
                             'revoked-lesson-precedent',
                             'sunset-expired-precedent',
                             'mixed-precedent-drift'],
             'runbook_ref': 'wvf-0081.md',
             'prompt_id': 'PP-0134',
             'prompt_needles': ['Use `docs/10-method/wvf-0081.md`',
                                'current-portability-precedent, stale-template-precedent, '
                                'conflicting-carrier-precedent, revoked-lesson-precedent, sunset-expired-precedent, or '
                                'mixed-precedent-drift'],
             'claim_id': 'CL-0174',
             'oq_id': 'OQ-0176',
             'resolution_id': 'RS-0184',
             'trajectory_oq_id': 'OQ-0177',
             'qws_id': 'QWS-0259',
             'qws_label': 'precedent-revocation court / stale-rule registry / conflict-arbitration tribunal',
             'changelog_needles': ['wvf-0081.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_drift_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_drift_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_drift_state',
             'allowed': ['current-portability-precedent',
                         'stale-template-precedent',
                         'conflicting-carrier-precedent',
                         'revoked-lesson-precedent',
                         'sunset-expired-precedent',
                         'mixed-precedent-drift'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0081.md'],
             'excluded': ['precedent-court-by-default',
                          'stale-history-still-binds',
                          'one-conflict-needs-tribunal',
                          'revocation-means-erase-history',
                          'precedent-drift-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_portability_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_portability_witness_contract',
             'doc_path': 'docs/10-method/wvf-0079.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent-portability witnesses, '
                             'nonportable history, carrier match, template binding, counterexample only, sunset '
                             'inheritance, and mixed portability',
                             'This is the compact successor surface for `OQ-0175`.',
                             '## Practice / observation',
                             '## External pressure from validating policy bindings, ordered audit rules, recording '
                             'rules, selectors, sampling policies, and transparency logs',
                             '## Working synthesis',
                             '## Nonportable history vs carrier match vs template binding vs counterexample only vs '
                             'sunset inheritance vs mixed portability',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_portability_state`',
                             'nonportable-history-precedent',
                             'carrier-matched-precedent',
                             'template-bound-precedent',
                             'counterexample-only-precedent',
                             'sunset-inherited-precedent',
                             'mixed-precedent-portability'],
             'runbook_ref': 'wvf-0079.md',
             'prompt_id': 'PP-0132',
             'prompt_needles': ['Use `docs/10-method/wvf-0079.md`',
                                'nonportable-history-precedent, carrier-matched-precedent, template-bound-precedent, '
                                'counterexample-only-precedent, sunset-inherited-precedent, or '
                                'mixed-precedent-portability'],
             'claim_id': 'CL-0172',
             'oq_id': 'OQ-0175',
             'resolution_id': 'RS-0182',
             'trajectory_oq_id': 'OQ-0176',
             'qws_id': 'QWS-0257',
             'qws_label': 'precedent-drift court / portable-rule registry / telemetry common-law engine',
             'changelog_needles': ['wvf-0079.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_portability_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_portability_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_portability_state',
             'allowed': ['nonportable-history-precedent',
                         'carrier-matched-precedent',
                         'template-bound-precedent',
                         'counterexample-only-precedent',
                         'sunset-inherited-precedent',
                         'mixed-precedent-portability'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0079.md'],
             'excluded': ['precedent-court-by-default',
                          'history-vault-is-policy',
                          'one-appeal-binds-all',
                          'template-means-universal-rule',
                          'precedent-portability-ish']}},
 {'source_checker': 'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_governance_threshold_witness_contract.py',
  'kwargs': {'kind': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_governance_threshold_witness_contract',
             'doc_path': 'docs/10-method/wvf-0084.md',
             'doc_needles': ['# GPU replay cross-observer custody-exit appeal precedent tie-break governance-threshold '
                             'witnesses, no registry, repeated closeout failure, cross-carrier conflict, authority '
                             'split, audit retention, sunset breach, and mixed escalation',
                             'This is the compact successor surface for `OQ-0179`.',
                             '## Practice / observation',
                             '## External pressure from audit policy, finalizers, rule windows, sampling state, '
                             'admission boundaries, and transparency logs',
                             '## Working synthesis',
                             '## No registry vs repeated closeout failure vs cross-carrier conflict vs authority split '
                             'vs audit retention vs sunset breach vs mixed escalation',
                             '## Countermodels / probes',
                             '## Design consequences',
                             '## Overflow test',
                             '## Transformer-facing implication',
                             '`gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_governance_threshold_state`',
                             'no-registry-needed-tiebreak-governance',
                             'repeated-closeout-failure-tiebreak-governance',
                             'cross-carrier-conflict-tiebreak-governance',
                             'authority-split-tiebreak-governance',
                             'audit-retention-tiebreak-governance',
                             'sunset-breach-tiebreak-governance',
                             'mixed-tiebreak-governance-escalation'],
             'runbook_ref': 'wvf-0084.md',
             'prompt_id': 'PP-0137',
             'prompt_needles': ['Use `docs/10-method/wvf-0084.md`',
                                'no-registry-needed-tiebreak-governance, '
                                'repeated-closeout-failure-tiebreak-governance, '
                                'cross-carrier-conflict-tiebreak-governance, authority-split-tiebreak-governance, '
                                'audit-retention-tiebreak-governance, sunset-breach-tiebreak-governance, or '
                                'mixed-tiebreak-governance-escalation'],
             'claim_id': 'CL-0177',
             'oq_id': 'OQ-0179',
             'resolution_id': 'RS-0187',
             'trajectory_oq_id': 'OQ-0180',
             'qws_id': 'QWS-0262',
             'qws_label': 'standing tie-break registry / registry-operator authority / closeout governance court',
             'changelog_needles': ['wvf-0084.md',
                                   'check_gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_governance_threshold_witness_contract.py',
                                   'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_governance_threshold_state'],
             'family': 'gpu_replay_cross_observer_custody_exit_appeal_precedent_tiebreak_governance_threshold_state',
             'allowed': ['no-registry-needed-tiebreak-governance',
                         'repeated-closeout-failure-tiebreak-governance',
                         'cross-carrier-conflict-tiebreak-governance',
                         'authority-split-tiebreak-governance',
                         'audit-retention-tiebreak-governance',
                         'sunset-breach-tiebreak-governance',
                         'mixed-tiebreak-governance-escalation'],
             'surfaces': ['WITNESS-VOCABULARY.json', 'REVISION-RECEIPT.json', 'docs/10-method/wvf-0084.md'],
             'excluded': ['registry-by-use',
                          'priority-ledger-by-default',
                          'arbitration-court-by-closeout',
                          'permanent-precedent-by-audit',
                          'tiebreak-governance-ish']}}]
