# Locality-sized method-doc ratchet contract specs.
# Aggregated by tools/method_doc_ratchet_contract_specs.py; consumed by the batch checker.

METHOD_DOC_RATCHET_CONTRACT_SPECS_PART_1 = [{'source_checker': 'check_homing_packet_contract.py',
  'doc_path': 'docs/10-method/homing-packets-adaptive-distinguishing-probes-and-reorientation.md',
  'doc_needles': ['# Homing packets, adaptive distinguishing probes, and reorientation under ambiguity',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Identification packet vs homing packet vs sentinel panel vs witness panel',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'ambiguity class',
                  'orientation/update rule',
                  'stop or escalation condition',
                  'homing packet'],
  'prompt_runbook_needles': ['homing packet', 'ambiguity class', 'orientation/update rule']},
 {'source_checker': 'check_negative_control_handle_contract.py',
  'doc_path': 'docs/10-method/negative-control-handles-sham-packets-and-placebo-guards.md',
  'doc_needles': ['# Negative-control handles, sham packets, and placebo guards',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Negative-control handle vs observer/actuator split vs witness set',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'active handle',
                  'matched sham',
                  'expected differential signature',
                  'pass/fail rule',
                  'retire / escalate rule'],
  'prompt_runbook_needles': ['negative-control handle', 'matched sham', 'expected differential signature']},
 {'source_checker': 'check_stopping_packet_contract.py',
  'doc_path': 'docs/10-method/stopping-packets-sequential-decision-thresholds-and-commit-certificates.md',
  'doc_needles': ['# Stopping packets, sequential decision thresholds, and commit certificates',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Probe-economics packet vs stopping packet',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'ambiguity class',
                  'decision threshold or commit criterion',
                  'continuation action licensed',
                  'error / rollback posture',
                  'budget-exhaustion fallback'],
  'prompt_runbook_needles': ['stopping packet', 'commit criterion', 'budget-exhaustion fallback']},
 {'source_checker': 'check_probe_economics_contract.py',
  'doc_path': 'docs/10-method/probe-economics-value-of-information-and-budgeted-disambiguation.md',
  'doc_needles': ['# Probe economics, value of information, and budgeted disambiguation',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Identification packet vs homing packet vs probe-economics packet',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'candidate probe family',
                  'gated continuation decision',
                  'rough cost class',
                  'expected split power',
                  'nearest deferred alternative'],
  'prompt_runbook_needles': ['probe-economics packet',
                             'expected split power',
                             'nearest deferred alternative']},
 {'source_checker': 'check_blind_packet_contract.py',
  'doc_path': 'docs/10-method/blind-packets-label-scrubbed-adjudication-and-attribution-guards.md',
  'doc_needles': ['# Blind packets, label-scrubbed adjudication, and attribution guards',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Blind packet vs negative-control handle vs observer/actuator split',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'judged artifact',
                  'scrubbed or relabeled view',
                  'hidden metadata',
                  'reveal / unblinding rule',
                  'disagreement / escalation consequence'],
  'prompt_runbook_needles': ['blind packet',
                             'scrubbed or relabeled view',
                             'disagreement or escalation consequence']},
 {'source_checker': 'check_continuation_monitor_contract.py',
  'doc_path': 'docs/10-method/continuation-monitors-anytime-validity-and-public-observer-loops.md',
  'doc_needles': ['# Continuation monitors, anytime-validity pressure, and public observer loops',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Stopping packet vs continuation monitor',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'monitored property or ambiguity split',
                  'accumulating evidence state or score',
                  'update or shrink rule',
                  'reset or stitching rule',
                  'coupling to stop rule'],
  'prompt_runbook_needles': ['continuation monitor', 'reset or stitching rule', 'couples to the stop rule']},
 {'source_checker': 'check_observer_actuator_split_contract.py',
  'doc_path': 'docs/10-method/observer-actuator-splits-and-non-self-certifying-handles.md',
  'doc_needles': ['# Observer/actuator splits, non-self-certifying handles, and public observer-controller '
                  'loops',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Observer/actuator split vs continuation monitor vs control-authority packet',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'observer surface',
                  'actuator surface',
                  'allowed coupling',
                  'independent witness',
                  'self-certification risk'],
  'prompt_runbook_needles': ['observer/actuator split', 'independent witness', 'self-certification risk']},
 {'source_checker': 'check_execution_witness_contract.py',
  'doc_path': 'docs/10-method/execution-witnesses-substrate-perturbation-packets-and-runtime-variance-audits.md',
  'doc_needles': ['# Execution witnesses, substrate perturbation packets, and runtime variance audits',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Execution witness vs blind packet vs continuation margin',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'judged effect / continuation property',
                  'substrate family',
                  'fixed controls / allowed perturbation',
                  'divergence signature',
                  'rerun / escalation consequence'],
  'prompt_runbook_needles': ['execution witness', 'substrate family', 'rerun or escalation consequence']},
 {'source_checker': 'check_necessity_witness_contract.py',
  'doc_path': 'docs/10-method/necessity-witnesses-support-cores-and-ablation-ladders.md',
  'doc_needles': ['# Necessity witnesses, support cores, and ablation ladders',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Necessity witness vs conformance witness vs rewrite witness vs assistant-echo filter',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'full candidate surface',
                  'proposed support core',
                  'smallest ablation / removal family',
                  'tolerated degradation / continuation margin',
                  'prune / promote / rollback consequence'],
  'prompt_runbook_needles': ['necessity witness',
                             'full candidate surface',
                             'prune, promote, or rollback consequence']}]
