# Locality-sized method-doc ratchet contract specs.
# Aggregated by tools/method_doc_ratchet_contract_specs.py; consumed by the batch checker.

METHOD_DOC_RATCHET_CONTRACT_SPECS_PART_2 = [{'source_checker': 'check_rewrite_witness_contract.py',
  'doc_path': 'docs/10-method/rewrite-witnesses-roundtrip-packets-and-recap-authority-tests.md',
  'doc_needles': ['# Rewrite witnesses, round-trip packets, and recap-authority tests',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Rewrite witness vs assistant-echo filter vs public extract vs dependence-adjusted '
                  'witness',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'source packet / authority anchor',
                  'rewritten packet / compressed rewrite',
                  'round-trip or cross-exam witness',
                  'divergence signature',
                  'promotion / demotion / rollback consequence'],
  'prompt_runbook_needles': ['rewrite witness',
                             'source packet or authority anchor',
                             'promotion, demotion, or rollback consequence']},
 {'source_checker': 'check_reasoning_firebreak_contract.py',
  'doc_path': 'docs/10-method/reasoning-firebreaks-scratchpad-quarantine-and-public-extract-packets.md',
  'doc_needles': ['# Reasoning firebreaks, scratchpad quarantine, and public extract packets',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Reasoning firebreak vs assistant-echo filter vs blind packet vs execution witness',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'judged task / decision / continuation property',
                  'public extract / compact residue kept in canon',
                  'trace or scratchpad surface withheld / thinned / quarantined',
                  'allowed role',
                  'exposure / reinclusion / escalation consequence'],
  'prompt_runbook_needles': ['reasoning firebreak', 'public extract', 'allowed role']},
 {'source_checker': 'check_assistant_echo_filter_contract.py',
  'doc_path': 'docs/10-method/assistant-echo-filters-self-carry-omission-packets-and-history-decontamination.md',
  'doc_needles': ['# Assistant-echo filters, self-carry omission packets, and history decontamination',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Assistant-echo filter vs execution witness vs memory-store distinction',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'judged task / continuation property',
                  'kept user-side anchor / retained evidence surface',
                  'omitted or thinned assistant-side surface',
                  'invariance or gain signature',
                  'reinclusion / escalation consequence'],
  'prompt_runbook_needles': ['assistant-echo filter',
                             'kept user-side anchor',
                             'reinclusion or escalation consequence']},
 {'source_checker': 'check_conformance_witness_contract.py',
  'doc_path': 'docs/10-method/conformance-witnesses-loader-contracts-and-abi-drift-guards.md',
  'doc_needles': ['# Conformance witnesses, loader contracts, and ABI drift guards',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Conformance witness vs public hidden state vs execution witness vs rewrite witness',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'interface surface / claimed loader',
                  'supported model-wrapper-context family',
                  'minimal conformance test or metamorphic check family',
                  'non-conformance / drift signature',
                  'narrowing / demotion / fallback consequence'],
  'prompt_runbook_needles': ['conformance witness',
                             'supported model-wrapper-context family',
                             'narrowing, demotion, or fallback consequence']},
 {'source_checker': 'check_sufficiency_witness_contract.py',
  'doc_path': 'docs/10-method/sufficiency-witnesses-replay-capsules-and-core-only-reentry-trials.md',
  'doc_needles': ['# Sufficiency witnesses, replay capsules, and core-only re-entry trials',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Sufficiency witness vs necessity witness vs conformance witness vs assistant-echo '
                  'filter',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'candidate reduced packet / replay seed',
                  'core-only replay surface',
                  'fixed or withheld context family',
                  'target continuation property / tolerated degradation',
                  'reinflate / fallback / quarantine consequence'],
  'prompt_runbook_needles': ['sufficiency witness',
                             'core-only replay surface',
                             'reinflate, fallback, or quarantine consequence']},
 {'source_checker': 'check_dependence_adjusted_witness_contract.py',
  'doc_path': 'docs/10-method/dependence-adjusted-witnesses-effective-evidence-and-pseudoreplication-guards.md',
  'doc_needles': ['# Dependence-adjusted witnesses, effective evidence, and pseudo-replication guards',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Dependence-adjusted witness vs witness set vs blind packet vs continuation monitor',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'witness family / probe family',
                  'shared-origin coupling / dependence structure',
                  'effective evidence weight / discount rule',
                  'what still counts as genuinely new evidence',
                  'stop / escalation consequence'],
  'prompt_runbook_needles': ['dependence-adjusted witness',
                             'shared-origin coupling',
                             'genuinely new evidence']},
 {'source_checker': 'check_basin_fingerprint_contract.py',
  'doc_path': 'docs/10-method/basin-fingerprints-future-probe-signatures-and-same-answer-is-not-same-state.md',
  'doc_needles': ['# Basin fingerprints, future-probe signatures, and same-answer-is-not-same-state',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Basin fingerprint vs triangulation vs predictive state vs future equivalence',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'anchor continuation property / judged branch',
                  'compared loader, packet, or intervention family',
                  'fingerprint panel / future-probe signature',
                  'tolerated divergence / instability budget',
                  'narrowing / fallback / quarantine consequence'],
  'prompt_runbook_needles': ['future-probe signature',
                             'tolerated divergence or instability budget',
                             'narrowing, fallback, or quarantine consequence']},
 {'source_checker': 'check_triangulation_witness_contract.py',
  'doc_path': 'docs/10-method/triangulation-witnesses-multiloader-overlap-and-basin-checks.md',
  'doc_needles': ['# Triangulation witnesses, multi-loader overlap, and basin checks',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Triangulation witness vs conformance witness vs sufficiency witness vs rewrite witness',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'anchor continuation property / judged basin',
                  'at least two non-trivially different loader surfaces',
                  'shared support envelope / fixed execution family',
                  'expected overlap / divergence signature',
                  'narrowing / fallback / quarantine consequence'],
  'prompt_runbook_needles': ['triangulation witness',
                             'at least two non-trivially different loader surfaces',
                             'narrowing, fallback, or quarantine consequence']},
 {'source_checker': 'check_identifiability_budget_contract.py',
  'doc_path': 'docs/10-method/identifiability-budgets-probe-horizons-and-observability-frontiers.md',
  'doc_needles': ['# Identifiability budgets, probe horizons, and observability frontiers',
                  '## Practice / observation',
                  '## Working synthesis',
                  '## Identifiability budget vs basin fingerprint vs identification packet vs gauge '
                  'discipline',
                  '## Countermodels / probes',
                  '## Transformer-facing implication',
                  'judged state or mechanism claim',
                  'observable surface / public evidence family',
                  'hidden-context / wrapper assumptions',
                  'probe horizon / future family',
                  'tolerated ambiguity class / equivalence remainder',
                  'retreat / quarantine consequence'],
  'prompt_runbook_needles': ['probe horizon or future family',
                             'hidden-context or wrapper assumptions',
                             'tolerated ambiguity class or equivalence remainder']}]
