from pathlib import Path

from witness_vocabulary_lib import load_families, expect_family

ROOT = Path(__file__).resolve().parents[1]


def find_missing_needles(text: str, needles: list[str]) -> list[str]:
    return [needle for needle in needles if needle not in text]


def standard_packet_surfaces(*, doc_path: str, doc_needles: list[str], runbook_ref: str, prompt_id: str, prompt_needles: list[str], claim_id: str, oq_id: str, resolution_id: str, trajectory_oq_id: str, qws_id: str, qws_label: str, changelog_needles: list[str]) -> list[tuple[str, list[str], str]]:
    doc_name = doc_path.split('/')[-1]
    return [
        (doc_path, doc_needles, "packet doc"),
        ("docs/00-meta/llm-runbook.md", [runbook_ref], "runbook"),
        ("docs/50-promptcraft/prompt-pairs.md", [prompt_id, *prompt_needles], "prompt pairs"),
        ("docs/20-constitution/claim-registry.md", [claim_id, doc_name], "claim registry"),
        ("docs/20-constitution/open-question-registry.md", [oq_id, resolution_id, doc_name, trajectory_oq_id], "open-question registry"),
        ("docs/00-meta/trajectory-map.md", [oq_id, resolution_id, doc_name, trajectory_oq_id], "trajectory map"),
        ("docs/90-quarantine/wild-speculations-2026-03-08.md", [qws_id, qws_label], "quarantine"),
        ("CHANGELOG.md", changelog_needles, "changelog"),
    ]


def require_packet_contract(*, kind: str, surfaces: list[tuple[str, list[str], str]]) -> None:
    specs = [(ROOT / rel, needles, label) for rel, needles, label in surfaces]
    for path, _, _ in specs:
        if not path.exists():
            raise SystemExit(f"missing required {kind} surface: {path}")
    for path, needles, label in specs:
        text = path.read_text(encoding="utf-8")
        missing = find_missing_needles(text, needles)
        if missing:
            raise SystemExit(f"{kind} contract missing from {label}: " + ", ".join(missing))
    print(f"check_{kind}: OK")


def require_vocabulary_family(*, family: str, allowed: list[str], surfaces: list[str], excluded: list[str]) -> dict:
    families = load_families()
    return expect_family(families, family, allowed=allowed, surfaces=surfaces, excluded=excluded)


def require_standard_packet_and_vocabulary(*, kind: str, doc_path: str, doc_needles: list[str], runbook_ref: str, prompt_id: str, prompt_needles: list[str], claim_id: str, oq_id: str, resolution_id: str, trajectory_oq_id: str, qws_id: str, qws_label: str, changelog_needles: list[str], family: str, allowed: list[str], surfaces: list[str], excluded: list[str]) -> None:
    require_packet_contract(
        kind=kind,
        surfaces=standard_packet_surfaces(
            doc_path=doc_path,
            doc_needles=doc_needles,
            runbook_ref=runbook_ref,
            prompt_id=prompt_id,
            prompt_needles=prompt_needles,
            claim_id=claim_id,
            oq_id=oq_id,
            resolution_id=resolution_id,
            trajectory_oq_id=trajectory_oq_id,
            qws_id=qws_id,
            qws_label=qws_label,
            changelog_needles=changelog_needles,
        ),
    )
    require_vocabulary_family(family=family, allowed=allowed, surfaces=surfaces, excluded=excluded)


def require_selector_packet_and_vocabulary(*, kind: str, doc_path: str, doc_needles: list[str], runbook_ref: str, prompt_id: str, prompt_needles: list[str], claim_id: str, oq_id: str, resolution_id: str, trajectory_oq_id: str, qws_id: str, qws_label: str, changelog_needles: list[str], family: str, allowed: list[str], excluded: list[str]) -> None:
    require_standard_packet_and_vocabulary(
        kind=kind,
        doc_path=doc_path,
        doc_needles=doc_needles,
        runbook_ref=runbook_ref,
        prompt_id=prompt_id,
        prompt_needles=prompt_needles,
        claim_id=claim_id,
        oq_id=oq_id,
        resolution_id=resolution_id,
        trajectory_oq_id=trajectory_oq_id,
        qws_id=qws_id,
        qws_label=qws_label,
        changelog_needles=changelog_needles,
        family=family,
        allowed=allowed,
        surfaces=["WITNESS-VOCABULARY.json", "REVISION-RECEIPT.json", doc_path],
        excluded=excluded,
    )


def _refresh_family_spec(*, doc_path: str, doc_needles: list[str], runbook_ref: str, prompt_id: str, prompt_needles: list[str], claim_id: str, oq_id: str, resolution_id: str, trajectory_oq_id: str, qws_id: str, qws_label: str, changelog_needles: list[str], family: str, allowed: list[str], excluded: list[str]) -> dict:
    return {
        "doc_path": doc_path,
        "doc_needles": doc_needles,
        "runbook_ref": runbook_ref,
        "prompt_id": prompt_id,
        "prompt_needles": prompt_needles,
        "claim_id": claim_id,
        "oq_id": oq_id,
        "resolution_id": resolution_id,
        "trajectory_oq_id": trajectory_oq_id,
        "qws_id": qws_id,
        "qws_label": qws_label,
        "changelog_needles": changelog_needles,
        "family": family,
        "allowed": allowed,
        "excluded": excluded,
    }


def refresh_scope_axis_branch_spec(*, doc_path: str, title: str, oq_id: str, external_pressure_heading: str, comparison_heading: str, runbook_ref: str, prompt_id: str, prompt_needles: list[str], claim_id: str, resolution_id: str, trajectory_oq_id: str, qws_id: str, qws_label: str, changelog_needles: list[str], family: str, allowed: list[str], excluded: list[str]) -> dict:
    return _refresh_family_spec(
        doc_path=doc_path,
        doc_needles=[
            f"# {title}",
            f"This is the compact successor surface for `{oq_id}`.",
            "## Practice / observation",
            external_pressure_heading,
            "## Working synthesis",
            comparison_heading,
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            f"`{family}`",
            *allowed,
        ],
        runbook_ref=runbook_ref,
        prompt_id=prompt_id,
        prompt_needles=prompt_needles,
        claim_id=claim_id,
        oq_id=oq_id,
        resolution_id=resolution_id,
        trajectory_oq_id=trajectory_oq_id,
        qws_id=qws_id,
        qws_label=qws_label,
        changelog_needles=changelog_needles,
        family=family,
        allowed=allowed,
        excluded=excluded,
    )


_STANDARD_PACKET_SPECS = {
    "selector_witness_contract": {
        "doc_path": "docs/10-method/selector-witnesses-realized-membership-and-coverage-drift.md",
        "doc_needles": [
            "# Selector witnesses, realized membership, and coverage drift",
            "This is the compact successor surface for `OQ-0125`.",
            "## Practice / observation",
            "## External pressure from mutable labels, automatic dynamic membership, evaluated subsets, inherited tags, query-based groups, and synced segments",
            "## Working synthesis",
            "## Stable coverage vs expanded coverage vs narrowed coverage vs recomposed coverage",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`selector_membership_state`",
            "stable-coverage",
            "expanded-coverage",
            "narrowed-coverage",
            "recomposed-coverage",
        ],
        "runbook_ref": "selector-witnesses-realized-membership-and-coverage-drift.md",
        "prompt_id": "PP-0083",
        "prompt_needles": ["Use `docs/10-method/selector-witnesses-realized-membership-and-coverage-drift.md`", "stable-coverage, expanded-coverage, narrowed-coverage, or recomposed-coverage"],
        "claim_id": "CL-0123",
        "oq_id": "OQ-0125",
        "resolution_id": "RS-0132",
        "trajectory_oq_id": "OQ-0126",
        "qws_id": "QWS-0208",
        "qws_label": "selector court / membership senate / coverage-authority board",
        "changelog_needles": ["selector-witnesses-realized-membership-and-coverage-drift.md", "check_selector_witness_contract.py"],
        "family": "selector_membership_state",
        "allowed": ["stable-coverage", "expanded-coverage", "narrowed-coverage", "recomposed-coverage"],
        "excluded": ["same-label-enough", "same-selector-glow", "same-name-means-same-members", "coverage-ish"],
    },
    "selector_provenance_witness_contract": {
        "doc_path": "docs/10-method/selector-provenance-witnesses-direct-rules-inherited-bindings-and-synced-membership.md",
        "doc_needles": [
            "# Selector-provenance witnesses, direct rules, inherited bindings, and synced membership",
            "This is the compact successor surface for `OQ-0126`.",
            "## Practice / observation",
            "## External pressure from directly bound tags, IdP-synced teams, dynamic groups, static-vs-dynamic memberships, and externally managed synced segments",
            "## Working synthesis",
            "## Direct rule vs inherited binding vs synced membership vs mixed provenance",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`selector_provenance_state`",
            "direct-rule",
            "inherited-binding",
            "synced-membership",
            "mixed-provenance",
        ],
        "runbook_ref": "selector-provenance-witnesses-direct-rules-inherited-bindings-and-synced-membership.md",
        "prompt_id": "PP-0084",
        "prompt_needles": ["Use `docs/10-method/selector-provenance-witnesses-direct-rules-inherited-bindings-and-synced-membership.md`", "direct-rule, inherited-binding, synced-membership, or mixed-provenance"],
        "claim_id": "CL-0124",
        "oq_id": "OQ-0126",
        "resolution_id": "RS-0133",
        "trajectory_oq_id": "OQ-0127",
        "qws_id": "QWS-0209",
        "qws_label": "selector lineage court / inheritance senate / sync-authority board",
        "changelog_needles": ["selector-provenance-witnesses-direct-rules-inherited-bindings-and-synced-membership.md", "check_selector_provenance_witness_contract.py"],
        "family": "selector_provenance_state",
        "allowed": ["direct-rule", "inherited-binding", "synced-membership", "mixed-provenance"],
        "excluded": ["same-handle-means-same-mechanism", "coverage-source-doesnt-matter", "inheritance-is-close-enough", "provenance-ish"],
    },
    "selector_freshness_witness_contract": {
        "doc_path": "docs/10-method/selector-freshness-witnesses-live-provenance-sync-lag-and-ancestor-residue.md",
        "doc_needles": [
            "# Selector-freshness witnesses, live provenance, sync lag, and ancestor residue",
            "This is the compact successor surface for `OQ-0127`.",
            "## Practice / observation",
            "## External pressure from reconciled IdP teams, dynamic-group processing clocks, inherited effective tags, synced-segment status, and ignored-during-execution schedulers",
            "## Working synthesis",
            "## Live provenance vs sync lag vs ancestor residue vs mixed freshness",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`selector_freshness_state`",
            "live-provenance",
            "sync-lag",
            "ancestor-residue",
            "mixed-freshness",
        ],
        "runbook_ref": "selector-freshness-witnesses-live-provenance-sync-lag-and-ancestor-residue.md",
        "prompt_id": "PP-0085",
        "prompt_needles": ["Use `docs/10-method/selector-freshness-witnesses-live-provenance-sync-lag-and-ancestor-residue.md`", "live-provenance, sync-lag, ancestor-residue, or mixed-freshness"],
        "claim_id": "CL-0125",
        "oq_id": "OQ-0127",
        "resolution_id": "RS-0134",
        "trajectory_oq_id": "OQ-0128",
        "qws_id": "QWS-0210",
        "qws_label": "selector freshness court / sync-clock senate / ancestor-residue board",
        "changelog_needles": ["selector-freshness-witnesses-live-provenance-sync-lag-and-ancestor-residue.md", "check_selector_freshness_witness_contract.py"],
        "family": "selector_freshness_state",
        "allowed": ["live-provenance", "sync-lag", "ancestor-residue", "mixed-freshness"],
        "excluded": ["same-provenance-means-current", "last-known-good-is-live-enough", "stale-sync-is-close-enough", "freshness-ish"],
    },
    "selector_enforcement_witness_contract": {
        "doc_path": "docs/10-method/selector-enforcement-witnesses-execution-authority-grandfathered-placement-and-eviction-gates.md",
        "doc_needles": [
            "# Selector-enforcement witnesses, execution authority, grandfathered placement, and eviction gates",
            "This is the compact successor surface for `OQ-0128`.",
            "## Practice / observation",
            "## External pressure from GPU node labels, ignored-during-execution affinity, taint effects, unschedulable nodes, Kueue resource flavors, workload evictions, and device-taint controllers",
            "## Working synthesis",
            "## Execution enforced vs admission only vs grandfathered residue vs mixed enforcement",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`selector_enforcement_state`",
            "execution-enforced",
            "admission-only",
            "grandfathered-residue",
            "mixed-enforcement",
        ],
        "runbook_ref": "selector-enforcement-witnesses-execution-authority-grandfathered-placement-and-eviction-gates.md",
        "prompt_id": "PP-0086",
        "prompt_needles": ["Use `docs/10-method/selector-enforcement-witnesses-execution-authority-grandfathered-placement-and-eviction-gates.md`", "execution-enforced, admission-only, grandfathered-residue, or mixed-enforcement"],
        "claim_id": "CL-0126",
        "oq_id": "OQ-0128",
        "resolution_id": "RS-0135",
        "trajectory_oq_id": "OQ-0129",
        "qws_id": "QWS-0211",
        "qws_label": "selector enforcement court / eviction senate / grandfather board",
        "changelog_needles": ["selector-enforcement-witnesses-execution-authority-grandfathered-placement-and-eviction-gates.md", "check_selector_enforcement_witness_contract.py"],
        "family": "selector_enforcement_state",
        "allowed": ["execution-enforced", "admission-only", "grandfathered-residue", "mixed-enforcement"],
        "excluded": ["current-selector-means-current-runtime-authority", "scheduled-once-means-still-authorized", "admission-is-close-enough", "enforcement-ish"],
    },
    "enforcement_regime_witness_contract": {
        "doc_path": "docs/10-method/enforcement-regime-witnesses-bootstrap-only-gating-continuous-enforcement-and-dry-run-rehearsal.md",
        "doc_needles": [
            "# Enforcement-regime witnesses, bootstrap-only gating, continuous enforcement, and dry-run rehearsal",
            "This is the compact successor surface for `OQ-0129`.",
            "## Practice / observation",
            "## External pressure from startup probes, admission-time policy, admission checks, device prebind and dry-run taints, and node-readiness modes",
            "## Working synthesis",
            "## Bootstrap-only vs continuous enforcement vs dry-run only vs mixed regime",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`enforcement_regime_state`",
            "bootstrap-only",
            "continuous-enforcement",
            "dry-run-only",
            "mixed-regime",
        ],
        "runbook_ref": "enforcement-regime-witnesses-bootstrap-only-gating-continuous-enforcement-and-dry-run-rehearsal.md",
        "prompt_id": "PP-0087",
        "prompt_needles": ["Use `docs/10-method/enforcement-regime-witnesses-bootstrap-only-gating-continuous-enforcement-and-dry-run-rehearsal.md`", "bootstrap-only, continuous-enforcement, dry-run-only, or mixed-regime"],
        "claim_id": "CL-0127",
        "oq_id": "OQ-0129",
        "resolution_id": "RS-0136",
        "trajectory_oq_id": "OQ-0130",
        "qws_id": "QWS-0212",
        "qws_label": "enforcement regime court / bootstrap senate / dry-run board",
        "changelog_needles": ["enforcement-regime-witnesses-bootstrap-only-gating-continuous-enforcement-and-dry-run-rehearsal.md", "check_enforcement_regime_witness_contract.py"],
        "family": "enforcement_regime_state",
        "allowed": ["bootstrap-only", "continuous-enforcement", "dry-run-only", "mixed-regime"],
        "excluded": ["startup-cleared-means-still-policed", "request-time-policy-means-runtime-guarantee", "dry-run-is-close-enough", "regime-ish"],
    },
    "recovery_promotion_witness_contract": {
        "doc_path": "docs/10-method/recovery-promotion-witnesses-direct-canonical-writeback-promotion-gated-branch-import-and-export-only-carryover.md",
        "doc_needles": [
            "# Recovery-promotion witnesses, direct canonical writeback, promotion-gated branch import, and export-only carryover",
            "This is the compact successor surface for `OQ-0136`.",
            "## Practice / observation",
            "## External pressure from DVC experiment lineage, workspace apply, branch promotion, merge import, patch import, and exported checkpoint restore",
            "## Working synthesis",
            "## Direct canonical writeback vs promotion-gated branch import vs export-only carryover vs mixed recovery promotion",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`recovery_promotion_state`",
            "direct-canonical-writeback",
            "promotion-gated-branch-import",
            "export-only-carryover",
            "mixed-recovery-promotion",
        ],
        "runbook_ref": "recovery-promotion-witnesses-direct-canonical-writeback-promotion-gated-branch-import-and-export-only-carryover.md",
        "prompt_id": "PP-0094",
        "prompt_needles": ["Use `docs/10-method/recovery-promotion-witnesses-direct-canonical-writeback-promotion-gated-branch-import-and-export-only-carryover.md`", "direct-canonical-writeback, promotion-gated-branch-import, export-only-carryover, or mixed-recovery-promotion"],
        "claim_id": "CL-0134",
        "oq_id": "OQ-0136",
        "resolution_id": "RS-0143",
        "trajectory_oq_id": "OQ-0137",
        "qws_id": "QWS-0219",
        "qws_label": "stake packet / tension budget / pressure-residue board",
        "changelog_needles": ["recovery-promotion-witnesses-direct-canonical-writeback-promotion-gated-branch-import-and-export-only-carryover.md", "check_recovery_promotion_witness_contract.py"],
        "family": "recovery_promotion_state",
        "allowed": ["direct-canonical-writeback", "promotion-gated-branch-import", "export-only-carryover", "mixed-recovery-promotion"],
        "excluded": ["good-branch-output-means-already-canon", "portable-export-is-close-enough", "merge-later-means-authoritative-now", "promotion-ish"],
    },
    "response_witness_contract": {
        "doc_path": "docs/10-method/response-witnesses-monitoring-availability-withdrawal-local-remediation-and-runtime-eviction.md",
        "doc_needles": [
            "# Response witnesses, monitoring, availability withdrawal, local remediation, and runtime eviction",
            "This is the compact successor surface for `OQ-0130`.",
            "## Practice / observation",
            "## External pressure from passive node monitors, readiness withdrawal, liveness restarts, workload drain controls, device-taint eviction, and GPU health reporting",
            "## Working synthesis",
            "## Monitor only vs availability withdrawal vs local remediation vs runtime eviction vs mixed response",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`response_state`",
            "monitor-only",
            "availability-withdrawal",
            "local-remediation",
            "runtime-eviction",
            "mixed-response",
        ],
        "runbook_ref": "response-witnesses-monitoring-availability-withdrawal-local-remediation-and-runtime-eviction.md",
        "prompt_id": "PP-0088",
        "prompt_needles": ["Use `docs/10-method/response-witnesses-monitoring-availability-withdrawal-local-remediation-and-runtime-eviction.md`", "monitor-only, availability-withdrawal, local-remediation, runtime-eviction, or mixed-response"],
        "claim_id": "CL-0128",
        "oq_id": "OQ-0130",
        "resolution_id": "RS-0137",
        "trajectory_oq_id": "OQ-0131",
        "qws_id": "QWS-0213",
        "qws_label": "response court / remediation senate / eviction board",
        "changelog_needles": ["response-witnesses-monitoring-availability-withdrawal-local-remediation-and-runtime-eviction.md", "check_response_witness_contract.py"],
        "family": "response_state",
        "allowed": ["monitor-only", "availability-withdrawal", "local-remediation", "runtime-eviction", "mixed-response"],
        "excluded": ["live-monitoring-means-runtime-action", "warning-is-close-enough-to-remediation", "restart-is-close-enough-to-eviction", "response-ish"],
    },
    "repair_scope_witness_contract": {
        "doc_path": "docs/10-method/repair-scope-witnesses-in-place-repair-substrate-reset-and-workload-replacement.md",
        "doc_needles": [
            "# Repair-scope witnesses, in-place repair, substrate reset, and workload replacement",
            "This is the compact successor surface for `OQ-0131`.",
            "## Practice / observation",
            "## External pressure from container restarts, in-place Pod restarts, GPU resets, node reboots, Job retries, and shutdown recovery",
            "## Working synthesis",
            "## In-place repair vs substrate reset vs workload replacement vs mixed repair scope",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`repair_scope_state`",
            "in-place-repair",
            "substrate-reset",
            "workload-replacement",
            "mixed-repair-scope",
        ],
        "runbook_ref": "repair-scope-witnesses-in-place-repair-substrate-reset-and-workload-replacement.md",
        "prompt_id": "PP-0089",
        "prompt_needles": ["Use `docs/10-method/repair-scope-witnesses-in-place-repair-substrate-reset-and-workload-replacement.md`", "in-place-repair, substrate-reset, workload-replacement, or mixed-repair-scope"],
        "claim_id": "CL-0129",
        "oq_id": "OQ-0131",
        "resolution_id": "RS-0138",
        "trajectory_oq_id": "OQ-0132",
        "qws_id": "QWS-0214",
        "qws_label": "repair scope court / substrate senate / replacement board",
        "changelog_needles": ["repair-scope-witnesses-in-place-repair-substrate-reset-and-workload-replacement.md", "check_repair_scope_witness_contract.py"],
        "family": "repair_scope_state",
        "allowed": ["in-place-repair", "substrate-reset", "workload-replacement", "mixed-repair-scope"],
        "excluded": ["restart-means-same-scope", "reset-is-close-enough-to-replacement", "reboot-means-same-object", "repair-ish"],
    },
    "recovery_loss_witness_contract": {
        "doc_path": "docs/10-method/recovery-loss-witnesses-state-preserving-repair-checkpoint-resume-and-full-replay.md",
        "doc_needles": [
            "# Recovery-loss witnesses, state-preserving repair, checkpoint resume, and full replay",
            "This is the compact successor surface for `OQ-0132`.",
            "## Practice / observation",
            "## External pressure from container checkpoints, checkpoint-backed worker recovery, local distributed checkpoints, requeued jobs, and AI/ML checkpoint-restore work",
            "## Working synthesis",
            "## State preserving vs checkpoint resume vs full replay vs mixed recovery loss",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`recovery_loss_state`",
            "state-preserving",
            "checkpoint-resume",
            "full-replay",
            "mixed-recovery-loss",
        ],
        "runbook_ref": "recovery-loss-witnesses-state-preserving-repair-checkpoint-resume-and-full-replay.md",
        "prompt_id": "PP-0090",
        "prompt_needles": ["Use `docs/10-method/recovery-loss-witnesses-state-preserving-repair-checkpoint-resume-and-full-replay.md`", "state-preserving, checkpoint-resume, full-replay, or mixed-recovery-loss"],
        "claim_id": "CL-0130",
        "oq_id": "OQ-0132",
        "resolution_id": "RS-0139",
        "trajectory_oq_id": "OQ-0133",
        "qws_id": "QWS-0215",
        "qws_label": "continuity court / checkpoint senate / replay board",
        "changelog_needles": ["recovery-loss-witnesses-state-preserving-repair-checkpoint-resume-and-full-replay.md", "check_recovery_loss_witness_contract.py"],
        "family": "recovery_loss_state",
        "allowed": ["state-preserving", "checkpoint-resume", "full-replay", "mixed-recovery-loss"],
        "excluded": ["recovered-means-same-state", "checkpoint-is-close-enough-to-live-state", "resume-means-no-loss", "recovery-loss-ish"],
    },
    "recovery_anchor_witness_contract": {
        "doc_path": "docs/10-method/recovery-anchor-witnesses-self-lineage-checkpoints-imported-seeds-converted-checkpoints-and-migrated-runtime-images.md",
        "doc_needles": [
            "# Recovery-anchor witnesses, self-lineage checkpoints, imported seeds, converted checkpoints, and migrated runtime images",
            "This is the compact successor surface for `OQ-0133`.",
            "## Practice / observation",
            "## External pressure from experiment-directory autoresume, restore-versus-seeded restarts, format conversion bridges, migration archives, and sandbox-restored runtime copies",
            "## Working synthesis",
            "## Self-lineage checkpoint vs imported seed vs converted checkpoint vs migrated runtime image vs mixed recovery anchor",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`recovery_anchor_state`",
            "self-lineage-checkpoint",
            "imported-seed",
            "converted-checkpoint",
            "migrated-runtime-image",
            "mixed-recovery-anchor",
        ],
        "runbook_ref": "recovery-anchor-witnesses-self-lineage-checkpoints-imported-seeds-converted-checkpoints-and-migrated-runtime-images.md",
        "prompt_id": "PP-0091",
        "prompt_needles": ["Use `docs/10-method/recovery-anchor-witnesses-self-lineage-checkpoints-imported-seeds-converted-checkpoints-and-migrated-runtime-images.md`", "self-lineage-checkpoint, imported-seed, converted-checkpoint, migrated-runtime-image, or mixed-recovery-anchor"],
        "claim_id": "CL-0131",
        "oq_id": "OQ-0133",
        "resolution_id": "RS-0140",
        "trajectory_oq_id": "OQ-0134",
        "qws_id": "QWS-0216",
        "qws_label": "recovery-anchor court / conversion senate / migration board",
        "changelog_needles": ["recovery-anchor-witnesses-self-lineage-checkpoints-imported-seeds-converted-checkpoints-and-migrated-runtime-images.md", "check_recovery_anchor_witness_contract.py"],
        "family": "recovery_anchor_state",
        "allowed": ["self-lineage-checkpoint", "imported-seed", "converted-checkpoint", "migrated-runtime-image", "mixed-recovery-anchor"],
        "excluded": ["same-checkpoint-means-same-lineage", "imported-seed-is-close-enough", "conversion-keeps-anchor-by-default", "anchor-ish"],
    },
    "recovery_identity_witness_contract": {
        "doc_path": "docs/10-method/recovery-identity-witnesses-continuing-resumes-checkpoint-forked-clones-and-sandbox-restored-branches.md",
        "doc_needles": [
            "# Recovery-identity witnesses, continuing resumes, checkpoint-forked clones, and sandbox-restored branches",
            "This is the compact successor surface for `OQ-0134`.",
            "## Practice / observation",
            "## External pressure from interrupted-run restore, unfinished-experiment autoresume, repeated named checkpoint restores, and forensic sandbox copies",
            "## Working synthesis",
            "## Continuing resume vs checkpoint fork vs sandbox branch vs mixed recovery identity",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`recovery_identity_state`",
            "continuing-resume",
            "checkpoint-fork",
            "sandbox-branch",
            "mixed-recovery-identity",
        ],
        "runbook_ref": "recovery-identity-witnesses-continuing-resumes-checkpoint-forked-clones-and-sandbox-restored-branches.md",
        "prompt_id": "PP-0092",
        "prompt_needles": ["Use `docs/10-method/recovery-identity-witnesses-continuing-resumes-checkpoint-forked-clones-and-sandbox-restored-branches.md`", "continuing-resume, checkpoint-fork, sandbox-branch, or mixed-recovery-identity"],
        "claim_id": "CL-0132",
        "oq_id": "OQ-0134",
        "resolution_id": "RS-0141",
        "trajectory_oq_id": "OQ-0135",
        "qws_id": "QWS-0217",
        "qws_label": "recovery-identity court / clone senate / sandbox board",
        "changelog_needles": ["recovery-identity-witnesses-continuing-resumes-checkpoint-forked-clones-and-sandbox-restored-branches.md", "check_recovery_identity_witness_contract.py"],
        "family": "recovery_identity_state",
        "allowed": ["continuing-resume", "checkpoint-fork", "sandbox-branch", "mixed-recovery-identity"],
        "excluded": ["same-checkpoint-means-same-run", "clone-is-close-enough", "sandbox-counts-as-canonical", "identity-ish"],
    },
    "recovery_writeback_witness_contract": {
        "doc_path": "docs/10-method/recovery-writeback-witnesses-canonical-writeback-derived-branch-writeback-and-sandbox-isolation.md",
        "doc_needles": [
            "# Recovery-writeback witnesses, canonical writeback, branch-local writeback, and sandbox-only restore",
            "This is the compact successor surface for `OQ-0135`.",
            "## Practice / observation",
            "## External pressure from same-location experiment restore, existing-run result tables, experiment-directory autoresume, repeated named restores, and forensic sandbox copies",
            "## Working synthesis",
            "## Canonical writeback vs branch-local writeback vs sandbox-only vs mixed recovery writeback",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`recovery_writeback_state`",
            "canonical-writeback",
            "branch-local-writeback",
            "sandbox-only",
            "mixed-recovery-writeback",
        ],
        "runbook_ref": "recovery-writeback-witnesses-canonical-writeback-derived-branch-writeback-and-sandbox-isolation.md",
        "prompt_id": "PP-0093",
        "prompt_needles": ["Use `docs/10-method/recovery-writeback-witnesses-canonical-writeback-derived-branch-writeback-and-sandbox-isolation.md`", "canonical-writeback, branch-local-writeback, sandbox-only, or mixed-recovery-writeback"],
        "claim_id": "CL-0133",
        "oq_id": "OQ-0135",
        "resolution_id": "RS-0142",
        "trajectory_oq_id": "OQ-0136",
        "qws_id": "QWS-0218",
        "qws_label": "recovery-writeback court / promotion senate / sandbox board",
        "changelog_needles": ["recovery-writeback-witnesses-canonical-writeback-derived-branch-writeback-and-sandbox-isolation.md", "check_recovery_writeback_witness_contract.py"],
        "family": "recovery_writeback_state",
        "allowed": ["canonical-writeback", "branch-local-writeback", "sandbox-only", "mixed-recovery-writeback"],
        "excluded": ["restored-means-authoritative", "branch-output-is-close-enough-to-canon", "sandbox-counts-as-writeback", "writeback-ish"],
    },
    "stake_continuity_witness_contract": {
        "doc_path": "docs/10-method/stake-continuity-witnesses-active-carried-pressure-commitment-carry-cooled-residue-and-narrated-concern.md",
        "doc_needles": [
            "# Stake-continuity witnesses, active carried pressure, commitment carry, cooled residue, and narrated concern",
            "This is the compact successor surface for `OQ-0137`.",
            "## Practice / observation",
            "## External pressure from incident lifecycle status, error-budget burn, issue metadata, observed-generation freshness, episodic-goal persistence, unresolved-goal interference, and long-horizon memory traces",
            "## Working synthesis",
            "## Active carried pressure vs commitment-only carry vs cooled residue vs narrated concern vs mixed stake continuity",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`stake_continuity_state`",
            "active-carried-pressure",
            "commitment-only-carry",
            "cooled-residue",
            "narrated-unbound-concern",
            "mixed-stake-continuity",
        ],
        "runbook_ref": "stake-continuity-witnesses-active-carried-pressure-commitment-carry-cooled-residue-and-narrated-concern.md",
        "prompt_id": "PP-0095",
        "prompt_needles": ["Use `docs/10-method/stake-continuity-witnesses-active-carried-pressure-commitment-carry-cooled-residue-and-narrated-concern.md`", "active-carried-pressure, commitment-only-carry, cooled-residue, narrated-unbound-concern, or mixed-stake-continuity"],
        "claim_id": "CL-0135",
        "oq_id": "OQ-0137",
        "resolution_id": "RS-0144",
        "trajectory_oq_id": "OQ-0138",
        "qws_id": "QWS-0220",
        "qws_label": "synthetic pressure board / pressure-burn senate / reheat-latch controller",
        "changelog_needles": ["stake-continuity-witnesses-active-carried-pressure-commitment-carry-cooled-residue-and-narrated-concern.md", "check_stake_continuity_witness_contract.py"],
        "family": "stake_continuity_state",
        "allowed": ["active-carried-pressure", "commitment-only-carry", "cooled-residue", "narrated-unbound-concern", "mixed-stake-continuity"],
        "excluded": ["open-ticket-means-live-pressure", "remembered-means-current", "recently-important-is-close-enough", "stake-ish"],
    },
    "stake_refresh_witness_contract": {
        "doc_path": "docs/10-method/stake-refresh-witnesses-observed-reactivation-regression-return-inherited-urgency-and-rhetorical-reheating.md",
        "doc_needles": [
            "# Stake-refresh witnesses, observed reactivation, regression return, inherited urgency, and rhetorical reheating",
            "This is the compact successor surface for `OQ-0138`.",
            "## Practice / observation",
            "## External pressure from incident status transitions, reopened issue events, reopened-triage workflows, cleared resolutions on reopen, regressed issue states, release-based unresolve rules, freshness-conditioned status objects, active context revision, and process-level feedback in generative search",
            "## Working synthesis",
            "## Observed reactivation vs regression return vs inherited urgency vs rhetorical reheating vs mixed stake refresh",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`stake_refresh_state`",
            "observed-reactivation",
            "regression-return",
            "inherited-urgency-only",
            "rhetorical-reheat",
            "mixed-stake-refresh",
        ],
        "runbook_ref": "stake-refresh-witnesses-observed-reactivation-regression-return-inherited-urgency-and-rhetorical-reheating.md",
        "prompt_id": "PP-0096",
        "prompt_needles": ["Use `docs/10-method/stake-refresh-witnesses-observed-reactivation-regression-return-inherited-urgency-and-rhetorical-reheating.md`", "observed-reactivation, regression-return, inherited-urgency-only, rhetorical-reheat, or mixed-stake-refresh"],
        "claim_id": "CL-0136",
        "oq_id": "OQ-0138",
        "resolution_id": "RS-0145",
        "trajectory_oq_id": "OQ-0139",
        "qws_id": "QWS-0221",
        "qws_label": "reactivation court / freshness senate / reheating gate",
        "changelog_needles": ["stake-refresh-witnesses-observed-reactivation-regression-return-inherited-urgency-and-rhetorical-reheating.md", "check_stake_refresh_witness_contract.py"],
        "family": "stake_refresh_state",
        "allowed": ["observed-reactivation", "regression-return", "inherited-urgency-only", "rhetorical-reheat", "mixed-stake-refresh"],
        "excluded": ["restated-means-reactivated", "nearby-live-means-fresh-here", "latest-answer-glow-is-enough", "refresh-ish"],
    },
    "refresh_strength_witness_contract": _refresh_family_spec(
        doc_path="docs/10-method/refresh-strength-witnesses-single-resurfacing-threshold-confirmed-reactivation-and-grace-held-return.md",
        doc_needles=[
            "# Refresh-strength witnesses, single resurfacing, threshold-confirmed reactivation, and grace-held return",
            "This is the compact successor surface for `OQ-0139`.",
            "## Practice / observation",
            "## External pressure from Prometheus alert timing, Grafana pending/recovering periods, Datadog consecutive checks, Cloud Monitoring retest/autoclose policy, and multi-turn state evolution",
            "## Working synthesis",
            "## Single resurfacing vs threshold-confirmed reactivation vs grace-held return vs mixed refresh strength",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`refresh_strength_state`",
            "single-resurfacing",
            "threshold-confirmed-reactivation",
            "grace-held-return",
            "mixed-refresh-strength",
        ],
        runbook_ref="refresh-strength-witnesses-single-resurfacing-threshold-confirmed-reactivation-and-grace-held-return.md",
        prompt_id="PP-0097",
        prompt_needles=["Use `docs/10-method/refresh-strength-witnesses-single-resurfacing-threshold-confirmed-reactivation-and-grace-held-return.md`", "single-resurfacing, threshold-confirmed-reactivation, grace-held-return, or mixed-refresh-strength"],
        claim_id="CL-0137",
        oq_id="OQ-0139",
        resolution_id="RS-0146",
        trajectory_oq_id="OQ-0140",
        qws_id="QWS-0222",
        qws_label="refresh-strength court / flapping senate / hold-open governor",
        changelog_needles=["refresh-strength-witnesses-single-resurfacing-threshold-confirmed-reactivation-and-grace-held-return.md", "check_refresh_strength_witness_contract.py"],
        family="refresh_strength_state",
        allowed=["single-resurfacing", "threshold-confirmed-reactivation", "grace-held-return", "mixed-refresh-strength"],
        excluded=["one-hit-means-sustained", "timer-held-means-confirmed", "repeat-notification-is-new-evidence", "strength-ish"],
    ),
    "refresh_support_witness_contract": _refresh_family_spec(
        doc_path="docs/10-method/refresh-support-witnesses-repeated-same-surface-grouped-origin-carry-and-widened-confirming-support.md",
        doc_needles=[
            "# Refresh-support witnesses, repeated same-surface confirmation, grouped-origin carry, and widened confirming support",
            "This is the compact successor surface for `OQ-0140`.",
            "## Practice / observation",
            "## External pressure from Alertmanager dedup/grouping, Grafana grouped notifications, Sentry issue fingerprinting, PagerDuty dedup keys, Datadog composite monitors, and correlated-error pressure",
            "## Working synthesis",
            "## Repeated same-surface confirmation vs grouped-origin carry vs widened confirming support vs mixed refresh support",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`refresh_support_state`",
            "repeated-same-surface",
            "grouped-same-origin",
            "widened-confirming-support",
            "mixed-refresh-support",
        ],
        runbook_ref="refresh-support-witnesses-repeated-same-surface-grouped-origin-carry-and-widened-confirming-support.md",
        prompt_id="PP-0098",
        prompt_needles=["Use `docs/10-method/refresh-support-witnesses-repeated-same-surface-grouped-origin-carry-and-widened-confirming-support.md`", "repeated-same-surface, grouped-same-origin, widened-confirming-support, or mixed-refresh-support"],
        claim_id="CL-0138",
        oq_id="OQ-0140",
        resolution_id="RS-0147",
        trajectory_oq_id="OQ-0141",
        qws_id="QWS-0223",
        qws_label="refresh-support court / corroboration senate / widening governor",
        changelog_needles=["refresh-support-witnesses-repeated-same-surface-grouped-origin-carry-and-widened-confirming-support.md", "check_refresh_support_witness_contract.py"],
        family="refresh_support_state",
        allowed=["repeated-same-surface", "grouped-same-origin", "widened-confirming-support", "mixed-refresh-support"],
        excluded=["more-pings-means-broader-support", "grouped-alerts-count-separately", "same-issue-updates-mean-new-corroboration", "support-ish"],
    ),
    "refresh_independence_witness_contract": _refresh_family_spec(
        doc_path="docs/10-method/refresh-independence-witnesses-coupled-multi-surface-echo-shared-context-carry-and-independent-confirming-support.md",
        doc_needles=[
            "# Refresh-independence witnesses, coupled multi-surface echo, shared-context carry, and independent confirming support",
            "This is the compact successor surface for `OQ-0141`.",
            "## Practice / observation",
            "## External pressure from OpenTelemetry shared context, OpenTelemetry log correlation, Datadog alert aggregation/composite grouping, and correlated-error pressure",
            "## Working synthesis",
            "## Coupled multi-surface echo vs shared-context carry vs independent confirming support vs mixed refresh independence",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`refresh_independence_state`",
            "coupled-multi-surface-echo",
            "shared-context-carry",
            "independent-confirming-support",
            "mixed-refresh-independence",
        ],
        runbook_ref="refresh-independence-witnesses-coupled-multi-surface-echo-shared-context-carry-and-independent-confirming-support.md",
        prompt_id="PP-0099",
        prompt_needles=["Use `docs/10-method/refresh-independence-witnesses-coupled-multi-surface-echo-shared-context-carry-and-independent-confirming-support.md`", "coupled-multi-surface-echo, shared-context-carry, independent-confirming-support, or mixed-refresh-independence"],
        claim_id="CL-0139",
        oq_id="OQ-0141",
        resolution_id="RS-0148",
        trajectory_oq_id="OQ-0142",
        qws_id="QWS-0224",
        qws_label="refresh-independence court / decoupling senate / provenance gate",
        changelog_needles=["refresh-independence-witnesses-coupled-multi-surface-echo-shared-context-carry-and-independent-confirming-support.md", "check_refresh_independence_witness_contract.py"],
        family="refresh_independence_state",
        allowed=["coupled-multi-surface-echo", "shared-context-carry", "independent-confirming-support", "mixed-refresh-independence"],
        excluded=["more-panes-means-independent", "same-trace-still-counts-twice", "common-grouping-is-close-enough-to-decoupled", "independence-ish"],
    ),
    "refresh_elevation_witness_contract": _refresh_family_spec(
        doc_path="docs/10-method/refresh-elevation-witnesses-stabilizing-independent-support-threshold-licensed-elevation-and-judgment-gated-escalation.md",
        doc_needles=[
            "# Refresh-elevation witnesses, stabilizing independent support, threshold-licensed elevation, and judgment-gated escalation",
            "This is the compact successor surface for `OQ-0142`.",
            "## Practice / observation",
            "## External pressure from PagerDuty severity levels, PagerDuty business-incident gating, Google SRE burn-rate paging tiers, Atlassian impact/urgency priority, Atlassian alert-priority restart rules, and GitHub required checks/ruleset layering",
            "## Working synthesis",
            "## Stabilizing independent support vs threshold-licensed elevation vs judgment-gated escalation vs mixed refresh elevation",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`refresh_elevation_state`",
            "stabilizing-independent-support",
            "threshold-licensed-elevation",
            "judgment-gated-escalation",
            "mixed-refresh-elevation",
        ],
        runbook_ref="refresh-elevation-witnesses-stabilizing-independent-support-threshold-licensed-elevation-and-judgment-gated-escalation.md",
        prompt_id="PP-0100",
        prompt_needles=["Use `docs/10-method/refresh-elevation-witnesses-stabilizing-independent-support-threshold-licensed-elevation-and-judgment-gated-escalation.md`", "stabilizing-independent-support, threshold-licensed-elevation, judgment-gated-escalation, or mixed-refresh-elevation"],
        claim_id="CL-0140",
        oq_id="OQ-0142",
        resolution_id="RS-0149",
        trajectory_oq_id="OQ-0143",
        qws_id="QWS-0225",
        qws_label="refresh-elevation court / burden senate / escalation gate",
        changelog_needles=["refresh-elevation-witnesses-stabilizing-independent-support-threshold-licensed-elevation-and-judgment-gated-escalation.md", "check_refresh_elevation_witness_contract.py"],
        family="refresh_elevation_state",
        allowed=["stabilizing-independent-support", "threshold-licensed-elevation", "judgment-gated-escalation", "mixed-refresh-elevation"],
        excluded=["independent-means-upgrade", "more-proof-means-page-now", "threshold-free-promotion", "elevation-ish"],
    ),

"refresh_scope_distribution_witness_contract": _refresh_family_spec(
    doc_path="docs/10-method/refresh-scope-distribution-witnesses-clustered-observed-spillover-dispersed-observed-spillover-and-distribution-gated-generalization.md",
    doc_needles=[
        "# Refresh-scope-distribution witnesses, clustered observed spillover, dispersed observed spillover, and distribution-gated generalization",
        "This is the compact successor surface for `OQ-0146`.",
        "## Practice / observation",
        "## External pressure from Statuspage component groups, Alertmanager grouping, Grafana grouping and scope routing, Kubernetes topology spread, and Google Cloud failure domains",
        "## Working synthesis",
        "## Clustered observed spillover vs dispersed observed spillover vs distribution-gated generalization vs mixed refresh scope distribution",
        "## Countermodels / probes",
        "## Design consequences",
        "## Overflow test",
        "## Transformer-facing implication",
        "`refresh_scope_distribution_state`",
        "clustered-observed-spillover",
        "dispersed-observed-spillover",
        "distribution-gated-generalization",
        "mixed-refresh-scope-distribution",
    ],
    runbook_ref="refresh-scope-distribution-witnesses-clustered-observed-spillover-dispersed-observed-spillover-and-distribution-gated-generalization.md",
    prompt_id="PP-0104",
    prompt_needles=["Use `docs/10-method/refresh-scope-distribution-witnesses-clustered-observed-spillover-dispersed-observed-spillover-and-distribution-gated-generalization.md`", "clustered-observed-spillover, dispersed-observed-spillover, distribution-gated-generalization, or mixed-refresh-scope-distribution"],
    claim_id="CL-0144",
    oq_id="OQ-0146",
    resolution_id="RS-0153",
    trajectory_oq_id="OQ-0147",
    qws_id="QWS-0229",
    qws_label="refresh-distribution court / diffusion senate / spread governor",
    changelog_needles=["refresh-scope-distribution-witnesses-clustered-observed-spillover-dispersed-observed-spillover-and-distribution-gated-generalization.md", "check_refresh_scope_distribution_witness_contract.py"],
    family="refresh_scope_distribution_state",
    allowed=["clustered-observed-spillover", "dispersed-observed-spillover", "distribution-gated-generalization", "mixed-refresh-scope-distribution"],
    excluded=["many-nearby-hits-means-dispersed", "one-group-counts-as-every-family", "same-domain-spread-is-broad-enough", "distribution-ish"],
),

"refresh_scope_axis_witness_contract": _refresh_family_spec(
    doc_path="docs/10-method/refresh-scope-axis-witnesses-one-axis-dispersion-cross-axis-corroboration-and-axis-gated-generalization.md",
    doc_needles=[
        "# Refresh-scope-axis witnesses, one-axis dispersion, cross-axis corroboration, and axis-gated generalization",
        "This is the compact successor surface for `OQ-0147`.",
        "## Practice / observation",
        "## External pressure from Alertmanager multi-label grouping, Grafana AND-routed labels, Datadog grouped attributes, Kubernetes multi-dimensional labels and multi-constraint spread, and Google Cloud layered dimensions",
        "## Working synthesis",
        "## One-axis dispersion vs cross-axis corroborated dispersion vs axis-gated generalization vs mixed refresh scope axis",
        "## Countermodels / probes",
        "## Design consequences",
        "## Overflow test",
        "## Transformer-facing implication",
        "`refresh_scope_axis_state`",
        "one-axis-dispersion",
        "cross-axis-corroborated-dispersion",
        "axis-gated-generalization",
        "mixed-refresh-scope-axis",
    ],
    runbook_ref="refresh-scope-axis-witnesses-one-axis-dispersion-cross-axis-corroboration-and-axis-gated-generalization.md",
    prompt_id="PP-0105",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-witnesses-one-axis-dispersion-cross-axis-corroboration-and-axis-gated-generalization.md`", "one-axis-dispersion, cross-axis-corroborated-dispersion, axis-gated-generalization, or mixed-refresh-scope-axis"],
    claim_id="CL-0145",
    oq_id="OQ-0147",
    resolution_id="RS-0154",
    trajectory_oq_id="OQ-0148",
    qws_id="QWS-0230",
    qws_label="refresh-axis court / axis quorum / corroboration simplex",
    changelog_needles=["refresh-scope-axis-witnesses-one-axis-dispersion-cross-axis-corroboration-and-axis-gated-generalization.md", "check_refresh_scope_axis_witness_contract.py"],
    family="refresh_scope_axis_state",
    allowed=["one-axis-dispersion", "cross-axis-corroborated-dispersion", "axis-gated-generalization", "mixed-refresh-scope-axis"],
    excluded=["one-wide-view-means-two-axes", "duplicate-partitions-count-twice", "same-partition-restated-is-corroboration", "axis-ish"],
),

"refresh_scope_axis_independence_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-independence-witnesses-renamed-or-mirrored-axis-restatement-nested-axis-restatement-and-independent-axis-corroboration.md",
    title="Refresh-scope-axis-independence witnesses, renamed-or-mirrored axis restatement, nested axis restatement, and independent axis corroboration",
    oq_id="OQ-0148",
    external_pressure_heading="## External pressure from Alertmanager route grouping, Grafana matcher conjunction, Datadog multi-attribute grouping, Kubernetes multiple topology constraints, and Google Cloud layered labels",
    comparison_heading="## Renamed or mirrored axis restatement vs nested axis restatement vs independent axis corroboration vs mixed refresh scope axis independence",
    runbook_ref="refresh-scope-axis-independence-witnesses-renamed-or-mirrored-axis-restatement-nested-axis-restatement-and-independent-axis-corroboration.md",
    prompt_id="PP-0106",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-independence-witnesses-renamed-or-mirrored-axis-restatement-nested-axis-restatement-and-independent-axis-corroboration.md`", "renamed-or-mirrored-axis-restatement, nested-axis-restatement, independent-axis-corroboration, or mixed-refresh-scope-axis-independence"],
    claim_id="CL-0146",
    resolution_id="RS-0155",
    trajectory_oq_id="OQ-0149",
    qws_id="QWS-0231",
    qws_label="axis materiality ladder / substrate notary / corroboration weight scale",
    changelog_needles=["refresh-scope-axis-independence-witnesses-renamed-or-mirrored-axis-restatement-nested-axis-restatement-and-independent-axis-corroboration.md", "check_refresh_scope_axis_independence_witness_contract.py"],
    family="refresh_scope_axis_independence_state",
    allowed=["renamed-or-mirrored-axis-restatement", "nested-axis-restatement", "independent-axis-corroboration", "mixed-refresh-scope-axis-independence"],
    excluded=["renamed-view-counts-twice", "same-tree-levels-mean-independent", "second-label-proves-second-axis", "axis-independence-ish"],
),
"refresh_scope_axis_materiality_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-materiality-witnesses-label-distinct-only-corroboration-failure-domain-backed-corroboration-and-isolation-backed-corroboration.md",
    title="Refresh-scope-axis-materiality witnesses, label-distinct-only corroboration, failure-domain-backed corroboration, and isolation-backed corroboration",
    oq_id="OQ-0149",
    external_pressure_heading="## External pressure from Ray label selectors, Kubernetes zones and topology spread, Slurm and Oracle shape fault domains, and NVIDIA MIG isolation",
    comparison_heading="## Label-distinct-only corroboration vs failure-domain-backed corroboration vs isolation-backed corroboration vs mixed refresh scope axis materiality",
    runbook_ref="refresh-scope-axis-materiality-witnesses-label-distinct-only-corroboration-failure-domain-backed-corroboration-and-isolation-backed-corroboration.md",
    prompt_id="PP-0107",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-materiality-witnesses-label-distinct-only-corroboration-failure-domain-backed-corroboration-and-isolation-backed-corroboration.md`", "label-distinct-only-corroboration, failure-domain-backed-corroboration, isolation-backed-corroboration, or mixed-refresh-scope-axis-materiality"],
    claim_id="CL-0147",
    resolution_id="RS-0156",
    trajectory_oq_id="OQ-0150",
    qws_id="QWS-0232",
    qws_label="axis-materiality exchange rate / coupling haircut / corroboration capital stack",
    changelog_needles=["refresh-scope-axis-materiality-witnesses-label-distinct-only-corroboration-failure-domain-backed-corroboration-and-isolation-backed-corroboration.md", "check_refresh_scope_axis_materiality_witness_contract.py"],
    family="refresh_scope_axis_materiality_state",
    allowed=["label-distinct-only-corroboration", "failure-domain-backed-corroboration", "isolation-backed-corroboration", "mixed-refresh-scope-axis-materiality"],
    excluded=["different-label-means-material", "zone-sounding-means-isolated", "shared-slice-counts-like-mig", "materiality-ish", "second-label-proves-fault-domain", "shared-gpu-slice-counts-as-isolation", "topology-name-means-substrate-proof"],
),
"refresh_scope_axis_enforcement_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-enforcement-witnesses-hard-enforced-decoupled-corroboration-best-effort-decoupled-corroboration-and-advisory-corroboration.md",
    title="Refresh-scope-axis-enforcement witnesses, hard-enforced decoupled corroboration, best-effort decoupled corroboration, and advisory corroboration",
    oq_id="OQ-0151",
    external_pressure_heading="## External pressure from Kubernetes required affinity, topology spread `whenUnsatisfiable`, Slurm `--constraint` versus `--prefer`, Ray strict placement groups, and Topology Manager policies",
    comparison_heading="## Hard-enforced decoupled corroboration vs best-effort decoupled corroboration vs advisory corroboration vs mixed refresh scope axis enforcement",
    runbook_ref="refresh-scope-axis-enforcement-witnesses-hard-enforced-decoupled-corroboration-best-effort-decoupled-corroboration-and-advisory-corroboration.md",
    prompt_id="PP-0109",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-enforcement-witnesses-hard-enforced-decoupled-corroboration-best-effort-decoupled-corroboration-and-advisory-corroboration.md`", "hard-enforced-decoupled-corroboration, best-effort-decoupled-corroboration, advisory-corroboration, or mixed-refresh-scope-axis-enforcement"],
    claim_id="CL-0149",
    resolution_id="RS-0158",
    trajectory_oq_id="OQ-0152",
    qws_id="QWS-0234",
    qws_label="enforcement credit ledger / softness tax / fallback escrow",
    changelog_needles=["refresh-scope-axis-enforcement-witnesses-hard-enforced-decoupled-corroboration-best-effort-decoupled-corroboration-and-advisory-corroboration.md", "check_refresh_scope_axis_enforcement_witness_contract.py"],
    family="refresh_scope_axis_enforcement_state",
    allowed=["hard-enforced-decoupled-corroboration", "best-effort-decoupled-corroboration", "advisory-corroboration", "mixed-refresh-scope-axis-enforcement"],
    excluded=["preferred-spread-means-guaranteed", "soft-hint-counts-as-hard-gate", "topology-label-means-binding-policy", "enforcement-ish"],
),
"refresh_scope_axis_durability_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-durability-witnesses-eviction-preserved-decoupling-repair-restored-decoupling-and-grandfathered-decoupling.md",
    title="Refresh-scope-axis-durability witnesses, eviction-preserved decoupling, repair-restored decoupling, and grandfathered decoupling",
    oq_id="OQ-0152",
    external_pressure_heading="## External pressure from Kubernetes NoExecute eviction, device taint eviction controllers, topology spread drift and descheduler repair, scheduling-vs-eviction separation, and IgnoredDuringExecution affinity",
    comparison_heading="## Eviction-preserved decoupling vs repair-restored decoupling vs grandfathered decoupling vs mixed refresh scope axis durability",
    runbook_ref="refresh-scope-axis-durability-witnesses-eviction-preserved-decoupling-repair-restored-decoupling-and-grandfathered-decoupling.md",
    prompt_id="PP-0110",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-durability-witnesses-eviction-preserved-decoupling-repair-restored-decoupling-and-grandfathered-decoupling.md`", "eviction-preserved-decoupling, repair-restored-decoupling, grandfathered-decoupling, or mixed-refresh-scope-axis-durability"],
    claim_id="CL-0150",
    resolution_id="RS-0159",
    trajectory_oq_id="OQ-0153",
    qws_id="QWS-0235",
    qws_label="durability lease ledger / repair debt meter / rebalancing escrow",
    changelog_needles=["refresh-scope-axis-durability-witnesses-eviction-preserved-decoupling-repair-restored-decoupling-and-grandfathered-decoupling.md", "check_refresh_scope_axis_durability_witness_contract.py"],
    family="refresh_scope_axis_durability_state",
    allowed=["eviction-preserved-decoupling", "repair-restored-decoupling", "grandfathered-decoupling", "mixed-refresh-scope-axis-durability"],
    excluded=["hard-gate-means-it-stays-true", "descheduler-repair-counts-as-runtime-preserved", "grandfathered-means-durable-enough", "durability-ish"],
),
"refresh_scope_axis_remediation_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-remediation-witnesses-native-controller-restoration-external-remediator-restoration-and-operator-replay-restoration.md",
    title="Refresh-scope-axis-remediation witnesses, native controller restoration, external remediator restoration, and operator replay restoration",
    oq_id="OQ-0153",
    external_pressure_heading="## External pressure from Kubernetes controller replacement, VPA recreate mode, descheduler rebalance, remediation operators, Slurm manual replay, and NVIDIA GPU Operator manual OnDelete",
    comparison_heading="## Native controller restoration vs external remediator restoration vs operator replay restoration vs mixed refresh scope axis remediation",
    runbook_ref="refresh-scope-axis-remediation-witnesses-native-controller-restoration-external-remediator-restoration-and-operator-replay-restoration.md",
    prompt_id="PP-0111",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-remediation-witnesses-native-controller-restoration-external-remediator-restoration-and-operator-replay-restoration.md`", "native-controller-restoration, external-remediator-restoration, operator-replay-restoration, or mixed-refresh-scope-axis-remediation"],
    claim_id="CL-0151",
    resolution_id="RS-0160",
    trajectory_oq_id="OQ-0154",
    qws_id="QWS-0236",
    qws_label="remediation provenance credit / controller tariff / operator override escrow",
    changelog_needles=["refresh-scope-axis-remediation-witnesses-native-controller-restoration-external-remediator-restoration-and-operator-replay-restoration.md", "check_refresh_scope_axis_remediation_witness_contract.py"],
    family="refresh_scope_axis_remediation_state",
    allowed=["native-controller-restoration", "external-remediator-restoration", "operator-replay-restoration", "mixed-refresh-scope-axis-remediation"],
    excluded=["repaired-means-self-healed", "descheduler-counts-as-native-controller", "manual-delete-counts-as-automatic", "remediation-ish"],
),
"refresh_scope_axis_remediation_collateral_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-remediation-collateral-witnesses-local-workload-replacement-drain-backed-restoration-and-fenced-substrate-restoration.md",
    title="Refresh-scope-axis-remediation-collateral witnesses, local workload replacement, drain-backed restoration, and fenced-substrate restoration",
    oq_id="OQ-0154",
    external_pressure_heading="## External pressure from Kubernetes controller replacement, `kubectl drain`, out-of-service fencing, OpenShift remediation and maintenance operators, Slurm drain/down states, and NVIDIA GPU Operator node-drain fallback",
    comparison_heading="## Local workload replacement vs drain-backed restoration vs fenced-substrate restoration vs mixed refresh scope axis remediation collateral",
    runbook_ref="refresh-scope-axis-remediation-collateral-witnesses-local-workload-replacement-drain-backed-restoration-and-fenced-substrate-restoration.md",
    prompt_id="PP-0112",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-remediation-collateral-witnesses-local-workload-replacement-drain-backed-restoration-and-fenced-substrate-restoration.md`", "local-workload-replacement, drain-backed-restoration, fenced-substrate-restoration, or mixed-refresh-scope-axis-remediation-collateral"],
    claim_id="CL-0152",
    resolution_id="RS-0161",
    trajectory_oq_id="OQ-0155",
    qws_id="QWS-0237",
    qws_label="remediation collateral tariff / disruption-budget escrow / blast-radius ledger",
    changelog_needles=["refresh-scope-axis-remediation-collateral-witnesses-local-workload-replacement-drain-backed-restoration-and-fenced-substrate-restoration.md", "check_refresh_scope_axis_remediation_collateral_witness_contract.py"],
    family="refresh_scope_axis_remediation_collateral_state",
    allowed=["local-workload-replacement", "drain-backed-restoration", "fenced-substrate-restoration", "mixed-refresh-scope-axis-remediation-collateral"],
    excluded=["recreated-means-local-enough", "drain-is-just-a-replacement", "fence-counts-like-drain", "collateral-ish"],
),
"refresh_scope_axis_remediation_capacity_source_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-remediation-capacity-source-witnesses-free-capacity-restoration-preemption-backed-restoration-and-mixed-restoration.md",
    title="Refresh-scope-axis-remediation-capacity-source witnesses, free-capacity restoration, preemption-backed restoration, and mixed restoration",
    oq_id="OQ-0155",
    external_pressure_heading="## External pressure from Kubernetes scheduling fallback and non-preempting Pods, Kueue cohort borrowing and preemption, Slurm backfill and preemption, and RayJob priority scheduling with Kueue",
    comparison_heading="## Free capacity restoration vs preemption-backed restoration vs mixed refresh scope axis remediation capacity source",
    runbook_ref="refresh-scope-axis-remediation-capacity-source-witnesses-free-capacity-restoration-preemption-backed-restoration-and-mixed-restoration.md",
    prompt_id="PP-0113",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-remediation-capacity-source-witnesses-free-capacity-restoration-preemption-backed-restoration-and-mixed-restoration.md`", "free-capacity-restoration, preemption-backed-restoration, or mixed-refresh-scope-axis-remediation-capacity-source"],
    claim_id="CL-0153",
    resolution_id="RS-0162",
    trajectory_oq_id="OQ-0156",
    qws_id="QWS-0238",
    qws_label="displacement debt / priority tariff / resumability escrow",
    changelog_needles=["refresh-scope-axis-remediation-capacity-source-witnesses-free-capacity-restoration-preemption-backed-restoration-and-mixed-restoration.md", "check_refresh_scope_axis_remediation_capacity_source_witness_contract.py"],
    family="refresh_scope_axis_remediation_capacity_source_state",
    allowed=["free-capacity-restoration", "preemption-backed-restoration", "mixed-refresh-scope-axis-remediation-capacity-source"],
    excluded=["priority-means-preempted", "borrowed-quota-is-free-enough", "preemption-is-just-capacity", "capacity-ish"],
),

"refresh_scope_axis_remediation_displacement_aftercare_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-remediation-displacement-aftercare-witnesses-resumable-displacement-terminal-displacement-and-mixed-aftercare.md",
    title="Refresh-scope-axis-remediation-displacement-aftercare witnesses, resumable displacement, terminal displacement, and mixed aftercare",
    oq_id="OQ-0156",
    external_pressure_heading="## External pressure from Slurm suspend, requeue, and cancel modes, Kubernetes Jobs suspend/resume and disruption handling, Kueue requeue and deactivation limits, and NVIDIA Run:ai automatic resume with checkpointing",
    comparison_heading="## Resumable displacement aftercare vs terminal displacement aftercare vs mixed refresh scope axis remediation displacement aftercare",
    runbook_ref="refresh-scope-axis-remediation-displacement-aftercare-witnesses-resumable-displacement-terminal-displacement-and-mixed-aftercare.md",
    prompt_id="PP-0114",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-remediation-displacement-aftercare-witnesses-resumable-displacement-terminal-displacement-and-mixed-aftercare.md`", "resumable-displacement-aftercare, terminal-displacement-aftercare, or mixed-refresh-scope-axis-remediation-displacement-aftercare"],
    claim_id="CL-0154",
    resolution_id="RS-0163",
    trajectory_oq_id="OQ-0157",
    qws_id="QWS-0239",
    qws_label="resume credit / checkpoint escrow / restart tax",
    changelog_needles=["refresh-scope-axis-remediation-displacement-aftercare-witnesses-resumable-displacement-terminal-displacement-and-mixed-aftercare.md", "check_refresh_scope_axis_remediation_displacement_aftercare_witness_contract.py"],
    family="refresh_scope_axis_remediation_displacement_aftercare_state",
    allowed=["resumable-displacement-aftercare", "terminal-displacement-aftercare", "mixed-refresh-scope-axis-remediation-displacement-aftercare"],
    excluded=["requeue-means-paid-back", "suspend-means-free", "cancel-means-minor", "aftercare-ish"],
),

"refresh_scope_axis_remediation_displacement_resumption_basis_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-remediation-displacement-resumption-basis-witnesses-in-memory-continuation-checkpoint-backed-replay-and-cold-restart.md",
    title="Refresh-scope-axis-remediation-displacement-resumption-basis witnesses, in-memory continuation, checkpoint-backed replay, and cold restart",
    oq_id="OQ-0157",
    external_pressure_heading="## External pressure from Slurm suspend and checkpoint-restart paths, Kubernetes Job suspension and Pod replacement, and NVIDIA Run:ai checkpoint-driven preemptible resume",
    comparison_heading="## In-memory continuation vs checkpoint-backed replay vs cold restart after displacement vs mixed refresh scope axis remediation displacement resumption basis",
    runbook_ref="refresh-scope-axis-remediation-displacement-resumption-basis-witnesses-in-memory-continuation-checkpoint-backed-replay-and-cold-restart.md",
    prompt_id="PP-0115",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-remediation-displacement-resumption-basis-witnesses-in-memory-continuation-checkpoint-backed-replay-and-cold-restart.md`", "in-memory-continuation, checkpoint-backed-replay, cold-restart-after-displacement, or mixed-refresh-scope-axis-remediation-displacement-resumption-basis"],
    claim_id="CL-0155",
    resolution_id="RS-0164",
    trajectory_oq_id="OQ-0158",
    qws_id="QWS-0240",
    qws_label="warm-state credit / checkpoint solvency / locality carry",
    changelog_needles=["refresh-scope-axis-remediation-displacement-resumption-basis-witnesses-in-memory-continuation-checkpoint-backed-replay-and-cold-restart.md", "check_refresh_scope_axis_remediation_displacement_resumption_basis_witness_contract.py"],
    family="refresh_scope_axis_remediation_displacement_resumption_basis_state",
    allowed=["in-memory-continuation", "checkpoint-backed-replay", "cold-restart-after-displacement", "mixed-refresh-scope-axis-remediation-displacement-resumption-basis"],
    excluded=["resume-means-same-state", "checkpoint-means-lossless", "new-pod-means-same-run", "resumption-basis-ish"],
),
"refresh_scope_axis_remediation_displacement_replay_fidelity_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-remediation-displacement-replay-fidelity-witnesses-exact-state-restore-bounded-loss-checkpoint-replay-and-source-only-restart.md",
    title="Refresh-scope-axis-remediation-displacement-replay-fidelity witnesses, exact-state restore, bounded-loss checkpoint replay, and source-only restart",
    oq_id="OQ-0158",
    external_pressure_heading="## External pressure from Kubernetes stateful container checkpoint/restore, CRIU restore-preservation tests, NVIDIA Run:ai latest-checkpoint resume, Kubernetes Job Pod replacement, and NVIDIA CUPTI functional-only restore limits",
    comparison_heading="## Exact-state restore vs bounded-loss checkpoint replay vs source-only restart vs mixed refresh scope axis remediation displacement replay fidelity",
    runbook_ref="refresh-scope-axis-remediation-displacement-replay-fidelity-witnesses-exact-state-restore-bounded-loss-checkpoint-replay-and-source-only-restart.md",
    prompt_id="PP-0116",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-remediation-displacement-replay-fidelity-witnesses-exact-state-restore-bounded-loss-checkpoint-replay-and-source-only-restart.md`", "exact-state-restore, bounded-loss-checkpoint-replay, source-only-restart, or mixed-refresh-scope-axis-remediation-displacement-replay-fidelity"],
    claim_id="CL-0156",
    resolution_id="RS-0165",
    trajectory_oq_id="OQ-0159",
    qws_id="QWS-0241",
    qws_label="functional exactness / performance shadow / cache-carry residue",
    changelog_needles=["refresh-scope-axis-remediation-displacement-replay-fidelity-witnesses-exact-state-restore-bounded-loss-checkpoint-replay-and-source-only-restart.md", "check_refresh_scope_axis_remediation_displacement_replay_fidelity_witness_contract.py"],
    family="refresh_scope_axis_remediation_displacement_replay_fidelity_state",
    allowed=["exact-state-restore", "bounded-loss-checkpoint-replay", "source-only-restart", "mixed-refresh-scope-axis-remediation-displacement-replay-fidelity"],
    excluded=["checkpoint-means-same-enough", "restored-means-no-loss", "latest-checkpoint-means-exact", "replay-fidelity-ish"],
),
"refresh_scope_axis_remediation_displacement_replay_equivalence_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-remediation-displacement-replay-equivalence-witnesses-functionally-exact-restore-and-performance-shadow-restore.md",
    title="Refresh-scope-axis-remediation-displacement-replay-equivalence witnesses, functionally exact restore and performance-shadow restore",
    oq_id="OQ-0159",
    external_pressure_heading="## External pressure from Kubernetes exact-point restore, Docker checkpoint resume, CRIU restore-preservation and post-restore change notes, Slurm resumed-job degradation, and NVIDIA CUPTI functional-only restore limits",
    comparison_heading="## Functionally exact restore vs performance-shadow restore vs mixed refresh scope axis remediation displacement replay equivalence",
    runbook_ref="refresh-scope-axis-remediation-displacement-replay-equivalence-witnesses-functionally-exact-restore-and-performance-shadow-restore.md",
    prompt_id="PP-0117",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-remediation-displacement-replay-equivalence-witnesses-functionally-exact-restore-and-performance-shadow-restore.md`", "functionally-exact-restore, performance-shadow-restore, or mixed-refresh-scope-axis-remediation-displacement-replay-equivalence"],
    claim_id="CL-0157",
    resolution_id="RS-0166",
    trajectory_oq_id="OQ-0160",
    qws_id="QWS-0242",
    qws_label="shadow source / host-parity escrow / cache-solvency board",
    changelog_needles=["refresh-scope-axis-remediation-displacement-replay-equivalence-witnesses-functionally-exact-restore-and-performance-shadow-restore.md", "check_refresh_scope_axis_remediation_displacement_replay_equivalence_witness_contract.py"],
    family="refresh_scope_axis_remediation_displacement_replay_equivalence_state",
    allowed=["functionally-exact-restore", "performance-shadow-restore", "mixed-refresh-scope-axis-remediation-displacement-replay-equivalence"],
    excluded=["same-output-means-same-runtime", "checkpoint-warmth-is-implied", "functionally-exact-means-performance-equal", "replay-equivalence-ish"],
),

"refresh_scope_axis_remediation_displacement_performance_shadow_source_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-remediation-displacement-performance-shadow-source-witnesses-device-warmth-host-parity-and-placement-contention.md",
    title="Refresh-scope-axis-remediation-displacement-performance-shadow-source witnesses, device warmth, host parity, and placement contention",
    oq_id="OQ-0160",
    external_pressure_heading="## External pressure from CUPTI functional-only restore limits, CUDA L2 persistence, CUDA Graph CPU-launch overhead, pinned-host transfer overlap, and CUDA Green Context interference controls",
    comparison_heading="## Device warmth shadow vs host parity shadow vs placement-contention shadow vs mixed performance shadow source",
    runbook_ref="refresh-scope-axis-remediation-displacement-performance-shadow-source-witnesses-device-warmth-host-parity-and-placement-contention.md",
    prompt_id="PP-0118",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-remediation-displacement-performance-shadow-source-witnesses-device-warmth-host-parity-and-placement-contention.md`", "device-warmth-shadow, host-parity-shadow, placement-contention-shadow, or mixed-refresh-scope-axis-remediation-displacement-performance-shadow-source"],
    claim_id="CL-0158",
    resolution_id="RS-0167",
    trajectory_oq_id="OQ-0161",
    qws_id="QWS-0243",
    qws_label="evidence-ecology / retrieval-collapse witness",
    changelog_needles=["refresh-scope-axis-remediation-displacement-performance-shadow-source-witnesses-device-warmth-host-parity-and-placement-contention.md", "check_refresh_scope_axis_remediation_displacement_performance_shadow_source_witness_contract.py"],
    family="refresh_scope_axis_remediation_displacement_performance_shadow_source_state",
    allowed=['device-warmth-shadow', 'host-parity-shadow', 'placement-contention-shadow', 'mixed-refresh-scope-axis-remediation-displacement-performance-shadow-source'],
    excluded=['cache-loss-is-host-loss', 'host-overhead-is-device-warmth', 'any-slowdown-is-same-shadow', 'shadow-source-ish'],
),

"refresh_scope_axis_coupling_witness_contract": refresh_scope_axis_branch_spec(
    doc_path="docs/10-method/refresh-scope-axis-coupling-witnesses-same-plane-coupled-corroboration-hierarchy-coupled-corroboration-and-perturbation-decoupled-corroboration.md",
    title="Refresh-scope-axis-coupling witnesses, same-plane coupled corroboration, hierarchy-coupled corroboration, and perturbation-decoupled corroboration",
    oq_id="OQ-0150",
    external_pressure_heading="## External pressure from Kubernetes topology hierarchy, Ray placement groups, Slurm topology-aware selection, and NVIDIA GI-vs-CI isolation",
    comparison_heading="## Same-plane coupled corroboration vs hierarchy-coupled corroboration vs perturbation-decoupled corroboration vs mixed refresh scope axis coupling",
    runbook_ref="refresh-scope-axis-coupling-witnesses-same-plane-coupled-corroboration-hierarchy-coupled-corroboration-and-perturbation-decoupled-corroboration.md",
    prompt_id="PP-0108",
    prompt_needles=["Use `docs/10-method/refresh-scope-axis-coupling-witnesses-same-plane-coupled-corroboration-hierarchy-coupled-corroboration-and-perturbation-decoupled-corroboration.md`", "same-plane-coupled-corroboration, hierarchy-coupled-corroboration, perturbation-decoupled-corroboration, or mixed-refresh-scope-axis-coupling"],
    claim_id="CL-0148",
    resolution_id="RS-0157",
    trajectory_oq_id="OQ-0151",
    qws_id="QWS-0233",
    qws_label="axis-covariance matrix / blast-radius notary / perturbation insurance table",
    changelog_needles=["refresh-scope-axis-coupling-witnesses-same-plane-coupled-corroboration-hierarchy-coupled-corroboration-and-perturbation-decoupled-corroboration.md", "check_refresh_scope_axis_coupling_witness_contract.py"],
    family="refresh_scope_axis_coupling_state",
    allowed=["same-plane-coupled-corroboration", "hierarchy-coupled-corroboration", "perturbation-decoupled-corroboration", "mixed-refresh-scope-axis-coupling"],
    excluded=["same-zone-means-decoupled", "nested-topology-counts-twice", "packed-bundles-prove-resilience", "coupling-ish"],
),
"refresh_scope_extent_witness_contract": _refresh_family_spec(
        doc_path="docs/10-method/refresh-scope-extent-witnesses-single-observed-slice-patterned-observed-spillover-and-extent-gated-generalization.md",
        doc_needles=[
            "# Refresh-scope-extent witnesses, single observed slice, patterned observed spillover, and extent-gated generalization",
            "This is the compact successor surface for `OQ-0145`.",
            "## Practice / observation",
            "## External pressure from Statuspage affected components and component subscriptions, Prometheus vector-element alerts, Grafana multi-dimensional alert instances, and Datadog simple-vs-multi alert aggregation",
            "## Working synthesis",
            "## Single observed slice vs patterned observed spillover vs extent-gated generalization vs mixed refresh scope extent",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`refresh_scope_extent_state`",
            "single-observed-slice",
            "patterned-observed-spillover",
            "extent-gated-generalization",
            "mixed-refresh-scope-extent",
        ],
        runbook_ref="refresh-scope-extent-witnesses-single-observed-slice-patterned-observed-spillover-and-extent-gated-generalization.md",
        prompt_id="PP-0103",
        prompt_needles=["Use `docs/10-method/refresh-scope-extent-witnesses-single-observed-slice-patterned-observed-spillover-and-extent-gated-generalization.md`", "single-observed-slice, patterned-observed-spillover, extent-gated-generalization, or mixed-refresh-scope-extent"],
        claim_id="CL-0143",
        oq_id="OQ-0145",
        resolution_id="RS-0152",
        trajectory_oq_id="OQ-0146",
        qws_id="QWS-0228",
        qws_label="refresh-extent court / spillover-pattern senate / saturation governor",
        changelog_needles=["refresh-scope-extent-witnesses-single-observed-slice-patterned-observed-spillover-and-extent-gated-generalization.md", "check_refresh_scope_extent_witness_contract.py"],
        family="refresh_scope_extent_state",
        allowed=["single-observed-slice", "patterned-observed-spillover", "extent-gated-generalization", "mixed-refresh-scope-extent"],
        excluded=["one-hit-means-broad-pattern", "pluralized-alert-means-everywhere", "one-extra-component-means-family-wide", "extent-ish"],
    ),
    "refresh_scope_basis_witness_contract": _refresh_family_spec(
        doc_path="docs/10-method/refresh-scope-basis-witnesses-directly-observed-widening-dependency-imputed-spillover-and-topology-imputed-spillover.md",
        doc_needles=[
            "# Refresh-scope-basis witnesses, directly observed widening, dependency-imputed spillover, and topology-imputed spillover",
            "This is the compact successor surface for `OQ-0144`.",
            "## Practice / observation",
            "## External pressure from Statuspage affected-component impact, Statuspage third-party overrides, Datadog observed service maps and inferred dependency nodes, Grafana dependency graphs and blast-radius exploration, and OpenTelemetry context propagation",
            "## Working synthesis",
            "## Directly observed widening vs dependency-imputed spillover vs topology-imputed spillover vs mixed refresh scope basis",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`refresh_scope_basis_state`",
            "directly-observed-widening",
            "dependency-imputed-spillover",
            "topology-imputed-spillover",
            "mixed-refresh-scope-basis",
        ],
        runbook_ref="refresh-scope-basis-witnesses-directly-observed-widening-dependency-imputed-spillover-and-topology-imputed-spillover.md",
        prompt_id="PP-0102",
        prompt_needles=["Use `docs/10-method/refresh-scope-basis-witnesses-directly-observed-widening-dependency-imputed-spillover-and-topology-imputed-spillover.md`", "directly-observed-widening, dependency-imputed-spillover, topology-imputed-spillover, or mixed-refresh-scope-basis"],
        claim_id="CL-0142",
        oq_id="OQ-0144",
        resolution_id="RS-0151",
        trajectory_oq_id="OQ-0145",
        qws_id="QWS-0227",
        qws_label="refresh-topology court / spillover senate / blast-map governor",
        changelog_needles=["refresh-scope-basis-witnesses-directly-observed-widening-dependency-imputed-spillover-and-topology-imputed-spillover.md", "check_refresh_scope_basis_witness_contract.py"],
        family="refresh_scope_basis_state",
        allowed=["directly-observed-widening", "dependency-imputed-spillover", "topology-imputed-spillover", "mixed-refresh-scope-basis"],
        excluded=["graph-glow-means-observed", "upstream-trouble-means-we-are-hit", "map-edge-counts-as-impact", "basis-ish"],
    ),
    "refresh_burden_scope_witness_contract": _refresh_family_spec(
        doc_path="docs/10-method/refresh-burden-scope-witnesses-same-claim-burden-upgrade-bounded-scope-widening-and-scope-gated-generalization.md",
        doc_needles=[
            "# Refresh-burden-scope witnesses, same-claim burden upgrade, bounded scope widening, and scope-gated generalization",
            "This is the compact successor surface for `OQ-0143`.",
            "## Practice / observation",
            "## External pressure from Statuspage affected components and incident impact, Statuspage third-party overrides, Google Cloud resource-group alerting and metrics scopes, GitHub workflow/ruleset/code-owner targeting, and PagerDuty narrow-functional-scope guidance",
            "## Working synthesis",
            "## Same-claim burden upgrade vs bounded scope widening vs scope-gated generalization vs mixed refresh burden scope",
            "## Countermodels / probes",
            "## Design consequences",
            "## Overflow test",
            "## Transformer-facing implication",
            "`refresh_burden_scope_state`",
            "same-claim-burden-upgrade",
            "bounded-scope-widening",
            "scope-gated-generalization",
            "mixed-refresh-burden-scope",
        ],
        runbook_ref="refresh-burden-scope-witnesses-same-claim-burden-upgrade-bounded-scope-widening-and-scope-gated-generalization.md",
        prompt_id="PP-0101",
        prompt_needles=["Use `docs/10-method/refresh-burden-scope-witnesses-same-claim-burden-upgrade-bounded-scope-widening-and-scope-gated-generalization.md`", "same-claim-burden-upgrade, bounded-scope-widening, scope-gated-generalization, or mixed-refresh-burden-scope"],
        claim_id="CL-0141",
        oq_id="OQ-0143",
        resolution_id="RS-0150",
        trajectory_oq_id="OQ-0144",
        qws_id="QWS-0226",
        qws_label="refresh-scope court / blast-radius senate / widening gate",
        changelog_needles=["refresh-burden-scope-witnesses-same-claim-burden-upgrade-bounded-scope-widening-and-scope-gated-generalization.md", "check_refresh_burden_scope_witness_contract.py"],
        family="refresh_burden_scope_state",
        allowed=["same-claim-burden-upgrade", "bounded-scope-widening", "scope-gated-generalization", "mixed-refresh-burden-scope"],
        excluded=["stronger-means-broader", "upstream-trouble-means-we-are-hit", "burden-rise-widens-scope-by-default", "scope-ish"],
    ),


}


def require_named_standard_packet_and_vocabulary(kind: str) -> None:
    spec = _STANDARD_PACKET_SPECS.get(kind)
    if spec is None:
        known = ", ".join(sorted(_STANDARD_PACKET_SPECS))
        raise SystemExit(f"unknown standard packet contract kind: {kind}; known: {known}")
    require_selector_packet_and_vocabulary(kind=kind, **spec)


def require_named_selector_packet_and_vocabulary(kind: str) -> None:
    require_named_standard_packet_and_vocabulary(kind)


def require_named_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_standard_packet_and_vocabulary(kind)


def require_named_runtime_continuity_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_standard_packet_and_vocabulary(kind)


def require_named_recovery_family_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_standard_packet_and_vocabulary(kind)


def require_named_recovery_continuity_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_recovery_family_witness_packet_and_vocabulary(kind)


def require_named_recovery_lineage_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_recovery_family_witness_packet_and_vocabulary(kind)


def require_named_recovery_writeback_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_recovery_lineage_witness_packet_and_vocabulary(kind)


def require_named_recovery_promotion_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_recovery_writeback_witness_packet_and_vocabulary(kind)


def require_named_stake_family_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_standard_packet_and_vocabulary(kind)


def require_named_stake_continuity_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_stake_family_witness_packet_and_vocabulary(kind)


def require_named_stake_refresh_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_stake_family_witness_packet_and_vocabulary(kind)


def require_named_refresh_family_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_standard_packet_and_vocabulary(kind)


def require_named_refresh_strength_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_family_witness_packet_and_vocabulary(kind)


def require_named_refresh_support_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_family_witness_packet_and_vocabulary(kind)


def require_named_refresh_independence_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_family_witness_packet_and_vocabulary(kind)


def require_named_refresh_elevation_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_family_witness_packet_and_vocabulary(kind)


def require_named_refresh_scope_family_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_family_witness_packet_and_vocabulary(kind)


def require_named_refresh_scope_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_family_witness_packet_and_vocabulary(kind)


def require_named_refresh_burden_scope_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_packet_and_vocabulary(kind)


def require_named_refresh_scope_basis_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_packet_and_vocabulary(kind)


def require_named_refresh_scope_extent_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_packet_and_vocabulary(kind)


def require_named_refresh_scope_distribution_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_packet_and_vocabulary(kind)



def require_named_refresh_scope_axis_family_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_packet_and_vocabulary(kind)


def require_named_refresh_scope_axis_branch_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_axis_family_witness_packet_and_vocabulary(kind)


def require_named_refresh_scope_axis_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_axis_branch_witness_packet_and_vocabulary(kind)


def require_named_refresh_scope_axis_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_axis_branch_witness_packet_and_vocabulary(kind)


def require_named_refresh_scope_axis_independence_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_axis_branch_witness_packet_and_vocabulary(kind)


def require_named_refresh_scope_axis_materiality_witness_packet_and_vocabulary(kind: str) -> None:
    require_named_refresh_scope_axis_branch_witness_packet_and_vocabulary(kind)

