from __future__ import annotations

from pathlib import Path

import yaml
from typer.testing import CliRunner

from vhk.cli import app


runner = CliRunner()


def _make_project(tmp_path: Path) -> Path:
    proj = tmp_path / "p"
    (proj / "macros").mkdir(parents=True)

    (proj / "macros" / "sig.yaml").write_text(
        yaml.safe_dump(
            {
                "name": "sig",
                "steps": [
                    {"type": "Return", "value_expr": '"OK"', "out_var": "return_value"},
                ],
            }
        )
    )

    (proj / "project.yaml").write_text(
        yaml.safe_dump(
            {
                "name": "p",
                "macros": {"sig": "macros/sig.yaml"},
                "bindings": [
                    {
                        "keys": "Mod4+Shift+P",
                        "macro": "sig",
                        "description": "Global launch",
                    },
                    {
                        "keys": "Control+Alt+K",
                        "macro": "sig",
                        "description": "Scoped launch",
                        "when": {"class": "Firefox", "title": "Inbox"},
                        "vars": {"x": 1},
                    },
                ],
            }
        )
    )
    return proj


def _load_yaml_payload(text: str) -> dict:
    yaml_text = "\n".join(line for line in text.splitlines() if not line.startswith("#"))
    return yaml.safe_load(yaml_text) or {}


def test_gen_xremap_config_emits_keymaps_and_scoped_filters(tmp_path: Path):
    proj = _make_project(tmp_path)
    result = runner.invoke(app, ["gen-xremap-config", str(proj)])
    assert result.exit_code == 0, result.output

    text = result.output
    assert "# Generated by: vhk gen-xremap-config" in text

    payload = _load_yaml_payload(text)
    assert "keymap" in payload
    assert len(payload["keymap"]) == 2

    scoped = payload["keymap"][0]
    generic = payload["keymap"][1]

    assert scoped["name"] == "Scoped launch"
    assert scoped["exact_match"] is True
    assert scoped["application"]["only"] == "Firefox"
    assert scoped["window"]["only"] == "/^Inbox$/"
    assert "C-Alt-k" in scoped["remap"]
    launch = scoped["remap"]["C-Alt-k"]["launch"]
    assert launch[0] == "vhk"
    assert "--vars" in launch
    assert '"x": 1' in launch[launch.index("--vars") + 1]
    assert "--require-window" in launch
    assert "Firefox" in launch[launch.index("--require-window") + 1]

    assert generic["name"] == "Global launch"
    assert generic["exact_match"] is True
    assert "SUPER-Shift-p" in generic["remap"]


def test_gen_xremap_config_optional_timing_knobs(tmp_path: Path):
    proj = _make_project(tmp_path)
    result = runner.invoke(app, ["gen-xremap-config", str(proj), "--keypress-delay-ms", "12", "--throttle-ms", "18", "--superset-match"])
    assert result.exit_code == 0, result.output
    payload = _load_yaml_payload(result.output)
    assert payload["keypress_delay_ms"] == 12
    assert payload["throttle_ms"] == 18
    assert "exact_match" not in payload["keymap"][0]


def test_gen_xremap_config_supports_regex_app_and_title_filters(tmp_path: Path):
    proj = tmp_path / "p_regex"
    (proj / "macros").mkdir(parents=True)
    (proj / "macros" / "sig.yaml").write_text(
        yaml.safe_dump(
            {
                "name": "sig",
                "steps": [{"type": "Return", "value_expr": '"OK"', "out_var": "return_value"}],
            }
        )
    )
    (proj / "project.yaml").write_text(
        yaml.safe_dump(
            {
                "name": "p_regex",
                "macros": {"sig": "macros/sig.yaml"},
                "bindings": [
                    {
                        "keys": "Mod4+Shift+P",
                        "macro": "sig",
                        "description": "Regex scoped launch",
                        "when": {
                            "app_id": "firefox|zen",
                            "app_id_regex": True,
                            "title": "Inbox .*",
                            "title_regex": True,
                        },
                    }
                ],
            }
        )
    )

    result = runner.invoke(app, ["gen-xremap-config", str(proj)])
    assert result.exit_code == 0, result.output
    payload = _load_yaml_payload(result.output)
    scoped = payload["keymap"][0]
    assert scoped["application"]["only"] == "/firefox|zen/"
    assert scoped["window"]["only"] == "/Inbox .*/"
