from __future__ import annotations

import json
import shlex
from pathlib import Path
from typing import Any

from vhk.project.loader import load_project
from vhk.project.strategy import summarize_project_strategy


def _write_if_allowed(path: Path, content: bytes | str, *, force: bool) -> None:
    if path.exists() and not force:
        raise ValueError(f"Refusing to overwrite existing file: {path}. Use --force.")
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content)


def _trim_items(items: list[dict[str, Any]] | None, limit: int = 5) -> list[dict[str, Any]]:
    return [dict(item) for item in list(items or [])[:limit] if isinstance(item, dict)]


def _first_text(item: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = item.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def _render_artifact_summary(item: Any) -> str:
    if isinstance(item, str):
        return item
    if isinstance(item, dict):
        title = str(item.get("title") or item.get("id") or "artifact")
        path_hint = str(item.get("path_hint") or item.get("install_hint") or "").strip()
        if path_hint:
            return f"{title} (`{path_hint}`)"
        return title
    return str(item)


def _dedupe_keep_order(values: list[str]) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for raw in values:
        item = str(raw or "").strip()
        if not item or item in seen:
            continue
        seen.add(item)
        out.append(item)
    return out


def build_verification_plan(
    project_dir: Path,
    *,
    capability_usage: dict[str, list[dict[str, object]]] | None = None,
    capability_matrix: dict[str, object] | None = None,
    capability_issues: list[dict[str, object]] | None = None,
) -> dict[str, Any]:
    """Load a VHK project and emit a planner-backed verification payload."""

    project = load_project(project_dir)
    return summarize_project_strategy(
        project,
        capability_usage=capability_usage,
        capability_matrix=capability_matrix,
        capability_issues=capability_issues,
    )



def render_verification_guide(plan: dict[str, Any]) -> str:
    project = dict(plan.get("project") or {})
    overview = dict(plan.get("overview") or {})
    deployable_surfaces = _trim_items(plan.get("deployable_surfaces"), limit=6)
    setup_recipes = _trim_items(plan.get("setup_recipes"), limit=6)
    verification_gates = _trim_items(plan.get("verification_gates"), limit=8)
    toolchain_choices = _trim_items(plan.get("toolchain_choices"), limit=5)
    implementation_waves = _trim_items(plan.get("implementation_waves"), limit=5)
    session_capabilities = dict(plan.get("session_capabilities") or {})
    session_issues = list(plan.get("session_issues") or [])

    lines: list[str] = []
    lines.append(f"# VHK verification guide for {project.get('name') or 'project'}")
    lines.append("")
    lines.append("Generated by `vhk gen-verification-pack` from the same planner used by `vhk plan-project`.")
    if session_capabilities:
        lines.append("This guide is session-aware: release gates are rendered against the current desktop capability matrix so shipping review can happen against a real target.")
    else:
        lines.append("This guide is capability-agnostic: rerun it with session checks on the target desktop before shipping so the release pack matches reality.")
    lines.append("")

    lines.append("## Project snapshot")
    lines.append("")
    lines.append(f"- Root: `{project.get('root_dir') or '.'}`")
    lines.append(f"- Desktop backend: `{project.get('desktop_backend') or 'unknown'}`")
    lines.append(f"- Macros: {overview.get('macros', 0)}")
    lines.append(f"- Bindings: {overview.get('bindings', 0)}")
    lines.append(f"- Hotstrings: {overview.get('hotstrings', 0)}")
    lines.append(f"- Clipboard watchers: {overview.get('clipboard_watchers', 0)}")
    lines.append(f"- Window watchers: {overview.get('window_watchers', 0)}")
    lines.append("")

    if deployable_surfaces:
        lines.append("## Surfaces that must be proven")
        lines.append("")
        for item in deployable_surfaces:
            title = item.get("title") or item.get("id") or "surface"
            lines.append(f"### {title}")
            summary = _first_text(item, "summary", "why", "description", "notes")
            if summary:
                lines.append(summary)
            artifacts = list(item.get("artifacts") or [])
            if artifacts:
                lines.append("")
                lines.append("Representative artifacts:")
                for artifact in artifacts[:5]:
                    lines.append(f"- {_render_artifact_summary(artifact)}")
            generator_commands = list(item.get("generator_commands") or [])
            if generator_commands:
                lines.append("")
                lines.append("Generator commands:")
                for cmd in generator_commands[:4]:
                    lines.append(f"- `{cmd}`")
            lines.append("")

    if setup_recipes:
        lines.append("## Installation seams to rehearse")
        lines.append("")
        for item in setup_recipes:
            title = item.get("title") or item.get("id") or "recipe"
            lines.append(f"### {title}")
            summary = _first_text(item, "summary", "why", "description", "notes")
            if summary:
                lines.append(summary)
            install_steps = list(item.get("install_steps") or [])
            if install_steps:
                lines.append("")
                lines.append("Install steps:")
                for step in install_steps[:6]:
                    lines.append(f"- {step}")
            verify_steps = list(item.get("verify_steps") or [])
            if verify_steps:
                lines.append("")
                lines.append("Rehearsal checks:")
                for step in verify_steps[:5]:
                    lines.append(f"- {step}")
            rollback_steps = list(item.get("rollback_steps") or [])
            if rollback_steps:
                lines.append("")
                lines.append("Rollback / disable path:")
                for step in rollback_steps[:4]:
                    lines.append(f"- {step}")
            lines.append("")

    if verification_gates:
        lines.append("## Shipping gates")
        lines.append("")
        for item in verification_gates:
            title = item.get("title") or item.get("id") or "gate"
            lines.append(f"### {title}")
            summary = _first_text(item, "summary", "why", "description", "notes")
            if summary:
                lines.append(summary)
            checks = list(item.get("acceptance_checks") or item.get("checks") or [])
            if checks:
                lines.append("")
                lines.append("Acceptance checks:")
                for check in checks[:6]:
                    lines.append(f"- {check}")
            commands = list(item.get("commands") or [])
            if commands:
                lines.append("")
                lines.append("Commands:")
                for cmd in commands[:5]:
                    lines.append(f"- `{cmd}`")
            fallback_paths = list(item.get("fallback_paths") or [])
            if fallback_paths:
                lines.append("")
                lines.append("Fallback paths:")
                for path in fallback_paths[:4]:
                    lines.append(f"- {path}")
            lines.append("")

    if toolchain_choices:
        lines.append("## Toolchains worth validating explicitly")
        lines.append("")
        for item in toolchain_choices:
            title = item.get("title") or item.get("id") or "choice"
            summary = _first_text(item, "summary", "why", "description", "notes")
            if summary:
                lines.append(f"- **{title}** — {summary}")
            else:
                lines.append(f"- **{title}**")
        lines.append("")

    if implementation_waves:
        lines.append("## Delivery order behind the gates")
        lines.append("")
        for item in implementation_waves:
            title = item.get("title") or item.get("id") or "wave"
            order = item.get("order")
            label = f"Wave {order}: {title}" if order is not None else str(title)
            summary = _first_text(item, "objective", "summary", "why_now", "description", "notes")
            if summary:
                lines.append(f"- **{label}** — {summary}")
            else:
                lines.append(f"- **{label}**")
        lines.append("")

    lines.append("## Suggested commands")
    lines.append("")
    lines.append("```bash")
    lines.append("vhk doctor --json")
    lines.append("vhk validate . --json")
    lines.append("vhk plan-project . --json")
    lines.append("vhk gen-verification-pack . --force")
    lines.append("sh scripts/vhk_verify_release.sh")
    lines.append("```")
    lines.append("")

    if session_issues:
        lines.append("## Current session warnings")
        lines.append("")
        for item in session_issues[:8]:
            message = str(item.get("message") or item.get("summary") or "session issue")
            suggestion = str(item.get("suggestion") or "").strip()
            if suggestion:
                lines.append(f"- **{message}** — {suggestion}")
            else:
                lines.append(f"- **{message}**")
        lines.append("")

    return "\n".join(line.rstrip() for line in lines).rstrip() + "\n"



def render_release_checklist(plan: dict[str, Any]) -> str:
    project = dict(plan.get("project") or {})
    setup_recipes = _trim_items(plan.get("setup_recipes"), limit=8)
    verification_gates = _trim_items(plan.get("verification_gates"), limit=8)
    deployable_surfaces = _trim_items(plan.get("deployable_surfaces"), limit=8)
    session_issues = list(plan.get("session_issues") or [])

    lines: list[str] = []
    lines.append(f"# VHK release checklist for {project.get('name') or 'project'}")
    lines.append("")
    lines.append("Generated by `vhk gen-verification-pack`. Use this as a release rehearsal, not just a note file.")
    lines.append("")
    lines.append("## Baseline refresh")
    lines.append("")
    lines.append("- [ ] Run `vhk doctor --json` on the target session.")
    lines.append("- [ ] Run `vhk validate . --json` in the project root.")
    lines.append("- [ ] Run `vhk plan-project . --json` and review changed gates, recipes, and surfaces.")
    lines.append("- [ ] Regenerate `docs/VHK_VERIFICATION_PLAN.json` and `scripts/vhk_verify_release.sh`.")
    if session_issues:
        lines.append(f"- [ ] Review {min(len(session_issues), 8)} session issue(s) captured in `docs/VHK_VERIFICATION_PLAN.json`.")
    lines.append("")

    if deployable_surfaces:
        lines.append("## Surface agreement")
        lines.append("")
        for item in deployable_surfaces:
            title = item.get("title") or item.get("id") or "surface"
            summary = _first_text(item, "summary", "why", "description", "notes")
            if summary:
                lines.append(f"- [ ] {title} — {summary}")
            else:
                lines.append(f"- [ ] {title}")
        lines.append("")

    if setup_recipes:
        lines.append("## Install and rollback rehearsals")
        lines.append("")
        for item in setup_recipes:
            title = item.get("title") or item.get("id") or "recipe"
            lines.append(f"### {title}")
            lines.append("")
            for step in list(item.get("install_steps") or [])[:8]:
                lines.append(f"- [ ] {step}")
            for step in list(item.get("verify_steps") or [])[:6]:
                lines.append(f"- [ ] Verify: {step}")
            for step in list(item.get("rollback_steps") or [])[:5]:
                lines.append(f"- [ ] Roll back / disable: {step}")
            lines.append("")

    if verification_gates:
        lines.append("## Shipping gates")
        lines.append("")
        for item in verification_gates:
            title = item.get("title") or item.get("id") or "gate"
            lines.append(f"### {title}")
            lines.append("")
            for check in list(item.get("acceptance_checks") or item.get("checks") or [])[:7]:
                lines.append(f"- [ ] {check}")
            for cmd in list(item.get("commands") or [])[:5]:
                lines.append(f"- [ ] Run `{cmd}`")
            for path in list(item.get("fallback_paths") or [])[:4]:
                lines.append(f"- [ ] Fallback path documented: {path}")
            lines.append("")

    lines.append("## Evidence to keep with the release")
    lines.append("")
    lines.append("- [ ] Latest `vhk report` output or equivalent runtime evidence stored with the release notes.")
    lines.append("- [ ] Exported configs / launcher artifacts match the generated plan.")
    lines.append("- [ ] Rollback path is documented for every helper, service, or remapper surface used by this project.")
    lines.append("")

    return "\n".join(line.rstrip() for line in lines).rstrip() + "\n"



def render_release_script(plan: dict[str, Any]) -> str:
    project = dict(plan.get("project") or {})
    project_root = str(project.get("root_dir") or ".")
    verification_gates = _trim_items(plan.get("verification_gates"), limit=10)
    setup_recipes = _trim_items(plan.get("setup_recipes"), limit=8)

    header_lines = [
        "#!/usr/bin/env sh",
        "set -eu",
        "",
        f"PROJECT_ROOT={shlex.quote(project_root)}",
        'cd "$PROJECT_ROOT"',
        "",
        f'echo "== VHK release rehearsal: {str(project.get("name") or "project")} =="',
        'echo "Project root: $PROJECT_ROOT"',
        "",
        'echo "[1/4] Refreshing baseline diagnostics"',
        "vhk doctor --json",
        "vhk validate . --json",
        "vhk plan-project . --json > /dev/null",
        "",
    ]

    body: list[str] = []
    recipe_cmds = _dedupe_keep_order([
        cmd
        for item in setup_recipes
        for cmd in list(item.get("generator_commands") or [])[:4]
        if isinstance(cmd, str) and cmd.strip()
    ])
    if recipe_cmds:
        body.append('echo "[2/4] Regenerating surface artifacts used by release recipes"')
        for cmd in recipe_cmds:
            body.append(f'echo "+ {cmd}"')
            body.append(cmd)
        body.append("")
    else:
        body.append('echo "[2/4] No recipe generator commands were suggested for this project"')
        body.append("")

    gate_cmds = _dedupe_keep_order([
        cmd
        for item in verification_gates
        for cmd in list(item.get("commands") or [])[:5]
        if isinstance(cmd, str) and cmd.strip()
    ])
    if gate_cmds:
        body.append('echo "[3/4] Running shipping gate commands"')
        for cmd in gate_cmds:
            body.append(f'echo "+ {cmd}"')
            body.append(cmd)
        body.append("")
    else:
        body.append('echo "[3/4] No gate commands were suggested for this project"')
        body.append("")

    body.append('echo "[4/4] Manual acceptance checks to review"')
    acceptance_checks = []
    for item in verification_gates:
        title = str(item.get("title") or item.get("id") or "gate")
        for check in list(item.get("acceptance_checks") or item.get("checks") or [])[:6]:
            if isinstance(check, str) and check.strip():
                acceptance_checks.append(f"{title}: {check.strip()}")
    for entry in _dedupe_keep_order(acceptance_checks)[:30]:
        body.append(f'echo "- {entry.replace("\"", "\\\"")}"')
    body.append("")
    body.append('echo "Release rehearsal complete. Review docs/VHK_RELEASE_CHECKLIST.md before shipping."')
    body.append("")

    return "\n".join(header_lines + body)



def write_verification_pack(
    project_dir: Path,
    *,
    out_dir: Path | None = None,
    script_dir: Path | None = None,
    force: bool,
    guide: bool = True,
    checklist: bool = True,
    plan_json: bool = True,
    script: bool = True,
    capability_usage: dict[str, list[dict[str, object]]] | None = None,
    capability_matrix: dict[str, object] | None = None,
    capability_issues: list[dict[str, object]] | None = None,
) -> dict[str, Path]:
    """Write planner-backed release verification artifacts for an existing project."""

    out_dir = (out_dir or (project_dir / "docs")).expanduser().resolve()
    script_dir = (script_dir or (project_dir / "scripts")).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    script_dir.mkdir(parents=True, exist_ok=True)

    plan = build_verification_plan(
        project_dir,
        capability_usage=capability_usage,
        capability_matrix=capability_matrix,
        capability_issues=capability_issues,
    )

    written: dict[str, Path] = {}
    if plan_json:
        path = out_dir / "VHK_VERIFICATION_PLAN.json"
        _write_if_allowed(path, json.dumps(plan, ensure_ascii=False, indent=2) + "\n", force=force)
        written["plan_json"] = path
    if guide:
        path = out_dir / "VHK_VERIFICATION_GUIDE.md"
        _write_if_allowed(path, render_verification_guide(plan), force=force)
        written["guide"] = path
    if checklist:
        path = out_dir / "VHK_RELEASE_CHECKLIST.md"
        _write_if_allowed(path, render_release_checklist(plan), force=force)
        written["checklist"] = path
    if script:
        path = script_dir / "vhk_verify_release.sh"
        _write_if_allowed(path, render_release_script(plan), force=force)
        try:
            path.chmod(0o755)
        except Exception:
            pass
        written["script"] = path
    return written
