from packet_contract_common import require_named_recovery_lineage_witness_packet_and_vocabulary

require_named_recovery_lineage_witness_packet_and_vocabulary("recovery_anchor_witness_contract")

print("check_recovery_anchor_witness_contract: OK")
