from packet_contract_common import require_named_refresh_scope_axis_branch_witness_packet_and_vocabulary

require_named_refresh_scope_axis_branch_witness_packet_and_vocabulary("refresh_scope_axis_materiality_witness_contract")

print("check_refresh_scope_axis_materiality_witness_contract: OK")
