from packet_contract_common import require_named_runtime_continuity_witness_packet_and_vocabulary

require_named_runtime_continuity_witness_packet_and_vocabulary("selector_enforcement_witness_contract")

print("check_selector_enforcement_witness_contract: OK")
