from packet_contract_common import require_named_stake_continuity_witness_packet_and_vocabulary

require_named_stake_continuity_witness_packet_and_vocabulary("stake_continuity_witness_contract")

print("check_stake_continuity_witness_contract: OK")
