from packet_contract_common import require_named_refresh_elevation_witness_packet_and_vocabulary

require_named_refresh_elevation_witness_packet_and_vocabulary("refresh_elevation_witness_contract")

print("check_refresh_elevation_witness_contract: OK")
