#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
cd "$ROOT"
REVUP="REV0156"

PUBLIC_TRACE_COMMON_ENV_MODE="base"
source "$HERE/${REVUP}_COMMON_PUBLIC_TRACE_ENV.sh"
REQ="artifacts/runtime/${REVUP}_public_trace_requirements.txt"
VENV_DIR="${PUBLIC_TRACE_VENV_DIR:-.venv-public-trace}"
PYTHON_BIN="${PYTHON:-python3}"

python3 tools/public_trace_runtime_requirement_lock_audit.py --strict
python3 tools/public_trace_common_env_contract_audit.py

if [[ ! -f "$REQ" ]]; then
  echo "ERROR: missing public trace requirements file: $REQ" >&2
  exit 2
fi

if [[ "${PUBLIC_TRACE_BOOTSTRAP_DRY_RUN:-0}" == "1" ]]; then
  echo "bootstrap dry run ok: requirements file resolved to $REQ"
  echo "bootstrap dry run ok: target venv is $VENV_DIR"
  if [[ -n "${PUBLIC_TRACE_WHEELHOUSE:-}" ]]; then echo "bootstrap dry run ok: wheelhouse is ${PUBLIC_TRACE_WHEELHOUSE}"; fi
  exit 0
fi

if [[ ! -x "$VENV_DIR/bin/python" ]]; then
  echo "Creating project-local public trace virtualenv at $VENV_DIR" >&2
  if ! "$PYTHON_BIN" -m venv "$VENV_DIR"; then
    echo "ERROR: could not create $VENV_DIR with $PYTHON_BIN -m venv." >&2
    echo "       Install/enable the Python venv module, or set PUBLIC_TRACE_VENV_DIR to an existing venv." >&2
    exit 2
  fi
fi

VENV_PY="$VENV_DIR/bin/python"
VENV_PIP="$VENV_PY -m pip"
INSTALL_ARGS=(-r "$REQ")
if [[ -n "${PUBLIC_TRACE_WHEELHOUSE:-}" ]]; then
  case "$PUBLIC_TRACE_WHEELHOUSE" in
    /*) PUBLIC_TRACE_WHEELHOUSE_ABS="$PUBLIC_TRACE_WHEELHOUSE" ;;
    *) PUBLIC_TRACE_WHEELHOUSE_ABS="$ROOT/$PUBLIC_TRACE_WHEELHOUSE" ;;
  esac
  if [[ ! -d "$PUBLIC_TRACE_WHEELHOUSE_ABS" ]]; then
    echo "ERROR: PUBLIC_TRACE_WHEELHOUSE is set but is not a directory: $PUBLIC_TRACE_WHEELHOUSE_ABS" >&2
    exit 2
  fi
  export PUBLIC_TRACE_WHEELHOUSE="$PUBLIC_TRACE_WHEELHOUSE_ABS"
  export PIP_NO_INDEX=1
  export PIP_FIND_LINKS="$PUBLIC_TRACE_WHEELHOUSE_ABS"
  PUBLIC_TRACE_SKIP_PIP_UPGRADE="${PUBLIC_TRACE_SKIP_PIP_UPGRADE:-1}"
  INSTALL_ARGS=(--no-index --find-links "$PUBLIC_TRACE_WHEELHOUSE_ABS" -r "$REQ")
else
  PUBLIC_TRACE_SKIP_PIP_UPGRADE="${PUBLIC_TRACE_SKIP_PIP_UPGRADE:-0}"
fi

if [[ "$PUBLIC_TRACE_SKIP_PIP_UPGRADE" != "1" ]]; then
  "$VENV_PY" -m pip install --upgrade pip setuptools wheel
fi
"$VENV_PY" -m pip install "${INSTALL_ARGS[@]}"

# Prove the actual venv Python can import the capture stack and the current
# Transformers/Llama eager-attention surface before any expensive snapshot run.
export PUBLIC_TRACE_VENV_DIR="$ROOT/$VENV_DIR"
export VIRTUAL_ENV="$ROOT/$VENV_DIR"
export PYTHONNOUSERSITE="1"
"$VENV_PY" tools/public_trace_runtime_import_smoke.py --strict --require-project-venv

BOOTSTRAP_ENV="artifacts/runtime/CURRENT_PUBLIC_TRACE_BOOTSTRAP_ENV.sh"
cat > "$BOOTSTRAP_ENV" <<EOF
# Generated by ${REVUP}_BOOTSTRAP_PUBLIC_TRACE_ENV.sh. Source or PATH-prepend this before capture phases.
export PUBLIC_TRACE_VENV_DIR="$ROOT/$VENV_DIR"
export PATH="$ROOT/$VENV_DIR/bin:\$PATH"
export PYTHONNOUSERSITE="1"
export PUBLIC_TRACE_CACHE_ROOT="$PUBLIC_TRACE_CACHE_ROOT"
export HF_HOME="$HF_HOME"
export HF_HUB_CACHE="$HF_HUB_CACHE"
export HF_XET_CACHE="$HF_XET_CACHE"
export HF_ASSETS_CACHE="$HF_ASSETS_CACHE"
export HF_HUB_DOWNLOAD_TIMEOUT="${HF_HUB_DOWNLOAD_TIMEOUT:-300}"
export HF_HUB_ETAG_TIMEOUT="${HF_HUB_ETAG_TIMEOUT:-60}"
EOF

"$VENV_PY" tools/public_trace_bootstrap_runtime_audit.py || true
"$VENV_PY" tools/public_trace_cache_root_contract_audit.py || true

echo "Installed/verified public trace runtime requirements from $REQ inside $VENV_DIR"
echo "Bootstrap env written to $BOOTSTRAP_ENV"
