from __future__ import annotations

import html
from typing import Any


def _fmt_cell(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.6g}"
    return str(value)


def render_report_html(
    report: dict[str, Any],
    *,
    title: str = "Concord Report",
    artifact_path_by_task_id: dict[str, str] | None = None,
) -> str:
    run_id = report.get("run_id")
    n_artifacts = report.get("n_artifacts")
    experiment_hash = report.get("experiment_hash")
    definitions_hash = report.get("definitions_hash")
    world_id = report.get("world_id")

    rows = report.get("rows")
    if not isinstance(rows, list):
        rows = []

    headers: list[tuple[str, str]] = [
        ("artifact", "Artifact"),
        ("task_id", "Task"),
        ("world_id", "World"),
        ("a", "A"),
        ("b", "B"),
        ("rounds", "Rounds"),
        ("avg_a", "Avg A"),
        ("avg_b", "Avg B"),
        ("coop_a", "Coop A"),
        ("coop_b", "Coop B"),
        ("mutual_c", "Mutual C"),
    ]

    def _artifact_link(task_id: str | None) -> str:
        if not task_id or not artifact_path_by_task_id:
            return ""
        ap = artifact_path_by_task_id.get(task_id)
        if not ap:
            return ""
        href = html.escape(ap, quote=True)
        text = html.escape(ap)
        return f'<a href="{href}">{text}</a>'

    head = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <style>
    :root {{
      color-scheme: light dark;
    }}
    body {{
      font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;
      margin: 16px;
    }}
    h1 {{
      margin: 0 0 8px 0;
      font-size: 20px;
    }}
    .meta {{
      font-size: 13px;
      opacity: 0.9;
      margin-bottom: 16px;
      line-height: 1.5;
    }}
    .meta code {{
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      font-size: 12px;
    }}
    table {{
      border-collapse: collapse;
      width: 100%;
      font-size: 12px;
    }}
    th, td {{
      border: 1px solid rgba(128, 128, 128, 0.35);
      padding: 6px 8px;
      vertical-align: top;
      word-break: break-word;
    }}
    th {{
      text-align: left;
      position: sticky;
      top: 0;
      background: rgba(128, 128, 128, 0.15);
    }}
    tbody tr:nth-child(even) {{
      background: rgba(128, 128, 128, 0.06);
    }}
    .note {{
      margin-top: 16px;
      font-size: 12px;
      opacity: 0.85;
    }}
  </style>
</head>
<body>
"""

    meta_lines = [
        f"run_id=<code>{html.escape(str(run_id))}</code>" if run_id else None,
        f"world_id=<code>{html.escape(str(world_id))}</code>" if world_id else None,
        f"n_artifacts=<code>{html.escape(str(n_artifacts))}</code>" if n_artifacts is not None else None,
        f"experiment_hash=<code>{html.escape(str(experiment_hash))}</code>" if experiment_hash else None,
        f"definitions_hash=<code>{html.escape(str(definitions_hash))}</code>" if definitions_hash else None,
    ]
    meta_html = "<br>\n".join([m for m in meta_lines if m])

    out: list[str] = [head]
    out.append(f"<h1>{html.escape(title)}</h1>\n")
    out.append(f'<div class="meta">{meta_html}</div>\n')
    out.append("<table>\n<thead>\n<tr>\n")
    for _key, label in headers:
        out.append(f"<th>{html.escape(label)}</th>\n")
    out.append("</tr>\n</thead>\n<tbody>\n")

    for row in rows:
        if not isinstance(row, dict):
            continue
        task_id = row.get("task_id")
        if task_id is not None and not isinstance(task_id, str):
            task_id = str(task_id)

        out.append("<tr>\n")
        for key, _label in headers:
            if key == "artifact":
                cell = _artifact_link(task_id)
            else:
                cell = html.escape(_fmt_cell(row.get(key)))
            out.append(f"<td>{cell}</td>\n")
        out.append("</tr>\n")

    out.append("</tbody>\n</table>\n")
    out.append(
        '<div class="note">Generated by <code>grlab report-html</code> from <code>report.json</code>.</div>\n'
    )
    out.append("</body>\n</html>\n")
    return "".join(out)

