#!/usr/bin/env python3
"""Generate/check the candidate-native docket duplication audit."""
from __future__ import annotations

import argparse
import collections
import sys
from pathlib import Path

sys.dont_write_bytecode = True

OUTPUT = "docs/30-program/candidate-native-docket-duplication-audit.generated.md"
DOCKET_GLOB = "candidate-native-identifiability-*docket*.md"
COMMON_BLOCK = "docs/10-method/candidate-native-docket-common-block.md"


def docket_files(root: Path) -> list[Path]:
    return sorted((root / "docs/40-model").glob(DOCKET_GLOB), key=lambda p: p.name)


def long_lines(text: str) -> list[str]:
    return [line.strip() for line in text.splitlines() if len(line.strip()) >= 48 and not line.lstrip().startswith("|")]


def render(root: Path) -> str:
    files = docket_files(root)
    line_counter: collections.Counter[str] = collections.Counter()
    line_members: dict[str, set[str]] = collections.defaultdict(set)
    metrics = []
    total_bytes = 0
    total_read_links = 0
    for path in files:
        text = path.read_text()
        size = len(text.encode("utf-8"))
        total_bytes += size
        read_links = sum(1 for line in text.splitlines() if line.strip().startswith("- `docs/"))
        total_read_links += read_links
        for line in long_lines(text):
            line_counter[line] += 1
            line_members[line].add(path.name)
        metrics.append((path.name, size, read_links))

    repeated = [(line, count) for line, count in line_counter.most_common() if count >= 8]
    largest = sorted(metrics, key=lambda item: item[1], reverse=True)[:8]
    read_heavy = sorted(metrics, key=lambda item: item[2], reverse=True)[:8]
    common_link_lines = [line for line, count in repeated if line.startswith("- `docs/40-model/candidate-native-identifiability")]
    warning_lines = [line for line, count in repeated if "release" in line.lower() or "bundle" in line.lower() or "reimport" in line.lower()]

    lines = [
        "# Candidate-native docket duplication audit",
        "",
        "Generated by `tools/candidate_docket_duplication_audit.py`.",
        "",
        "## Scope",
        "",
        f"- Docket files scanned: `{len(files)}`",
        f"- Total docket bytes: `{total_bytes}`",
        f"- Read-together link bullets: `{total_read_links}`",
        f"- Lines repeated in eight or more docket files: `{len(repeated)}`",
        f"- Common-block owner: `{COMMON_BLOCK}`",
        "",
        "## Largest docket surfaces",
        "",
        "| File | Bytes | Read-together bullets |",
        "|---|---:|---:|",
    ]
    for name, size, links in largest:
        lines.append(f"| `{name}` | `{size}` | `{links}` |")
    lines += [
        "",
        "## Read-together-heavy surfaces",
        "",
        "| File | Read-together bullets | Bytes |",
        "|---|---:|---:|",
    ]
    for name, size, links in read_heavy:
        lines.append(f"| `{name}` | `{links}` | `{size}` |")
    lines += [
        "",
        "## Repeated owner-link block candidates",
        "",
    ]
    for line in common_link_lines[:24]:
        lines.append(f"- `{line[2:-1] if line.startswith('- `') and line.endswith('`') else line}` — repeated `{line_counter[line]}` times")
    lines += [
        "",
        "## Repeated release / reimport warning candidates",
        "",
    ]
    for line in warning_lines[:12]:
        trimmed = line if len(line) <= 220 else line[:217] + "..."
        lines.append(f"- repeated `{line_counter[line]}` times: {trimmed}")
    lines += [
        "",
        "## Refactor verdict",
        "",
        "The riskiest waste is not the existence of the dockets; it is front-matter and restart-link repetition making it hard to see which state machine each docket uniquely owns. The common-block surface should own shared non-promotion, read-together, export/reimport, release-seal, lineage, and current-authority warnings. Individual dockets should keep their state codes, mandatory rows, triggers, and failure effects.",
        "",
        "Do not bulk-delete the repeated blocks until lint has a replacement guard proving each docket still points to the common owner and keeps its unique state table. The next safe compression pass is: replace the largest read-together lists first, not the operational state tables.",
        "",
        "## Non-promotion boundary",
        "",
        "This audit changes restart ergonomics only. It does not promote candidate-native identifiability, route authority, evidence credit, forecast realization, or public-record credit.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    output = root / OUTPUT
    rendered = render(root)
    if args.check:
        if not output.exists():
            print(f"CANDIDATE DOCKET AUDIT FAIL missing {OUTPUT}")
            return 1
        if output.read_text() != rendered:
            print(f"CANDIDATE DOCKET AUDIT FAIL drifted {OUTPUT}; run make index")
            return 1
        print("CANDIDATE DOCKET AUDIT OK")
        return 0
    output.write_text(rendered)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
