from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
required = [
    'README.md',
    'START_HERE.md',
    'AGENTS.md',
    'CHANGELOG.md',
    'ARCHIVE_INDEX.md',
    'REVISION_RECEIPT.json',
    'RELEASE-MANIFEST.json',
    'ASSUMPTION_LEDGER.json',
    'FOLLOWTHROUGH_QUEUE.json',
    'FOREIGN_PRESSURE_LEDGER.json',
    'docs/00-meta/charter.md',
    'docs/00-meta/llm-runbook.md',
    'docs/00-meta/trajectory-map.md',
    'docs/00-meta/bibliography.md',
    'docs/10-core/design-principles.md',
    'docs/10-core/minimal-ai-literacy-spine.md',
    'docs/10-core/reference-model.md',
    'docs/20-governance/evidence-and-procurement.md',
    'docs/20-governance/pilot-to-scale-evidence-and-rollout-gates.md',
    'docs/20-governance/sector-and-function-profile-splits-for-rollout-gates.md',
    'docs/20-governance/accommodation-aware-disclosure-and-accessibility.md',
    'docs/20-governance/presumptive-access-support-categories-and-override-triggers.md',
    'docs/20-governance/subject-and-age-override-table-profile.md',
    'docs/20-governance/reusable-starter-override-rows.md',
    'docs/20-governance/general-purpose-vs-purpose-built-deployment-ladder.md',
    'docs/20-governance/student-facing-function-deployment-defaults-and-handoff-triggers.md',
    'docs/20-governance/sector-and-age-profile-splits-for-student-facing-defaults.md',
    'docs/20-governance/teacher-facing-function-delegation-defaults-and-sign-off-triggers.md',
    'docs/20-governance/sector-and-age-profile-splits-for-teacher-facing-defaults.md',
    'docs/20-governance/institution-facing-decision-support-defaults-and-contestability-triggers.md',
    'docs/20-governance/sector-and-office-profile-splits-for-institution-facing-defaults.md',
    'docs/20-governance/persistent-memory-personalization-and-learner-model-boundaries.md',
    'docs/20-governance/sector-and-function-profile-splits-for-memory-defaults.md',
    'docs/20-governance/minimum-observability-and-retention-without-surveillance.md',
    'docs/20-governance/sector-and-function-profile-splits-for-observability-defaults.md',
    'docs/20-governance/failure-escalation-safe-degradation-and-manual-fallback.md',
    'docs/20-governance/sector-and-function-profile-splits-for-failure-defaults.md',
    'docs/20-governance/model-and-workflow-change-classification-and-fresh-review-triggers.md',
    'docs/20-governance/sector-and-function-profile-splits-for-change-defaults.md',
    'docs/20-governance/open-question-registry.md',
    'docs/30-operations/phased-adoption-roadmap.md',
    'docs/30-operations/subject-embedded-exemplar-kernel.md',
    'docs/30-operations/course-level-ai-use-grammar.md',
    'docs/30-operations/lifelong-public-ai-learning-stack.md',
    'docs/30-operations/minimum-public-entitlement-and-handoff-standard.md',
    'docs/30-operations/portable-public-learning-packet-and-recognition-profile.md',
    'docs/30-operations/sector-defaults-for-public-ai-learning-recognition.md',
    'docs/30-operations/standing-equivalency-lists-and-review-governance.md',
    'docs/30-operations/standing-list-publication-profile-and-recency-windows.md',
    'docs/30-operations/standing-recognition-exception-profile-and-local-overrides.md',
    'docs/30-operations/appeal-feedback-and-standing-list-maintenance.md',
    'docs/30-operations/public-maintenance-history-and-trust-signals.md',
    'docs/30-operations/partner-consumption-and-grandfathering-rules.md',
    'docs/30-operations/in-flight-teach-out-and-substitute-equivalent-rules.md',
    'docs/30-operations/documented-reliance-and-burden-thresholds.md',
    'docs/30-operations/no-fault-transition-cost-absorption-and-fee-waiver-rules.md',
    'docs/40-assessment/authentic-assessment-and-proof-of-learning.md',
    'docs/40-assessment/proof-of-learning-bundles.md',
    'docs/40-assessment/bundle-intensity-bands-and-sampling-ceilings.md',
    'docs/40-assessment/subject-family-proof-intensity-defaults.md',
    'docs/40-assessment/sector-and-age-profile-splits-for-proof-intensity-defaults.md',
    'docs/90-quarantine/speculations-2026-03-22.md',
]
missing = [p for p in required if not (ROOT / p).exists()]
if missing:
    raise SystemExit('missing required surfaces: ' + ', '.join(missing))
print('check_required_surfaces: OK')
