from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Dict, Iterable, Mapping, Sequence


@dataclass(frozen=True)
class LabelMethodSummary:
    """Aggregate comparison of label-allocation methods over a fixed branch matrix.

    This module does not run games.  It consumes branch rollout rows generated by
    the Python semantic referee and asks: if two labelers had access to the same
    candidate actions and the same possible branch rollouts, which actions would
    they call best and how many rollout samples would they spend?

    That makes it a pure label-budget audit.  It is meant to sit between the
    public hard-frame queue and any future counterfactual policy training.
    """

    revision: str
    situations: int
    action_rows: int
    candidate_action_rows: int
    branch_rollout_rows: int
    methods: tuple[str, ...]
    fixed_rollouts_per_action: int
    adaptive_base_rollouts: int
    adaptive_extra_budget: int
    min_decisive_margin: float
    fixed_rollouts_spent: int
    adaptive_rollouts_spent: int
    adaptive_rollout_savings: int
    fixed_decisive_situations: int
    adaptive_decisive_situations: int
    best_set_agreement_rate: float
    chosen_best_agreement_rate: float
    adaptive_changed_label_situations: int
    adaptive_saved_rollouts_situations: int
    fixed_mean_margin: float
    adaptive_mean_margin: float
    fixed_decisive_per_100_rollouts: float
    adaptive_decisive_per_100_rollouts: float
    notes: tuple[str, ...]

    def as_dict(self) -> Dict[str, object]:
        return asdict(self)


def _mean(xs: Sequence[float | int]) -> float:
    return float(sum(float(x) for x in xs) / max(1, len(xs)))


def _parse_best_actions(best_actions: object) -> set[int]:
    if best_actions is None:
        return set()
    text = str(best_actions)
    if not text:
        return set()
    out: set[int] = set()
    for part in text.replace(";", ",").split(","):
        part = part.strip()
        if not part:
            continue
        try:
            out.add(int(part))
        except ValueError:
            continue
    return out


def _scores_from_rows(rows: Sequence[Mapping[str, object]]) -> dict[int, list[float]]:
    by_action: dict[int, list[tuple[int, float]]] = {}
    for row in rows:
        a = int(row["action_index"])
        rollout = int(row.get("rollout", len(by_action.get(a, ()))) )
        score = float(row.get("actor_score", 0.0))
        by_action.setdefault(a, []).append((rollout, score))
    return {a: [score for _, score in sorted(vals)] for a, vals in by_action.items()}


def _label_from_means(means: Mapping[int, float], *, eps: float = 1e-9) -> tuple[set[int], float, float]:
    """Return best-set, best score, and best-minus-second margin."""
    if not means:
        return set(), 0.0, 0.0
    ranked = sorted(((float(v), int(k)) for k, v in means.items()), reverse=True)
    best_score = float(ranked[0][0])
    best = {int(a) for v, a in ranked if abs(float(v) - best_score) <= eps}
    second = next((float(v) for v, a in ranked if int(a) not in best), best_score)
    return best, best_score, float(best_score - second)


def _fixed_method(scores: Mapping[int, Sequence[float]], *, rollouts_per_action: int) -> dict[str, object]:
    used: dict[int, list[float]] = {}
    for a, vals in scores.items():
        kept = [float(v) for v in vals[: int(rollouts_per_action)]]
        if kept:
            used[int(a)] = kept
    means = {a: _mean(vals) for a, vals in used.items()}
    best, best_score, margin = _label_from_means(means)
    return {
        "method": f"fixed_equal_{int(rollouts_per_action)}",
        "best_actions": best,
        "best_score": float(best_score),
        "margin": float(margin),
        "rollouts_spent": int(sum(len(v) for v in used.values())),
        "action_count": int(len(used)),
        "means": means,
    }


def _adaptive_method(
    scores: Mapping[int, Sequence[float]],
    *,
    base_rollouts: int = 1,
    extra_budget: int = 6,
    min_margin: float = 0.20,
) -> dict[str, object]:
    """Offline adaptive labeler over an already-generated rollout matrix.

    It spends one rollout per candidate, then spends extra samples on the current
    top contenders.  The method intentionally only consumes prefix rollouts per
    action, so it can be compared fairly against future online collectors.
    """

    used: dict[int, list[float]] = {}
    available = {int(a): [float(v) for v in vals] for a, vals in scores.items() if vals}
    for a, vals in available.items():
        used[a] = vals[: max(1, int(base_rollouts))]
    extras = 0
    while extras < int(extra_budget):
        means = {a: _mean(vals) for a, vals in used.items() if vals}
        best, _best_score, margin = _label_from_means(means)
        # If the margin is already reasonably clear and every action has at
        # least the base sample, stop.  This is a label-budget heuristic, not a
        # statistical proof.
        if len(means) >= 2 and margin >= float(min_margin):
            break
        ranked = sorted(((float(v), int(a)) for a, v in means.items()), reverse=True)
        if not ranked:
            break
        # Allocate to best and runner-up first, but keep cycling if one action
        # has exhausted generated rollout rows.
        candidate_order = [a for _, a in ranked[:2]] + [a for _, a in ranked[2:]]
        advanced = False
        for a in candidate_order:
            if len(used.get(a, [])) < len(available.get(a, [])):
                used[a].append(available[a][len(used[a])])
                extras += 1
                advanced = True
                break
        if not advanced:
            break
    means = {a: _mean(vals) for a, vals in used.items() if vals}
    best, best_score, margin = _label_from_means(means)
    return {
        "method": "adaptive_race_prefix",
        "best_actions": best,
        "best_score": float(best_score),
        "margin": float(margin),
        "rollouts_spent": int(sum(len(v) for v in used.values())),
        "action_count": int(len(used)),
        "means": means,
    }


def compare_fixed_vs_adaptive_labels(
    branch_rows: Sequence[Mapping[str, object]],
    *,
    revision: str,
    fixed_rollouts_per_action: int = 3,
    adaptive_base_rollouts: int = 1,
    adaptive_extra_budget: int = 6,
    min_decisive_margin: float = 0.20,
) -> tuple[list[Dict[str, object]], list[Dict[str, object]], LabelMethodSummary]:
    """Compare fixed-equal labels against prefix-adaptive labels.

    The input branch rows should include situation_id, action_index, rollout,
    and actor_score.  The output contains one detail row per situation/method and
    one pivot row per situation.
    """

    grouped: dict[str, list[Mapping[str, object]]] = {}
    for row in branch_rows:
        grouped.setdefault(str(row["situation_id"]), []).append(row)

    detail_rows: list[Dict[str, object]] = []
    pivot_rows: list[Dict[str, object]] = []
    fixed_rollouts = 0
    adaptive_rollouts = 0
    fixed_decisive = 0
    adaptive_decisive = 0
    agreements = 0
    chosen_agreements = 0
    changed = 0
    saved = 0
    fixed_margins: list[float] = []
    adaptive_margins: list[float] = []
    action_rows = 0

    for sid, rows in sorted(grouped.items()):
        scores = _scores_from_rows(rows)
        if len(scores) <= 1:
            continue
        action_rows += len(scores)
        # Use the first row as situation-level metadata.  Branch rows from our
        # collectors duplicate these fields for every branch rollout.
        meta = dict(rows[0])
        chosen = int(meta.get("behavior_chosen", -999))
        # Most branch rows encode behavior_chosen as a flag, not index.  Recover
        # the chosen action from the first flagged row if present.
        for r in rows:
            if int(r.get("behavior_chosen", 0)) == 1:
                chosen = int(r["action_index"])
                break
        fixed = _fixed_method(scores, rollouts_per_action=int(fixed_rollouts_per_action))
        adaptive = _adaptive_method(
            scores,
            base_rollouts=int(adaptive_base_rollouts),
            extra_budget=int(adaptive_extra_budget),
            min_margin=float(min_decisive_margin),
        )
        methods = (fixed, adaptive)
        for m in methods:
            best_actions = set(m["best_actions"])
            detail_rows.append({
                "revision": revision,
                "situation_id": sid,
                "method": m["method"],
                "action_count": int(m["action_count"]),
                "best_actions": ",".join(str(a) for a in sorted(best_actions)),
                "best_score": float(m["best_score"]),
                "margin": float(m["margin"]),
                "decisive": 1 if float(m["margin"]) >= float(min_decisive_margin) else 0,
                "rollouts_spent": int(m["rollouts_spent"]),
                "behavior_chosen_index": int(chosen),
                "behavior_chosen_best": 1 if int(chosen) in best_actions else 0,
                "starting_life": int(meta.get("starting_life", 0)),
                "starting_player": int(meta.get("starting_player", 0)),
                "action_count_full": int(meta.get("action_count", m["action_count"])),
                "union_branched_action_count": int(meta.get("union_branched_action_count", m["action_count"])),
            })
        fixed_best = set(fixed["best_actions"])
        adaptive_best = set(adaptive["best_actions"])
        agree = bool(fixed_best == adaptive_best)
        chosen_agree = bool((chosen in fixed_best) == (chosen in adaptive_best))
        f_roll = int(fixed["rollouts_spent"])
        a_roll = int(adaptive["rollouts_spent"])
        f_dec = float(fixed["margin"]) >= float(min_decisive_margin)
        a_dec = float(adaptive["margin"]) >= float(min_decisive_margin)
        fixed_rollouts += f_roll
        adaptive_rollouts += a_roll
        fixed_decisive += int(f_dec)
        adaptive_decisive += int(a_dec)
        agreements += int(agree)
        chosen_agreements += int(chosen_agree)
        changed += int(not agree)
        saved += int(a_roll < f_roll)
        fixed_margins.append(float(fixed["margin"]))
        adaptive_margins.append(float(adaptive["margin"]))
        pivot_rows.append({
            "revision": revision,
            "situation_id": sid,
            "action_count": int(meta.get("action_count", len(scores))),
            "union_branched_action_count": int(meta.get("union_branched_action_count", len(scores))),
            "behavior_chosen_index": int(chosen),
            "fixed_best_actions": ",".join(str(a) for a in sorted(fixed_best)),
            "adaptive_best_actions": ",".join(str(a) for a in sorted(adaptive_best)),
            "fixed_margin": float(fixed["margin"]),
            "adaptive_margin": float(adaptive["margin"]),
            "fixed_decisive": int(f_dec),
            "adaptive_decisive": int(a_dec),
            "fixed_rollouts_spent": f_roll,
            "adaptive_rollouts_spent": a_roll,
            "adaptive_rollouts_saved": f_roll - a_roll,
            "best_set_agree": int(agree),
            "behavior_chosen_best_fixed": 1 if chosen in fixed_best else 0,
            "behavior_chosen_best_adaptive": 1 if chosen in adaptive_best else 0,
            "chosen_best_agree": int(chosen_agree),
            "starting_life": int(meta.get("starting_life", 0)),
            "starting_player": int(meta.get("starting_player", 0)),
        })

    n = max(1, len(pivot_rows))
    methods = tuple(sorted({str(r["method"]) for r in detail_rows}))
    summary = LabelMethodSummary(
        revision=revision,
        situations=int(len(pivot_rows)),
        action_rows=int(action_rows),
        candidate_action_rows=int(len(detail_rows)),
        branch_rollout_rows=int(len(branch_rows)),
        methods=methods,
        fixed_rollouts_per_action=int(fixed_rollouts_per_action),
        adaptive_base_rollouts=int(adaptive_base_rollouts),
        adaptive_extra_budget=int(adaptive_extra_budget),
        min_decisive_margin=float(min_decisive_margin),
        fixed_rollouts_spent=int(fixed_rollouts),
        adaptive_rollouts_spent=int(adaptive_rollouts),
        adaptive_rollout_savings=int(fixed_rollouts - adaptive_rollouts),
        fixed_decisive_situations=int(fixed_decisive),
        adaptive_decisive_situations=int(adaptive_decisive),
        best_set_agreement_rate=float(agreements / n),
        chosen_best_agreement_rate=float(chosen_agreements / n),
        adaptive_changed_label_situations=int(changed),
        adaptive_saved_rollouts_situations=int(saved),
        fixed_mean_margin=_mean(fixed_margins),
        adaptive_mean_margin=_mean(adaptive_margins),
        fixed_decisive_per_100_rollouts=float(100.0 * fixed_decisive / max(1, fixed_rollouts)),
        adaptive_decisive_per_100_rollouts=float(100.0 * adaptive_decisive / max(1, adaptive_rollouts)),
        notes=(
            "This is an offline label-budget audit over a fixed branch matrix; it is not a promoted gameplay policy.",
            "The adaptive method consumes rollout prefixes only, making it comparable to an eventual online racer.",
            "A changed label is not automatically a bug: it may mean the fixed method used extra rollouts the adaptive method intentionally skipped.",
        ),
    )
    return detail_rows, pivot_rows, summary
