#!/usr/bin/env python3
"""
tools/evidence_packager.py

Build a content-addressed evidence packet + EvidenceBundleManifest.

This is intentionally minimal and stdlib-only. It is meant to be forked and re-implemented
by independent verifiers.

Usage:
  python tools/evidence_packager.py --election-id E123 --out evidence_packets/E123-public \
      docs/63-election-night-reporting-and-publication.md artifacts/claims/claim-evidence-matrix.csv
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def copy_to_objects(src: Path, objects_dir: Path, hexdigest: str) -> Path:
    ext = "".join(src.suffixes) or ".bin"
    dst = objects_dir / f"sha256-{hexdigest}{ext}"
    if not dst.exists():
        dst.write_bytes(src.read_bytes())
    return dst


def build_manifest(election_id: str, artifacts: list[dict], created_at: str) -> dict:
    # Minimal CryptoPolicy satisfying schemas/CryptoPolicy.json.
    crypto_policy = {
        "election_id": election_id,
        "allowed_crypto_suites": ["hfv.placeholder.suite"],
        "default_crypto_suite": "hfv.placeholder.suite",
        "deprecation": [],
        "notes": "Placeholder crypto policy for packaging; replace in production bundles."
    }

    return {
        "election_id": election_id,
        "created_at": created_at,
        "crypto_policy": crypto_policy,
        "artifacts": artifacts,
        "signatures": [
            {
                "signer_id": "packager:UNSIGNED",
                "alg": "none",
                "sig": "UNSIGNED"
            }
        ],
        # Optional newer fields (see docs/173).
        "bundle_version": "0.1",
        "created_by": "tools/evidence_packager.py",
        "notes": "This manifest is generated; signatures are placeholders unless replaced."
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--election-id", required=True)
    ap.add_argument("--out", required=True, help="Output packet directory")
    ap.add_argument("files", nargs="+", help="Files to include")
    args = ap.parse_args()

    out_dir = Path(args.out)
    objects_dir = out_dir / "objects"
    notes_dir = out_dir / "notes"
    objects_dir.mkdir(parents=True, exist_ok=True)
    notes_dir.mkdir(parents=True, exist_ok=True)

    created_at = datetime.now(timezone.utc).isoformat()

    artifacts = []
    for f in args.files:
        src = Path(f)
        if not src.exists():
            raise SystemExit(f"Missing file: {src}")
        hexdigest = sha256_file(src)
        dst = copy_to_objects(src, objects_dir, hexdigest)

        artifacts.append({
            "name": str(src).replace("\\\\", "/"),
            "media_type": "application/octet-stream",
            "sha256": hexdigest,
            "digest": f"sha256:{hexdigest}",
            "size_bytes": dst.stat().st_size,
            "url": "",
            "kind": "hfv.raw",
            "schema": ""
        })

    manifest = build_manifest(args.election_id, artifacts, created_at)
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    readme = notes_dir / "README.md"
    if not readme.exists():
        readme.write_text(
            "# Evidence packet\n\n"
            "Generated by tools/evidence_packager.py.\n\n"
            "This is a minimal template; replace placeholder signatures and crypto policy.\n",
            encoding="utf-8",
        )

    print(f"Wrote {out_dir / 'manifest.json'} with {len(artifacts)} artifacts.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
