#pragma once

#include <filesystem>
#include <memory>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>

#if !defined(_WIN32)
#include "sync_directory_authority.hpp"
#endif

namespace anonsync {

namespace atomic_file_publication_detail {
class PreparedImmutableJsonPublicationObserverAccess;
}

// Describes the strongest fact this publication attempt established before an
// exception escaped. The status is about this attempt's own namespace and
// durability effects; another authorized writer may replace the destination
// after those effects complete.
enum class SyncAtomicFilePublicationOutcome {
    NotPublished,
    PublishedDurabilityIndeterminate,
    PublishedAndDirectorySynced
};

[[nodiscard]] const char* sync_atomic_file_publication_outcome_name(
    SyncAtomicFilePublicationOutcome outcome) noexcept;

// Describes whether an unsuccessful attempt may have left an artifact related
// to its temporary inode or pathname. This is deliberately not a cleanup
// capability: another actor can replace a name between an identity check and
// unlinkat(), so the publisher never performs guessed failure-path deletion.
enum class SyncAtomicFilePublicationResidue {
    None,
    TemporaryArtifactMayRemain
};

[[nodiscard]] const char* sync_atomic_file_publication_residue_name(
    SyncAtomicFilePublicationResidue residue) noexcept;

// Exact classifier for the private temporary basename generated by this
// publisher. Recovery owners may count and diagnose these artifacts, but this
// predicate conveys no unlink, cleanup, byte, or ownership authority.
[[nodiscard]] bool sync_atomic_file_publication_temp_basename_is_exact(
    std::string_view basename) noexcept;

// Runtime publication failures carry machine-readable effect classification so
// callers never need to infer retry authority from diagnostic text. Existing
// std::exception handlers remain source-compatible.
class SyncAtomicFilePublicationError : public std::runtime_error {
public:
    SyncAtomicFilePublicationError(
        SyncAtomicFilePublicationOutcome outcome,
        SyncAtomicFilePublicationResidue residue,
        std::string message);

    // Retained for source compatibility with code that manually constructs the
    // exception. Runtime publication failures use the three-argument overload.
    SyncAtomicFilePublicationError(
        SyncAtomicFilePublicationOutcome outcome,
        std::string message);

    [[nodiscard]] SyncAtomicFilePublicationOutcome outcome() const noexcept;
    [[nodiscard]] SyncAtomicFilePublicationResidue residue() const noexcept;

private:
    SyncAtomicFilePublicationOutcome outcome_;
    SyncAtomicFilePublicationResidue residue_;
};

// A move-only, single-use authority for publishing immutable JSON to one exact
// destination. Construction resolves the path, proves the final name absent,
// and, on POSIX, retains the verified parent-directory descriptor across any
// intervening durable transition. The payload bytes and label are owned by the
// capability, so later publication cannot observe caller mutation.
//
// This is deliberately not a cross-resource transaction: another writer may
// still create the final name, and directory durability may still fail after
// the no-replace namespace transition. Those effects are reported through
// SyncAtomicFilePublicationError. A parent-path rebind detected before temp
// reservation is NotPublished with no possible temp residue. Inherited use
// after fork is a process-capability violation: it fail-stops without C++
// unwinding before filesystem mutation.
class SyncPreparedImmutableJsonPublication final {
public:
    SyncPreparedImmutableJsonPublication() noexcept;
    SyncPreparedImmutableJsonPublication(
        SyncPreparedImmutableJsonPublication&&) noexcept;
    SyncPreparedImmutableJsonPublication& operator=(
        SyncPreparedImmutableJsonPublication&&) noexcept;
    SyncPreparedImmutableJsonPublication(
        const SyncPreparedImmutableJsonPublication&) = delete;
    SyncPreparedImmutableJsonPublication& operator=(
        const SyncPreparedImmutableJsonPublication&) = delete;
    ~SyncPreparedImmutableJsonPublication();

    [[nodiscard]] bool valid() const noexcept;

    // Consumes this capability exactly once. A second call is a typed
    // NotPublished error and never reuses stale parent or pathname evidence.
    // A nonempty capability inherited by another process fail-stops before
    // pathname or retained-directory authority can be exercised.
    void publish_or_throw();

private:
    class Impl;
    explicit SyncPreparedImmutableJsonPublication(
        std::unique_ptr<Impl> implementation) noexcept;

    std::unique_ptr<Impl> implementation_;

    friend SyncPreparedImmutableJsonPublication
    prepare_sync_json_file_atomically_create_new_no_symlink_or_throw(
        const std::filesystem::path& final_path,
        std::string payload,
        const std::string& label);
    friend class atomic_file_publication_detail::
        PreparedImmutableJsonPublicationObserverAccess;
};

// Prepares immutable JSON publication before an irreversible transition. The
// returned capability owns the exact payload and, on POSIX, the exact verified
// destination parent. No temp file or final entry is created until
// publish_or_throw() is called.
[[nodiscard]] SyncPreparedImmutableJsonPublication
prepare_sync_json_file_atomically_create_new_no_symlink_or_throw(
    const std::filesystem::path& final_path,
    std::string payload,
    const std::string& label);

// Publishes one complete payload by creating a writer-owned file in the
// destination directory, syncing it, atomically replacing the final directory
// entry, and then syncing the directory. Existing symbolic links and
// non-regular final entries are rejected before publication. On POSIX, every
// parent component is opened without following links and the terminal parent
// identity is re-proven immediately before rename and again after directory
// synchronization. Those are point-in-time observations: without external
// coordination, another principal may rebind the pathname after either check.
// Pre-publication failures may leave an artifact related to the temp inode or
// its pathname. The implementation best-effort sanitizes only the exact
// retained handle; the typed error reports possible residue instead of racing
// a conditional pathname deletion or claiming that a later path still denotes
// the writer-created inode.
void write_sync_json_file_atomically_no_symlink_or_throw(
    const std::filesystem::path& final_path,
    const std::string& payload,
    const std::string& label);

// Binary payloads use the exact same capability-bound publication owner as
// JSON reports. The span is consumed synchronously and is never retained.
// This avoids manufacturing a second in-memory copy merely to publish an
// already sealed database or other byte-exact artifact.
void write_sync_file_atomically_no_symlink_or_throw(
    const std::filesystem::path& final_path,
    std::span<const unsigned char> payload,
    const std::string& label);

// Binary create-new equivalent for immutable payload/effect owners. The exact
// same retained-directory, temp-write, file-sync, atomic no-replace rename, and
// directory-sync protocol is used; an existing final entry is never replaced.
void write_sync_file_atomically_create_new_no_symlink_or_throw(
    const std::filesystem::path& final_path,
    std::span<const unsigned char> payload,
    const std::string& label);

#if !defined(_WIN32)
// Descriptor-relative immutable publication under one retained root authority.
// The relative path is traversed from the retained root descriptor without
// reopening the root by pathname. The root authority and terminal parent are
// re-proven before temp reservation, before the no-replace rename, and after
// parent-directory synchronization. A root path rebind permanently revokes the
// supplied authority and cannot redirect publication into a replacement tree.
void write_sync_file_atomically_create_new_under_directory_or_throw(
    const SyncDirectoryAuthority& root_authority,
    const std::filesystem::path& canonical_relative_path,
    std::span<const unsigned char> payload,
    const std::string& label);
#endif

// Restart reconciliation for an immutable create-new effect. Absent means no
// final directory entry was observed. ExactAndDirectorySynced means the exact
// expected bytes were read from one stable, same-owner, mode-0600,
// single-link, non-symlink regular-file identity, that file was synchronized,
// the parent directory was synchronized, and the same identities were
// re-proven afterward. ConflictingEntry means a final
// entry exists but is not that exact immutable effect. Filesystem/identity/I/O
// failures throw instead of being collapsed into a conflict or absence claim.
// The current Windows implementation can prove exact file bytes and flush the
// file handle but cannot prove parent-directory durability, so it throws rather
// than returning ExactAndDirectorySynced.
enum class SyncImmutableFileReconciliationOutcome {
    Absent,
    ExactAndDirectorySynced,
    ConflictingEntry,
};

[[nodiscard]] const char* sync_immutable_file_reconciliation_outcome_name(
    SyncImmutableFileReconciliationOutcome outcome) noexcept;

[[nodiscard]] SyncImmutableFileReconciliationOutcome
reconcile_sync_immutable_file_create_new_no_symlink_or_throw(
    const std::filesystem::path& final_path,
    std::span<const unsigned char> expected_payload,
    const std::string& label);

#if !defined(_WIN32)
// Descriptor-relative restart reconciliation under the same retained root
// authority used for publication. ExactAndDirectorySynced is returned only
// after exact file and parent identities are synchronized and re-proven from
// that root capability.
[[nodiscard]] SyncImmutableFileReconciliationOutcome
reconcile_sync_immutable_file_create_new_under_directory_or_throw(
    const SyncDirectoryAuthority& root_authority,
    const std::filesystem::path& canonical_relative_path,
    std::span<const unsigned char> expected_payload,
    const std::string& label);
#endif

// Immutable evidence must never replace an existing directory entry. This
// preflight proves, at one point in time and without mutation, that the exact
// destination parent is traversable without symlinks and that the final name is
// absent. It is an early denial only; the create-new publisher below repeats
// the proof and uses an atomic no-replace namespace operation, so a racing
// creator cannot be overwritten after preflight.
void preflight_sync_file_create_new_no_symlink_or_throw(
    const std::filesystem::path& final_path,
    const std::string& label);

// Publishes immutable JSON evidence with the same temp-write, file-sync,
// directory-sync, parent-identity, and typed-outcome protocol as the replacing
// publisher, but the namespace transition is create-new. Any existing final
// entry, including a regular file, is rejected and preserved byte-for-byte.
void write_sync_json_file_atomically_create_new_no_symlink_or_throw(
    const std::filesystem::path& final_path,
    const std::string& payload,
    const std::string& label);

// Resolves the operator-supplied path to an absolute lexically-normal path and
// delegates to the same directory-bound replacing publication owner used by
// heartbeats and ordinary reports.
void write_sync_cli_report_json_or_throw(
    const std::string& report_path,
    const std::string& payload,
    const std::string& label);

// CLI wrapper for the move-only prepared capability. The caller should build
// this object before an irreversible transition and invoke publish_or_throw()
// only after the durable outcome is known.
[[nodiscard]] SyncPreparedImmutableJsonPublication
prepare_sync_cli_immutable_json_create_new_or_throw(
    const std::string& output_path,
    std::string payload,
    const std::string& label);

// Compatibility wrappers for callers that need only a point-in-time preflight
// or a one-shot create-new publication. Cross-resource transitions should use
// the prepared capability above so the verified parent authority is retained.
void preflight_sync_cli_file_create_new_no_symlink_or_throw(
    const std::string& output_path,
    const std::string& label);
void write_sync_cli_immutable_json_create_new_or_throw(
    const std::string& output_path,
    const std::string& payload,
    const std::string& label);

}  // namespace anonsync
