#!/usr/bin/env python3
"""Generate docs/TOMBSTONES.md.

Purpose:
- keep the main numbered index lean (canonical docs only)
- provide a compact, auditable map of stable aliases (tombstones) → canonical targets

Tombstone shape is enforced separately by scripts/check_tombstones.py.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT = DOCS / "TOMBSTONES.md"

MD_PATH_RE = re.compile(r"`([^`]+?\.md)`")
LINK_RE = re.compile(r"\[[^\]]*\]\(([^)]+)\)")


def _first_heading(text: str) -> str | None:
    for line in text.splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith("#"):
            return s
        return None
    return None


def _extract_md_targets(text: str) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for m in MD_PATH_RE.finditer(text):
        t = m.group(1).strip()
        if t.endswith(".md") and t not in seen:
            out.append(t)
            seen.add(t)
    for m in LINK_RE.finditer(text):
        target = m.group(1).strip().strip("<>")
        target = target.split("#", 1)[0].split("?", 1)[0].strip()
        if target.endswith(".md") and target not in seen:
            out.append(target)
            seen.add(target)
    return out


def _rel_link(path_under_docs: Path) -> str:
    # docs/TOMBSTONES.md lives under docs/, so links are relative to docs/.
    return path_under_docs.name


def main() -> int:
    tombstones: list[tuple[Path, str, list[str]]] = []

    for p in sorted(DOCS.rglob("*.md")):
        try:
            text = p.read_text(encoding="utf-8")
        except Exception:
            continue
        h = _first_heading(text)
        if not h or not re.search(r"\bTombstone\b", h, flags=re.IGNORECASE):
            continue

        targets = _extract_md_targets(text)
        tombstones.append((p, h.lstrip("# ").strip(), targets))

    lines: list[str] = []
    lines.append("# Tombstones (non-normative aliases)")
    lines.append("")
    lines.append("**Track:** Shared")
    lines.append("")
    lines.append("<!-- generated by scripts/gen_tombstone_index.py; do not hand-edit -->")
    lines.append("")
    lines.append(
        "Tombstones preserve old references after moves/renames. They contain **no normative content**; "
        "they only point to canonical docs. Policy: `163` (artifact reference conventions)."
    )
    lines.append("")

    if not tombstones:
        lines.append("No tombstones found.")
        lines.append("")
    else:
        lines.append("| Tombstone | Points to |")
        lines.append("|---|---|")
        for p, title, targets in tombstones:
            rel = p.relative_to(DOCS)
            tomb_link = f"[`{rel.as_posix()}`]({_rel_link(rel)})" if rel.parent == Path(".") else f"`{rel.as_posix()}`"

            # Prefer a target that exists under docs/.
            canonical = ""
            for t in targets:
                # Normalize: allow bare file name, docs/foo.md, or relative.
                t_norm = t
                if t_norm.startswith("docs/"):
                    t_norm = t_norm[len("docs/"):]
                t_path = DOCS / t_norm
                if t_path.exists():
                    canonical = f"[`{t_norm}`]({t_path.name})"
                    break
            if not canonical and targets:
                canonical = "`" + targets[0] + "`"

            lines.append(f"| {tomb_link}<br/>{title} | {canonical} |")

        lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
