#!/usr/bin/env python3
"""scripts/gen_surface_anomaly_codes.py

Generate a small, human-readable surface anomaly-code list.

Determinism requirement: given identical inputs, output must be byte-for-byte identical.
"""

from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "SURFACE_ANOMALY_CODES.md"

# Import from tools/ (stdlib-only).
sys.path.insert(0, str(ROOT / "tools"))

from surface_anomaly_codes import all_codes_sorted  # type: ignore


def main() -> int:
    codes = all_codes_sorted()

    lines: list[str] = []
    lines.append("# Surface anomaly codes\n\n")
    lines.append("**Track:** Shared\n\n")
    lines.append("This file is generated by `scripts/gen_surface_anomaly_codes.py`.\n\n")
    lines.append(
        "Codes are intended to be **publishable** (small, stable) and comparable across implementations.\n"
    )
    lines.append(
        "They are designed for *notes fields* in monitoring payloads (e.g., `PublicSurfaceParitySnapshot` and `LivenessBeacon`).\n"
    )
    lines.append(
        "Context MAY follow after `:` for local debugging, but public artifacts SHOULD be able to publish only codes.\n\n"
    )

    lines.append("| code | severity | meaning |\n")
    lines.append("|---|---:|---|\n")
    for ac in codes:
        lines.append(f"| `{ac.code}` | `{ac.severity}` | {ac.summary} |\n")

    OUT.write_text("".join(lines), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
