#!/usr/bin/env python3
"""Generate docs/13-artifact-index.md from the archive tree.

The artifact index is a release-gate control surface, not a hand-written current
head note.  It must mention every canonical numbered doc so check_index.py can
catch omissions without asking maintainers to maintain a 900+ item list by hand.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
INDEX = DOCS / "13-artifact-index.md"

NUMBERED_RE = re.compile(r"^\d{1,3}[-_].*\.md$")


def is_tombstone(path: Path) -> bool:
    head = path.read_text(encoding="utf-8", errors="ignore")[:200].lower()
    return "tombstone" in head


def numbered_docs() -> list[Path]:
    return sorted(p for p in DOCS.glob("*.md") if NUMBERED_RE.match(p.name) and not is_tombstone(p))


def latest_report_globs(version_num: str) -> list[Path]:
    report_dir = ROOT / "artifacts" / "reports"
    if not report_dir.is_dir():
        return []
    patterns = [f"*rev{version_num}*.json", f"*rev{version_num}*.md", f"*rev{version_num}*.csv"]
    out: list[Path] = []
    for pat in patterns:
        out.extend(report_dir.glob(pat))
    return sorted(set(out))


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def main() -> int:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    version_num = version.removeprefix("v").zfill(4)
    docs = numbered_docs()
    latest_reports = latest_report_globs(version_num)

    lines: list[str] = []
    lines.append("# Artifact index")
    lines.append("")
    lines.append("**Track:** Shared release gate / navigation")
    lines.append("**Status:** generated release-gate artifact")
    lines.append("")
    lines.append(f"## Current head: {version}")
    lines.append("")
    lines.append("This file is generated by `scripts/gen_artifact_index.py` and checked by `scripts/check_index.py`.")
    lines.append("It intentionally lists every canonical numbered doc so the release gate cannot pass after a collapsed or stale index.")
    lines.append("")
    lines.append("Boundary: this index is a navigation and release-coherence artifact only. It is not current voter instruction, legal advice, certification evidence, production signer authority, independent validation, or live-pilot authorization.")
    lines.append("")
    lines.append("## Current-release high-risk artifacts")
    lines.append("")
    high_risk_candidates = [
        f"artifacts/examples/trust_policies/verification-policy-lockfile-ed25519-authorized-threshold2-rev{version_num}.json",
        f"artifacts/examples/trust_policies/verification-policy-lockfile-ed25519-authorized-threshold2-rev{version_num}.publication-receipt.json",
        f"artifacts/reports/release-go-no-go-decision.json",
        f"artifacts/reports/release-maintainer-handoff.json",
        f"artifacts/reports/source-review-pressure-rev{version_num}.json",
        f"artifacts/reports/current-authority-source-queue-rev{version_num}.json",
        f"artifacts/reports/platform-source-sampling-plan-rev{version_num}.json",
        f"artifacts/reports/trust-chain-fixture-surface-rev{version_num}.json",
    ]
    for item in high_risk_candidates:
        if (ROOT / item).exists():
            lines.append(f"- `{item}`")
    lines.append("")
    if latest_reports:
        lines.append(f"## Generated reports for {version}")
        lines.append("")
        for p in latest_reports:
            lines.append(f"- `{rel(p)}`")
        lines.append("")

    lines.append(f"## Canonical numbered docs ({len(docs)})")
    lines.append("")
    for p in docs:
        lines.append(f"- `{p.name}` — `{rel(p)}`")
    lines.append("")
    lines.append("## Generated-index invariants")
    lines.append("")
    lines.append(f"- `canonical_numbered_doc_count`: `{len(docs)}`")
    lines.append("- `tombstone_docs`: omitted from the canonical coverage list by design")
    lines.append("- `release_gate_check`: `scripts/check_index.py`")
    lines.append("- `release_gate_generator`: `scripts/gen_artifact_index.py`")
    lines.append("")

    INDEX.write_text("\n".join(lines), encoding="utf-8")
    print(f"WROTE {rel(INDEX)} canonical_numbered_doc_count={len(docs)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
