#!/usr/bin/env python3
"""Generate schemas/SCHEMA_CATALOG.md.

This is part of the 'no silent drift' discipline:
- schemas are normative interfaces for verifiers/clients
- the catalog makes review easier and supports external references
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "schemas"
OUT = SCHEMAS / "SCHEMA_CATALOG.md"

def file_sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

def main() -> None:
    rows = []
    for p in sorted(SCHEMAS.glob("*.json")):
        try:
            obj = json.loads(p.read_text(encoding="utf-8"))
            title = obj.get("title", p.stem)
            sid = obj.get("$id", "")
        except Exception:
            title = p.stem
            sid = ""
        rows.append((p.name, title, sid, file_sha256(p)))

    md = []
    md.append("# Schema catalog")
    md.append("")
    md.append("This file is generated by `scripts/gen_schema_catalog.py`.")
    md.append("")
    md.append("| File | Title | $id | sha256 |")
    md.append("|---|---|---|---|")
    for fn, title, sid, sha in rows:
        md.append(f"| `{fn}` | {title} | {sid} | `{sha}` |")
    OUT.write_text("\n".join(md) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} with {len(rows)} schemas.")

if __name__ == "__main__":
    main()
