#!/usr/bin/env python3
"""scripts/gen_verifier_problem_codes.py

Generate a small, human-readable verifier problem-code list.

This file is part of the anti-drift posture: it keeps verifier-facing reason codes
small, stable, and discoverable without duplicating lists across prose.

Determinism requirement: given identical inputs, output must be byte-for-byte identical.
"""

from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "VERIFIER_PROBLEM_CODES.md"

# Import from tools/ (stdlib-only).
sys.path.insert(0, str(ROOT / "tools"))

from verifier_problem_codes import all_codes_sorted  # type: ignore


def main() -> int:
    codes = all_codes_sorted()

    lines: list[str] = []
    lines.append("# Verifier problem codes\n")
    lines.append("This file is generated by `scripts/gen_verifier_problem_codes.py`.\n")
    lines.append("Codes are intended to be **publishable** (small, stable) and comparable across implementations.\n")
    lines.append("Context MAY follow after `:` for local debugging, but public reports SHOULD be able to publish only codes.\n\n")

    lines.append("| code | severity | meaning |\n")
    lines.append("|---|---:|---|\n")
    for pc in codes:
        lines.append(f"| `{pc.code}` | `{pc.severity}` | {pc.summary} |\n")

    OUT.write_text("".join(lines), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
