#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, sys
from pathlib import Path

FIELDS=['build_check_id','check','value','status','note']
EXCLUDE_NAMES={'SHA256SUMS.txt'}

def read_json(path: Path):
    try: return json.loads(path.read_text(encoding='utf-8'))
    except Exception: return {}

def add(rows, check, value, ok, note):
    rows.append({'build_check_id':f'archive_{len(rows)+1:03d}','check':check,'value':str(value),'status':'pass' if ok else 'fail','note':note})

def stable_files(root: Path):
    files=[]
    for p in sorted(root.rglob('*')):
        if not p.is_file(): continue
        if p.name in EXCLUDE_NAMES: continue
        if '__pycache__' in p.parts or p.suffix in {'.pyc','.pyo'}: continue
        files.append(str(p.relative_to(root)))
    return files

def run(root: Path):
    rows=[]; m=read_json(root/'manifest.json'); contract=read_json(root/'SCHEMA/Package-Release-Contract-current.json')
    export=m.get('export_name_without_zip','')
    add(rows,'root_directory_matches_export_name',root.name,root.name==export,'package root should match manifest export_name_without_zip')
    add(rows,'archive_posture_no_bundled_zips',sum(1 for p in root.rglob('*.zip')),not any(p.suffix.lower()=='.zip' for p in root.rglob('*')),'release package must not bundle older ZIPs')
    add(rows,'archive_posture_no_archive_dirs',sum(1 for p in root.rglob('*') if p.is_dir() and p.name.lower() in {'archive','archives'}),not any(p.is_dir() and p.name.lower() in {'archive','archives'} for p in root.rglob('*')),'release package must not include archive/archive dirs')
    files=stable_files(root)
    add(rows,'stable_file_count_excluding_checksum',len(files),len(files)>0,'stable file count excludes SHA256SUMS and Python cache artifacts')
    public_allowed=set(contract.get('allowed_public_layer_files',[])); public={str(p.relative_to(root)) for p in (root/'PUBLIC').glob('*') if p.is_file()}
    add(rows,'public_file_set_matches_contract',len(public),public==public_allowed and bool(public),'public file set should exactly match package release contract allowlist')
    add(rows,'deterministic_zip_recipe_declared',m.get('zip_determinism_policy',''),bool(m.get('zip_determinism_policy')),'manifest must declare sorted path order and normalized timestamp policy for external ZIP build')
    add(rows,'checksums_regenerated_after_reports_policy',m.get('checksum_regeneration_policy',''),bool(m.get('checksum_regeneration_policy')),'manifest must declare that SHA256SUMS is regenerated after report generation')
    return rows

def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Archive-Build-Manifest-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Archive-Build-Manifest-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n',encoding='utf-8')
    bad=[r for r in rows if r.get('status')!='pass']
    lines=['# Archive Build Manifest — current','', 'Generated by `tools/archive_build_manifest.py`.', '', f'Checks: {len(rows)}', f'Non-pass checks: {len(bad)}', '', 'This report records package-level archive-build assumptions before the external ZIP is created: root name, no bundled archives, public allowlist match, stable file count, and declared deterministic ZIP/checksum policy.', '', '| check | value | status | note |','|---|---:|---|---|']
    for r in rows: lines.append(f"| {r['check']} | {str(r['value']).replace('|','/')} | {r['status']} | {r['note'].replace('|','/')} |")
    (out/'Archive-Build-Manifest-current.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-fail', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    bad=[r for r in rows if r.get('status')!='pass']
    print(f"{'FAIL' if bad else 'PASS'} archive build manifest checks={len(rows)} nonpass={len(bad)}")
    if args.fail_on_fail and bad: sys.exit(1)
if __name__=='__main__': main()
