#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, hashlib, json, sys
from pathlib import Path

FIELDS=['member_path','package_path','size_bytes','sha256','package_zone','inclusion_scope','status','note']
SELF_OUTPUTS={
    'META/Archive-Member-Manifest-current.csv','META/Archive-Member-Manifest-current.json','META/Archive-Member-Manifest-current.md',
    'META/Generated-Artifact-Provenance-current.csv','META/Generated-Artifact-Provenance-current.json','META/Generated-Artifact-Provenance-current.md',
    'META/Release-Gate-Attestation-current.csv','META/Release-Gate-Attestation-current.json','META/Release-Gate-Attestation-current.md',
    'SCHEMA/Schema-Validation-Report-current.csv','SCHEMA/Schema-Validation-Report-current.json','SCHEMA/Schema-Validation-Report-current.md',
    'META/Release-Evidence-Closure-current.csv','META/Release-Evidence-Closure-current.json','META/Release-Evidence-Closure-current.md',
    'META/Package-Identity-Audit-current.csv','META/Package-Identity-Audit-current.json','META/Package-Identity-Audit-current.md',
}
EXCLUDED={'SHA256SUMS.txt','SHA256SUMS.txt.sig','QA-REPORT-current.txt'}

def sha(path: Path) -> str:
    h=hashlib.sha256(); h.update(path.read_bytes()); return h.hexdigest()

def read_json(path: Path):
    try: return json.loads(path.read_text(encoding='utf-8'))
    except Exception: return {}

def zone(rel: str) -> str:
    if rel.startswith('PUBLIC/'): return 'public_layer'
    if rel.startswith('GOVERNANCE/'): return 'governance_layer'
    if rel.startswith('META/'): return 'meta_audit_layer'
    if rel.startswith('SCHEMA/'): return 'schema_contract_layer'
    if rel.startswith('tools/'): return 'tooling_layer'
    if rel.startswith('CANDIDATES/'): return 'candidate_layer'
    if rel.startswith('OFFICE-CARDS/'): return 'office_card_layer'
    if rel.startswith('LONGFORM/'): return 'longform_layer'
    return 'root_handoff_layer'

def stable_files(root: Path) -> list[str]:
    out=[]
    for p in root.rglob('*'):
        if not p.is_file(): continue
        rel=str(p.relative_to(root)).replace('\\','/')
        if rel in EXCLUDED: continue
        if p.suffix.lower()=='.zip': continue
        if '__pycache__' in rel.split('/') or p.suffix.lower() in {'.pyc','.pyo'}: continue
        out.append(rel)
    return sorted(out)

def run(root: Path):
    manifest=read_json(root/'manifest.json')
    export=manifest.get('export_name_without_zip') or root.name
    rows=[]
    member_seen=set()
    for rel in stable_files(root):
        member=f'{export}/{rel}'
        status='pass'
        note='member path is package-root-prefixed and hash recorded'
        if rel in SELF_OUTPUTS:
            rows.append({'member_path':member,'package_path':rel,'size_bytes':'','sha256':'','package_zone':zone(rel),'inclusion_scope':'deferred_recursive_output','status':'pass','note':'recursive late-gate/self-output path included, with size/hash deferred to avoid report hash drift; final SHA256SUMS verifies bytes'})
            member_seen.add(member)
            continue
        unsafe = member.startswith('/') or '\\' in member or '..' in Path(member).parts or '//' in member
        if unsafe:
            status='fail'; note='unsafe archive member path shape'
        p=root/rel
        rows.append({'member_path':member,'package_path':rel,'size_bytes':str(p.stat().st_size),'sha256':sha(p),'package_zone':zone(rel),'inclusion_scope':'stable_package_file','status':status,'note':note})
        member_seen.add(member)
    # Summary duplicate check is encoded by marking all duplicate member paths if any were discovered.
    counts={}
    for r in rows: counts[r['member_path']]=counts.get(r['member_path'],0)+1
    dup={m for m,c in counts.items() if c>1}
    if dup:
        for r in rows:
            if r['member_path'] in dup:
                r['status']='fail'; r['note']='duplicate archive member path after root-prefixing'
    return rows

def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Archive-Member-Manifest-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Archive-Member-Manifest-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n',encoding='utf-8')
    bad=[r for r in rows if r.get('status')!='pass']
    deferred=sum(1 for r in rows if r.get('inclusion_scope')=='deferred_recursive_output')
    by_zone={}
    for r in rows: by_zone[r['package_zone']]=by_zone.get(r['package_zone'],0)+1
    lines=['# Archive Member Manifest — current','', 'Generated by `tools/archive_member_manifest.py`.', '', f'Members planned: {len(rows)}', f'Deferred recursive-output rows: {deferred}', f'Non-pass rows: {len(bad)}', '', 'This manifest records the intended ZIP member namespace: every stable file is rooted under `manifest.export_name_without_zip`. Late-gate/self-output files are listed with deferred size/hash values to avoid recursive hash drift; final SHA256SUMS verifies bytes.', '', '## Counts by zone', '']
    for z in sorted(by_zone): lines.append(f'- `{z}`: {by_zone[z]}')
    lines += ['', '| member_path | package_path | zone | scope | status |','|---|---|---|---|---|']
    for r in rows[:240]:
        lines.append(f"| `{r['member_path']}` | `{r['package_path']}` | {r['package_zone']} | {r['inclusion_scope']} | {r['status']} |")
    if len(rows)>240: lines.append(f'\n... {len(rows)-240} additional rows omitted from Markdown view; see CSV/JSON.')
    (out/'Archive-Member-Manifest-current.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-nonpass', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    bad=[r for r in rows if r.get('status')!='pass']
    print(f"{'FAIL' if bad else 'PASS'} archive member manifest rows={len(rows)} nonpass={len(bad)}")
    if args.fail_on_nonpass and bad: sys.exit(1)
if __name__=='__main__': main()
