#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, shutil, subprocess, sys, tempfile, zipfile
from pathlib import Path
sys.dont_write_bytecode=True
FIELDS=["check_id","check","severity","status","note"]
EXCLUDE={"SHA256SUMS.txt.sig"}
def rows_for_archive(archive: Path):
    rows=[]
    def add(check, ok, note, sev="high"):
        rows.append({"check_id":f"clean_extract_{len(rows)+1:03d}","check":check,"severity":"info" if ok else sev,"status":"pass" if ok else "fail","note":note})
    if not archive.exists():
        add("archive_exists", False, f"missing archive {archive}"); return rows
    with tempfile.TemporaryDirectory() as td:
        dest=Path(td)/"extract"; dest.mkdir()
        try:
            with zipfile.ZipFile(archive) as z:
                names=z.namelist(); z.extractall(dest)
            add("zip_extracts", True, f"members={len(names)}")
            bad=[n for n in names if any(m in n for m in ["├","║","Ã","Â","�"])]
            add("member_names_have_no_mojibake_markers", not bad, "; ".join(bad[:8]) if bad else "no mojibake markers")
            roots={n.split("/")[0] for n in names if n}
            if len(roots)==1:
                root=dest/next(iter(roots))
                proc=subprocess.run([sys.executable,"-B","tools/qa_cube.py","."], cwd=root, text=True, capture_output=True, timeout=180)
                add("qa_cube_passes_after_clean_extract", proc.returncode==0, (proc.stdout+proc.stderr)[-1000:])
            else:
                add("single_root_directory", False, f"roots={sorted(roots)}")
        except Exception as e:
            add("zip_extracts", False, f"exception: {e}")
    return rows
def write(root: Path, rows):
    out=root/"META/Clean-Extract-Archive-QA-current.csv"
    with out.open("w",encoding="utf-8",newline="") as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows(rows)
    out.with_suffix(".json").write_text(json.dumps(rows, ensure_ascii=False, indent=2)+"\n", encoding="utf-8")
    lines=["# Clean Extract Archive QA — current","", "Generated by `tools/clean_extract_archive_qa.py`.", "", "| check | severity | status | note |", "|---|---|---|---|"]
    for r in rows: lines.append(f"| {r['check']} | {r['severity']} | {r['status']} | {str(r['note']).replace('|','/').replace(chr(10),' ')[:500]} |")
    out.with_suffix(".md").write_text("\n".join(lines)+"\n", encoding="utf-8")
def main():
    ap=argparse.ArgumentParser(); ap.add_argument("archive", nargs="?"); ap.add_argument("--root", default="."); ap.add_argument("--write-report", action="store_true"); ap.add_argument("--fail-on-high", action="store_true")
    args=ap.parse_args(); root=Path(args.root).resolve()
    rows=rows_for_archive(Path(args.archive).resolve()) if args.archive else [{"check_id":"clean_extract_001","check":"archive_argument_required","severity":"info","status":"pass","note":"Run with an archive path after final ZIP creation to record extraction QA."}]
    if args.write_report: write(root, rows)
    bad=[r for r in rows if r.get("severity")=="high" and r.get("status")!="pass"]
    print(f"{'FAIL' if bad else 'PASS'} clean extract archive QA rows={len(rows)} high_fail={len(bad)}")
    if args.fail_on_high and bad: sys.exit(1)
if __name__=="__main__": main()
