#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, importlib.util, json, sys
from pathlib import Path
from collections import defaultdict

FIELDS=['cycle_id','cycle_class','path_chain','severity','status','note']


def read_artifacts(root: Path):
    gp=root/'tools/generated_artifact_provenance.py'
    try:
        spec=importlib.util.spec_from_file_location('gap_for_cycle_audit', gp)
        mod=importlib.util.module_from_spec(spec)
        assert spec and spec.loader
        spec.loader.exec_module(mod)
        return list(getattr(mod,'ARTIFACTS',[]))
    except Exception:
        rows=[]
        p=root/'META/Generated-Artifact-Provenance-current.csv'
        if p.exists():
            with p.open(encoding='utf-8', newline='') as f:
                for r in csv.DictReader(f):
                    rows.append((r.get('artifact_path',''), r.get('generator',''), [x for x in r.get('input_paths','').split('|') if x]))
        return rows


def find_cycles(graph):
    cycles=[]; visiting=[]; state={}
    def dfs(node):
        state[node]='visiting'; visiting.append(node)
        for nxt in graph.get(node,[]):
            if state.get(nxt)=='visiting':
                idx=visiting.index(nxt)
                cyc=visiting[idx:]+[nxt]
                norm='>'.join(cyc)
                # canonicalize by rotating to lexicographically first path string
                body=cyc[:-1]
                rots=['>'.join(body[i:]+body[:i]+[body[i]]) for i in range(len(body))]
                cycles.append(min(rots))
            elif state.get(nxt) is None:
                dfs(nxt)
        visiting.pop(); state[node]='done'
    for node in sorted(graph):
        if state.get(node) is None: dfs(node)
    return sorted(set(cycles))


def run(root: Path):
    arts=read_artifacts(root)
    outputs={a for a,_g,_i in arts if a}
    graph=defaultdict(set)
    edge_count=0
    for artifact, _gen, inputs in arts:
        if artifact: graph.setdefault(artifact,set())
        for inp in inputs:
            if inp in outputs and artifact:
                graph[inp].add(artifact); edge_count+=1
    cycles=find_cycles(graph)
    rows=[]
    if not cycles:
        rows.append({'cycle_id':'cycle_000','cycle_class':'no_generated_artifact_cycle','path_chain':'','severity':'info','status':'pass','note':f'no generated-artifact cycles detected across {len(outputs)} artifacts and {edge_count} generated-artifact dependency edges'})
        return rows
    for idx, chain in enumerate(cycles, start=1):
        rows.append({'cycle_id':f'cycle_{idx:03d}','cycle_class':'unapproved_generated_artifact_cycle','path_chain':chain,'severity':'high','status':'fail','note':'generated-artifact dependency cycle requires explicit bootstrap/review-only treatment before handoff'})
    return rows


def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Dependency-Cycle-Audit-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Dependency-Cycle-Audit-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n',encoding='utf-8')
    bad=[r for r in rows if r.get('severity')=='high' and r.get('status')!='pass']
    lines=['# Dependency Cycle Audit — current','', 'Generated by `tools/dependency_cycle_audit.py`.', '', f'Rows: {len(rows)}', f'High failures: {len(bad)}', '', 'This audit checks generated-artifact-to-generated-artifact dependency edges for hidden cycles. Bootstrap/self-reference loops must be explicit, not accidental.', '', '| cycle_id | cycle_class | status | path_chain | note |','|---|---|---|---|---|']
    for r in rows:
        lines.append(f"| {r['cycle_id']} | {r['cycle_class']} | {r['status']} | `{r['path_chain']}` | {r['note'].replace('|','/')} |")
    (out/'Dependency-Cycle-Audit-current.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')


def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-high', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    bad=[r for r in rows if r.get('severity')=='high' and r.get('status')!='pass']
    print(f"{'FAIL' if bad else 'PASS'} dependency cycle audit rows={len(rows)} high={len(bad)}")
    if args.fail_on_high and bad: sys.exit(1)
if __name__=='__main__': main()
