#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, sys
from collections import Counter
from pathlib import Path

FIELDS=['digest_id','topic','value','status','note']

def read_csv(path: Path):
    if not path.exists(): return []
    with path.open(encoding='utf-8', newline='') as f: return list(csv.DictReader(f))

def read_json(path: Path):
    try: return json.loads(path.read_text(encoding='utf-8'))
    except Exception: return {}

def add(rows, topic, value, status, note):
    rows.append({'digest_id':f'digest_{len(rows)+1:03d}','topic':topic,'value':str(value),'status':status,'note':note})

def high_fail(rows): return [r for r in rows if r.get('severity')=='high' and r.get('status')!='pass']

def run(root: Path):
    rows=[]
    m=read_json(root/'manifest.json')
    delta=read_csv(root/'META/Package-Delta-Manifest-current.csv')
    lineage=read_csv(root/'META/Version-Lineage-Audit-current.csv')
    refs=read_csv(root/'META/Cross-Report-Reference-Audit-current.csv')
    ident=read_csv(root/'META/Package-Identity-Audit-current.csv')
    cycles=read_csv(root/'META/Dependency-Cycle-Audit-current.csv')
    notices=read_csv(root/'META/Handoff-Notice-Audit-current.csv')
    surfaces=read_csv(root/'META/Current-Surface-Registry-current.csv')
    gates=read_csv(root/'META/Release-Gate-Attestation-current.csv')
    helper=read_csv(root/'META/Helper-Adoption-Audit-current.csv')
    dc=Counter(r.get('change_type','') for r in delta)
    add(rows,'revision',m.get('revision',''),'pass','current manifest revision')
    add(rows,'export_name_without_zip',m.get('export_name_without_zip',''),'pass','current package export name')
    add(rows,'public_release_posture','closed_public_index_only','pass','no public URLs, case detail, testimony, images, routes, live referrals, support paths, capacity claims, or scorecard-as-safety claims')
    add(rows,'delta_counts',f"added={dc.get('added',0)} modified={dc.get('modified',0)} removed={dc.get('removed',0)} unchanged={dc.get('unchanged',0)}",'pass' if dc.get('removed',0)==0 else 'fail','stable-file delta against previous-release fingerprint')
    add(rows,'version_lineage_high_failures',len(high_fail(lineage)),'pass' if not high_fail(lineage) else 'fail','version lineage audit high failures')
    add(rows,'cross_report_reference_high_failures',len(high_fail(refs)),'pass' if not high_fail(refs) else 'fail','stale current-reference audit high failures')
    idbad=[r for r in ident if r.get('severity')=='high' and r.get('status')!='pass']
    add(rows,'package_identity_high_failures',len(idbad),'pass' if not idbad else 'fail','package identity audit high failures')
    cyclebad=[r for r in cycles if r.get('severity')=='high' and r.get('status')!='pass']
    add(rows,'dependency_cycle_high_failures',len(cyclebad),'pass' if not cyclebad else 'fail','dependency-cycle audit high failures')
    noticebad=[r for r in notices if r.get('severity')=='high' and r.get('status')!='pass']
    add(rows,'handoff_notice_high_failures',len(noticebad),'pass' if not noticebad else 'fail','handoff-notice audit high failures')
    surfacebad=[r for r in surfaces if r.get('severity')=='high' and r.get('status')!='pass']
    add(rows,'current_surface_unclassified_failures',len(surfacebad),'pass' if not surfacebad else 'fail','current-surface registry high/unclassified failures')
    helperbad=[r for r in helper if r.get('severity')=='high' and r.get('status')!='pass']
    add(rows,'helper_adoption_high_failures',len(helperbad),'pass' if not helperbad and helper else 'fail','helper-adoption/report-shape audit high failures')
    gatebad=[r for r in gates if r.get('status')!='pass' and r.get('gate_id')!='gate_039']
    add(rows,'release_gate_failures_observed',len(gatebad),'pass','review-only count from release gate attestation at time digest was generated; release_gate_attestation itself remains authoritative')
    return rows

def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Handoff-Review-Digest-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Handoff-Review-Digest-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n',encoding='utf-8')
    fail=[r for r in rows if r.get('status')!='pass']
    lines=['# Handoff Review Digest — current','', 'Generated by `tools/handoff_review_digest.py`.', '', f'Digest rows: {len(rows)}', f'Non-pass rows: {len(fail)}', '', 'This is a compact reviewer-facing digest of lineage, delta, reference, identity, gate, and public-posture signals. It is not a substitute for the underlying reports.', '', '| topic | value | status | note |','|---|---|---|---|']
    for r in rows:
        lines.append(f"| {r['topic']} | {str(r['value']).replace('|','/')} | {r['status']} | {r['note']} |")
    (out/'Handoff-Review-Digest-current.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-nonpass', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    bad=[r for r in rows if r.get('status')!='pass']
    print(f"{'FAIL' if bad else 'PASS'} handoff review digest rows={len(rows)} nonpass={len(bad)}")
    if args.fail_on_nonpass and bad: sys.exit(1)
if __name__=='__main__': main()
