#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, re, sys
from pathlib import Path

FIELDS=['notice_check_id','check','file','severity','status','required_text','observed','note']
REQUIRED_NOTICE='GOVERNANCE/Handoff-Use-Limits-and-Reviewer-Notice-current.md'

PHRASES=[
    ('not_public_release_permission', r'not\s+(a\s+)?public[- ]release\s+permission'),
    ('not_referral_directory', r'not\s+a\s+referral\s+directory|must\s+not\s+be\s+used\s+as\s+a\s+live\s+referral'),
    ('not_case_list', r'not\s+a\s+case\s+list'),
    ('public_availability_not_permission', r'public\s+availability\s+is\s+not\s+permission'),
    ('closed_public_index_only', r'closed\s+public[- ]index\s+only|public\s+layer\s+remains\s+closed'),
    ('no_public_urls_or_operational_content', r'no\s+public\s+URLs.*case\s+details.*testimony.*images.*routes.*live\s+referrals'),
    ('human_review_required', r'human\s+review\s+is\s+required'),
    ('takedown_reclassification', r'takedown\s+and\s+reclassification'),
]
FRONT_DOORS=['000-START-HERE.txt','CURRENT-SPINE.md','PUBLIC/README-public-edition.md','GOVERNANCE/README-governance-current.md']


def text(root: Path, rel: str) -> str:
    p=root/rel
    return p.read_text(encoding='utf-8', errors='ignore') if p.exists() else ''


def add(rows, check, file, sev, ok, required, observed, note):
    rows.append({'notice_check_id':f'notice_{len(rows)+1:03d}','check':check,'file':file,'severity':sev if not ok else 'info','status':'pass' if ok else 'fail','required_text':required,'observed':observed,'note':note})


def run(root: Path):
    rows=[]
    notice_path=root/REQUIRED_NOTICE
    add(rows,'notice_file_exists',REQUIRED_NOTICE,'high',notice_path.exists(),REQUIRED_NOTICE,'exists' if notice_path.exists() else 'missing','handoff use-limit notice must exist')
    notice=text(root, REQUIRED_NOTICE)
    for name, pat in PHRASES:
        ok=bool(re.search(pat, notice, flags=re.I|re.S))
        add(rows,name,REQUIRED_NOTICE,'high',ok,pat,'matched' if ok else 'not found','required warning phrase must be present in handoff notice')
    for rel in FRONT_DOORS:
        t=text(root, rel)
        add(rows,'frontdoor_references_handoff_notice',rel,'high',REQUIRED_NOTICE in t,REQUIRED_NOTICE,'referenced' if REQUIRED_NOTICE in t else 'not referenced','front-door surfaces must point reviewers to the notice')
    pub=text(root,'PUBLIC/README-public-edition.md')
    add(rows,'public_readme_explicitly_closed','PUBLIC/README-public-edition.md','high',bool(re.search(r'not\s+(a\s+)?public[- ]release\s+permission', pub, flags=re.I)) and bool(re.search(r'public\s+layer\s+remains\s+closed|closed\s+public[- ]index\s+only', pub, flags=re.I)), 'not public-release permission + closed public index only','matched' if pub else 'missing','public README must not be mistaken for release permission')
    return rows


def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Handoff-Notice-Audit-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Handoff-Notice-Audit-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n',encoding='utf-8')
    bad=[r for r in rows if r.get('severity')=='high' and r.get('status')!='pass']
    lines=['# Handoff Notice Audit — current','', 'Generated by `tools/handoff_notice_audit.py`.', '', f'Rows: {len(rows)}', f'High failures: {len(bad)}', '', 'This audit prevents handoff/readme surfaces from becoming ambiguous release permission.', '', '| check | file | status | note |','|---|---|---|---|']
    for r in rows:
        lines.append(f"| {r['check']} | `{r['file']}` | {r['status']} | {r['note'].replace('|','/')} |")
    (out/'Handoff-Notice-Audit-current.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')


def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-high', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    bad=[r for r in rows if r.get('severity')=='high' and r.get('status')!='pass']
    print(f"{'FAIL' if bad else 'PASS'} handoff notice audit rows={len(rows)} high={len(bad)}")
    for r in bad[:10]: print(f"HIGH {r['check']} {r['file']}: {r['required_text']}")
    if args.fail_on_high and bad: sys.exit(1)
if __name__=='__main__': main()
