#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, sys
from collections import Counter
from pathlib import Path

FIELDS=['finding_id','json_path','object_path','duplicate_keys','severity','status','note']

class D(dict):
    pass

def hook(pairs):
    counts=Counter(k for k,_ in pairs)
    d=D()
    d.__dups__=[k for k,c in counts.items() if c>1]
    for k,v in pairs:
        d[k]=v
    return d

def add(rows, path, objpath, keys, sev, status, note):
    rows.append({'finding_id':f'jku_{len(rows)+1:04d}','json_path':path,'object_path':objpath,'duplicate_keys':'|'.join(keys),'severity':sev,'status':status,'note':note})

def walk(obj, path, rel, rows):
    if isinstance(obj, D):
        dups=getattr(obj,'__dups__',[])
        if dups:
            add(rows, rel, path or '$', sorted(dups), 'high', 'fail', 'duplicate object keys are ambiguous because standard JSON parsers silently keep the last value')
        for k,v in obj.items():
            walk(v, (path or '$') + '.' + str(k), rel, rows)
    elif isinstance(obj, list):
        for i,v in enumerate(obj):
            walk(v, f'{path or "$"}[{i}]', rel, rows)

def run(root: Path):
    rows=[]
    json_files=[p for p in sorted(root.rglob('*.json')) if '__pycache__' not in p.parts]
    for p in json_files:
        rel=str(p.relative_to(root))
        try:
            obj=json.loads(p.read_text(encoding='utf-8'), object_pairs_hook=hook)
        except Exception as e:
            add(rows, rel, '$', [], 'high', 'fail', f'JSON parse failed: {e}')
            continue
        before=len(rows)
        walk(obj, '$', rel, rows)
        if len(rows)==before:
            add(rows, rel, '$', [], 'info', 'pass', 'JSON parsed and no duplicate object keys were detected')
    if not json_files:
        add(rows, '.', '$', [], 'high', 'fail', 'no JSON files found')
    return rows

def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'JSON-Key-Uniqueness-Audit-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'JSON-Key-Uniqueness-Audit-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    high=sum(1 for r in rows if r.get('severity')=='high')
    lines=['# JSON Key Uniqueness Audit — current','', 'Generated by `tools/json_key_uniqueness_audit.py`.', '', f'JSON files/objects reviewed: {len(rows)}', f'High findings: {high}', '', 'Duplicate JSON keys are blocked because they make handoff metadata parser-dependent.', '', '| json_path | object_path | severity | status | duplicate_keys | note |','|---|---|---|---|---|---|']
    for r in rows[:220]:
        note=(r.get('note','') or '').replace('|','/').replace('\n',' ')
        lines.append(f"| `{r['json_path']}` | `{r['object_path']}` | {r['severity']} | {r['status']} | `{r['duplicate_keys']}` | {note} |")
    if len(rows)>220: lines.append(f'\n... {len(rows)-220} additional rows omitted from Markdown view.')
    (out/'JSON-Key-Uniqueness-Audit-current.md').write_text('\n'.join(lines)+'\n', encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-high', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    high=[r for r in rows if r.get('severity')=='high']
    print(f"{'FAIL' if high else 'PASS'} JSON key uniqueness rows={len(rows)} high={len(high)}")
    for r in high[:20]: print(f"HIGH {r['json_path']} {r['object_path']}: {r['duplicate_keys']}")
    if args.fail_on_high and high: sys.exit(1)
if __name__=='__main__': main()
