#!/usr/bin/env python3
from __future__ import annotations
"""Shared helpers for LivingChristFigures cube audit/report tools.

The helpers intentionally stay tiny and dependency-free: deterministic CSV/JSON
row I/O, stable Markdown table rendering, package-relative path handling, and
common high/fail row predicates.  Generator scripts set sys.dont_write_bytecode
before importing this module so helper adoption does not create __pycache__
artifacts in release builds.
"""
import csv
import json
from pathlib import Path
from typing import Iterable, Mapping, Sequence


def package_rel(root: Path, path: Path) -> str:
    """Return a forward-slash package-relative path."""
    return str(path.relative_to(root)).replace('\\', '/')


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(encoding='utf-8', newline='') as f:
        return list(csv.DictReader(f))


def read_csv_header(path: Path) -> list[str]:
    if not path.exists():
        return []
    with path.open(encoding='utf-8', newline='') as f:
        try:
            return next(csv.reader(f), [])
        except StopIteration:
            return []


def read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding='utf-8'))
    except Exception:
        return None


def safe_md(value) -> str:
    return str(value if value is not None else '').replace('|', '/').replace('\n', ' ')


def shape_rows(rows: Iterable[Mapping[str, object]], fields: Sequence[str]) -> list[dict[str, str]]:
    return [{field: str(row.get(field, '') if row.get(field, '') is not None else '') for field in fields} for row in rows]


def write_csv_json_md_report(
    root: Path,
    csv_rel: str,
    fields: Sequence[str],
    rows: Iterable[Mapping[str, object]],
    title: str,
    generated_by: str,
    columns: Sequence[str] | None = None,
    intro_lines: Sequence[str] | None = None,
    max_md_rows: int = 240,
) -> None:
    """Write deterministic CSV, JSON, and Markdown companions for a row report."""
    shaped = shape_rows(list(rows), fields)
    csv_path = root / csv_rel
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open('w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=list(fields))
        writer.writeheader()
        writer.writerows(shaped)
    csv_path.with_suffix('.json').write_text(json.dumps(shaped, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

    cols = list(columns or fields)
    lines = [f'# {title} — current', '', f'Generated by `{generated_by}`.', '']
    if intro_lines:
        lines.extend([safe_md(x) for x in intro_lines])
        lines.append('')
    lines.append('| ' + ' | '.join(cols) + ' |')
    lines.append('| ' + ' | '.join(['---'] * len(cols)) + ' |')
    for row in shaped[:max_md_rows]:
        lines.append('| ' + ' | '.join(safe_md(row.get(col, '')) for col in cols) + ' |')
    if len(shaped) > max_md_rows:
        lines.append('')
        lines.append(f'... {len(shaped) - max_md_rows} additional rows omitted from Markdown view; see CSV/JSON companions.')
    csv_path.with_suffix('.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')


def high_or_fail(rows: Iterable[Mapping[str, str]]) -> list[Mapping[str, str]]:
    out=[]
    for row in rows:
        if row.get('severity') == 'high' or row.get('status') == 'fail':
            out.append(row)
    return out



def csv_row_count(path: Path) -> int:
    """Return data-row count for a CSV file, excluding the header."""
    if not path.exists():
        return 0
    with path.open(encoding='utf-8', newline='') as f:
        return max(0, sum(1 for _ in csv.reader(f)) - 1)


def current_csv_surfaces(root: Path) -> list[str]:
    """Return sorted package-relative paths for all *-current.csv surfaces."""
    out=[]
    for p in sorted(root.rglob('*-current.csv')):
        rel=package_rel(root, p)
        parts=rel.split('/')
        if '__pycache__' in parts:
            continue
        out.append(rel)
    return out


def expected_field_schema_path(rel: str) -> str:
    """Infer the dedicated field-schema path for a current CSV surface."""
    name=Path(rel).name
    if name.endswith('-current.csv'):
        return 'SCHEMA/' + name[:-len('-current.csv')] + '-Fields-current.csv'
    return ''


def read_generated_artifact_specs(root: Path) -> dict[str, str]:
    """Return artifact_path -> generator from tools/generated_artifact_provenance.py when importable."""
    import importlib.util
    gp=root/'tools/generated_artifact_provenance.py'
    out={}
    try:
        spec=importlib.util.spec_from_file_location('gap_for_lib_cube', gp)
        mod=importlib.util.module_from_spec(spec)
        assert spec and spec.loader
        spec.loader.exec_module(mod)
        for artifact, generator, _inputs in getattr(mod, 'ARTIFACTS', []):
            out[artifact]=generator
    except Exception:
        pass
    if not out:
        for row in read_csv_rows(root/'META/Generated-Artifact-Provenance-current.csv'):
            if row.get('artifact_path'):
                out[row.get('artifact_path','')]=row.get('generator','')
    return out
