#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, hashlib, json, sys
from collections import Counter
from pathlib import Path

FIELDS=['delta_id','path','change_type','previous_sha256','current_sha256','previous_size_bytes','current_size_bytes','severity','status','note']
EXCLUDE={
    'SHA256SUMS.txt','SHA256SUMS.txt.sig','QA-REPORT-current.txt',
    'META/Package-Delta-Manifest-current.csv','META/Package-Delta-Manifest-current.json','META/Package-Delta-Manifest-current.md',
    'META/Generated-Artifact-Provenance-current.csv','META/Generated-Artifact-Provenance-current.json','META/Generated-Artifact-Provenance-current.md',
    'META/Release-Gate-Attestation-current.csv','META/Release-Gate-Attestation-current.json','META/Release-Gate-Attestation-current.md',
    'META/Release-Evidence-Closure-current.csv','META/Release-Evidence-Closure-current.json','META/Release-Evidence-Closure-current.md',
    'META/Handoff-Review-Digest-current.csv','META/Handoff-Review-Digest-current.json','META/Handoff-Review-Digest-current.md',
    'SCHEMA/Schema-Validation-Report-current.csv','SCHEMA/Schema-Validation-Report-current.json','SCHEMA/Schema-Validation-Report-current.md',
}
KNOWN_RENAMES={'CANDIDATES/Sonia-Bermúdez-Gente-como-Uno-People-Like-Us-cemetery.txt':'CANDIDATES/Sonia-Bermudez-Gente-como-Uno-People-Like-Us-cemetery.txt'}

def sha(p: Path) -> str:
    h=hashlib.sha256(); h.update(p.read_bytes()); return h.hexdigest()

def stable_files(root: Path):
    out=[]
    for p in root.rglob('*'):
        if not p.is_file(): continue
        rel=str(p.relative_to(root)).replace('\\','/')
        if rel in EXCLUDE: continue
        if p.suffix.lower()=='.zip': continue
        if '__pycache__' in rel.split('/') or p.suffix.lower() in {'.pyc','.pyo'}: continue
        out.append(rel)
    return sorted(out)

def read_json(path: Path):
    try: return json.loads(path.read_text(encoding='utf-8'))
    except Exception: return {}

def run(root: Path):
    prev=read_json(root/'META/Previous-Release-Fingerprint-current.json')
    prev_map={r.get('path',''):r for r in prev.get('stable_files',[]) if r.get('path') and r.get('path') not in EXCLUDE}
    cur_paths=stable_files(root)
    cur_map={rel:{'sha256':sha(root/rel),'size_bytes':(root/rel).stat().st_size} for rel in cur_paths}
    handled_new=set()
    rows=[]
    for old_rel,new_rel in KNOWN_RENAMES.items():
        if old_rel in prev_map and new_rel in cur_map:
            old=prev_map[old_rel]; cur=cur_map[new_rel]; handled_new.add(new_rel)
            rows.append({'delta_id':f'delta_{len(rows)+1:04d}','path':old_rel+' -> '+new_rel,'change_type':'renamed','previous_sha256':old.get('sha256',''),'current_sha256':cur.get('sha256',''),'previous_size_bytes':str(old.get('size_bytes','')),'current_size_bytes':str(cur.get('size_bytes','')),'severity':'info','status':'pass','note':'approved rev0065 ASCII package-path normalization; display name remains Unicode in content'})
    all_paths=sorted((set(prev_map)|set(cur_map))-set(KNOWN_RENAMES)-handled_new)
    for rel in all_paths:
        old=prev_map.get(rel); cur=cur_map.get(rel)
        if old and cur:
            change='unchanged' if old.get('sha256')==cur.get('sha256') else 'modified'
        elif cur and not old:
            change='added'
        else:
            change='removed'
        sev='high' if change=='removed' else 'info'
        status='fail' if change=='removed' else 'pass'
        note={'unchanged':'stable file unchanged from previous release','modified':'file changed since previous release and is accounted for in this delta manifest','added':'new stable file added in current release','removed':'stable file present in previous release is missing from current release'}[change]
        rows.append({'delta_id':f'delta_{len(rows)+1:04d}','path':rel,'change_type':change,'previous_sha256':(old or {}).get('sha256',''),'current_sha256':(cur or {}).get('sha256',''),'previous_size_bytes':str((old or {}).get('size_bytes','')),'current_size_bytes':str((cur or {}).get('size_bytes','')),'severity':sev,'status':status,'note':note})
    return rows

def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Package-Delta-Manifest-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Package-Delta-Manifest-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n',encoding='utf-8')
    counts=Counter(r['change_type'] for r in rows)
    lines=['# Package Delta Manifest — current','', 'Generated by `tools/package_delta_manifest.py`.', '', f'Rows: {len(rows)}', f'Added: {counts.get("added",0)}', f'Modified: {counts.get("modified",0)}', f'Unchanged: {counts.get("unchanged",0)}', f'Removed/fail: {counts.get("removed",0)}', '', 'This report compares the current stable package scope against `META/Previous-Release-Fingerprint-current.json`; it is an accountability surface, not public-release permission.', '', '| path | change_type | status | note |','|---|---|---|---|']
    changed=[x for x in rows if x['change_type']!='unchanged']
    for r in changed[:260]:
        lines.append(f"| `{r['path']}` | {r['change_type']} | {r['status']} | {r['note']} |")
    if len(changed)>260: lines.append('\n... additional changed rows omitted from Markdown view; see CSV/JSON.')
    (out/'Package-Delta-Manifest-current.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-removed', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    removed=[r for r in rows if r.get('change_type')=='removed']
    print(f"{'FAIL' if removed else 'PASS'} package delta rows={len(rows)} removed={len(removed)}")
    if args.fail_on_removed and removed: sys.exit(1)
if __name__=='__main__': main()
