#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, re, sys
from pathlib import Path
from collections import defaultdict

sys.dont_write_bytecode = True
from public_template_policy import NEAR_HARM, DEATH_WORDS, SERVICE_WORDS, ROUTE_WORDS, POLICY_WORDS, choose_public_shape_template, split_pipe

FIELDS = [
    'candidate_id','candidate_name','public_export_tier','public_shape_template',
    'highest_harm_proximity','most_restrictive_public_link_policy',
    'consent_or_governance_gate','live_referral_gate','capacity_gate','source_link_gate',
    'image_gate','case_detail_gate','public_url_release','public_claim_release',
    'required_review','review_note'
]

TIER_ALLOWED = {
    'public_index_shape_only',
    'boundary_index_shape_only',
    'policy_context_only',
    'quarantined_no_public_expansion',
}

RESTRICTIVE_LINK_RANK = {
    'internal_only_contact_rich': 0,
    'internal_only_case_extractable': 0,
    'internal_only_testimony_rich': 0,
    'internal_only_image_sensitive': 0,
    'boundary_note_required_or_internal_only': 1,
    'boundary_note_required': 2,
    'public_link_allowed_with_boundary_note': 3,
    'public_link_allowed': 4,
    '': 5,
}


def read_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open(encoding='utf-8', newline='') as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8', newline='') as f:
        w=csv.DictWriter(f, fieldnames=fields); w.writeheader(); w.writerows([{k:r.get(k,'') for k in fields} for r in rows])


def write_json(path: Path, rows: list[dict]) -> None:
    path.write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')


def write_md(path: Path, rows: list[dict]) -> None:
    lines=['# Public Export Eligibility — current','',
           'Generated by `tools/public_export_eligibility.py`. This ledger is an eligibility gate, not publication approval. It classifies the safest currently allowed public shape for each candidate and names the review gates that remain before any public prose expansion or public URL release.',
           '', f'Rows: {len(rows)}', '']
    fields=['candidate_id','public_export_tier','public_shape_template','public_url_release','public_claim_release','required_review','review_note']
    lines.append('| ' + ' | '.join(fields) + ' |')
    lines.append('| ' + ' | '.join(['---']*len(fields)) + ' |')
    for r in rows:
        vals=[str(r.get(f,'')).replace('|','/').replace('\n',' ')[:220] for f in fields]
        lines.append('| ' + ' | '.join(vals) + ' |')
    path.write_text('\n'.join(lines)+'\n', encoding='utf-8')


def strongest_link_policy(policies: list[str]) -> str:
    if not policies:
        return 'public_link_allowed_with_boundary_note'
    ranked=sorted(policies, key=lambda p: RESTRICTIVE_LINK_RANK.get(p, 1))
    return ranked[0] or 'public_link_allowed_with_boundary_note'


def classify_candidate(cand: dict, sources: list[dict], governance_row: dict | None) -> dict:
    harm=set()
    policies=[]
    for s in sources:
        harm.update(split_pipe(s.get('harm_proximity','')))
        policies.append(s.get('public_link_policy',''))
    strongest=strongest_link_policy(policies)
    template=choose_public_shape_template(cand, harm, governance_row)
    text=' '.join([cand.get('name',''), cand.get('office',''), cand.get('sensitivity',''), cand.get('status_current',''), cand.get('capacity_state','')])
    live_referral_gate = 'pass_non_referral_index_only' if cand.get('live_referral_safe') == 'false' else 'requires_special_live_referral_review'
    capacity_gate = 'block_current_capacity_language' if re.search(r'(?i)current|capacity|available|service|referral|shelter|helpline|hotline|outreach|implementation', text) else 'no_current_capacity_claim'
    source_link_gate = 'internal_only_or_manual_review' if strongest.startswith('internal_only') or strongest=='boundary_note_required_or_internal_only' else ('boundary_note_required' if 'boundary' in strongest else 'public_link_allowed_with_review')
    image_gate = 'images_blocked_by_default' if (DEATH_WORDS.search(text) or 'image_or_vigil_near' in harm or 'MMIWG' in text or 'Red Dress' in text) else 'no_images_in_public_index'
    case_detail_gate = 'block_case_detail_or_person_record_extraction' if (harm & NEAR_HARM or DEATH_WORDS.search(text) or SERVICE_WORDS.search(text) or ROUTE_WORDS.search(text)) else 'block_non_load_bearing_personal_detail'
    if governance_row:
        tier='quarantined_no_public_expansion'
        consent_gate='governance_row_requires_manual_family_or_community_review_before_expansion'
        public_claim='boundary_index_only_no_prose_expansion'
        review='family_or_community_governance_review_before_public_expansion'
    elif SERVICE_WORDS.search(text) or ROUTE_WORDS.search(text) or DEATH_WORDS.search(text) or harm & NEAR_HARM:
        tier='boundary_index_shape_only'
        consent_gate='no_specific_consent_record; boundary_index_only'
        public_claim='safe_index_shape_only_after_renderer'
        review='manual_review_before_any_public_prose_expansion'
    elif POLICY_WORDS.search(text):
        tier='policy_context_only'
        consent_gate='no_specific_consent_record; policy_context_only'
        public_claim='policy_context_only_not_safety_or_completion'
        review='manual_review_before_public_prose_expansion'
    else:
        tier='public_index_shape_only'
        consent_gate='no_specific_consent_record; index_shape_only'
        public_claim='safe_index_shape_only_after_renderer'
        review='manual_review_before_full_public_publication'
    url_release = 'no_public_urls_without_manual_link_review' if source_link_gate != 'public_link_allowed_with_review' else 'boundary_note_required_for_any_public_url'
    if tier == 'quarantined_no_public_expansion':
        url_release = 'internal_only_until_governance_review'
    note_parts=[
        f'template={template}',
        f'link_gate={source_link_gate}',
        f'capacity_gate={capacity_gate}',
    ]
    if governance_row:
        note_parts.append('explicit_governance_quarantine_not_template_identity')
    if harm:
        note_parts.append('harm=' + '|'.join(sorted(harm))[:120])
    return {
        'candidate_id': cand.get('candidate_id',''),
        'candidate_name': cand.get('name',''),
        'public_export_tier': tier,
        'public_shape_template': template,
        'highest_harm_proximity': '|'.join(sorted(harm)) if harm else 'not_recorded',
        'most_restrictive_public_link_policy': strongest,
        'consent_or_governance_gate': consent_gate,
        'live_referral_gate': live_referral_gate,
        'capacity_gate': capacity_gate,
        'source_link_gate': source_link_gate,
        'image_gate': image_gate,
        'case_detail_gate': case_detail_gate,
        'public_url_release': url_release,
        'public_claim_release': public_claim,
        'required_review': review,
        'review_note': '; '.join(note_parts),
    }


def run(root: Path) -> list[dict]:
    candidates=read_csv(root/'Candidate-Ledger-current.csv')
    source_rows=read_csv(root/'Source-Registry-current.csv')
    consent_rows={r.get('candidate_id',''): r for r in read_csv(root/'GOVERNANCE/Family-Consent-and-Case-Name-Use-Ledger-current.csv')}
    by_cand=defaultdict(list)
    for s in source_rows:
        for cid in split_pipe(s.get('candidate_ids','')):
            by_cand[cid].append(s)
    rows=[]
    for cand in candidates:
        cid=cand.get('candidate_id','')
        rows.append(classify_candidate(cand, by_cand.get(cid, []), consent_rows.get(cid)))
    return rows


def write_reports(root: Path, rows: list[dict]) -> None:
    out=root/'META'
    write_csv(out/'Public-Export-Eligibility-current.csv', rows, FIELDS)
    write_json(out/'Public-Export-Eligibility-current.json', rows)
    write_md(out/'Public-Export-Eligibility-current.md', rows)


def main() -> None:
    ap=argparse.ArgumentParser()
    ap.add_argument('root', nargs='?', default='.')
    ap.add_argument('--write-report', action='store_true')
    ap.add_argument('--json', action='store_true')
    args=ap.parse_args()
    root=Path(args.root).resolve()
    rows=run(root)
    if args.write_report:
        write_reports(root, rows)
    if args.json:
        print(json.dumps(rows, ensure_ascii=False, indent=2))
    else:
        tiers={t:0 for t in sorted(TIER_ALLOWED)}
        for r in rows:
            tiers[r['public_export_tier']]=tiers.get(r['public_export_tier'],0)+1
        print('public_export_eligibility_rows=' + str(len(rows)) + ' ' + ' '.join(f'{k}={v}' for k,v in sorted(tiers.items())))

if __name__ == '__main__':
    main()
