#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, sys
from pathlib import Path
FIELDS=['finding_id','severity','check','file','row','status','detail','remediation']

def read_json(path: Path):
    try: return json.loads(path.read_text(encoding='utf-8'))
    except Exception: return None

def read_csv(path: Path):
    if not path.exists(): return []
    with path.open(encoding='utf-8', newline='') as f: return list(csv.DictReader(f))

def add(rows, sev, check, file, row, status, detail, remediation):
    rows.append({'finding_id':f'rdc_{len(rows)+1:04d}','severity':sev,'check':check,'file':file,'row':str(row),'status':status,'detail':detail,'remediation':remediation})

def exists(root: Path, rel: str) -> bool:
    return bool(rel) and (root/rel).exists()

def run(root: Path):
    rows=[]; manifest=read_json(root/'manifest.json') or {}; contract=read_json(root/'SCHEMA/Package-Release-Contract-current.json') or {}; pub=read_json(root/'PUBLIC/PUBLIC-EXPORT-MANIFEST-current.json') or {}
    rev=manifest.get('revision','')
    front=['000-START-HERE.txt','CURRENT-SPINE.md','CUBE-MAP.md','CUBE-RULES.txt','LivingChristFigures.txt','manifest.json','PUBLIC/README-public-edition.md','SCHEMA/README-schema-current.md','META/README-meta-instruments-current.md','GOVERNANCE/README-governance-current.md','tools/README.md']
    for rel in front:
        if not exists(root, rel): add(rows,'high','required_frontdoor_exists',rel,0,'missing','front-door/current README missing','restore or deliberately remove from required-document set')
        else: add(rows,'info','required_frontdoor_exists',rel,0,'pass','front-door/current README exists','none')
    # Revision-bearing surfaces should contain current revision, except static ethics docs.
    for rel in ['000-START-HERE.txt','CURRENT-SPINE.md','CUBE-MAP.md','CUBE-RULES.txt','PUBLIC/README-public-edition.md','SCHEMA/Package-Release-Contract-current.json','PUBLIC/PUBLIC-EXPORT-MANIFEST-current.json']:
        if exists(root, rel):
            txt=(root/rel).read_text(encoding='utf-8', errors='ignore')
            add(rows,'info' if rev and rev in txt else 'high','required_revision_surface_current',rel,0,'pass' if rev and rev in txt else 'missing_current_revision',f'{rev} present in revision-bearing surface' if rev and rev in txt else f'{rev} missing from revision-bearing surface','update front-door revision surface')
    allowed=set(contract.get('allowed_public_layer_files',[])); public={str(p.relative_to(root)) for p in (root/'PUBLIC').glob('*') if p.is_file()}
    if allowed==public and allowed:
        add(rows,'info','public_contract_file_set','PUBLIC/',0,'pass',f'public file set exactly matches {len(allowed)} allowed files','none')
    else:
        add(rows,'high','public_contract_file_set','PUBLIC/',0,'drift',f'public_only={sorted(public-allowed)} allowed_only={sorted(allowed-public)}','synchronize Package-Release-Contract-current.json and PUBLIC/ file set')
    for key, rel in (contract.get('governance_layer') or {}).items():
        add(rows,'info' if exists(root,rel) else 'high','contract_governance_path_exists',rel,0,'pass' if exists(root,rel) else 'missing',f'governance_layer.{key} path exists' if exists(root,rel) else f'governance_layer.{key} path missing','update contract or restore file')
    # Generated provenance outputs should be triads when named as current CSV reports.
    for i,r in enumerate(read_csv(root/'META/Generated-Artifact-Provenance-current.csv'), start=2):
        art=r.get('artifact_path','')
        if art.endswith('-current.csv'):
            base=art[:-4]
            missing=[base+'.json', base+'.md']
            miss=[x for x in missing if not exists(root,x)]
            add(rows,'info' if not miss else 'high','generated_artifact_companions',art,i,'pass' if not miss else 'missing_companion', 'generated CSV has JSON/Markdown companions' if not miss else 'missing: '+ '; '.join(miss),'write or regenerate report companions')
    if not any(r['severity']=='high' for r in rows):
        add(rows,'info','required_document_coverage','.',0,'pass',f'PASS required documents, contract paths, public allowlist, and generated companions verified for {rev}','none')
    return rows

def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Required-Document-Coverage-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Required-Document-Coverage-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n',encoding='utf-8')
    high=sum(1 for r in rows if r.get('severity')=='high')
    lines=['# Required Document Coverage — current','', 'Generated by `tools/required_document_coverage.py`.', '', f'Rows: {len(rows)}', f'High findings: {high}', '', '| finding_id | severity | check | file | status | detail |','|---|---|---|---|---|---|']
    for r in rows[:260]: lines.append(f"| {r['finding_id']} | {r['severity']} | {r['check']} | `{r['file']}` | {r['status']} | {(r['detail'] or '').replace('|','/')} |")
    if len(rows)>260: lines.append(f'\n... {len(rows)-260} additional rows omitted from Markdown view; see CSV/JSON.')
    (out/'Required-Document-Coverage-current.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-high', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    high=[r for r in rows if r.get('severity')=='high']
    print(f"{'FAIL' if high else 'PASS'} required-document coverage rows={len(rows)} high={len(high)}")
    if args.fail_on_high and high: sys.exit(1)
if __name__=='__main__': main()
