#!/usr/bin/env python3
from __future__ import annotations
import argparse, subprocess, sys
from pathlib import Path
sys.dont_write_bytecode=True
# The rev0065 governance surfaces are generated during the patch/build pass. This tool
# verifies that the surfaces exist and can be regenerated by rerunning the package patcher.
# It intentionally does not crawl sources or contact anyone.
REQUIRED=[
 'META/Source-Freshness-Preservation-current.csv',
 'META/Source-Preservation-Status-current.csv',
 'META/Evidence-Debt-Sprint-current.csv',
 'GOVERNANCE/Permission-State-Ledger-current.csv',
 'META/Office-Accountability-current.csv',
 'META/Controlled-Vocabulary-Normalization-current.csv',
 'META/Normalized-Code-Overlay-current.csv',
 'META/Public-Lint-Allowed-Contexts-current.csv',
 'META/Path-Rename-Ledger-current.csv',
 'META/Clean-Extract-Archive-QA-current.csv',
 'META/Helper-Adoption-Scope-current.csv',
 'META/Helper-Golden-Output-Audit-current.csv'
]
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-high', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); missing=[r for r in REQUIRED if not (root/r).exists()]
    print(('FAIL' if missing else 'PASS')+' rev0065 governance surfaces present')
    for r in missing: print('missing '+r)
    if args.fail_on_high and missing: sys.exit(1)
if __name__=='__main__': main()
