#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, re, sys
from pathlib import Path

FIELDS=['severity','check','file','line','match','detail']
REV_RE=re.compile(r'rev[0-9]{4}')
HEADER_PATTERNS=[re.compile(r'current\s+rev([0-9]{4})', re.I), re.compile(r'current\s+revision:\s*rev([0-9]{4})', re.I), re.compile(r'as\s+of\s+rev([0-9]{4})', re.I), re.compile(r'^rev([0-9]{4})\s+current note', re.I), re.compile(r'^#\s+.*?rev([0-9]{4})', re.I), re.compile(r'^.*?—\s*rev([0-9]{4})', re.I)]
FRONT_DOOR=[
    '000-START-HERE.txt','LivingChristFigures.txt','CUBE-MAP.md','CUBE-RULES.txt','CURRENT-SPINE.md',
    'PUBLIC/README-public-edition.md','PUBLIC/PUBLIC-EXPORT-MANIFEST-current.json',
    'SCHEMA/Package-Release-Contract-current.json','manifest.json'
]
JSON_REV_FIELDS={
    'manifest.json':['revision','package_revision'],
    'PUBLIC/PUBLIC-EXPORT-MANIFEST-current.json':['revision','package_revision'],
    'SCHEMA/Package-Release-Contract-current.json':['package_revision','revision_updated'],
}

def row(sev, check, file, line, match, detail):
    return {'severity':sev,'check':check,'file':file,'line':str(line),'match':match,'detail':detail}

def current_rev(root: Path) -> str:
    try:
        return json.loads((root/'manifest.json').read_text(encoding='utf-8')).get('revision','')
    except Exception:
        return ''

def run(root: Path):
    cur=current_rev(root)
    rows=[]
    if not cur:
        return [row('high','current_revision_read','manifest.json',0,'','manifest revision missing or unreadable')]
    for rel in FRONT_DOOR:
        p=root/rel
        if not p.exists():
            rows.append(row('high','frontdoor_exists',rel,0,'','front-door file missing'))
            continue
        text=p.read_text(encoding='utf-8', errors='ignore')
        lines=text.splitlines()
        # First lines/headings of front-door files should reflect the current package revision.
        for i, line in enumerate(lines[:20], start=1):
            for pat in HEADER_PATTERNS:
                m=pat.search(line)
                if m:
                    got='rev'+m.group(1)
                    if got != cur:
                        rows.append(row('high','frontdoor_header_revision_current',rel,i,line.strip(),f'{got} != {cur}'))
        if rel in JSON_REV_FIELDS:
            try:
                data=json.loads(text)
                for key in JSON_REV_FIELDS[rel]:
                    if data.get(key) != cur:
                        rows.append(row('high','json_revision_field_current',rel,0,key,f'{key}={data.get(key)!r} != {cur!r}'))
            except Exception as e:
                rows.append(row('high','json_revision_parse',rel,0,'',str(e)))
    if not rows:
        rows.append(row('info','revision_surface_audit','.',0,cur,'PASS front-door revision surface matches manifest revision'))
    return rows

def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Revision-Surface-Audit-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Revision-Surface-Audit-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n',encoding='utf-8')
    high=sum(1 for r in rows if r.get('severity')=='high')
    lines=['# Revision Surface Audit — current','', 'Generated by `tools/revision_surface_audit.py`.', '', f'High findings: {high}', '']
    if high:
        lines.append('## Findings')
        for r in rows:
            if r.get('severity')=='high':
                lines.append(f"- `{r.get('file')}` line {r.get('line')}: {r.get('detail')} ({r.get('match')})")
    else:
        lines.append('PASS: current front-door revision surface matches `manifest.json`.')
    (out/'Revision-Surface-Audit-current.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-high', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    for r in rows: print(f"{r.get('severity','?').upper()} {r.get('check')} {r.get('file')}: {r.get('detail')}")
    if args.fail_on_high and any(r.get('severity')=='high' for r in rows): sys.exit(1)
if __name__=='__main__': main()
