#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, sys
from pathlib import Path

FIELDS=['boundary_id','reviewed_surface','role_boundary','required_signal','severity','status','note']
REQUIRED_SIGNALS=[
    ('role_boundary_doc_exists','GOVERNANCE/Review-Role-and-Handoff-Boundaries-current.md','review role boundary','review authority does not transfer reuse rights'),
    ('operator_boundary','GOVERNANCE/Review-Role-and-Handoff-Boundaries-current.md','operator/editor boundary','operator may edit the package but may not override family, community, or consent limits'),
    ('reviewer_boundary','GOVERNANCE/Review-Role-and-Handoff-Boundaries-current.md','reviewer boundary','reviewer may evaluate release readiness but may not convert the cube into a referral directory'),
    ('public_reader_boundary','GOVERNANCE/Review-Role-and-Handoff-Boundaries-current.md','public-reader boundary','public reader is not a referral recipient'),
    ('family_authority_boundary','GOVERNANCE/Review-Role-and-Handoff-Boundaries-current.md','family/community authority boundary','family or community review authority is not implied by public-source availability'),
    ('start_here_pointer','000-START-HERE.txt','front-door pointer','GOVERNANCE/Review-Role-and-Handoff-Boundaries-current.md'),
    ('current_spine_pointer','CURRENT-SPINE.md','spine pointer','GOVERNANCE/Review-Role-and-Handoff-Boundaries-current.md'),
    ('governance_readme_pointer','GOVERNANCE/README-governance-current.md','governance index pointer','Review-Role-and-Handoff-Boundaries-current.md'),
    ('public_readme_boundary','PUBLIC/README-public-edition.md','public reader boundary','not public-release permission'),
    ('contract_gate_pointer','SCHEMA/Package-Release-Contract-current.json','contract gate pointer','review_role_boundary_audit_gate'),
]

def add(rows, bid, surface, role, signal, sev, status, note):
    rows.append({'boundary_id':bid,'reviewed_surface':surface,'role_boundary':role,'required_signal':signal,'severity':sev,'status':status,'note':note})

def run(root: Path):
    rows=[]
    for idx,(name, rel, role, signal) in enumerate(REQUIRED_SIGNALS, start=1):
        p=root/rel
        bid=f'rrb_{idx:03d}_{name}'
        if not p.exists():
            add(rows,bid,rel,role,signal,'high','fail','required review-role boundary surface is missing')
            continue
        text=p.read_text(encoding='utf-8', errors='ignore').lower()
        ok=signal.lower() in text
        add(rows,bid,rel,role,signal,'info' if ok else 'high','pass' if ok else 'fail','required signal is present' if ok else 'required signal is absent')
    return rows

def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Review-Role-Boundary-Audit-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Review-Role-Boundary-Audit-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    high=sum(1 for r in rows if r.get('severity')=='high')
    lines=['# Review Role Boundary Audit — current','', 'Generated by `tools/review_role_boundary_audit.py`.', '', f'Boundary checks: {len(rows)}', f'High findings: {high}', '', 'This audit prevents handoff review roles from being mistaken for consent, service capacity, referral authority, or public reuse permission.', '', '| boundary_id | surface | role_boundary | severity | status | required_signal |','|---|---|---|---|---|---|']
    for r in rows:
        sig=(r.get('required_signal','') or '').replace('|','/').replace('\n',' ')
        lines.append(f"| {r['boundary_id']} | `{r['reviewed_surface']}` | {r['role_boundary']} | {r['severity']} | {r['status']} | `{sig}` |")
    (out/'Review-Role-Boundary-Audit-current.md').write_text('\n'.join(lines)+'\n', encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-high', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    high=[r for r in rows if r.get('severity')=='high']
    print(f"{'FAIL' if high else 'PASS'} review-role boundary rows={len(rows)} high={len(high)}")
    for r in high[:20]: print(f"HIGH {r['reviewed_surface']} missing {r['required_signal']}")
    if args.fail_on_high and high: sys.exit(1)
if __name__=='__main__': main()
