#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, sys
from pathlib import Path

FIELDS=['coverage_id','gate_id','gate_name','covered_by_selftest','selftest_ids','coverage_status','note']
REQUIRED_COVERAGE={
    'gate_003':('row_validation_zero_high',['selftest_005'],'row-contract failure injection'),
    'gate_004':('public_release_lint_zero_high',['selftest_001'],'public raw-URL leak injection'),
    'gate_010':('revision_surface_zero_high',['selftest_003'],'stale front-door revision injection'),
    'gate_012':('public_layer_contract_closed',['selftest_006'],'unallowlisted PUBLIC file injection'),
    'gate_016':('csv_json_mirror_audit_zero_high',['selftest_002'],'CSV/JSON mirror cell drift injection'),
    'gate_020':('path_reference_audit_zero_high',['selftest_004'],'missing path reference injection'),
    'gate_064':('public_index_semantic_audit_zero_high_fail',['selftest_007','selftest_008'],'public quarantine semantic canary plus domain-template overreach canary'),
}

def read_csv(path: Path):
    if not path.exists(): return []
    with path.open(encoding='utf-8', newline='') as f: return list(csv.DictReader(f))

def run(root: Path):
    selftests=read_csv(root/'META/Audit-Selftest-current.csv')
    passed={r.get('selftest_id','') for r in selftests if r.get('status')=='pass'}
    rows=[]
    for idx,(gate,(name,tests,note)) in enumerate(REQUIRED_COVERAGE.items(), start=1):
        ok=all(t in passed for t in tests)
        rows.append({'coverage_id':f'selftest_cov_{idx:03d}','gate_id':gate,'gate_name':name,'covered_by_selftest':'yes' if ok else 'no','selftest_ids':'|'.join(tests),'coverage_status':'pass' if ok else 'fail','note':note if ok else 'missing or failing selftest(s): '+ '; '.join([t for t in tests if t not in passed])})
    return rows

def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Selftest-Coverage-Matrix-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Selftest-Coverage-Matrix-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n',encoding='utf-8')
    bad=[r for r in rows if r.get('coverage_status')!='pass']
    lines=['# Selftest Coverage Matrix — current','', 'Generated by `tools/selftest_coverage_matrix.py`.', '', f'Covered gates: {len(rows)}', f'Non-pass coverage rows: {len(bad)}', '', 'This matrix records which critical release gates currently have controlled-mutation coverage. It intentionally covers a focused set of high-risk validators rather than pretending all gates can be mutation-tested cheaply.', '', '| gate | gate_name | coverage_status | selftests |','|---|---|---|---|']
    for r in rows: lines.append(f"| {r['gate_id']} | {r['gate_name']} | {r['coverage_status']} | `{r['selftest_ids']}` |")
    (out/'Selftest-Coverage-Matrix-current.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-missing', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    bad=[r for r in rows if r.get('coverage_status')!='pass']
    print(f"{'FAIL' if bad else 'PASS'} selftest coverage rows={len(rows)} nonpass={len(bad)}")
    if args.fail_on_missing and bad: sys.exit(1)
if __name__=='__main__': main()
