#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, importlib.util, json, re, sys
from pathlib import Path
FIELDS=['tool_path','tool_role','declared_outputs','included_in_provenance','included_in_dependency_graph','included_in_release_gate','qa_direct_check','status','note']

def read_csv(path: Path):
    if not path.exists(): return []
    with path.open(encoding='utf-8', newline='') as f: return list(csv.DictReader(f))

def provenance(root: Path):
    out={}
    gp=root/'tools/generated_artifact_provenance.py'
    try:
        spec=importlib.util.spec_from_file_location('gap', gp); mod=importlib.util.module_from_spec(spec); assert spec and spec.loader; spec.loader.exec_module(mod)
        for art, gen, inputs in getattr(mod,'ARTIFACTS',[]): out.setdefault(gen,[]).append(art)
    except Exception:
        for r in read_csv(root/'META/Generated-Artifact-Provenance-current.csv'):
            out.setdefault(r.get('generator',''),[]).append(r.get('artifact_path',''))
    return out

def release_gate_tools(root: Path):
    txt=(root/'tools/release_gate_attestation.py').read_text(encoding='utf-8', errors='ignore') if (root/'tools/release_gate_attestation.py').exists() else ''
    return set(re.findall(r'tools/[A-Za-z0-9_\-]+\.py', txt))

def qa_tools(root: Path):
    txt=(root/'tools/qa_cube.py').read_text(encoding='utf-8', errors='ignore') if (root/'tools/qa_cube.py').exists() else ''
    return set(re.findall(r'tools/[A-Za-z0-9_\-]+\.py', txt)) | {'tools/qa_cube.py'}

def dep_tools(root: Path):
    rows=read_csv(root/'META/Package-Dependency-Graph-current.csv')
    return {r.get('target_path','') for r in rows if r.get('target_path','').startswith('tools/')} | {r.get('source_path','') for r in rows if r.get('source_path','').startswith('tools/')} | {r.get('generator','') for r in rows if r.get('generator','').startswith('tools/')}

def role_for(path: str, outputs: list[str]):
    name=Path(path).name
    if path=='tools/qa_cube.py': return 'package_qa_runner'
    if path=='tools/schema_validate.py': return 'schema_validator'
    if outputs: return 'generated_report_builder'
    if name in {'public_contract_check.py'}: return 'checker'
    return 'checker_or_helper'

def run(root: Path):
    prov=provenance(root); gate=release_gate_tools(root); qa=qa_tools(root); deps=dep_tools(root)
    rows=[]
    for p in sorted((root/'tools').glob('*.py')):
        rel=str(p.relative_to(root)); outs=sorted([x for x in prov.get(rel,[]) if x])
        role=role_for(rel, outs)
        in_prov='yes' if outs else 'no'
        in_dep='yes' if rel in deps else 'no'
        in_gate='yes' if rel in gate or outs else 'no'
        qa_check='yes' if rel in qa or rel in {'tools/qa_cube.py','tools/schema_validate.py'} else 'no'
        if role=='generated_report_builder' and in_prov!='yes':
            status='missing_provenance'
        elif in_dep!='yes':
            status='missing_dependency_inventory'
        else:
            status='pass'
        note='tool is inventoried as generator/checker; generated outputs are listed where applicable'
        rows.append({'tool_path':rel,'tool_role':role,'declared_outputs':'|'.join(outs),'included_in_provenance':in_prov,'included_in_dependency_graph':in_dep,'included_in_release_gate':in_gate,'qa_direct_check':qa_check,'status':status,'note':note})
    return rows

def write_reports(root: Path, rows):
    out=root/'META'; out.mkdir(exist_ok=True)
    with (out/'Tool-Run-Matrix-current.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows([{k:r.get(k,'') for k in FIELDS} for r in rows])
    (out/'Tool-Run-Matrix-current.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2)+'\n',encoding='utf-8')
    bad=[r for r in rows if r.get('status')!='pass']
    lines=['# Tool Run Matrix — current','', 'Generated by `tools/tool_run_matrix.py`.', '', f'Tools: {len(rows)}', f'Non-pass rows: {len(bad)}', '', '| tool | role | status | outputs |','|---|---|---|---|']
    for r in rows:
        lines.append(f"| `{r['tool_path']}` | {r['tool_role']} | {r['status']} | `{r['declared_outputs']}` |")
    (out/'Tool-Run-Matrix-current.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('root', nargs='?', default='.'); ap.add_argument('--write-report', action='store_true'); ap.add_argument('--fail-on-nonpass', action='store_true')
    args=ap.parse_args(); root=Path(args.root).resolve(); rows=run(root)
    if args.write_report: write_reports(root, rows)
    bad=[r for r in rows if r.get('status')!='pass']
    print(f"{'FAIL' if bad else 'PASS'} tool-run matrix tools={len(rows)} nonpass={len(bad)}")
    if args.fail_on_nonpass and bad: sys.exit(1)
if __name__=='__main__': main()
