#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

FIXTURES = [
    {
        'name': 'fixturelab-home',
        'payload': {
            'adapter': 'fixturelab',
            'url': 'http://127.0.0.1:8765/',
            'title': 'GlassTTY Fixture Lab',
            'prompt': 'hello from fixture lab',
            'latest_output': 'fixture-lab response placeholder',
            'selection': '',
            'candidates': {
                'inputs': [{'selector_hint': '[data-glasstty-role="prompt"]', 'score': 1, 'text_length': 22, 'visible': True}],
                'outputs': [{'selector_hint': '[data-glasstty-role="latest-output"]', 'score': 1, 'text_length': 32, 'visible': True}],
            },
            'html_samples': {
                'prompt': '<textarea data-glasstty-role="prompt">hello from fixture lab</textarea>',
                'latest_output': '<article data-glasstty-role="latest-output">fixture-lab response placeholder</article>',
            },
            'metadata': {'generator': 'seed-fixture-corpus'},
        },
    },
    {
        'name': 'fixturelab-contenteditable',
        'payload': {
            'adapter': 'fixturelab',
            'url': 'http://127.0.0.1:8765/contenteditable',
            'title': 'GlassTTY Fixture Lab — contenteditable',
            'prompt': 'hello from contenteditable lab',
            'latest_output': 'contenteditable placeholder',
            'selection': '',
            'candidates': {
                'inputs': [{'selector_hint': '[data-glasstty-role="prompt"]', 'score': 1, 'text_length': 30, 'visible': True}],
                'outputs': [{'selector_hint': '[data-glasstty-role="latest-output"]', 'score': 1, 'text_length': 27, 'visible': True}],
            },
            'html_samples': {
                'prompt': '<div data-glasstty-role="prompt" contenteditable="true">hello from contenteditable lab</div>',
                'latest_output': '<article data-glasstty-role="latest-output">contenteditable placeholder</article>',
            },
            'metadata': {'generator': 'seed-fixture-corpus'},
        },
    },
    {
        'name': 'fixturelab-thread',
        'payload': {
            'adapter': 'fixturelab',
            'url': 'http://127.0.0.1:8765/thread',
            'title': 'GlassTTY Fixture Lab — thread',
            'prompt': 'draft in thread fixture',
            'latest_output': 'newest assistant response in thread fixture',
            'selection': '',
            'candidates': {
                'inputs': [{'selector_hint': '[data-glasstty-role="prompt"]', 'score': 1, 'text_length': 23, 'visible': True}],
                'outputs': [{'selector_hint': '[data-glasstty-role="latest-output"]', 'score': 1, 'text_length': 41, 'visible': True}],
            },
            'html_samples': {
                'prompt': '<textarea data-glasstty-role="prompt">draft in thread fixture</textarea>',
                'latest_output': '<article data-glasstty-role="latest-output">newest assistant response in thread fixture</article>',
            },
            'metadata': {'generator': 'seed-fixture-corpus'},
        },
    },
    {
        'name': 'fixturelab-dialog-live',
        'payload': {
            'adapter': 'fixturelab',
            'url': 'http://127.0.0.1:8765/dialog-form',
            'title': 'GlassTTY Fixture Lab — dialog form',
            'prompt': 'Draft inside dialog',
            'latest_output': 'Dialog saved state',
            'selection': '',
            'candidates': {
                'inputs': [{
                    'selector_hint': '[data-glasstty-role="prompt"]',
                    'score': 1,
                    'text_length': 19,
                    'visible': True,
                    'label_text': 'Message',
                    'labels': ['Message'],
                    'accessible_name': 'Message',
                    'accessible_names': ['Message'],
                    'fieldset_legend': 'Composer',
                    'fieldset_legends': ['Composer'],
                    'dialog_name': 'Profile settings',
                    'dialog_role': 'dialog',
                    'dialog_modal': True,
                    'dialog_open': True,
                    'control_kind': 'textarea',
                    'form_name': 'Profile settings',
                    'form_action': 'http://127.0.0.1:8765/dialog-form/save',
                    'form_method': 'post',
                }],
                'outputs': [{
                    'selector_hint': '[data-glasstty-role="latest-output"]',
                    'score': 1,
                    'text_length': 18,
                    'visible': True,
                    'dialog_name': 'Profile settings',
                    'dialog_role': 'dialog',
                }],
            },
            'html_samples': {
                'prompt': '<textarea data-glasstty-role="prompt">Draft inside dialog</textarea>',
                'latest_output': '<article data-glasstty-role="latest-output">Dialog saved state</article>',
                'submit': '<button data-glasstty-role="submit" type="submit">Save</button>',
            },
            'metadata': {
                'generator': 'seed-fixture-corpus',
                'top_input_label': 'Message',
                'top_input_accessible_name': 'Message',
                'top_fieldset_legend': 'Composer',
                'top_dialog_name': 'Profile settings',
                'top_form_name': 'Profile settings',
                'top_submit_label': 'Save',
                'top_submit_action': 'http://127.0.0.1:8765/dialog-form/save',
                'submit_candidates': [{
                    'selector_hint': '[data-glasstty-role="submit"]',
                    'score': 1,
                    'text_length': 4,
                    'visible': True,
                    'accessible_name': 'Save',
                    'text_sample': 'Save',
                    'dialog_name': 'Profile settings',
                    'dialog_role': 'dialog',
                    'dialog_modal': True,
                    'dialog_open': True,
                    'control_kind': 'button',
                    'form_name': 'Profile settings',
                    'form_action': 'http://127.0.0.1:8765/dialog-form/save',
                    'form_method': 'post',
                    'submit_action': 'http://127.0.0.1:8765/dialog-form/save',
                    'submit_method': 'post',
                }],
                'semantic_outline': {
                    'heading_outline': ['Dialog lab'],
                    'prompt_labels': ['Message'],
                    'accessible_names': ['Message'],
                    'prompt_descriptions': [],
                    'submit_labels': ['Save'],
                    'form_names': ['Profile settings'],
                    'form_actions': ['http://127.0.0.1:8765/dialog-form/save'],
                    'fieldset_legends': ['Composer'],
                    'dialog_names': ['Profile settings'],
                    'iframe_names': [],
                    'iframe_titles': [],
                    'control_kinds': ['textarea'],
                    'option_labels': [],
                    'choice_groups': [],
                    'autocomplete_tokens': [],
                    'state_flags': [],
                    'constraint_hints': [],
                    'link_hosts': ['127.0.0.1:8765'],
                },
                'dialog_samples': [{
                    'selectorHint': 'dialog#profile-dialog',
                    'name': 'Profile settings',
                    'role': 'dialog',
                    'modal': True,
                    'open': True,
                }],
                'iframe_samples': [],
                'form_actions': ['http://127.0.0.1:8765/dialog-form/save'],
                'dialog_count': 1,
                'iframe_count': 0,
            },
        },
    },
    {
        'name': 'fixturelab-iframe-live',
        'payload': {
            'adapter': 'fixturelab',
            'url': 'http://127.0.0.1:8765/iframe-shell',
            'title': 'GlassTTY Fixture Lab — iframe shell',
            'prompt': '4242424242424242',
            'latest_output': 'Saved 4242',
            'selection': '',
            'candidates': {
                'inputs': [{
                    'selector_hint': '[data-glasstty-role="prompt"]',
                    'score': 1,
                    'text_length': 16,
                    'visible': True,
                    'label_text': 'Card number',
                    'labels': ['Card number'],
                    'accessible_name': 'Card number',
                    'accessible_names': ['Card number'],
                    'fieldset_legend': 'Embedded card',
                    'fieldset_legends': ['Embedded card'],
                    'control_kind': 'input:text',
                    'form_name': 'Embedded composer',
                    'form_action': 'http://127.0.0.1:8765/iframe-compose/save',
                    'form_method': 'post',
                    'frame_selector': 'iframe#billing-frame',
                    'frame_name': 'billing-frame',
                    'frame_title': 'Billing details',
                    'frame_path': 'iframe#billing-frame',
                    'frame_depth': 1,
                    'frame_path_selectors': ['iframe#billing-frame'],
                    'frame_path_names': ['billing-frame'],
                    'frame_path_titles': ['Billing details'],
                }],
                'outputs': [{
                    'selector_hint': '[data-glasstty-role="latest-output"]',
                    'score': 1,
                    'text_length': 10,
                    'visible': True,
                    'frame_selector': 'iframe#billing-frame',
                    'frame_name': 'billing-frame',
                    'frame_title': 'Billing details',
                    'frame_path': 'iframe#billing-frame',
                    'frame_depth': 1,
                    'frame_path_selectors': ['iframe#billing-frame'],
                }],
            },
            'html_samples': {
                'prompt': '<input id="iframe-prompt" name="cardNumber" data-glasstty-role="prompt" value="4242424242424242" />',
                'latest_output': '<article data-glasstty-role="latest-output">Saved 4242</article>',
                'submit': '<button data-glasstty-role="submit" type="button">Save card</button>',
            },
            'metadata': {
                'generator': 'seed-fixture-corpus',
                'accessible_iframe_count': 1,
                'blocked_iframe_count': 0,
                'traversed_document_count': 2,
                'max_frame_depth': 1,
                'frame_paths': ['iframe#billing-frame'],
                'top_input_label': 'Card number',
                'top_input_accessible_name': 'Card number',
                'top_fieldset_legend': 'Embedded card',
                'top_form_name': 'Embedded composer',
                'top_input_frame_path': 'iframe#billing-frame',
                'top_input_frame_depth': 1,
                'top_submit_label': 'Save card',
                'top_submit_action': 'http://127.0.0.1:8765/iframe-compose/save',
                'top_submit_frame_path': 'iframe#billing-frame',
                'submit_candidates': [{
                    'selector_hint': '[data-glasstty-role="submit"]',
                    'score': 1,
                    'text_length': 9,
                    'visible': True,
                    'accessible_name': 'Save card',
                    'text_sample': 'Save card',
                    'control_kind': 'button',
                    'form_name': 'Embedded composer',
                    'form_action': 'http://127.0.0.1:8765/iframe-compose/save',
                    'form_method': 'post',
                    'submit_action': 'http://127.0.0.1:8765/iframe-compose/save',
                    'submit_method': 'post',
                    'frame_selector': 'iframe#billing-frame',
                    'frame_name': 'billing-frame',
                    'frame_title': 'Billing details',
                    'frame_path': 'iframe#billing-frame',
                    'frame_depth': 1,
                    'frame_path_selectors': ['iframe#billing-frame'],
                    'frame_path_names': ['billing-frame'],
                    'frame_path_titles': ['Billing details'],
                }],
                'semantic_outline': {
                    'heading_outline': ['GlassTTY Fixture Lab — iframe shell', 'GlassTTY Fixture Lab — iframe compose'],
                    'prompt_labels': ['Card number'],
                    'accessible_names': ['Card number'],
                    'prompt_descriptions': [],
                    'submit_labels': ['Save card'],
                    'form_names': ['Embedded composer'],
                    'form_actions': ['http://127.0.0.1:8765/iframe-compose/save'],
                    'fieldset_legends': ['Embedded card'],
                    'dialog_names': [],
                    'iframe_names': ['billing-frame'],
                    'iframe_titles': ['Billing details'],
                    'frame_paths': ['iframe#billing-frame'],
                    'control_kinds': ['input:text'],
                    'option_labels': [],
                    'choice_groups': [],
                    'autocomplete_tokens': [],
                    'state_flags': [],
                    'constraint_hints': [],
                    'link_hosts': ['127.0.0.1:8765'],
                },
                'iframe_samples': [{
                    'selectorHint': 'iframe#billing-frame',
                    'name': 'billing-frame',
                    'title': 'Billing details',
                    'src': '/iframe-compose',
                    'resolvedSrc': 'http://127.0.0.1:8765/iframe-compose',
                    'accessible': True,
                    'depth': 1,
                    'framePath': 'iframe#billing-frame',
                    'framePathSelectors': ['iframe#billing-frame'],
                }],
                'form_actions': ['http://127.0.0.1:8765/iframe-compose/save'],
            },
        },
    },
    {
        'name': 'fixturelab-iframe-split-live',
        'payload': {
            'adapter': 'fixturelab',
            'url': 'http://127.0.0.1:8765/iframe-split-shell',
            'title': 'GlassTTY Fixture Lab — iframe split shell',
            'prompt': 'Need billing follow-up',
            'latest_output': 'Top-level billing summary is current',
            'selection': '',
            'candidates': {
                'inputs': [{
                    'selector_hint': '[data-glasstty-role="prompt"]',
                    'score': 1,
                    'text_length': 22,
                    'visible': True,
                    'label_text': 'Draft note',
                    'labels': ['Draft note'],
                    'accessible_name': 'Draft note',
                    'accessible_names': ['Draft note'],
                    'fieldset_legend': 'Embedded draft composer',
                    'fieldset_legends': ['Embedded draft composer'],
                    'control_kind': 'textarea',
                    'form_name': 'Embedded split composer',
                    'form_action': 'http://127.0.0.1:8765/iframe-split-compose/save',
                    'form_method': 'post',
                    'frame_selector': 'iframe#billing-split-frame',
                    'frame_name': 'billing-split-frame',
                    'frame_title': 'Billing draft frame',
                    'frame_path': 'iframe#billing-split-frame',
                    'frame_depth': 1,
                    'frame_path_selectors': ['iframe#billing-split-frame'],
                    'frame_path_names': ['billing-split-frame'],
                    'frame_path_titles': ['Billing draft frame'],
                }],
                'outputs': [{
                    'selector_hint': '[data-glasstty-role="latest-output"]',
                    'score': 1,
                    'text_length': 35,
                    'visible': True,
                    'text_sample': 'Top-level billing summary is current',
                    'control_kind': 'article',
                }],
            },
            'html_samples': {
                'prompt': '<textarea id="split-iframe-prompt" data-glasstty-role="prompt">Need billing follow-up</textarea>',
                'latest_output': '<article data-glasstty-role="latest-output">Top-level billing summary is current</article>',
                'submit': '<button data-glasstty-role="submit" type="button">Queue follow-up</button>',
            },
            'metadata': {
                'generator': 'seed-fixture-corpus',
                'accessible_iframe_count': 1,
                'blocked_iframe_count': 0,
                'traversed_document_count': 2,
                'max_frame_depth': 1,
                'frame_paths': ['iframe#billing-split-frame'],
                'split_scope_detected': True,
                'top_input_label': 'Draft note',
                'top_input_accessible_name': 'Draft note',
                'top_fieldset_legend': 'Embedded draft composer',
                'top_form_name': 'Embedded split composer',
                'top_input_frame_path': 'iframe#billing-split-frame',
                'top_input_frame_depth': 1,
                'top_output_label': 'Top-level billing summary is current',
                'top_output_frame_path': None,
                'top_output_frame_depth': None,
                'top_submit_label': 'Queue follow-up',
                'top_submit_action': 'http://127.0.0.1:8765/iframe-split-compose/save',
                'top_submit_frame_path': 'iframe#billing-split-frame',
                'submit_candidates': [{
                    'selector_hint': '[data-glasstty-role="submit"]',
                    'score': 1,
                    'text_length': 15,
                    'visible': True,
                    'accessible_name': 'Queue follow-up',
                    'text_sample': 'Queue follow-up',
                    'control_kind': 'button',
                    'form_name': 'Embedded split composer',
                    'form_action': 'http://127.0.0.1:8765/iframe-split-compose/save',
                    'form_method': 'post',
                    'submit_action': 'http://127.0.0.1:8765/iframe-split-compose/save',
                    'submit_method': 'post',
                    'frame_selector': 'iframe#billing-split-frame',
                    'frame_name': 'billing-split-frame',
                    'frame_title': 'Billing draft frame',
                    'frame_path': 'iframe#billing-split-frame',
                    'frame_depth': 1,
                    'frame_path_selectors': ['iframe#billing-split-frame'],
                    'frame_path_names': ['billing-split-frame'],
                    'frame_path_titles': ['Billing draft frame'],
                }],
                'semantic_outline': {
                    'heading_outline': ['GlassTTY Fixture Lab — iframe split shell', 'GlassTTY Fixture Lab — iframe split compose'],
                    'prompt_labels': ['Draft note'],
                    'accessible_names': ['Draft note'],
                    'prompt_descriptions': [],
                    'submit_labels': ['Queue follow-up'],
                    'form_names': ['Embedded split composer'],
                    'form_actions': ['http://127.0.0.1:8765/iframe-split-compose/save'],
                    'fieldset_legends': ['Embedded draft composer'],
                    'dialog_names': [],
                    'iframe_names': ['billing-split-frame'],
                    'iframe_titles': ['Billing draft frame'],
                    'frame_paths': ['iframe#billing-split-frame'],
                    'control_kinds': ['textarea', 'article'],
                    'option_labels': [],
                    'choice_groups': [],
                    'autocomplete_tokens': [],
                    'state_flags': [],
                    'constraint_hints': [],
                    'link_hosts': ['127.0.0.1:8765'],
                },
                'iframe_samples': [{
                    'selectorHint': 'iframe#billing-split-frame',
                    'name': 'billing-split-frame',
                    'title': 'Billing draft frame',
                    'src': '/iframe-split-compose',
                    'resolvedSrc': 'http://127.0.0.1:8765/iframe-split-compose',
                    'accessible': True,
                    'depth': 1,
                    'framePath': 'iframe#billing-split-frame',
                    'framePathSelectors': ['iframe#billing-split-frame'],
                }],
                'form_actions': ['http://127.0.0.1:8765/iframe-split-compose/save'],
            },
        },
    },
    {
        'name': 'fixturelab-iframe-nested-live',
        'payload': {
            'adapter': 'fixturelab',
            'url': 'http://127.0.0.1:8765/iframe-nested-shell',
            'title': 'GlassTTY Fixture Lab — iframe nested shell',
            'prompt': '5555444433331111',
            'latest_output': 'Nested saved 1111',
            'selection': '',
            'candidates': {
                'inputs': [{
                    'selector_hint': '[data-glasstty-role="prompt"]',
                    'score': 1,
                    'text_length': 16,
                    'visible': True,
                    'label_text': 'Card number',
                    'labels': ['Card number'],
                    'accessible_name': 'Card number',
                    'accessible_names': ['Card number'],
                    'fieldset_legend': 'Nested card editor',
                    'fieldset_legends': ['Nested card editor'],
                    'control_kind': 'input:text',
                    'form_name': 'Nested billing details',
                    'form_action': 'http://127.0.0.1:8765/iframe-nested-compose/save',
                    'form_method': 'post',
                    'frame_selector': 'iframe#card-frame',
                    'frame_name': 'card-frame',
                    'frame_title': 'Card editor frame',
                    'frame_path': 'iframe#settings-frame >> iframe#card-frame',
                    'frame_depth': 2,
                    'frame_path_selectors': ['iframe#settings-frame', 'iframe#card-frame'],
                    'frame_path_names': ['settings-frame', 'card-frame'],
                    'frame_path_titles': ['Settings shell', 'Card editor frame'],
                }],
                'outputs': [{
                    'selector_hint': '[data-glasstty-role="latest-output"]',
                    'score': 1,
                    'text_length': 17,
                    'visible': True,
                    'frame_selector': 'iframe#card-frame',
                    'frame_name': 'card-frame',
                    'frame_title': 'Card editor frame',
                    'frame_path': 'iframe#settings-frame >> iframe#card-frame',
                    'frame_depth': 2,
                    'frame_path_selectors': ['iframe#settings-frame', 'iframe#card-frame'],
                }],
            },
            'html_samples': {
                'prompt': '<input id="nested-card-number" name="cardNumber" data-glasstty-role="prompt" value="5555444433331111" />',
                'latest_output': '<article data-glasstty-role="latest-output">Nested saved 1111</article>',
                'submit': '<button data-glasstty-role="submit" type="button">Save nested card</button>',
            },
            'metadata': {
                'generator': 'seed-fixture-corpus',
                'accessible_iframe_count': 2,
                'blocked_iframe_count': 0,
                'traversed_document_count': 3,
                'max_frame_depth': 2,
                'frame_paths': ['iframe#settings-frame', 'iframe#settings-frame >> iframe#card-frame'],
                'top_input_label': 'Card number',
                'top_input_accessible_name': 'Card number',
                'top_fieldset_legend': 'Nested card editor',
                'top_form_name': 'Nested billing details',
                'top_input_frame_path': 'iframe#settings-frame >> iframe#card-frame',
                'top_input_frame_depth': 2,
                'top_submit_label': 'Save nested card',
                'top_submit_action': 'http://127.0.0.1:8765/iframe-nested-compose/save',
                'top_submit_frame_path': 'iframe#settings-frame >> iframe#card-frame',
                'submit_candidates': [{
                    'selector_hint': '[data-glasstty-role="submit"]',
                    'score': 1,
                    'text_length': 16,
                    'visible': True,
                    'accessible_name': 'Save nested card',
                    'text_sample': 'Save nested card',
                    'control_kind': 'button',
                    'form_name': 'Nested billing details',
                    'form_action': 'http://127.0.0.1:8765/iframe-nested-compose/save',
                    'form_method': 'post',
                    'submit_action': 'http://127.0.0.1:8765/iframe-nested-compose/save',
                    'submit_method': 'post',
                    'frame_selector': 'iframe#card-frame',
                    'frame_name': 'card-frame',
                    'frame_title': 'Card editor frame',
                    'frame_path': 'iframe#settings-frame >> iframe#card-frame',
                    'frame_depth': 2,
                    'frame_path_selectors': ['iframe#settings-frame', 'iframe#card-frame'],
                    'frame_path_names': ['settings-frame', 'card-frame'],
                    'frame_path_titles': ['Settings shell', 'Card editor frame'],
                }],
                'semantic_outline': {
                    'heading_outline': ['GlassTTY Fixture Lab — iframe nested shell', 'GlassTTY Fixture Lab — iframe nested middle', 'GlassTTY Fixture Lab — iframe nested compose'],
                    'prompt_labels': ['Card number'],
                    'accessible_names': ['Card number'],
                    'prompt_descriptions': [],
                    'submit_labels': ['Save nested card'],
                    'form_names': ['Nested billing details'],
                    'form_actions': ['http://127.0.0.1:8765/iframe-nested-compose/save'],
                    'fieldset_legends': ['Nested card editor'],
                    'dialog_names': [],
                    'iframe_names': ['settings-frame', 'card-frame'],
                    'iframe_titles': ['Settings shell', 'Card editor frame'],
                    'frame_paths': ['iframe#settings-frame', 'iframe#settings-frame >> iframe#card-frame'],
                    'control_kinds': ['input:text'],
                    'option_labels': [],
                    'choice_groups': [],
                    'autocomplete_tokens': [],
                    'state_flags': [],
                    'constraint_hints': [],
                    'link_hosts': ['127.0.0.1:8765'],
                },
                'iframe_samples': [{
                    'selectorHint': 'iframe#settings-frame',
                    'name': 'settings-frame',
                    'title': 'Settings shell',
                    'src': '/iframe-nested-middle',
                    'resolvedSrc': 'http://127.0.0.1:8765/iframe-nested-middle',
                    'accessible': True,
                    'depth': 1,
                    'framePath': 'iframe#settings-frame',
                    'framePathSelectors': ['iframe#settings-frame'],
                }, {
                    'selectorHint': 'iframe#card-frame',
                    'name': 'card-frame',
                    'title': 'Card editor frame',
                    'src': '/iframe-nested-compose',
                    'resolvedSrc': 'http://127.0.0.1:8765/iframe-nested-compose',
                    'accessible': True,
                    'depth': 2,
                    'framePath': 'iframe#settings-frame >> iframe#card-frame',
                    'framePathSelectors': ['iframe#settings-frame', 'iframe#card-frame'],
                }],
                'form_actions': ['http://127.0.0.1:8765/iframe-nested-compose/save'],
            },
        },
    },

    {
        'name': 'fixturelab-iframe-partial-live',
        'payload': {
            'adapter': 'fixturelab',
            'url': 'http://127.0.0.1:8765/iframe-partial-shell',
            'title': 'GlassTTY Fixture Lab — iframe partial shell',
            'prompt': 'Accessible draft note',
            'latest_output': 'Saved accessible draft',
            'selection': '',
            'candidates': {
                'inputs': [{
                    'selector_hint': '[data-glasstty-role="prompt"]',
                    'score': 1,
                    'text_length': 21,
                    'visible': True,
                    'label_text': 'Billing note',
                    'labels': ['Billing note'],
                    'accessible_name': 'Billing note',
                    'accessible_names': ['Billing note'],
                    'fieldset_legend': 'Accessible billing draft',
                    'fieldset_legends': ['Accessible billing draft'],
                    'control_kind': 'textarea',
                    'form_name': 'Partial billing composer',
                    'form_action': 'http://127.0.0.1:8765/iframe-partial-compose/save',
                    'form_method': 'post',
                    'frame_selector': 'iframe#accessible-frame',
                    'frame_name': 'accessible-frame',
                    'frame_title': 'Accessible billing frame',
                    'frame_path': 'iframe#accessible-frame',
                    'frame_depth': 1,
                    'frame_path_selectors': ['iframe#accessible-frame'],
                    'frame_path_names': ['accessible-frame'],
                    'frame_path_titles': ['Accessible billing frame'],
                }],
                'outputs': [{
                    'selector_hint': '[data-glasstty-role="latest-output"]',
                    'score': 1,
                    'text_length': 22,
                    'visible': True,
                    'frame_selector': 'iframe#accessible-frame',
                    'frame_name': 'accessible-frame',
                    'frame_title': 'Accessible billing frame',
                    'frame_path': 'iframe#accessible-frame',
                    'frame_depth': 1,
                    'frame_path_selectors': ['iframe#accessible-frame'],
                    'frame_path_names': ['accessible-frame'],
                    'frame_path_titles': ['Accessible billing frame'],
                    'text_sample': 'Saved accessible draft',
                }],
            },
            'html_samples': {
                'prompt': '<textarea id="partial-iframe-prompt" data-glasstty-role="prompt">Accessible draft note</textarea>',
                'latest_output': '<article data-glasstty-role="latest-output">Saved accessible draft</article>',
                'submit': '<button data-glasstty-role="submit" type="button">Save accessible draft</button>',
            },
            'metadata': {
                'generator': 'seed-fixture-corpus',
                'iframe_count': 2,
                'accessible_iframe_count': 1,
                'blocked_iframe_count': 1,
                'blocked_iframe_names': ['partner-frame'],
                'blocked_iframe_titles': ['Partner billing widget'],
                'blocked_frame_paths': ['iframe#partner-frame'],
                'blocked_iframe_samples': [{
                    'selectorHint': 'iframe#partner-frame',
                    'name': 'partner-frame',
                    'title': 'Partner billing widget',
                    'accessible': False,
                    'reason': 'cross-origin-or-inaccessible',
                    'depth': 1,
                    'framePath': 'iframe#partner-frame',
                    'framePathSelectors': ['iframe#partner-frame'],
                }],
                'traversed_document_count': 2,
                'total_iframe_count': 2,
                'frame_capture_ratio': 0.5,
                'frame_capture_status': 'partial',
                'frame_capture_warning': 'frame capture is partial: 1/2 iframes were accessible and 1 were blocked',
                'max_frame_depth': 1,
                'frame_paths': ['iframe#accessible-frame'],
                'top_input_label': 'Billing note',
                'top_input_accessible_name': 'Billing note',
                'top_fieldset_legend': 'Accessible billing draft',
                'top_form_name': 'Partial billing composer',
                'top_input_frame_path': 'iframe#accessible-frame',
                'top_input_frame_depth': 1,
                'top_output_label': 'Saved accessible draft',
                'top_output_frame_path': 'iframe#accessible-frame',
                'top_output_frame_depth': 1,
                'top_submit_label': 'Save accessible draft',
                'top_submit_action': 'http://127.0.0.1:8765/iframe-partial-compose/save',
                'top_submit_frame_path': 'iframe#accessible-frame',
                'submit_candidates': [{
                    'selector_hint': '[data-glasstty-role="submit"]',
                    'score': 1,
                    'text_length': 21,
                    'visible': True,
                    'accessible_name': 'Save accessible draft',
                    'text_sample': 'Save accessible draft',
                    'control_kind': 'button',
                    'form_name': 'Partial billing composer',
                    'form_action': 'http://127.0.0.1:8765/iframe-partial-compose/save',
                    'form_method': 'post',
                    'submit_action': 'http://127.0.0.1:8765/iframe-partial-compose/save',
                    'submit_method': 'post',
                    'frame_selector': 'iframe#accessible-frame',
                    'frame_name': 'accessible-frame',
                    'frame_title': 'Accessible billing frame',
                    'frame_path': 'iframe#accessible-frame',
                    'frame_depth': 1,
                    'frame_path_selectors': ['iframe#accessible-frame'],
                    'frame_path_names': ['accessible-frame'],
                    'frame_path_titles': ['Accessible billing frame'],
                }],
                'semantic_outline': {
                    'heading_outline': ['GlassTTY Fixture Lab — iframe partial shell', 'GlassTTY Fixture Lab — iframe partial compose'],
                    'prompt_labels': ['Billing note'],
                    'accessible_names': ['Billing note'],
                    'prompt_descriptions': [],
                    'submit_labels': ['Save accessible draft'],
                    'form_names': ['Partial billing composer'],
                    'form_actions': ['http://127.0.0.1:8765/iframe-partial-compose/save'],
                    'fieldset_legends': ['Accessible billing draft'],
                    'dialog_names': [],
                    'iframe_names': ['accessible-frame', 'partner-frame'],
                    'iframe_titles': ['Accessible billing frame', 'Partner billing widget'],
                    'frame_paths': ['iframe#accessible-frame'],
                    'control_kinds': ['textarea'],
                    'option_labels': [],
                    'choice_groups': [],
                    'autocomplete_tokens': [],
                    'state_flags': [],
                    'constraint_hints': [],
                    'link_hosts': ['127.0.0.1:8765'],
                },
                'iframe_samples': [{
                    'selectorHint': 'iframe#accessible-frame',
                    'name': 'accessible-frame',
                    'title': 'Accessible billing frame',
                    'src': '/iframe-partial-compose',
                    'resolvedSrc': 'http://127.0.0.1:8765/iframe-partial-compose',
                    'accessible': True,
                    'depth': 1,
                    'framePath': 'iframe#accessible-frame',
                    'framePathSelectors': ['iframe#accessible-frame'],
                }, {
                    'selectorHint': 'iframe#partner-frame',
                    'name': 'partner-frame',
                    'title': 'Partner billing widget',
                    'accessible': False,
                    'reason': 'cross-origin-or-inaccessible',
                    'depth': 1,
                    'framePath': 'iframe#partner-frame',
                    'framePathSelectors': ['iframe#partner-frame'],
                }],
                'form_actions': ['http://127.0.0.1:8765/iframe-partial-compose/save'],
            },
        },
    },
    {
        'name': 'claude-synthetic-thread',
        'payload': {
            'adapter': 'claude',
            'url': 'https://claude.ai/chat/synthetic-thread',
            'title': 'Synthetic Claude Thread',
            'prompt': 'please summarize the thread',
            'latest_output': 'This synthetic Claude fixture exists to exercise index and compare tooling without requiring a live browser session.',
            'selection': '',
            'candidates': {
                'inputs': [{'selector_hint': 'textarea[placeholder*=Message]', 'score': 0.91, 'text_length': 27, 'visible': True}],
                'outputs': [{'selector_hint': 'article[data-testid*=assistant]', 'score': 0.88, 'text_length': 106, 'visible': True}],
            },
            'html_samples': {
                'prompt': '<textarea placeholder="Message Claude">please summarize the thread</textarea>',
                'latest_output': '<article data-testid="assistant-message">This synthetic Claude fixture exists to exercise index and compare tooling without requiring a live browser session.</article>',
            },
            'metadata': {
                'generator': 'seed-fixture-corpus',
                'prompt_selector': 'textarea[placeholder*=Message]',
                'latest_output_selector': 'article[data-testid*=assistant]',
            },
        },
    },
    {
        'name': 'fixturelab-dialog-form',
        'payload': {
            'adapter': 'offscreen-html',
            'url': 'http://127.0.0.1:8765/dialog-form',
            'title': 'GlassTTY Fixture Lab — dialog form',
            'prompt': 'Draft inside dialog',
            'latest_output': 'Dialog saved state',
            'selection': '',
            'candidates': {
                'inputs': [{
                    'selector_hint': 'textarea#dialog-prompt',
                    'score': 0.97,
                    'text_length': 19,
                    'visible': True,
                    'label_text': 'Message',
                    'accessible_name': 'Message',
                    'control_kind': 'textbox',
                    'dialog_name': 'Profile settings',
                    'dialog_role': 'dialog',
                    'dialog_modal': True,
                    'dialog_open': True,
                    'form_name': 'Profile settings',
                    'fieldset_legend': 'Composer',
                }],
                'outputs': [{'selector_hint': 'article[data-glasstty-role="latest-output"]', 'score': 0.82, 'text_length': 18, 'visible': True}],
            },
            'html_samples': {
                'prompt': '<textarea id="dialog-prompt">Draft inside dialog</textarea>',
                'latest_output': '<article data-glasstty-role="latest-output">Dialog saved state</article>',
                'submit': '<button data-glasstty-role="submit" type="button">Save</button>',
            },
            'metadata': {
                'generator': 'seed-fixture-corpus',
                'top_submit_label': 'Save',
                'top_submit_action': None,
                'semantic_outline': {
                    'dialog_names': ['Profile settings'],
                    'form_names': ['Profile settings'],
                    'fieldset_legends': ['Composer'],
                    'control_kinds': ['textbox'],
                    'submit_labels': ['Save'],
                    'link_hosts': ['127.0.0.1:8765'],
                },
            },
        },
    },
    {
        'name': 'fixturelab-iframe-compose',
        'payload': {
            'adapter': 'offscreen-html',
            'url': 'http://127.0.0.1:8765/iframe-compose',
            'title': 'GlassTTY Fixture Lab — iframe compose',
            'prompt': '4242424242424242',
            'latest_output': 'Saved 4242',
            'selection': '',
            'candidates': {
                'inputs': [{
                    'selector_hint': 'input#iframe-prompt',
                    'score': 0.96,
                    'text_length': 0,
                    'visible': True,
                    'label_text': 'Card number',
                    'accessible_name': 'Card number',
                    'control_kind': 'input:text',
                    'form_name': 'Embedded composer',
                    'fieldset_legend': 'Embedded card',
                    'frame_selector': '#billing-frame',
                    'frame_name': 'billing-frame',
                    'frame_title': 'Billing details',
                }],
                'outputs': [{
                    'selector_hint': 'article[data-glasstty-role="latest-output"]',
                    'score': 0.8,
                    'text_length': 10,
                    'visible': True,
                    'frame_selector': '#billing-frame',
                    'frame_name': 'billing-frame',
                    'frame_title': 'Billing details',
                }],
            },
            'html_samples': {
                'prompt': '<input id="iframe-prompt" value="4242424242424242" />',
                'latest_output': '<article data-glasstty-role="latest-output">Saved 4242</article>',
                'submit': '<button data-glasstty-role="submit" type="button">Save card</button>',
            },
            'metadata': {
                'generator': 'seed-fixture-corpus',
                'top_submit_label': 'Save card',
                'top_submit_action': '/iframe-compose/save',
                'semantic_outline': {
                    'form_names': ['Embedded composer'],
                    'fieldset_legends': ['Embedded card'],
                    'iframe_names': ['billing-frame'],
                    'iframe_titles': ['Billing details'],
                    'control_kinds': ['input:text'],
                    'submit_labels': ['Save card'],
                    'link_hosts': ['127.0.0.1:8765'],
                },
            },
        },
    },
]


def envelope(name: str, payload: dict) -> dict:
    return {
        'version': '0.1',
        'request_id': f'seed-{name}',
        'type': 'fixture.capture',
        'timestamp': datetime.now(timezone.utc).isoformat(),
        'message': {
            'request_id': f'seed-{name}',
            'type': 'fixture.capture.response',
            'payload': payload,
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description='Write a deterministic sample GlassTTY fixture corpus')
    parser.add_argument('output_dir', nargs='?', default='fixtures/corpus')
    parser.add_argument('--force', action='store_true')
    args = parser.parse_args()
    target = Path(args.output_dir)
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for spec in FIXTURES:
        path = target / f"{spec['name']}.json"
        if path.exists() and not args.force:
            written.append({'path': str(path), 'status': 'kept'})
            continue
        path.write_text(json.dumps(envelope(spec['name'], spec['payload']), ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        written.append({'path': str(path), 'status': 'written'})
    print(json.dumps({'root': str(target), 'count': len(written), 'files': written}, ensure_ascii=False))


if __name__ == '__main__':
    main()
