from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARCHIVE = ROOT / "archive"
TOOLS = ROOT / "tools"
ARCHIVE_TITLE = 'The Good'
REVISION = 22

TIMESTAMP = '2026-03-22 04:02 America/New_York'

TIMESTAMP_FILE = '2026.03.22.04.02'

CODENAME = 'movementmembership-nonexile-returnpaths-wayfarer'

PACKAGE_FOLDER = 'The-Good-rev0022-2026.03.22.04.02-movementmembership-nonexile-returnpaths-wayfarer'

SOURCE_CATALOG = {'COE-FINGAIN': {'kind': 'policy-framework',
                 'publisher': 'Council of Europe',
                 'stability': 'stable',
                 'title': 'Guide on prohibition on financial gain',
                 'url': 'https://www.coe.int/en/web/human-rights-and-biomedicine/guide-financial-gain'},
 'ILO-DECENTWORK': {'kind': 'policy-framework',
                    'publisher': 'International Labour Organization',
                    'stability': 'rolling',
                    'title': 'Decent work and the 2030 Agenda for sustainable development',
                    'url': 'https://www.ilo.org/topics-and-sectors/decent-work-and-2030-agenda-sustainable-development'},
 'ILO-SDIALOGUE': {'kind': 'policy-framework',
                   'publisher': 'International Labour Organization',
                   'stability': 'rolling',
                   'title': 'Social dialogue and tripartism',
                   'url': 'https://www.ilo.org/topics-and-sectors/social-dialogue-and-tripartism'},
 'ILO-WORKTIME': {'kind': 'policy-framework',
                  'publisher': 'International Labour Organization',
                  'stability': 'rolling',
                  'title': 'Working time and work organization',
                  'url': 'https://www.ilo.org/topics-and-sectors/working-time-and-work-organization'},
 'IOM-REGPATH': {'kind': 'policy-framework',
                 'publisher': 'International Organization for Migration',
                 'stability': 'rolling',
                 'title': 'Facilitating pathways for regular migration',
                 'url': 'https://www.iom.int/facilitating-pathways-regular-migration'},
 'IPBES-NEXUS': {'kind': 'scientific-assessment',
                 'publisher': 'IPBES',
                 'stability': 'snapshot',
                 'title': 'Nexus Assessment',
                 'url': 'https://www.ipbes.net/nexus-assessment'},
 'IPCC-SYR': {'kind': 'scientific-assessment',
              'publisher': 'IPCC',
              'stability': 'snapshot',
              'title': 'Synthesis Report',
              'url': 'https://www.ipcc.ch/synthesis-report/'},
 'NY-ANIMCON': {'kind': 'scientific-statement',
                'publisher': 'New York University',
                'stability': 'snapshot',
                'title': 'The New York Declaration on Animal Consciousness',
                'url': 'https://sites.google.com/nyu.edu/nydeclaration/declaration'},
 'OECD-ACCESSCOM': {'kind': 'policy-framework',
                    'publisher': 'OECD',
                    'stability': 'snapshot',
                    'title': 'Accessible and inclusive public communication',
                    'url': 'https://www.oecd.org/en/publications/accessible-and-inclusive-public-communication_222b62d9-en.html'},
 'OECD-BUILTENV': {'kind': 'policy-framework',
                   'publisher': 'OECD',
                   'stability': 'stable',
                   'title': 'Built Environment through a Well-being Lens',
                   'url': 'https://www.oecd.org/en/publications/built-environment-through-a-well-being-lens_1b5bebf4-en.html'},
 'OECD-CHILDSWB2025': {'kind': 'policy-framework',
                       'publisher': 'OECD',
                       'stability': 'snapshot',
                       'title': "Why and how to measure children's subjective well-being",
                       'url': 'https://www.oecd.org/en/publications/why-and-how-to-measure-children-s-subjective-well-being_78eb787c-en.html'},
 'OECD-CONN2025': {'kind': 'policy-framework',
                   'publisher': 'OECD',
                   'stability': 'snapshot',
                   'title': 'Social Connections and Loneliness in OECD Countries',
                   'url': 'https://www.oecd.org/en/publications/social-connections-and-loneliness-in-oecd-countries_6df2d6a0-en.html'},
 'OECD-DARK': {'kind': 'policy-framework',
               'publisher': 'OECD',
               'stability': 'snapshot',
               'title': 'Dark commercial patterns',
               'url': 'https://www.oecd.org/en/publications/dark-commercial-patterns_44f5e846-en.html'},
 'OECD-DISCRIM2025': {'kind': 'policy-framework',
                      'publisher': 'OECD',
                      'stability': 'snapshot',
                      'title': 'Combatting Discrimination in the European Union',
                      'url': 'https://www.oecd.org/en/publications/combatting-discrimination-in-the-european-union_29c2c36a-en.html'},
 'OECD-JOBQUALITY': {'kind': 'policy-framework',
                     'publisher': 'OECD',
                     'stability': 'rolling',
                     'title': 'Job quality',
                     'url': 'https://www.oecd.org/en/topics/policy-issues/job-quality.html'},
 'OECD-PRIVACY': {'kind': 'policy-framework',
                  'publisher': 'OECD',
                  'stability': 'rolling',
                  'title': 'Privacy and data protection',
                  'url': 'https://www.oecd.org/en/topics/privacy-and-data-protection.html'},
 'OECD-REGFUTURE': {'kind': 'policy-framework',
                    'publisher': 'OECD',
                    'stability': 'snapshot',
                    'title': 'Regulating for the future: OECD Regulatory Policy Outlook 2025',
                    'url': 'https://www.oecd.org/en/publications/2025/04/oecd-regulatory-policy-outlook-2025_a754bf4c/full-report/regulating-for-the-future_e948d334.html'},
 'OECD-SWB2025': {'kind': 'policy-framework',
                  'publisher': 'OECD',
                  'stability': 'snapshot',
                  'title': 'OECD Guidelines on Measuring Subjective Well-being (2025 update)',
                  'url': 'https://www.oecd.org/en/publications/oecd-guidelines-on-measuring-subjective-well-being-2025-update_9203632a-en/full-report/measuring-subjective-well-being_b4b53f27.html'},
 'OECD-TIMEUSE': {'kind': 'policy-framework',
                  'publisher': 'OECD',
                  'stability': 'rolling',
                  'title': 'Time use database',
                  'url': 'https://www.oecd.org/en/data/datasets/time-use-database.html'},
 'OECD-TRUST2025': {'kind': 'policy-framework',
                    'publisher': 'OECD',
                    'stability': 'snapshot',
                    'title': 'Government at a Glance 2025 — Levels of trust in public institutions',
                    'url': 'https://www.oecd.org/en/publications/government-at-a-glance-2025_0efd0bcd-en/full-report/levels-of-trust-in-public-institutions_62a3b94e.html'},
 'OECD-WB': {'kind': 'policy-framework',
             'publisher': 'OECD',
             'stability': 'rolling',
             'title': 'OECD Well-being Data Monitor',
             'url': 'https://www.oecd.org/en/data/tools/well-being-data-monitor.html'},
 'OHCHR-CRC': {'kind': 'policy-framework',
               'publisher': 'Office of the United Nations High Commissioner for Human Rights',
               'stability': 'stable',
               'title': 'Convention on the Rights of the Child',
               'url': 'https://www.ohchr.org/en/instruments-mechanisms/instruments/convention-rights-child'},
 'OHCHR-CRPD': {'kind': 'policy-framework',
                'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                'stability': 'stable',
                'title': 'Convention on the Rights of Persons with Disabilities',
                'url': 'https://www.ohchr.org/en/instruments-mechanisms/instruments/convention-rights-persons-disabilities'},
 'OHCHR-CULTLIFE': {'kind': 'policy-framework',
                    'publisher': 'OHCHR',
                    'stability': 'stable',
                    'title': 'Right to participate in cultural life',
                    'url': 'https://www.ohchr.org/en/special-procedures/sr-cultural-rights/international-standards'},
 'OHCHR-HARMFUL': {'kind': 'policy-framework',
                   'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                   'stability': 'rolling',
                   'title': 'Harmful practices',
                   'url': 'https://www.ohchr.org/en/women/harmful-practices'},
 'OHCHR-HOMELESSNESS': {'kind': 'policy-framework',
                        'publisher': 'Office of the United Nations High Commissioner for Human '
                                     'Rights',
                        'stability': 'rolling',
                        'title': 'Homelessness and human rights',
                        'url': 'https://www.ohchr.org/en/special-procedures/sr-housing/homelessness-and-human-rights'},
 'OHCHR-HOUSING': {'kind': 'policy-framework',
                   'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                   'stability': 'rolling',
                   'title': 'The human right to adequate housing',
                   'url': 'https://www.ohchr.org/en/special-procedures/sr-housing/human-right-adequate-housing'},
 'OHCHR-HOUSINGGUIDE': {'kind': 'policy-framework',
                        'publisher': 'Office of the United Nations High Commissioner for Human '
                                     'Rights',
                        'stability': 'stable',
                        'title': 'Guidelines for the implementation of the right to adequate '
                                 'housing',
                        'url': 'https://www.ohchr.org/en/special-procedures/sr-housing/guidelines-implementation-right-adequate-housing'},
 'OHCHR-HUMRIGHTS': {'kind': 'policy-framework',
                     'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                     'stability': 'rolling',
                     'title': 'What are human rights?',
                     'url': 'https://www.ohchr.org/en/what-are-human-rights'},
 'OHCHR-ICCPR': {'kind': 'policy-framework',
                 'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                 'stability': 'stable',
                 'title': 'International Covenant on Civil and Political Rights',
                 'url': 'https://www.ohchr.org/en/instruments-mechanisms/instruments/international-covenant-civil-and-political-rights'},
 'OHCHR-ICESCR': {'kind': 'policy-framework',
                  'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                  'stability': 'stable',
                  'title': 'International Covenant on Economic, Social and Cultural Rights',
                  'url': 'https://www.ohchr.org/en/instruments-mechanisms/instruments/international-covenant-economic-social-and-cultural-rights'},
 'OHCHR-LGBTI': {'kind': 'policy-framework',
                 'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                 'stability': 'rolling',
                 'title': 'About LGBTI people and human rights',
                 'url': 'https://www.ohchr.org/en/sexual-orientation-and-gender-identity/about-lgbti-people-and-human-rights'},
 'OHCHR-NATIONALITY': {'kind': 'policy-framework',
                       'publisher': 'Office of the United Nations High Commissioner for Human '
                                    'Rights',
                       'stability': 'rolling',
                       'title': 'OHCHR and the right to a nationality',
                       'url': 'https://www.ohchr.org/en/nationality-and-statelessness'},
 'OHCHR-OLDERPRINC': {'kind': 'policy-framework',
                      'publisher': 'Office of the United Nations High Commissioner for Human '
                                   'Rights',
                      'stability': 'stable',
                      'title': 'United Nations Principles for Older Persons',
                      'url': 'https://www.ohchr.org/en/instruments-mechanisms/instruments/united-nations-principles-older-persons'},
 'OHCHR-PARTICIPATE': {'kind': 'policy-framework',
                       'publisher': 'Office of the United Nations High Commissioner for Human '
                                    'Rights',
                       'stability': 'rolling',
                       'title': 'Equal participation in political and public affairs',
                       'url': 'https://www.ohchr.org/en/equal-participation'},
 'OHCHR-PRISONERS': {'kind': 'policy-framework',
                     'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                     'stability': 'stable',
                     'title': 'Basic Principles for the Treatment of Prisoners',
                     'url': 'https://www.ohchr.org/en/instruments-mechanisms/instruments/basic-principles-treatment-prisoners'},
 'OHCHR-PRIVACY2025': {'kind': 'policy-framework',
                       'publisher': 'Office of the United Nations High Commissioner for Human '
                                    'Rights',
                       'stability': 'snapshot',
                       'title': 'A/HRC/60/45: The right to privacy in the digital age',
                       'url': 'https://www.ohchr.org/en/documents/thematic-reports/ahrc6045-right-privacy-digital-age-report-office-united-nations-high'},
 'OHCHR-REINTEG2025': {'kind': 'policy-framework',
                       'publisher': 'Office of the United Nations High Commissioner for Human '
                                    'Rights',
                       'stability': 'snapshot',
                       'title': 'Human rights and the social reintegration of persons released '
                                'from detention and persons subjected to non-custodial measures',
                       'url': 'https://www.ohchr.org/en/documents/thematic-reports/ahrc6055-human-rights-and-social-reintegration-persons-released'},
 'OHCHR-RIGHTWORK': {'kind': 'policy-framework',
                     'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                     'stability': 'rolling',
                     'title': 'About the right to work',
                     'url': 'https://www.ohchr.org/en/right-work/about-right-work'},
 'OHCHR-SRHR': {'kind': 'policy-framework',
                'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                'stability': 'rolling',
                'title': 'Sexual and reproductive health and rights',
                'url': 'https://www.ohchr.org/en/women/sexual-and-reproductive-health-and-rights'},
 'OHCHR-UDHR': {'kind': 'policy-framework',
                'publisher': 'Office of the United Nations High Commissioner for Human Rights',
                'stability': 'stable',
                'title': 'Universal Declaration of Human Rights',
                'url': 'https://www.ohchr.org/en/human-rights/universal-declaration/translations/english'},
 'SEP-AESTHXP': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Aesthetic Experience',
                 'url': 'https://plato.stanford.edu/entries/aesthetic-experience/'},
 'SEP-AFRICAN': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'African Ethics',
                 'url': 'https://plato.stanford.edu/entries/african-ethics/'},
 'SEP-ARCHITECTURE': {'kind': 'philosophy-reference',
                      'publisher': 'Stanford Encyclopedia of Philosophy',
                      'stability': 'stable',
                      'title': 'Philosophy of Architecture',
                      'url': 'https://plato.stanford.edu/entries/architecture/'},
 'SEP-ATONE': {'kind': 'philosophy-reference',
               'publisher': 'Stanford Encyclopedia of Philosophy',
               'stability': 'stable',
               'title': 'Atonement',
               'url': 'https://plato.stanford.edu/entries/atonement/'},
 'SEP-AUTONOMY': {'kind': 'philosophy-reference',
                  'publisher': 'Stanford Encyclopedia of Philosophy',
                  'stability': 'stable',
                  'title': 'Autonomy in Moral and Political Philosophy',
                  'url': 'https://plato.stanford.edu/entries/autonomy-moral/'},
 'SEP-BUDDHIST': {'kind': 'philosophy-reference',
                  'publisher': 'Stanford Encyclopedia of Philosophy',
                  'stability': 'stable',
                  'title': 'Ethics in Indian Buddhism',
                  'url': 'https://plato.stanford.edu/entries/ethics-indian-buddhism/'},
 'SEP-CAP': {'kind': 'philosophy-reference',
             'publisher': 'Stanford Encyclopedia of Philosophy',
             'stability': 'stable',
             'title': 'The Capability Approach',
             'url': 'https://plato.stanford.edu/entries/capability-approach/'},
 'SEP-CHILDHOOD': {'kind': 'philosophy-reference',
                   'publisher': 'Stanford Encyclopedia of Philosophy',
                   'stability': 'stable',
                   'title': 'The Philosophy of Childhood',
                   'url': 'https://plato.stanford.edu/entries/childhood/'},
 'SEP-CHILDRIGHTS': {'kind': 'philosophy-reference',
                     'publisher': 'Stanford Encyclopedia of Philosophy',
                     'stability': 'stable',
                     'title': "Children's Rights",
                     'url': 'https://plato.stanford.edu/entries/rights-children/'},
 'SEP-CHINESE': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Chinese Ethics',
                 'url': 'https://plato.stanford.edu/entries/ethics-chinese/'},
 'SEP-CITIZENSHIP': {'kind': 'philosophy-reference',
                     'publisher': 'Stanford Encyclopedia of Philosophy',
                     'stability': 'stable',
                     'title': 'Citizenship',
                     'url': 'https://plato.stanford.edu/entries/citizenship/'},
 'SEP-COGDIS': {'kind': 'philosophy-reference',
                'publisher': 'Stanford Encyclopedia of Philosophy',
                'stability': 'stable',
                'title': 'Cognitive Disability and Moral Status',
                'url': 'https://plato.stanford.edu/entries/cognitive-disability/'},
 'SEP-COMMONGOOD': {'kind': 'philosophy-reference',
                    'publisher': 'Stanford Encyclopedia of Philosophy',
                    'stability': 'stable',
                    'title': 'The Common Good',
                    'url': 'https://plato.stanford.edu/entries/common-good/'},
 'SEP-CONS': {'kind': 'philosophy-reference',
              'publisher': 'Stanford Encyclopedia of Philosophy',
              'stability': 'stable',
              'title': 'Consequentialism',
              'url': 'https://plato.stanford.edu/entries/consequentialism/'},
 'SEP-CONTRACT': {'kind': 'philosophy-reference',
                  'publisher': 'Stanford Encyclopedia of Philosophy',
                  'stability': 'stable',
                  'title': 'Contractualism',
                  'url': 'https://plato.stanford.edu/entries/contractualism/'},
 'SEP-DEATH': {'kind': 'philosophy-reference',
               'publisher': 'Stanford Encyclopedia of Philosophy',
               'stability': 'stable',
               'title': 'Death',
               'url': 'https://plato.stanford.edu/entries/death/'},
 'SEP-DEMOCRACY': {'kind': 'philosophy-reference',
                   'publisher': 'Stanford Encyclopedia of Philosophy',
                   'stability': 'stable',
                   'title': 'Democracy',
                   'url': 'https://plato.stanford.edu/entries/democracy/'},
 'SEP-DEON': {'kind': 'philosophy-reference',
              'publisher': 'Stanford Encyclopedia of Philosophy',
              'stability': 'stable',
              'title': 'Deontological Ethics',
              'url': 'https://plato.stanford.edu/entries/ethics-deontological/'},
 'SEP-DIGNITY': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Dignity',
                 'url': 'https://plato.stanford.edu/entries/dignity/'},
 'SEP-DISABILITY': {'kind': 'philosophy-reference',
                    'publisher': 'Stanford Encyclopedia of Philosophy',
                    'stability': 'stable',
                    'title': 'Disability: Definitions and Models',
                    'url': 'https://plato.stanford.edu/entries/disability/'},
 'SEP-DISABILITYCRIT': {'kind': 'philosophy-reference',
                        'publisher': 'Stanford Encyclopedia of Philosophy',
                        'stability': 'stable',
                        'title': 'Critical Disability Theory',
                        'url': 'https://plato.stanford.edu/entries/disability-critical/'},
 'SEP-DISABILITYJUST': {'kind': 'philosophy-reference',
                        'publisher': 'Stanford Encyclopedia of Philosophy',
                        'stability': 'stable',
                        'title': 'Disability and Justice',
                        'url': 'https://plato.stanford.edu/entries/disability-justice/'},
 'SEP-DISWB': {'kind': 'philosophy-reference',
               'publisher': 'Stanford Encyclopedia of Philosophy',
               'stability': 'stable',
               'title': 'Disability and Well-Being',
               'url': 'https://plato.stanford.edu/entries/disability-well-being/'},
 'SEP-DJUST': {'kind': 'philosophy-reference',
               'publisher': 'Stanford Encyclopedia of Philosophy',
               'stability': 'stable',
               'title': 'Distributive Justice',
               'url': 'https://plato.stanford.edu/entries/justice-distributive/'},
 'SEP-EGAL': {'kind': 'philosophy-reference',
              'publisher': 'Stanford Encyclopedia of Philosophy',
              'stability': 'stable',
              'title': 'Egalitarianism',
              'url': 'https://plato.stanford.edu/entries/egalitarianism/'},
 'SEP-EXPLOIT': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Exploitation',
                 'url': 'https://plato.stanford.edu/entries/exploitation/'},
 'SEP-FEMAUTO': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Feminist Perspectives on Autonomy',
                 'url': 'https://plato.stanford.edu/entries/feminism-autonomy/'},
 'SEP-FEMETH': {'kind': 'philosophy-reference',
                'publisher': 'Stanford Encyclopedia of Philosophy',
                'stability': 'stable',
                'title': 'Feminist Ethics',
                'url': 'https://plato.stanford.edu/entries/feminism-ethics/'},
 'SEP-FORGIVE': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Forgiveness',
                 'url': 'https://plato.stanford.edu/entries/forgiveness/'},
 'SEP-FRIEND': {'kind': 'philosophy-reference',
                'publisher': 'Stanford Encyclopedia of Philosophy',
                'stability': 'stable',
                'title': 'Friendship',
                'url': 'https://plato.stanford.edu/entries/friendship/'},
 'SEP-GROUNDS': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'The Grounds of Moral Status',
                 'url': 'https://plato.stanford.edu/entries/grounds-moral-status/'},
 'SEP-IMMIGRATION': {'kind': 'philosophy-reference',
                     'publisher': 'Stanford Encyclopedia of Philosophy',
                     'stability': 'stable',
                     'title': 'Immigration',
                     'url': 'https://plato.stanford.edu/entries/immigration/'},
 'SEP-INFCONSENT': {'kind': 'philosophy-reference',
                    'publisher': 'Stanford Encyclopedia of Philosophy',
                    'stability': 'stable',
                    'title': 'Informed Consent',
                    'url': 'https://plato.stanford.edu/entries/informed-consent/'},
 'SEP-ITPRIV': {'kind': 'philosophy-reference',
                'publisher': 'Stanford Encyclopedia of Philosophy',
                'stability': 'stable',
                'title': 'Privacy and Information Technology',
                'url': 'https://plato.stanford.edu/entries/it-privacy/'},
 'SEP-IV': {'kind': 'philosophy-reference',
            'publisher': 'Stanford Encyclopedia of Philosophy',
            'stability': 'stable',
            'title': 'Intrinsic vs. Extrinsic Value',
            'url': 'https://plato.stanford.edu/entries/value-intrinsic-extrinsic/'},
 'SEP-LOVE': {'kind': 'philosophy-reference',
              'publisher': 'Stanford Encyclopedia of Philosophy',
              'stability': 'stable',
              'title': 'Love',
              'url': 'https://plato.stanford.edu/entries/love/'},
 'SEP-MANIP': {'kind': 'philosophy-reference',
               'publisher': 'Stanford Encyclopedia of Philosophy',
               'stability': 'stable',
               'title': 'The Ethics of Manipulation',
               'url': 'https://plato.stanford.edu/entries/ethics-manipulation/'},
 'SEP-MARKETS': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Markets',
                 'url': 'https://plato.stanford.edu/entries/markets/'},
 'SEP-MDILEM': {'kind': 'philosophy-reference',
                'publisher': 'Stanford Encyclopedia of Philosophy',
                'stability': 'stable',
                'title': 'Moral Dilemmas',
                'url': 'https://plato.stanford.edu/entries/moral-dilemmas/'},
 'SEP-MDU': {'kind': 'philosophy-reference',
             'publisher': 'Stanford Encyclopedia of Philosophy',
             'stability': 'stable',
             'title': 'Moral Decision-Making Under Uncertainty',
             'url': 'https://plato.stanford.edu/entries/moral-decision-uncertainty/'},
 'SEP-MEANING': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'The Meaning of Life',
                 'url': 'https://plato.stanford.edu/entries/life-meaning/'},
 'SEP-MORALANIMAL': {'kind': 'philosophy-reference',
                     'publisher': 'Stanford Encyclopedia of Philosophy',
                     'stability': 'stable',
                     'title': 'The Moral Status of Animals',
                     'url': 'https://plato.stanford.edu/entries/moral-animal/'},
 'SEP-NEEDS': {'kind': 'philosophy-reference',
               'publisher': 'Stanford Encyclopedia of Philosophy',
               'stability': 'stable',
               'title': 'Needs in Moral and Political Philosophy',
               'url': 'https://plato.stanford.edu/entries/needs/'},
 'SEP-PERF': {'kind': 'philosophy-reference',
              'publisher': 'Stanford Encyclopedia of Philosophy',
              'stability': 'stable',
              'title': 'Perfectionism in Moral and Political Philosophy',
              'url': 'https://plato.stanford.edu/entries/perfectionism-moral/'},
 'SEP-PREF': {'kind': 'philosophy-reference',
              'publisher': 'Stanford Encyclopedia of Philosophy',
              'stability': 'stable',
              'title': 'Preferences',
              'url': 'https://plato.stanford.edu/entries/preferences/'},
 'SEP-PRIOR': {'kind': 'philosophy-reference',
               'publisher': 'Stanford Encyclopedia of Philosophy',
               'stability': 'stable',
               'title': 'Prioritarianism as a Theory of Value',
               'url': 'https://plato.stanford.edu/entries/prioritarianism/'},
 'SEP-PRIVACY': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Privacy',
                 'url': 'https://plato.stanford.edu/entries/privacy/'},
 'SEP-PRIVMED': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Privacy and Medicine',
                 'url': 'https://plato.stanford.edu/entries/privacy-medicine/'},
 'SEP-PROPERTY': {'kind': 'philosophy-reference',
                  'publisher': 'Stanford Encyclopedia of Philosophy',
                  'stability': 'stable',
                  'title': 'Property and Ownership',
                  'url': 'https://plato.stanford.edu/entries/property/'},
 'SEP-PUBJUST': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Public Justification',
                 'url': 'https://plato.stanford.edu/archives/fall2025/entries/justification-public/'},
 'SEP-PUBLICREASON': {'kind': 'philosophy-reference',
                      'publisher': 'Stanford Encyclopedia of Philosophy',
                      'stability': 'stable',
                      'title': 'Public Reason',
                      'url': 'https://plato.stanford.edu/entries/public-reason/'},
 'SEP-RECOGNITION': {'kind': 'philosophy-reference',
                     'publisher': 'Stanford Encyclopedia of Philosophy',
                     'stability': 'stable',
                     'title': 'Recognition',
                     'url': 'https://plato.stanford.edu/entries/recognition/'},
 'SEP-RECONCILE': {'kind': 'philosophy-reference',
                   'publisher': 'Stanford Encyclopedia of Philosophy',
                   'stability': 'stable',
                   'title': 'Reconciliation',
                   'url': 'https://plato.stanford.edu/entries/reconciliation/'},
 'SEP-RELGOODS': {'kind': 'philosophy-reference',
                  'publisher': 'Stanford Encyclopedia of Philosophy',
                  'stability': 'stable',
                  'title': 'Personal Relationship Goods',
                  'url': 'https://plato.stanford.edu/entries/personal-relationship-goods/'},
 'SEP-REPUB': {'kind': 'philosophy-reference',
               'publisher': 'Stanford Encyclopedia of Philosophy',
               'stability': 'stable',
               'title': 'Republicanism',
               'url': 'https://plato.stanford.edu/entries/republicanism/'},
 'SEP-RESPECT': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Respect',
                 'url': 'https://plato.stanford.edu/entries/respect/'},
 'SEP-RISK': {'kind': 'philosophy-reference',
              'publisher': 'Stanford Encyclopedia of Philosophy',
              'stability': 'stable',
              'title': 'Risk',
              'url': 'https://plato.stanford.edu/entries/risk/'},
 'SEP-SOCIALEPI': {'kind': 'philosophy-reference',
                   'publisher': 'Stanford Encyclopedia of Philosophy',
                   'stability': 'stable',
                   'title': 'Social Epistemology',
                   'url': 'https://plato.stanford.edu/entries/epistemology-social/'},
 'SEP-SPORT': {'kind': 'philosophy-reference',
               'publisher': 'Stanford Encyclopedia of Philosophy',
               'stability': 'stable',
               'title': 'Philosophy of Sport',
               'url': 'https://plato.stanford.edu/entries/sport/'},
 'SEP-VE': {'kind': 'philosophy-reference',
            'publisher': 'Stanford Encyclopedia of Philosophy',
            'stability': 'stable',
            'title': 'Virtue Ethics',
            'url': 'https://plato.stanford.edu/entries/ethics-virtue/'},
 'SEP-VPLURAL': {'kind': 'philosophy-reference',
                 'publisher': 'Stanford Encyclopedia of Philosophy',
                 'stability': 'stable',
                 'title': 'Value Pluralism',
                 'url': 'https://plato.stanford.edu/entries/value-pluralism/'},
 'SEP-WB': {'kind': 'philosophy-reference',
            'publisher': 'Stanford Encyclopedia of Philosophy',
            'stability': 'stable',
            'title': 'Well-Being',
            'url': 'https://plato.stanford.edu/entries/well-being/'},
 'SEP-WORKLABOR': {'kind': 'philosophy-reference',
                   'publisher': 'Stanford Encyclopedia of Philosophy',
                   'stability': 'stable',
                   'title': 'Philosophical Approaches to Work and Labor',
                   'url': 'https://plato.stanford.edu/entries/work-labor/'},
 'UN-CRPD-GC2': {'kind': 'policy-framework',
                 'publisher': 'United Nations Committee on the Rights of Persons with Disabilities',
                 'stability': 'stable',
                 'title': 'General comment No. 2 (2014) on accessibility',
                 'url': 'https://docs.un.org/en/CRPD/C/GC/2'},
 'UN-SDG2030': {'kind': 'policy-framework',
                'publisher': 'United Nations Department of Economic and Social Affairs',
                'stability': 'stable',
                'title': 'Transforming our world: the 2030 Agenda for Sustainable Development',
                'url': 'https://sdgs.un.org/2030agenda'},
 'UNDP-HDR2025': {'kind': 'policy-framework',
                  'publisher': 'United Nations Development Programme',
                  'stability': 'snapshot',
                  'title': 'Human Development Report 2025',
                  'url': 'https://hdr.undp.org/content/human-development-report-2025'},
 'UNESCO-CLIMATEETH': {'kind': 'policy-framework',
                       'publisher': 'UNESCO',
                       'stability': 'stable',
                       'title': 'Declaration of Ethical Principles in relation to Climate Change',
                       'url': 'https://www.unesco.org/en/legal-affairs/declaration-ethical-principles-relation-climate-change'},
 'UNESCO-CULTPUB': {'kind': 'policy-framework',
                    'publisher': 'UNESCO',
                    'stability': 'rolling',
                    'title': 'Culture as a global public good',
                    'url': 'https://www.unesco.org/en/sustainable-development/culture/policybrief/culturepublicgood'},
 'UNESCO-DIVEXP': {'kind': 'policy-framework',
                   'publisher': 'UNESCO',
                   'stability': 'stable',
                   'title': 'Convention on the Protection and Promotion of the Diversity of '
                            'Cultural Expressions',
                   'url': 'https://www.unesco.org/en/legal-affairs/convention-protection-and-promotion-diversity-cultural-expressions'},
 'UNHCR-GT2025': {'kind': 'policy-framework',
                  'publisher': 'UNHCR',
                  'stability': 'snapshot',
                  'title': 'Global Trends',
                  'url': 'https://www.unhcr.org/global-trends'},
 'UNHCR-STATELESS2025': {'kind': 'policy-framework',
                         'publisher': 'UNHCR',
                         'stability': 'snapshot',
                         'title': 'Ending statelessness',
                         'url': 'https://www.unhcr.org/what-we-do/protect-human-rights/ending-statelessness'},
 'UNODC-REOFFEND': {'kind': 'policy-framework',
                    'publisher': 'United Nations Office on Drugs and Crime',
                    'stability': 'snapshot',
                    'title': 'Model Strategies on Reducing Reoffending',
                    'url': 'https://www.unodc.org/unodc/justice-and-prison-reform/cpcj-model-strategies-on-reducing-reoffending.html'},
 'UNODC-RJ': {'kind': 'policy-framework',
              'publisher': 'United Nations Office on Drugs and Crime',
              'stability': 'rolling',
              'title': 'Tools and Publications - Restorative Justice',
              'url': 'https://www.unodc.org/unodc/en/justice-and-prison-reform/cpcj-restorative-justice.html'},
 'WHO-AGEISM': {'kind': 'policy-framework',
                'publisher': 'World Health Organization',
                'stability': 'rolling',
                'title': 'Ageism',
                'url': 'https://www.who.int/health-topics/ageism'},
 'WHO-ARTS': {'kind': 'policy-framework',
              'publisher': 'World Health Organization',
              'stability': 'rolling',
              'title': 'Arts and health',
              'url': 'https://www.who.int/initiatives/arts-and-health'},
 'WHO-DISHEALTH': {'kind': 'policy-framework',
                   'publisher': 'World Health Organization',
                   'stability': 'rolling',
                   'title': 'Global report on health equity for persons with disabilities',
                   'url': 'https://www.who.int/teams/noncommunicable-diseases/sensory-functions-disability-and-rehabilitation/global-report-on-health-equity-for-persons-with-disabilities'},
 'WHO-HUMRIGHTS': {'kind': 'policy-framework',
                   'publisher': 'World Health Organization',
                   'stability': 'rolling',
                   'title': 'Human rights',
                   'url': 'https://www.who.int/health-topics/human-rights'},
 'WHO-LTCOLDER': {'kind': 'policy-framework',
                  'publisher': 'World Health Organization',
                  'stability': 'rolling',
                  'title': 'Providing access to long-term care for older people',
                  'url': 'https://www.who.int/health-topics/ageing/providing-access-to-long-term-care-for-older-people'},
 'WHO-MHWORK': {'kind': 'policy-framework',
                'publisher': 'World Health Organization',
                'stability': 'rolling',
                'title': 'Mental health at work',
                'url': 'https://www.who.int/news-room/fact-sheets/detail/mental-health-at-work'},
 'WHO-NURTCARE': {'kind': 'policy-framework',
                  'publisher': 'World Health Organization',
                  'stability': 'rolling',
                  'title': 'Nurturing care for early childhood development',
                  'url': 'https://www.who.int/teams/maternal-newborn-child-adolescent-health-and-ageing/child-health/nurturing-care'},
 'WHO-ONEHEALTH': {'kind': 'policy-framework',
                   'publisher': 'World Health Organization',
                   'stability': 'rolling',
                   'title': 'One Health',
                   'url': 'https://www.who.int/health-topics/one-health'},
 'WHO-PALLCARE': {'kind': 'policy-framework',
                  'publisher': 'World Health Organization',
                  'stability': 'rolling',
                  'title': 'Palliative care',
                  'url': 'https://www.who.int/health-topics/palliative-care'},
 'WHO-SDOH': {'kind': 'policy-framework',
              'publisher': 'World Health Organization',
              'stability': 'rolling',
              'title': 'Social determinants of health',
              'url': 'https://www.who.int/news-room/fact-sheets/detail/social-determinants-of-health'},
 'WHO-SOCIALCONN2025': {'kind': 'policy-framework',
                        'publisher': 'World Health Organization',
                        'stability': 'snapshot',
                        'title': 'Report of the WHO Commission on Social Connection',
                        'url': 'https://www.who.int/groups/commission-on-social-connection/report'},
 'WHO-SOCIALQA2025': {'kind': 'policy-framework',
                      'publisher': 'World Health Organization',
                      'stability': 'snapshot',
                      'title': 'Social connection — questions and answers',
                      'url': 'https://www.who.int/news-room/questions-and-answers/item/social-connection'},
 'WHO-SRHR': {'kind': 'policy-framework',
              'publisher': 'World Health Organization',
              'stability': 'rolling',
              'title': 'Sexual and reproductive health and rights',
              'url': 'https://www.who.int/health-topics/sexual-and-reproductive-health-and-rights'}}

NOTE_SOURCE_MAP = {'archive/001-charter-and-research-discipline.md': ['SEP-IV',
                                                    'SEP-WB',
                                                    'UN-SDG2030',
                                                    'UNDP-HDR2025'],
 'archive/002-theory-family-map.md': ['SEP-CAP',
                                      'SEP-CONS',
                                      'SEP-CONTRACT',
                                      'SEP-DEON',
                                      'SEP-FEMETH',
                                      'SEP-MEANING',
                                      'SEP-PERF',
                                      'SEP-VE',
                                      'SEP-WB'],
 'archive/003-no-good-by-single-number.md': ['OECD-WB',
                                             'SEP-CAP',
                                             'SEP-IV',
                                             'SEP-WB',
                                             'UNDP-HDR2025'],
 'archive/004-personal-good-welfare-agency-meaning-and-relationship.md': ['SEP-AESTHXP',
                                                                          'SEP-AUTONOMY',
                                                                          'SEP-DIGNITY',
                                                                          'SEP-FEMAUTO',
                                                                          'SEP-MEANING',
                                                                          'SEP-RELGOODS',
                                                                          'SEP-SPORT',
                                                                          'SEP-WB'],
 'archive/005-social-good-care-trust-non-domination-and-public-justification.md': ['OHCHR-PARTICIPATE',
                                                                                   'SEP-DEMOCRACY',
                                                                                   'SEP-FEMETH',
                                                                                   'SEP-PUBLICREASON',
                                                                                   'SEP-RECOGNITION',
                                                                                   'SEP-RELGOODS',
                                                                                   'SEP-REPUB',
                                                                                   'SEP-RESPECT'],
 'archive/006-institutional-good-truth-seeking-rights-and-contestability.md': ['ILO-SDIALOGUE',
                                                                               'OECD-TRUST2025',
                                                                               'OHCHR-PARTICIPATE',
                                                                               'SEP-DEMOCRACY',
                                                                               'SEP-DIGNITY',
                                                                               'SEP-PUBLICREASON',
                                                                               'SEP-REPUB',
                                                                               'SEP-SOCIALEPI',
                                                                               'SEP-WORKLABOR'],
 'archive/007-future-good-sustainability-option-value-and-no-prosperity-by-liquidation.md': ['IPCC-SYR',
                                                                                             'OECD-WB',
                                                                                             'UN-SDG2030',
                                                                                             'UNDP-HDR2025'],
 'archive/008-measurement-dashboard-judgment-thresholds-and-policy-translation.md': ['COE-FINGAIN',
                                                                                     'ILO-DECENTWORK',
                                                                                     'ILO-SDIALOGUE',
                                                                                     'ILO-WORKTIME',
                                                                                     'OECD-ACCESSCOM',
                                                                                     'OECD-CHILDSWB2025',
                                                                                     'OECD-CONN2025',
                                                                                     'OECD-DARK',
                                                                                     'OECD-DISCRIM2025',
                                                                                     'OECD-JOBQUALITY',
                                                                                     'OECD-PRIVACY',
                                                                                     'OECD-SWB2025',
                                                                                     'OECD-TIMEUSE',
                                                                                     'OECD-TRUST2025',
                                                                                     'OECD-WB',
                                                                                     'OHCHR-CRC',
                                                                                     'OHCHR-CRPD',
                                                                                     'OHCHR-ICESCR',
                                                                                     'OHCHR-OLDERPRINC',
                                                                                     'OHCHR-PARTICIPATE',
                                                                                     'OHCHR-PRIVACY2025',
                                                                                     'OHCHR-REINTEG2025',
                                                                                     'OHCHR-RIGHTWORK',
                                                                                     'OHCHR-SRHR',
                                                                                     'OHCHR-UDHR',
                                                                                     'SEP-CAP',
                                                                                     'SEP-DISABILITYJUST',
                                                                                     'SEP-INFCONSENT',
                                                                                     'SEP-MANIP',
                                                                                     'SEP-MARKETS',
                                                                                     'SEP-PRIVACY',
                                                                                     'SEP-PRIVMED',
                                                                                     'UN-CRPD-GC2',
                                                                                     'UN-SDG2030',
                                                                                     'UNDP-HDR2025',
                                                                                     'UNESCO-CULTPUB',
                                                                                     'UNESCO-DIVEXP',
                                                                                     'UNODC-REOFFEND',
                                                                                     'WHO-AGEISM',
                                                                                     'WHO-DISHEALTH',
                                                                                     'WHO-HUMRIGHTS',
                                                                                     'WHO-LTCOLDER',
                                                                                     'WHO-MHWORK',
                                                                                     'WHO-NURTCARE',
                                                                                     'WHO-PALLCARE',
                                                                                     'WHO-SDOH',
                                                                                     'WHO-SRHR'],
 'archive/009-cross-tradition-expansion-and-canon-humility.md': ['SEP-AFRICAN',
                                                                 'SEP-BUDDHIST',
                                                                 'SEP-CHINESE'],
 'archive/010-priority-kernels-a-pluralist-working-synthesis.md': ['ILO-DECENTWORK',
                                                                   'ILO-SDIALOGUE',
                                                                   'ILO-WORKTIME',
                                                                   'IPCC-SYR',
                                                                   'OECD-JOBQUALITY',
                                                                   'OHCHR-CRC',
                                                                   'OHCHR-CRPD',
                                                                   'OHCHR-CULTLIFE',
                                                                   'OHCHR-ICESCR',
                                                                   'OHCHR-OLDERPRINC',
                                                                   'OHCHR-PARTICIPATE',
                                                                   'OHCHR-RIGHTWORK',
                                                                   'OHCHR-SRHR',
                                                                   'SEP-AESTHXP',
                                                                   'SEP-CAP',
                                                                   'SEP-CHILDHOOD',
                                                                   'SEP-CHILDRIGHTS',
                                                                   'SEP-DEMOCRACY',
                                                                   'SEP-DIGNITY',
                                                                   'SEP-DISABILITYJUST',
                                                                   'SEP-FEMAUTO',
                                                                   'SEP-INFCONSENT',
                                                                   'SEP-ITPRIV',
                                                                   'SEP-MANIP',
                                                                   'SEP-MARKETS',
                                                                   'SEP-PREF',
                                                                   'SEP-PRIVACY',
                                                                   'SEP-RECOGNITION',
                                                                   'SEP-RELGOODS',
                                                                   'SEP-REPUB',
                                                                   'SEP-SOCIALEPI',
                                                                   'SEP-SPORT',
                                                                   'SEP-WB',
                                                                   'SEP-WORKLABOR',
                                                                   'UN-CRPD-GC2',
                                                                   'UNESCO-CULTPUB',
                                                                   'UNESCO-DIVEXP',
                                                                   'WHO-HUMRIGHTS',
                                                                   'WHO-LTCOLDER',
                                                                   'WHO-MHWORK',
                                                                   'WHO-NURTCARE',
                                                                   'WHO-PALLCARE',
                                                                   'WHO-SRHR'],
 'archive/011-quarantine-world-contact-non-domination-and-regenerative-flourishing.md': ['IPCC-SYR',
                                                                                         'SEP-CAP',
                                                                                         'SEP-FEMETH',
                                                                                         'SEP-REPUB',
                                                                                         'SEP-SOCIALEPI'],
 'archive/012-open-questions-and-test-cases.md': ['COE-FINGAIN',
                                                  'ILO-DECENTWORK',
                                                  'ILO-SDIALOGUE',
                                                  'ILO-WORKTIME',
                                                  'IPCC-SYR',
                                                  'OECD-CHILDSWB2025',
                                                  'OECD-CONN2025',
                                                  'OECD-DARK',
                                                  'OECD-DISCRIM2025',
                                                  'OECD-JOBQUALITY',
                                                  'OECD-SWB2025',
                                                  'OECD-TIMEUSE',
                                                  'OECD-TRUST2025',
                                                  'OHCHR-CRC',
                                                  'OHCHR-CRPD',
                                                  'OHCHR-CULTLIFE',
                                                  'OHCHR-HUMRIGHTS',
                                                  'OHCHR-ICESCR',
                                                  'OHCHR-OLDERPRINC',
                                                  'OHCHR-PARTICIPATE',
                                                  'OHCHR-PRIVACY2025',
                                                  'OHCHR-RIGHTWORK',
                                                  'OHCHR-SRHR',
                                                  'OHCHR-UDHR',
                                                  'SEP-CHILDHOOD',
                                                  'SEP-CHILDRIGHTS',
                                                  'SEP-DEMOCRACY',
                                                  'SEP-DISABILITYJUST',
                                                  'SEP-EXPLOIT',
                                                  'SEP-INFCONSENT',
                                                  'SEP-MARKETS',
                                                  'SEP-PRIVACY',
                                                  'SEP-PUBLICREASON',
                                                  'SEP-RELGOODS',
                                                  'SEP-WB',
                                                  'SEP-WORKLABOR',
                                                  'UN-CRPD-GC2',
                                                  'UN-SDG2030',
                                                  'UNESCO-CULTPUB',
                                                  'UNESCO-DIVEXP',
                                                  'WHO-AGEISM',
                                                  'WHO-HUMRIGHTS',
                                                  'WHO-LTCOLDER',
                                                  'WHO-MHWORK',
                                                  'WHO-NURTCARE',
                                                  'WHO-PALLCARE',
                                                  'WHO-SRHR'],
 'archive/013-kernel-collisions-triage-tragic-remainder-and-repair.md': ['SEP-MDILEM',
                                                                         'SEP-PUBJUST',
                                                                         'SEP-REPUB'],
 'archive/014-kernel-admission-common-good-scaffolding-and-value-gates.md': ['OECD-WB',
                                                                             'SEP-CAP',
                                                                             'SEP-COMMONGOOD',
                                                                             'SEP-IV',
                                                                             'SEP-NEEDS',
                                                                             'SEP-PUBLICREASON',
                                                                             'SEP-VPLURAL'],
 'archive/015-patient-scope-sentience-and-living-systems.md': ['IPBES-NEXUS',
                                                               'NY-ANIMCON',
                                                               'SEP-COGDIS',
                                                               'SEP-GROUNDS',
                                                               'SEP-MORALANIMAL',
                                                               'WHO-ONEHEALTH'],
 'archive/016-distribution-sufficiency-priority-and-anti-oligarchy.md': ['OECD-WB',
                                                                         'SEP-DJUST',
                                                                         'SEP-EGAL',
                                                                         'SEP-PRIOR',
                                                                         'SEP-REPUB'],
 'archive/017-uncertainty-precaution-reversibility-and-burden-shifting.md': ['OECD-REGFUTURE',
                                                                             'SEP-MDU',
                                                                             'SEP-PUBLICREASON',
                                                                             'SEP-REPUB',
                                                                             'SEP-RISK',
                                                                             'UNESCO-CLIMATEETH'],
 'archive/018-preference-formation-adaptive-desire-and-manipulation.md': ['OECD-DARK',
                                                                          'SEP-FEMAUTO',
                                                                          'SEP-MANIP',
                                                                          'SEP-PREF'],
 'archive/019-affirmative-flourishing-play-beauty-learning-and-celebration.md': ['OECD-SWB2025',
                                                                                 'OHCHR-CULTLIFE',
                                                                                 'SEP-AESTHXP',
                                                                                 'SEP-PERF',
                                                                                 'SEP-SPORT',
                                                                                 'SEP-WB',
                                                                                 'UNESCO-CULTPUB',
                                                                                 'WHO-ARTS'],
 'archive/020-dignity-recognition-humiliation-and-belonging.md': ['OECD-DISCRIM2025',
                                                                  'OHCHR-HUMRIGHTS',
                                                                  'SEP-DIGNITY',
                                                                  'SEP-RECOGNITION',
                                                                  'SEP-RESPECT',
                                                                  'WHO-SDOH'],
 'archive/021-repair-accountability-forgiveness-and-second-chances.md': ['OHCHR-PRISONERS',
                                                                         'OHCHR-REINTEG2025',
                                                                         'SEP-ATONE',
                                                                         'SEP-FORGIVE',
                                                                         'SEP-RECONCILE',
                                                                         'UNODC-REOFFEND',
                                                                         'UNODC-RJ'],
 'archive/022-voice-participation-and-co-authorship.md': ['ILO-SDIALOGUE',
                                                          'OECD-TRUST2025',
                                                          'OHCHR-PARTICIPATE',
                                                          'SEP-AUTONOMY',
                                                          'SEP-DEMOCRACY',
                                                          'SEP-REPUB',
                                                          'SEP-WORKLABOR'],
 'archive/023-privacy-sanctuary-and-protected-opacity.md': ['OECD-PRIVACY',
                                                            'OHCHR-PRIVACY2025',
                                                            'SEP-ITPRIV',
                                                            'SEP-PRIVACY'],
 'archive/024-non-fungibility-bounded-markets-and-protected-spheres.md': ['COE-FINGAIN',
                                                                          'SEP-EXPLOIT',
                                                                          'SEP-MARKETS',
                                                                          'UNESCO-DIVEXP'],
 'archive/025-rest-rhythm-and-time-sovereignty.md': ['ILO-WORKTIME',
                                                     'OECD-TIMEUSE',
                                                     'OHCHR-CULTLIFE',
                                                     'OHCHR-ICESCR',
                                                     'OHCHR-UDHR',
                                                     'SEP-AUTONOMY',
                                                     'SEP-WORKLABOR',
                                                     'WHO-MHWORK'],
 'archive/026-accessibility-accommodation-and-world-fit.md': ['OECD-ACCESSCOM',
                                                              'OHCHR-CRPD',
                                                              'SEP-DISABILITY',
                                                              'SEP-DISABILITYCRIT',
                                                              'SEP-DISABILITYJUST',
                                                              'SEP-DISWB',
                                                              'UN-CRPD-GC2',
                                                              'WHO-DISHEALTH'],
 'archive/027-childhood-development-and-just-guardianship.md': ['OECD-CHILDSWB2025',
                                                                'OHCHR-CRC',
                                                                'SEP-CHILDHOOD',
                                                                'SEP-CHILDRIGHTS',
                                                                'WHO-NURTCARE'],
 'archive/028-aging-frailty-mortality-and-bereavement.md': ['OECD-CONN2025',
                                                            'OHCHR-OLDERPRINC',
                                                            'SEP-DEATH',
                                                            'WHO-AGEISM',
                                                            'WHO-LTCOLDER',
                                                            'WHO-PALLCARE'],
 'archive/029-home-dwelling-place-and-non-displacement.md': ['OECD-BUILTENV',
                                                             'OHCHR-HOMELESSNESS',
                                                             'OHCHR-HOUSING',
                                                             'OHCHR-HOUSINGGUIDE',
                                                             'SEP-ARCHITECTURE',
                                                             'SEP-PROPERTY',
                                                             'UNHCR-GT2025'],
 'archive/030-bodily-integrity-consent-and-reproductive-agency.md': ['OHCHR-SRHR',
                                                                     'SEP-INFCONSENT',
                                                                     'SEP-PRIVMED',
                                                                     'WHO-HUMRIGHTS',
                                                                     'WHO-SRHR'],
 'archive/031-intimacy-friendship-chosen-kin-and-exit.md': ['OHCHR-HARMFUL',
                                                            'OHCHR-ICCPR',
                                                            'OHCHR-LGBTI',
                                                            'SEP-FRIEND',
                                                            'SEP-LOVE',
                                                            'SEP-RELGOODS',
                                                            'WHO-SOCIALCONN2025',
                                                            'WHO-SOCIALQA2025'],
 'archive/032-livelihood-meaningful-work-and-non-servility.md': ['ILO-DECENTWORK',
                                                                 'ILO-SDIALOGUE',
                                                                 'ILO-WORKTIME',
                                                                 'OECD-JOBQUALITY',
                                                                 'OHCHR-ICESCR',
                                                                 'OHCHR-RIGHTWORK',
                                                                 'SEP-WORKLABOR',
                                                                 'WHO-MHWORK'],
 'archive/033-movement-migration-membership-and-non-exile.md': ['IOM-REGPATH',
                                                                'OHCHR-NATIONALITY',
                                                                'OHCHR-UDHR',
                                                                'SEP-CITIZENSHIP',
                                                                'SEP-IMMIGRATION',
                                                                'UNHCR-GT2025',
                                                                'UNHCR-STATELESS2025']}

THREADS = [{'description': 'Why a good order should be built for human variation in advance rather than '
                 'making people petition for ordinary entry into shared life through '
                 'accommodation, disclosure, or segregation.',
  'id': 'accessibility-world-fit',
  'notes': ['archive/026-accessibility-accommodation-and-world-fit.md'],
  'title': 'Accessibility, disability, and world-fit'},
 {'description': 'Why a theory of the good cannot stop at harm prevention and civic protection, '
                 'but must also make room for beauty, play, learning, craft, and shared '
                 'celebration without imposing one official life script.',
  'id': 'affirmative-flourishing',
  'notes': ['archive/019-affirmative-flourishing-play-beauty-learning-and-celebration.md'],
  'title': 'Affirmative flourishing, culture, and play'},
 {'description': 'How bodily integrity, informed consent, reproductive agency, and resistance to '
                 'bodily commandeering fit into a theory of the good across care, medicine, public '
                 'health, dependency, and ordinary institutions.',
  'id': 'embodied-agency',
  'notes': ['archive/030-bodily-integrity-consent-and-reproductive-agency.md'],
  'title': 'Bodily integrity, consent, and reproductive agency'},
 {'description': 'Cross-tradition widening, current synthesis candidate, speculative compression, '
                 'test backlog, a protocol for unavoidable collisions among protected goods, and a '
                 'growth rule for admitting future candidate values.',
  'id': 'canon-expansion',
  'notes': ['archive/009-cross-tradition-expansion-and-canon-humility.md',
            'archive/010-priority-kernels-a-pluralist-working-synthesis.md',
            'archive/011-quarantine-world-contact-non-domination-and-regenerative-flourishing.md',
            'archive/012-open-questions-and-test-cases.md',
            'archive/013-kernel-collisions-triage-tragic-remainder-and-repair.md',
            'archive/014-kernel-admission-common-good-scaffolding-and-value-gates.md'],
  'title': 'Canon expansion, synthesis, quarantine, conflict protocol, and growth rule'},
 {'description': 'Why a good order must treat children as present bearers of the good whose '
                 'dependency justifies answerable guidance, play, developmental support, and voice '
                 'proportionate to evolving capacities rather than ownership, neglect, or adultist '
                 'overcontrol.',
  'id': 'childhood-development',
  'notes': ['archive/027-childhood-development-and-just-guardianship.md'],
  'title': 'Childhood, development, and just guardianship'},
 {'description': 'How equal standing, anti-humiliation, and plural belonging matter in their own '
                 'right rather than only as by-products of income, formal rights, or aggregate '
                 'welfare.',
  'id': 'dignity-recognition',
  'notes': ['archive/020-dignity-recognition-humiliation-and-belonging.md'],
  'title': 'Dignity, recognition, and belonging'},
 {'description': 'How protected goods and burdens should be distributed once scarcity, inequality, '
                 'and concentration of power are in play.',
  'id': 'distributional-shape',
  'notes': ['archive/016-distribution-sufficiency-priority-and-anti-oligarchy.md'],
  'title': 'Distribution, priority, and civic equality'},
 {'description': 'Intergenerational continuity and the translation of value into governance.',
  'id': 'future-policy',
  'notes': ['archive/007-future-good-sustainability-option-value-and-no-prosperity-by-liquidation.md',
            'archive/008-measurement-dashboard-judgment-thresholds-and-policy-translation.md'],
  'title': 'Future good and policy translation'},
 {'description': 'Why a good order must let people dwell somewhere in security, privacy, '
                 'continuity, and dignity rather than merely covering bodies while tolerating '
                 'homelessness, warehousing, or serial uprooting.',
  'id': 'dwelling-place',
  'notes': ['archive/029-home-dwelling-place-and-non-displacement.md'],
  'title': 'Home, dwelling, and non-displacement'},
 {'description': 'Why a good order must let people form, sustain, revise, and leave close ties in '
                 'safety and dignity, without reducing serious attachment to blood, marriage, or '
                 'institutionally approved households.',
  'id': 'intimacy-chosen-kin',
  'notes': ['archive/031-intimacy-friendship-chosen-kin-and-exit.md'],
  'title': 'Intimacy, friendship, chosen kin, and exit'},
 {'description': 'Why a good order must let people age, depend, grieve, and die with dignity, '
                 'support, continuity, and social accompaniment rather than abandonment, '
                 'warehousing, or ageist disposal.',
  'id': 'later-life',
  'notes': ['archive/028-aging-frailty-mortality-and-bereavement.md'],
  'title': 'Later life, mortality, and bereavement'},
 {'description': 'Why a good order must make livelihood materially possible without servility, job '
                 'lock, unsafe extraction, or the assumption that wage status measures full human '
                 'worth.',
  'id': 'livelihood-work',
  'notes': ['archive/032-livelihood-meaningful-work-and-non-servility.md'],
  'title': 'Livelihood, meaningful work, and non-servility'},
 {'description': 'How the archive should think, compress, and refuse premature monism.',
  'id': 'metaframe',
  'notes': ['archive/001-charter-and-research-discipline.md',
            'archive/002-theory-family-map.md',
            'archive/003-no-good-by-single-number.md'],
  'title': 'Meta-frame and method'},
 {'id': 'movement-membership',
  'title': 'Movement, migration, membership, and non-exile',
  'description': 'Why a good order must let people stay, move, seek safety, return, reunite, and '
                 'belong without arbitrary exile, camp limbo, or degrading status precarity.',
  'notes': ['archive/033-movement-migration-membership-and-non-exile.md']},
 {'description': 'Why a good order must distinguish ordinary exchange from domains where pricing '
                 'exploits vulnerability, corrupts standing, or misdescribes what should remain '
                 'shared, bounded, or not-for-sale.',
  'id': 'bounded-markets',
  'notes': ['archive/024-non-fungibility-bounded-markets-and-protected-spheres.md'],
  'title': 'Non-fungibility, bounded markets, and protected spheres'},
 {'description': 'Who counts directly, how sentience and agency differ, and how ecosystems and '
                 'other enabling systems matter without collapsing into the same category as '
                 'welfare subjects.',
  'id': 'patient-scope',
  'notes': ['archive/015-patient-scope-sentience-and-living-systems.md'],
  'title': 'Patient scope and living systems'},
 {'description': 'What makes a life go well for a person or other being, including how agency and '
                 'stated preference can be deformed by deprivation or manipulation.',
  'id': 'personal-good',
  'notes': ['archive/004-personal-good-welfare-agency-meaning-and-relationship.md',
            'archive/018-preference-formation-adaptive-desire-and-manipulation.md'],
  'title': 'Personal good, agency, and preference formation'},
 {'description': 'Why a good order should preserve seclusion, confidentiality, selective '
                 'self-disclosure, and protected opacity rather than demanding permanent '
                 'legibility to states, firms, families, or publics.',
  'id': 'privacy-sanctuary',
  'notes': ['archive/023-privacy-sanctuary-and-protected-opacity.md'],
  'title': 'Privacy, sanctuary, and protected opacity'},
 {'description': 'How a good order responds after wrongdoing or breach: truthful acknowledgment, '
                 'victim protection, repair, bounded mercy, and reviewable return without coercing '
                 'forgiveness or freezing people permanently at their worst act.',
  'id': 'repair-return',
  'notes': ['archive/021-repair-accountability-forgiveness-and-second-chances.md'],
  'title': 'Repair, accountability, and second chances'},
 {'description': 'Why a good order must preserve real rest, predictable off-time, and freedom from '
                 'permanent availability, schedule precarity, and time poverty.',
  'id': 'time-sovereignty',
  'notes': ['archive/025-rest-rhythm-and-time-sovereignty.md'],
  'title': 'Rest, rhythm, and time sovereignty'},
 {'description': 'Relational, civic, and institutional features of a better common world.',
  'id': 'social-institutional-good',
  'notes': ['archive/005-social-good-care-trust-non-domination-and-public-justification.md',
            'archive/006-institutional-good-truth-seeking-rights-and-contestability.md'],
  'title': 'Social and institutional good'},
 {'description': 'How the archive should act when empirical, moral, and institutional uncertainty '
                 'remain deep but the stakes are serious.',
  'id': 'uncertainty-discipline',
  'notes': ['archive/017-uncertainty-precaution-reversibility-and-burden-shifting.md'],
  'title': 'Uncertainty, precaution, and reversibility'},
 {'description': 'Why a good order should not merely protect or serve people, but also give them '
                 'meaningful and reviewable ways to help shape public, economic, and institutional '
                 'rule.',
  'id': 'voice-participation',
  'notes': ['archive/022-voice-participation-and-co-authorship.md'],
  'title': 'Voice, participation, and shared rule'}]

CONTROL_SURFACES = [{'purpose': 'Keep the archive from collapsing into mere harm-management by protecting access to '
             'play, beauty, learning, craft, and shared celebration above the floor.',
  'surface': 'affirmative flourishing layer'},
 {'purpose': 'Keep price, payment, and willingness to pay from being mistaken for sufficient moral '
             'permission in domains where standing, care, culture, or bodily integrity are at '
             'stake.',
  'surface': 'bounded-markets rule'},
 {'purpose': 'Keep bold synthesis visible without silently hardening it into law.',
  'surface': 'canon/quarantine split'},
 {'purpose': 'Keep protection and service from hardening into guardianship by requiring '
             'meaningful, reviewable opportunities for affected people to shape shared rule.',
  'surface': 'co-authorship rule'},
 {'purpose': 'Translate value into governance without scalar capture.',
  'surface': 'dashboard pluralism'},
 {'purpose': 'Keep childhood from being treated as mere adult preparation by making present goods, '
             'play, caregiver stability, and evolving-capacity voice visible in design and policy.',
  'surface': 'developmental-fit rule'},
 {'purpose': 'Keep later life, frailty, palliative care, social connection, and bereavement '
             'visible so longevity is not confused with ageist abandonment, coercive prolongation, '
             'or social death before biological death.',
  'surface': 'dignified-finitude rule'},
 {'purpose': 'Keep humiliation, stigma, civic invisibility, and caste-like ranking visible as '
             'direct degradations rather than hiding them behind income, rights, or average '
             'welfare.',
  'surface': 'dignity-and-recognition floor'},
 {'purpose': 'Keep floors, priority to the worse-off, and anti-oligarchic safeguards visible '
             'whenever protected goods are allocated under scarcity.',
  'surface': 'distribution rule'},
 {'purpose': 'Keep shelter, tenure, neighborhood continuity, and freedom from forced uprooting '
             'visible so indoor status is not confused with the ability to actually dwell.',
  'surface': 'dwelling rule'},
 {'purpose': 'Keep bodily integrity, valid consent, and reproductive agency visible so care, '
             'medicine, safety, or family order do not quietly become excuses for bodily '
             'commandeering.',
  'surface': 'embodied-agency rule'},
 {'purpose': 'Keep close personal bonds visible as non-substitutable goods while protecting people '
             'against coercive kinship, forced intimacy, chosen-kin erasure, and exit penalties.',
  'surface': 'intimate-association-and-exit rule'},
 {'purpose': 'Sort candidate goods into kernels, scaffolding, indicators, local aims, or '
             'quarantine before the ontology bloats.',
  'surface': 'kernel admission gates'},
 {'purpose': 'Keep decent livelihood, work quality, and the refusal of degrading labor visible so '
             'employment counts do not hide servility, job lock, or contribution stigma.',
  'surface': 'livelihood-and-nonservility rule'},
 {'surface': 'movement-and-membership rule',
  'purpose': 'Keep arbitrary exile, status precarity, family separation, blocked return, and camp '
             'limbo visible so shelter or service delivery do not masquerade as full belonging.'},
 {'purpose': 'Separate direct welfare subjects from life-supporting systems so scope can widen '
             'without ontology blur.',
  'surface': 'patient-scope distinction'},
 {'purpose': 'Keep stated desire morally important without letting resignation or manipulation '
             'masquerade as the good.',
  'surface': 'preference-formation audit'},
 {'purpose': 'Protect high-weight floors before optimizing above them.',
  'surface': 'priority kernels'},
 {'purpose': 'Keep agency, intimacy, dissent, and selective self-disclosure from being dissolved '
             'by permanent surveillance, mandatory exposure, or one-way legibility to power.',
  'surface': 'protected-opacity rule'},
 {'purpose': 'Keep accountability distinct from humiliation and permanent civic exile by requiring '
             'victim protection, reparative pathways, and reviewable return after breach.',
  'surface': 'repair-and-return rule'},
 {'purpose': 'Preserve replay paths while keeping notes compact.', 'surface': 'source registry'},
 {'purpose': 'Keep growth legible across personal, social, institutional, and temporal layers.',
  'surface': 'thread map'},
 {'purpose': 'Keep usable time, rest, schedule predictability, and freedom from permanent '
             'availability visible so rights and flourishing do not become merely nominal.',
  'surface': 'time-sovereignty rule'},
 {'purpose': 'Handle unavoidable kernel collisions without pretending all losses are compensable.',
  'surface': 'tragic remainder protocol'},
 {'purpose': 'Keep serious uncertainty from licensing either irreversible harm or permanent '
             'status-quo paralysis.',
  'surface': 'uncertainty rule'},
 {'purpose': 'Keep normate design, petition-based access, and segregated service visible so equal '
             'standing is not confused with nominal availability.',
  'surface': 'world-fit rule'}]

ASSURANCE_ARTIFACTS = [{'artifact': 'SOURCES.json',
  'role': 'Machine-readable source registry with reverse note mapping.'},
 {'artifact': 'ARCHIVE_INDEX.json',
  'role': 'Generated note index with titles, theses, and inferred tags.'},
 {'artifact': 'THREAD_SUMMARY.json',
  'role': "Compact summary of the archive's current conceptual threads."},
 {'artifact': 'MANIFEST.json',
  'role': 'File hash manifest for package integrity and merge discipline.'}]

LIFECYCLE_GATES = {'challenge-and-revision': ['archive/012-open-questions-and-test-cases.md',
                            'archive/013-kernel-collisions-triage-tragic-remainder-and-repair.md',
                            'archive/014-kernel-admission-common-good-scaffolding-and-value-gates.md'],
 'expansion-and-synthesis': ['archive/009-cross-tradition-expansion-and-canon-humility.md',
                             'archive/010-priority-kernels-a-pluralist-working-synthesis.md',
                             'archive/011-quarantine-world-contact-non-domination-and-regenerative-flourishing.md'],
 'operationalization': ['archive/008-measurement-dashboard-judgment-thresholds-and-policy-translation.md',
                        'archive/017-uncertainty-precaution-reversibility-and-burden-shifting.md'],
 'scoping': ['archive/001-charter-and-research-discipline.md',
             'archive/002-theory-family-map.md',
             'archive/003-no-good-by-single-number.md'],
 'substantive-core': ['archive/004-personal-good-welfare-agency-meaning-and-relationship.md',
                      'archive/005-social-good-care-trust-non-domination-and-public-justification.md',
                      'archive/006-institutional-good-truth-seeking-rights-and-contestability.md',
                      'archive/007-future-good-sustainability-option-value-and-no-prosperity-by-liquidation.md',
                      'archive/015-patient-scope-sentience-and-living-systems.md',
                      'archive/016-distribution-sufficiency-priority-and-anti-oligarchy.md',
                      'archive/018-preference-formation-adaptive-desire-and-manipulation.md',
                      'archive/019-affirmative-flourishing-play-beauty-learning-and-celebration.md',
                      'archive/020-dignity-recognition-humiliation-and-belonging.md',
                      'archive/021-repair-accountability-forgiveness-and-second-chances.md',
                      'archive/022-voice-participation-and-co-authorship.md',
                      'archive/023-privacy-sanctuary-and-protected-opacity.md',
                      'archive/024-non-fungibility-bounded-markets-and-protected-spheres.md',
                      'archive/025-rest-rhythm-and-time-sovereignty.md',
                      'archive/026-accessibility-accommodation-and-world-fit.md',
                      'archive/027-childhood-development-and-just-guardianship.md',
                      'archive/028-aging-frailty-mortality-and-bereavement.md',
                      'archive/029-home-dwelling-place-and-non-displacement.md',
                      'archive/030-bodily-integrity-consent-and-reproductive-agency.md',
                      'archive/031-intimacy-friendship-chosen-kin-and-exit.md',
                      'archive/032-livelihood-meaningful-work-and-non-servility.md',
                      'archive/033-movement-migration-membership-and-non-exile.md']}

REQUIRED_ROOT_FILES = ['ARCHIVE_INDEX.json',
 'ASSURANCE_ARTIFACTS.json',
 'CHANGELOG.md',
 'CONTROL_SURFACES.json',
 'INDEX.md',
 'LIFECYCLE_GATES.json',
 'MANIFEST.json',
 'Makefile',
 'README.md',
 'RELEASES.json',
 'SOURCES.json',
 'SOURCES.md',
 'START_HERE.md',
 'THREADS.json',
 'THREADS.md',
 'THREAD_SUMMARY.json']

TAG_RULES = {'accessibility': ['accessibility',
                   'accommodation',
                   'assistive',
                   'barrier',
                   'captioning',
                   'disability',
                   'normate',
                   'plain language',
                   'universal design',
                   'world-fit'],
 'admission': ['admission', 'kernel', 'common-good', 'scaffolding', 'indicator', 'proxy'],
 'agency': ['agency', 'autonomy', 'self-direction', 'dignity'],
 'bodily-integrity': ['bodily integrity',
                      'consent',
                      'informed consent',
                      'reproductive agency',
                      'sterilization',
                      'forced pregnancy',
                      'restraint',
                      'intimate exam',
                      'coercive testing',
                      'body brokerage'],
 'care': ['care', 'relationship', 'friendship', 'social contact'],
 'childhood': ['child',
               'children',
               'childhood',
               'guardian',
               'guardianship',
               'caregiver',
               'developmental',
               'best interests',
               'evolving capacities'],
 'commodification': ['commodification',
                     'market',
                     'for sale',
                     'price',
                     'pricing',
                     'fungible',
                     'non-fungible',
                     'auction',
                     'pay-to-access',
                     'public option'],
 'conflict': ['dilemma', 'remainder', 'triage', 'conflict', 'repair'],
 'cross-tradition': ['african', 'chinese', 'buddhist', 'canon'],
 'dignity-recognition': ['dignity',
                         'recognition',
                         'humiliation',
                         'stigma',
                         'belonging',
                         'status injury',
                         'equal standing'],
 'distribution': ['distribution',
                  'inequality',
                  'sufficiency',
                  'priority',
                  'worst-off',
                  'oligarchy',
                  'inheritance'],
 'dwelling-place': ['home',
                    'housing',
                    'dwelling',
                    'eviction',
                    'tenure',
                    'homeless',
                    'homelessness',
                    'displacement',
                    'uprooting',
                    'neighborhood',
                    'neighbourhood',
                    'shelter'],
 'future': ['future', 'intergenerational', 'sustainability', 'ecological', 'climate'],
 'institutions': ['institution', 'contestability', 'rights', 'epistemic', 'truth-seeking'],
 'intimacy-kinship': ['friendship',
                      'intimacy',
                      'chosen kin',
                      'chosen family',
                      'family rejection',
                      'forced marriage',
                      'coercive kinship',
                      'visitation',
                      'companion'],
 'later-life': ['ageing',
                'aging',
                'older person',
                'older people',
                'frailty',
                'mortality',
                'bereavement',
                'grief',
                'palliative',
                'long-term care',
                'later life'],
 'measurement': ['metric', 'dashboard', 'index', 'measurement', 'score'],
 'movement-membership': ['movement',
                         'migration',
                         'asylum',
                         'return',
                         'nationality',
                         'stateless',
                         'membership',
                         'exile',
                         'deportation',
                         'border',
                         'family reunification',
                         'regular pathway'],
 'nondomination': ['domination', 'public justification', 'standing', 'coercion'],
 'participation': ['voice',
                   'participation',
                   'democracy',
                   'shared rule',
                   'co-authorship',
                   'co-determination',
                   'workplace democracy'],
 'preference-formation': ['preference',
                          'adaptive preference',
                          'manipulation',
                          'dark pattern',
                          'desire formation'],
 'privacy': ['privacy',
             'sanctuary',
             'seclusion',
             'confidentiality',
             'surveillance',
             'opacity',
             'legibility',
             'selective disclosure',
             'encryption'],
 'repair-return': ['repair',
                   'forgiveness',
                   'reconciliation',
                   'reintegration',
                   'second chance',
                   're-entry',
                   'reentry',
                   'mercy',
                   'amends'],
 'synthesis': ['priority kernel', 'synthesis', 'quarantine', 'hypothesis'],
 'time-sovereignty': ['rest',
                      'leisure',
                      'sleep',
                      'time poverty',
                      'schedule',
                      'always-on',
                      'disconnect',
                      'availability',
                      'off-time',
                      'rhythm'],
 'uncertainty': ['uncertainty',
                 'precaution',
                 'reversible',
                 'irreversible',
                 'risk',
                 'burden of proof',
                 'option value'],
 'wellbeing': ['well-being', 'welfare', 'flourish', 'personal good', 'life go well']}

RELEASE_HIGHLIGHTS = ['added a canon-level note on movement, migration, membership, and non-exile so the archive no '
 'longer treats people as well-served while they remain trapped by arbitrary exile, status '
 'precarity, or blocked return',
 'tightened the synthesis, dashboard, and stress layers so family separation, camp limbo, '
 'statelessness, deportability, and regular-pathway failure become visible',
 'expanded the stress frontier with a border-externalization / statelessness / '
 'climate-displacement-limbo pressure case',
 'strengthened lint so note-source mappings must stay alphabetically ordered for more stable '
 'long-run diffs']

def current_revision() -> str:
    return f"rev{REVISION:04d}"
