#!/usr/bin/env node
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { performance } from 'node:perf_hooks';
import { REVISION, VERSION, TraceLog, createCrossLaneScheduler, createBlockStoreLaneAdapter, digestBytesHex } from '../src/browserrt.mjs';
const TASK_ID = 'scheduler:storage-lane-quarantine-restore-backpressure-binding-proof';
const DEFAULT_OUT = `artifacts/validation/REV${REVISION.slice(3)}-STORAGE-LANE-QUARANTINE-RESTORE-BACKPRESSURE-BINDING-PROBE.json`;
const argValue = (argv, flag, fallback = null) => { const i = argv.indexOf(flag); return i >= 0 ? argv[i + 1] : fallback; };
function bytes(v){ return typeof v === 'string' ? new TextEncoder().encode(v) : v instanceof Uint8Array ? v : new Uint8Array(v); }
function makeScheduler(label, trace){ return createCrossLaneScheduler({ label, trace, lanes:[{id:'storage',rank:70,capacity:1,quantum:4096,maxQueuedCost:8192},{id:'maintenance',rank:10,capacity:1,quantum:64,maxQueuedCost:128}]}); }
function makeStore(){ const records=new Map(); return { name:'restore-backpressure-memory-store', provider:'memory:restore-backpressure', async put(payload){ const b=bytes(payload); const hash=await digestBytesHex(b); const digest=`sha256:${hash}`; records.set(digest,b); return { ref:{id:`block:${digest}`, digest, hash, backend:this.provider, bytes:b.byteLength}, digest, hash, bytes:b.byteLength, duplicate:false }; }, async get(ref){ const d=typeof ref==='string'?ref:ref?.digest; if(!records.has(d)) throw new Error(`missing ${d}`); return new Uint8Array(records.get(d)); }, async has(ref){ const d=typeof ref==='string'?ref:ref?.digest; return records.has(d); }, async verify(ref){ const d=typeof ref==='string'?ref:ref?.digest; const b=records.get(d); return { ok:Boolean(b), present:Boolean(b), digest:d, bytes:b?.byteLength??0 }; }, async delete(ref){ const d=typeof ref==='string'?ref:ref?.digest; return records.delete(d); }, async estimate(){ return { usage:[...records.values()].reduce((s,b)=>s+b.byteLength,0), quota:null, usageDetails:{ records:records.size } }; }, async cleanupForTest(){ records.clear(); return true; }, async waitForSettled(){ return { ok:true, reason:'memory-store-settled', last:{heldCount:0,pendingCount:0,available:true} }; }, snapshot(){ return { name:this.name, provider:this.provider, blockCount:records.size }; } }; }
function row(opId, status){ return Object.freeze({ opId, kind:'put', lane:'storage', timeoutMs:250, timedOutAtMs:1700000000000 + opId.length, settledAtMs:1700000000500 + opId.length, result: status==='successful'?{ disposition:'synthetic-late-success' }:undefined, error: status==='failed'?{ name:'SyntheticFailure', message:'synthetic late failure', code:'BRT_OPFS_OPERATION_FAILED', storageDisposition:'BRT_OPFS_OPERATION_FAILED' }:undefined }); }
function ledger(){ const successful=[row('restore-backpressure-success','successful')]; const failed=[row('restore-backpressure-failure','failed')]; return Object.freeze({ schema:'brt.storageLane.timedOutOperationQuarantine.v1', exportedAtMs:Date.now(), label:`${REVISION}-restore-backpressure-ledger`, reason:'restore-backpressure-import', lane:'storage', counts:{ total:2, unsettled:0, successful:1, failed:1 }, unsettledTimedOutOperations:[], successfulTimedOutOperations:successful, failedTimedOutOperations:failed }); }
export async function runProbe(){ const started=performance.now(); const trace=new TraceLog(); const adapter=createBlockStoreLaneAdapter({ label:`${REVISION}-restore-backpressure-adapter`, store:makeStore(), scheduler:makeScheduler(`${REVISION}-restore-backpressure-scheduler`, trace), trace, lane:'storage', defaultOperationTimeoutMs:1000 });
  const emptyLedger={...ledger(), counts:{total:0,unsettled:0,successful:0,failed:0}, successfulTimedOutOperations:[], failedTimedOutOperations:[]};
  const emptyImport=adapter.importTimedOutOperationQuarantine(emptyLedger,{ lane:'storage', reason:'empty-import-mark-unhealthy-false', markUnhealthy:false });
  const laneAfterEmpty=adapter.snapshot().executor.scheduler.lanes.find(l=>l.id==='storage');
  const importResult=adapter.importTimedOutOperationQuarantine(ledger(),{ lane:'storage', reason:'nonempty-import-mark-unhealthy-false', markUnhealthy:false });
  const snapAfter=adapter.snapshot(); const laneAfter=snapAfter.executor.scheduler.lanes.find(l=>l.id==='storage');
  const rejected=adapter.schedulePut('must-not-mutate-while-imported-quarantine-remains',{ id:'restore-backpressure-rejected-put', priority:'user-visible' });
  const markHealthy=adapter.markHealthy('storage','unsafe-mark-healthy-while-quarantine-remains');
  const blocked=await adapter.recoverWhenStoreSettled({ timeoutMs:50, intervalMs:5, reason:'blocked-by-imported-quarantine' });
  const quarantineBeforeClear=adapter.timedOutOperationQuarantine('storage');
  const reviewManifest=adapter.createTimedOutOperationQuarantineReview({ lane:'storage', category:'all', opIds:['restore-backpressure-success','restore-backpressure-failure'], reviewer:'release-probe', reviewToken:`${REVISION}-restore-backpressure-reviewed`, reason:'review-for-forced-import-backpressure' });
  const missingFingerprintClear=adapter.clearTimedOutOperationQuarantine({ lane:'storage', category:'all', opIds:['restore-backpressure-success','restore-backpressure-failure'], reviewed:true, reviewToken:`${REVISION}-restore-backpressure-missing-fingerprint`, requireReviewFingerprint:true, reason:'missing-fingerprint-clear-must-fail' });
  const clear=adapter.clearTimedOutOperationQuarantine({ reviewManifest, requireReviewFingerprint:true, reason:'reviewed-scoped-bound-clear-after-forced-import' });
  const recovered=await adapter.recoverWhenStoreSettled({ timeoutMs:50, intervalMs:5, reason:'recover-after-reviewed-scoped-bound-clear' });
  const accepted=adapter.schedulePut(`BrowserRT ${REVISION} restore backpressure recovered write`,{ id:'restore-backpressure-recovered-put', priority:'user-visible' });
  const drain=await adapter.drain({ maxSteps:2 }); const recoveredResult=drain.results.find(r=>r.opId==='restore-backpressure-recovered-put')||null; const recoveredVerify=recoveredResult?.result?.ref?await adapter.store.verify(recoveredResult.result.ref):null;
  const traceKinds=trace.snapshot().map(e=>e.kind); const finalSnapshot=adapter.snapshot();
  assert.equal(emptyImport.ok,true); assert.equal(emptyImport.markUnhealthyForced,false); assert.equal(laneAfterEmpty.healthy,true);
  assert.equal(importResult.ok,true); assert.equal(importResult.importedCount,2); assert.equal(importResult.markUnhealthyRequested,false); assert.equal(importResult.markUnhealthyForced,true); assert.equal(importResult.markedUnhealthyLanes.length,1);
  assert.equal(laneAfter.healthy,false); assert.equal(laneAfter.healthReason,'timed-out-operation-quarantine-imported');
  assert.equal(rejected.accepted,false); assert.equal(rejected.scheduler.noMutation,true); assert.equal(markHealthy.healthy,false); assert.equal(markHealthy.disposition,'rejected-timed-out-operation-quarantine'); assert.equal(blocked.recovered,false);
  assert.equal(reviewManifest.reviewFingerprint, quarantineBeforeClear.reviewFingerprint); assert.equal(missingFingerprintClear.ok,false); assert.equal(missingFingerprintClear.code,'timed-out-quarantine-clear-review-fingerprint-required'); assert.equal(clear.ok,true); assert.equal(clear.reviewFingerprint, reviewManifest.reviewFingerprint); assert.equal(recovered.recovered,true); assert.equal(accepted.accepted,true); assert.equal(recoveredResult?.ok,true); assert.equal(recoveredVerify?.ok,true);
  assert.equal(finalSnapshot.executor.stats.quarantineLedgerImportBackpressureForced,1); assert.ok(traceKinds.includes('storage-lane:timed-out-quarantine-import-backpressure-forced')); assert.ok(traceKinds.includes('storage-lane:timed-out-quarantine-review-created'));
  return { project:'BrowserRT', revision:REVISION, version:VERSION, schema:1, probe_id:`${REVISION}-storage-lane-quarantine-restore-backpressure-proof`, task_id:TASK_ID, status:'passed', generatedAt:new Date().toISOString(), durationMs:Math.round(performance.now()-started), observations:{ emptyImport, laneAfterEmpty, importResult, laneAfter, rejected, markHealthy, blocked, quarantineBeforeClear, reviewManifest, missingFingerprintClear, clear, recovered, accepted, recoveredResult, recoveredVerify, finalSnapshot, traceKinds }, claimsChecked:['non-empty timeout-quarantine import forces backpressure even with markUnhealthy:false','follow-on write rejects with noMutation','review fingerprint bound clear gates recovery'], nonClaims:['Synthetic release-tier proof only; no browser, cancellation, rollback, durability, quota, eviction, or production-readiness claim.'] };
}
const argv=process.argv.slice(2); const out=argValue(argv,'--json',DEFAULT_OUT); try{ const report=await runProbe(); if(out){ await mkdir(dirname(out),{recursive:true}); await writeFile(out,JSON.stringify(report,null,2)+'\n'); console.log(out);} else console.log(JSON.stringify(report,null,2)); }catch(error){ const report={ project:'BrowserRT', revision:REVISION, version:VERSION, schema:1, probe_id:`${REVISION}-storage-lane-quarantine-restore-backpressure-proof`, task_id:TASK_ID, status:'failed', generatedAt:new Date().toISOString(), error:{ name:error?.name||'Error', message:error?.message||String(error), stack:error?.stack }, nonClaims:['Failed proof is not silently skipped.']}; if(out){ await mkdir(dirname(out),{recursive:true}); await writeFile(out,JSON.stringify(report,null,2)+'\n'); console.error(out);} console.error(`[storage_lane_quarantine_restore_backpressure_probe] FAIL: ${error?.stack||error}`); process.exitCode=1; }
