#!/usr/bin/env node
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { performance } from 'node:perf_hooks';
import { REVISION, VERSION, TraceLog, createCrossLaneScheduler, createBlockStoreLaneAdapter, digestBytesHex } from '../src/browserrt.mjs';

const TASK_ID = 'scheduler:storage-lane-quarantine-legacy-clear-binding-proof';
const DEFAULT_OUT = `artifacts/validation/REV${REVISION.slice(3)}-STORAGE-LANE-QUARANTINE-LEGACY-CLEAR-BINDING-PROBE.json`;
const argValue = (argv, flag, fallback = null) => { const i = argv.indexOf(flag); return i >= 0 ? argv[i + 1] : fallback; };
function bytes(value) { if (value instanceof Uint8Array) return new Uint8Array(value); if (value instanceof ArrayBuffer) return new Uint8Array(value.slice(0)); if (ArrayBuffer.isView(value)) return new Uint8Array(value.buffer.slice(value.byteOffset, value.byteOffset + value.byteLength)); return new TextEncoder().encode(String(value)); }
function makeScheduler(label, trace) { return createCrossLaneScheduler({ label, trace, lanes: [{ id: 'storage', rank: 70, capacity: 2, quantum: 4096, maxQueuedCost: 8192 }, { id: 'maintenance', rank: 10, capacity: 1, quantum: 64, maxQueuedCost: 128 }] }); }
function makeStore({ trace = null } = {}) { const records = new Map(); return { name: 'synthetic-quarantine-legacy-clear-binding-store', provider: 'synthetic-quarantine-legacy-clear-binding-provider-v0', async put(payload, fields = {}) { const body = bytes(payload); const hash = await digestBytesHex(body); const digest = `sha256:${hash}`; records.set(digest, body); trace?.emit('synthetic-quarantine-legacy-clear-binding:put', { digest, bytes: body.byteLength, label: fields.label ?? null }); const ref = Object.freeze({ kind: 'block', id: `block:${digest}`, digest, hash, backend: this.provider, bytes: body.byteLength }); return Object.freeze({ ref, digest, hash, bytes: body.byteLength, duplicate: false, label: fields.label ?? null }); }, async get(ref) { const digest = typeof ref === 'string' ? ref : ref?.digest ?? ref?.ref?.digest; const row = records.get(digest); if (!row) throw new Error(`missing block ${digest}`); return new Uint8Array(row); }, async has(ref) { const digest = typeof ref === 'string' ? ref : ref?.digest ?? ref?.ref?.digest; return records.has(digest); }, async verify(ref) { const digest = typeof ref === 'string' ? ref : ref?.digest ?? ref?.ref?.digest; const row = records.get(digest); return Object.freeze({ ok: Boolean(row), present: Boolean(row), digest, bytes: row?.byteLength ?? 0 }); }, async delete(ref) { const digest = typeof ref === 'string' ? ref : ref?.digest ?? ref?.ref?.digest; return records.delete(digest); }, async estimate() { return Object.freeze({ quota: null, usage: [...records.values()].reduce((sum, row) => sum + row.byteLength, 0), usageDetails: { synthetic: records.size } }); }, async cleanupForTest() { const had = records.size > 0; records.clear(); return had; }, async waitForSettled({ timeoutMs = 1000 } = {}) { return Object.freeze({ ok: true, elapsedMs: 0, timeoutMs, last: { heldCount: 0, pendingCount: 0, available: true }, reason: 'synthetic-settled' }); }, snapshot() { return Object.freeze({ name: this.name, provider: this.provider, available: true, opened: true, blockCount: records.size }); } }; }
function mixedLedger() { return Object.freeze({ schema: 'brt.storageLane.timedOutOperationQuarantine.v1', exportedAtMs: Date.now(), label: `${REVISION}-legacy-clear-binding-ledger`, reason: 'legacy-clear-binding-import', lane: 'storage', counts: Object.freeze({ total: 2, unsettled: 0, successful: 1, failed: 1 }), unsettledTimedOutOperations: Object.freeze([]), successfulTimedOutOperations: Object.freeze([{ opId: 'legacy-clear-success', kind: 'put', lane: 'storage', timeoutMs: 250, timedOutAtMs: 1700000000000, settledAtMs: 1700000001000, result: { disposition: 'synthetic-late-success', digest: 'sha256:legacy-clear-success' } }]), failedTimedOutOperations: Object.freeze([{ opId: 'legacy-clear-failure', kind: 'put', lane: 'storage', timeoutMs: 250, timedOutAtMs: 1700000000100, settledAtMs: 1700000001100, error: { name: 'SyntheticLateFailure', message: 'synthetic late failure', code: 'BRT_SYNTHETIC_LATE_FAILURE', storageDisposition: 'BRT_SYNTHETIC_LATE_FAILURE' } }]) }); }

export async function runProbe() {
  const started = performance.now(); const trace = new TraceLog(); const store = makeStore({ trace });
  const adapter = createBlockStoreLaneAdapter({ label: `${REVISION}-legacy-clear-binding`, store, scheduler: makeScheduler(`${REVISION}-legacy-clear-binding-scheduler`, trace), trace, lane: 'storage', defaultOperationTimeoutMs: 1000 });
  const imported = adapter.importTimedOutOperationQuarantine(mixedLedger(), { lane: 'storage', reason: 'legacy-clear-binding-valid-import', markUnhealthy: false });
  const importedQuarantine = adapter.timedOutOperationQuarantine('storage');
  const rejectedWhileQuarantined = adapter.schedulePut(`${REVISION}:legacy-clear-binding-rejected`, { id: 'legacy-clear-binding-rejected-put', priority: 'user-visible' });
  const noFingerprintSuccess = adapter.clearSuccessfulTimedOutOperations({ lane: 'storage', opId: 'legacy-clear-success', reviewed: true, reviewToken: 'legacy-success-no-fingerprint', reason: 'legacy-success-clear-without-fingerprint' });
  const staleFingerprintSuccess = adapter.clearSuccessfulTimedOutOperations({ lane: 'storage', opId: 'legacy-clear-success', reviewed: true, reviewToken: 'legacy-success-stale-fingerprint', reviewFingerprint: 'brt-qfp-v1:0000000000000000', reason: 'legacy-success-clear-stale-fingerprint' });
  const noFingerprintFailure = adapter.clearFailedTimedOutOperations({ lane: 'storage', opId: 'legacy-clear-failure', reviewed: true, reviewToken: 'legacy-failure-no-fingerprint', reason: 'legacy-failure-clear-without-fingerprint' });
  const successReview = adapter.createTimedOutOperationQuarantineReview({ lane: 'storage', category: 'successful', opId: 'legacy-clear-success', reviewer: 'rev0078-release-probe', reviewToken: 'legacy-success-bound-review', reason: 'legacy-success-bound-review' });
  const clearSuccess = adapter.clearSuccessfulTimedOutOperations({ reviewManifest: successReview, requireReviewFingerprint: true, reason: 'legacy-success-bound-clear' });
  const blockedAfterSuccess = await adapter.recoverWhenStoreSettled({ timeoutMs: 200, intervalMs: 5, reason: 'legacy-clear-binding-blocked-after-success-only' });
  const failureReview = adapter.createTimedOutOperationQuarantineReview({ lane: 'storage', category: 'failed', opId: 'legacy-clear-failure', reviewer: 'rev0078-release-probe', reviewToken: 'legacy-failure-bound-review', reason: 'legacy-failure-bound-review' });
  const staleOldSuccessReviewOnFailure = adapter.clearFailedTimedOutOperations({ reviewManifest: successReview, reason: 'legacy-failure-clear-with-stale-success-review' });
  const clearFailure = adapter.clearFailedTimedOutOperations({ reviewManifest: failureReview, requireReviewFingerprint: true, reason: 'legacy-failure-bound-clear' });
  const recovered = await adapter.recoverWhenStoreSettled({ timeoutMs: 200, intervalMs: 5, reason: 'legacy-clear-binding-reviewed-cleared' });
  const accepted = adapter.schedulePut(`${REVISION}:legacy-clear-binding-recovered`, { id: 'legacy-clear-binding-recovered-put', priority: 'user-visible' });
  const drain = await adapter.drain({ maxSteps: 3 });
  const recoveredResult = drain.results.find((row) => row.opId === 'legacy-clear-binding-recovered-put') ?? null;
  const recoveredVerify = recoveredResult?.result?.ref ? await store.verify(recoveredResult.result.ref) : null;
  const finalQuarantine = adapter.timedOutOperationQuarantine('storage');
  const finalLane = adapter.snapshot().executor.scheduler.lanes.find((lane) => lane.id === 'storage');
  const traceKinds = trace.kinds();

  assert.equal(imported.ok, true); assert.equal(imported.markUnhealthyForced, true); assert.equal(imported.importedCount, 2); assert.equal(importedQuarantine.totalCount, 2);
  assert.equal(rejectedWhileQuarantined.accepted, false); assert.equal(rejectedWhileQuarantined.scheduler.noMutation, true);
  assert.equal(noFingerprintSuccess.ok, false); assert.equal(noFingerprintSuccess.code, 'late-success-clear-review-fingerprint-required');
  assert.equal(staleFingerprintSuccess.ok, false); assert.equal(staleFingerprintSuccess.code, 'late-success-clear-review-fingerprint-mismatch');
  assert.equal(noFingerprintFailure.ok, false); assert.equal(noFingerprintFailure.code, 'late-failure-clear-review-fingerprint-required');
  assert.equal(clearSuccess.ok, true); assert.equal(clearSuccess.clearedCount, 1); assert.equal(blockedAfterSuccess.recovered, false); assert.equal(blockedAfterSuccess.reason, 'timed-out-operation-late-failure');
  assert.equal(staleOldSuccessReviewOnFailure.ok, false); assert.equal(staleOldSuccessReviewOnFailure.code, 'late-failure-clear-review-fingerprint-mismatch');
  assert.equal(clearFailure.ok, true); assert.equal(clearFailure.clearedCount, 1); assert.equal(recovered.recovered, true); assert.equal(accepted.accepted, true); assert.equal(recoveredResult?.ok, true); assert.equal(recoveredVerify?.ok, true);
  assert.equal(finalQuarantine.totalCount, 0); assert.equal(finalLane.healthy, true);
  for (const kind of ['storage-lane:timed-out-quarantine-import-backpressure-forced','storage-lane:late-provider-success-clear-rejected','storage-lane:late-provider-failure-clear-rejected','storage-lane:late-provider-successes-cleared','storage-lane:late-provider-failures-cleared']) assert.ok(traceKinds.includes(kind), `missing trace kind ${kind}`);

  return { project: 'BrowserRT', revision: REVISION, version: VERSION, schema: 1, probe_id: `${REVISION}-storage-lane-quarantine-legacy-clear-binding-proof`, task_id: TASK_ID, status: 'passed', generatedAt: new Date().toISOString(), durationMs: Math.round(performance.now() - started), purpose: 'Release-light proof that legacy late-success/late-failure quarantine clear helpers require review-fingerprint-bound maintenance clearing and cannot bypass imported timeout-quarantine backpressure.', observations: { imported, importedQuarantine, rejectedWhileQuarantined, noFingerprintSuccess, staleFingerprintSuccess, noFingerprintFailure, successReview, clearSuccess, blockedAfterSuccess, failureReview, staleOldSuccessReviewOnFailure, clearFailure, recovered, accepted, recoveredResult, recoveredVerify, finalQuarantine, finalLane, traceKinds }, claimsChecked: ['legacy clear helpers reject missing/stale review fingerprints', 'review manifests bind clear to the current quarantine fingerprint', 'recovery remains blocked until both success and failure quarantine rows are bound-cleared'], nonClaims: ['No provider cancellation, rollback, OPFS durability, cross-browser, cryptographic attestation, or production readiness claim.'] };
}
const argv = process.argv.slice(2); const out = argValue(argv, '--json', DEFAULT_OUT);
try { const report = await runProbe(); if (out) { await mkdir(dirname(out), { recursive: true }); await writeFile(out, JSON.stringify(report, null, 2) + '\n'); console.log(out); } else console.log(JSON.stringify(report, null, 2)); }
catch (error) { const report = { project: 'BrowserRT', revision: REVISION, version: VERSION, schema: 1, probe_id: `${REVISION}-storage-lane-quarantine-legacy-clear-binding-proof`, task_id: TASK_ID, status: 'failed', generatedAt: new Date().toISOString(), error: { name: error?.name || 'Error', message: error?.message || String(error), stack: error?.stack }, nonClaims: ['Failed quarantine legacy-clear binding proof is not silently skipped.'] }; if (out) { await mkdir(dirname(out), { recursive: true }); await writeFile(out, JSON.stringify(report, null, 2) + '\n'); console.error(out); } console.error(`[storage_lane_quarantine_legacy_clear_binding_probe] FAIL: ${error?.stack || error}`); process.exitCode = 1; }
