#include "test_harness.hpp"

#include "iotox/agent_config.hpp"
#include "iotox/cli.hpp"
#include "iotox/cli_registry.hpp"
#include "iotox/route_inventory.hpp"
#include "iotox/rollback_witness_service.hpp"
#include "iotox/security/identity.hpp"
#include "iotox/security/sodium.hpp"
#include "iotox/state_store.hpp"
#include "iotox/sync_automation.hpp"
#include "iotox/sync_namespace.hpp"
#include "iotox/sync_transaction.hpp"
#include "iotox/terminal_profile.hpp"
#include "iotox/update_bundle.hpp"

#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string_view>
#include <sys/stat.h>
#include <unistd.h>
#include <vector>

namespace {

class CerrCapture {
  public:
    CerrCapture() : previous_(std::cerr.rdbuf(captured_.rdbuf())) {}
    ~CerrCapture() { std::cerr.rdbuf(previous_); }

    CerrCapture(const CerrCapture &) = delete;
    CerrCapture &operator=(const CerrCapture &) = delete;

  private:
    std::ostringstream captured_;
    std::streambuf *previous_;
};

class CoutCapture {
  public:
    CoutCapture() : previous_(std::cout.rdbuf(captured_.rdbuf())) {}
    ~CoutCapture() { std::cout.rdbuf(previous_); }

    CoutCapture(const CoutCapture &) = delete;
    CoutCapture &operator=(const CoutCapture &) = delete;

    [[nodiscard]] std::string text() const { return captured_.str(); }

  private:
    std::ostringstream captured_;
    std::streambuf *previous_;
};

class TemporaryDirectory {
  public:
    TemporaryDirectory() {
        std::string pattern = "/tmp/iotox-cli-route-set-XXXXXX";
        std::vector<char> bytes(pattern.begin(), pattern.end());
        bytes.push_back('\0');
        char *created = ::mkdtemp(bytes.data());
        if (created != nullptr) root_ = created;
    }
    ~TemporaryDirectory() {
        std::error_code ignored;
        std::filesystem::remove_all(root_, ignored);
    }
    [[nodiscard]] const std::filesystem::path &root() const { return root_; }

  private:
    std::filesystem::path root_;
};

IOTOX_TEST("CLI command registry freezes the complete stable surface") {
    const auto commands = iotox::cli_command_registry();
    IOTOX_CHECK(commands.size() == 222U);
    IOTOX_CHECK(std::ranges::is_sorted(
        commands, {}, &iotox::CliCommandDescriptor::name));
    for (std::size_t index = 0U; index < commands.size(); ++index) {
        const auto &command = commands[index];
        IOTOX_CHECK(!command.name.empty());
        IOTOX_CHECK(command.name.find_first_not_of(
                        "abcdefghijklmnopqrstuvwxyz0123456789-") ==
                    std::string_view::npos);
        IOTOX_CHECK(iotox::find_cli_command(command.name) == &command);
        if (index != 0U) {
            IOTOX_CHECK(commands[index - 1U].name != command.name);
        }
        if (!command.canonical_name.empty()) {
            IOTOX_CHECK(command.kind ==
                        iotox::CliCommandKind::compatibility);
            const auto *canonical =
                iotox::find_cli_command(command.canonical_name);
            IOTOX_CHECK(canonical != nullptr);
            IOTOX_CHECK(canonical->canonical_name.empty());
        }
    }
    IOTOX_CHECK(iotox::find_cli_command("not-an-iotox-command") == nullptr);
}

IOTOX_TEST("CLI help command index is generated from the registry") {
    CoutCapture output;
    const std::array<std::string_view, 2U> arguments{"help", "all"};
    IOTOX_CHECK(iotox::run_cli(arguments) == 0);
    const std::string help = output.text();
    IOTOX_CHECK(help.find(
                    "COMMAND INDEX (generated from the parser registry):\n") !=
                std::string::npos);
    for (const auto &command : iotox::cli_command_registry()) {
        IOTOX_CHECK(help.find("  " + std::string(command.name) + "  [") !=
                    std::string::npos);
    }
    IOTOX_CHECK(help.find(
                    "transport-peer-add  [compatibility] "
                    "alias-for=transport-peer-accept") != std::string::npos);
    IOTOX_CHECK(help.find(
                    "transport-peer-reject  [compatibility] "
                    "alias-for=request-reject") != std::string::npos);
}

IOTOX_TEST("CLI completion generators cover every registered command") {
    for (const std::string_view shell : {"bash", "zsh", "fish"}) {
        auto generated = iotox::generate_cli_completion(shell);
        IOTOX_CHECK_MSG(generated.ok(), generated.status().message());
        IOTOX_CHECK(generated.value().find(
                        "generated by iotox completion " +
                        std::string(shell)) != std::string::npos);
        for (const auto &command : iotox::cli_command_registry()) {
            IOTOX_CHECK(generated.value().find(command.name) !=
                        std::string::npos);
        }
    }
    auto invalid = iotox::generate_cli_completion("powershell");
    IOTOX_CHECK(!invalid.ok());
    IOTOX_CHECK(invalid.status().code() == iotox::ErrorCode::invalid_argument);
}

IOTOX_TEST("CLI completion command emits one selected shell grammar") {
    {
        CoutCapture output;
        const std::array<std::string_view, 2U> arguments{"completion", "bash"};
        IOTOX_CHECK(iotox::run_cli(arguments) == 0);
        IOTOX_CHECK(output.text().starts_with(
            "# generated by iotox completion bash\n"));
        IOTOX_CHECK(output.text().find(
                        "complete -F _iotox_complete iotox\n") !=
                    std::string::npos);
    }
    CerrCapture errors;
    const std::array<std::string_view, 2U> invalid{
        "completion", "powershell"};
    IOTOX_CHECK(iotox::run_cli(invalid) == 2);
}

}  // namespace

IOTOX_TEST("CLI rejects malformed laboratory and resource limits before startup") {
    const std::string terminal_peer(64U, '1');
    const std::string terminal_session(32U, '2');
    const std::vector<std::vector<std::string_view>> invalid_arguments{
        {"run", "--max-authority-records", "0"},
        {"run", "--max-command-records", "0"},
        {"run", "--max-command-store-bytes", "0"},
        {"run", "--max-pending-command-records", "0"},
        {"run", "--max-pending-commands-per-peer", "0"},
        {"run", "--max-command-bytes-per-peer", "0"},
        {"run", "--clock-rollback-tolerance-ms", "invalid"},
        {"run", "--require-state-protection", "fscrypt-v2"},
        {"run", "--require-state-protection", "unknown",
         "--protected-state-root", "/tmp/iotox-state"},
        {"run", "--protected-state-root", "/tmp/iotox-state"},
        {"run", "--protected-state-policy-id",
         "00000000000000000000000000000000"},
        {"run", "--require-state-protection", "fscrypt-v2",
         "--protected-state-root", "/tmp/iotox-state",
         "--protected-state-policy-id", "not-hex"},
        {"run", "--route-generation-state", "/tmp/routes.generation"},
        {"run", "--enable-route-workers"},
        {"run", "--enable-private-route-bindings"},
        {"run", "--route-worker-root", "/tmp/routes"},
        {"run", "--enable-route-workers", "--route-set", "/tmp/routes.signed"},
        {"run", "--route-worker-network", "not-a-spec"},
        {"run", "--route-worker-network",
         "1111111111111111111111111111111111111111111111111111111111111111=tox/"
         "native"},
        {"run", "--route-worker-network",
         "1111111111111111111111111111111111111111111111111111111111111111=tox/"
         "tor"},
        {"run", "--route-worker-network",
         "1111111111111111111111111111111111111111111111111111111111111111=tox/"
         "tor@localhost:9050"},
        {"run", "--route-worker-bootstrap", "not-a-spec"},
        {"run", "--route-worker-tcp-relay",
         "1111111111111111111111111111111111111111111111111111111111111111="
         "invalid"},
        {"run", "--route-worker-bootstrap",
         "1111111111111111111111111111111111111111111111111111111111111111=192."
         "0."
         "2.10:33445:"
         "2222222222222222222222222222222222222222222222222222222222222222"},
        {"run", "--enable-route-workers", "--route-set", "/tmp/routes.signed",
         "--route-worker-root", "/tmp/route-workers", "--route-worker-network",
         "1111111111111111111111111111111111111111111111111111111111111111=tox/"
         "tor@127.0.0.1:9050",
         "--route-worker-bootstrap",
         "1111111111111111111111111111111111111111111111111111111111111111="
         "bootstrap.example:33445:"
         "2222222222222222222222222222222222222222222222222222222222222222",
         "--route-worker-tcp-relay",
         "1111111111111111111111111111111111111111111111111111111111111111=192."
         "0."
         "2.10:33445:"
         "2222222222222222222222222222222222222222222222222222222222222222"},
        {"run", "--enable-route-workers", "--route-set", "/tmp/routes.signed",
         "--route-worker-root", "/tmp/route-workers", "--route-worker-network",
         "1111111111111111111111111111111111111111111111111111111111111111=tox/"
         "native",
         "--route-worker-bootstrap",
         "1111111111111111111111111111111111111111111111111111111111111111=192."
         "0."
         "2.10:33445:"
         "2222222222222222222222222222222222222222222222222222222222222222",
         "--route-worker-bootstrap",
         "1111111111111111111111111111111111111111111111111111111111111111=192."
         "0."
         "2.10:33445:"
         "2222222222222222222222222222222222222222222222222222222222222222"},
        {"run", "--enable-route-workers", "--route-set", "/tmp/routes.signed",
         "--route-worker-root", "/tmp/route-workers", "--route-worker-network",
         "1111111111111111111111111111111111111111111111111111111111111111=tox/"
         "native",
         "--route-worker-network",
         "1111111111111111111111111111111111111111111111111111111111111111=tox/"
         "native"},
        {"run", "--enable-sync"},
        {"run", "--sync-policy-root", "/tmp/sync"},
        {"run", "--enable-signed-updates"},
        {"run", "--update-policy", "/tmp/update.policy"},
        {"run", "--enable-signed-updates", "--update-policy",
         "/tmp/update.policy"},
        {"run", "--max-sync-publisher-replays", "0"},
        {"run", "--max-sync-publisher-replays", "65537"},
        {"run", "--max-sync-subscriber-jobs", "0"},
        {"run", "--max-sync-subscriber-jobs", "1025"},
        {"run", "--max-sync-worker-queue", "0"},
        {"run", "--max-sync-worker-queue", "4097"},
        {"run", "--max-sync-content-lanes", "0"},
        {"run", "--max-sync-content-lanes", "65"},
        {"run", "--sync-route-policy", "unknown"},
        {"run", "--sync-route-policy", "adaptive"},
        {"run", "--sync-route-failover", "unknown"},
        {"run", "--sync-route-failover", "fail-closed"},
        {"run", "--qualify-route-stop-after-bytes", "0"},
        {"run", "--qualify-route-stop-after-bytes", "1"},
        {"run", "--qualify-route-stop-count", "0"},
        {"run", "--qualify-route-stop-count", "1"},
        {"run", "--qualify-route-stop-count", "4"},
        {"run", "--qualify-route-stop-file-bytes", "0"},
        {"run", "--qualify-route-stop-file-bytes", "2"},
        {"run", "--qualify-route-stop-worker", "not-a-public-key"},
        {"run", "--qualify-route-stop-worker",
         std::string_view("1111111111111111111111111111111111111111111111111111"
                          "111111111111")},
        {"run", "--enable-sync", "--sync-policy-root", "/tmp/sync",
         "--enable-route-workers", "--route-set", "/tmp/routes.signed",
         "--route-worker-root", "/tmp/route-workers",
         "--qualify-route-stop-after-bytes", "2",
         "--qualify-route-stop-file-bytes", "2"},
        {"run", "--qualify-route-fault-delay-ms", "0"},
        {"run", "--qualify-route-fault-delay-ms", "1"},
        {"run", "--qualify-route-fault-delay-ms", "60001"},
        {"run", "--qualify-route-stop-after-cancel"},
        {"run", "--enable-sync", "--sync-policy-root", "/tmp/sync",
         "--enable-route-workers", "--route-set", "/tmp/routes.signed",
         "--route-worker-root", "/tmp/route-workers",
         "--qualify-route-stop-after-bytes", "1",
         "--qualify-route-stop-after-cancel"},
        {"run", "--qualify-route-first-worker",
         std::string_view("1111111111111111111111111111111111111111111111111111"
                          "111111111111")},
        {"run", "--qualify-route-first-worker",
         std::string_view("0000000000000000000000000000000000000000000000000000"
                          "000000000000")},
        {"run", "--qualify-route-first-worker", "not-a-public-key"},
        {"run", "--qualify-route-other-delay-ms", "0"},
        {"run", "--qualify-route-other-delay-ms", "1"},
        {"run", "--qualify-route-other-delay-ms", "60001"},
        {"run", "--network", "unknown"},
        {"run", "--network", "tox/tor"},
        {"run", "--network", "tox/i2p"},
        {"run", "--network", "tox/i2p-construction"},
        {"run", "--network", "tox/i2p-construction", "--socks5-proxy",
         "127.0.0.1:7656"},
        {"run", "--network", "tox/tor", "--socks5-proxy", "localhost:9050"},
        {"run", "--network", "tox/tor", "--socks5-proxy", "127.0.0.1:9050"},
        {"run", "--network", "tox/tor", "--socks5-proxy", "127.0.0.1:9050",
         "--tcp-relay",
         "relay.example:33445:"
         "1111111111111111111111111111111111111111111111111111111111111111"},
        {"run", "--network", "tox/tor", "--socks5-proxy", "127.0.0.1:9050",
         "--socks5-proxy", "127.0.0.1:9051", "--tcp-relay",
         "192.0.2.1:33445:"
         "1111111111111111111111111111111111111111111111111111111111111111"},
        {"run", "--network", "tox/tor", "--socks5-proxy", "127.0.0.1:9050",
         "--bootstrap",
         "bootstrap.example:33445:"
         "1111111111111111111111111111111111111111111111111111111111111111",
         "--tcp-relay",
         "192.0.2.1:33445:"
         "1111111111111111111111111111111111111111111111111111111111111111"},
        {"run", "--network", "tox/native", "--socks5-proxy", "127.0.0.1:9050"},
        {"run", "--bootstrap", "invalid"},
        {"run", "--tcp-relay", "invalid"},
        {"run", "--bootstrap-retry-ms", "0"},
        {"run", "--owner-command-timeout-ms", "0"},
        {"run", "--max-iterate-ms", "0"},
        {"run", "--max-iterate-ms", "1001"},
        {"run", "--ratox-active-service-ms", "0"},
        {"run", "--ratox-active-service-ms", "21"},
        {"run", "--ratox-active-iterate-ms", "0"},
        {"run", "--ratox-active-iterate-ms", "1001"},
        {"run", "--max-pending-commands", "0"},
        {"run", "--max-pending-events", "0"},
        {"run", "--file-pacing-high-events", "0"},
        {"run", "--file-pacing-low-events", "1048577"},
        {"run", "--file-pacing-hold-us", "99"},
        {"run", "--file-pacing-hold-us", "1000001"},
        {"run", "--file-pacing-resume-batch", "0"},
        {"run", "--file-pacing-resume-batch", "1025"},
        {"run", "--max-file-bytes", "0"},
        {"run", "--max-active-sends", "0"},
        {"run", "--max-active-receives", "257"},
        {"run", "--file-carrier-window", "0"},
        {"run", "--file-carrier-window", "257"},
        {"run", "--file-carrier-quantum-ms", "4"},
        {"run", "--file-carrier-quantum-ms", "1001"},
        {"run", "--max-active-receives", "1", "--file-carrier-window", "2"},
        {"run", "--max-pending-file-offers", "65537"},
        {"run", "--ratox-cgroup-pids-max", "0"},
        {"run", "--ratox-cgroup-pids-max", "4"},
        {"run", "--ratox-cgroup-memory-high-bytes", "0"},
        {"run", "--ratox-cgroup-memory-high-bytes", "1"},
        {"run", "--ratox-cgroup-memory-max-bytes", "0"},
        {"run", "--ratox-cgroup-memory-max-bytes", "1"},
        {"run", "--ratox-cgroup-swap-max-bytes", "invalid"},
        {"run", "--ratox-cgroup-swap-max-bytes", "1"},
        {"run", "--ratox-cgroup-cpu-quota-us", "0"},
        {"run", "--ratox-cgroup-cpu-period-us", "0"},
        {"run", "--ratox-cgroup-cpu-period-us", "100000"},
        {"run", "--ratox-cgroup-cpu-quota-us", "999"},
        {"run", "--ratox-cgroup-cpu-quota-us", "1000",
         "--ratox-cgroup-cpu-period-us", "1000001"},
        {"run", "--ratox-cgroup-io-device", "8:16"},
        {"run", "--ratox-cgroup-io-rbps", "1"},
        {"run", "--ratox-cgroup-io-device", "0:0", "--ratox-cgroup-io-rbps",
         "1"},
        {"run", "--ratox-cgroup-io-device", "08:16", "--ratox-cgroup-io-rbps",
         "1"},
        {"run", "--ratox-cgroup-io-device", "8:16:1", "--ratox-cgroup-io-rbps",
         "1"},
        {"run", "--ratox-cgroup-io-device", "4294967296:16",
         "--ratox-cgroup-io-rbps", "1"},
        {"run", "--ratox-cgroup-io-device", "8:16", "--ratox-cgroup-io-rbps",
         "0"},
        {"run", "--ratox-cgroup-io-device", "8:16", "--ratox-cgroup-io-wbps",
         "9223372036854775808"},
        {"run", "--ratox-cgroup-io-device", "8:16", "--ratox-cgroup-io-riops",
         "invalid"},
        {"run", "--ratox-cgroup-io-device", "8:16", "--ratox-cgroup-io-wiops",
         "1"},
        {"run", "--ratox-cgroup-aggregate-pids-max", "0"},
        {"run", "--ratox-cgroup-aggregate-pids-max", "4"},
        {"run", "--ratox-cgroup-aggregate-memory-max-bytes", "0"},
        {"run", "--ratox-cgroup-aggregate-memory-max-bytes", "1"},
        {"run", "--ratox-cgroup-aggregate-swap-max-bytes", "invalid"},
        {"run", "--ratox-cgroup-aggregate-swap-max-bytes", "1"},
        {"run", "--ratox-cgroup-aggregate-cpu-quota-us", "0"},
        {"run", "--ratox-cgroup-aggregate-cpu-period-us", "0"},
        {"run", "--ratox-cgroup-aggregate-cpu-period-us", "100000"},
        {"run", "--ratox-cgroup-aggregate-cpu-quota-us", "999"},
        {"run", "--ratox-cgroup-aggregate-cpu-quota-us", "1000",
         "--ratox-cgroup-aggregate-cpu-period-us", "1000001"},
        {"run", "--ratox-cgroup-aggregate-cpu-quota-us", "100000"},
        {"run", "--ratox-cgroup-admission-cpu-some-avg10-bp", "10001"},
        {"run", "--ratox-cgroup-admission-memory-full-avg10-bp", "invalid"},
        {"run", "--ratox-cgroup-admission-io-full-avg10-bp", "10001"},
        {"run", "--ratox-cgroup-admission-hysteresis-bp", "1"},
        {"run", "--ratox-cgroup-admission-cpu-some-avg10-bp", "50",
         "--ratox-cgroup-admission-hysteresis-bp", "51", "--ratox-cgroup-root",
         "/sys/fs/cgroup/iotox"},
        {"run", "--ratox-cgroup-admission-cpu-some-avg10-bp", "50"},
        {"run", "--ratox-cgroup-admission-trigger-window-us", "invalid"},
        {"run", "--ratox-cgroup-admission-trigger-window-us", "2000000"},
        {"run", "--ratox-cgroup-admission-cpu-some-trigger-stall-us", "1"},
        {"run", "--ratox-cgroup-admission-cpu-some-avg10-bp", "50",
         "--ratox-cgroup-admission-trigger-window-us", "1999999",
         "--ratox-cgroup-admission-cpu-some-trigger-stall-us", "1",
         "--ratox-cgroup-root", "/sys/fs/cgroup/iotox"},
        {"run", "--ratox-cgroup-admission-cpu-some-avg10-bp", "50",
         "--ratox-cgroup-admission-trigger-window-us", "2500000",
         "--ratox-cgroup-admission-cpu-some-trigger-stall-us", "1",
         "--ratox-cgroup-root", "/sys/fs/cgroup/iotox"},
        {"run", "--ratox-cgroup-admission-cpu-some-avg10-bp", "50",
         "--ratox-cgroup-admission-trigger-window-us", "10000001",
         "--ratox-cgroup-admission-cpu-some-trigger-stall-us", "1",
         "--ratox-cgroup-root", "/sys/fs/cgroup/iotox"},
        {"run", "--ratox-cgroup-admission-cpu-some-avg10-bp", "50",
         "--ratox-cgroup-admission-trigger-window-us", "2000000",
         "--ratox-cgroup-admission-cpu-some-trigger-stall-us", "0",
         "--ratox-cgroup-root", "/sys/fs/cgroup/iotox"},
        {"run", "--ratox-cgroup-admission-cpu-some-avg10-bp", "50",
         "--ratox-cgroup-admission-trigger-window-us", "2000000",
         "--ratox-cgroup-admission-cpu-some-trigger-stall-us", "2000001",
         "--ratox-cgroup-root", "/sys/fs/cgroup/iotox"},
        {"run", "--ratox-cgroup-admission-cpu-some-avg10-bp", "50",
         "--ratox-cgroup-admission-trigger-window-us", "2000000",
         "--ratox-cgroup-admission-memory-full-trigger-stall-us", "1",
         "--ratox-cgroup-root", "/sys/fs/cgroup/iotox"},
        {"run", "--ratox-cgroup-admission-cpu-some-avg10-bp", "50",
         "--ratox-cgroup-admission-trigger-window-us", "2000000",
         "--ratox-cgroup-admission-cpu-some-trigger-stall-us", "1"},
        {"run", "--run-ms", "18446744073709551615"},
        {"run", "--unknown-option", "value"},
        {"run", "--library"},
        {"update-policy-template", "system-image", "iotox-test-x86_64", "/tmp",
         "--signer-policy-epoch", "1", "--signer-policy-epoch", "2"},
        {"update-policy-template", "system-image", "iotox-test-x86_64", "/tmp",
         "--payload-kind", "unknown"},
        {"update-policy-template", "system-image", "iotox-test-x86_64", "/tmp",
         "--payload-kind"},
        {"run", "--enable-update-linux-service"},
        {"run", "--witness-sync-guarded-state"},
        {"run", "--update-service-helper", "/tmp/iotox"},
        {"update-gc"},
        {"update-gc", "purge"},
        {"command", "0", "update.stage"},
        {"command", "0", "update.stage", "00"},
        {"command", "0", "update.stage",
         "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"},
        {"host-capabilities", "--allow-sudo"},
        {"terminal-shell-discover", "--allow-sudo"},
        {"terminal-profile-template", "maintenance", "--shell", "/bin/sh"},
        {"terminal-profile-shell-template", "owner", "--toolbox-dir", "/tmp"},
        {"terminal-profile-toolbox-template", "rescue", "--shell", "/bin/sh"},
        {"terminal-profile-toolbox-template", "rescue", "--toolbox-dir", "/tmp"},
        {"--reconnect", "terminal-resume", terminal_session, terminal_peer},
        {"--reconnect", "--batch", "terminal", terminal_peer},
        {"--reconnect", "--reconnect", "terminal", terminal_peer},
    };

    CerrCapture capture;
    for (const auto &arguments : invalid_arguments) {
        IOTOX_CHECK(iotox::run_cli(arguments) == 2);
    }
}

IOTOX_TEST("CLI lints config and preflights merged overrides without mutation") {
    const char *mock_toxcore = std::getenv("IOTOX_TEST_MOCK_TOXCORE");
    IOTOX_CHECK(mock_toxcore != nullptr);
    TemporaryDirectory directory;
    const std::filesystem::path config_path = directory.root() / "agent.conf";
    const std::filesystem::path configured_runtime = directory.root() / "old-run";
    const std::filesystem::path override_runtime = directory.root() / "new-run";
    const std::filesystem::path state = directory.root() / "state" / "device.toxsave";
    const std::filesystem::path sync_root = directory.root() / "new-sync";
    iotox::AgentConfigRecord record;
    record.arguments = {
        "--library", mock_toxcore,
        "--runtime", configured_runtime.string(),
        "--state", state.string(),
        "--no-default-bootstrap",
        "--no-default-relays",
        "--enable-sync",
        "--sync-policy-root", sync_root.string(),
    };
    auto encoded = iotox::encode_agent_config_record(record);
    IOTOX_CHECK(encoded.ok());
    {
        std::ofstream output(config_path, std::ios::binary | std::ios::trunc);
        output.write(
            reinterpret_cast<const char *>(encoded.value().data()),
            static_cast<std::streamsize>(encoded.value().size()));
        output.close();
        IOTOX_CHECK(output.good());
    }
    IOTOX_CHECK(::chmod(config_path.c_str(), 0600) == 0);

    {
        CoutCapture output;
        const std::array<std::string, 2U> owned{
            "config-lint", config_path.string()};
        const std::array<std::string_view, 2U> command{owned[0], owned[1]};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find("decision=valid\n") !=
                    std::string::npos);
    }
    {
        CoutCapture output;
        const std::array<std::string, 5U> owned{
            "run-check", "--config", config_path.string(), "--runtime",
            override_runtime.string()};
        const std::array<std::string_view, 5U> command{
            owned[0], owned[1], owned[2], owned[3], owned[4]};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find("iotox-run-check-v1\n") == 0U);
        IOTOX_CHECK(output.text().find("source=config+overrides\n") !=
                    std::string::npos);
        IOTOX_CHECK(output.text().find("protected-state=disabled\n") !=
                    std::string::npos);
        IOTOX_CHECK(output.text().find(
                        "synchronization=empty-policy-store-will-create\n") !=
                    std::string::npos);
        IOTOX_CHECK(output.text().find("mutation=none\n") !=
                    std::string::npos);
    }
    IOTOX_CHECK(!std::filesystem::exists(configured_runtime));
    IOTOX_CHECK(!std::filesystem::exists(override_runtime));
    IOTOX_CHECK(!std::filesystem::exists(state));
    IOTOX_CHECK(!std::filesystem::exists(sync_root));
}

IOTOX_TEST("CLI discovers and freezes a non-root owner login shell profile") {
    if (::geteuid() == 0) return;
    {
        CerrCapture error_output;
        const std::array<std::string_view, 3U> command{
            "--shell", "/iotox-missing-explicit-shell",
            "terminal-shell-discover"};
        IOTOX_CHECK(iotox::run_cli(command) == 4);
    }
    std::error_code error;
    const std::filesystem::path explicit_executable =
        std::filesystem::canonical("/proc/self/exe", error);
    IOTOX_CHECK(!error);
    const std::string executable = explicit_executable.string();
    {
        CoutCapture output;
        const std::array<std::string_view, 3U> command{
            "--shell", executable, "terminal-shell-discover"};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find(
                        "selected=" + executable + " source=explicit\n") !=
                    std::string::npos);
        IOTOX_CHECK(output.text().find("policy=not-probed\n") !=
                    std::string::npos);
    }

    std::string profile_text;
    {
        CoutCapture output;
        const std::array<std::string_view, 4U> command{
            "--shell", executable,
            "terminal-profile-shell-template", "owner-shell"};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        profile_text = output.text();
    }
    const std::vector<std::uint8_t> bytes(
        profile_text.begin(), profile_text.end());
    auto profile = iotox::terminal::decode_profile_record(bytes);
    IOTOX_CHECK_MSG(profile.ok(), profile.status().message());
    IOTOX_CHECK(profile.value().id == "owner-shell");
    IOTOX_CHECK(!profile.value().enabled);
    IOTOX_CHECK(profile.value().arguments ==
                std::vector<std::string>({executable}));
    IOTOX_CHECK(profile.value().identity.mode ==
                iotox::terminal::IdentityMode::account);
    IOTOX_CHECK(profile.value().identity.uid ==
                static_cast<std::uint32_t>(::geteuid()));
    IOTOX_CHECK(profile.value().identity.gid ==
                static_cast<std::uint32_t>(::getegid()));
    IOTOX_CHECK(!profile.value().identity.clear_supplementary_groups);
    IOTOX_CHECK(!profile.value().allow_privilege_escalation);
    IOTOX_CHECK(profile.value().confinement ==
                iotox::terminal::ConfinementMode::baseline);
    IOTOX_CHECK(profile_text.find("/run/sandwurm") == std::string::npos);

    const int group_count = ::getgroups(0, nullptr);
    IOTOX_CHECK(group_count >= 0);
    std::vector<gid_t> native_groups(static_cast<std::size_t>(group_count));
    IOTOX_CHECK(group_count == 0 ||
                ::getgroups(group_count, native_groups.data()) == group_count);
    std::vector<std::uint32_t> expected_groups;
    expected_groups.reserve(native_groups.size());
    for (const gid_t group : native_groups) {
        if (group != ::getegid()) {
            expected_groups.push_back(static_cast<std::uint32_t>(group));
        }
    }
    std::sort(expected_groups.begin(), expected_groups.end());
    IOTOX_CHECK(profile.value().identity.supplementary_groups ==
                expected_groups);
}

IOTOX_TEST("CLI qualifies and freezes an explicit rescue toolbox profile") {
    if (::geteuid() == 0) return;
    std::error_code error;
    const std::filesystem::path explicit_executable =
        std::filesystem::canonical("/proc/self/exe", error);
    IOTOX_CHECK(!error);
    TemporaryDirectory temporary;
    const auto toolbox = temporary.root() / "toolbox";
    std::filesystem::create_directory(toolbox, error);
    IOTOX_CHECK(!error);
    IOTOX_CHECK(::chmod(toolbox.c_str(), static_cast<mode_t>(0700)) == 0);
    std::filesystem::copy_file(
        explicit_executable, toolbox / "toybox", error);
    IOTOX_CHECK(!error);
    IOTOX_CHECK(::chmod(
                    (toolbox / "toybox").c_str(),
                    static_cast<mode_t>(0500)) == 0);

    const std::string executable = explicit_executable.string();
    const std::string toolbox_text = toolbox.string();
    {
        CoutCapture output;
        const std::array<std::string_view, 5U> command{
            "--shell", executable, "--toolbox-dir", toolbox_text,
            "terminal-shell-discover"};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find(
                        "toolbox-dir=" + toolbox_text +
                        " multicall=" + toolbox_text + "/toybox\n") !=
                    std::string::npos);
    }

    std::string profile_text;
    {
        CoutCapture output;
        const std::array<std::string_view, 6U> command{
            "--shell", executable, "--toolbox-dir", toolbox_text,
            "terminal-profile-toolbox-template", "rescue"};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        profile_text = output.text();
    }
    const std::vector<std::uint8_t> bytes(
        profile_text.begin(), profile_text.end());
    auto profile = iotox::terminal::decode_profile_record(bytes);
    IOTOX_CHECK_MSG(profile.ok(), profile.status().message());
    IOTOX_CHECK(profile.value().id == "rescue");
    IOTOX_CHECK(!profile.value().enabled);
    IOTOX_CHECK(profile.value().arguments ==
                std::vector<std::string>({executable, "-i"}));
    IOTOX_CHECK(profile.value().confinement ==
                iotox::terminal::ConfinementMode::baseline);
    IOTOX_CHECK(!profile.value().allow_privilege_escalation);
    IOTOX_CHECK(profile.value().executable_sha256.has_value());
    IOTOX_CHECK(profile.value().toolbox_sha256.has_value());
    const auto environment_value = [&](std::string_view name) {
        const auto found = std::find_if(
            profile.value().environment.begin(),
            profile.value().environment.end(),
            [&](const iotox::terminal::EnvironmentEntry &entry) {
                return entry.name == name;
            });
        return found == profile.value().environment.end()
            ? std::string{}
            : found->value;
    };
    IOTOX_CHECK(environment_value("ENV").empty());
    IOTOX_CHECK(environment_value("HISTFILE") == "/dev/null");
    IOTOX_CHECK(environment_value("IOTOX_RESCUE_TOOLBOX") == toolbox_text);
    IOTOX_CHECK(environment_value("PS1") == "iotox-rescue$ ");
    IOTOX_CHECK(environment_value("PATH").starts_with(toolbox_text + ":"));

    IOTOX_CHECK(::chmod(temporary.root().c_str(), static_cast<mode_t>(0777)) == 0);
    {
        CerrCapture output;
        const std::array<std::string_view, 6U> command{
            "--shell", executable, "--toolbox-dir", toolbox_text,
            "terminal-profile-toolbox-template", "unsafe-parent"};
        IOTOX_CHECK(iotox::run_cli(command) == 4);
    }
    IOTOX_CHECK(::chmod(temporary.root().c_str(), static_cast<mode_t>(0700)) == 0);
    IOTOX_CHECK(::chmod(toolbox.c_str(), static_cast<mode_t>(0770)) == 0);
    {
        CerrCapture output;
        const std::array<std::string_view, 6U> command{
            "--shell", executable, "--toolbox-dir", toolbox_text,
            "terminal-profile-toolbox-template", "rejected"};
        IOTOX_CHECK(iotox::run_cli(command) == 4);
    }
}

IOTOX_TEST("CLI authors and strictly rereads the canonical terminal profile store") {
    TemporaryDirectory temporary;
    const auto store = temporary.root() / "ratox-profiles";
    const auto profiles = store / "profiles";
    const auto bindings = store / "bindings";
    IOTOX_CHECK(std::filesystem::create_directories(profiles));
    IOTOX_CHECK(std::filesystem::create_directories(bindings));
    IOTOX_CHECK(::chmod(store.c_str(), static_cast<mode_t>(0700)) == 0);
    IOTOX_CHECK(::chmod(profiles.c_str(), static_cast<mode_t>(0700)) == 0);
    IOTOX_CHECK(::chmod(bindings.c_str(), static_cast<mode_t>(0700)) == 0);

    std::string profile_text;
    {
        CoutCapture output;
        const std::array<std::string_view, 2U> command{
            "terminal-profile-template", "maintenance"};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        profile_text = output.text();
    }
    IOTOX_CHECK(profile_text.starts_with("iotox-terminal-profile-v7\n"));
    IOTOX_CHECK(profile_text.find("id=maintenance\n") != std::string::npos);
    IOTOX_CHECK(profile_text.find("enabled=0\n") != std::string::npos);
    const auto source = temporary.root() / "maintenance.profile";
    const std::vector<std::uint8_t> profile_bytes(
        profile_text.begin(), profile_text.end());
    IOTOX_CHECK(iotox::StateStore::write_atomic(source, profile_bytes).ok());

    {
        CoutCapture output;
        const std::string source_text = source.string();
        const std::array<std::string_view, 2U> command{
            "terminal-profile-lint", source_text};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find("valid=1 id=maintenance") !=
                    std::string::npos);
    }
    const std::string store_text = store.string();
    const std::string source_text = source.string();
    {
        CoutCapture output;
        const std::array<std::string_view, 4U> command{
            "--ratox-profile-store", store_text,
            "terminal-profile-install", source_text};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text() == "installed=maintenance\n");
    }
    {
        CoutCapture output;
        const std::array<std::string_view, 3U> command{
            "--ratox-profile-store", store_text,
            "terminal-profile-list"};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text() ==
                    "id=maintenance enabled=0 bindings=0\n");
    }
    {
        CoutCapture output;
        const std::array<std::string_view, 4U> command{
            "--ratox-profile-store", store_text,
            "terminal-profile-show", "maintenance"};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text() == profile_text);
    }

    const std::string principal(64U, '1');
    {
        CoutCapture output;
        const std::array<std::string_view, 5U> command{
            "--ratox-profile-store", store_text,
            "terminal-profile-bind", principal, "maintenance"};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find(" profile=maintenance\n") !=
                    std::string::npos);
    }
    {
        CerrCapture error;
        const std::array<std::string_view, 4U> command{
            "--ratox-profile-store", store_text,
            "terminal-profile-remove", "maintenance"};
        IOTOX_CHECK(iotox::run_cli(command) == 4);
    }
    {
        CoutCapture output;
        const std::array<std::string_view, 4U> command{
            "--ratox-profile-store", store_text,
            "terminal-profile-unbind", principal};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text() == "unbound=" + principal + "\n");
    }
    {
        CoutCapture output;
        const std::array<std::string_view, 4U> command{
            "--ratox-profile-store", store_text,
            "terminal-profile-remove", "maintenance"};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text() == "removed=maintenance\n");
    }
}

IOTOX_TEST("CLI reports live host terminal confinement capabilities") {
    CoutCapture output;
    const std::array<std::string_view, 1U> command{"host-capabilities"};
    IOTOX_CHECK(iotox::run_cli(command) == 0);
    const std::string report = output.text();
    IOTOX_CHECK(report.find("pidfd=") != std::string::npos);
    IOTOX_CHECK(report.find("seccomp=") != std::string::npos);
    IOTOX_CHECK(report.find("mdwe=") != std::string::npos);
    IOTOX_CHECK(report.find("landlock-abi=") != std::string::npos);
    IOTOX_CHECK(report.find("privilege-escalation-prerequisite=") !=
                std::string::npos);
    IOTOX_CHECK(report.find("sudo-path=") != std::string::npos);
    IOTOX_CHECK(report.find("sudo-policy=not-probed\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("cgroup-v2=") != std::string::npos);
}

IOTOX_TEST("CLI creates and inspects one canonical signed update bundle") {
    TemporaryDirectory temporary;
    IOTOX_CHECK(!temporary.root().empty());
    IOTOX_CHECK(::chmod(temporary.root().c_str(), 0700) == 0);
    const auto update_root = temporary.root() / "update-root";
    IOTOX_CHECK(std::filesystem::create_directory(update_root));
    IOTOX_CHECK(::chmod(update_root.c_str(), 0700) == 0);

    auto sodium = iotox::security::Sodium::load();
    IOTOX_CHECK_MSG(sodium.ok(), sodium.status().message());
    const auto identity_path = temporary.root() / "release.identity";
    std::string generated_signer_text;
    {
        CoutCapture output;
        const std::string identity_native = identity_path.string();
        const std::vector<std::string_view> command{
            "update-signer-keygen", identity_native};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        generated_signer_text = output.text();
    }
    IOTOX_CHECK(generated_signer_text.find(" public-key=") !=
                std::string::npos);
    IOTOX_CHECK(generated_signer_text.find(
                    " format=iotox-ed25519-identity-v1 created=1\n") !=
                std::string::npos);
    auto signer = iotox::security::DeviceIdentity::load_release(
        identity_path, sodium.value());
    IOTOX_CHECK_MSG(signer.ok(), signer.status().message());
    IOTOX_CHECK(generated_signer_text.find(
                    signer.value().public_key_hex()) != std::string::npos);
    {
        CoutCapture output;
        const std::string identity_native = identity_path.string();
        const std::vector<std::string_view> command{
            "update-signer-show", identity_native};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find(
                        signer.value().public_key_hex()) !=
                    std::string::npos);
        IOTOX_CHECK(output.text().find(" valid=1\n") !=
                    std::string::npos);
    }
    {
        CerrCapture error;
        const std::string identity_native = identity_path.string();
        const std::vector<std::string_view> command{
            "update-signer-keygen", identity_native};
        IOTOX_CHECK(iotox::run_cli(command) == 3);
    }
    auto retired_signer =
        iotox::security::DeviceIdentity::create_new_release(
            temporary.root() / "retired-release.identity", sodium.value());
    IOTOX_CHECK_MSG(retired_signer.ok(), retired_signer.status().message());
    const std::string signer_hex =
        iotox::security::hex(signer.value().public_key());
    const std::string retired_signer_hex =
        iotox::security::hex(retired_signer.value().public_key());

    std::string policy_text;
    {
        CoutCapture output;
        const std::string root_text = update_root.string();
        const std::vector<std::string_view> command{
            "update-policy-template", "system-image", "iotox-test-x86_64",
            root_text, signer_hex};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        policy_text = output.text();
    }
    const std::vector<std::uint8_t> policy_bytes(
        policy_text.begin(), policy_text.end());
    auto decoded_policy = iotox::update::decode_update_policy(policy_bytes);
    IOTOX_CHECK_MSG(decoded_policy.ok(), decoded_policy.status().message());
    IOTOX_CHECK(decoded_policy.value().namespace_id == "system-image");
    IOTOX_CHECK(decoded_policy.value().target == "iotox-test-x86_64");
    IOTOX_CHECK(decoded_policy.value().root == update_root);
    IOTOX_CHECK(decoded_policy.value().trusted_signers.size() == 1U);

    {
        CoutCapture output;
        const std::string root_text = update_root.string();
        const std::vector<std::string_view> command{
            "update-policy-template", "service-image",
            "iotox-test-linux-service-x86_64", root_text,
            "--signer-policy-epoch", "1", "--payload-kind",
            "linux-service-v1", signer_hex};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        const std::string service_text = output.text();
        const std::vector<std::uint8_t> service_bytes(
            service_text.begin(), service_text.end());
        auto service_policy =
            iotox::update::decode_update_policy(service_bytes);
        IOTOX_CHECK_MSG(
            service_policy.ok(), service_policy.status().message());
        IOTOX_CHECK(
            service_policy.value().payload_kind ==
            iotox::update::PayloadKind::linux_service_v1);
        IOTOX_CHECK(service_text.starts_with(
            "iotox-update-policy-v3\n"));
    }

    const auto policy_path = temporary.root() / "update.policy";
    IOTOX_CHECK(iotox::StateStore::write_atomic(
                    policy_path, policy_bytes).ok());
    IOTOX_CHECK(::chmod(policy_path.c_str(), 0600) == 0);
    {
        CoutCapture output;
        const std::string policy_native = policy_path.string();
        const std::vector<std::string_view> command{
            "update-policy-lint", policy_native};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find(
                        "namespace=system-image target=iotox-test-x86_64") ==
                    0U);
        IOTOX_CHECK(output.text().find(
                        " signer-policy-epoch=0 revoked-signers=0 signers=1 "
                        "canonical=1\n") != std::string::npos);
    }

    {
        CerrCapture error;
        const std::string policy_native = policy_path.string();
        const std::vector<std::string_view> command{
            "update-policy-rotate", policy_native,
            "--retire-signer", signer_hex};
        IOTOX_CHECK(iotox::run_cli(command) == 2);
    }

    auto successor_signer =
        iotox::security::DeviceIdentity::create_new_release(
            temporary.root() / "successor-release.identity",
            sodium.value());
    IOTOX_CHECK_MSG(successor_signer.ok(),
                    successor_signer.status().message());
    std::string overlap_policy_text;
    {
        CoutCapture output;
        const std::string policy_native = policy_path.string();
        const std::string successor_hex =
            successor_signer.value().public_key_hex();
        const std::vector<std::string_view> command{
            "update-policy-rotate", policy_native,
            "--add-signer", successor_hex};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        overlap_policy_text = output.text();
    }
    auto overlap_policy = iotox::update::decode_update_policy(
        std::vector<std::uint8_t>(overlap_policy_text.begin(),
                                  overlap_policy_text.end()));
    IOTOX_CHECK_MSG(overlap_policy.ok(),
                    overlap_policy.status().message());
    IOTOX_CHECK(overlap_policy.value().signer_policy_epoch == 1U);
    IOTOX_CHECK(overlap_policy.value().trusted_signers.size() == 2U);
    IOTOX_CHECK(overlap_policy.value().revoked_signers.empty());
    const auto overlap_policy_path = temporary.root() / "update-overlap.policy";
    IOTOX_CHECK(iotox::StateStore::write_atomic(
                    overlap_policy_path,
                    std::vector<std::uint8_t>(overlap_policy_text.begin(),
                                              overlap_policy_text.end())).ok());
    IOTOX_CHECK(::chmod(overlap_policy_path.c_str(), 0600) == 0);
    std::string retired_policy_text;
    {
        CoutCapture output;
        const std::string policy_native = overlap_policy_path.string();
        const std::vector<std::string_view> command{
            "update-policy-rotate", policy_native,
            "--retire-signer", signer_hex};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        retired_policy_text = output.text();
    }
    auto retired_policy = iotox::update::decode_update_policy(
        std::vector<std::uint8_t>(retired_policy_text.begin(),
                                  retired_policy_text.end()));
    IOTOX_CHECK_MSG(retired_policy.ok(),
                    retired_policy.status().message());
    IOTOX_CHECK(retired_policy.value().signer_policy_epoch == 2U);
    IOTOX_CHECK(retired_policy.value().trusted_signers.size() == 1U);
    IOTOX_CHECK(retired_policy.value().trusted_signers.front() ==
                successor_signer.value().public_key());
    IOTOX_CHECK(retired_policy.value().revoked_signers.size() == 1U);
    IOTOX_CHECK(retired_policy.value().revoked_signers.front() ==
                signer.value().public_key());

    std::string rotated_policy_text;
    {
        CoutCapture output;
        const std::string root_text = update_root.string();
        const std::vector<std::string_view> command{
            "update-policy-template", "system-image", "iotox-test-x86_64",
            root_text, "--signer-policy-epoch", "2", signer_hex,
            "--revoked-signer", retired_signer_hex};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        rotated_policy_text = output.text();
    }
    const std::vector<std::uint8_t> rotated_policy_bytes(
        rotated_policy_text.begin(), rotated_policy_text.end());
    auto rotated_policy =
        iotox::update::decode_update_policy(rotated_policy_bytes);
    IOTOX_CHECK_MSG(rotated_policy.ok(), rotated_policy.status().message());
    IOTOX_CHECK(rotated_policy.value().signer_policy_epoch == 2U);
    IOTOX_CHECK(rotated_policy.value().trusted_signers.size() == 1U);
    IOTOX_CHECK(rotated_policy.value().revoked_signers.size() == 1U);

    const auto rotated_policy_path = temporary.root() / "update-v2.policy";
    IOTOX_CHECK(iotox::StateStore::write_atomic(
                    rotated_policy_path, rotated_policy_bytes).ok());
    IOTOX_CHECK(::chmod(rotated_policy_path.c_str(), 0600) == 0);
    {
        CoutCapture output;
        const std::string policy_native = rotated_policy_path.string();
        const std::vector<std::string_view> command{
            "update-policy-lint", policy_native};
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find(
                        " signer-policy-epoch=2 revoked-signers=1 signers=1 "
                        "canonical=1\n") != std::string::npos);
    }

    const auto payload_path = temporary.root() / "payload.bin";
    const std::string payload_text = "inert update payload\n";
    const std::vector<std::uint8_t> payload_bytes(
        payload_text.begin(), payload_text.end());
    IOTOX_CHECK(iotox::StateStore::write_atomic(
                    payload_path, payload_bytes).ok());
    IOTOX_CHECK(::chmod(payload_path.c_str(), 0600) == 0);
    const auto bundle_path = temporary.root() / "release.iub";
    const std::string identity_native = identity_path.string();
    const std::string policy_native = rotated_policy_path.string();
    const std::string payload_native = payload_path.string();
    const std::string bundle_native = bundle_path.string();
    const std::vector<std::string_view> command{
        "--identity", identity_native, "update-bundle-create", policy_native,
        payload_native, bundle_native, "7", "7.0.0-test"};
    {
        CoutCapture output;
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find(" sequence=7 version=\"7.0.0-test\"") !=
                    std::string::npos);
        IOTOX_CHECK(output.text().find(" signed=1\n") != std::string::npos);
    }
    auto inspected = iotox::update::inspect_signed_update_bundle(
        rotated_policy.value(), bundle_path, sodium.value());
    IOTOX_CHECK_MSG(inspected.ok(), inspected.status().message());
    IOTOX_CHECK(inspected.value().manifest.release_sequence == 7U);
    IOTOX_CHECK(inspected.value().manifest.version == "7.0.0-test");
    IOTOX_CHECK(inspected.value().manifest.payload_bytes ==
                payload_bytes.size());
    CerrCapture error;
    IOTOX_CHECK(iotox::run_cli(command) == 3);
}

IOTOX_TEST("CLI creates one canonical signed route set without replacement") {
    TemporaryDirectory temporary;
    IOTOX_CHECK(!temporary.root().empty());
    auto sodium = iotox::security::Sodium::load();
    IOTOX_CHECK(sodium.ok());
    const auto identity_path = temporary.root() / "device.identity";
    auto identity = iotox::security::DeviceIdentity::load_or_create(
        identity_path, sodium.value(), true);
    IOTOX_CHECK(identity.ok());
    const auto output_path = temporary.root() / "routes.signed";
    const std::string identity_text = identity_path.string();
    const std::string output_text = output_path.string();
    const std::string coordinator(64U, '1');
    const std::string bulk_key(64U, '2');
    const std::string protected_member =
        coordinator + ":protected:either:1:0:0";
    const std::string bulk_member = bulk_key + ":bulk:either:8:1:0";
    const std::vector<std::string_view> command{
        "--identity", identity_text, "route-set-create", output_text,
        "1", coordinator, protected_member, bulk_member};
    {
        CoutCapture output;
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find(" generation=1 members=2 ") !=
                    std::string::npos);
    }
    auto artifact = iotox::StateStore::read(output_path);
    IOTOX_CHECK(artifact.ok());
    auto verified = iotox::routes::verify_route_set(
        artifact.value(), identity.value().public_key(), 1U,
        sodium.value());
    IOTOX_CHECK(verified.ok());
    IOTOX_CHECK(verified.value().members.size() == 2U);
    const auto generation_path = temporary.root() / "routes.generation";
    const std::string generation_text = generation_path.string();
    const std::string domain(32U, 'a');
    const std::vector<std::string_view> enroll{
        "witness-route-enrollment", identity_text, output_text,
        generation_text, domain, "9"};
    {
        CoutCapture output;
        IOTOX_CHECK(iotox::run_cli(enroll) == 0);
        const std::string encoded = output.text();
        IOTOX_CHECK(encoded.size() ==
                    iotox::rollback_witness::kEnrollmentBytes * 2U + 1U);
        auto bytes = iotox::security::decode_hex_exact(
            std::string_view{encoded}.substr(0U, encoded.size() - 1U),
            iotox::rollback_witness::kEnrollmentBytes,
            "route witness enrollment");
        IOTOX_CHECK_MSG(bytes.ok(), bytes.status().message());
        iotox::rollback_witness::EnrollmentBytes enrollment{};
        std::copy(bytes.value().begin(), bytes.value().end(),
                  enrollment.begin());
        auto record = iotox::rollback_witness::verify_enrollment(
            enrollment, sodium.value());
        IOTOX_CHECK_MSG(record.ok(), record.status().message());
        IOTOX_CHECK(record.value().lane ==
                    iotox::rollback_witness::Lane::route_generation);
        IOTOX_CHECK(record.value().committed.position == 1U);
    }
    CerrCapture error;
    IOTOX_CHECK(iotox::run_cli(command) == 2);
}

IOTOX_TEST("CLI creates route-set v2 with signed member network classes") {
    TemporaryDirectory temporary;
    IOTOX_CHECK(!temporary.root().empty());
    auto sodium = iotox::security::Sodium::load();
    IOTOX_CHECK(sodium.ok());
    const auto identity_path = temporary.root() / "device.identity";
    auto identity = iotox::security::DeviceIdentity::load_or_create(
        identity_path, sodium.value(), true);
    IOTOX_CHECK(identity.ok());
    const auto output_path = temporary.root() / "routes-v2.signed";
    const std::string identity_text = identity_path.string();
    const std::string output_text = output_path.string();
    const std::string coordinator(64U, '1');
    const std::string bulk_key(64U, '2');
    const std::string protected_member =
        coordinator + ":protected:either:tox/native:1:0:0";
    const std::string bulk_member =
        bulk_key + ":bulk:tcp:tox/i2p:8:1:0";
    const std::vector<std::string_view> command{
        "--identity", identity_text, "route-set-create-v2", output_text,
        "2", coordinator, protected_member, bulk_member};
    {
        CoutCapture output;
        IOTOX_CHECK(iotox::run_cli(command) == 0);
        IOTOX_CHECK(output.text().find(" generation=2 members=2 format=2 ") !=
                    std::string::npos);
    }
    auto artifact = iotox::StateStore::read(output_path);
    IOTOX_CHECK(artifact.ok());
    auto verified = iotox::routes::verify_route_set(
        artifact.value(), identity.value().public_key(), 2U,
        sodium.value());
    IOTOX_CHECK(verified.ok());
    IOTOX_CHECK(verified.value().format_version ==
                iotox::routes::kRouteSetFormatVersionV2);
    IOTOX_CHECK(verified.value().members.front().network_class ==
                iotox::routes::NetworkClass::tox_native);
    IOTOX_CHECK(verified.value().members.back().network_class ==
                iotox::routes::NetworkClass::tox_i2p);
}

IOTOX_TEST("CLI rejects malformed synchronization controls before socket use") {
    const std::string long_namespace(65U, 'a');
    const std::string zero_record(64U, '0');
    const std::vector<std::vector<std::string_view>> invalid_arguments{
        {"sync-publish"},
        {"sync-publish", "field-notes", "relative-file"},
        {"sync-publish", long_namespace, "/tmp/artifact"},
        {"sync-auto-publish"},
        {"sync-auto-publish", "field-notes", "relative-file"},
        {"sync-auto-publish", long_namespace, "/tmp/artifact"},
        {"sync-auto-publish", "field-notes", "/tmp/artifact", "0"},
        {"sync-auto-publish", "field-notes", "/tmp/artifact", "86401"},
        {"sync-create"},
        {"sync-create", "field-notes", "relative-file"},
        {"sync-create", long_namespace, "/tmp/artifact"},
        {"sync-create", "field-notes", "/tmp/artifact", "0"},
        {"sync-create", "field-notes", "/tmp/artifact", "86401"},
        {"sync-create", "field-notes", "/tmp/artifact", "read-write",
         "30", "unknown-metadata"},
        {"sync-create", "field-notes", "/tmp/artifact", "read-write",
         "30", "owner-mode-v2", "include=../escape"},
        {"sync-create", "field-notes", "/tmp/artifact", "read-write",
         "30", "owner-mode-v2", "include=docs", "include=docs"},
        {"sync-doctor"},
        {"sync-doctor", "relative-file"},
        {"sync-doctor", "/tmp/artifact", "one-writer", "0"},
        {"sync-doctor", "/tmp/artifact", "one-writer", "30",
         "owner-mode-v2"},
        {"sync-doctor", "/tmp/artifact", "read-write", "30",
         "owner-mode-v2", "include=../escape"},
        {"sync-doctor-configured"},
        {"sync-doctor-configured", "--config", "/tmp/agent.conf"},
        {"sync-doctor-configured", "--config", "/tmp/agent.conf", "Invalid"},
        {"sync-share"},
        {"sync-share", "Invalid", "1", "read-only"},
        {"sync-share", "field-notes", "1", "write-only"},
        {"sync-share", "field-notes", "1", "owner"},
        {"sync-follow"},
        {"sync-follow", "invalid", "field-notes", "pull"},
        {"sync-follow", "1", "field-notes", "automatic"},
        {"sync-follow", "1", "field-notes", "verified", "0"},
        {"sync-automation", "extra"},
        {"sync-automation-remove"},
        {"sync-automation-remove", "Invalid"},
        {"sync-activate"},
        {"sync-activate", "field-notes", "00"},
        {"sync-activate", "field-notes",
         "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"},
        {"sync-namespace-template"},
        {"sync-namespace-template-tree"},
        {"sync-namespace-template", "Field-Notes", "/tmp/sync", "00"},
        {"sync-namespace-lint"},
        {"sync-namespace-install"},
        {"sync-namespace-update"},
        {"sync-namespace-remove"},
        {"sync-namespace-remove", "Invalid"},
        {"sync-repair"},
        {"sync-repair", "Invalid"},
        {"sync-health"},
        {"sync-health", "Invalid"},
        {"sync-health", "field-notes", "unknown"},
        {"sync-health", "field-notes", "cached", "extra"},
        {"sync-gc"},
        {"sync-gc", "Invalid", "dry-run"},
        {"sync-gc", "field-notes", "apply"},
        {"sync-gc", "field-notes", "quarantine", "extra"},
        {"sync-interest"},
        {"sync-interest", "Invalid"},
        {"sync-interest", "field-notes", "include=../escape"},
        {"sync-interest", "field-notes", "include=docs", "include=docs"},
        {"sync-interest-clear"},
        {"sync-interest-clear", "field-notes", "extra"},
        {"sync-checkpoint"},
        {"sync-checkpoint", "Invalid"},
        {"sync-retention"},
        {"sync-restore", "Invalid"},
        {"sync-history"},
        {"sync-history", "field-notes", "0"},
        {"sync-history", "field-notes", "129"},
        {"sync-diff"},
        {"sync-diff", "field-notes", "00", zero_record},
        {"sync-conflicts"},
        {"sync-conflicts", "Invalid"},
        {"sync-restore-plan"},
        {"sync-restore-plan", "field-notes", "00"},
        {"sync-restore-forward"},
        {"sync-restore-forward", "field-notes", zero_record,
         "00"},
        {"sync-pin"},
        {"sync-pin", "field-notes", "00"},
        {"sync-unpin", "Invalid", zero_record},
        {"sync-writer-cutoff"},
        {"sync-writer-cutoff", "field-notes", "00"},
        {"sync-cancel"},
        {"sync-cancel", "0"},
        {"sync-cancel", "invalid"},
        {"sync-source-add"},
        {"sync-source-add", "0", "1"},
        {"sync-source-add", "invalid", "1"},
        {"sync-source-add", "1", "invalid"},
        {"sync-replica-import"},
        {"sync-replica-import", "", "relative-head"},
        {"sync-replica-import", "bad/name", "relative-head"},
        {"sync-replica-import", long_namespace, "/tmp/head"},
        {"sync-pull-multi"},
        {"sync-pull-multi", "0", "field-notes"},
        {"sync-pull-multi", "0", "field-notes", "0"},
        {"sync-pull-multi", "invalid", "field-notes", "1"},
        {"sync-pull-multi", "0", long_namespace, "1"},
        {"sync-pull-multi-route", "0", "field-notes", "any", "0"},
        {"sync-pull-multi-route", "0", "field-notes", "invalid", "0"},
        {"sync-pull-multi-route", "0", long_namespace, "tox/native", "0"},
    };
    CerrCapture capture;
    for (const auto &arguments : invalid_arguments) {
        IOTOX_CHECK(iotox::run_cli(arguments) == 2);
    }
}

IOTOX_TEST("CLI preflights a writable sync tree without an Agent or mutation") {
    TemporaryDirectory temporary;
    IOTOX_CHECK(!temporary.root().empty());
    const auto source = temporary.root() / "source";
    const auto docs = source / "docs";
    IOTOX_CHECK(std::filesystem::create_directories(docs));
    IOTOX_CHECK(::chmod(source.c_str(), static_cast<mode_t>(0700)) == 0);
    IOTOX_CHECK(::chmod(docs.c_str(), static_cast<mode_t>(0700)) == 0);
    const std::vector<std::uint8_t> content{'h', 'e', 'l', 'l', 'o'};
    IOTOX_CHECK(iotox::StateStore::write_atomic(docs / "note", content).ok());
    const std::string source_text = source.string();
    const std::array<std::string_view, 7U> command{
        "sync-doctor", source_text, "read-write", "30",
        "owner-mode-v2", "include=docs", "exclude=docs/cache"};
    CoutCapture output;
    IOTOX_CHECK(iotox::run_cli(command) == 0);
    const std::string report = output.text();
    IOTOX_CHECK(report.starts_with(
        "iotox-sync-doctor-v3\ndecision=ready\n"));
    IOTOX_CHECK(report.find("access=read-write\n") != std::string::npos);
    IOTOX_CHECK(report.find("engine=tree-v2\n") != std::string::npos);
    IOTOX_CHECK(report.find("metadata=owner-mode-v2\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("files=1\n") != std::string::npos);
    IOTOX_CHECK(report.find("content-bytes=5\n") != std::string::npos);
    IOTOX_CHECK(report.find("managed-storage-headroom=not-probed\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("filesystem-contract=ready\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find(
                    "path-model=byte-exact-case-sensitive-required\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("backup=not-assessed\n") !=
                std::string::npos);
    IOTOX_CHECK(std::distance(std::filesystem::directory_iterator(source),
                              std::filesystem::directory_iterator{}) == 1);
    IOTOX_CHECK(std::distance(std::filesystem::directory_iterator(docs),
                              std::filesystem::directory_iterator{}) == 1);
}

IOTOX_TEST("CLI verifies one independently supplied restore tree") {
    TemporaryDirectory temporary;
    IOTOX_CHECK(!temporary.root().empty());
    const auto backup = temporary.root() / "backup";
    const auto restored = temporary.root() / "restored";
    IOTOX_CHECK(std::filesystem::create_directory(backup));
    IOTOX_CHECK(std::filesystem::create_directory(restored));
    IOTOX_CHECK(::chmod(backup.c_str(), static_cast<mode_t>(0700)) == 0);
    IOTOX_CHECK(::chmod(restored.c_str(), static_cast<mode_t>(0700)) == 0);
    const std::vector<std::uint8_t> content{'d', 'r', 'i', 'l', 'l'};
    IOTOX_CHECK(iotox::StateStore::write_atomic(backup / "note", content).ok());
    IOTOX_CHECK(
        iotox::StateStore::write_atomic(restored / "note", content).ok());
    const std::string backup_text = backup.string();
    const std::string restored_text = restored.string();
    const std::array<std::string_view, 7U> command{
        "sync-recovery-verify", backup_text, restored_text,
        "backup-system=restic", "backup-generation=snap-1",
        "backup-failure-domain=usb-disk",
        "restore-provenance=manual-drill"};
    CoutCapture output;
    IOTOX_CHECK(iotox::run_cli(command) == 0);
    const std::string report = output.text();
    IOTOX_CHECK(report.starts_with(
        "iotox-sync-recovery-verify-v1\ndecision=match\n"));
    IOTOX_CHECK(report.find("backup-bytes=5\n") != std::string::npos);
    IOTOX_CHECK(report.find("restored-bytes=5\n") != std::string::npos);
    IOTOX_CHECK(report.find("iotox-live-state-read=0\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("operator-provenance=present\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("backup-system-hex=726573746963\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("backup-independence=not-assessed\n") !=
                std::string::npos);
}

IOTOX_TEST("CLI reports authenticated witness checkpoint custody") {
    TemporaryDirectory temporary;
    IOTOX_CHECK(!temporary.root().empty());
    const auto device_root = temporary.root() / "device";
    const auto service_root = temporary.root() / "service";
    const auto checkpoint_root = temporary.root() / "checkpoint";
    IOTOX_CHECK(std::filesystem::create_directory(device_root));
    IOTOX_CHECK(std::filesystem::create_directory(service_root));
    IOTOX_CHECK(std::filesystem::create_directory(checkpoint_root));
    IOTOX_CHECK(::chmod(device_root.c_str(), static_cast<mode_t>(0700)) == 0);
    IOTOX_CHECK(::chmod(service_root.c_str(), static_cast<mode_t>(0700)) == 0);
    IOTOX_CHECK(::chmod(checkpoint_root.c_str(), static_cast<mode_t>(0700)) == 0);

    auto sodium = iotox::security::Sodium::load();
    IOTOX_CHECK_MSG(sodium.ok(), sodium.status().message());
    auto device = iotox::security::DeviceIdentity::load_or_create(
        device_root / "device.identity", sodium.value(), true);
    IOTOX_CHECK_MSG(device.ok(), device.status().message());
    auto service = iotox::security::DeviceIdentity::create_new_witness(
        service_root / "service.identity", sodium.value());
    IOTOX_CHECK_MSG(service.ok(), service.status().message());
    auto store = iotox::rollback_witness::ServiceStore::open(
        service_root, service.value(), sodium.value());
    IOTOX_CHECK_MSG(store.ok(), store.status().message());
    iotox::rollback_witness::Record record;
    record.domain[0U] = 0x41U;
    record.device = device.value().public_key();
    record.witness_epoch = 7U;
    IOTOX_CHECK(store.value()->enroll(record).ok());
    auto checkpoint = store.value()->checkpoint();
    IOTOX_CHECK_MSG(checkpoint.ok(), checkpoint.status().message());
    const auto checkpoint_path = checkpoint_root / "service.checkpoint";
    IOTOX_CHECK(iotox::StateStore::write_atomic(
                    checkpoint_path, checkpoint.value())
                    .ok());

    const std::string service_root_text = service_root.string();
    const std::string checkpoint_text = checkpoint_path.string();
    const std::string service_key_text = service.value().public_key_hex();
    const std::vector<std::string_view> command{
        "witness-service-checkpoint-custody", service_root_text,
        checkpoint_text, service_key_text, "custody-system=restic",
        "custody-generation=wcp-001", "custody-failure-domain=usb-disk"};
    CoutCapture output;
    IOTOX_CHECK(iotox::run_cli(command) == 0);
    const std::string report = output.text();
    IOTOX_CHECK(report.starts_with(
        "iotox-witness-checkpoint-custody-v1\ncheckpoint-authenticated=1\n"));
    IOTOX_CHECK(report.find("outside-service-root=1\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("checkpoint-records=1\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("operator-custody=present\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("custody-system-hex=726573746963\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("operational-independence=not-assessed\n") !=
                std::string::npos);

    const auto inside_checkpoint = service_root / "inside.checkpoint";
    IOTOX_CHECK(iotox::StateStore::write_atomic(
                    inside_checkpoint, checkpoint.value())
                    .ok());
    const std::string inside_text = inside_checkpoint.string();
    const std::vector<std::string_view> inside_command{
        "witness-service-checkpoint-custody", service_root_text,
        inside_text, service_key_text};
    CerrCapture errors;
    IOTOX_CHECK(iotox::run_cli(inside_command) == 2);
}

IOTOX_TEST("CLI joins configured sync source to live managed headroom") {
    TemporaryDirectory temporary;
    IOTOX_CHECK(!temporary.root().empty());
    const auto source = temporary.root() / "source.bin";
    IOTOX_CHECK(iotox::StateStore::write_atomic(
                    source, std::vector<std::uint8_t>{'d', 'a', 't', 'a'})
                    .ok());
    const auto identity_path = temporary.root() / "device.identity";
    auto sodium = iotox::security::Sodium::load();
    IOTOX_CHECK_MSG(sodium.ok(), sodium.status().message());
    auto identity = iotox::security::DeviceIdentity::load_or_create(
        identity_path, sodium.value(), true);
    IOTOX_CHECK_MSG(identity.ok(), identity.status().message());

    const auto policy_root = temporary.root() / "sync-policy";
    const auto namespaces = policy_root / "namespaces";
    IOTOX_CHECK(std::filesystem::create_directories(namespaces));
    IOTOX_CHECK(::chmod(policy_root.c_str(), 0700) == 0);
    IOTOX_CHECK(::chmod(namespaces.c_str(), 0700) == 0);
    auto managed = iotox::sync::prepare_managed_namespace_root(
        policy_root, "field-notes",
        static_cast<std::uint32_t>(::geteuid()));
    IOTOX_CHECK_MSG(managed.ok(), managed.status().message());
    iotox::sync::NamespacePolicy policy;
    policy.id = "field-notes";
    policy.root = managed.value().string();
    policy.engine = iotox::sync::Engine::content_v2;
    policy.activation = iotox::sync::ActivationMode::manual;
    policy.writers = {identity.value().public_key()};
    --policy.quotas.maximum_store_bytes;
    auto installed = iotox::sync::install_namespace_policy(
        policy_root, policy, static_cast<std::uint32_t>(::geteuid()));
    IOTOX_CHECK_MSG(installed.ok(), installed.status().message());
    {
        auto initialized =
            iotox::sync::SyncNamespaceTransaction::acquire(policy);
        IOTOX_CHECK_MSG(initialized.ok(), initialized.status().message());
    }
    iotox::sync::SyncAutomationSpec automation;
    automation.namespace_id = policy.id;
    automation.mode = iotox::sync::SyncAutomationMode::publish;
    automation.source_path = source.string();
    automation.interval_ms = 1750U;
    iotox::sync::SyncAutomationStore automation_store{policy_root};
    auto stored = automation_store.put(automation, identity.value(),
                                       sodium.value());
    IOTOX_CHECK_MSG(stored.ok(), stored.status().message());

    const auto config_path = temporary.root() / "agent.conf";
    iotox::AgentConfigRecord config;
    config.arguments = {
        "--state", (temporary.root() / "device.toxsave").string(),
        "--identity", identity_path.string(),
        "--no-default-bootstrap", "--no-default-relays",
        "--enable-sync", "--sync-policy-root", policy_root.string(),
    };
    auto encoded = iotox::encode_agent_config_record(config);
    IOTOX_CHECK_MSG(encoded.ok(), encoded.status().message());
    {
        std::ofstream output(config_path, std::ios::binary | std::ios::trunc);
        output.write(
            reinterpret_cast<const char *>(encoded.value().data()),
            static_cast<std::streamsize>(encoded.value().size()));
        output.close();
        IOTOX_CHECK(output.good());
    }
    IOTOX_CHECK(::chmod(config_path.c_str(), 0600) == 0);

    const std::array<std::string, 4U> owned{
        "sync-doctor-configured", "--config", config_path.string(),
        "field-notes"};
    const std::array<std::string_view, 4U> command{
        owned[0], owned[1], owned[2], owned[3]};
    CoutCapture output;
    IOTOX_CHECK(iotox::run_cli(command) == 0);
    const std::string report = output.text();
    IOTOX_CHECK(report.starts_with(
        "iotox-sync-doctor-v4\ndecision=ready\n"));
    IOTOX_CHECK(report.find("configured-namespace=field-notes\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("automation-generation=1\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("automation-interval-ms=1750\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("quota-store-bytes=" +
                            std::to_string(policy.quotas.maximum_store_bytes) +
                            "\n") != std::string::npos);
    IOTOX_CHECK(report.find("managed-storage-headroom=ready\n") !=
                std::string::npos);
    IOTOX_CHECK(report.find("backup=not-assessed\n") != std::string::npos);
}

IOTOX_TEST("CLI accepts bounded selective read-write sync creation") {
    TemporaryDirectory temporary;
    IOTOX_CHECK(!temporary.root().empty());
    const std::string runtime =
        (temporary.root() / "absent-runtime").string();
    const std::vector<std::string_view> arguments{
        "--runtime", runtime, "sync-create", "field-notes", "/tmp/source",
        "read-write", "30", "owner-mode-v2", "include=docs",
        "exclude=docs/cache"};
    CerrCapture capture;
    // Valid parsing reaches the absent control socket. Parser refusal is 2.
    IOTOX_CHECK(iotox::run_cli(arguments) == 3);
    const std::vector<std::string_view> interest{
        "--runtime", runtime, "sync-interest", "field-notes",
        "include=docs", "exclude=docs/cache"};
    IOTOX_CHECK(iotox::run_cli(interest) == 3);
    const std::vector<std::string_view> interest_show{
        "--runtime", runtime, "sync-interest", "field-notes"};
    IOTOX_CHECK(iotox::run_cli(interest_show) == 3);
    const std::vector<std::string_view> interest_clear{
        "--runtime", runtime, "sync-interest-clear", "field-notes"};
    IOTOX_CHECK(iotox::run_cli(interest_clear) == 3);

    std::vector<std::string> owned{
        "--runtime", runtime, "sync-create", "field-notes", "/tmp/source",
        "read-write", "30", "owner-mode-v2"};
    for (std::size_t index = 0U;
         index <= iotox::sync::kMaximumTreeV2SelectionRules; ++index) {
        owned.push_back("include=path-" + std::to_string(index));
    }
    std::vector<std::string_view> excessive;
    excessive.reserve(owned.size());
    for (const std::string &argument : owned) excessive.push_back(argument);
    IOTOX_CHECK(iotox::run_cli(excessive) == 2);
}

IOTOX_TEST(
    "CLI accepts a repeated routed source as distinct carrier intent") {
    TemporaryDirectory temporary;
    IOTOX_CHECK(!temporary.root().empty());
    const std::string runtime =
        (temporary.root() / "absent-runtime").string();
    const std::vector<std::string_view> arguments{
        "--runtime", runtime, "sync-pull-multi-route", "0",
        "field-notes", "tox/native", "0"};
    CerrCapture capture;
    // The command reached the absent control socket. A parser rejection is 2.
    IOTOX_CHECK(iotox::run_cli(arguments) == 3);
}

IOTOX_TEST("CLI renders a canonical synchronization namespace template") {
    const std::string writer(64U, '1');
    const std::string subscriber_high(64U, '3');
    const std::string subscriber_low(64U, '2');
    CoutCapture capture;
    const std::vector<std::string_view> arguments{
        "sync-namespace-template", "field-notes", "/var/lib/iotox/field-notes",
        writer, subscriber_high, subscriber_low};
    IOTOX_CHECK(iotox::run_cli(arguments) == 0);
    const std::string text = capture.text();
    const std::vector<std::uint8_t> bytes(text.begin(), text.end());
    auto decoded = iotox::sync::decode_namespace_policy(bytes);
    IOTOX_CHECK_MSG(decoded.ok(), decoded.status().message());
    IOTOX_CHECK(decoded.value().id == "field-notes");
    IOTOX_CHECK(decoded.value().root == "/var/lib/iotox/field-notes");
    IOTOX_CHECK(decoded.value().engine == iotox::sync::Engine::range_v1);
    IOTOX_CHECK(decoded.value().activation ==
                iotox::sync::ActivationMode::manual);
    IOTOX_CHECK(decoded.value().writers.size() == 1U);
    IOTOX_CHECK(decoded.value().subscribers.size() == 2U);
    IOTOX_CHECK(decoded.value().subscribers[0U][0U] == 0x22U);
    IOTOX_CHECK(decoded.value().subscribers[1U][0U] == 0x33U);
}

IOTOX_TEST("CLI renders a canonical tree synchronization namespace template") {
    const std::string writer(64U, '1');
    CoutCapture capture;
    const std::vector<std::string_view> arguments{
        "sync-namespace-template-tree", "site-tree",
        "/var/lib/iotox/site-tree", writer};
    IOTOX_CHECK(iotox::run_cli(arguments) == 0);
    const std::string text = capture.text();
    const std::vector<std::uint8_t> bytes(text.begin(), text.end());
    auto decoded = iotox::sync::decode_namespace_policy(bytes);
    IOTOX_CHECK_MSG(decoded.ok(), decoded.status().message());
    IOTOX_CHECK(decoded.value().id == "site-tree");
    IOTOX_CHECK(decoded.value().engine ==
                iotox::sync::Engine::treepack_v1);
    IOTOX_CHECK(decoded.value().activation ==
                iotox::sync::ActivationMode::manual);
}
