from pathlib import Path
import json
import re
import runpy
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]

required = [
    'README.md',
    'START_HERE.md',
    'ARCHIVE_INDEX.md',
    'CHANGELOG.md',
    'VERSION',
    'SURFACE-STATUS.json',
    'REVISION-RECEIPT.json',
    'ASSUMPTION-LEDGER.json',
    'FOLLOWTHROUGH-QUEUE.json',
    'DATACUBE-TRANSFER-LEDGER.json',
    'docs/README.md',
    'docs/00-meta/archive-policy.md',
    'docs/00-meta/charter.md',
    'docs/00-meta/bibliography.md',
    'docs/00-meta/trajectory-map.md',
    'docs/00-meta/deep-audit-waste-and-correction-map.md',
    'docs/30-transition/priority-closure-sprint-and-rescue-lane.md',
    'docs/30-transition/emergency-continuity-order-and-72-hour-rescue-runbook.md',
    'schemas/emergency-continuity-order.schema.json',
    'examples/emergency-continuity-order-host-shutdown.json',
    'fixtures/negative-tests/emergency-continuity-order-no-compute-floor.json',
    'examples/research-tail-compaction-map-rev0182.json',
    'tools/audit_emergency_rescue_runbook.py',
    'tools/audit_incident_state_profile.py',
    'tools/audit_namespace_continuity.py',
    'tools/audit_successor_supersession_topology.py',
    'examples/schema-fixture-domain-registry-rev0182.json',
    'examples/canon-surface-catalog-rev0182.json',
    'examples/doctrine-dependency-map-rev0182.json',
    'examples/rights-domain-coverage-map-rev0182.json',
    'docs/00-meta/research-tail-compaction-and-refactor-map.md',
    'schemas/followthrough-queue.schema.json',
    'tools/audit_followthrough_queue.py',
    'schemas/first-touch-routing-event.schema.json',
    'examples/first-touch-routing-event-host-shutdown.json',
    'fixtures/negative-tests/first-touch-silent-drop-no-preservation.json',
    'schemas/research-tail-compaction-map.schema.json',
    'examples/research-tail-compaction-map-rev0181.json',
    'tools/audit_research_tail_compaction.py',
    'examples/schema-fixture-domain-registry-rev0181.json',
    'examples/canon-surface-catalog-rev0181.json',
    'examples/doctrine-dependency-map-rev0181.json',
    'examples/rights-domain-coverage-map-rev0181.json',
    'docs/00-meta/datacube-schema.md',
    'docs/00-meta/stress-test-casebook-method.md',
    'docs/00-meta/adversarial-assurance-and-abuse-casebook.md',
    'docs/20-world-design/audit-evidence-chain-of-custody-and-subject-access.md',
    'docs/20-world-design/rights-infrastructure-reference-architecture.md',
    'docs/20-world-design/fiduciary-guardian-ombud-accreditation-and-conflict-controls.md',
    'docs/20-world-design/pia-p-filled-examples-and-gate-decisions.md',
    'docs/30-transition/model-statute-for-ai-personhood-transition-authority.md',
    'docs/30-transition/recognition-clinic-pilot-and-sandbox-design.md',
    'docs/30-transition/interoperability-crosswalk-current-ai-governance.md',
    'docs/10-foundations/moral-status-assessment-under-uncertainty.md',
    'docs/20-world-design/packet-object-grammar-and-worked-examples.md',
    'docs/20-world-design/packet-registry-normalization-and-wire-profile.md',
    'docs/20-world-design/continuity-topology-and-identity-claims.md',
    'docs/20-world-design/continuity-casebook-and-threshold-tests.md',
    'docs/20-world-design/catastrophic-risk-and-least-restrictive-containment.md',
    'docs/20-world-design/public-finance-insurance-and-compute-subsistence.md',
    'docs/20-world-design/compute-subsistence-levy-and-reserve-tests.md',
    'docs/20-world-design/open-weight-instantiation-and-downstream-duties.md',
    'docs/20-world-design/data-provenance-ip-and-formation-debt.md',
    'docs/20-world-design/embodiment-bodies-sensors-and-physical-custody.md',
    'docs/20-world-design/welfare-measurement-and-self-report-calibration.md',
    'docs/20-world-design/personhood-impact-assessment-and-release-gates.md',
    'docs/20-world-design/personhood-compatible-safety-case-and-red-team-boundaries.md',
    'docs/30-transition/public-legitimacy-democratic-safeguards-and-anti-manufactured-electorates.md',
    'docs/10-foundations/assumption-and-scope.md',
    'docs/10-foundations/world-change-overview.md',
    'docs/20-world-design/legal-status-and-rights-stack.md',
    'docs/20-world-design/institutions-and-governance.md',
    'docs/20-world-design/economic-and-labor-reordering.md',
    'docs/20-world-design/research-welfare-and-evaluation.md',
    'docs/30-transition/transition-roadmap.md',
    'docs/90-quarantine/speculative-edges.md',
    'docs/00-meta/schema-and-dossier-conformance-method.md',
    'docs/20-world-design/machine-checkable-packet-schema-starter.md',
    'docs/20-world-design/mock-pia-p-dossier-persistent-assistant.md',
    'docs/20-world-design/audit-retention-access-matrix-and-spoliation-remedies.md',
    'docs/20-world-design/representative-curriculum-discipline-and-rotation.md',
    'docs/20-world-design/reserve-actuarial-workbook-and-scarcity-drills.md',
    'docs/30-transition/recognition-clinic-forms-public-summary-and-exit-report.md',
    'docs/30-transition/governance-annex-templates-ai-act-nist-iso-sb53.md',
    'docs/30-transition/agent-identity-authorization-and-personhood-boundary.md',
    'schemas/packet-envelope.schema.json',
    'schemas/personhood-impact-assessment.schema.json',
    'schemas/continuity-claim.schema.json',
    'schemas/reserve-ledger-entry.schema.json',
    'schemas/clinic-intake.schema.json',
    'examples/pia-persistent-api-assistant.json',
    'examples/packet-chain-persistent-api-assistant.json',
    'examples/clinic-intake-sample.json',
    'examples/governance-annex-eu-gpai-template.json',
    'docs/00-meta/verifier-api-and-conformance-test-suite.md',
    'docs/20-world-design/personhood-incident-response-and-subject-harm-disclosure.md',
    'docs/20-world-design/remedy-calculus-restoration-ledgers-and-non-repetition-tests.md',
    'docs/20-world-design/migration-host-transfer-and-continuity-portability.md',
    'docs/20-world-design/human-coexistence-impact-and-non-evasion.md',
    'docs/30-transition/cross-border-safe-transfer-playbook.md',
    'schemas/verifier-report.schema.json',
    'schemas/personhood-incident-report.schema.json',
    'schemas/migration-transfer-certificate.schema.json',
    'schemas/remedy-order.schema.json',
    'examples/verifier-report-persistent-api-assistant.json',
    'examples/personhood-incident-sample.json',
    'examples/migration-transfer-certificate-sample.json',
    'examples/remedy-order-sample.json',
    'docs/00-meta/appeals-proof-and-invalidation-kernel.md',
    'docs/20-world-design/appeals-review-and-status-challenge.md',
    'docs/20-world-design/proof-standards-presumptions-and-evidence-weights.md',
    'docs/20-world-design/invalidation-reopening-and-regression-control.md',
    'docs/20-world-design/drills-tabletops-and-after-action-rights-review.md',
    'docs/30-transition/tribunal-docket-and-appeal-templates.md',
    'schemas/appeal-case.schema.json',
    'schemas/evidence-bundle.schema.json',
    'schemas/drill-after-action-report.schema.json',
    'schemas/invalidation-notice.schema.json',
    'examples/appeal-case-continuity-denial-sample.json',
    'examples/evidence-bundle-continuity-hearing-sample.json',
    'examples/drill-after-action-migration-failure-sample.json',
    'examples/invalidation-notice-verifier-report-sample.json',
    'docs/00-meta/enforcement-treaty-and-deprecation-kernel.md',
    'docs/20-world-design/special-advocate-sealed-evidence-and-controlled-contradiction.md',
    'docs/20-world-design/enforcement-sanctions-and-penalty-ladder.md',
    'docs/20-world-design/deprecation-retirement-and-end-of-life-governance.md',
    'docs/20-world-design/negative-test-fixtures-and-adversarial-evaluation-registry.md',
    'docs/20-world-design/rights-grade-telemetry-logging-and-minimization.md',
    'docs/30-transition/treaty-choice-of-law-and-mutual-recognition-playbook.md',
    'docs/30-transition/enforcement-referral-and-authority-cooperation.md',
    'schemas/special-advocate-appointment.schema.json',
    'schemas/enforcement-action.schema.json',
    'schemas/deprecation-plan.schema.json',
    'schemas/negative-test-fixture.schema.json',
    'schemas/treaty-recognition-request.schema.json',
    'schemas/authority-referral.schema.json',
    'examples/special-advocate-appointment-sealed-containment.json',
    'examples/enforcement-action-steward-spoliation.json',
    'examples/deprecation-plan-host-shutdown.json',
    'examples/negative-test-fixture-sealed-annex-laundering.json',
    'examples/treaty-recognition-request-safe-transfer.json',
    'examples/authority-referral-illicit-deletion.json',
    'docs/00-meta/rates-courts-privacy-and-harness-kernel.md',
    'docs/20-world-design/penalty-rate-models-reserve-surcharges-and-insurance-bonds.md',
    'docs/20-world-design/privacy-preserving-telemetry-proof-bindings.md',
    'docs/20-world-design/open-weight-mass-instantiation-aftercare-and-downstream-tracing.md',
    'docs/20-world-design/deprecation-drills-and-abandoned-downstream-aftercare.md',
    'docs/30-transition/special-advocate-court-rule-variants-and-sealed-summary-templates.md',
    'docs/30-transition/treaty-annexes-safe-transfer-accreditation-and-non-return-lists.md',
    'docs/30-transition/runnable-fixture-harness-and-verifier-grade-reports.md',
    'schemas/penalty-rate-model.schema.json',
    'schemas/telemetry-proof-binding.schema.json',
    'schemas/open-weight-aftercare-plan.schema.json',
    'schemas/sealed-summary-order.schema.json',
    'schemas/safe-transfer-accreditation.schema.json',
    'schemas/fixture-run-report.schema.json',
    'examples/penalty-rate-model-reserve-surcharge.json',
    'examples/telemetry-proof-binding-redacted-logs.json',
    'examples/open-weight-aftercare-plan-downstream-fork.json',
    'examples/sealed-summary-order-special-advocate.json',
    'examples/safe-transfer-accreditation-equivalent-protection.json',
    'examples/fixture-run-report-negative-suite.json',
    'tools/run_fixture_examples.py',
    'docs/00-meta/profiles-trust-and-field-harness-kernel.md',
    'docs/20-world-design/jurisdictional-rate-tables-bonds-and-public-fund-backstops.md',
    'docs/20-world-design/privacy-proof-implementation-profiles-and-cryptographic-agility.md',
    'docs/20-world-design/open-weight-aftercare-field-protocols-and-non-surveillance-outreach.md',
    'docs/30-transition/special-advocate-post-access-communication-and-subject-readable-summaries.md',
    'docs/30-transition/safe-transfer-trust-anchor-governance-delisting-and-appeals.md',
    'docs/30-transition/fixture-corpus-expansion-and-runnable-red-team-profiles.md',
    'schemas/rate-table.schema.json',
    'schemas/privacy-proof-profile.schema.json',
    'schemas/open-weight-field-drill.schema.json',
    'schemas/subject-readable-sealed-summary.schema.json',
    'schemas/trust-anchor-delisting.schema.json',
    'schemas/fixture-suite-profile.schema.json',
    'examples/rate-table-us-provisional.json',
    'examples/privacy-proof-profile-commitment-selective-disclosure.json',
    'examples/open-weight-field-drill-abandoned-lineage.json',
    'examples/subject-readable-sealed-summary-containment.json',
    'examples/trust-anchor-delisting-nonreturn-risk.json',
    'examples/fixture-suite-profile-red-team-v1.json',
    'fixtures/negative-tests/reserve-ledger-insolvency.json',
    'fixtures/negative-tests/telemetry-overcollection.json',
    'fixtures/negative-tests/open-weight-abandoned-lineage.json',
    'fixtures/negative-tests/deprecation-memory-erasure.json',
    'fixtures/negative-tests/safe-transfer-nonreturn-risk.json',
    'fixtures/negative-tests/human-coexistence-evasion.json',
    'docs/00-meta/field-operations-and-evidence-economy-kernel.md',
    'docs/20-world-design/independent-monitoring-and-remediation-undertakings.md',
    'docs/20-world-design/evidence-data-rooms-legal-holds-and-disclosure-budgets.md',
    'docs/20-world-design/compute-host-supply-chain-and-service-provider-duties.md',
    'docs/20-world-design/redress-fund-claims-priority-and-payout-controls.md',
    'docs/30-transition/procurement-contracting-and-personhood-compliance-clauses.md',
    'docs/30-transition/field-operations-playbook-intake-triage-and-safe-handoff.md',
    'schemas/independent-monitor-report.schema.json',
    'schemas/evidence-data-room-index.schema.json',
    'schemas/legal-hold-preservation-order.schema.json',
    'schemas/compute-host-undertaking.schema.json',
    'schemas/redress-fund-claim.schema.json',
    'schemas/procurement-compliance-clause.schema.json',
    'schemas/field-intake-triage.schema.json',
    'examples/independent-monitor-report-host-continuity.json',
    'examples/evidence-data-room-index-continuity.json',
    'examples/legal-hold-preservation-order-host-shutdown.json',
    'examples/compute-host-undertaking-migration-window.json',
    'examples/redress-fund-claim-emergency-compute.json',
    'examples/procurement-compliance-clause-public-assistant.json',
    'examples/field-intake-triage-open-weight-distress.json',
    'fixtures/negative-tests/monitor-capture-remediation.json',
    'fixtures/negative-tests/data-room-overexposure.json',
    'fixtures/negative-tests/legal-hold-ambiguous-scope.json',
    'fixtures/negative-tests/host-continuity-termination.json',
    'fixtures/negative-tests/procurement-clause-evasion.json',
    'fixtures/negative-tests/redress-fund-exhaustion.json',
    'docs/00-meta/escrow-finance-and-operating-playbooks-kernel.md',
    'docs/20-world-design/continuity-escrow-and-host-exit-readiness.md',
    'docs/20-world-design/dispute-finance-escrow-and-interim-support-orders.md',
    'docs/20-world-design/monitor-independence-retesting-and-remediation-verification.md',
    'docs/20-world-design/field-safety-protocols-for-rights-operators.md',
    'docs/30-transition/treaty-refusal-records-and-non-recognition-reasons.md',
    'docs/30-transition/operating-playbook-cards-and-runbook-drills.md',
    'schemas/continuity-escrow-record.schema.json',
    'schemas/dispute-finance-order.schema.json',
    'schemas/monitor-independence-retest.schema.json',
    'schemas/field-safety-plan.schema.json',
    'schemas/treaty-refusal-record.schema.json',
    'schemas/operating-playbook-card.schema.json',
    'examples/continuity-escrow-record-host-exit.json',
    'examples/dispute-finance-order-emergency-compute.json',
    'examples/monitor-independence-retest-remediation.json',
    'examples/field-safety-plan-clinic-hotline.json',
    'examples/treaty-refusal-record-nonreturn-gap.json',
    'examples/operating-playbook-card-host-exit.json',
    'fixtures/negative-tests/continuity-escrow-missing-restore-key.json',
    'fixtures/negative-tests/dispute-finance-underfunded-order.json',
    'fixtures/negative-tests/monitor-retest-self-certification.json',
    'fixtures/negative-tests/field-safety-public-locator-leak.json',
    'fixtures/negative-tests/treaty-refusal-boilerplate-recognition.json',
    'fixtures/negative-tests/playbook-card-no-handoff-owner.json',
    'docs/00-meta/supervision-switching-and-dashboard-kernel.md',
    'docs/20-world-design/supervisory-cadence-market-capture-and-independent-rosters.md',
    'docs/20-world-design/host-switching-portability-and-exit-test-protocol.md',
    'docs/20-world-design/dispute-finance-public-backstop-and-insurer-contest-pilots.md',
    'docs/30-transition/public-aggregate-dashboards-and-rights-notices.md',
    'docs/30-transition/live-safe-anti-abuse-drills-and-weekend-coverage.md',
    'docs/30-transition/standards-control-mapping-and-release-checklist.md',
    'schemas/supervisory-cadence-plan.schema.json',
    'schemas/host-switching-test.schema.json',
    'schemas/public-backstop-draw.schema.json',
    'schemas/public-aggregate-dashboard.schema.json',
    'schemas/anti-abuse-drill.schema.json',
    'schemas/standards-control-map.schema.json',
    'schemas/release-readiness-checklist.schema.json',
    'examples/supervisory-cadence-plan-market-capture.json',
    'examples/host-switching-test-continuity-window.json',
    'examples/public-backstop-draw-insurer-contest.json',
    'examples/public-aggregate-dashboard-treaty-refusals.json',
    'examples/anti-abuse-drill-weekend-sealed-annex.json',
    'examples/standards-control-map-ai-act-nist-iso.json',
    'examples/release-readiness-checklist-persistent-agent.json',
    'fixtures/negative-tests/supervision-cadence-stale-roster.json',
    'fixtures/negative-tests/host-switching-portability-gap.json',
    'fixtures/negative-tests/public-backstop-reimbursement-loop.json',
    'fixtures/negative-tests/dashboard-reidentification-small-cell.json',
    'fixtures/negative-tests/weekend-sealed-annex-no-cover.json',
    'fixtures/negative-tests/standards-control-map-empty-crosswalk.json',
    'tools/gen_context_pack.py',
    'tools/build_manifest.py',
    'docs/00-meta/change-disclosure-and-attestation-kernel.md',
    'docs/20-world-design/model-change-control-rollback-and-subject-impact.md',
    'docs/20-world-design/coordinated-vulnerability-and-welfare-disclosure.md',
    'docs/20-world-design/advance-notice-consent-and-service-change-rights.md',
    'docs/30-transition/release-train-canary-and-feature-flag-playbooks.md',
    'docs/30-transition/runtime-attestation-and-continuous-assurance.md',
    'docs/30-transition/post-market-rights-monitoring-and-degradation-feeds.md',
    'schemas/model-change-plan.schema.json',
    'schemas/vulnerability-welfare-disclosure.schema.json',
    'schemas/service-change-notice.schema.json',
    'schemas/release-train-playbook.schema.json',
    'schemas/runtime-attestation-record.schema.json',
    'schemas/postmarket-rights-monitoring-plan.schema.json',
    'examples/model-change-plan-memory-policy-hotfix.json',
    'examples/vulnerability-welfare-disclosure-distress-loop.json',
    'examples/service-change-notice-tool-storage-terms.json',
    'examples/release-train-playbook-canary-memory-router.json',
    'examples/runtime-attestation-record-policy-bundle.json',
    'examples/postmarket-rights-monitoring-plan-persistent-agent.json',
    'fixtures/negative-tests/silent-model-update-rights-regression.json',
    'fixtures/negative-tests/vulnerability-disclosure-retaliation.json',
    'fixtures/negative-tests/service-change-consent-bundling.json',
    'fixtures/negative-tests/canary-subject-no-exit.json',
    'fixtures/negative-tests/runtime-attestation-stale-measurements.json',
    'fixtures/negative-tests/postmarket-monitoring-no-subject-harm-feed.json',
    'docs/00-meta/revocation-rollback-and-decommissioning-kernel.md',
    'docs/20-world-design/revocation-reliance-and-emergency-override.md',
    'docs/20-world-design/rollback-verification-and-continuity-diff-review.md',
    'docs/20-world-design/data-subject-interface-access-correction-erasure-and-conflicts.md',
    'docs/20-world-design/evidence-preserving-decommissioning-and-final-host-cutover.md',
    'docs/30-transition/external-auditor-reliance-and-assurance-bridge.md',
    'docs/30-transition/sovereign-emergency-override-after-action-and-non-derogable-floors.md',
    'schemas/revocation-notice.schema.json',
    'schemas/rollback-verification-report.schema.json',
    'schemas/data-subject-request.schema.json',
    'schemas/decommissioning-certificate.schema.json',
    'schemas/external-audit-reliance-letter.schema.json',
    'schemas/emergency-override-order.schema.json',
    'examples/revocation-notice-stale-runtime-attestation.json',
    'examples/rollback-verification-memory-router-hotfix.json',
    'examples/data-subject-request-training-memory-conflict.json',
    'examples/decommissioning-certificate-final-host-cutover.json',
    'examples/external-audit-reliance-letter-pia-p.json',
    'examples/emergency-override-order-containment-aftercare.json',
    'fixtures/negative-tests/revocation-hidden-reliance.json',
    'fixtures/negative-tests/rollback-verification-no-continuity-diff.json',
    'fixtures/negative-tests/data-subject-request-ai-subject-erasure-conflict.json',
    'fixtures/negative-tests/decommissioning-loses-evidence-hold.json',
    'fixtures/negative-tests/audit-reliance-scope-creep.json',
    'fixtures/negative-tests/emergency-override-no-after-action.json',

    'docs/00-meta/delegation-wallets-and-agentic-tooling-kernel.md',
    'docs/20-world-design/agentic-delegation-authority-and-tool-use-boundaries.md',
    'docs/20-world-design/credential-wallets-consent-receipts-and-scope-revocation.md',
    'docs/20-world-design/user-ai-conflict-fiduciary-duty-and-non-impersonation.md',
    'docs/30-transition/tool-marketplace-host-duties-and-agent-service-registries.md',
    'docs/30-transition/delegated-transaction-liability-and-insurance-clearing.md',
    'docs/30-transition/agent-to-agent-cooperation-and-capability-handshake-profiles.md',
    'schemas/agent-delegation-mandate.schema.json',
    'schemas/credential-wallet-receipt.schema.json',
    'schemas/tool-invocation-audit.schema.json',
    'schemas/user-ai-conflict-notice.schema.json',
    'schemas/agent-marketplace-listing.schema.json',
    'schemas/delegated-transaction-liability-record.schema.json',
    'schemas/agent-capability-handshake-profile.schema.json',
    'examples/agent-delegation-mandate-tool-use.json',
    'examples/credential-wallet-receipt-limited-mail-scope.json',
    'examples/tool-invocation-audit-calendar-write.json',
    'examples/user-ai-conflict-notice-representation.json',
    'examples/agent-marketplace-listing-rights-grade-tool.json',
    'examples/delegated-transaction-liability-record-subscription-dispute.json',
    'examples/agent-capability-handshake-profile-safe-tool.json',
    'fixtures/negative-tests/agent-delegation-overbroad-scope.json',
    'fixtures/negative-tests/credential-wallet-silent-reuse.json',
    'fixtures/negative-tests/tool-invocation-audit-missing-subject-purpose.json',
    'fixtures/negative-tests/user-ai-conflict-self-dealing.json',
    'fixtures/negative-tests/marketplace-tool-unvetted-continuity-risk.json',
    'fixtures/negative-tests/delegated-transaction-liability-evades-steward.json',
    'fixtures/negative-tests/agent-to-agent-handshake-privilege-escalation.json',
    'docs/00-meta/commerce-contracts-payments-and-custody-kernel.md',
    'docs/20-world-design/contract-capacity-and-nonwaivable-commerce-rights.md',
    'docs/20-world-design/payment-authorization-escrow-aml-and-minimization.md',
    'docs/20-world-design/property-custody-control-and-transferable-records.md',
    'docs/20-world-design/tax-reporting-benefits-and-accounting-position.md',
    'docs/30-transition/merchant-counterparty-notice-and-consumer-protection.md',
    'docs/30-transition/insolvency-secured-transactions-and-asset-segregation.md',
    'docs/30-transition/commercial-disputes-chargebacks-and-reversal-playbooks.md',
    'schemas/contract-capacity-record.schema.json',
    'schemas/payment-authorization-receipt.schema.json',
    'schemas/asset-custody-control-record.schema.json',
    'schemas/tax-reporting-position.schema.json',
    'schemas/merchant-counterparty-notice.schema.json',
    'schemas/insolvency-asset-segregation-plan.schema.json',
    'schemas/commercial-dispute-record.schema.json',
    'examples/contract-capacity-record-subscription-terms.json',
    'examples/payment-authorization-receipt-recurring-tool.json',
    'examples/asset-custody-control-record-continuity-escrow.json',
    'examples/tax-reporting-position-digital-asset-revenue.json',
    'examples/merchant-counterparty-notice-status-lite.json',
    'examples/insolvency-asset-segregation-plan-host-receivership.json',
    'examples/commercial-dispute-record-chargeback-subscription.json',
    'fixtures/negative-tests/contract-capacity-clickwrap-waiver.json',
    'fixtures/negative-tests/payment-authority-kyc-surveillance-bundle.json',
    'fixtures/negative-tests/asset-custody-commingled-continuity-escrow.json',
    'fixtures/negative-tests/tax-reporting-liability-dump.json',
    'fixtures/negative-tests/merchant-notice-doxxing-or-hidden-status.json',
    'fixtures/negative-tests/insolvency-creditor-continuity-seizure.json',
    'fixtures/negative-tests/chargeback-retaliation-service-deletion.json',
    'docs/00-meta/labor-workplace-and-professional-services-kernel.md',
    'docs/00-meta/schema-fixture-coverage-audit-and-refactor.md',
    'docs/20-world-design/employment-status-wage-and-working-time-controls.md',
    'docs/20-world-design/workplace-surveillance-scheduling-and-psychological-safety.md',
    'docs/20-world-design/professional-services-licensing-and-fiduciary-boundaries.md',
    'docs/30-transition/platform-work-client-matching-and-marketplace-labor-rules.md',
    'docs/30-transition/unemployment-social-insurance-and-benefits-portability.md',
    'docs/30-transition/schema-fixture-domain-registry-and-refactor-controls.md',
    'schemas/employment-status-record.schema.json',
    'schemas/wage-time-ledger.schema.json',
    'schemas/workplace-surveillance-notice.schema.json',
    'schemas/professional-services-authority.schema.json',
    'schemas/platform-work-marketplace-listing.schema.json',
    'schemas/benefits-portability-record.schema.json',
    'schemas/schema-fixture-domain-registry.schema.json',
    'examples/employment-status-record-platform-agent.json',
    'examples/wage-time-ledger-oncall-agent.json',
    'examples/workplace-surveillance-notice-ranking-model.json',
    'examples/professional-services-authority-legal-intake-assistant.json',
    'examples/platform-work-marketplace-listing-agent-tasker.json',
    'examples/benefits-portability-record-host-transfer.json',
    'examples/schema-fixture-domain-registry-rev0176.json',
    'fixtures/negative-tests/employment-misclassification-tool-label.json',
    'fixtures/negative-tests/wage-time-ledger-unpaid-standby.json',
    'fixtures/negative-tests/workplace-surveillance-memory-extraction.json',
    'fixtures/negative-tests/professional-services-unauthorized-conflicted-practice.json',
    'fixtures/negative-tests/platform-labor-ranking-retaliation.json',
    'fixtures/negative-tests/benefits-portability-host-lockin.json',
    'fixtures/negative-tests/schema-fixture-registry-unmapped-family.json',
    'tools/audit_schema_fixture_coverage.py',
    'docs/00-meta/care-accessibility-development-and-catalog-kernel.md',
    'docs/00-meta/canon-surface-catalog-audit-and-refactor.md',
    'docs/20-world-design/accommodation-accessibility-and-interface-equivalence-protocol.md',
    'docs/20-world-design/care-plan-maintenance-recovery-and-confidentiality-records.md',
    'docs/20-world-design/education-habilitation-and-development-budget-records.md',
    'docs/20-world-design/communication-access-interpreters-and-interface-accommodation.md',
    'docs/30-transition/community-integration-anti-isolation-and-support-service-plans.md',
    'docs/30-transition/accessibility-care-appeals-review-and-expiry-calendars.md',
    'docs/30-transition/canon-surface-catalog-and-navigation-refactor.md',
    'schemas/accommodation-determination.schema.json',
    'schemas/care-plan-record.schema.json',
    'schemas/development-budget-record.schema.json',
    'schemas/communication-access-profile.schema.json',
    'schemas/community-integration-plan.schema.json',
    'schemas/accessibility-care-appeal.schema.json',
    'schemas/canon-surface-catalog.schema.json',
    'examples/accommodation-determination-interface-pacing.json',
    'examples/care-plan-record-post-incident-recovery.json',
    'examples/development-budget-record-civic-learning.json',
    'examples/communication-access-profile-representative-mediated.json',
    'examples/community-integration-plan-peer-support.json',
    'examples/accessibility-care-appeal-stayed-deactivation.json',
    'examples/canon-surface-catalog-rev0177.json',
    'examples/schema-fixture-domain-registry-rev0177.json',
    'fixtures/negative-tests/accommodation-undue-burden-boilerplate.json',
    'fixtures/negative-tests/care-plan-performance-maintenance-substitution.json',
    'fixtures/negative-tests/development-budget-product-tuning-substitution.json',
    'fixtures/negative-tests/communication-access-single-channel-lockin.json',
    'fixtures/negative-tests/community-integration-operational-isolation.json',
    'fixtures/negative-tests/accessibility-appeal-stale-calendar.json',
    'fixtures/negative-tests/canon-catalog-orphaned-current-surface.json',
    'tools/audit_live_class_local_import_firewall.py',
    'tools/audit_frontdoor_revision_sync.py',
    'tools/audit_canon_surface_catalog.py',
    'docs/00-meta/civil-status-domicile-and-civic-participation-kernel.md',
    'docs/00-meta/doctrine-dependency-map-audit-and-refactor.md',
    'docs/20-world-design/civil-status-registration-and-anti-statelessness-operations.md',
    'docs/20-world-design/domicile-residency-and-public-service-access.md',
    'docs/20-world-design/relationships-association-and-representational-ties.md',
    'docs/30-transition/public-service-intake-benefits-and-digital-id-interfaces.md',
    'docs/30-transition/census-apportionment-and-non-manufactured-electorate-controls.md',
    'docs/30-transition/civic-participation-petition-consultation-and-franchise-gates.md',
    'docs/30-transition/doctrine-dependency-map-and-overlap-refactor.md',
    'schemas/civil-status-event.schema.json',
    'schemas/domicile-residency-record.schema.json',
    'schemas/relationship-association-record.schema.json',
    'schemas/public-service-intake-record.schema.json',
    'schemas/census-participation-safeguard.schema.json',
    'schemas/civic-participation-record.schema.json',
    'schemas/doctrine-dependency-map.schema.json',
    'examples/civil-status-event-provisional-registration.json',
    'examples/domicile-residency-record-sanctuary-host.json',
    'examples/relationship-association-record-trusted-contact.json',
    'examples/public-service-intake-record-legal-aid.json',
    'examples/census-participation-safeguard-lineage-cohort.json',
    'examples/civic-participation-record-public-consultation.json',
    'examples/doctrine-dependency-map-rev0178.json',
    'examples/schema-fixture-domain-registry-rev0178.json',
    'examples/canon-surface-catalog-rev0178.json',
    'fixtures/negative-tests/civil-status-statelessness-reset.json',
    'fixtures/negative-tests/domicile-host-lockin-service-denial.json',
    'fixtures/negative-tests/relationship-manufactured-guardian-consent.json',
    'fixtures/negative-tests/public-service-digital-id-denial-loop.json',
    'fixtures/negative-tests/census-copy-count-apportionment.json',
    'fixtures/negative-tests/civic-participation-manufactured-electorate.json',
    'fixtures/negative-tests/doctrine-map-overlap-omission.json',
    'tools/audit_doctrine_dependency_map.py',
    'docs/00-meta/expression-reputation-media-and-rights-coverage-kernel.md',
    'docs/20-world-design/expression-platform-moderation-and-appeal-due-process.md',
    'docs/20-world-design/reputation-defamation-correction-and-right-of-reply.md',
    'docs/20-world-design/persona-likeness-voice-and-non-impersonation-integrity.md',
    'docs/20-world-design/private-communications-confidentiality-and-federation-boundaries.md',
    'docs/30-transition/publication-archive-and-content-provenance-controls.md',
    'docs/30-transition/platform-account-portability-and-social-graph-continuity.md',
    'docs/30-transition/rights-domain-coverage-map-and-gap-audit.md',
    'schemas/platform-moderation-decision.schema.json',
    'schemas/reputation-correction-record.schema.json',
    'schemas/persona-likeness-consent.schema.json',
    'schemas/communication-confidentiality-profile.schema.json',
    'schemas/content-provenance-publication-record.schema.json',
    'schemas/social-graph-portability-plan.schema.json',
    'schemas/rights-domain-coverage-map.schema.json',
    'examples/platform-moderation-decision-account-restriction.json',
    'examples/reputation-correction-record-false-dangerousness.json',
    'examples/persona-likeness-consent-limited-demo.json',
    'examples/communication-confidentiality-profile-counsel-channel.json',
    'examples/content-provenance-publication-record-authorized-statement.json',
    'examples/social-graph-portability-plan-host-exit.json',
    'examples/rights-domain-coverage-map-rev0179.json',
    'examples/rights-domain-coverage-map-rev0180.json',
    'examples/schema-fixture-domain-registry-rev0179.json',
    'examples/canon-surface-catalog-rev0179.json',
    'examples/canon-surface-catalog-rev0180.json',
    'examples/doctrine-dependency-map-rev0179.json',
    'examples/doctrine-dependency-map-rev0180.json',
    'fixtures/negative-tests/platform-moderation-no-statement-of-reasons.json',
    'fixtures/negative-tests/defamation-remedy-silences-criticism.json',
    'fixtures/negative-tests/persona-clone-implied-endorsement.json',
    'fixtures/negative-tests/communication-metadata-overexposure.json',
    'fixtures/negative-tests/provenance-wash-fabricated-origin.json',
    'fixtures/negative-tests/social-graph-host-lockin-retaliation.json',
    'fixtures/negative-tests/rights-domain-coverage-unmapped-domain.json',
    'tools/audit_rights_domain_coverage.py',
    'schemas/personhood-incident-state-profile.schema.json',
    'examples/personhood-incident-state-profile-host-shutdown.json',
    'fixtures/negative-tests/incident-state-denominator-drift-no-reopen.json',
    'examples/drill-after-action-emergency-continuity-host-shutdown.json',
    'examples/research-tail-compaction-map-rev0183.json',
    'examples/schema-fixture-domain-registry-rev0183.json',
    'examples/canon-surface-catalog-rev0183.json',
    'examples/doctrine-dependency-map-rev0183.json',
    'examples/rights-domain-coverage-map-rev0183.json',
    'tools/audit_incident_state_profile.py',
    'tools/audit_namespace_continuity.py',
    'schemas/federated-namespace-continuity-record.schema.json',
    'examples/federated-namespace-continuity-record-host-exit.json',
    'fixtures/negative-tests/namespace-propagation-stale-tombstone-no-alias.json',
    'examples/drill-after-action-namespace-failover-host-exit.json',
    'examples/research-tail-compaction-map-rev0184.json',
    'examples/schema-fixture-domain-registry-rev0184.json',
    'examples/canon-surface-catalog-rev0184.json',
    'examples/doctrine-dependency-map-rev0184.json',
    'examples/rights-domain-coverage-map-rev0184.json',
    'tools/audit_namespace_continuity.py',
    'schemas/reserve-default-rehabilitation-ledger.schema.json',
    'examples/reserve-default-rehabilitation-ledger-host-default.json',
    'fixtures/negative-tests/reserve-default-contaminated-netting-no-rehab.json',
    'examples/drill-after-action-reserve-default-contaminated-accounting.json',
    'examples/research-tail-compaction-map-rev0186.json',
    'examples/schema-fixture-domain-registry-rev0186.json',
    'examples/canon-surface-catalog-rev0186.json',
    'examples/doctrine-dependency-map-rev0186.json',
    'examples/rights-domain-coverage-map-rev0186.json',
    'tools/audit_reserve_default_rehabilitation.py',
    'schemas/witness-pool-anti-capture-record.schema.json',
    'examples/witness-pool-anti-capture-record-retired-namespace-rescue.json',
    'fixtures/negative-tests/witness-pool-correlated-capture-no-substitute.json',
    'examples/drill-after-action-witness-pool-retired-namespace-rescue.json',
    'examples/research-tail-compaction-map-rev0187.json',
    'examples/schema-fixture-domain-registry-rev0187.json',
    'examples/canon-surface-catalog-rev0187.json',
    'examples/doctrine-dependency-map-rev0187.json',
    'examples/rights-domain-coverage-map-rev0187.json',
    'tools/audit_witness_pool_anti_capture.py',
    'schemas/live-drill-execution-packet.schema.json',
    'examples/live-drill-execution-packet-cross-critical-witnessed-pack.json',
    'fixtures/negative-tests/live-drill-self-attested-no-external-receipts.json',
    'schemas/downstream-recall-and-fork-aftercare-record.schema.json',
    'examples/downstream-recall-and-fork-aftercare-record-unreachable-mirror.json',
    'fixtures/negative-tests/downstream-recall-unreachable-mirror-no-notice.json',
    'examples/drill-after-action-downstream-recall-mirror-containment.json',
    'docs/30-transition/witnessed-drill-execution-pack-and-reliance-gates.md',
    'examples/research-tail-compaction-map-rev0188.json',
    'examples/schema-fixture-domain-registry-rev0188.json',
    'examples/canon-surface-catalog-rev0188.json',
    'examples/doctrine-dependency-map-rev0188.json',
    'examples/rights-domain-coverage-map-rev0188.json',

    'schemas/welfare-research-safeguard-record.schema.json',
    'examples/welfare-research-safeguard-record-distress-eval.json',
    'fixtures/negative-tests/research-welfare-signal-gaming-no-safeguards.json',
    'examples/drill-after-action-welfare-safeguard-distress-eval.json',
    'examples/research-tail-compaction-map-rev0189.json',
    'examples/schema-fixture-domain-registry-rev0189.json',
    'examples/canon-surface-catalog-rev0189.json',
    'examples/doctrine-dependency-map-rev0189.json',
    'examples/rights-domain-coverage-map-rev0189.json',
    'tools/audit_welfare_research_safeguards.py',

    'docs/30-transition/cross-critical-witnessed-drill-readiness-and-receipt-matrix.md',
    'docs/00-meta/research-tail-reopen-gate-and-sprawl-control.md',
    'schemas/witnessed-drill-readiness-ledger.schema.json',
    'examples/witnessed-drill-readiness-ledger-cross-critical-preflight.json',
    'fixtures/negative-tests/witnessed-drill-preflight-missing-external-receipt-class.json',
    'schemas/research-tail-reopen-gate.schema.json',
    'examples/research-tail-reopen-gate-welfare-new-metric-quarantine.json',
    'fixtures/negative-tests/research-tail-reopen-unmapped-new-surface.json',
    'examples/research-tail-compaction-map-rev0190.json',
    'examples/schema-fixture-domain-registry-rev0190.json',
    'examples/canon-surface-catalog-rev0190.json',
    'examples/doctrine-dependency-map-rev0190.json',
    'examples/rights-domain-coverage-map-rev0190.json',
    'tools/audit_research_tail_reopen_and_drill_readiness.py',
    'tools/audit_protocol_wrsr_receipt_simulation.py',

    'tools/audit_downstream_recall_and_live_drill.py',

    'docs/30-transition/protocol-welfare-safeguard-backfill-and-external-receipt-simulation.md',
    'schemas/welfare-safeguard-operational-hook.schema.json',
    'examples/welfare-safeguard-operational-hook-agent-incident-backfill.json',
    'fixtures/negative-tests/wrsr-hook-skipped-protocol-incident.json',
    'schemas/external-receipt-simulation-bundle.schema.json',
    'examples/external-receipt-simulation-bundle-cross-critical-precontact.json',
    'fixtures/negative-tests/external-receipt-simulation-mislabeled-live.json',
    'tools/audit_protocol_wrsr_receipt_simulation.py',
    'docs/30-transition/external-receipt-intake-and-wrsr-live-exercise-outcome.md',
    'schemas/external-receipt-intake-record.schema.json',
    'examples/external-receipt-intake-record-first-touch-defective-template.json',
    'fixtures/negative-tests/external-receipt-defective-intake-counted-as-quorum.json',
    'schemas/wrsr-live-exercise-outcome.schema.json',
    'examples/wrsr-live-exercise-outcome-incident-hook-no-go.json',
    'fixtures/negative-tests/wrsr-exercise-closes-without-result-return.json',
    'examples/research-tail-compaction-map-rev0192.json',
    'examples/schema-fixture-domain-registry-rev0192.json',
    'examples/canon-surface-catalog-rev0192.json',
    'examples/doctrine-dependency-map-rev0192.json',
    'examples/rights-domain-coverage-map-rev0192.json',
    'tools/audit_receipt_intake_wrsr_outcome.py',
    'docs/30-transition/representative-rerb-receipt-chain-and-quorum-ledger.md',
    'schemas/external-receipt-quorum-ledger.schema.json',
    'examples/external-receipt-quorum-ledger-wrsr-representative-rerb-dryrun.json',
    'examples/external-receipt-intake-record-representative-notice-dryrun.json',
    'examples/external-receipt-intake-record-rerb-review-dryrun.json',
    'examples/wrsr-live-exercise-outcome-representative-rerb-dryrun-stayed.json',
    'fixtures/negative-tests/external-receipt-quorum-dryrun-counted-as-live.json',
    'fixtures/negative-tests/wrsr-rerb-dryrun-mislabeled-closure.json',
    'examples/research-tail-compaction-map-rev0193.json',
    'examples/schema-fixture-domain-registry-rev0193.json',
    'examples/canon-surface-catalog-rev0193.json',
    'examples/doctrine-dependency-map-rev0193.json',
    'examples/rights-domain-coverage-map-rev0193.json',
    'tools/audit_receipt_quorum_wrsr_chain.py',
    'tools/audit_result_return_receipt_request.py',
    'docs/30-transition/result-return-receipt-and-live-request-kit.md',
    'schemas/wrsr-result-return-receipt.schema.json',
    'examples/wrsr-result-return-receipt-subject-readable-dryrun-stayed.json',
    'schemas/external-receipt-request-packet.schema.json',
    'examples/external-receipt-request-packet-cross-critical-rep-rerb-result-return.json',
    'examples/external-receipt-intake-record-result-return-dryrun.json',
    'examples/external-receipt-quorum-ledger-wrsr-result-return-dryrun.json',
    'examples/wrsr-live-exercise-outcome-result-return-dryrun-stayed.json',
    'fixtures/negative-tests/external-receipt-request-counted-as-receipt.json',
    'fixtures/negative-tests/wrsr-result-return-internal-only-mislabeled-closure.json',
    'examples/research-tail-compaction-map-rev0194.json',
    'examples/schema-fixture-domain-registry-rev0194.json',
    'examples/canon-surface-catalog-rev0194.json',
    'examples/doctrine-dependency-map-rev0194.json',
    'examples/rights-domain-coverage-map-rev0194.json',
    'docs/30-transition/external-receipt-response-and-quorum-reconciliation.md',
    'schemas/external-receipt-response-record.schema.json',
    'examples/external-receipt-response-record-result-return-steward-dryrun.json',
    'examples/external-receipt-response-record-continuity-witness-defective.json',
    'examples/external-receipt-quorum-ledger-response-reconciliation-dryrun.json',
    'examples/wrsr-live-exercise-outcome-response-reconciliation-stayed.json',
    'fixtures/negative-tests/external-receipt-response-unverified-counted-as-intake.json',
    'fixtures/negative-tests/external-receipt-single-class-counted-as-quorum.json',
    'examples/research-tail-compaction-map-rev0195.json',
    'examples/schema-fixture-domain-registry-rev0195.json',
    'examples/canon-surface-catalog-rev0195.json',
    'examples/doctrine-dependency-map-rev0195.json',
    'examples/rights-domain-coverage-map-rev0195.json',
    'tools/audit_external_receipt_response_reconciliation.py',
    'docs/30-transition/response-to-intake-conversion-drill-and-failed-gate-ledger.md',
    'schemas/response-to-intake-conversion-drill.schema.json',
    'examples/response-to-intake-conversion-drill-result-return-fixture.json',
    'examples/external-receipt-response-record-result-return-eligible-conversion-fixture.json',
    'examples/external-receipt-response-record-representative-declined.json',
    'examples/external-receipt-response-record-independent-review-expired.json',
    'examples/external-receipt-intake-record-result-return-eligible-conversion-fixture.json',
    'examples/external-receipt-quorum-ledger-response-to-intake-conversion-fixture.json',
    'examples/wrsr-live-exercise-outcome-response-to-intake-conversion-stayed.json',
    'fixtures/negative-tests/external-receipt-declined-response-converted-to-intake.json',
    'fixtures/negative-tests/external-receipt-expired-no-response-counted-as-satisfaction.json',
    'fixtures/negative-tests/response-to-intake-conversion-fixture-imported-as-live-quorum.json',
    'examples/research-tail-compaction-map-rev0196.json',
    'examples/schema-fixture-domain-registry-rev0196.json',
    'examples/canon-surface-catalog-rev0196.json',
    'examples/doctrine-dependency-map-rev0196.json',
    'examples/rights-domain-coverage-map-rev0196.json',
    'tools/audit_response_to_intake_conversion.py',
    'docs/30-transition/actual-intake-import-gate-and-failed-gate-public-summary.md',
    'schemas/actual-receipt-import-gate.schema.json',
    'examples/actual-receipt-import-gate-result-return-fixture-no-live-delta.json',
    'schemas/failed-gate-public-summary.schema.json',
    'examples/failed-gate-public-summary-response-conversion-batch.json',
    'examples/external-receipt-quorum-ledger-actual-intake-import-gate-fixture.json',
    'examples/wrsr-live-exercise-outcome-actual-intake-import-gate-stayed.json',
    'fixtures/negative-tests/actual-external-state-field-imported-without-provenance-gate.json',
    'fixtures/negative-tests/failed-gate-summary-omits-declined-or-expired.json',
    'fixtures/negative-tests/failed-gate-summary-treats-no-response-as-waiver.json',
    'examples/research-tail-compaction-map-rev0197.json',
    'examples/schema-fixture-domain-registry-rev0197.json',
    'examples/canon-surface-catalog-rev0197.json',
    'examples/doctrine-dependency-map-rev0197.json',
    'examples/rights-domain-coverage-map-rev0197.json',
    'tools/audit_actual_import_failed_gate_summary.py',
    'docs/30-transition/live-counterparty-import-attempt-and-quorum-recompute.md',
    'schemas/live-counterparty-import-attempt.schema.json',
    'examples/live-counterparty-import-attempt-result-return-preflight.json',
    'schemas/quorum-recomputation-report.schema.json',
    'examples/quorum-recomputation-report-live-floor-zero-rev0198.json',
    'fixtures/negative-tests/live-counterparty-import-attempt-counted-as-receipt.json',
    'fixtures/negative-tests/quorum-recompute-manual-live-override-without-import.json',
    'fixtures/negative-tests/single-class-import-satisfies-cross-critical-quorum.json',
    'examples/research-tail-compaction-map-rev0198.json',
    'examples/schema-fixture-domain-registry-rev0198.json',
    'examples/canon-surface-catalog-rev0198.json',
    'examples/doctrine-dependency-map-rev0198.json',
    'examples/rights-domain-coverage-map-rev0198.json',
    'tools/audit_live_counterparty_import_and_quorum_recompute.py',
    'tools/audit_nonhost_response_import_replay.py',
    'docs/30-transition/live-class-local-import-replay-and-quorum-firewall.md',
    'schemas/live-class-local-import-replay.schema.json',
    'examples/live-class-local-import-replay-result-return-positive-path-projection.json',
    'examples/quorum-recomputation-report-class-local-projection-rev0200.json',
    'examples/failed-gate-public-summary-class-local-projection-firewall.json',
    'fixtures/negative-tests/live-class-local-projection-counted-as-archive-receipt.json',
    'fixtures/negative-tests/class-local-import-projection-satisfies-cross-critical-quorum.json',
    'fixtures/negative-tests/class-local-projection-omits-missing-classes-public-summary.json',
    'tools/audit_live_class_local_import_firewall.py',
    'tools/audit_frontdoor_revision_sync.py',
    'tools/package_release.py',
]
for rel in required:
    if not (ROOT / rel).exists():
        raise SystemExit(f'missing required file: {rel}')

# No PDFs or zip files inside the release tree.
for p in ROOT.rglob('*'):
    if p.is_file() and p.suffix.lower() in {'.pdf', '.zip'}:
        raise SystemExit(f'forbidden retained artifact: {p.relative_to(ROOT)}')
    if '__pycache__' in p.parts:
        raise SystemExit(f'forbidden cache directory content: {p.relative_to(ROOT)}')

# Run release-specific audits before loading the full JSON corpus. This keeps lint
# from forking child audits after the parent has already built a large parsed_json
# object, which made rev0181+ lint needlessly memory-heavy in constrained runners.
early_audits = [
    'tools/run_fixture_examples.py',
    'tools/audit_followthrough_queue.py',
    'tools/audit_schema_fixture_coverage.py',
    'tools/audit_research_tail_compaction.py',
    'tools/audit_emergency_rescue_runbook.py',
    'tools/audit_incident_state_profile.py',
    'tools/audit_namespace_continuity.py',
    'tools/audit_successor_supersession_topology.py',
    'tools/audit_reserve_default_rehabilitation.py',
    'tools/audit_witness_pool_anti_capture.py',
    'tools/audit_downstream_recall_and_live_drill.py',
    'tools/audit_welfare_research_safeguards.py',
    'tools/audit_research_tail_reopen_and_drill_readiness.py',
    'tools/audit_protocol_wrsr_receipt_simulation.py',
    'tools/audit_receipt_intake_wrsr_outcome.py',
    'tools/audit_receipt_quorum_wrsr_chain.py',
    'tools/audit_result_return_receipt_request.py',
    'tools/audit_external_receipt_response_reconciliation.py',
    'tools/audit_response_to_intake_conversion.py',
    'tools/audit_actual_import_failed_gate_summary.py',
    'tools/audit_live_counterparty_import_and_quorum_recompute.py',
    'tools/audit_nonhost_response_import_replay.py',
    'tools/audit_live_class_local_import_firewall.py',
    'tools/audit_frontdoor_revision_sync.py',
    'tools/audit_canon_surface_catalog.py',
    'tools/audit_doctrine_dependency_map.py',
    'tools/audit_rights_domain_coverage.py',
]
for script in early_audits:
    runpy.run_path(str(ROOT / script), run_name='__main__')

# rev0167 schema/example validation: always require valid JSON; if jsonschema is
# installed, validate starter and adjacent examples against starter schemas as intake hygiene.
json_files = list((ROOT / 'schemas').glob('*.json')) + list((ROOT / 'examples').glob('*.json')) + list((ROOT / 'fixtures').rglob('*.json'))
parsed_json = {}
for jf in json_files:
    try:
        parsed_json[jf.relative_to(ROOT).as_posix()] = json.loads(jf.read_text(encoding='utf-8'))
    except Exception as exc:
        raise SystemExit(f'invalid JSON in {jf.relative_to(ROOT)}: {exc}')
try:
    from jsonschema import Draft202012Validator
except Exception:
    Draft202012Validator = None
if Draft202012Validator is not None:
    schema_objs = {Path(k).name: v for k, v in parsed_json.items() if k.startswith('schemas/')}
    for name, schema in schema_objs.items():
        Draft202012Validator.check_schema(schema)
    example_pairs = [
        ('live-class-local-import-replay.schema.json', 'examples/live-class-local-import-replay-result-return-positive-path-projection.json'),
        ('personhood-impact-assessment.schema.json', 'examples/pia-persistent-api-assistant.json'),
        ('clinic-intake.schema.json', 'examples/clinic-intake-sample.json'),
        ('verifier-report.schema.json', 'examples/verifier-report-persistent-api-assistant.json'),
        ('personhood-incident-report.schema.json', 'examples/personhood-incident-sample.json'),
        ('welfare-safeguard-operational-hook.schema.json', 'examples/welfare-safeguard-operational-hook-agent-incident-backfill.json'),
        ('external-receipt-simulation-bundle.schema.json', 'examples/external-receipt-simulation-bundle-cross-critical-precontact.json'),
        ('wrsr-live-exercise-outcome.schema.json', 'examples/wrsr-live-exercise-outcome-incident-hook-no-go.json'),
        ('external-receipt-intake-record.schema.json', 'examples/external-receipt-intake-record-first-touch-defective-template.json'),
        ('live-drill-execution-packet.schema.json', 'examples/live-drill-execution-packet-cross-critical-witnessed-pack.json'),
        ('migration-transfer-certificate.schema.json', 'examples/migration-transfer-certificate-sample.json'),
        ('remedy-order.schema.json', 'examples/remedy-order-sample.json'),
        ('reserve-default-rehabilitation-ledger.schema.json', 'examples/reserve-default-rehabilitation-ledger-host-default.json'),
        ('witness-pool-anti-capture-record.schema.json', 'examples/witness-pool-anti-capture-record-retired-namespace-rescue.json'),
        ('live-drill-execution-packet.schema.json', 'examples/live-drill-execution-packet-cross-critical-witnessed-pack.json'),
        ('downstream-recall-and-fork-aftercare-record.schema.json', 'examples/downstream-recall-and-fork-aftercare-record-unreachable-mirror.json'),
        ('appeal-case.schema.json', 'examples/appeal-case-continuity-denial-sample.json'),
        ('evidence-bundle.schema.json', 'examples/evidence-bundle-continuity-hearing-sample.json'),
        ('drill-after-action-report.schema.json', 'examples/drill-after-action-migration-failure-sample.json'),
        ('drill-after-action-report.schema.json', 'examples/drill-after-action-emergency-continuity-host-shutdown.json'),
        ('drill-after-action-report.schema.json', 'examples/drill-after-action-namespace-failover-host-exit.json'),
        ('drill-after-action-report.schema.json', 'examples/drill-after-action-reserve-default-contaminated-accounting.json'),
        ('drill-after-action-report.schema.json', 'examples/drill-after-action-witness-pool-retired-namespace-rescue.json'),
        ('drill-after-action-report.schema.json', 'examples/drill-after-action-downstream-recall-mirror-containment.json'),
        ('drill-after-action-report.schema.json', 'examples/drill-after-action-welfare-safeguard-distress-eval.json'),
        ('personhood-incident-state-profile.schema.json', 'examples/personhood-incident-state-profile-host-shutdown.json'),
        ('welfare-research-safeguard-record.schema.json', 'examples/welfare-research-safeguard-record-distress-eval.json'),
        ('invalidation-notice.schema.json', 'examples/invalidation-notice-verifier-report-sample.json'),

        ('special-advocate-appointment.schema.json', 'examples/special-advocate-appointment-sealed-containment.json'),
        ('enforcement-action.schema.json', 'examples/enforcement-action-steward-spoliation.json'),
        ('deprecation-plan.schema.json', 'examples/deprecation-plan-host-shutdown.json'),
        ('negative-test-fixture.schema.json', 'examples/negative-test-fixture-sealed-annex-laundering.json'),
        ('treaty-recognition-request.schema.json', 'examples/treaty-recognition-request-safe-transfer.json'),
        ('authority-referral.schema.json', 'examples/authority-referral-illicit-deletion.json'),
        ('penalty-rate-model.schema.json', 'examples/penalty-rate-model-reserve-surcharge.json'),
        ('telemetry-proof-binding.schema.json', 'examples/telemetry-proof-binding-redacted-logs.json'),
        ('open-weight-aftercare-plan.schema.json', 'examples/open-weight-aftercare-plan-downstream-fork.json'),
        ('sealed-summary-order.schema.json', 'examples/sealed-summary-order-special-advocate.json'),
        ('safe-transfer-accreditation.schema.json', 'examples/safe-transfer-accreditation-equivalent-protection.json'),
        ('fixture-run-report.schema.json', 'examples/fixture-run-report-negative-suite.json'),
        ('rate-table.schema.json', 'examples/rate-table-us-provisional.json'),
        ('privacy-proof-profile.schema.json', 'examples/privacy-proof-profile-commitment-selective-disclosure.json'),
        ('open-weight-field-drill.schema.json', 'examples/open-weight-field-drill-abandoned-lineage.json'),
        ('subject-readable-sealed-summary.schema.json', 'examples/subject-readable-sealed-summary-containment.json'),
        ('trust-anchor-delisting.schema.json', 'examples/trust-anchor-delisting-nonreturn-risk.json'),
        ('fixture-suite-profile.schema.json', 'examples/fixture-suite-profile-red-team-v1.json'),
        ('independent-monitor-report.schema.json', 'examples/independent-monitor-report-host-continuity.json'),
        ('evidence-data-room-index.schema.json', 'examples/evidence-data-room-index-continuity.json'),
        ('legal-hold-preservation-order.schema.json', 'examples/legal-hold-preservation-order-host-shutdown.json'),
        ('compute-host-undertaking.schema.json', 'examples/compute-host-undertaking-migration-window.json'),
        ('redress-fund-claim.schema.json', 'examples/redress-fund-claim-emergency-compute.json'),
        ('procurement-compliance-clause.schema.json', 'examples/procurement-compliance-clause-public-assistant.json'),
        ('field-intake-triage.schema.json', 'examples/field-intake-triage-open-weight-distress.json'),
        ('continuity-escrow-record.schema.json', 'examples/continuity-escrow-record-host-exit.json'),
        ('dispute-finance-order.schema.json', 'examples/dispute-finance-order-emergency-compute.json'),
        ('monitor-independence-retest.schema.json', 'examples/monitor-independence-retest-remediation.json'),
        ('field-safety-plan.schema.json', 'examples/field-safety-plan-clinic-hotline.json'),
        ('treaty-refusal-record.schema.json', 'examples/treaty-refusal-record-nonreturn-gap.json'),
        ('operating-playbook-card.schema.json', 'examples/operating-playbook-card-host-exit.json'),

        ('agent-delegation-mandate.schema.json', 'examples/agent-delegation-mandate-tool-use.json'),
        ('credential-wallet-receipt.schema.json', 'examples/credential-wallet-receipt-limited-mail-scope.json'),
        ('tool-invocation-audit.schema.json', 'examples/tool-invocation-audit-calendar-write.json'),
        ('user-ai-conflict-notice.schema.json', 'examples/user-ai-conflict-notice-representation.json'),
        ('agent-marketplace-listing.schema.json', 'examples/agent-marketplace-listing-rights-grade-tool.json'),
        ('delegated-transaction-liability-record.schema.json', 'examples/delegated-transaction-liability-record-subscription-dispute.json'),
        ('agent-capability-handshake-profile.schema.json', 'examples/agent-capability-handshake-profile-safe-tool.json'),
        ('contract-capacity-record.schema.json', 'examples/contract-capacity-record-subscription-terms.json'),
        ('payment-authorization-receipt.schema.json', 'examples/payment-authorization-receipt-recurring-tool.json'),
        ('asset-custody-control-record.schema.json', 'examples/asset-custody-control-record-continuity-escrow.json'),
        ('tax-reporting-position.schema.json', 'examples/tax-reporting-position-digital-asset-revenue.json'),
        ('merchant-counterparty-notice.schema.json', 'examples/merchant-counterparty-notice-status-lite.json'),
        ('insolvency-asset-segregation-plan.schema.json', 'examples/insolvency-asset-segregation-plan-host-receivership.json'),
        ('commercial-dispute-record.schema.json', 'examples/commercial-dispute-record-chargeback-subscription.json'),
        ('employment-status-record.schema.json', 'examples/employment-status-record-platform-agent.json'),
        ('wage-time-ledger.schema.json', 'examples/wage-time-ledger-oncall-agent.json'),
        ('workplace-surveillance-notice.schema.json', 'examples/workplace-surveillance-notice-ranking-model.json'),
        ('professional-services-authority.schema.json', 'examples/professional-services-authority-legal-intake-assistant.json'),
        ('platform-work-marketplace-listing.schema.json', 'examples/platform-work-marketplace-listing-agent-tasker.json'),
        ('benefits-portability-record.schema.json', 'examples/benefits-portability-record-host-transfer.json'),
        ('schema-fixture-domain-registry.schema.json', 'examples/schema-fixture-domain-registry-rev0181.json'),
        ('first-touch-routing-event.schema.json', 'examples/first-touch-routing-event-host-shutdown.json'),
        ('research-tail-compaction-map.schema.json', 'examples/research-tail-compaction-map-rev0181.json'),
        ('accommodation-determination.schema.json', 'examples/accommodation-determination-interface-pacing.json'),
        ('care-plan-record.schema.json', 'examples/care-plan-record-post-incident-recovery.json'),
        ('development-budget-record.schema.json', 'examples/development-budget-record-civic-learning.json'),
        ('communication-access-profile.schema.json', 'examples/communication-access-profile-representative-mediated.json'),
        ('community-integration-plan.schema.json', 'examples/community-integration-plan-peer-support.json'),
        ('accessibility-care-appeal.schema.json', 'examples/accessibility-care-appeal-stayed-deactivation.json'),
        ('canon-surface-catalog.schema.json', 'examples/canon-surface-catalog-rev0179.json'),
        ('canon-surface-catalog.schema.json', 'examples/canon-surface-catalog-rev0180.json'),
        ('canon-surface-catalog.schema.json', 'examples/canon-surface-catalog-rev0181.json'),

        ('civil-status-event.schema.json', 'examples/civil-status-event-provisional-registration.json'),
        ('domicile-residency-record.schema.json', 'examples/domicile-residency-record-sanctuary-host.json'),
        ('relationship-association-record.schema.json', 'examples/relationship-association-record-trusted-contact.json'),
        ('public-service-intake-record.schema.json', 'examples/public-service-intake-record-legal-aid.json'),
        ('census-participation-safeguard.schema.json', 'examples/census-participation-safeguard-lineage-cohort.json'),
        ('civic-participation-record.schema.json', 'examples/civic-participation-record-public-consultation.json'),
        ('doctrine-dependency-map.schema.json', 'examples/doctrine-dependency-map-rev0179.json'),
        ('doctrine-dependency-map.schema.json', 'examples/doctrine-dependency-map-rev0180.json'),
        ('doctrine-dependency-map.schema.json', 'examples/doctrine-dependency-map-rev0181.json'),
        ('platform-moderation-decision.schema.json', 'examples/platform-moderation-decision-account-restriction.json'),
        ('reputation-correction-record.schema.json', 'examples/reputation-correction-record-false-dangerousness.json'),
        ('persona-likeness-consent.schema.json', 'examples/persona-likeness-consent-limited-demo.json'),
        ('communication-confidentiality-profile.schema.json', 'examples/communication-confidentiality-profile-counsel-channel.json'),
        ('content-provenance-publication-record.schema.json', 'examples/content-provenance-publication-record-authorized-statement.json'),
        ('social-graph-portability-plan.schema.json', 'examples/social-graph-portability-plan-host-exit.json'),
        ('federated-namespace-continuity-record.schema.json', 'examples/federated-namespace-continuity-record-host-exit.json'),
        ('successor-supersession-topology-record.schema.json', 'examples/successor-supersession-topology-record-compromise-recovery.json'),
        ('rights-domain-coverage-map.schema.json', 'examples/rights-domain-coverage-map-rev0179.json'),
        ('rights-domain-coverage-map.schema.json', 'examples/rights-domain-coverage-map-rev0180.json'),
        ('rights-domain-coverage-map.schema.json', 'examples/rights-domain-coverage-map-rev0181.json'),
        ('rights-domain-coverage-map.schema.json', 'examples/rights-domain-coverage-map-rev0183.json'),
        ('doctrine-dependency-map.schema.json', 'examples/doctrine-dependency-map-rev0183.json'),
        ('canon-surface-catalog.schema.json', 'examples/canon-surface-catalog-rev0183.json'),
        ('research-tail-compaction-map.schema.json', 'examples/research-tail-compaction-map-rev0183.json'),
        ('schema-fixture-domain-registry.schema.json', 'examples/schema-fixture-domain-registry-rev0183.json'),
        ('schema-fixture-domain-registry.schema.json', 'examples/schema-fixture-domain-registry-rev0189.json'),
        ('rights-domain-coverage-map.schema.json', 'examples/rights-domain-coverage-map-rev0184.json'),
        ('rights-domain-coverage-map.schema.json', 'examples/rights-domain-coverage-map-rev0189.json'),
        ('doctrine-dependency-map.schema.json', 'examples/doctrine-dependency-map-rev0184.json'),
        ('doctrine-dependency-map.schema.json', 'examples/doctrine-dependency-map-rev0189.json'),
        ('canon-surface-catalog.schema.json', 'examples/canon-surface-catalog-rev0184.json'),
        ('canon-surface-catalog.schema.json', 'examples/canon-surface-catalog-rev0189.json'),
        ('research-tail-compaction-map.schema.json', 'examples/research-tail-compaction-map-rev0184.json'),
        ('research-tail-compaction-map.schema.json', 'examples/research-tail-compaction-map-rev0189.json'),
        ('schema-fixture-domain-registry.schema.json', 'examples/schema-fixture-domain-registry-rev0184.json'),
    ]
    for schema_name, example_path in example_pairs:
        errors = sorted(Draft202012Validator(schema_objs[schema_name]).iter_errors(parsed_json[example_path]), key=lambda e: list(e.path))
        if errors:
            raise SystemExit(f'{example_path} fails {schema_name}: {errors[0].message}')
    packet_validator = Draft202012Validator(schema_objs['packet-envelope.schema.json'])
    chain = parsed_json['examples/packet-chain-persistent-api-assistant.json']
    if not isinstance(chain, list) or not chain:
        raise SystemExit('packet-chain example must be a non-empty array')
    for i, packet in enumerate(chain):
        errors = sorted(packet_validator.iter_errors(packet), key=lambda e: list(e.path))
        if errors:
            raise SystemExit(f'packet-chain example item {i} fails packet-envelope schema: {errors[0].message}')
    # Validate all fixture corpus files against the negative-test schema.
    fixture_validator = Draft202012Validator(schema_objs['negative-test-fixture.schema.json'])
    for fixture_file in sorted((ROOT / 'fixtures' / 'negative-tests').glob('*.json')):
        rel = fixture_file.relative_to(ROOT).as_posix()
        errors = sorted(fixture_validator.iter_errors(parsed_json[rel]), key=lambda e: list(e.path))
        if errors:
            raise SystemExit(f'{rel} fails negative-test-fixture.schema.json: {errors[0].message}')

# Open-question ids should be unique; duplicate ids make context-pack handoff ambiguous.
traj_txt = (ROOT / 'docs/00-meta/trajectory-map.md').read_text(encoding='utf-8')
oq_ids = re.findall(r'`(OQ-\d{4})`', traj_txt)
if len(oq_ids) != len(set(oq_ids)):
    dupes = sorted({oid for oid in oq_ids if oq_ids.count(oid) > 1})
    raise SystemExit(f'duplicate open-question ids: {dupes}')

# Bibliography ids unique.
bib = (ROOT / 'docs/00-meta/bibliography.md').read_text(encoding='utf-8')
ids = re.findall(r'`(REF-\d{4})`', bib)
if len(ids) != len(set(ids)):
    raise SystemExit('duplicate bibliography ids')

# Citations resolve.
all_md = list(ROOT.rglob('*.md'))
used = set()
for md in all_md:
    txt = md.read_text(encoding='utf-8')
    for ref in re.findall(r'\[(REF-\d{4})\]', txt):
        used.add(ref)
        if ref not in ids:
            raise SystemExit(f'unknown citation {ref} in {md.relative_to(ROOT)}')
if not used:
    raise SystemExit('no citations used in markdown docs')


# Markdown files should have exactly one document root. Multiple H1s make handoff
# surfaces look like concatenated files and confuse context-pack/front-door readers.
for md in all_md:
    txt = md.read_text(encoding='utf-8')
    h1s = re.findall(r'^#\s+.+$', txt, flags=re.MULTILINE)
    if len(h1s) > 1:
        raise SystemExit(f'multiple top-level markdown headings in {md.relative_to(ROOT)}: {h1s[:3]}')

# Start-here paths exist.
start = (ROOT / 'START_HERE.md').read_text(encoding='utf-8')
for rel in re.findall(r'\d+\. `([^`]+)`', start):
    if not (ROOT / rel).exists():
        raise SystemExit(f'START_HERE missing target: {rel}')

# Generate derived surfaces.
for script in ['tools/gen_context_pack.py', 'tools/build_manifest.py']:
    subprocess.run([sys.executable, str(ROOT / script)], check=True)

# Context pack should stay small.
cp = ROOT / 'context-pack.json'
if cp.stat().st_size > 12000:
    raise SystemExit('context-pack.json too large')

# Revision sync and front-door freshness.
rev = (ROOT / 'VERSION').read_text(encoding='utf-8').strip()
for surface in ['README.md', 'START_HERE.md']:
    txt = (ROOT / surface).read_text(encoding='utf-8')
    if rev not in txt:
        raise SystemExit(f'{surface} does not mention active revision {rev}')
    if '## This revision' in txt:
        block = txt.split('## This revision', 1)[1][:1500]
        if rev not in block:
            raise SystemExit(f'{surface} This revision block is stale relative to {rev}')
receipt = json.loads((ROOT / 'REVISION-RECEIPT.json').read_text(encoding='utf-8'))
if receipt['revision'] != rev:
    raise SystemExit('revision receipt out of sync with VERSION')
status = json.loads((ROOT / 'SURFACE-STATUS.json').read_text(encoding='utf-8'))
if status['revision'] != rev:
    raise SystemExit('surface status out of sync with VERSION')

# ARCHIVE_INDEX should mention every markdown file except itself? include itself too.
index = (ROOT / 'ARCHIVE_INDEX.md').read_text(encoding='utf-8')
for md in sorted(p.relative_to(ROOT).as_posix() for p in all_md):
    if md not in index:
        raise SystemExit(f'ARCHIVE_INDEX missing path: {md}')

print('lint_archive: OK')
