from pathlib import Path
import sys
root=Path(sys.argv[1])
old='''    def _deactivate_transfer(self, transfer):\n\n        username = transfer.username\n        token = transfer.token\n\n        if token is None or token not in self.active_users.get(username, {}):\n            return False\n\n        del self.active_users[username][token]\n\n        if not self.active_users[username]:\n            del self.active_users[username]\n\n        if transfer.speed > 0:\n            self.total_bandwidth = max(0, self.total_bandwidth - transfer.speed)\n\n        if transfer.request_timer_id is not None:\n            events.cancel_scheduled(transfer.request_timer_id)\n            transfer.request_timer_id = None\n\n        transfer.speed = transfer.avg_speed\n        transfer.sock = None\n        transfer.token = None\n\n        return True\n'''
new='''    def _deactivate_transfer(self, transfer):\n\n        username = transfer.username\n        token = transfer.token\n\n        if token is None:\n            return False\n\n        active_transfers = self.active_users.get(username, {})\n        active_transfer = active_transfers.get(token)\n        deactivated = False\n\n        if active_transfer is transfer:\n            del active_transfers[token]\n\n            if not active_transfers:\n                del self.active_users[username]\n\n            deactivated = True\n\n        if transfer.speed > 0:\n            self.total_bandwidth = max(0, self.total_bandwidth - transfer.speed)\n\n        if transfer.request_timer_id is not None:\n            events.cancel_scheduled(transfer.request_timer_id)\n            transfer.request_timer_id = None\n\n        transfer.speed = transfer.avg_speed\n        transfer.sock = None\n        transfer.token = None\n\n        return deactivated\n'''
old2='''        log.add_transfer("Received download request with token %s for file %s from user %s",\n                         (token, virtual_path, username))\n\n        download = (self.queued_users.get(username, {}).get(virtual_path)\n                    or self.failed_users.get(username, {}).get(virtual_path))\n'''
new2='''        log.add_transfer("Received download request with token %s for file %s from user %s",\n                         (token, virtual_path, username))\n\n        download = (self.queued_users.get(username, {}).get(virtual_path)\n                    or self.failed_users.get(username, {}).get(virtual_path))\n        active_download = self.active_users.get(username, {}).get(token)\n\n        if active_download is not None and active_download is not download:\n            log.add_transfer("Rejected duplicate download request with token %s for file %s from user %s; "\n                             "token is already bound to active file %s",\n                             (token, virtual_path, username, active_download.virtual_path))\n            reason = TransferRejectReason.QUEUED if download is not None else TransferRejectReason.CANCELLED\n            return TransferResponse(allowed=False, reason=reason, token=token)\n'''
for rel, oldv, newv in [('pynicotine/transfers.py', old, new), ('pynicotine/downloads.py', old2, new2)]:
    p=root/rel
    t=p.read_text()
    if newv in t:
        continue
    if oldv not in t:
        raise SystemExit(f'anchor missing: {p}')
    p.write_text(t.replace(oldv,newv,1))
print('applied u123 inline')
