#!/usr/bin/env node
import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { performance } from 'node:perf_hooks';
import { REVISION, VERSION } from '../src/browserrt.mjs';
const TASK_ID = 'facility:storage-lane-quarantine-legacy-clear-binding-contract-audit';
// Surface ids guarded by this carried-forward audit: surface:storage-lane-quarantine-legacy-clear-binding, surface:browser-opfs-web-lock-quarantine-legacy-clear-binding.
const DEFAULT_OUT = `artifacts/audit/REV${REVISION.slice(3)}-STORAGE-LANE-QUARANTINE-LEGACY-CLEAR-BINDING-CONTRACT-AUDIT.json`;
const argValue = (argv, flag, fallback = null) => { const i = argv.indexOf(flag); return i >= 0 ? argv[i + 1] : fallback; };
async function text(path) { try { return await readFile(path, 'utf8'); } catch { return ''; } }
function missing(haystack, needles) { return needles.filter((needle) => !haystack.includes(needle)); }
function check(checks, id, ok, detail = {}) { checks.push(Object.freeze({ id, ok: Boolean(ok), ...detail })); }
export async function runAudit() {
  const started = performance.now();
  const files = Object.fromEntries(await Promise.all(['src/storage-lane-scheduler.mjs','src/block-store-lane-adapter.mjs','src/types.d.ts','tools/storage_lane_quarantine_legacy_clear_binding_probe.mjs','tools/browser_opfs_web_lock_quarantine_legacy_clear_binding_probe.mjs','docs/40-validation/storage-lane-quarantine-legacy-clear-binding-slice.md','docs/40-validation/browser-opfs-web-lock-quarantine-legacy-clear-binding-slice.md','test/manifest.json','test/impact-map.json','test/surface-inventory.json','package.json','Makefile','README.md','START_HERE.md','AGENTS.md','CONTEXT-PACK.md'].map(async (p) => [p, await text(p)])));
  const checks = [];
  check(checks, 'runtime-legacy-success-clear-fingerprint-bound', missing(files['src/storage-lane-scheduler.mjs'], ['late-success-clear-review-fingerprint-required','late-success-clear-review-fingerprint-mismatch','reviewManifest','requireReviewFingerprint','storage-lane:late-provider-success-clear-rejected']).length === 0, { missing: missing(files['src/storage-lane-scheduler.mjs'], ['late-success-clear-review-fingerprint-required','late-success-clear-review-fingerprint-mismatch','reviewManifest','requireReviewFingerprint','storage-lane:late-provider-success-clear-rejected']) });
  check(checks, 'runtime-legacy-failure-clear-fingerprint-bound', missing(files['src/storage-lane-scheduler.mjs'], ['late-failure-clear-review-fingerprint-required','late-failure-clear-review-fingerprint-mismatch','storage-lane:late-provider-failure-clear-rejected']).length === 0, { missing: missing(files['src/storage-lane-scheduler.mjs'], ['late-failure-clear-review-fingerprint-required','late-failure-clear-review-fingerprint-mismatch','storage-lane:late-provider-failure-clear-rejected']) });
  check(checks, 'adapter-forwards-review-binding-options', missing(files['src/block-store-lane-adapter.mjs'], ['reviewFingerprint: options.reviewFingerprint','requireReviewFingerprint: options.requireReviewFingerprint !== false','reviewManifest: options.reviewManifest','opIds: options.opIds']).length === 0, { missing: missing(files['src/block-store-lane-adapter.mjs'], ['reviewFingerprint: options.reviewFingerprint','requireReviewFingerprint: options.requireReviewFingerprint !== false','reviewManifest: options.reviewManifest','opIds: options.opIds']) });
  check(checks, 'types-include-legacy-binding-options', missing(files['src/types.d.ts'], ['clearSuccessfulTimedOutOperations','clearFailedTimedOutOperations','reviewFingerprint?: string | null','requireReviewFingerprint?: boolean','reviewManifest?: Record<string, unknown> | null','opIds?: string[] | null']).length === 0);
  check(checks, 'release-proof-wired', missing(files['tools/storage_lane_quarantine_legacy_clear_binding_probe.mjs'], ['scheduler:storage-lane-quarantine-legacy-clear-binding-proof','late-success-clear-review-fingerprint-required','late-failure-clear-review-fingerprint-required','staleOldSuccessReviewOnFailure','reviewManifest']).length === 0);
  check(checks, 'browser-proof-wired', missing(files['tools/browser_opfs_web_lock_quarantine_legacy_clear_binding_probe.mjs'], ['browser:opfs-web-lock-quarantine-legacy-clear-binding-proof','opfsWebLockGuardedBlockStore','late-success-clear-review-fingerprint-required','late-failure-clear-review-fingerprint-required','coord:web-lock-acquired']).length === 0);
  check(checks, 'docs-preserve-nonclaims', missing(files['docs/40-validation/storage-lane-quarantine-legacy-clear-binding-slice.md'], ['legacy clear helpers','review-fingerprint','not provider cancellation']).length === 0 && missing(files['docs/40-validation/browser-opfs-web-lock-quarantine-legacy-clear-binding-slice.md'], ['Managed Chromium','real OPFS','real Web Locks','not cross-browser']).length === 0);
  check(checks, 'manifest-impact-surface-wired', missing(files['test/manifest.json'], ['scheduler:storage-lane-quarantine-legacy-clear-binding-proof','browser:opfs-web-lock-quarantine-legacy-clear-binding-proof','facility:storage-lane-quarantine-legacy-clear-binding-contract-audit']).length === 0 && missing(files['test/impact-map.json'], ['scheduler:storage-lane-quarantine-legacy-clear-binding-proof','browser:opfs-web-lock-quarantine-legacy-clear-binding-proof','facility:storage-lane-quarantine-legacy-clear-binding-contract-audit']).length === 0 && missing(files['test/surface-inventory.json'], ['storage-lane-quarantine-legacy-clear-binding']).length === 0);
  check(checks, 'first-read-carried-anchor', [files['README.md'], files['START_HERE.md'], files['AGENTS.md'], files['CONTEXT-PACK.md']].every((body) => body.includes(REVISION) && body.includes('Carry-forward linked seam for audits')) && files['docs/40-validation/browser-opfs-web-lock-quarantine-legacy-clear-binding-slice.md'].includes('quarantine-legacy-clear-binding'));
  const ok = checks.every((row) => row.ok);
  const report = Object.freeze({ project: 'BrowserRT', revision: REVISION, version: VERSION, schema: 1, task_id: TASK_ID, status: ok ? 'passed' : 'failed', generatedAt: new Date().toISOString(), durationMs: Math.round(performance.now() - started), checks, nonClaims: ['Audit checks wiring and textual contracts only; release/browser probes provide executable evidence.'] });
  assert.equal(ok, true, JSON.stringify(checks.filter((row) => !row.ok), null, 2));
  return report;
}
const argv = process.argv.slice(2); const out = argValue(argv, '--json', DEFAULT_OUT);
try { const report = await runAudit(); if (out) { await mkdir(dirname(out), { recursive: true }); await writeFile(out, JSON.stringify(report, null, 2) + '\n'); console.log(out); } else console.log(JSON.stringify(report, null, 2)); }
catch (error) { const report = { project: 'BrowserRT', revision: REVISION, version: VERSION, schema: 1, task_id: TASK_ID, status: 'failed', generatedAt: new Date().toISOString(), error: { name: error?.name || 'Error', message: error?.message || String(error), stack: error?.stack }, nonClaims: ['Failed audit is not silently skipped.'] }; if (out) { await mkdir(dirname(out), { recursive: true }); await writeFile(out, JSON.stringify(report, null, 2) + '\n'); console.error(out); } console.error(`[storage_lane_quarantine_legacy_clear_binding_contract_audit] FAIL: ${error?.stack || error}`); process.exitCode = 1; }
