from __future__ import annotations

"""Auditable editor hostcall and static-feature registration tables.

The bridge still owns hostcall implementations because most handlers close
over an Editor instance, but the names and handler bindings live here so the
registration surface is reviewable without scanning thousands of lines of
handler bodies.
"""

from dataclasses import dataclass
from typing import Any, Mapping


@dataclass(frozen=True)
class HostcallEntry:
    name: str
    handler_name: str


# Capability-controlled feature strings must stay out of this static list.
# They are advertised by micromax_editor.capabilities.refresh_vm_features()
# only when their cap.* option is enabled.
STATIC_EDITOR_HOST_FEATURES: tuple[str, ...] = (
    'micromax-editor',
    'host.capabilities',
    'ed.trust-state',
    'ed.jumplist',
    'ed.jump-history-rows',
    'ed.jump-detail-row',
    'ed.jump-section-rows',
    'ed.jump-section-summary-rows',
    'ed.messages',
    'ed.macros',
    'ed.macro-detail-row',
    'ed.marks',
    'ed.mark-inventory-rows',
    'ed.mark-detail-row',
    'ed.mark-section-rows',
    'ed.mark-section-summary-rows',
    'ed.buffers',
    'ed.buffer-inventory-rows',
    'ed.buffer-detail-row',
    'ed.buffer-section-rows',
    'ed.buffer-section-summary-rows',
    'ed.prompt-suggestions',
    'ed.prompt-suggestion-rows',
    'ed.prompt-current-row',
    'ed.prompt-current-section',
    'ed.prompt-current-preview',
    'ed.prompt-current-position',
    'ed.prompt-window',
    'ed.prompt-display',
    'ed.prompt-panel',
    'ed.prompt-mx-completion',
    'ed.micromax-commands',
    'ed.bindings',
    'ed.binding-detail-row',
    'ed.command-rows',
    'ed.command-detail-row',
    'ed.action-detail-row',
    'ed.word-detail-row',
    'ed.doc-detail-row',
    'ed.topic-detail-row',
    'ed.help-current-heading-detail-row',
    'ed.help-heading-detail-row',
    'ed.hook-detail-row',
    'ed.hook-inventory-rows',
    'ed.hook-summary-rows',
    'ed.command-palette',
    'ed.command-palette-rows',
    'ed.command-palette-section-rows',
    'ed.command-palette-section-summary-rows',
    'ed.topic-rows',
    'ed.topic-section-rows',
    'ed.topic-section-summary-rows',
    'ed.apropos-section-rows',
    'ed.apropos-section-summary-rows',
    'ed.topic-prompt',
    'ed.binding-prompt',
    'ed.binding-prompt-rows',
    'ed.binding-section-rows',
    'ed.binding-section-summary-rows',
    'ed.registration-groups',
    'ed.keymodes',
    'ed.keymode-inventory-rows',
    'ed.keymode-detail-row',
    'ed.transient-keymodes',
    'ed.binding-discovery',
    'ed.available-binding-inventory-rows',
    'ed.option-inventory-rows',
    'ed.option-section-summary-rows',
    'ed.option-detail-row',
    'ed.prefix-maps',
    'ed.mode-prefix-maps',
    'ed.statusline',
    'ed.statusfmt',
    'ed.statusline-text',
    'ed.statusline-model',
    'ed.interaction-model',
    'ed.keymenu-model',
    'ed.infobar-model',
    'ed.screen-layout',
    'ed.gutter-model',
    'ed.edit-window',
    'ed.search-rows',
    'ed.showchars-rows',
    'ed.viewport-cues',
    'ed.docs-cues',
    'ed.display-rows',
    'ed.viewport-rows',
    'ed.screen-model',
    'ed.screen-rows',
    'ed.bottom-rows',
    'ed.with-buffer',
    'ed.with-viewport',
    'ed.recent',
    'ed.recent-clear',
    'ed.recent-clear-count',
    'ed.recent-inventory-rows',
    'ed.recent-detail-row',
    'ed.recent-slot-detail-row',
    'ed.recent-dir-detail-row',
    'ed.recent-slot-dir-detail-row',
    'ed.recent-section-rows',
    'ed.recent-section-summary-rows',
    'ed.recent-dir-section-rows',
    'ed.recent-dir-section-summary-rows',
    'ed.recent-prompt-rows',
    'ed.recent-dir-prompt-rows',
    'ed.doc-rows',
    'ed.doc-section-rows',
    'ed.doc-section-summary-rows',
    'ed.help-doc',
    'ed.help-follow',
    'ed.help-back',
    'ed.help-forward',
    'ed.help-resume',
    'ed.help-prune',
    'ed.help-link-rows',
    'ed.help-link-detail-row',
    'ed.helphistory-rows',
    'ed.helplink-section-rows',
    'ed.help-outline-rows',
    'ed.help-outline-section-rows',
    'ed.helpnav-section-rows',
    'ed.helpnav-section-summary-rows',
    'ed.filetype',
    'ed.viewport',
    'ed.lines',
    'ed.replace-preview',
    'ed.highlight',
    'ed.highlight-tags',
    'ed.after',
    'ed.cancel-timer',
    'ed.pump-timers',
    'ed.plugin-inventory-rows',
    'ed.plugin-detail-row',
    'ed.plugin-cleanup-failure-rows',
    'ed.plugin-section-rows',
    'ed.plugin-section-summary-rows',
    'plugin.list',
    'plugin.reload',
    'plugin.errors',
)


EDITOR_HOSTCALL_REGISTRY: tuple[HostcallEntry, ...] = (
    HostcallEntry('ed.msg', 'hc_ed_msg'),
    HostcallEntry('ed.messages', 'hc_ed_messages'),
    HostcallEntry('ed.last-message', 'hc_ed_last_message'),
    HostcallEntry('ed.pop-message', 'hc_ed_pop_message'),
    HostcallEntry('ed.clear-messages', 'hc_ed_clear_messages'),
    HostcallEntry('host.capabilities', 'hc_host_capabilities'),
    HostcallEntry('ed.trust-state', 'hc_ed_trust_state'),
    HostcallEntry('ed.open-url', 'hc_ed_open_url'),
    HostcallEntry('ed.shell', 'hc_ed_shell'),
    HostcallEntry('ed.fs-read', 'hc_ed_fs_read'),
    HostcallEntry('ed.fs-list', 'hc_ed_fs_list'),
    HostcallEntry('ed.fs-stat', 'hc_ed_fs_stat'),
    HostcallEntry('ed.buffers', 'hc_ed_buffers'),
    HostcallEntry('ed.buffer-inventory-rows', 'hc_ed_buffer_inventory_rows'),
    HostcallEntry('ed.buffer-detail-row', 'hc_ed_buffer_detail_row'),
    HostcallEntry('ed.buffer-section-rows', 'hc_ed_buffer_section_rows'),
    HostcallEntry('ed.buffer-section-summary-rows', 'hc_ed_buffer_section_summary_rows'),
    HostcallEntry('ed.active-buffer', 'hc_ed_active_buffer'),
    HostcallEntry('ed.set-active-buffer', 'hc_ed_set_active_buffer'),
    HostcallEntry('ed.mark-set', 'hc_ed_mark_set'),
    HostcallEntry('ed.mark-jump', 'hc_ed_mark_jump'),
    HostcallEntry('ed.marks', 'hc_ed_marks'),
    HostcallEntry('ed.mark-inventory-rows', 'hc_ed_mark_inventory_rows'),
    HostcallEntry('ed.mark-detail-row', 'hc_ed_mark_detail_row'),
    HostcallEntry('ed.mark-section-rows', 'hc_ed_mark_section_rows'),
    HostcallEntry('ed.mark-section-summary-rows', 'hc_ed_mark_section_summary_rows'),
    HostcallEntry('ed.status', 'hc_ed_status'),
    HostcallEntry('ed.status-summary', 'hc_ed_status_summary'),
    HostcallEntry('ed.statusfmt', 'hc_ed_statusfmt'),
    HostcallEntry('ed.statusline-text', 'hc_ed_statusline_text'),
    HostcallEntry('ed.statusline-model', 'hc_ed_statusline_model'),
    HostcallEntry('ed.prompt-panel', 'hc_ed_prompt_panel'),
    HostcallEntry('ed.gutter-model', 'hc_ed_gutter_model'),
    HostcallEntry('ed.interaction-model', 'hc_ed_interaction_model'),
    HostcallEntry('ed.keymenu-model', 'hc_ed_keymenu_model'),
    HostcallEntry('ed.infobar-model', 'hc_ed_infobar_model'),
    HostcallEntry('ed.screen-layout', 'hc_ed_screen_layout'),
    HostcallEntry('ed.edit-window', 'hc_ed_edit_window'),
    HostcallEntry('ed.search-rows', 'hc_ed_search_rows'),
    HostcallEntry('ed.showchars-rows', 'hc_ed_showchars_rows'),
    HostcallEntry('ed.viewport-cues', 'hc_ed_viewport_cues'),
    HostcallEntry('ed.docs-cues', 'hc_ed_docs_cues'),
    HostcallEntry('ed.display-rows', 'hc_ed_display_rows'),
    HostcallEntry('ed.viewport-rows', 'hc_ed_viewport_rows'),
    HostcallEntry('ed.screen-model', 'hc_ed_screen_model'),
    HostcallEntry('ed.screen-rows', 'hc_ed_screen_rows'),
    HostcallEntry('ed.bottom-rows', 'hc_ed_bottom_rows'),
    HostcallEntry('ed.with-buffer', 'hc_ed_with_buffer'),
    HostcallEntry('ed.with-viewport', 'hc_ed_with_viewport'),
    HostcallEntry('ed.plugin-inventory-rows', 'hc_ed_plugin_inventory_rows'),
    HostcallEntry('ed.plugin-detail-row', 'hc_ed_plugin_detail_row'),
    HostcallEntry('ed.plugin-cleanup-failure-rows', 'hc_ed_plugin_cleanup_failure_rows'),
    HostcallEntry('ed.plugin-section-rows', 'hc_ed_plugin_section_rows'),
    HostcallEntry('ed.plugin-section-summary-rows', 'hc_ed_plugin_section_summary_rows'),
    HostcallEntry('ed.recent', 'hc_ed_recent'),
    HostcallEntry('ed.recent-clear', 'hc_ed_recent_clear'),
    HostcallEntry('ed.recent-clear-count', 'hc_ed_recent_clear_count'),
    HostcallEntry('ed.recent-inventory-rows', 'hc_ed_recent_inventory_rows'),
    HostcallEntry('ed.recent-detail-row', 'hc_ed_recent_detail_row'),
    HostcallEntry('ed.recent-slot-detail-row', 'hc_ed_recent_slot_detail_row'),
    HostcallEntry('ed.recent-dir-detail-row', 'hc_ed_recent_dir_detail_row'),
    HostcallEntry('ed.recent-slot-dir-detail-row', 'hc_ed_recent_slot_dir_detail_row'),
    HostcallEntry('ed.recent-section-rows', 'hc_ed_recent_section_rows'),
    HostcallEntry('ed.recent-section-summary-rows', 'hc_ed_recent_section_summary_rows'),
    HostcallEntry('ed.recent-dir-section-rows', 'hc_ed_recent_dir_section_rows'),
    HostcallEntry('ed.recent-dir-section-summary-rows', 'hc_ed_recent_dir_section_summary_rows'),
    HostcallEntry('ed.recent-prompt-rows', 'hc_ed_recent_prompt_rows'),
    HostcallEntry('ed.recent-dir-prompt-rows', 'hc_ed_recent_dir_prompt_rows'),
    HostcallEntry('ed.doc-rows', 'hc_ed_doc_rows'),
    HostcallEntry('ed.doc-section-rows', 'hc_ed_doc_section_rows'),
    HostcallEntry('ed.doc-section-summary-rows', 'hc_ed_doc_section_summary_rows'),
    HostcallEntry('ed.help-doc', 'hc_ed_help_doc'),
    HostcallEntry('ed.help-follow', 'hc_ed_help_follow'),
    HostcallEntry('ed.help-back', 'hc_ed_help_back'),
    HostcallEntry('ed.help-forward', 'hc_ed_help_forward'),
    HostcallEntry('ed.help-resume', 'hc_ed_help_resume'),
    HostcallEntry('ed.help-prune', 'hc_ed_help_prune'),
    HostcallEntry('ed.help-link-rows', 'hc_ed_help_link_rows'),
    HostcallEntry('ed.help-link-detail-row', 'hc_ed_help_link_detail_row'),
    HostcallEntry('ed.helphistory-rows', 'hc_ed_helphistory_rows'),
    HostcallEntry('ed.helplink-section-rows', 'hc_ed_helplink_section_rows'),
    HostcallEntry('ed.help-outline-rows', 'hc_ed_help_outline_rows'),
    HostcallEntry('ed.help-outline-section-rows', 'hc_ed_help_outline_section_rows'),
    HostcallEntry('ed.helpnav-section-rows', 'hc_ed_helpnav_section_rows'),
    HostcallEntry('ed.helpnav-section-summary-rows', 'hc_ed_helpnav_section_summary_rows'),
    HostcallEntry('ed.filetype', 'hc_ed_filetype'),
    HostcallEntry('ed.with-messages', 'hc_ed_with_messages'),
    HostcallEntry('ed.capture-messages', 'hc_ed_capture_messages'),
    HostcallEntry('ed.macro-names', 'hc_ed_macro_names'),
    HostcallEntry('ed.macro-detail-row', 'hc_ed_macro_detail_row'),
    HostcallEntry('ed.macro-inventory-rows', 'hc_ed_macro_inventory_rows'),
    HostcallEntry('ed.macro-status-rows', 'hc_ed_macro_status_rows'),
    HostcallEntry('ed.macro-get', 'hc_ed_macro_get'),
    HostcallEntry('ed.macro-set', 'hc_ed_macro_set'),
    HostcallEntry('ed.macro-record', 'hc_ed_macro_record'),
    HostcallEntry('ed.macro-stop', 'hc_ed_macro_stop'),
    HostcallEntry('ed.macro-cancel', 'hc_ed_macro_cancel'),
    HostcallEntry('ed.macro-play', 'hc_ed_macro_play'),
    HostcallEntry('ed.macro-recording?', 'hc_ed_macro_recording'),
    HostcallEntry('ed.macro-playing?', 'hc_ed_macro_playing'),
    HostcallEntry('ed.cmd-add', 'hc_ed_cmd_add'),
    HostcallEntry('ed.hook-detail-row', 'hc_ed_hook_detail_row'),
    HostcallEntry('ed.hook-inventory-rows', 'hc_ed_hook_inventory_rows'),
    HostcallEntry('ed.hook-summary-rows', 'hc_ed_hook_summary_rows'),
    HostcallEntry('ed.cmd-rm', 'hc_ed_cmd_rm'),
    HostcallEntry('ed.cmds', 'hc_ed_cmds'),
    HostcallEntry('ed.cmd-rows', 'hc_ed_cmd_rows'),
    HostcallEntry('ed.command-detail-row', 'hc_ed_command_detail_row'),
    HostcallEntry('ed.action-detail-row', 'hc_ed_action_detail_row'),
    HostcallEntry('ed.word-detail-row', 'hc_ed_word_detail_row'),
    HostcallEntry('ed.doc-detail-row', 'hc_ed_doc_detail_row'),
    HostcallEntry('ed.topic-detail-row', 'hc_ed_topic_detail_row'),
    HostcallEntry('ed.help-current-heading-detail-row', 'hc_ed_help_current_heading_detail_row'),
    HostcallEntry('ed.help-heading-detail-row', 'hc_ed_help_heading_detail_row'),
    HostcallEntry('ed.command-palette', 'hc_ed_command_palette'),
    HostcallEntry('ed.command-palette-rows', 'hc_ed_command_palette_rows'),
    HostcallEntry('ed.command-palette-section-rows', 'hc_ed_command_palette_section_rows'),
    HostcallEntry('ed.command-palette-section-summary-rows', 'hc_ed_command_palette_section_summary_rows'),
    HostcallEntry('ed.topic-rows', 'hc_ed_topic_rows'),
    HostcallEntry('ed.topic-section-rows', 'hc_ed_topic_section_rows'),
    HostcallEntry('ed.topic-section-summary-rows', 'hc_ed_topic_section_summary_rows'),
    HostcallEntry('ed.topic-prompt', 'hc_ed_topic_prompt'),
    HostcallEntry('ed.binding-prompt', 'hc_ed_binding_prompt'),
    HostcallEntry('ed.apropos-rows', 'hc_ed_apropos_rows'),
    HostcallEntry('ed.apropos-section-rows', 'hc_ed_apropos_section_rows'),
    HostcallEntry('ed.apropos-section-summary-rows', 'hc_ed_apropos_section_summary_rows'),
    HostcallEntry('ed.binding-prompt-rows', 'hc_ed_binding_prompt_rows'),
    HostcallEntry('ed.binding-section-rows', 'hc_ed_binding_section_rows'),
    HostcallEntry('ed.binding-section-summary-rows', 'hc_ed_binding_section_summary_rows'),
    HostcallEntry('ed.bind', 'hc_ed_bind'),
    HostcallEntry('ed.bind-mode', 'hc_ed_bind_mode'),
    HostcallEntry('ed.bind-doc', 'hc_ed_bind_doc'),
    HostcallEntry('ed.bind-mode-doc', 'hc_ed_bind_mode_doc'),
    HostcallEntry('ed.bind-prefix', 'hc_ed_bind_prefix'),
    HostcallEntry('ed.bind-mode-prefix', 'hc_ed_bind_mode_prefix'),
    HostcallEntry('ed.unbind', 'hc_ed_unbind'),
    HostcallEntry('ed.unbind-mode', 'hc_ed_unbind_mode'),
    HostcallEntry('ed.bindings', 'hc_ed_bindings'),
    HostcallEntry('ed.binding-detail', 'hc_ed_binding_detail'),
    HostcallEntry('ed.binding-detail-row', 'hc_ed_binding_detail_row'),
    HostcallEntry('ed.binding-modes', 'hc_ed_binding_modes'),
    HostcallEntry('ed.binding-rows-for', 'hc_ed_binding_rows_for'),
    HostcallEntry('ed.binding-info-for', 'hc_ed_binding_info_for'),
    HostcallEntry('ed.available-bindings', 'hc_ed_available_bindings'),
    HostcallEntry('ed.available-binding-info', 'hc_ed_available_binding_info'),
    HostcallEntry('ed.available-binding-inventory-rows', 'hc_ed_available_binding_inventory_rows'),
    HostcallEntry('ed.resolve-key', 'hc_ed_resolve_key'),
    HostcallEntry('ed.resolve-key-info', 'hc_ed_resolve_key_info'),
    HostcallEntry('ed.keymode!', 'hc_ed_keymode_store'),
    HostcallEntry('ed.keymode@', 'hc_ed_keymode_fetch'),
    HostcallEntry('ed.keymode-push', 'hc_ed_keymode_push'),
    HostcallEntry('ed.keymode-push-once', 'hc_ed_keymode_push_once'),
    HostcallEntry('ed.prefix-mode', 'hc_ed_prefix_mode'),
    HostcallEntry('ed.keymode-pop', 'hc_ed_keymode_pop'),
    HostcallEntry('ed.keymodes', 'hc_ed_keymodes'),
    HostcallEntry('ed.keymode-rows', 'hc_ed_keymode_rows'),
    HostcallEntry('ed.keymode-inventory-rows', 'hc_ed_keymode_inventory_rows'),
    HostcallEntry('ed.keymode-detail-row', 'hc_ed_keymode_detail_row'),
    HostcallEntry('ed.group!', 'hc_ed_group_store'),
    HostcallEntry('ed.group@', 'hc_ed_group_fetch'),
    HostcallEntry('ed.run', 'hc_ed_run'),
    HostcallEntry('ed.press-key', 'hc_ed_press_key'),
    HostcallEntry('ed.command', 'hc_ed_command'),
    HostcallEntry('ed.command-edit', 'hc_ed_command_edit'),
    HostcallEntry('ed.prompt-kind', 'hc_ed_prompt_kind'),
    HostcallEntry('ed.prompt-text', 'hc_ed_prompt_text'),
    HostcallEntry('ed.prompt-set', 'hc_ed_prompt_set'),
    HostcallEntry('ed.prompt-submit', 'hc_ed_prompt_submit'),
    HostcallEntry('ed.prompt-suggestions', 'hc_ed_prompt_suggestions'),
    HostcallEntry('ed.prompt-suggestion-rows', 'hc_ed_prompt_suggestion_rows'),
    HostcallEntry('ed.prompt-current-row', 'hc_ed_prompt_current_row'),
    HostcallEntry('ed.prompt-current-section', 'hc_ed_prompt_current_section'),
    HostcallEntry('ed.prompt-current-preview', 'hc_ed_prompt_current_preview'),
    HostcallEntry('ed.prompt-current-position', 'hc_ed_prompt_current_position'),
    HostcallEntry('ed.prompt-window', 'hc_ed_prompt_window'),
    HostcallEntry('ed.prompt-display', 'hc_ed_prompt_display'),
    HostcallEntry('ed.prompt-suggest-index', 'hc_ed_prompt_suggest_index'),
    HostcallEntry('ed.prompt-complete', 'hc_ed_prompt_complete'),
    HostcallEntry('ed.prompt-clear-suggestions', 'hc_ed_prompt_clear_suggestions'),
    HostcallEntry('ed.input-set', 'hc_ed_input_set'),
    HostcallEntry('ed.input-get', 'hc_ed_input_get'),
    HostcallEntry('ed.input-keys', 'hc_ed_input_keys'),
    HostcallEntry('ed.input-clear', 'hc_ed_input_clear'),
    HostcallEntry('ed.input', 'hc_ed_input'),
    HostcallEntry('ed.insert', 'hc_ed_insert'),
    HostcallEntry('ed.backspace', 'hc_ed_backspace'),
    HostcallEntry('ed.open', 'hc_ed_open'),
    HostcallEntry('ed.save', 'hc_ed_save'),
    HostcallEntry('ed.text', 'hc_ed_text'),
    HostcallEntry('ed.set-text', 'hc_ed_set_text'),
    HostcallEntry('ed.line', 'hc_ed_line'),
    HostcallEntry('ed.lines', 'hc_ed_lines'),
    HostcallEntry('ed.highlight', 'hc_ed_highlight'),
    HostcallEntry('ed.highlight-tags', 'hc_ed_highlight_tags'),
    HostcallEntry('ed.after', 'hc_ed_after'),
    HostcallEntry('ed.cancel-timer', 'hc_ed_cancel_timer'),
    HostcallEntry('ed.pump-timers', 'hc_ed_pump_timers'),
    HostcallEntry('plugin.list', 'hc_plugin_list'),
    HostcallEntry('plugin.reload', 'hc_plugin_reload'),
    HostcallEntry('plugin.errors', 'hc_plugin_errors'),
    HostcallEntry('ed.viewport', 'hc_ed_viewport'),
    HostcallEntry('ed.viewport!', 'hc_ed_viewport_store'),
    HostcallEntry('ed.cursor', 'hc_ed_cursor'),
    HostcallEntry('ed.set-cursor', 'hc_ed_set_cursor'),
    HostcallEntry('ed.has-selection', 'hc_ed_has_selection'),
    HostcallEntry('ed.selection', 'hc_ed_selection_text'),
    HostcallEntry('ed.clear-selection', 'hc_ed_clear_selection'),
    HostcallEntry('ed.cursors', 'hc_ed_cursors'),
    HostcallEntry('ed.set-cursors', 'hc_ed_set_cursors'),
    HostcallEntry('ed.primary', 'hc_ed_primary'),
    HostcallEntry('ed.set-primary', 'hc_ed_set_primary'),
    HostcallEntry('ed.selections', 'hc_ed_selections'),
    HostcallEntry('ed.set-selections', 'hc_ed_set_selections'),
    HostcallEntry('ed.replace-selections', 'hc_ed_replace_selections'),
    HostcallEntry('ed.replace-preview', 'hc_ed_replace_preview'),
    HostcallEntry('ed.selection-range', 'hc_ed_selection_range'),
    HostcallEntry('ed.set-selection-range', 'hc_ed_set_selection_range'),
    HostcallEntry('ed.range-text', 'hc_ed_range_text'),
    HostcallEntry('ed.replace-range', 'hc_ed_replace_range'),
    HostcallEntry('ed.delete-range', 'hc_ed_delete_range'),
    HostcallEntry('ed.with-undo', 'hc_ed_with_undo'),
    HostcallEntry('ed.clipboard', 'hc_ed_clipboard'),
    HostcallEntry('ed.set-clipboard', 'hc_ed_set_clipboard'),
    HostcallEntry('ed.clipboard-items', 'hc_ed_clipboard_items'),
    HostcallEntry('ed.set-clipboard-items', 'hc_ed_set_clipboard_items'),
    HostcallEntry('ed.clipboard-import', 'hc_ed_clipboard_import'),
    HostcallEntry('ed.push-selections', 'hc_ed_push_selections'),
    HostcallEntry('ed.pop-selections', 'hc_ed_pop_selections'),
    HostcallEntry('ed.clear-saved-selections', 'hc_ed_clear_saved_selections'),
    HostcallEntry('ed.cursorstate', 'hc_ed_cursorstate'),
    HostcallEntry('ed.set-cursorstate', 'hc_ed_set_cursorstate'),
    HostcallEntry('ed.with-cursorstate', 'hc_ed_with_cursorstate'),
    HostcallEntry('ed.push-jump', 'hc_ed_push_jump'),
    HostcallEntry('ed.jump-back', 'hc_ed_jump_back'),
    HostcallEntry('ed.jump-forward', 'hc_ed_jump_forward'),
    HostcallEntry('ed.jump-info', 'hc_ed_jump_info'),
    HostcallEntry('ed.clear-jumps', 'hc_ed_clear_jumps'),
    HostcallEntry('ed.jump-history-rows', 'hc_ed_jump_history_rows'),
    HostcallEntry('ed.jump-detail-row', 'hc_ed_jump_detail_row'),
    HostcallEntry('ed.jump-section-rows', 'hc_ed_jump_section_rows'),
    HostcallEntry('ed.jump-section-summary-rows', 'hc_ed_jump_section_summary_rows'),
    HostcallEntry('ed.find', 'hc_ed_find'),
    HostcallEntry('ed.find-next', 'hc_ed_find_next'),
    HostcallEntry('ed.find-prev', 'hc_ed_find_prev'),
    HostcallEntry('ed.option-inventory-rows', 'hc_ed_option_inventory_rows'),
    HostcallEntry('ed.option-section-summary-rows', 'hc_ed_option_section_summary_rows'),
    HostcallEntry('ed.option-detail-row', 'hc_ed_option_detail_row'),
    HostcallEntry('ed.opt-get', 'hc_ed_opt_get'),
    HostcallEntry('ed.opt-set', 'hc_ed_opt_set'),
    HostcallEntry('ed.opt-set-local', 'hc_ed_opt_set_local'),
    HostcallEntry('ed.require', 'hc_ed_require'),
)


def advertise_static_editor_host_features(vm: Any) -> None:
    """Advertise always-present editor host features on ``vm``.

    Optional/unsafe capabilities are deliberately excluded from
    ``STATIC_EDITOR_HOST_FEATURES`` and are reconciled separately by the
    capability registry.
    """

    vm.host_features.update(STATIC_EDITOR_HOST_FEATURES)


def register_editor_hostcalls(vm: Any, handlers: Mapping[str, Any]) -> None:
    """Register the editor hostcalls listed in ``EDITOR_HOSTCALL_REGISTRY``.

    ``handlers`` is normally ``locals()`` from ``install_editor_hostcalls``.
    Resolve every handler before registering any hostcall so an extraction
    typo fails atomically during startup rather than leaving a partial bridge.
    """

    resolved: list[tuple[str, Any]] = []
    missing: list[str] = []
    for entry in EDITOR_HOSTCALL_REGISTRY:
        fn = handlers.get(entry.handler_name)
        if not callable(fn):
            missing.append(f"{entry.name}->{entry.handler_name}")
            continue
        resolved.append((entry.name, fn))
    if missing:
        joined = ", ".join(missing)
        raise RuntimeError(f"missing editor hostcall handler(s): {joined}")
    for name, fn in resolved:
        vm.register_host(name, fn)


def editor_hostcall_names() -> tuple[str, ...]:
    """Return registered editor hostcall names in registration order."""

    return tuple(entry.name for entry in EDITOR_HOSTCALL_REGISTRY)
