#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib.metadata as md
import importlib.util
import json
import os
import platform
import shlex
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from tools.hf_snapshot_integrity import (  # noqa: E402
    EXPECTED_MODEL_SAFETENSORS_SHA256,
    REQUIRED_SNAPSHOT_FILES,
    inspect_snapshot,
    snapshot_candidate_paths,
)

META = json.loads((ROOT / 'CUBE-META.json').read_text(encoding='utf-8'))
REV = str(META.get('revision', 'rev0000'))
REVUP = REV.upper()
REVNO = int(REV.replace('rev', ''))
OUT_AUDIT = ROOT / 'artifacts' / 'audit'
OUT_MAN = ROOT / 'artifacts' / 'run-manifests'
OUT_RUNTIME = ROOT / 'artifacts' / 'runtime'
for d in (OUT_AUDIT, OUT_MAN, OUT_RUNTIME):
    d.mkdir(parents=True, exist_ok=True)

DEFAULT_MODEL_ID = 'TinyLlama/TinyLlama-1.1B-Chat-v1.0'
DEFAULT_REVISION = 'fe8a4ea1ffedaf415f4da2f062534de366a451e6'
CAPTURE_REQUIRED_MODULES = ['numpy', 'torch', 'transformers', 'huggingface_hub', 'safetensors']


def module_presence(name: str) -> dict[str, Any]:
    spec = importlib.util.find_spec(name)  # type: ignore[attr-defined]
    out: dict[str, Any] = {
        'name': name,
        'present': bool(spec is not None),
        'origin': getattr(spec, 'origin', None) if spec else None,
        'checked_without_importing_module': True,
    }
    if spec is not None:
        try:
            out['version'] = md.version(name)
        except Exception as exc:
            out['version_error'] = repr(exc)
    return out


def prompt_status(path_text: str) -> dict[str, Any]:
    path = (ROOT / path_text).resolve() if not Path(path_text).is_absolute() else Path(path_text).expanduser()
    rec: dict[str, Any] = {'path': str(path), 'exists': path.is_file(), 'prompt_count': 0, 'blockers': []}
    if not path.is_file():
        rec['blockers'].append('prompt_manifest_missing')
        return rec
    try:
        lines = path.read_text(encoding='utf-8').splitlines()
        prompts = [line for line in lines if line.strip() and not line.lstrip().startswith('#')]
        rec['prompt_count'] = len(prompts)
        rec['first_prompt_chars'] = len(prompts[0]) if prompts else 0
        if len(prompts) < 2:
            rec['blockers'].append('prompt_manifest_needs_at_least_two_prompts')
    except Exception as exc:
        rec['blockers'].append('prompt_manifest_unreadable')
        rec['error'] = type(exc).__name__ + ': ' + repr(exc)
    return rec


def choose_digest_verified_snapshot(snapshot_checks: list[dict[str, Any]]) -> dict[str, Any]:
    """Return the exact local snapshot directory that capture must load.

    Earlier preflights reported only that *some* candidate snapshot passed the
    digest gate.  That is not a strong enough capture contract when Transformers
    may resolve a model id through cache lookup.  The capture-start gate now
    emits a shell env file binding LOCAL_SNAPSHOT_DIR/CAPTURE_MODEL to the first
    digest-verified candidate so the loader consumes the same bytes that were
    hashed.
    """
    for check in snapshot_checks:
        safe = check.get('model_safetensors', {}) if isinstance(check, dict) else {}
        if check.get('complete_required_snapshot') and safe.get('sha256_matches_expected') is True:
            return {
                'path': str(check.get('path', '')),
                'model_safetensors_sha256': str(safe.get('sha256', '')),
                'selection_contract': 'digest_verified_local_snapshot_path_v1',
                'complete_required_snapshot': True,
                'sha256_matches_expected': True,
            }
    return {
        'path': '',
        'model_safetensors_sha256': '',
        'selection_contract': 'digest_verified_local_snapshot_path_v1',
        'complete_required_snapshot': False,
        'sha256_matches_expected': False,
    }


def write_capture_env(out_path: Path, *, selected: dict[str, Any], model_id: str, revision: str, prompt_manifest: str, status: str, decision: str) -> dict[str, Any]:
    selected_path = str(selected.get('path') or '')
    lines = [
        '#!/usr/bin/env bash',
        '# Generated by public_trace_capture_start_preflight_report.py.',
        '# Source this only after the strict capture-start preflight succeeds.',
        f'export PUBLIC_TRACE_CAPTURE_START_STATUS={shlex.quote(status)}',
        f'export PUBLIC_TRACE_CAPTURE_START_DECISION={shlex.quote(decision)}',
        f'export MODEL_ID={shlex.quote(model_id)}',
        f'export MODEL_REVISION={shlex.quote(revision)}',
        f'export PROMPT_MANIFEST={shlex.quote(prompt_manifest)}',
        'export CAPTURE_SNAPSHOT_SELECTION_CONTRACT=digest_verified_local_snapshot_path_v1',
        'export HF_HUB_OFFLINE=1',
        'export TRANSFORMERS_OFFLINE=1',
        'export HF_HUB_DISABLE_TELEMETRY=1',
        'export HF_HUB_DISABLE_IMPLICIT_TOKEN=1',
        'export HF_HUB_DISABLE_UPDATE_CHECK=1',
        'export PUBLIC_TRACE_CAPTURE_OFFLINE_QUARANTINE=hf_transformers_offline_env_before_runtime_import_v1',
    ]
    # Keep generated capture env files portable across zip extraction by
    # deriving the project root from the env file location when sourced. The
    # JSON audit below still records the concrete cache env seen during this run.
    lines.extend([
        '_PUBLIC_TRACE_ENV_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"',
        'export PUBLIC_TRACE_CACHE_ROOT="${PUBLIC_TRACE_CACHE_ROOT:-$_PUBLIC_TRACE_ENV_ROOT/artifacts/runtime/public-trace-hf-cache}"',
        'export HF_HOME="${HF_HOME:-$PUBLIC_TRACE_CACHE_ROOT/hf-home}"',
        'export HF_HUB_CACHE="${HF_HUB_CACHE:-$PUBLIC_TRACE_CACHE_ROOT/hub}"',
        'export HF_XET_CACHE="${HF_XET_CACHE:-$PUBLIC_TRACE_CACHE_ROOT/xet}"',
        'export HF_ASSETS_CACHE="${HF_ASSETS_CACHE:-$PUBLIC_TRACE_CACHE_ROOT/assets}"',
    ])
    cache_exports = {
        'PUBLIC_TRACE_CACHE_ROOT': os.environ.get('PUBLIC_TRACE_CACHE_ROOT', ''),
        'HF_HOME': os.environ.get('HF_HOME', ''),
        'HF_HUB_CACHE': os.environ.get('HF_HUB_CACHE', ''),
        'HF_XET_CACHE': os.environ.get('HF_XET_CACHE', ''),
        'HF_ASSETS_CACHE': os.environ.get('HF_ASSETS_CACHE', ''),
    }
    exports: dict[str, str] = {
        'PUBLIC_TRACE_CAPTURE_START_STATUS': status,
        'PUBLIC_TRACE_CAPTURE_START_DECISION': decision,
        'MODEL_ID': model_id,
        'MODEL_REVISION': revision,
        'PROMPT_MANIFEST': prompt_manifest,
        'CAPTURE_SNAPSHOT_SELECTION_CONTRACT': 'digest_verified_local_snapshot_path_v1',
        'HF_HUB_OFFLINE': '1',
        'TRANSFORMERS_OFFLINE': '1',
        'HF_HUB_DISABLE_TELEMETRY': '1',
        'HF_HUB_DISABLE_IMPLICIT_TOKEN': '1',
        'HF_HUB_DISABLE_UPDATE_CHECK': '1',
        'PUBLIC_TRACE_CAPTURE_OFFLINE_QUARANTINE': 'hf_transformers_offline_env_before_runtime_import_v1',
    }
    exports.update({k: v for k, v in cache_exports.items() if v})
    if selected_path and status == 'pass' and decision == 'capture_start_ready':
        lines.extend([
            f'export LOCAL_SNAPSHOT_DIR={shlex.quote(selected_path)}',
            f'export CAPTURE_MODEL={shlex.quote(selected_path)}',
            f'export CAPTURE_MODEL_SOURCE={shlex.quote("selected_digest_verified_local_snapshot")}',
            f'export MODEL_SAFETENSORS_SHA256={shlex.quote(str(selected.get("model_safetensors_sha256") or ""))}',
        ])
        exports.update({
            'LOCAL_SNAPSHOT_DIR': selected_path,
            'CAPTURE_MODEL': selected_path,
            'CAPTURE_MODEL_SOURCE': 'selected_digest_verified_local_snapshot',
            'MODEL_SAFETENSORS_SHA256': str(selected.get('model_safetensors_sha256') or ''),
        })
    else:
        lines.append('# No LOCAL_SNAPSHOT_DIR exported because capture is blocked or no digest-verified snapshot was selected.')
    out_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    try:
        out_path.chmod(0o644)
    except Exception:
        pass
    return exports


def main() -> int:
    ap = argparse.ArgumentParser(description='Machine-readable final preflight before local-only public trace capture.')
    ap.add_argument('--phase', choices=['capture'], default='capture')
    ap.add_argument('--strict', action='store_true')
    ap.add_argument('--require-weight-hash', action='store_true', default=os.environ.get('REQUIRE_WEIGHT_HASH') == '1')
    ap.add_argument('--capture-local-only', action='store_true', default=os.environ.get('CAPTURE_LOCAL_ONLY') == '1')
    args = ap.parse_args()

    packet_path = ROOT / 'artifacts' / 'run-manifests' / f'{REVUP}_TINYLLAMA_PUBLIC_TRACE_RUN_PACKET.json'
    packet = json.loads(packet_path.read_text(encoding='utf-8')) if packet_path.exists() else {}
    target = packet.get('target_model', {}) if isinstance(packet, dict) else {}
    model_id = str(os.environ.get('MODEL_ID') or target.get('model_id') or DEFAULT_MODEL_ID)
    revision = str(os.environ.get('MODEL_REVISION') or target.get('model_revision') or DEFAULT_REVISION)
    prompt_manifest = str(os.environ.get('PROMPT_MANIFEST') or f'artifacts/prompts/{REVUP}_PUBLIC_TRACE_PROMPTS.txt')
    allow_download_env = os.environ.get('ALLOW_DOWNLOAD', '0') == '1'
    capture_local_only = bool(args.capture_local_only)
    require_weight_hash = bool(args.require_weight_hash)

    modules = {name: module_presence(name) for name in CAPTURE_REQUIRED_MODULES}
    prompt = prompt_status(prompt_manifest)
    snapshot_checks = [inspect_snapshot(p, model_id=model_id, revision=revision, include_hashes=require_weight_hash) for p in snapshot_candidate_paths(model_id, revision)]
    complete_snapshot = any(bool(c.get('complete_required_snapshot')) for c in snapshot_checks)
    digest_verified_snapshot = any(bool(c.get('complete_required_snapshot')) and bool(c.get('model_safetensors', {}).get('sha256_matches_expected')) for c in snapshot_checks)
    selected_snapshot = choose_digest_verified_snapshot(snapshot_checks)
    selected_snapshot_path = str(selected_snapshot.get('path') or '')

    blockers: list[str] = []
    warnings: list[str] = []
    for name, rec in modules.items():
        if not rec.get('present'):
            blockers.append(f'{name}_not_importable')
    blockers.extend(str(b) for b in prompt.get('blockers', []))
    if not complete_snapshot:
        blockers.append('local_integrity_valid_tinyllama_snapshot_not_available')
    if require_weight_hash and not digest_verified_snapshot:
        blockers.append('local_digest_verified_tinyllama_snapshot_not_available')
    if require_weight_hash and digest_verified_snapshot and not selected_snapshot_path:
        blockers.append('digest_verified_snapshot_exists_but_no_selected_capture_path')
    if allow_download_env:
        warnings.append('ALLOW_DOWNLOAD_ignored_for_capture_start_capture_helper_uses_local_files_only')
    if not capture_local_only:
        blockers.append('capture_local_only_not_asserted')

    blockers = sorted(set(blockers))
    warnings = sorted(set(warnings))
    decision = 'capture_start_ready' if not blockers else 'do_not_start_capture'
    status = 'pass' if not blockers else 'blocked_here'
    capture_env_paths = [
        OUT_RUNTIME / 'CURRENT_PUBLIC_TRACE_CAPTURE_ENV.sh',
        OUT_MAN / f'{REVUP}_PUBLIC_TRACE_CAPTURE_ENV.sh',
    ]
    capture_env_exports = {}
    for env_path in capture_env_paths:
        capture_env_exports = write_capture_env(env_path, selected=selected_snapshot, model_id=model_id, revision=revision, prompt_manifest=prompt_manifest, status=status, decision=decision)
    audit = {
        'revision': REV,
        'revision_number': REVNO,
        'package_name': META.get('package_name'),
        'archive_name': META.get('archive_name'),
        'status': status,
        'decision': decision,
        'promotion_allowed': False,
        'public_pretrained_trace_loaded': False,
        'gpu_fused_kernel_measured': False,
        'summary': 'Final import-light capture-start report. It requires the exact prompt manifest, capture runtime module presence, and a local digest-verified TinyLlama snapshot because the capture helper is local-files-only unless --allow-download is explicitly passed, which public evidence capture wrappers forbid. It also writes Hugging Face/Transformers offline controls into the selected capture env so capture cannot depend on network or implicit Hub tokens after snapshot preparation.',
        'phase': 'capture',
        'capture_local_only': capture_local_only,
        'allow_download_env': allow_download_env,
        'allow_download_effective_for_capture': False,
        'require_weight_hash': require_weight_hash,
        'model_id': model_id,
        'model_revision': revision,
        'expected_model_safetensors_sha256': EXPECTED_MODEL_SAFETENSORS_SHA256,
        'required_snapshot_files': REQUIRED_SNAPSHOT_FILES,
        'prompt_manifest': prompt,
        'modules': modules,
        'snapshot_candidates': snapshot_checks,
        'complete_snapshot_available': complete_snapshot,
        'digest_verified_snapshot_available': digest_verified_snapshot,
        'selected_snapshot': selected_snapshot,
        'selected_snapshot_path': selected_snapshot_path,
        'selected_snapshot_digest_verified': bool(selected_snapshot_path and selected_snapshot.get('sha256_matches_expected') is True),
        'capture_model_source_contract': 'load_selected_digest_verified_local_snapshot_path',
        'capture_offline_quarantine_contract': 'hf_transformers_offline_env_before_runtime_import_v1',
        'cache_root_contract': 'project_local_hf_cache_root_v1',
        'capture_env_persists_cache_root': True,
        'capture_env_cache_exports': {k: v for k, v in capture_env_exports.items() if k in ['PUBLIC_TRACE_CACHE_ROOT', 'HF_HOME', 'HF_HUB_CACHE', 'HF_XET_CACHE', 'HF_ASSETS_CACHE']},
        'capture_offline_quarantine_exports': {
            'HF_HUB_OFFLINE': '1',
            'TRANSFORMERS_OFFLINE': '1',
            'HF_HUB_DISABLE_TELEMETRY': '1',
            'HF_HUB_DISABLE_IMPLICIT_TOKEN': '1',
            'HF_HUB_DISABLE_UPDATE_CHECK': '1',
        },
        'capture_env_paths': [str(p) for p in capture_env_paths],
        'capture_env_exports': capture_env_exports,
        'blockers': blockers,
        'warnings': warnings,
        'next_repair_if_blocked': [
            'run HASH_WEIGHTS=1 ALLOW_DOWNLOAD=1 bash artifacts/capture-kit/PREPARE_CURRENT_PUBLIC_TRACE_SNAPSHOT.sh to materialize and hash-check the reviewed TinyLlama snapshot, or mount it via LOCAL_SNAPSHOT_DIR',
            'install the capture runtime so numpy, torch, transformers, huggingface_hub, and safetensors are visible to this Python interpreter',
            'rerun capture with ALLOW_DOWNLOAD=0 CAPTURE_LOCAL_ONLY=1 after the local digest-verified snapshot is present',
        ],
        'source_basis': [
            {'url': 'https://huggingface.co/docs/transformers/en/installation', 'note': 'Offline Transformers runs require model files to be downloaded and cached ahead of time.'},
            {'url': 'https://huggingface.co/docs/huggingface_hub/en/guides/download', 'note': 'snapshot_download materializes repository files into a local cache/snapshot.'},
            {'url': 'https://huggingface.co/docs/hub/en/local-cache', 'note': 'The Hub cache has explicit snapshots/<commit> paths; capture should bind to the selected verified snapshot path rather than rely on ambiguous cache lookup.'},
            {'url': 'https://huggingface.co/docs/safetensors/en/metadata_parsing', 'note': 'Safetensors metadata/header parsing is cheap structural evidence, not a full-byte digest proof.'},
        ],
        'python': {'version': platform.python_version(), 'executable': sys.executable, 'platform': platform.platform()},
    }
    for out in [OUT_AUDIT / f'{REVUP}_PUBLIC_TRACE_CAPTURE_START_PREFLIGHT_REPORT.json', OUT_MAN / f'{REVUP}_PUBLIC_TRACE_CAPTURE_START_PREFLIGHT_REPORT.json', OUT_RUNTIME / 'CURRENT_CAPTURE_START_PREFLIGHT_REPORT.json']:
        out.write_text(json.dumps(audit, indent=2, sort_keys=False) + '\n', encoding='utf-8')
    md = [
        f'# Public trace capture-start preflight report — {REVUP}',
        '',
        f"Status: `{status}`  ",
        f"Decision: `{decision}`  ",
        'Promotion allowed: `false`',
        '',
        '## Blockers',
        '',
    ]
    md.extend([f'- `{b}`' for b in blockers] if blockers else ['- none'])
    md.extend(['', '## Warnings', ''])
    md.extend([f'- `{w}`' for w in warnings] if warnings else ['- none'])
    md.extend(['', '## Selected snapshot for capture', ''])
    md.append(f"- path: `{selected_snapshot_path or 'none'}`")
    md.append(f"- contract: `{selected_snapshot.get('selection_contract')}`")
    md.extend(['', '## Next repair', ''])
    md.extend([f'- {x}' for x in audit['next_repair_if_blocked']])
    (OUT_AUDIT / f'{REVUP}_PUBLIC_TRACE_CAPTURE_START_PREFLIGHT_REPORT.md').write_text('\n'.join(md) + '\n', encoding='utf-8')
    print(json.dumps({'status': status, 'decision': decision, 'selected_snapshot_path': selected_snapshot_path, 'blockers': blockers, 'warnings': warnings}, indent=2))
    return 0 if (not blockers or not args.strict) else 1


if __name__ == '__main__':
    raise SystemExit(main())
