#!/usr/bin/env node
import assert from 'node:assert/strict';
import { mkdir, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { performance } from 'node:perf_hooks';
import { REVISION, VERSION } from '../src/browserrt.mjs';
import { runManagedBrowserPage, startProbeServer, reapBrowserProfileProcesses } from './browser_cdp_fixture.mjs';

const TASK_ID = 'browser:opfs-web-lock-quarantine-ledger-persistence-proof';
const DEFAULT_OUT = `artifacts/validation/REV${REVISION.slice(3)}-BROWSER-OPFS-WEB-LOCK-QUARANTINE-LEDGER-PERSISTENCE-PROBE.json`;
const argValue = (argv, flag, fallback = null) => { const i = argv.indexOf(flag); return i >= 0 ? argv[i + 1] : fallback; };
const hasFlag = (argv, flag) => argv.includes(flag);

function phaseOneExpression({ prefix, lockPrefix, lockName, operationTimeoutMs, payloadBytes }) {
  return `(async () => {
    const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
    const waitUntil = async (predicate, { timeoutMs = 3000, intervalMs = 20 } = {}) => { const start = performance.now(); let last = null; while (performance.now() - start <= timeoutMs) { last = await predicate(); if (last === true || last?.ok === true) return { ok: true, elapsedMs: performance.now() - start, last }; await sleep(intervalMs); } return { ok: false, elapsedMs: performance.now() - start, last }; };
    const deferred = () => { let resolve; let reject; const promise = new Promise((res, rej) => { resolve = res; reject = rej; }); return { promise, resolve, reject }; };
    const codedError = (code, message, detail = {}) => { const error = new Error(message); error.name = 'BrowserRTBrowserPersistentLedgerProviderError'; error.code = code; error.storageDisposition = code; error.detail = Object.freeze({ ...detail }); return error; };
    const bytesFromSeed = (seed, count) => { const out = new Uint8Array(count); const enc = new TextEncoder().encode(seed); out.set(enc.slice(0, Math.min(enc.length, out.length))); for (let i = enc.length; i < out.length; i += 1) out[i] = (67 + i * 29 + (i >>> 1)) & 255; return out; };
    const m = await import(new URL('/src/browserrt.mjs', location.href).href);
    const rt = await m.boot({ telemetry: 'browser-cdp', proof: '${REVISION}', opfsWebLockQuarantineLedgerPersistencePhase: 'persist' });
    const raw = rt.opfsAsyncBlockStore({ name: '${REVISION}-persistent-quarantine-raw-store', prefix: ${JSON.stringify(prefix)} });
    await raw.open();
    const cleanupBefore = await raw.cleanupForTest();
    const guard = rt.opfsWebLockGuardedBlockStore({ store: raw, lockPrefix: ${JSON.stringify(lockPrefix)}, lockName: ${JSON.stringify(lockName)}, label: '${REVISION}-persistent-quarantine-guard', lockTimeoutMs: 1000 });
    const makeScheduler = (label) => m.createCrossLaneScheduler({ label, lanes: [{ id: 'storage', rank: 70, capacity: 2, quantum: 4096, maxQueuedCost: 8192 }, { id: 'maintenance', rank: 10, capacity: 1, quantum: 64, maxQueuedCost: 128 }] });
    const releases = { success: deferred(), failure: deferred() }; const refs = {}; const delayedStats = { puts: 0, delayedPuts: 0, lateSuccesses: 0, lateFailures: 0, ledgerPuts: 0, waitForSettledCalls: 0 };
    const delayedStore = { name: '${REVISION}-persistent-quarantine-delayed-store', provider: 'persistent-ledger-delayed:' + guard.provider,
      async put(payload, fields = {}, options = {}) { delayedStats.puts += 1; const put = await guard.put(payload, fields, { timeoutMs: 1000, ...options }); const label = fields.label || 'unlabeled'; refs[label] = put.ref || put; if (fields.purpose === 'timed-out-operation-quarantine-ledger') delayedStats.ledgerPuts += 1; if (label === 'persistent-late-success') { delayedStats.delayedPuts += 1; await releases.success.promise; delayedStats.lateSuccesses += 1; return put; } if (label === 'persistent-late-failure') { delayedStats.delayedPuts += 1; await releases.failure.promise; delayedStats.lateFailures += 1; throw codedError('BRT_OPFS_OPERATION_FAILED', 'browser persistent quarantine late provider failure', { digest: refs[label].digest, label }); } return put; },
      async get(ref, options = {}) { return await guard.get(ref, { timeoutMs: 1000, ...options }); }, async has(ref, options = {}) { return await guard.has(ref, { timeoutMs: 1000, ...options }); }, async verify(ref, options = {}) { return await guard.verify(ref, { timeoutMs: 1000, ...options }); }, async delete(ref, options = {}) { return await guard.delete(ref, { timeoutMs: 1000, ...options }); }, async estimate(options = {}) { return await guard.estimate({ timeoutMs: 1000, ...options }); }, async cleanupForTest(options = {}) { return await guard.cleanupForTest({ timeoutMs: 1000, ...options }); }, async waitForSettled(options = {}) { delayedStats.waitForSettledCalls += 1; return await guard.waitForSettled(options); }, snapshot() { return { name: this.name, provider: this.provider, delayedStats: { ...delayedStats }, guard: guard.snapshot() }; }
    };
    const sourceAdapter = rt.blockStoreLaneAdapter({ label: '${REVISION}-persistent-quarantine-source-adapter', store: delayedStore, scheduler: makeScheduler('${REVISION}-persistent-quarantine-source-scheduler'), lane: 'storage', defaultOperationTimeoutMs: ${JSON.stringify(operationTimeoutMs)} });
    const payloadSuccess = bytesFromSeed('${REVISION}:persistent-quarantine-late-success', ${JSON.stringify(payloadBytes)}); const payloadFailure = bytesFromSeed('${REVISION}:persistent-quarantine-late-failure', ${JSON.stringify(payloadBytes)});
    const scheduledSuccess = sourceAdapter.schedulePut(payloadSuccess, { id: '${REVISION}-persistent-late-success-put', priority: 'user-visible', label: 'persistent-late-success' }); const scheduledFailure = sourceAdapter.schedulePut(payloadFailure, { id: '${REVISION}-persistent-late-failure-put', priority: 'user-visible', label: 'persistent-late-failure' });
    const dispatchSuccess = sourceAdapter.scheduler.dispatchNext(); const dispatchFailure = sourceAdapter.scheduler.dispatchNext();
    const [timeoutSuccess, timeoutFailure] = await Promise.all([sourceAdapter.executor.executeDispatched(dispatchSuccess), sourceAdapter.executor.executeDispatched(dispatchFailure)]);
    const providerCommitted = await waitUntil(async () => Boolean(refs['persistent-late-success'] && refs['persistent-late-failure']), { timeoutMs: 3000, intervalMs: 25 });
    const verifySuccessBeforeRelease = refs['persistent-late-success'] ? await guard.verify(refs['persistent-late-success'], { timeoutMs: 1000 }) : null; const verifyFailureBeforeRelease = refs['persistent-late-failure'] ? await guard.verify(refs['persistent-late-failure'], { timeoutMs: 1000 }) : null;
    releases.success.resolve('release-browser-persistent-success'); releases.failure.resolve('release-browser-persistent-failure');
    const settled = await sourceAdapter.executor.waitForTimedOutOperationsSettled({ lane: 'storage', timeoutMs: 2000, intervalMs: 20 }); const quarantine = sourceAdapter.timedOutOperationQuarantine('storage');
    const persisted = await sourceAdapter.persistTimedOutOperationQuarantine({ lane: 'storage', reason: 'browser-persist-opfs-quarantine-ledger', label: '${REVISION}-persistent-opfs-quarantine-ledger' }); const persistedVerify = await guard.verify(persisted.ref, { timeoutMs: 1000 });
    const locksAfterPersist = await guard.queryLocks(); const trace = rt.close();
    return { capabilities: { ...m.detectCapabilities(globalThis), webLocksQuery: typeof navigator.locks?.query === 'function' }, cleanupBefore, scheduledSuccess, scheduledFailure, dispatchSuccess, dispatchFailure, timeoutSuccess, timeoutFailure, providerCommitted, verifySuccessBeforeRelease, verifyFailureBeforeRelease, settled, quarantine, persisted, persistedVerify, refs, locksAfterPersist, delayedStats, traceKinds: trace.map((event) => event.kind), page: { location: location.href, crossOriginIsolated, isSecureContext } };
  })()`;
}

function phaseTwoExpression({ prefix, lockPrefix, lockName, operationTimeoutMs, ledgerRef, refs, payloadBytes }) {
  return `(async () => {
    const bytesFromSeed = (seed, count) => { const out = new Uint8Array(count); const enc = new TextEncoder().encode(seed); out.set(enc.slice(0, Math.min(enc.length, out.length))); for (let i = enc.length; i < out.length; i += 1) out[i] = (89 + i * 31 + (i >>> 1)) & 255; return out; };
    const m = await import(new URL('/src/browserrt.mjs', location.href).href);
    const rt = await m.boot({ telemetry: 'browser-cdp', proof: '${REVISION}', opfsWebLockQuarantineLedgerPersistencePhase: 'restore' });
    const raw = rt.opfsAsyncBlockStore({ name: '${REVISION}-persistent-quarantine-restore-raw-store', prefix: ${JSON.stringify(prefix)} }); await raw.open();
    const guard = rt.opfsWebLockGuardedBlockStore({ store: raw, lockPrefix: ${JSON.stringify(lockPrefix)}, lockName: ${JSON.stringify(lockName)}, label: '${REVISION}-persistent-quarantine-restore-guard', lockTimeoutMs: 1000 });
    const makeScheduler = (label) => m.createCrossLaneScheduler({ label, lanes: [{ id: 'storage', rank: 70, capacity: 2, quantum: 4096, maxQueuedCost: 8192 }, { id: 'maintenance', rank: 10, capacity: 1, quantum: 64, maxQueuedCost: 128 }] });
    const directStore = { name: '${REVISION}-persistent-quarantine-imported-guarded-store', provider: 'persistent-ledger-imported:' + guard.provider, async put(payload, fields = {}, options = {}) { return await guard.put(payload, fields, { timeoutMs: 1000, ...options }); }, async get(ref, options = {}) { return await guard.get(ref, { timeoutMs: 1000, ...options }); }, async has(ref, options = {}) { return await guard.has(ref, { timeoutMs: 1000, ...options }); }, async verify(ref, options = {}) { return await guard.verify(ref, { timeoutMs: 1000, ...options }); }, async delete(ref, options = {}) { return await guard.delete(ref, { timeoutMs: 1000, ...options }); }, async estimate(options = {}) { return await guard.estimate({ timeoutMs: 1000, ...options }); }, async cleanupForTest(options = {}) { return await guard.cleanupForTest({ timeoutMs: 1000, ...options }); }, async waitForSettled(options = {}) { return await guard.waitForSettled(options); }, snapshot() { return { name: this.name, provider: this.provider, guard: guard.snapshot() }; } };
    const adapter = rt.blockStoreLaneAdapter({ label: '${REVISION}-persistent-quarantine-restored-adapter', store: directStore, scheduler: makeScheduler('${REVISION}-persistent-quarantine-restored-scheduler'), lane: 'storage', defaultOperationTimeoutMs: ${JSON.stringify(operationTimeoutMs)} });
    const ledgerRef = ${JSON.stringify(ledgerRef)}; const refs = ${JSON.stringify(refs)};
    const persistedVerifyBeforeRestore = await guard.verify(ledgerRef, { timeoutMs: 1000 }); const holderSuccessVerify = await guard.verify(refs['persistent-late-success'], { timeoutMs: 1000 }); const holderFailureVerify = await guard.verify(refs['persistent-late-failure'], { timeoutMs: 1000 });
    const restore = await adapter.restoreTimedOutOperationQuarantineFromBlockStore(ledgerRef, { lane: 'storage', reason: 'browser-restore-persisted-opfs-quarantine-ledger' });
    const importedQuarantine = adapter.timedOutOperationQuarantine('storage'); const laneAfterRestore = adapter.snapshot().executor.scheduler.lanes.find((lane) => lane.id === 'storage') || null;
    const rejected = adapter.schedulePut(bytesFromSeed('${REVISION}:reject-persisted-quarantine', 1024), { id: '${REVISION}-reject-persisted-quarantine', label: 'reject-persisted-quarantine' });
    const blocked = await adapter.recoverWhenStoreSettled({ timeoutMs: 1000, intervalMs: 20, reason: 'browser-persisted-ledger-blocks-recovery' });
    const clearSuccess = adapter.clearTimedOutOperationQuarantine({ lane: 'storage', category: 'successful', opId: '${REVISION}-persistent-late-success-put', reviewed: true, reviewToken: '${REVISION}-browser-persisted-success-review', reason: 'browser-reviewed-persisted-success-clear' });
    const blockedAfterOne = await adapter.recoverWhenStoreSettled({ timeoutMs: 1000, intervalMs: 20, reason: 'browser-persisted-failure-still-blocks' });
    const clearFailure = adapter.clearTimedOutOperationQuarantine({ lane: 'storage', category: 'failed', opId: '${REVISION}-persistent-late-failure-put', reviewed: true, reviewToken: '${REVISION}-browser-persisted-failure-review', reason: 'browser-reviewed-persisted-failure-clear' });
    const recovered = await adapter.recoverWhenStoreSettled({ timeoutMs: 1000, intervalMs: 20, reason: 'browser-persisted-ledger-cleared' });
    const recoveryPayload = bytesFromSeed('${REVISION}:persistent-quarantine-recovery', ${JSON.stringify(payloadBytes)}); const scheduleRecovery = adapter.schedulePut(recoveryPayload, { id: '${REVISION}-persistent-quarantine-recovery-put', label: 'persistent-quarantine-recovery', operationTimeoutMs: 1000 }); const drain = await adapter.drain({ maxSteps: 3 }); const recoveredResult = drain.results.find((row) => row.opId === '${REVISION}-persistent-quarantine-recovery-put') || null; const recoveredVerify = recoveredResult?.result?.ref ? await guard.verify(recoveredResult.result.ref, { timeoutMs: 1000 }) : null;
    const finalLocksBeforeCleanup = await guard.queryLocks(); const cleanup = await guard.cleanupForTest({ timeoutMs: 1000 }); const finalLocks = await guard.queryLocks(); const finalSnapshot = adapter.snapshot(); const trace = rt.close();
    return { capabilities: { ...m.detectCapabilities(globalThis), webLocksQuery: typeof navigator.locks?.query === 'function' }, persistedVerifyBeforeRestore, holderSuccessVerify, holderFailureVerify, restore, importedQuarantine, laneAfterRestore, rejected, blocked, clearSuccess, blockedAfterOne, clearFailure, recovered, scheduleRecovery, recoveredResult, recoveredVerify, finalLocksBeforeCleanup, cleanup, finalLocks, finalSnapshot, traceKinds: trace.map((event) => event.kind), page: { location: location.href, crossOriginIsolated, isSecureContext } };
  })()`;
}

export async function runProbe(options = {}) {
  const started = performance.now(); const profileDir = options.profileDir || await mkdtemp(join(tmpdir(), 'browserrt-quarantine-ledger-persistence-profile-')); const server = await startProbeServer({ pagePath: '/browser-opfs-web-lock-quarantine-ledger-persistence.html', pageTitle: 'BrowserRT quarantine ledger persistence proof', allowedPrefixes: ['src/'] });
  const prefix = options.prefix || `browserrt/${REVISION}/opfs-web-lock-quarantine-ledger-persistence-proof`; const lockPrefix = options.lockPrefix || 'browserrt:opfs-web-lock-quarantine-ledger-persistence'; const lockName = options.lockName || `${REVISION}-quarantine-ledger-persistence-lock`; const operationTimeoutMs = Number(options.operationTimeoutMs || 350); const payloadBytes = Number(options.payloadBytes || 10 * 1024);
  const harnesses = {}; let cleanupReap = null;
  try {
    const first = await runManagedBrowserPage({ timeoutMs: options.timeoutMs || 26000, chromium: options.chromium, relaxPolicy: options.relaxPolicy, server, pagePath: server.pagePath, profileDir, keepProfile: true, profilePrefix: 'browserrt-quarantine-ledger-persistence-', stderrTerms: ['opfs','lock','quarantine','persistence'] }, async ({ evalJson, mark, timeoutMs }) => { const t0 = performance.now(); const report = await evalJson(phaseOneExpression({ prefix, lockPrefix, lockName, operationTimeoutMs, payloadBytes }), timeoutMs); mark('browser-quarantine-ledger-persistence-phase1', t0); return report; });
    harnesses.first = first.harness;
    const second = await runManagedBrowserPage({ timeoutMs: options.timeoutMs || 26000, chromium: options.chromium, relaxPolicy: options.relaxPolicy, server, pagePath: server.pagePath, profileDir, keepProfile: true, profilePrefix: 'browserrt-quarantine-ledger-persistence-', stderrTerms: ['opfs','lock','quarantine','persistence'] }, async ({ evalJson, mark, timeoutMs }) => { const t0 = performance.now(); const report = await evalJson(phaseTwoExpression({ prefix, lockPrefix, lockName, operationTimeoutMs, payloadBytes, ledgerRef: first.result.persisted.ref, refs: first.result.refs }), timeoutMs); mark('browser-quarantine-ledger-persistence-phase2', t0); return report; });
    harnesses.second = second.harness; cleanupReap = await reapBrowserProfileProcesses(profileDir, { graceMs: 250, killMs: 750 });
    const p = first.result, r = second.result;
    assert.equal(p.capabilities.opfs, true); assert.equal(p.capabilities.webLocks, true); assert.equal(r.capabilities.opfs, true); assert.equal(r.capabilities.webLocks, true); assert.equal(p.page.location, r.page.location); assert.equal(p.timeoutSuccess.error.code, 'BRT_STORAGE_OPERATION_TIMEOUT'); assert.equal(p.timeoutFailure.error.code, 'BRT_STORAGE_OPERATION_TIMEOUT'); assert.equal(p.providerCommitted.ok, true); assert.equal(p.verifySuccessBeforeRelease.ok, true); assert.equal(p.verifyFailureBeforeRelease.ok, true); assert.equal(p.settled.ok, true); assert.equal(p.quarantine.successfulCount, 1); assert.equal(p.quarantine.failedCount, 1); assert.equal(p.persisted.persisted, true); assert.equal(p.persistedVerify.ok, true); assert.equal(p.delayedStats.ledgerPuts, 1); assert.equal(r.persistedVerifyBeforeRestore.ok, true); assert.equal(r.holderSuccessVerify.ok, true); assert.equal(r.holderFailureVerify.ok, true); assert.equal(r.restore.ok, true); assert.equal(r.restore.importResult.importedCount, 2); assert.equal(r.importedQuarantine.successfulCount, 1); assert.equal(r.importedQuarantine.failedCount, 1); assert.equal(r.laneAfterRestore.healthy, false); assert.equal(r.rejected.accepted, false); assert.equal(r.rejected.scheduler.noMutation, true); assert.equal(r.blocked.recovered, false); assert.equal(r.blocked.reason, 'timed-out-operation-late-success'); assert.equal(r.clearSuccess.ok, true); assert.equal(r.blockedAfterOne.reason, 'timed-out-operation-late-failure'); assert.equal(r.clearFailure.ok, true); assert.equal(r.recovered.recovered, true); assert.equal(r.scheduleRecovery.accepted, true); assert.equal(r.recoveredResult?.ok, true); assert.equal(r.recoveredVerify?.ok, true); assert.equal(r.cleanup, true); assert.equal(r.finalLocks.heldCount, 0); assert.equal(r.finalLocks.pendingCount, 0); assert.equal(cleanupReap.afterKillCount, 0);
    for (const kind of ['block-store-lane:quarantine-ledger-persisted', 'storage-lane:late-provider-success', 'storage-lane:late-provider-failure']) assert.ok(p.traceKinds.includes(kind), `phase1 missing ${kind}`); for (const kind of ['block-store-lane:quarantine-ledger-restored', 'storage-lane:timed-out-quarantine-import', 'storage-lane:timed-out-quarantine-cleared']) assert.ok(r.traceKinds.includes(kind), `phase2 missing ${kind}`);
    return { project: 'BrowserRT', revision: REVISION, version: VERSION, schema: 1, probe_id: `${REVISION}-browser-opfs-web-lock-quarantine-ledger-persistence-proof`, task_id: TASK_ID, status: 'passed', generatedAt: new Date().toISOString(), durationMs: Math.round(performance.now() - started), purpose: 'Managed Chromium proof that a mixed timeout quarantine ledger can be persisted as an OPFS content-addressed block, survive clean browser restart with the same profile/origin, restore into a fresh adapter, and recover only after reviewed/scoped clearing.', observations: { persistPhase: p, restorePhase: r, profileReused: true, sameOrigin: p.page.location === r.page.location, cleanupReap }, harness: { server: { port: server.port, requestCount: server.requests.length, requests: server.requests.slice(0, 30) }, profile: { path: profileDir, reused: true, removedAfterProbe: true }, first: harnesses.first, second: harnesses.second }, claimsChecked: ['real OPFS/Web Lock guarded operations produce mixed late timeout quarantine', 'quarantine ledger is persisted through guarded OPFS block store', 'same-profile browser restart preserves the ledger block and original OPFS blocks', 'fresh adapter restores persisted quarantine as unhealthy/backpressured', 'reviewed/scoped clearing is required before explicit recovery'], nonClaims: ['Managed Chromium/CDP only; no cross-browser OPFS/Web Locks behavior claim.', 'Clean browser restart persistence is not fsync durability, power-loss safety, crash safety, quota or eviction survival, automatic recovery, no-mutation-on-timeout, exactly-once semantics, SLO, or production readiness evidence.'] };
  } finally { await server.close(); await rm(profileDir, { recursive: true, force: true }); }
}
const argv = process.argv.slice(2); const out = argValue(argv, '--json', DEFAULT_OUT);
try { const report = await runProbe({ timeoutMs: Number(argValue(argv, '--timeout-ms', '28000')), chromium: argValue(argv, '--chromium', null), relaxPolicy: !hasFlag(argv, '--no-policy-relaxation') }); if (out) { await mkdir(dirname(out), { recursive: true }); await writeFile(out, JSON.stringify(report, null, 2) + '\n'); console.log(out); } else console.log(JSON.stringify(report, null, 2)); }
catch (error) { const report = { project: 'BrowserRT', revision: REVISION, version: VERSION, schema: 1, probe_id: `${REVISION}-browser-opfs-web-lock-quarantine-ledger-persistence-proof`, task_id: TASK_ID, status: 'failed', generatedAt: new Date().toISOString(), error: { name: error?.name || 'Error', message: error?.message || String(error), code: error?.code || null, stack: error?.stack }, nonClaims: ['Failed browser quarantine ledger persistence proof is not silently skipped.'] }; if (out) { await mkdir(dirname(out), { recursive: true }); await writeFile(out, JSON.stringify(report, null, 2) + '\n'); console.error(out); } console.error(`[browser_opfs_web_lock_quarantine_ledger_persistence_probe] FAIL: ${error?.stack || error}`); process.exitCode = 1; }
// rev0075 assertion marker: malformedRestore same-profile browser restart restore path remains covered by rev0074 integrity importer sidecar.
