#!/usr/bin/env node
import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { REVISION, VERSION } from '../src/browserrt.mjs';
const TASK_ID='facility:storage-lane-quarantine-restore-backpressure-contract-audit';
const CURRENT_BROWSER='browser:opfs-web-lock-quarantine-restore-backpressure-proof';
const CURRENT_RELEASE='scheduler:storage-lane-quarantine-restore-backpressure-proof';
const DEFAULT_OUT=`artifacts/audit/REV${REVISION.slice(3)}-STORAGE-LANE-QUARANTINE-RESTORE-BACKPRESSURE-CONTRACT-AUDIT.json`;
const argValue=(argv,flag,fallback=null)=>{const i=argv.indexOf(flag);return i>=0?argv[i+1]:fallback;};
async function text(p){return readFile(p,'utf8');} function missing(body,needles){return needles.filter(n=>!String(body).includes(n));} function check(a,n,p,d={}){a.push({name:n,status:p?'passed':'failed',...d});}
export async function runAudit(){ const files=Object.fromEntries(await Promise.all(['src/storage-lane-scheduler.mjs','src/block-store-lane-adapter.mjs','src/types.d.ts','tools/storage_lane_quarantine_restore_backpressure_probe.mjs','tools/browser_opfs_web_lock_quarantine_restore_backpressure_probe.mjs','docs/40-validation/storage-lane-quarantine-restore-backpressure-slice.md','docs/40-validation/browser-opfs-web-lock-quarantine-restore-backpressure-slice.md','docs/40-validation/storage-lane-quarantine-restore-backpressure-contract-audit-slice.md','test/manifest.json','test/impact-map.json','test/surface-inventory.json','package.json','Makefile','README.md','START_HERE.md','AGENTS.md','CONTEXT-PACK.md','CUBE-META.json','REVISION-RECEIPT.json','REENTRY-CONTRACT.json','SURFACE-STATUS.json','VALIDATION-INDEX.json'].map(async p=>[p,await text(p)])));
 const manifest=JSON.parse(files['test/manifest.json']); const taskIds=new Set((manifest.tasks||[]).map(t=>t.id)); const checks=[];
 check(checks,'scheduler-forces-backpressure-on-nonempty-import',missing(files['src/storage-lane-scheduler.mjs'],['quarantineLedgerImportBackpressureForced','markUnhealthyForced','markUnhealthyRequested','storage-lane:timed-out-quarantine-import-backpressure-forced','timed-out-operation-quarantine-imported']).length===0);
 check(checks,'release-browser-proofs-wired',missing(files['tools/storage_lane_quarantine_restore_backpressure_probe.mjs']+files['tools/browser_opfs_web_lock_quarantine_restore_backpressure_probe.mjs'],[CURRENT_RELEASE,CURRENT_BROWSER,'markUnhealthy:false','markUnhealthyForced','noMutation','quarantineLedgerImportBackpressureForced']).length===0);
 check(checks,'docs-preserve-nonclaims',missing(files['docs/40-validation/storage-lane-quarantine-restore-backpressure-slice.md']+files['docs/40-validation/browser-opfs-web-lock-quarantine-restore-backpressure-slice.md']+files['docs/40-validation/storage-lane-quarantine-restore-backpressure-contract-audit-slice.md'],['markUnhealthy','forced lane backpressure','noMutation','cross-browser','durability','production readiness']).length===0);
 check(checks,'manifest-tasks-present',[CURRENT_RELEASE,CURRENT_BROWSER,TASK_ID].every(id=>taskIds.has(id)),{missing:[CURRENT_RELEASE,CURRENT_BROWSER,TASK_ID].filter(id=>!taskIds.has(id))});
 for(const [name,body] of Object.entries({impact:files['test/impact-map.json'],surfaces:files['test/surface-inventory.json'],makefile:files.Makefile,packageJson:files['package.json']})) check(checks,`${name}-references-current-slice`,body.includes('quarantine-restore-backpressure')&&body.includes(TASK_ID));
 check(checks,'first-read-current-office',['README.md','START_HERE.md','AGENTS.md','CONTEXT-PACK.md','CUBE-META.json','REVISION-RECEIPT.json','REENTRY-CONTRACT.json','SURFACE-STATUS.json','VALIDATION-INDEX.json'].every(p=>files[p].includes('OPFS Web Lock Quarantine Restore Backpressure Proof')&&files[p].includes(CURRENT_BROWSER)&&files[p].includes(TASK_ID)));
 check(checks,'package-current-office',files['package.json'].includes('"revision": "'+REVISION+'"')&&files['package.json'].includes('opfs-web-lock-quarantine-restore-backpressure-proof')&&files['package.json'].includes(CURRENT_BROWSER)&&files['package.json'].includes(TASK_ID));
 check(checks,'types-current-and-hook-markers',missing(files['src/types.d.ts'],[`REVISION: '${REVISION}'`,`VERSION: '${VERSION}'`,'quarantineLedgerImportBackpressureForced','markUnhealthyForced','storage-lane:timed-out-quarantine-import-backpressure-forced']).length===0);
 const failed=checks.filter(r=>r.status!=='passed'); assert.equal(failed.length,0,failed.map(r=>`${r.name}: ${JSON.stringify(r)}`).join('\n'));
 return {project:'BrowserRT',revision:REVISION,version:VERSION,schema:1,task_id:TASK_ID,status:'passed',generatedAt:new Date().toISOString(),checks,purpose:'Static contract audit for quarantine restore backpressure wiring.',nonClaims:['Static audit only; no browser execution, cancellation, rollback, durability, quota, eviction, SLO, or production readiness evidence.']}; }
const out=argValue(process.argv.slice(2),'--json',DEFAULT_OUT); try{const r=await runAudit(); if(out){await mkdir(dirname(out),{recursive:true}); await writeFile(out,JSON.stringify(r,null,2)+'\n'); console.log(out);} else console.log(JSON.stringify(r,null,2));}catch(error){const r={project:'BrowserRT',revision:REVISION,version:VERSION,schema:1,task_id:TASK_ID,status:'failed',generatedAt:new Date().toISOString(),error:{name:error?.name||'Error',message:error?.message||String(error),stack:error?.stack},nonClaims:['Failed audit is not silently skipped.']}; if(out){await mkdir(dirname(out),{recursive:true}); await writeFile(out,JSON.stringify(r,null,2)+'\n'); console.error(out);} console.error(`[storage_lane_quarantine_restore_backpressure_contract_audit] FAIL: ${error?.stack||error}`); process.exitCode=1;}
// surface:storage-lane-quarantine-restore-backpressure surface:browser-opfs-web-lock-quarantine-restore-backpressure surface:storage-lane-quarantine-restore-backpressure-contract-audit
