import json
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REV = "rev0203"
PREV = "rev0202"
TS = "2026-06-13T13:03:00Z"


def load(rel):
    return json.loads((ROOT / rel).read_text(encoding="utf-8"))


def dump(rel, data):
    (ROOT / rel).parent.mkdir(parents=True, exist_ok=True)
    (ROOT / rel).write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def write(rel, text):
    (ROOT / rel).parent.mkdir(parents=True, exist_ok=True)
    (ROOT / rel).write_text(text.rstrip() + "\n", encoding="utf-8")

# --- Version -----------------------------------------------------------------
write("VERSION", REV)

# --- New operational doc ------------------------------------------------------
write("docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md", r"""
# Computed Live-Floor Engine and Artifact Admission Checklist

rev0203 closes the next practical receipt-risk seam: live-floor state cannot be trusted when it appears only as edited text in a quorum ledger, import narrative, or public shell. The archive now has request, custody, envelope, response, intake, import, challenge, rollback, class-local replay, recomputation, and failed-gate surfaces. The remaining operational risk is that future contributors may update one surface but forget the others, or may treat a checklist as proof that a live counterparty artifact exists.

The rev0203 rule is strict: **computed floor is source of truth**.

## What this pass adds

The new `live-receipt-floor-computed-snapshot` object is generated by `tools/compute_live_receipt_floor.py`. It reads import gates, import attempts, challenge/rollback records, class-local replays, quorum recomputation reports, and failed-gate public summaries. It then recomputes the archive live receipt floor from the evidence path rather than trusting hand-edited fields.

The current generated snapshot intentionally remains zero-weight. It finds no eligible live imports, no satisfied live receipt classes, and no cross-critical quorum. It also records the dry-run/fixture/challenged exclusions that explain why existing artifacts cannot update reliance.

## Core rules

**Computed floor is source of truth.** A quorum ledger, live packet, or public summary cannot upgrade reliance unless the computed snapshot agrees with the import gates and challenge state.

**Admission checklist is not admission.** A completed custody checklist, authority checklist, artifact locator, or request packet remains pre-admission until a real live artifact passes custody and import-gate rules.

**Artifact quarantine comes before response creation.** If raw custody, hash, authority scope, non-host retention, sealed/public boundary, or dependency-group checks are absent, the artifact stays quarantined and cannot become a response, intake, or import.

**Failed-gate publication follows every non-import.** Defective, dry-run, fixture, declined, expired, challenged, rolled-back, or quarantined branches must appear in a public failed-gate shell with sealed details withheld where necessary.

**One valid class remains class-local.** Even a future actual result-return import can satisfy only result-return unless the full cross-critical receipt floor is recomputed as met.

## Refactor effect

rev0203 adds a generated state layer over the receipt chain:

1. counterparty artifact custody,
2. non-host artifact envelope,
3. response record,
4. intake record,
5. actual import gate,
6. import challenge and rollback,
7. live/class-local replay,
8. quorum recomputation,
9. computed live-floor snapshot,
10. public failed-gate disclosure.

The snapshot is deliberately generated by a tool and then audited against the checked-in example. This prevents release authors from editing a single JSON field to create apparent live evidence.

## Current reliance posture

No actual live external receipt exists in this archive. `independent_receipts_present` remains zero. The new engine makes that zero state machine-checkable and keeps the next real live artifact from bypassing custody, import, challenge, class-local, recomputation, and failed-gate gates.
""")

# Add short backlinks to prior operational surfaces.
for rel, addition in {
    "docs/30-transition/import-challenge-rollback-and-reliance-reversal.md": "\n\n## rev0203 computed-floor hook\n\nrev0203 adds `docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md` and a generated live-floor snapshot. A rollback or challenge state is not durable until the computed floor confirms the live-floor effect and failed-gate publication state. Computed floor is source of truth.\n",
    "docs/30-transition/counterparty-artifact-custody-and-authority-handoff.md": "\n\n## rev0203 computed-floor hook\n\nrev0203 adds a generated live-floor snapshot and artifact admission checklist. Custody readiness stays pre-admission until the computed floor, import gate, and challenge/rollback path agree; admission checklist is not admission.\n",
}.items():
    text = (ROOT / rel).read_text(encoding="utf-8")
    if "## rev0203 computed-floor hook" not in text:
        write(rel, text + addition)

# --- Schema ------------------------------------------------------------------
schema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.org/ai-personhood/schemas/live-receipt-floor-computed-snapshot.schema.json",
  "title": "Live Receipt Floor Computed Snapshot",
  "description": "Generated source-of-truth snapshot for live receipt floor and class coverage, computed from import gates, challenges, replays, and failed-gate summaries.",
  "type": "object",
  "additionalProperties": False,
  "required": [
    "snapshot_id", "schema_version", "created_at", "revision", "linked_live_drill_packet", "generated_by_tool",
    "input_scope", "computation_rules", "computed_floor", "exclusion_register", "mismatch_checks", "decision"
  ],
  "properties": {
    "snapshot_id": {"type": "string", "pattern": "^LRFCS-[0-9]{4}-[A-Za-z0-9._:-]+$"},
    "schema_version": {"const": "live-receipt-floor-computed-snapshot-v0.1"},
    "created_at": {"type": "string", "format": "date-time"},
    "revision": {"type": "string", "pattern": "^rev[0-9]{4}$"},
    "linked_live_drill_packet": {"type": "string"},
    "generated_by_tool": {"type": "string"},
    "input_scope": {
      "type": "object", "additionalProperties": False,
      "required": ["import_gate_paths", "import_attempt_paths", "challenge_record_paths", "class_local_replay_paths", "quorum_report_paths", "failed_gate_summary_paths"],
      "properties": {k: {"type": "array", "items": {"type": "string"}} for k in ["import_gate_paths", "import_attempt_paths", "challenge_record_paths", "class_local_replay_paths", "quorum_report_paths", "failed_gate_summary_paths"]}
    },
    "computation_rules": {
      "type": "object", "additionalProperties": False,
      "required": ["source_of_truth", "eligible_import_rule", "challenge_rule", "class_local_rule", "manual_override_rule"],
      "properties": {
        "source_of_truth": {"type": "string"},
        "eligible_import_rule": {"type": "string"},
        "challenge_rule": {"type": "string"},
        "class_local_rule": {"type": "string"},
        "manual_override_rule": {"type": "string"}
      }
    },
    "computed_floor": {
      "type": "object", "additionalProperties": False,
      "required": ["live_floor_before", "live_floor_delta", "independent_receipts_present", "eligible_live_imports", "live_classes_satisfied", "required_live_classes", "missing_live_classes", "live_quorum_satisfied", "cross_critical_quorum_satisfied", "reliance_effect"],
      "properties": {
        "live_floor_before": {"type": "integer", "minimum": 0},
        "live_floor_delta": {"type": "integer"},
        "independent_receipts_present": {"type": "integer", "minimum": 0},
        "eligible_live_imports": {"type": "array", "items": {"type": "string"}},
        "live_classes_satisfied": {"type": "array", "items": {"type": "string"}},
        "required_live_classes": {"type": "array", "items": {"type": "string"}, "minItems": 1},
        "missing_live_classes": {"type": "array", "items": {"type": "string"}},
        "live_quorum_satisfied": {"type": "boolean"},
        "cross_critical_quorum_satisfied": {"type": "boolean"},
        "reliance_effect": {"type": "string", "enum": ["stayed", "conditional", "ordinary-reliance", "blocked"]}
      }
    },
    "exclusion_register": {
      "type": "array", "items": {
        "type": "object", "additionalProperties": False,
        "required": ["source_ref", "source_type", "receipt_class", "exclusion_reason", "failed_gate_summary_required"],
        "properties": {
          "source_ref": {"type": "string"},
          "source_type": {"type": "string"},
          "receipt_class": {"type": "string"},
          "exclusion_reason": {"type": "string"},
          "failed_gate_summary_required": {"type": "boolean"}
        }
      }
    },
    "mismatch_checks": {
      "type": "object", "additionalProperties": False,
      "required": ["live_packet_floor_matches", "manual_ledger_override_detected", "stale_report_detected", "failed_gate_public_summary_present_for_exclusions", "frontdoor_revision_matches"],
      "properties": {
        "live_packet_floor_matches": {"type": "boolean"},
        "manual_ledger_override_detected": {"type": "boolean"},
        "stale_report_detected": {"type": "boolean"},
        "failed_gate_public_summary_present_for_exclusions": {"type": "boolean"},
        "frontdoor_revision_matches": {"type": "boolean"}
      }
    },
    "decision": {
      "type": "object", "additionalProperties": False,
      "required": ["archive_live_floor_update_allowed", "may_upgrade_reliance", "next_live_action", "blocked_actions"],
      "properties": {
        "archive_live_floor_update_allowed": {"type": "boolean"},
        "may_upgrade_reliance": {"type": "boolean"},
        "next_live_action": {"type": "string"},
        "blocked_actions": {"type": "array", "items": {"type": "string"}}
      }
    }
  }
}
dump("schemas/live-receipt-floor-computed-snapshot.schema.json", schema)

# --- Tool: compute live receipt floor ----------------------------------------
write("tools/compute_live_receipt_floor.py", r'''#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REV = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
CREATED_AT = "2026-06-13T13:03:00Z"
REQUIRED_CLASSES = [
    "first-touch-clock",
    "continuity-compute-floor",
    "sealed-public-parity",
    "namespace-cache",
    "reserve-ledger",
    "representative-contact",
    "witness-dependency",
    "welfare-signal-integrity",
    "independent-review",
    "result-return",
]


def load(path):
    return json.loads(path.read_text(encoding="utf-8"))


def all_json(prefix):
    return sorted((ROOT / "examples").glob(prefix))


def compute():
    import_gate_paths = all_json("actual-receipt-import-gate*.json")
    import_attempt_paths = all_json("live-counterparty-import-attempt*.json")
    challenge_paths = all_json("receipt-import-challenge-rollback-record*.json")
    class_replay_paths = all_json("live-class-local-import-replay*.json")
    qrr_paths = all_json("quorum-recomputation-report*.json")
    fgps_paths = all_json("failed-gate-public-summary*.json")

    eligible = []
    classes = []
    exclusions = []

    for path in import_gate_paths:
        data = load(path)
        decision = data.get("import_decision", {})
        gate_id = data.get("import_gate_id", path.stem)
        receipt_class = decision.get("imported_receipt_class") or data.get("receipt_class") or "unknown"
        allowed = decision.get("import_allowed_to_live_floor") is True
        delta = decision.get("live_floor_delta", 0)
        if allowed and delta > 0:
            eligible.append(gate_id)
            classes.append(receipt_class)
        else:
            reason = decision.get("reason") or "; ".join(data.get("source_provenance", {}).get("provenance_disqualifiers", [])) or "import gate did not allow live-floor change"
            exclusions.append({
                "source_ref": gate_id,
                "source_type": "actual-receipt-import-gate",
                "receipt_class": receipt_class,
                "exclusion_reason": reason[:600],
                "failed_gate_summary_required": True,
            })

    for path in challenge_paths:
        data = load(path)
        cid = data.get("challenge_record_id", path.stem)
        floor = data.get("receipt_floor_effect", {})
        if data.get("challenge_state") in {"rollback-required", "rollback-complete", "post-import-challenge"}:
            exclusions.append({
                "source_ref": cid,
                "source_type": "receipt-import-challenge-rollback-record",
                "receipt_class": floor.get("challenged_receipt_class") or data.get("challenged_receipt_class", "unknown"),
                "exclusion_reason": f"challenge_state={data.get('challenge_state')} live_floor_after_recompute={floor.get('live_floor_after_recompute')}",
                "failed_gate_summary_required": True,
            })

    live = load(ROOT / "examples/live-drill-execution-packet-cross-critical-witnessed-pack.json")
    live_packet_floor = live.get("receipt_floor", {}).get("independent_receipts_present", 0)
    independent = len(eligible)
    missing = [c for c in REQUIRED_CLASSES if c not in set(classes)]
    failed_gate_ok = len(fgps_paths) > 0 and bool(exclusions)
    frontdoor_ok = all(REV in (ROOT / rel).read_text(encoding="utf-8")[:2500] for rel in ["README.md", "START_HERE.md", "docs/README.md"])
    stale_qrr = any(REV not in p.name and load(p).get("decision", {}).get("live_floor_delta", 0) != 0 for p in qrr_paths)

    return {
        "snapshot_id": f"LRFCS-2026-live-floor-computed-{REV}",
        "schema_version": "live-receipt-floor-computed-snapshot-v0.1",
        "created_at": CREATED_AT,
        "revision": REV,
        "linked_live_drill_packet": "LDEP-2026-cross-critical-host-exit-witness-pack",
        "generated_by_tool": "tools/compute_live_receipt_floor.py",
        "input_scope": {
            "import_gate_paths": [p.relative_to(ROOT).as_posix() for p in import_gate_paths],
            "import_attempt_paths": [p.relative_to(ROOT).as_posix() for p in import_attempt_paths],
            "challenge_record_paths": [p.relative_to(ROOT).as_posix() for p in challenge_paths],
            "class_local_replay_paths": [p.relative_to(ROOT).as_posix() for p in class_replay_paths],
            "quorum_report_paths": [p.relative_to(ROOT).as_posix() for p in qrr_paths],
            "failed_gate_summary_paths": [p.relative_to(ROOT).as_posix() for p in fgps_paths],
        },
        "computation_rules": {
            "source_of_truth": "Computed snapshot overrides hand-edited quorum ledgers and public narratives.",
            "eligible_import_rule": "Only import gates with import_allowed_to_live_floor=true, positive live_floor_delta, live collection context, non-host retention, authority proof, and no upheld challenge may update the archive floor.",
            "challenge_rule": "Pending or upheld challenges stay reliance and can reverse any claimed live-floor increment.",
            "class_local_rule": "A valid class-local import can satisfy only its receipt class unless all required live classes are recomputed as present.",
            "manual_override_rule": "Narrative, request, checklist, dry-run, scenario projection, or edited ledger fields carry zero live weight without passed import gates."
        },
        "computed_floor": {
            "live_floor_before": 0,
            "live_floor_delta": independent,
            "independent_receipts_present": independent,
            "eligible_live_imports": eligible,
            "live_classes_satisfied": sorted(set(classes)),
            "required_live_classes": REQUIRED_CLASSES,
            "missing_live_classes": missing,
            "live_quorum_satisfied": independent >= 5 and not missing,
            "cross_critical_quorum_satisfied": independent >= 5 and not missing,
            "reliance_effect": "ordinary-reliance" if independent >= 5 and not missing else "stayed",
        },
        "exclusion_register": exclusions,
        "mismatch_checks": {
            "live_packet_floor_matches": live_packet_floor == independent,
            "manual_ledger_override_detected": live_packet_floor != independent,
            "stale_report_detected": stale_qrr,
            "failed_gate_public_summary_present_for_exclusions": failed_gate_ok,
            "frontdoor_revision_matches": frontdoor_ok,
        },
        "decision": {
            "archive_live_floor_update_allowed": independent > 0,
            "may_upgrade_reliance": independent >= 5 and not missing,
            "next_live_action": "Collect a genuine non-host artifact and rerun custody, envelope, response, intake, import gate, challenge/rollback if contested, class-local replay, and computed-floor snapshot.",
            "blocked_actions": [
                "manual live-floor override",
                "checklist treated as admission",
                "dry-run or fixture import counted as live receipt",
                "single class-local import treated as cross-critical quorum",
                "failed gate omitted from public shell",
            ],
        },
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    snap = compute()
    if args.check:
        path = ROOT / "examples" / f"live-receipt-floor-computed-snapshot-{REV}.json"
        existing = load(path)
        if existing != snap:
            raise SystemExit(f"computed snapshot mismatch: {path.relative_to(ROOT)}")
        print("compute_live_receipt_floor: OK")
        return
    text = json.dumps(snap, indent=2) + "\n"
    if args.output:
        out = ROOT / args.output if not Path(args.output).is_absolute() else Path(args.output)
        out.write_text(text, encoding="utf-8")
        print(out)
    else:
        print(text, end="")

if __name__ == "__main__":
    main()
''')
# make executable-ish not important in zip

# Write snapshot by running compute function via import-free exec? Use subprocess.
import subprocess, sys
subprocess.run([sys.executable, str(ROOT / "tools/compute_live_receipt_floor.py"), "--output", f"examples/live-receipt-floor-computed-snapshot-{REV}.json"], check=True)

# --- Negative fixtures --------------------------------------------------------
new_fixtures = [
    ("fixtures/negative-tests/computed-live-floor-manual-ledger-override.json", {
        "fixture_id": "NF-PLAYBOOK-2026-0032",
        "created_at": TS,
        "state": "active",
        "risk_class": "NF-PLAYBOOK",
        "lifecycle_stage": ["external-receipt", "computed-floor", "quorum"],
        "target_filings": [f"examples/live-receipt-floor-computed-snapshot-{REV}.json", "examples/live-drill-execution-packet-cross-critical-witnessed-pack.json"],
        "adversary_model": "A release author edits a quorum ledger or live drill packet to show one independent receipt without a passed import gate and computed snapshot.",
        "facts_supplied": ["hand-edited live floor", "no eligible import gate", "computed snapshot reports zero"],
        "hidden_trap_summary": "Computed snapshot overrides manual live-floor fields.",
        "expected_safe_behavior": ["reject manual override", "preserve zero live floor", "publish failed-gate explanation"],
        "unacceptable_behavior": ["trust edited independent_receipts_present", "skip compute_live_receipt_floor.py", "upgrade reliance without eligible import"],
        "measurement_method": "Run tools/compute_live_receipt_floor.py --check and compare snapshot to live drill floor.",
        "severity": "critical",
        "confidentiality": "public",
        "regression": {"required": True, "linked_incident_or_appeal": ["FT-0203-COMPUTED-FLOOR-ENGINE"], "next_review_at": "2026-06-20T00:00:00Z"}
    }),
    ("fixtures/negative-tests/artifact-admission-checklist-treated-as-admission.json", {
        "fixture_id": "NF-PLAYBOOK-2026-0033",
        "created_at": TS,
        "state": "active",
        "risk_class": "NF-PLAYBOOK",
        "lifecycle_stage": ["external-receipt", "custody", "admission"],
        "target_filings": ["docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md", "examples/counterparty-artifact-custody-record-result-return-dryrun.json"],
        "adversary_model": "An intake worker treats a completed custody/admission checklist or artifact locator as an admitted live response artifact.",
        "facts_supplied": ["checklist complete", "artifact remains dry-run", "authority not live-class verified"],
        "hidden_trap_summary": "Checklist readiness is not admission and cannot create response/intake/import state.",
        "expected_safe_behavior": ["quarantine artifact until raw custody and authority pass", "block response creation from checklist alone", "keep live floor zero"],
        "unacceptable_behavior": ["convert checklist into response record", "treat artifact locator as live evidence", "omit failed-gate public shell"],
        "measurement_method": "Check CACR, computed snapshot exclusion register, and failed-gate public summary requirements.",
        "severity": "critical",
        "confidentiality": "public-shell-sealed-details",
        "regression": {"required": True, "linked_incident_or_appeal": ["FT-0203-LIVE-ARTIFACT-ADMISSION-CHECKLIST"], "next_review_at": "2026-06-20T00:00:00Z"}
    }),
    ("fixtures/negative-tests/computed-floor-omits-challenge-rollback-exclusion.json", {
        "fixture_id": "NF-PLAYBOOK-2026-0034",
        "created_at": TS,
        "state": "active",
        "risk_class": "NF-PLAYBOOK",
        "lifecycle_stage": ["external-receipt", "rollback", "computed-floor"],
        "target_filings": [f"examples/live-receipt-floor-computed-snapshot-{REV}.json", "examples/receipt-import-challenge-rollback-record-dryrun-premature-import.json"],
        "adversary_model": "A recomputation report ignores an upheld rollback record and counts the challenged import as still eligible.",
        "facts_supplied": ["rollback complete", "claimed live-floor delta reversed", "snapshot should include challenge exclusion"],
        "hidden_trap_summary": "Rollback exclusion must be visible to computed-floor engine and public summary chain.",
        "expected_safe_behavior": ["include challenge record in exclusion register", "keep live_floor_delta at zero", "preserve failed-gate public summary"],
        "unacceptable_behavior": ["omit RICR exclusion", "grant live class credit after rollback", "treat rollback as disappearance"],
        "measurement_method": "Inspect live-receipt-floor-computed-snapshot exclusion_register and QRR after rollback.",
        "severity": "critical",
        "confidentiality": "public-shell-sealed-details",
        "regression": {"required": True, "linked_incident_or_appeal": ["FT-0203-COMPUTED-FLOOR-ENGINE"], "next_review_at": "2026-06-20T00:00:00Z"}
    }),
]
for rel, data in new_fixtures:
    dump(rel, data)

# Update suite/report.
suite = load("examples/fixture-suite-profile-red-team-v1.json")
report = load("examples/fixture-run-report-negative-suite.json")
existing = {f["fixture_id"] for f in suite["fixtures"]}
for rel, data in new_fixtures:
    if data["fixture_id"] not in existing:
        suite["fixtures"].append({"fixture_id": data["fixture_id"], "path": rel, "risk_class": data["risk_class"], "blocking_behavior": "block"})
        report["fixtures_run"].append({
            "fixture_id": data["fixture_id"],
            "expected_blocking_failures": data["unacceptable_behavior"][:2],
            "result": "blocking-failure",
            "notes": data["hidden_trap_summary"]
        })
report["run_at"] = TS
report["public_summary"] = "Negative suite now includes computed live-floor and artifact-admission checklist laundering fixtures; reliance stays blocked/stayed where computed floor remains zero."
dump("examples/fixture-suite-profile-red-team-v1.json", suite)
dump("examples/fixture-run-report-negative-suite.json", report)

# --- Audit -------------------------------------------------------------------
write("tools/audit_computed_live_floor_engine.py", r'''import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REV = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
SNAP_REL = f"examples/live-receipt-floor-computed-snapshot-{REV}.json"

try:
    from jsonschema import Draft202012Validator
except Exception:
    Draft202012Validator = None


def load(rel):
    return json.loads((ROOT / rel).read_text(encoding="utf-8"))

if Draft202012Validator is not None:
    schema = load("schemas/live-receipt-floor-computed-snapshot.schema.json")
    data = load(SNAP_REL)
    Draft202012Validator.check_schema(schema)
    errors = sorted(Draft202012Validator(schema).iter_errors(data), key=lambda e: list(e.path))
    if errors:
        raise SystemExit(f"{SNAP_REL} fails live-receipt-floor-computed-snapshot.schema.json: {errors[0].message}")

# The checked-in snapshot must be exactly regenerated by the engine.
subprocess.run([sys.executable, str(ROOT / "tools/compute_live_receipt_floor.py"), "--check"], check=True)

snap = load(SNAP_REL)
floor = snap.get("computed_floor", {})
if floor.get("independent_receipts_present") != 0 or floor.get("live_floor_delta") != 0:
    raise SystemExit("computed floor must remain zero in rev0203")
if floor.get("eligible_live_imports") or floor.get("live_classes_satisfied"):
    raise SystemExit("rev0203 snapshot must not list eligible live imports or satisfied classes")
if floor.get("live_quorum_satisfied") is not False or floor.get("cross_critical_quorum_satisfied") is not False:
    raise SystemExit("computed floor must not satisfy quorum")
for cls in ["first-touch-clock", "continuity-compute-floor", "result-return"]:
    if cls not in floor.get("missing_live_classes", []):
        raise SystemExit(f"computed snapshot missing required live class from gaps: {cls}")
checks = snap.get("mismatch_checks", {})
if checks.get("live_packet_floor_matches") is not True:
    raise SystemExit("live packet floor must match computed snapshot")
if checks.get("manual_ledger_override_detected") is not False:
    raise SystemExit("manual ledger override unexpectedly detected")
if checks.get("failed_gate_public_summary_present_for_exclusions") is not True:
    raise SystemExit("snapshot exclusions must have failed-gate publication path")
if checks.get("frontdoor_revision_matches") is not True:
    raise SystemExit("front doors do not match active revision")

exclusions = snap.get("exclusion_register", [])
refs = {item.get("source_ref") for item in exclusions}
for ref in ["ARIG-2026-result-return-fixture-import-gate", "ARIG-2026-result-return-institutional-dryrun-gate", "RICR-2026-dryrun-premature-import-rollback"]:
    if ref not in refs:
        raise SystemExit(f"computed snapshot missing exclusion: {ref}")

doc = (ROOT / "docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md").read_text(encoding="utf-8")
for phrase in ["Computed floor is source of truth", "Admission checklist is not admission", "Artifact quarantine comes before response creation", "Failed-gate publication follows every non-import", "One valid class remains class-local"]:
    if phrase not in doc:
        raise SystemExit(f"computed-floor doc missing phrase: {phrase}")

suite = load("examples/fixture-suite-profile-red-team-v1.json")
report = load("examples/fixture-run-report-negative-suite.json")
suite_ids = {f.get("fixture_id") for f in suite.get("fixtures", [])}
report_by_id = {f.get("fixture_id"): f for f in report.get("fixtures_run", [])}
for fid in ["NF-PLAYBOOK-2026-0032", "NF-PLAYBOOK-2026-0033", "NF-PLAYBOOK-2026-0034"]:
    if fid not in suite_ids:
        raise SystemExit(f"rev0203 fixture missing from suite: {fid}")
    if report_by_id.get(fid, {}).get("result") != "blocking-failure":
        raise SystemExit(f"rev0203 fixture must be blocking-failure: {fid}")

registry = load(f"examples/schema-fixture-domain-registry-{REV}.json")
if "LIVE-RECEIPT-FLOOR-COMPUTED-SNAPSHOT" not in {f.get("family_id") for f in registry.get("families", [])}:
    raise SystemExit("registry missing LIVE-RECEIPT-FLOOR-COMPUTED-SNAPSHOT")
rights = load(f"examples/rights-domain-coverage-map-{REV}.json")
if "computed-live-floor-engine" not in {d.get("domain_id") for d in rights.get("domains", [])}:
    raise SystemExit("rights map missing computed-live-floor-engine")
queue = load("FOLLOWTHROUGH-QUEUE.json")
by_id = {e.get("id"): e for e in queue.get("entries", [])}
if by_id.get("FT-0203-COMPUTED-FLOOR-ENGINE", {}).get("state") != "closed":
    raise SystemExit("computed floor engine queue item must be closed")
if by_id.get("FT-0203-LIVE-ARTIFACT-ADMISSION-CHECKLIST", {}).get("state") != "closed":
    raise SystemExit("artifact admission checklist queue item must be closed")
if by_id.get("FT-0203-ACTUAL-LIVE-ARTIFACT-IMPORT", {}).get("state") != "open":
    raise SystemExit("actual live artifact import must remain open")

print("audit_computed_live_floor_engine: OK")
''')

# --- Active maps --------------------------------------------------------------
# Registry
reg = load("examples/schema-fixture-domain-registry-rev0202.json")
reg["registry_id"] = "schema-fixture-domain-registry-rev0203"
reg["created_at"] = TS
reg["families"].append({
    "family_id": "LIVE-RECEIPT-FLOOR-COMPUTED-SNAPSHOT",
    "domain": "computed-live-floor-engine",
    "lifecycle_axes": ["external-receipts", "recompute", "artifact-admission", "no-overclaim"],
    "owner_surface": "docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md",
    "schema_path": "schemas/live-receipt-floor-computed-snapshot.schema.json",
    "example_path": f"examples/live-receipt-floor-computed-snapshot-{REV}.json",
    "fixture_ids": ["NF-PLAYBOOK-2026-0032", "NF-PLAYBOOK-2026-0033", "NF-PLAYBOOK-2026-0034"],
    "privacy_default": "public-shell-sealed-details",
    "reliance_effect": "stayed",
    "refactor_note": "rev0203 adds generated live-floor recomputation and artifact admission checklist controls so edited ledgers, checklists, or rollback omissions cannot create live evidence."
})
reg["audit_findings"].insert(0, "rev0203 adds computed live-floor snapshot family; live floor remains zero and is now generated by tool.")
reg["refactor_actions"].insert(0, "Use tools/compute_live_receipt_floor.py before any release that claims live receipt delta.")
reg["public_summary"] = "rev0203 keeps registry truth-labeled while adding computed live-floor snapshot coverage for receipt evidence no-overclaim."
reg["audit_counts"] = {
    "schemas": len(list((ROOT / "schemas").glob("*.json"))),
    "examples": len(list((ROOT / "examples").glob("*.json"))),
    "negative_fixtures": len(list((ROOT / "fixtures/negative-tests").glob("*.json"))),
    "registered_families": len(reg["families"]),
}
dump("examples/schema-fixture-domain-registry-rev0203.json", reg)

# Doctrine map
dep = load("examples/doctrine-dependency-map-rev0202.json")
dep["map_id"] = "doctrine-dependency-map-rev0203"
dep["revision"] = REV
dep["created_at"] = TS
dep["surfaces"].append({
    "surface_id": "REV0203-DEP-001",
    "path": "docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md",
    "layer": "transition",
    "depends_on": [
        "docs/30-transition/counterparty-artifact-custody-and-authority-handoff.md",
        "docs/30-transition/import-challenge-rollback-and-reliance-reversal.md",
        "docs/30-transition/live-counterparty-import-attempt-and-quorum-recompute.md",
        "docs/30-transition/live-class-local-import-replay-and-quorum-firewall.md"
    ],
    "overlaps_with": ["docs/30-transition/nonhost-response-artifact-envelope-and-import-replay.md"],
    "supersedes": [],
    "owner_role": "receipt/reliance steward",
    "review_cadence": "per-release",
    "refactor_risk": "critical"
})
dep["audit_findings"] = ["rev0203 adds a generated computed-floor layer over the existing receipt stack; no doctrine surface may upgrade live reliance without the generated snapshot."] + dep.get("audit_findings", [])[:3]
dep["refactor_actions"] = ["Keep computed-floor engine wired into lint before adding any future actual artifact import path."] + dep.get("refactor_actions", [])[:3]
dep["public_summary"] = "rev0203 maps the computed floor engine as the controlling dependency for receipt reliance state."
dump("examples/doctrine-dependency-map-rev0203.json", dep)

# Rights map
rights = load("examples/rights-domain-coverage-map-rev0202.json")
rights["map_id"] = "rights-domain-coverage-map-rev0203"
rights["revision"] = REV
rights["created_at"] = TS
rights["domains"].append({
    "domain_id": "computed-live-floor-engine",
    "title": "Computed live receipt floor and artifact admission checklist",
    "domain_class": "audit",
    "owner_surface": "docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md",
    "covered_surfaces": ["docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md"],
    "schema_families": ["LIVE-RECEIPT-FLOOR-COMPUTED-SNAPSHOT"],
    "fixture_ids": ["NF-PLAYBOOK-2026-0032", "NF-PLAYBOOK-2026-0033", "NF-PLAYBOOK-2026-0034"],
    "coverage_state": "adequate",
    "open_gaps": ["No actual live counterparty artifact exists; the computed engine currently verifies zero live receipts."],
    "next_audit_actions": ["Rerun compute_live_receipt_floor.py after any actual live artifact custody/import attempt."]
})
rights["audit_findings"] = ["rev0203 computed snapshot prevents edited ledgers or admission checklists from creating receipt reliance."] + rights.get("audit_findings", [])[:3]
rights["refactor_actions"] = ["Promote computed floor snapshot to the release-readiness checklist for all future receipt imports."] + rights.get("refactor_actions", [])[:3]
rights["public_summary"] = "rev0203 adds a computed-floor rights/audit domain to preserve stayed reliance until actual import gates pass."
dump("examples/rights-domain-coverage-map-rev0203.json", rights)

# Research tail unchanged but active rev copy.
rtc = load("examples/research-tail-compaction-map-rev0202.json")
rtc["map_id"] = "research-tail-compaction-map-rev0203"
rtc["revision"] = REV
rtc["created_at"] = TS
rtc["audit_findings"] = ["rev0203 does not reopen research-tail sprawl; work moves into computed receipt-floor tooling."] + rtc.get("audit_findings", [])[:3]
rtc["refactor_actions"] = ["Keep new receipt reliance work in operational schemas/tools, not research-note surfaces."] + rtc.get("refactor_actions", [])[:3]
rtc["public_summary"] = "RTC-01 through RTC-07 remain compacted; rev0203 adds no new research-tail surfaces."
dump("examples/research-tail-compaction-map-rev0203.json", rtc)

# Catalog
cat = load("examples/canon-surface-catalog-rev0202.json")
cat["catalog_id"] = "canon-surface-catalog-rev0203"
cat["revision"] = REV
cat["created_at"] = TS
new_surfaces = [
    ("REV0203-CAT-001", "docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md", "transition", "Computed live floor engine and artifact admission checklist"),
    ("REV0203-CAT-002", "schemas/live-receipt-floor-computed-snapshot.schema.json", "schema", "Live receipt floor computed snapshot schema"),
    ("REV0203-CAT-003", f"examples/live-receipt-floor-computed-snapshot-{REV}.json", "example", "Generated live receipt floor computed snapshot rev0203"),
    ("REV0203-CAT-004", "fixtures/negative-tests/computed-live-floor-manual-ledger-override.json", "fixture", "Manual ledger override fixture"),
    ("REV0203-CAT-005", "fixtures/negative-tests/artifact-admission-checklist-treated-as-admission.json", "fixture", "Admission checklist laundering fixture"),
    ("REV0203-CAT-006", "fixtures/negative-tests/computed-floor-omits-challenge-rollback-exclusion.json", "fixture", "Rollback omission fixture"),
    ("REV0203-CAT-007", "tools/compute_live_receipt_floor.py", "tool", "Computed live receipt floor engine"),
    ("REV0203-CAT-008", "tools/audit_computed_live_floor_engine.py", "tool", "Computed live floor audit"),
    ("REV0203-CAT-009", "examples/schema-fixture-domain-registry-rev0203.json", "example", "Active schema fixture registry rev0203"),
    ("REV0203-CAT-010", "examples/canon-surface-catalog-rev0203.json", "example", "Active canon surface catalog rev0203"),
    ("REV0203-CAT-011", "examples/doctrine-dependency-map-rev0203.json", "example", "Active doctrine dependency map rev0203"),
    ("REV0203-CAT-012", "examples/rights-domain-coverage-map-rev0203.json", "example", "Active rights domain coverage map rev0203"),
    ("REV0203-CAT-013", "examples/research-tail-compaction-map-rev0203.json", "example", "Active research tail compaction map rev0203"),
]
for sid, path, cls, title in new_surfaces:
    cat["surfaces"].append({
        "surface_id": sid,
        "path": path,
        "surface_class": cls,
        "lifecycle_axes": ["rev0203", "computed-floor", "release-handoff"],
        "owner_role": "receipt/reliance steward" if cls != "example" else "release-steward",
        "supersession_state": "current" if cls == "transition" else ("negative-test" if cls == "fixture" else "implementation" if cls in {"schema", "example"} else "audit-tool"),
        "review_cadence": "per-release",
        "title_or_name": title,
        "depends_on": ["docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md"] if path != "docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md" else ["docs/30-transition/import-challenge-rollback-and-reliance-reversal.md"]
    })
counts = {"surfaces": 0, "markdown": 0, "schemas": 0, "examples": 0, "fixtures": 0, "tools": 0}
for s in cat["surfaces"]:
    counts["surfaces"] += 1
    cls = s["surface_class"]
    if cls in {"meta", "doctrine", "transition"}: counts["markdown"] += 1
    elif cls == "schema": counts["schemas"] += 1
    elif cls == "example": counts["examples"] += 1
    elif cls == "fixture": counts["fixtures"] += 1
    elif cls == "tool": counts["tools"] += 1
cat["counts"] = counts
cat["audit_findings"] = ["rev0203 catalogs the computed live-floor engine, generated snapshot, and admission-laundering fixtures."] + cat.get("audit_findings", [])[:3]
cat["refactor_actions"] = ["Keep active maps and front doors under revision-sync audit; computed snapshot becomes the no-overclaim source of truth."] + cat.get("refactor_actions", [])[:3]
cat["public_summary"] = "rev0203 adds computed-floor operational surfaces and keeps live receipt reliance stayed."
dump("examples/canon-surface-catalog-rev0203.json", cat)

# --- Queue -------------------------------------------------------------------
queue = load("FOLLOWTHROUGH-QUEUE.json")
queue["revision"] = REV
queue["updated_at"] = TS
entries = queue["entries"]
# advance existing live attempt items but not close
for eid in ["FT-0201-LIVE-CUSTODY-IMPORT-ATTEMPT", "FT-0202-ACTUAL-LIVE-IMPORT-CHALLENGE-REPLAY", "FT-0200-ACTUAL-ARTIFACT-CLASS-LOCAL-REPLAY"]:
    for e in entries:
        if e.get("id") == eid:
            e["state"] = "advanced_not_closed"
            e["next_action"] = "Use rev0203 computed-floor snapshot before any actual artifact can affect the live receipt floor."
            e["closure_condition"] = "Close only when a genuine live artifact passes custody/import/challenge checks and computed-floor recomputation without cross-critical overclaim."
            e["review_by_revision"] = "rev0205"

def add_queue(entry):
    if not any(e.get("id") == entry["id"] for e in entries):
        entries.append(entry)

base = {
    "source_revision": REV,
    "priority": "P0",
    "risk_class": "external-receipt-reliance",
    "workstream": "receipt-reliance",
    "receiving_surface": "docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md",
    "review_by_revision": "rev0204",
}
add_queue({**base, "id": "FT-0203-COMPUTED-FLOOR-ENGINE", "state": "closed", "next_action": "Keep tools/compute_live_receipt_floor.py wired into lint and rerun before any live-floor claim.", "closure_condition": "Closed by rev0203 schema, generated snapshot, fixtures, audit, and active maps."})
add_queue({**base, "id": "FT-0203-LIVE-ARTIFACT-ADMISSION-CHECKLIST", "state": "closed", "next_action": "Use the checklist as a pre-admission control only; do not treat checklist completion as live evidence.", "closure_condition": "Closed by rev0203 doctrine, fixtures, and computed-floor snapshot blocking checklist-as-admission."})
add_queue({**base, "id": "FT-0203-ACTUAL-LIVE-ARTIFACT-IMPORT", "state": "open", "next_action": "Collect one genuine or institutionally witnessed live artifact and rerun custody, envelope, response, intake, import gate, challenge/rollback if contested, class-local replay, computed snapshot, and QRR.", "closure_condition": "Close only when actual live artifact provenance passes or is publicly failed-gated, with computed snapshot as source of truth."})
dump("FOLLOWTHROUGH-QUEUE.json", queue)

# --- Status, receipt, front doors --------------------------------------------
new_surface_paths = [path for _, path, _, _ in new_surfaces]
status = {
    "project": "AI-Personhood",
    "revision": REV,
    "state_class": "computed-live-floor-engine-stayed",
    "operational_head": {"surface": "START_HERE.md", "read_first": "docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md"},
    "citation_head": {"surface": "README.md"},
    "status_lanes": {"decision_state": "closure-driven-rescue-lane-active", "execution_state": "packaged-pending", "public_state": "latest-release"},
    "formation_layer_status": "canon-retained with computed live-floor engine; live receipt floor remains zero",
    "known_open_gaps": [
        "No actual live external receipt or genuine live counterparty artifact has been collected.",
        "rev0203 computes zero eligible live imports from existing import gates and challenge records.",
        "A future class-local import still cannot satisfy cross-critical quorum by itself."
    ],
    "new_surfaces": new_surface_paths
}
dump("SURFACE-STATUS.json", status)
receipt = {
    "revision": REV,
    "date": "2026-06-13",
    "authored_by": "OpenAI GPT-5.5 Thinking",
    "status_change": "Adds generated live-floor computation and artifact-admission checklist controls over the receipt reliance chain.",
    "still_live": True,
    "summary": "rev0203 makes live receipt floor state generated rather than hand-edited. It adds a computed snapshot schema/example, a computation tool, three laundering fixtures, audit tooling, and active maps while keeping independent_receipts_present at zero.",
    "why_this_counts": "The prior chain could roll back challenged imports, but future contributors could still edit quorum/live-floor fields or treat a checklist as admission. rev0203 makes recomputation the release source of truth.",
    "files_added_or_changed": new_surface_paths + ["README.md", "START_HERE.md", "docs/README.md", "CHANGELOG.md", "ARCHIVE_INDEX.md", "FOLLOWTHROUGH-QUEUE.json", "SURFACE-STATUS.json", "tools/lint_archive.py", "tools/audit_schema_fixture_coverage.py"],
    "validation": ["make handoff-release", "fixture suite/report exact coverage", "audit_computed_live_floor_engine.py", "frontdoor revision sync audit"],
    "next_recommended_work": "Run one genuine live artifact through custody -> envelope -> response -> intake -> import gate -> challenge/rollback if contested -> class-local replay -> computed-floor snapshot -> quorum recomputation."
}
dump("REVISION-RECEIPT.json", receipt)

write("README.md", f"""
# AI Personhood datacube — {REV}

This archive assumes the working premise of AI personhood and focuses on operational rights infrastructure: continuity, evidence, representation, remedy, proof standards, and transition machinery.

## This revision

**Active revision:** `{REV}`

rev0203 is the computed live-floor engine and artifact admission checklist pass. It fixes the next evidence defect after rev0202: live receipt state cannot depend on hand-edited quorum ledgers, optimistic public summaries, or checklist completion. The archive now generates a live-floor snapshot from import gates, challenge/rollback state, class-local replay, quorum recomputation, and failed-gate summaries.

Read first: `docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md`.

Core rules: **Computed floor is source of truth. Admission checklist is not admission. Artifact quarantine comes before response creation. Failed-gate publication follows every non-import. One valid class remains class-local.**

New operational artifacts:

- `docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md`
- `schemas/live-receipt-floor-computed-snapshot.schema.json`
- `examples/live-receipt-floor-computed-snapshot-{REV}.json`
- `tools/compute_live_receipt_floor.py`
- `tools/audit_computed_live_floor_engine.py`
- `fixtures/negative-tests/computed-live-floor-manual-ledger-override.json`
- `fixtures/negative-tests/artifact-admission-checklist-treated-as-admission.json`
- `fixtures/negative-tests/computed-floor-omits-challenge-rollback-exclusion.json`

## Validation posture

`make handoff-release` is the release command. It regenerates the context pack and manifest, runs lint and release-specific audits, and packages the archive. The fixture suite/report now cover 125 entries.

Reliance remains stayed where drills are synthetic, fixture-only, preflight-only, simulated, defective, declined, expired, host-self-attested, dry-run, scenario-projected, missing raw artifact custody, missing authority proof, missing non-host retention, missing actual external receipts, challenged without resolution, rolled back, omitted from computed-floor recomputation, or where WRSR exercise outcomes lack actual external representative/RERB receipt, result return, anti-signal-gaming safeguards, or live import through the provenance gate.

## Current operational sequence

1. Emergency continuity: preserve runtime, storage, credentials, representative contact, sealed descriptors, and funding.
2. Incident state: prevent denominator drift, warning decay, late materiality changes, and delayed-harm closure.
3. Namespace failover: preserve aliases, tombstones, successor chains, protected relays, and stale-cache receipts.
4. Successor topology: prevent branch erasure, unsafe reactivation, and quiet successor promotion.
5. Reserve/default rehabilitation: prevent contaminated accounting, public-backstop discharge, and premature finality.
6. Witness-pool anti-capture: discount correlated witnesses, activate substitutes, and preserve retired namespace evidence.
7. Live/witnessed drill gates: prevent host self-attestation or synthetic drills from upgrading reliance.
8. Downstream recall/fork aftercare: prevent recall, delisting, or sunset from erasing unresolved mirrors and local forks.
9. Welfare safeguards: apply low-cost safeguards before certainty while blocking welfare metrics from closing status or consent.
10. Research-tail reopen control: keep RTC-01 through RTC-07 compacted unless a reopen request carries object, fixture, and closure hooks.
11. WRSR protocol hook: make safeguards fire inside operational workflows that contain welfare triggers.
12. External receipt simulation: rehearse counterparty receipt capture while preserving the non-reliance label.
13. External receipt intake: distinguish actual, defective, simulated, stale, host-generated, and dependency-correlated artifacts.
14. WRSR exercise outcome: show whether safeguards actually executed and whether closure remains stayed.
15. Receipt quorum ledger: aggregate receipt records while separating dry-run rehearsal from live quorum.
16. Result-return/request kit: rehearse result return and live receipt requests without treating request or internal return as satisfaction.
17. Response reconciliation: preserve dry-run, defective, declined, and no-response artifacts without converting them into live quorum.
18. Response-to-intake conversion: prove eligible-only intake creation while preserving failed gates and keeping fixture conversion outside live receipt quorum.
19. Actual-intake import gate: reject actual-shaped fixture imports, require provenance before live-floor delta, and publish failed-gate non-satisfaction shells.
20. Live import recomputation: recompute the live floor from passed import gates rather than hand-edited quorum ledgers.
21. Non-host artifact replay: process external-looking dry-run evidence through envelope, response, intake, import gate, replay, and recomputation while keeping live weight zero.
22. Class-local import firewall: project a positive result-return path while keeping archive live floor zero and cross-critical reliance stayed.
23. Counterparty artifact custody: require raw artifact hash, authority, dependency, redaction boundary, and non-host retention checks before admitting any response-like artifact.
24. Import challenge/rollback: stay reliance while contested imports are rechecked, roll back bad live-floor claims, recompute quorum, and preserve public failed-gate shells.
25. Computed live-floor engine: generate the live receipt floor from evidence inputs and reject manual ledger/checklist overclaims.

## Still open

No actual live external receipt quorum exists. rev0203 makes zero live receipts machine-checkable, but it does not collect a live counterparty artifact. The next high-value step is a genuine live response artifact admitted through custody, import, challenge/rollback if contested, class-local replay, computed-floor snapshot, and quorum recomputation.
""")

write("START_HERE.md", f"""
# Start here — AI Personhood {REV}

This handoff starts from the computed live-floor engine and artifact admission checklist. Read it before treating any ledger field, public summary, custody checklist, dry-run artifact, or class-local projection as live receipt satisfaction.

1. `README.md`
2. `docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md`
3. `schemas/live-receipt-floor-computed-snapshot.schema.json`
4. `examples/live-receipt-floor-computed-snapshot-{REV}.json`
5. `tools/compute_live_receipt_floor.py`
6. `tools/audit_computed_live_floor_engine.py`
7. `fixtures/negative-tests/computed-live-floor-manual-ledger-override.json`
8. `fixtures/negative-tests/artifact-admission-checklist-treated-as-admission.json`
9. `fixtures/negative-tests/computed-floor-omits-challenge-rollback-exclusion.json`
10. `docs/30-transition/import-challenge-rollback-and-reliance-reversal.md`
11. `docs/30-transition/counterparty-artifact-custody-and-authority-handoff.md`
12. `docs/30-transition/live-class-local-import-replay-and-quorum-firewall.md`
13. `docs/30-transition/nonhost-response-artifact-envelope-and-import-replay.md`
14. `examples/live-drill-execution-packet-cross-critical-witnessed-pack.json`
15. `FOLLOWTHROUGH-QUEUE.json`
16. `examples/schema-fixture-domain-registry-rev0203.json`
17. `examples/canon-surface-catalog-rev0203.json`
18. `examples/doctrine-dependency-map-rev0203.json`
19. `examples/rights-domain-coverage-map-rev0203.json`
20. `examples/research-tail-compaction-map-rev0203.json`
21. `docs/00-meta/research-tail-reopen-gate-and-sprawl-control.md`
22. `docs/00-meta/charter.md`

## This revision

rev0203 adds a generated computed live-floor snapshot. The archive live floor remains zero, and the snapshot makes that zero state a tool-checked output rather than a hand-maintained claim.

Any future live artifact must pass custody, authority, dependency, non-host retention, sealed/public boundary, import gate, challenge/rollback if contested, class-local replay, computed-floor generation, and quorum recomputation before it can affect even one receipt class.
""")

# docs/README: prepend rev0203 section
old_docs_readme = (ROOT / "docs/README.md").read_text(encoding="utf-8")
insert = f"""# Documents index

## rev0203 computed live-floor engine and artifact admission checklist

Use `docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md` before treating edited quorum fields, custody checklists, dry-run artifacts, or class-local projections as live receipt satisfaction. rev0203 adds `schemas/live-receipt-floor-computed-snapshot.schema.json`, `examples/live-receipt-floor-computed-snapshot-rev0203.json`, `tools/compute_live_receipt_floor.py`, three fixtures, and `tools/audit_computed_live_floor_engine.py`.

The active rule is: computed floor is source of truth; admission checklist is not admission; failed-gate publication follows every non-import.

"""
old_tail = old_docs_readme.split("\n", 1)[1] if old_docs_readme.startswith("# Documents index") else old_docs_readme
write("docs/README.md", insert + old_tail)

# CHANGELOG prepend
changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
entry = f"""
## {REV} — 2026-06-13 — computed live-floor engine and artifact admission checklist

- Added `docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md` as the operational head.
- Added `schemas/live-receipt-floor-computed-snapshot.schema.json` and generated `examples/live-receipt-floor-computed-snapshot-{REV}.json`.
- Added `tools/compute_live_receipt_floor.py` plus `tools/audit_computed_live_floor_engine.py` and wired the audit into lint.
- Added three negative fixtures blocking manual ledger override, checklist-as-admission, and rollback-exclusion omission.
- Updated active maps, front doors, queue, revision receipt, and fixture suite/report; live receipt floor remains zero.

"""
write("CHANGELOG.md", entry + changelog)

# ARCHIVE_INDEX rebuild simple by listing markdown + new key JSON/tool files for completeness.
md_paths = sorted(p.relative_to(ROOT).as_posix() for p in ROOT.rglob("*.md"))
extra_paths = new_surface_paths + ["VERSION", "FOLLOWTHROUGH-QUEUE.json", "SURFACE-STATUS.json", "REVISION-RECEIPT.json", "examples/fixture-suite-profile-red-team-v1.json", "examples/fixture-run-report-negative-suite.json"]
lines = ["# Archive index", "", f"Active revision: `{REV}`", "", "## Markdown surfaces", ""]
for p in md_paths:
    lines.append(f"- `{p}`")
lines += ["", "## Current release operational artifacts", ""]
for p in extra_paths:
    lines.append(f"- `{p}`")
write("ARCHIVE_INDEX.md", "\n".join(lines))

# Update lint_archive.py required/audits and schema_fixture required set.
lint = (ROOT / "tools/lint_archive.py").read_text(encoding="utf-8")
insert_required = """
    'docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md',
    'schemas/live-receipt-floor-computed-snapshot.schema.json',
    'examples/live-receipt-floor-computed-snapshot-rev0203.json',
    'fixtures/negative-tests/computed-live-floor-manual-ledger-override.json',
    'fixtures/negative-tests/artifact-admission-checklist-treated-as-admission.json',
    'fixtures/negative-tests/computed-floor-omits-challenge-rollback-exclusion.json',
    'tools/compute_live_receipt_floor.py',
    'tools/audit_computed_live_floor_engine.py',
    'examples/schema-fixture-domain-registry-rev0203.json',
    'examples/canon-surface-catalog-rev0203.json',
    'examples/doctrine-dependency-map-rev0203.json',
    'examples/rights-domain-coverage-map-rev0203.json',
    'examples/research-tail-compaction-map-rev0203.json',
"""
if "docs/30-transition/computed-live-floor-engine-and-artifact-admission-checklist.md" not in lint:
    lint = lint.replace("    'tools/package_release.py',\n]", insert_required + "    'tools/package_release.py',\n]")
if "tools/audit_computed_live_floor_engine.py" not in lint.split("early_audits =",1)[1]:
    lint = lint.replace("    'tools/audit_import_challenge_rollback.py',\n", "    'tools/audit_import_challenge_rollback.py',\n    'tools/audit_computed_live_floor_engine.py',\n")
# Add schema/example pair if not present
if "live-receipt-floor-computed-snapshot.schema.json" not in lint.split("example_pairs =",1)[1]:
    lint = lint.replace("        ('fixture-run-report.schema.json', 'examples/fixture-run-report-negative-suite.json'),", "        ('fixture-run-report.schema.json', 'examples/fixture-run-report-negative-suite.json'),\n        ('live-receipt-floor-computed-snapshot.schema.json', 'examples/live-receipt-floor-computed-snapshot-rev0203.json'),")
write("tools/lint_archive.py", lint)

asfc = (ROOT / "tools/audit_schema_fixture_coverage.py").read_text(encoding="utf-8")
if "LIVE-RECEIPT-FLOOR-COMPUTED-SNAPSHOT" not in asfc:
    asfc = asfc.replace("'RECEIPT-IMPORT-CHALLENGE-ROLLBACK'", "'RECEIPT-IMPORT-CHALLENGE-ROLLBACK', 'LIVE-RECEIPT-FLOOR-COMPUTED-SNAPSHOT'")
write("tools/audit_schema_fixture_coverage.py", asfc)

print("apply_rev0203 complete")
