from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from vhk.project.loader import load_project
from vhk.project.strategy import summarize_project_strategy


def _write_if_allowed(path: Path, content: bytes | str, *, force: bool) -> None:
    if path.exists() and not force:
        raise ValueError(f"Refusing to overwrite existing file: {path}. Use --force.")
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content)


def _trim_items(items: list[dict[str, Any]] | None, limit: int = 5) -> list[dict[str, Any]]:
    return [dict(item) for item in list(items or [])[:limit] if isinstance(item, dict)]


def _first_text(item: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = item.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def _render_artifact_summary(item: Any) -> str:
    if isinstance(item, str):
        return item
    if isinstance(item, dict):
        title = str(item.get("title") or item.get("id") or "artifact")
        path_hint = str(item.get("path_hint") or item.get("install_hint") or "").strip()
        if path_hint:
            return f"{title} (`{path_hint}`)"
        return title
    return str(item)


def build_operator_plan(
    project_dir: Path,
    *,
    capability_usage: dict[str, list[dict[str, object]]] | None = None,
    capability_matrix: dict[str, object] | None = None,
    capability_issues: list[dict[str, object]] | None = None,
) -> dict[str, Any]:
    """Load a VHK project and emit a planner-backed operator pack payload."""

    project = load_project(project_dir)
    return summarize_project_strategy(
        project,
        capability_usage=capability_usage,
        capability_matrix=capability_matrix,
        capability_issues=capability_issues,
    )


def render_operator_guide(plan: dict[str, Any]) -> str:
    project = dict(plan.get("project") or {})
    overview = dict(plan.get("overview") or {})
    product_lanes = _trim_items(plan.get("product_lanes"), limit=4)
    deployable_surfaces = _trim_items(plan.get("deployable_surfaces"), limit=7)
    setup_recipes = _trim_items(plan.get("setup_recipes"), limit=7)
    verification_gates = _trim_items(plan.get("verification_gates"), limit=5)
    implementation_waves = _trim_items(plan.get("implementation_waves"), limit=5)
    reference_patterns = _trim_items(plan.get("reference_patterns"), limit=4)
    session_capabilities = dict(plan.get("session_capabilities") or {})
    session_issues = list(plan.get("session_issues") or [])

    lines: list[str] = []
    lines.append(f"# VHK operator guide for {project.get('name') or 'project'}")
    lines.append("")
    lines.append("Generated by `vhk gen-operator-pack` from the same planner used by `vhk plan-project`.")
    if session_capabilities:
        lines.append("This guide is capability-aware: it includes the current session fit so deploy/install review can happen against a real desktop, not only a hypothetical target.")
    else:
        lines.append("This guide is capability-agnostic: rerun it with session checks on the target desktop before shipping so install choices reflect the real environment.")
    lines.append("")

    lines.append("## Project snapshot")
    lines.append("")
    lines.append(f"- Root: `{project.get('root_dir') or '.'}`")
    lines.append(f"- Desktop backend: `{project.get('desktop_backend') or 'unknown'}`")
    lines.append(f"- Macros: {overview.get('macros', 0)}")
    lines.append(f"- Bindings: {overview.get('bindings', 0)}")
    lines.append(f"- Hotstrings: {overview.get('hotstrings', 0)}")
    lines.append(f"- Clipboard watchers: {overview.get('clipboard_watchers', 0)}")
    lines.append(f"- Bus watchers: {overview.get('bus_watchers', 0)}")
    lines.append(f"- Window watchers: {overview.get('window_watchers', 0)}")
    lines.append(f"- Presets: {overview.get('presets', 0)}")
    tags = list(plan.get("project_tags") or [])
    if tags:
        lines.append(f"- Project tags: {', '.join(str(tag) for tag in tags)}")
    lines.append("")

    if product_lanes:
        lines.append("## Leading product lanes")
        lines.append("")
        for item in product_lanes:
            title = item.get("title") or item.get("id") or "lane"
            lines.append(f"### {title}")
            summary = _first_text(item, "summary", "why", "description", "notes")
            if summary:
                lines.append(str(summary))
            evidence = list(item.get("evidence") or [])
            if evidence:
                lines.append("")
                lines.append(f"Evidence: {', '.join(str(x) for x in evidence[:5])}")
            lines.append("")

    if deployable_surfaces:
        lines.append("## Deployable surfaces")
        lines.append("")
        for item in deployable_surfaces:
            title = item.get("title") or item.get("id") or "surface"
            lines.append(f"### {title}")
            summary = _first_text(item, "summary", "why", "description", "notes")
            if summary:
                lines.append(summary)
            entrypoint = str(item.get("entrypoint") or "").strip()
            if entrypoint:
                lines.append("")
                lines.append(f"Entrypoint: `{entrypoint}`")
            artifacts = list(item.get("artifacts") or [])
            if artifacts:
                lines.append("")
                lines.append("Representative artifacts:")
                for art in artifacts[:5]:
                    lines.append(f"- {_render_artifact_summary(art)}")
            generator_commands = list(item.get("generator_commands") or [])
            if generator_commands:
                lines.append("")
                lines.append("Generator commands:")
                for cmd in generator_commands[:4]:
                    lines.append(f"- `{cmd}`")
            lines.append("")

    if setup_recipes:
        lines.append("## Setup recipes")
        lines.append("")
        for item in setup_recipes:
            title = item.get("title") or item.get("id") or "recipe"
            lines.append(f"### {title}")
            summary = _first_text(item, "summary", "why", "description", "notes")
            if summary:
                lines.append(summary)
            install_steps = list(item.get("install_steps") or [])
            if install_steps:
                lines.append("")
                lines.append("Install steps:")
                for step in install_steps[:6]:
                    lines.append(f"- {step}")
            verify_steps = list(item.get("verify_steps") or [])
            if verify_steps:
                lines.append("")
                lines.append("Verify:")
                for step in verify_steps[:5]:
                    lines.append(f"- {step}")
            rollback_steps = list(item.get("rollback_steps") or [])
            if rollback_steps:
                lines.append("")
                lines.append("Rollback / escape hatch:")
                for step in rollback_steps[:4]:
                    lines.append(f"- {step}")
            lines.append("")

    if verification_gates:
        lines.append("## Verification gates")
        lines.append("")
        for item in verification_gates:
            title = item.get("title") or item.get("id") or "gate"
            lines.append(f"### {title}")
            summary = _first_text(item, "summary", "why", "description", "notes")
            if summary:
                lines.append(summary)
            checks = list(item.get("acceptance_checks") or item.get("checks") or [])
            if checks:
                lines.append("")
                lines.append("Acceptance checks:")
                for check in checks[:6]:
                    lines.append(f"- {check}")
            commands = list(item.get("commands") or [])
            if commands:
                lines.append("")
                lines.append("Commands:")
                for cmd in commands[:4]:
                    lines.append(f"- `{cmd}`")
            lines.append("")

    if implementation_waves:
        lines.append("## Implementation waves")
        lines.append("")
        for item in implementation_waves:
            title = item.get("title") or item.get("id") or "wave"
            order = item.get("order")
            if order is not None:
                lines.append(f"### Wave {order}: {title}")
            else:
                lines.append(f"### {title}")
            summary = _first_text(item, "objective", "summary", "why_now", "description", "notes")
            if summary:
                lines.append(summary)
            deliverables = list(item.get("deliverables") or [])
            if deliverables:
                lines.append("")
                lines.append("Deliverables:")
                for deliverable in deliverables[:5]:
                    lines.append(f"- {deliverable}")
            lines.append("")

    if reference_patterns:
        lines.append("## Borrowed product patterns")
        lines.append("")
        for item in reference_patterns:
            title = item.get("title") or item.get("id") or "pattern"
            summary = _first_text(item, "summary", "why", "description", "notes")
            if summary:
                lines.append(f"- **{title}** — {summary}")
            else:
                lines.append(f"- **{title}**")
        lines.append("")

    if session_capabilities:
        lines.append("## Current session fit")
        lines.append("")
        for capability in [
            "screen_capture",
            "text_injection",
            "pointer_injection",
            "global_hotkeys",
            "window_introspection",
            "input_capture",
        ]:
            item = session_capabilities.get(capability)
            if not isinstance(item, dict):
                continue
            status = str(item.get("status") or "unknown")
            recommended = str(item.get("recommended") or "")
            mechanisms = ", ".join(str(x) for x in (item.get("mechanisms") or [])[:4])
            lines.append(f"- **{capability}** — `{status}`; recommended: `{recommended or 'n/a'}`; mechanisms: {mechanisms or 'n/a'}")
        lines.append("")
        if session_issues:
            lines.append("### Session warnings")
            lines.append("")
            for item in session_issues[:8]:
                message = _first_text(item, "message", "summary", "why", "description")
                suggestion = _first_text(item, "suggestion", "response", "notes")
                if suggestion:
                    lines.append(f"- {message} — {suggestion}")
                else:
                    lines.append(f"- {message}")
            lines.append("")

    lines.append("## Suggested refresh commands")
    lines.append("")
    lines.append("```bash")
    lines.append("vhk doctor --json")
    lines.append("vhk validate . --json")
    lines.append("vhk plan-project . --json")
    lines.append("vhk gen-operator-pack . --force")
    lines.append("```")
    lines.append("")

    return "\n".join(line.rstrip() for line in lines).rstrip() + "\n"


def render_deployment_checklist(plan: dict[str, Any]) -> str:
    project = dict(plan.get("project") or {})
    setup_recipes = _trim_items(plan.get("setup_recipes"), limit=8)
    verification_gates = _trim_items(plan.get("verification_gates"), limit=6)
    implementation_waves = _trim_items(plan.get("implementation_waves"), limit=6)
    session_issues = list(plan.get("session_issues") or [])

    lines: list[str] = []
    lines.append(f"# VHK deployment checklist for {project.get('name') or 'project'}")
    lines.append("")
    lines.append("Generated by `vhk gen-operator-pack`. Treat this as the operator handoff for install, verify, and rollback review.")
    lines.append("")
    lines.append("## Baseline refresh")
    lines.append("")
    lines.append("- [ ] Run `vhk doctor --json` on the target session.")
    lines.append("- [ ] Run `vhk validate . --json` in the project root.")
    lines.append("- [ ] Run `vhk plan-project . --json` and review changed surfaces/gates.")
    if session_issues:
        lines.append(f"- [ ] Review {min(len(session_issues), 8)} session issue(s) captured in `docs/VHK_OPERATOR_PLAN.json`.")
    lines.append("")

    if implementation_waves:
        lines.append("## Delivery waves")
        lines.append("")
        for item in implementation_waves:
            title = item.get("title") or item.get("id") or "wave"
            order = item.get("order")
            objective = _first_text(item, "objective", "summary", "why_now", "description")
            label = f"Wave {order}: {title}" if order is not None else str(title)
            if objective:
                lines.append(f"- [ ] {label} — {objective}")
            else:
                lines.append(f"- [ ] {label}")
        lines.append("")

    if setup_recipes:
        lines.append("## Install and rollback recipes")
        lines.append("")
        for item in setup_recipes:
            title = item.get("title") or item.get("id") or "recipe"
            lines.append(f"### {title}")
            lines.append("")
            for step in list(item.get("install_steps") or [])[:8]:
                lines.append(f"- [ ] {step}")
            for step in list(item.get("verify_steps") or [])[:6]:
                lines.append(f"- [ ] Verify: {step}")
            for step in list(item.get("rollback_steps") or [])[:5]:
                lines.append(f"- [ ] Roll back / disable: {step}")
            generator_commands = list(item.get("generator_commands") or [])
            if generator_commands:
                for cmd in generator_commands[:4]:
                    lines.append(f"- [ ] Generate artifacts with `{cmd}`")
            lines.append("")

    if verification_gates:
        lines.append("## Shipping gates")
        lines.append("")
        for item in verification_gates:
            title = item.get("title") or item.get("id") or "gate"
            lines.append(f"### {title}")
            lines.append("")
            for check in list(item.get("acceptance_checks") or item.get("checks") or [])[:6]:
                lines.append(f"- [ ] {check}")
            for cmd in list(item.get("commands") or [])[:4]:
                lines.append(f"- [ ] Run `{cmd}`")
            fallback_paths = list(item.get("fallback_paths") or [])
            for path in fallback_paths[:4]:
                lines.append(f"- [ ] Fallback path documented: {path}")
            lines.append("")

    return "\n".join(line.rstrip() for line in lines).rstrip() + "\n"


def write_operator_pack(
    project_dir: Path,
    *,
    out_dir: Path | None = None,
    force: bool,
    guide: bool = True,
    checklist: bool = True,
    plan_json: bool = True,
    capability_usage: dict[str, list[dict[str, object]]] | None = None,
    capability_matrix: dict[str, object] | None = None,
    capability_issues: list[dict[str, object]] | None = None,
) -> dict[str, Path]:
    """Write planner-backed operator deployment artifacts for an existing project."""

    out_dir = (out_dir or (project_dir / "docs")).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    plan = build_operator_plan(
        project_dir,
        capability_usage=capability_usage,
        capability_matrix=capability_matrix,
        capability_issues=capability_issues,
    )

    written: dict[str, Path] = {}
    if plan_json:
        path = out_dir / "VHK_OPERATOR_PLAN.json"
        _write_if_allowed(path, json.dumps(plan, ensure_ascii=False, indent=2) + "\n", force=force)
        written["plan_json"] = path
    if guide:
        path = out_dir / "VHK_OPERATOR_GUIDE.md"
        _write_if_allowed(path, render_operator_guide(plan), force=force)
        written["guide"] = path
    if checklist:
        path = out_dir / "VHK_DEPLOYMENT_CHECKLIST.md"
        _write_if_allowed(path, render_deployment_checklist(plan), force=force)
        written["checklist"] = path
    return written
