#!/usr/bin/env python3
"""Rebuild instructions: rev0318 scoped SQLite is generated by build_rev0318.py from selected CSVs."""
print("Use /mnt/data/build_rev0318.py in the cloudtainer build log to rebuild cube/datacube-rev0318-emergency.sqlite")
