#!/usr/bin/env python3
"""Print the short operator packet for a scarce real FreeBSD host-proof run.

This is intentionally not a validator and not a proof source.  It is a
constant-bound runbook generator whose output tells an operator exactly what to
run on FreeBSD, what finite handoff files to bring back, and what default-mode
cloudtainer commands will reject simulations.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FREEBSD_TOOLS = ROOT / "tools" / "freebsd"
if str(FREEBSD_TOOLS) not in sys.path:
    sys.path.insert(0, str(FREEBSD_TOOLS))

import host_proof_contract as contract  # noqa: E402

IMPORT_STATUS_REPORTER_REL = contract.HOST_PROOF_IMPORT_STATUS_REPORTER_REL
SEALED_PREFLIGHT_REL = contract.HOST_PROOF_SEALED_HANDOFF_PREFLIGHT_REL
# literal filename retained for source-surface guard: report_removable_media_local_fallback_host_proof_imports.py
WORK_ORDER_STAGER_REL = contract.HOST_PROOF_WORK_ORDER_STAGER_REL
WORK_ORDER_VERIFIER_REL = contract.HOST_PROOF_WORK_ORDER_VERIFIER_REL
WORK_ORDER_REL = "validation/freebsd-real-host-proof-work-order/current"


def render(mode: str) -> str:
    required = ", ".join(sorted(contract.HANDOFF_REQUIRED_NAMES))
    optional = ", ".join(sorted(contract.HANDOFF_OPTIONAL_NAMES))
    lines: list[str] = []
    lines.append("# DeriveBSD FreeBSD real-host proof operator packet")
    lines.append("")
    lines.append("This handoff-first packet is generated by `tools/freebsd/print_real_host_proof_operator_packet.py`; cloudtainer import commands stay default-mode and do not expose checker-simulation flags.")
    lines.append("A refusal, failed receipt, or checker-only simulation is regression evidence, but not an importable `real-host-proof`.")
    lines.append("")
    lines.append(f"Generated for cube cut: `{contract.CURRENT_CUBE_CUT_VERSION}`")
    lines.append(f"Primary host target: `{contract.PRIMARY_FREEBSD_RELEASE}` / `kern.osreldate >= {contract.PRIMARY_FREEBSD_OSRELDATE_MINIMUM}` / `{contract.HOST_TARGET_PRIMARY_TIER}`")
    lines.append(f"Supported floor: `{contract.SUPPORTED_FREEBSD_RELEASE_FLOOR}` / `kern.osreldate >= {contract.MIN_FREEBSD_OSRELDATE}` / `{contract.HOST_TARGET_LEGACY_TIER}`")
    lines.append(f"Host target matrix: `{contract.HOST_TARGET_MATRIX_ID}` (`{contract.HOST_TARGET_TIER_POLICY}`); receipts must preserve `host_target_matrix_id` and `host_target_tier`.")
    lines.append(f"Default checked-in import root: `{contract.DEFAULT_IMPORT_ROOT_REL}`")
    lines.append(f"Proof status reporter: `{IMPORT_STATUS_REPORTER_REL}`")
    lines.append(f"real-host proof work order: `{WORK_ORDER_REL}` (refresh with `{WORK_ORDER_STAGER_REL} --replace`; verify with `{WORK_ORDER_VERIFIER_REL}` or `VERIFY_WORK_ORDER.sh`)")
    lines.append("")
    lines.append("## Goal")
    lines.append("")
    lines.append("Produce one finite FreeBSD handoff that can be copied back to the cloudtainer and imported without any checker-simulation, refusal, or failed-proof flags.")
    lines.append("")
    lines.append("## Preconditions on the FreeBSD host")
    lines.append("")
    lines.append("Run from the repository root on a real FreeBSD host. `PREFLIGHT_ON_FREEBSD.sh` verifies the copied work-order kit, then runs the root-required preflight either directly when uid 0 or through `sudo env PYTHON=...`; this fixes the collection/preflight split where `RUN_ON_FREEBSD.sh` could use sudo for collection but fail preflight as the invoking user. The preflight must observe FreeBSD, uid 0 at the actual preflight boundary, Capsicum feature sysctls enabled, `python3`, `cc`, `makefs`, `mdconfig`, `fstyp`, `mount`, `umount`, and `sha256` or `sha256sum` before media authority is used. A passed receipt records `host_target_tier`; `primary-production` is the desired target, while `supported-legacy-floor` is accepted only for the current supported 14.x floor because real host proof is scarce and must be labeled honestly. Do not collect new proof on the previous 14.3 floor; keep older 14.3 evidence historical.")
    lines.append("")
    lines.append("## Concrete work order")
    lines.append("")
    lines.append(f"The checked-in real-host proof work order at `{WORK_ORDER_REL}` contains `PREFLIGHT_ON_FREEBSD.sh`, `RUN_ON_FREEBSD.sh`, `IMPORT_IN_CLOUDTAINER.sh`, `VERIFY_WORK_ORDER.sh`, and `real-host-proof-work-order.json`. It is generated by `{WORK_ORDER_STAGER_REL}` and verified by `{WORK_ORDER_VERIFIER_REL}`. The manifest binds the runnable work-order script digests plus repo proof-tool digests, so stale copied kits fail before scarce host time or returned proof is spent. The standalone preflight script can be run before collection and `RUN_ON_FREEBSD.sh` invokes it before the collector. The cloudtainer script runs sealed import preflight before publishing and passes `--reuse-existing-import`, so target-tier failures fail before writing an import and an interrupted rerun can verify/reuse the already-published matching sealed digest import. The sealed importer also holds an exclusive sibling import-root lock during publish/reuse/replace decisions, so two cloudtainer sessions cannot interleave scarce proof publication.")
    lines.append("")
    lines.append("```sh")
    lines.append(f"python3 -B -S {WORK_ORDER_STAGER_REL} {WORK_ORDER_REL} --replace")
    lines.append("sh validation/freebsd-real-host-proof-work-order/current/VERIFY_WORK_ORDER.sh /path/to/DeriveBSD validation/freebsd-real-host-proof-work-order/current")
    lines.append("sh validation/freebsd-real-host-proof-work-order/current/PREFLIGHT_ON_FREEBSD.sh /path/to/DeriveBSD")
    lines.append("sh validation/freebsd-real-host-proof-work-order/current/RUN_ON_FREEBSD.sh /path/to/DeriveBSD /tmp/derivebsd-host-proof-handoff derivebsd-freebsd-host-proof-handoff.zip")
    lines.append("sh validation/freebsd-real-host-proof-work-order/current/IMPORT_IN_CLOUDTAINER.sh /path/to/DeriveBSD derivebsd-freebsd-host-proof-handoff.zip")
    lines.append("```")
    lines.append("")
    lines.append("## Preferred cloudtainer handoff path")
    lines.append("")
    lines.append("```sh")
    lines.append("cd /path/to/DeriveBSD")
    lines.append("handoff_dir=${DERIVEBSD_HOST_PROOF_HANDOFF_DIR:-/tmp/derivebsd-host-proof-handoff.$(date -u +%Y%m%dT%H%M%SZ)}")
    lines.append("sudo env PYTHON=${PYTHON:-python3} \\")
    lines.append(f"  tools/freebsd/collect_removable_media_local_fallback_host_proof.sh \\")
    lines.append("  \"$handoff_dir/receipt.json\" \\")
    lines.append("  \"$handoff_dir/bundle.json\" \\")
    lines.append("  \"$handoff_dir\"")
    lines.append("archive=derivebsd-freebsd-host-proof-handoff.zip")
    lines.append(f"python3 -B -S {contract.HOST_PROOF_HANDOFF_SEALER_REL} \\")
    lines.append("  \"$handoff_dir\" --output \"$archive\"")
    lines.append("```")
    lines.append("")
    lines.append(f"Bring back either the handoff directory with exactly the required files `{required}` or the deterministic sealed handoff archive. `{optional}` is optional, but if it is present then `SHA256SUMS` must cover it too. Do not add loose notes, logs, screenshots, or renamed files to the handoff directory; the verifier and sealer reject loose files and path drift. Do not point the handoff directory or import root at symlinks; the collector and strict wrapper refuse those paths before host proof collection/import. Do not reuse a handoff directory unless the deliberate replacement environment is set. The collector also has a handoff overwrite guard: if `receipt.json`, `bundle.json`, `SHA256SUMS`, or `README.import.txt` already exists in the handoff directory, it refuses before FreeBSD preflight unless `{contract.HANDOFF_REPLACE_ENV}=1` is set for a deliberate replacement.")
    lines.append("The deterministic sealer rejects a symlinked handoff, copies the handoff through a finite nofollow staging snapshot before archive write, enforces finite size limits, writes canonical sorted stored ZIP members with exact regular-file mode metadata, and the unseal/import tail rejects noncanonical ZIP metadata before atomic publish and audit.")
    lines.append("")
    lines.append("## Cloudtainer import commands")
    lines.append("")
    lines.append("Use the sealed preflight first, then the sealed one-command importer when the handoff comes back as the deterministic archive:")
    lines.append("")
    lines.append("```sh")
    lines.append("python3 -B -S " + SEALED_PREFLIGHT_REL + ' \\')
    lines.append("  /path/to/derivebsd-freebsd-host-proof-handoff.zip \\")
    lines.append("  --import-root " + contract.DEFAULT_IMPORT_ROOT_REL + ' \\')
    lines.append("  --require-primary-target \\")
    lines.append("  --reuse-existing-import")
    lines.append("python3 -B -S " + contract.HOST_PROOF_SEALED_HANDOFF_IMPORTER_REL + ' \\')
    lines.append("  /path/to/derivebsd-freebsd-host-proof-handoff.zip \\")
    lines.append("  --import-root " + contract.DEFAULT_IMPORT_ROOT_REL + ' \\')
    lines.append("  --require-primary-target \\")
    lines.append("  --reuse-existing-import")
    lines.append(f"python3 -B -S {IMPORT_STATUS_REPORTER_REL} --json")
    lines.append(f"python3 -B -S {contract.HOST_PROOF_CHECKED_IMPORT_GATE_REL}")
    lines.append(f"python3 -B -S {contract.HOST_PROOF_THEATRE_GATE_REL}")
    lines.append("```")
    lines.append("")
    lines.append("If the sealed archive needs inspection before import, unseal it to a scratch handoff directory first:")
    lines.append("")
    lines.append("```sh")
    lines.append(f"python3 -B -S {contract.HOST_PROOF_HANDOFF_UNSEALER_REL} \\")
    lines.append("  /path/to/derivebsd-freebsd-host-proof-handoff.zip \\")
    lines.append("  --output-dir /path/to/handoff")
    lines.append("```")
    lines.append("")
    lines.append("If the handoff comes back as a loose directory already, skip unseal and point `/path/to/handoff` at that directory, then run the explicit verify/import/audit/report tail:")
    lines.append("")
    lines.append("```sh")
    lines.append("python3 -B -S tools/freebsd/verify_removable_media_local_fallback_host_proof_handoff.py /path/to/handoff")
    lines.append(f"python3 -B -S tools/freebsd/import_removable_media_local_fallback_host_proof_handoff.py /path/to/handoff --import-root {contract.DEFAULT_IMPORT_ROOT_REL}")
    lines.append(f"python3 -B -S tools/freebsd/audit_removable_media_local_fallback_host_proof_imports.py {contract.DEFAULT_IMPORT_ROOT_REL}")
    lines.append(f"python3 -B -S {IMPORT_STATUS_REPORTER_REL}")
    lines.append("```")
    lines.append("")
    lines.append("The preflight predicts the full copied-snapshot import identity without publishing; `--reuse-existing-import` is allowed only to verify and reuse an audit-clean matching sealed digest import during an operator retry. The importer itself serializes publish/reuse/replace behind an exclusive sibling import-root lock. Those commands run in default real-host-proof mode. They intentionally pass no non-proof allowance flags. The proof status reporter is observational: in this cloudtainer it should say `status=blocked-no-real-host-proof-import` and `proof_complete=false` until a primary-production real host proof has been imported. Use `--fail-if-incomplete` only when intentionally gating a proof-completion milestone.")
    lines.append("")
    lines.append("## Same-host one-command path")
    lines.append("")
    lines.append("Use this only when the FreeBSD host is the archive that will be returned or copied back as a whole.")
    lines.append("")
    lines.append("```sh")
    lines.append("cd /path/to/DeriveBSD")
    lines.append("run_receipt=validation/freebsd-host-proof-imports/collect-import-run.receipt.json")
    lines.append("sudo env PYTHON=${PYTHON:-python3} DERIVEBSD_KEEP_HOST_PROOF_HANDOFF=1 \\")
    lines.append(f"  tools/freebsd/collect_import_removable_media_local_fallback_host_proof.sh \\")
    lines.append(f'  --import-root {contract.DEFAULT_IMPORT_ROOT_REL} \\')
    lines.append("  --run-receipt \"$run_receipt\"")
    lines.append("python3 -B -S tools/freebsd/validate_collect_import_run_receipt.py \"$run_receipt\"")
    lines.append(f"python3 -B -S {IMPORT_STATUS_REPORTER_REL} --fail-if-incomplete")
    lines.append("```")
    lines.append("")
    lines.append("If a later stage fails after collection, preserve the handoff and rerun the strict resume path instead of collecting again:")
    lines.append("")
    lines.append("```sh")
    lines.append(f"tools/freebsd/collect_import_removable_media_local_fallback_host_proof.sh --resume-handoff /path/to/preserved/handoff --import-root {contract.DEFAULT_IMPORT_ROOT_REL} --run-receipt validation/freebsd-host-proof-imports/resume-run.receipt.json")
    lines.append("```")
    lines.append("")
    lines.append("## Refusal boundary")
    lines.append("")
    lines.append("A Linux cloudtainer refusal receipt, a checker-only success simulation, a failed receipt, or an empty import-root proof status is useful regression evidence, but it is not a real host proof and is not an importable `real-host-proof`.")
    lines.append("")
    lines.append(f"Last updated: {contract.CURRENT_CUBE_CUT_VERSION}")
    lines.append("")
    lines.append("Path rule: handoff, import-root, archive, unseal-output, and run-receipt paths must not be symlinks and must not pass through any existing symlink ancestor before host proof work.")
    lines.append("Seal rule: the deterministic sealer archives a verified nofollow copied staging snapshot with canonical sorted entries and exact regular-file mode metadata before transport.")
    if mode == "terse":
        terse_lines = [
            "# DeriveBSD FreeBSD real-host proof operator packet",
            "",
            f"Generated for cube cut: `{contract.CURRENT_CUBE_CUT_VERSION}`",
            f"Primary host target: `{contract.PRIMARY_FREEBSD_RELEASE}` / `kern.osreldate >= {contract.PRIMARY_FREEBSD_OSRELDATE_MINIMUM}` / `{contract.HOST_TARGET_PRIMARY_TIER}`",
            f"Supported floor: `{contract.SUPPORTED_FREEBSD_RELEASE_FLOOR}` / `kern.osreldate >= {contract.MIN_FREEBSD_OSRELDATE}` / `{contract.HOST_TARGET_LEGACY_TIER}`",
            f"Proof status reporter: `{IMPORT_STATUS_REPORTER_REL}`",
            f"real-host proof work order: `{WORK_ORDER_REL}`; verifier: `{WORK_ORDER_VERIFIER_REL}`; host preflight: `PREFLIGHT_ON_FREEBSD.sh`; sealed preflight: `{SEALED_PREFLIGHT_REL}`; import lock: `{contract.SEALED_IMPORT_LOCK_POLICY}`",
            "",
            "## Preferred cloudtainer handoff path",
            "",
            f"1. Refresh `{WORK_ORDER_REL}` with `{WORK_ORDER_STAGER_REL} --replace` if the cube changed, run `VERIFY_WORK_ORDER.sh` / `{WORK_ORDER_VERIFIER_REL}`, run `PREFLIGHT_ON_FREEBSD.sh` on the real host, then use `RUN_ON_FREEBSD.sh` and `IMPORT_IN_CLOUDTAINER.sh` for the scarce proof run.",
            "2. On FreeBSD, run the collector into a finite handoff directory.",
            "3. Seal it with the deterministic handoff sealer, which writes canonical sorted stored ZIP members from a verified copied staging snapshot, or bring back exactly `receipt.json`, `bundle.json`, and `SHA256SUMS`; if `README.import.txt` is present, make sure `SHA256SUMS` covers it too.",
            f"4. In the cloudtainer, run `{SEALED_PREFLIGHT_REL} --require-primary-target --reuse-existing-import` and `{contract.HOST_PROOF_SEALED_HANDOFF_IMPORTER_REL} --require-primary-target --reuse-existing-import`; otherwise unseal only for inspection, then verify/import/audit/report the handoff into `{contract.DEFAULT_IMPORT_ROOT_REL}` in default real-proof mode.",
            "5. Run the proof status reporter; `blocked-no-real-host-proof-import` means the cube still has no product proof.",
            "6. Do not add loose files, do not reuse a handoff directory with existing receipt/bundle files, do not use symlink handoff/import-root paths, and do not use non-proof allowance flags.",
        ]
        return "\n".join(terse_lines) + "\n"
    return "\n".join(lines) + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="print the real FreeBSD host-proof operator packet")
    parser.add_argument("--mode", choices=["full", "terse"], default="full", help="packet length")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    sys.stdout.write(render(args.mode))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
