function(iotox_validate_sanitizers)
    if(IOTOX_ENABLE_TSAN AND (IOTOX_ENABLE_ASAN OR IOTOX_ENABLE_UBSAN))
        message(FATAL_ERROR "ThreadSanitizer must be used separately from ASan/UBSan")
    endif()
endfunction()

function(iotox_enable_sanitizers target)
    if(MSVC)
        return()
    endif()

    set(sanitizers "")
    if(IOTOX_ENABLE_ASAN)
        list(APPEND sanitizers "address")
    endif()
    if(IOTOX_ENABLE_UBSAN)
        list(APPEND sanitizers "undefined")
    endif()
    if(IOTOX_ENABLE_TSAN)
        list(APPEND sanitizers "thread")
    endif()

    if(sanitizers)
        list(JOIN sanitizers "," sanitizer_flags)
        target_compile_options(${target} PRIVATE -fno-omit-frame-pointer "-fsanitize=${sanitizer_flags}")
        target_link_options(${target} PRIVATE "-fsanitize=${sanitizer_flags}")
    endif()
endfunction()
